### ISSUE TITLE
Memory Leak in rails app with ruby 2.3.0 and Puma 2.15.3

### ISSUE THREAD

**Issue by ThomasCelen** [puma/puma#1000]
Hi all,

For some time I've been having a memory leak in my application. The current setup runs with Ruby 2.3.0, Rails 4.2 and Puma Webserver puma 2.15.3 It is recommended by Heroku to use Puma, however a lot of debugging has lead me to believe it's actual Puma Webserver which is the cause of all the troubles. During debugging I've removed most of the gems, code etc but the issue kept showing up, RAM Memory increasing until an out of memory showed up. This is why I'm 99,999% sure the leak isn't from my application. Next I installed "Thin" Webserver on my Development system and also this was not a solution. Then I also upgraded my ruby version to 2.3.0 and the leak was immediately solved, RAM usage stayed ok.

Due to this evolution, I upgraded my production system to Ruby 2.3.0 (thinking it was only a ruby version issue) but still I'm having the memory leak. I'm now at the point that it seems to be a combination of my Puma Webserver, together with Ruby 2.3.0...

Does anyone of you have any experience with Puma giving memory leaks with Ruby 2.3.0.

Thanks in advance,
T

**UPDATE:**
my puma.rb
```
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end
```

**Comment by evanphx** [comment]
Is there a way you can replicate the issue for me? There are 2 ways: either
provide me an app that leaks in a repo for me to run, or show that the
hello.ru trivial rack app leaks.

**Comment by ThomasCelen** [comment]
Hi, I added you to a test repository. It's an older version where ruby isn't yet upgraded to 2.3.0 but besides that it's unfortunately also leaking...

**Comment by ThomasCelen** [comment]
hi @evanphx , have you been able to spot any issue yet?
Many thanks for your help!

**Comment by ThomasCelen** [comment]
hi @evanphx , can you please share if you already looked into my issue? If not I will attempt Unicorn webserver as I'm really convinced it's Puma.. The only thing I'm doubtful of is that some library is loaded incorrectly and causes the memory leak.

Cheers,
T

**Comment by codehotter** [comment]
Hi Thomas. Is it a private repository? Are you able to produce a minimal app that still leaks and share it publicly in this issue?

**Comment by evanphx** [comment]
@ThomasCelen Sorry for the delay. I don't see the repository... Where is it?

**Comment by ThomasCelen** [comment]
@evanphx I added you as a collaborator, https://github.com/ThomasCelen/FR_test/invitations

**Comment by ThomasCelen** [comment]
@codehotter and @evanphx  I added you both as collaborators to my test repository.. https://github.com/ThomasCelen/test_app/invitations
Can you please help me find the issue? I've been tracking this for months and the only thing I can figure is that, unfortunately, it's a Puma issue in combination with Ruby.

**Comment by evanphx** [comment]
@ThomasCelen Do you have any steps to reproduce the issue?

**Comment by ThomasCelen** [comment]
@evanphx just running the app will already trigger the leak actually so it's not difficult to replicate..

**Comment by evanphx** [comment]
@ThomasCelen Just leave it idle? Do I need to send it request? To what URLs?

**Comment by ThomasCelen** [comment]
@evanphx  Indeed, just "rails s" to boot the application, run localhost:3000 (don't think there are any big DB migrations that are needed") and then the app automatically starts increasing RAM.. I've been tracking it with "puma worker killer", though I've never been able to trace the source.

**Comment by evanphx** [comment]
@ThomasCelen Alrighty, I'm looking now.

**Comment by evanphx** [comment]
@ThomasCelen I'm still looking at the issue, but in the mean time, can you disable preload and move your puma_worker_killer out of the initializer and into the puma config file detailed here: https://github.com/schneems/puma_worker_killer

**Comment by evanphx** [comment]
@ThomasCelen do you have any stats/graphs of the memory usage you're seeing? I've running some tests and I do see it increase in small amounts but it appears to drop back down once a GC is done.

**Comment by evanphx** [comment]
For example:
```
[90336] PumaWorkerKiller: Consuming 169.87890625 mb with master and 2 workers
T_OBJECT=18 T_STRING=194 T_ARRAY=120 T_HASH=12 T_DATA=68 T_IMEMO=30 
[90336] PumaWorkerKiller: Consuming 169.8828125 mb with master and 2 workers
T_OBJECT=9 T_STRING=109 T_ARRAY=63 T_HASH=7 T_DATA=34 T_IMEMO=15 
[90336] PumaWorkerKiller: Consuming 169.94921875 mb with master and 2 workers
T_OBJECT=9 T_STRING=109 T_ARRAY=63 T_HASH=7 T_DATA=34 T_IMEMO=15 
[90336] PumaWorkerKiller: Consuming 152.5703125 mb with master and 2 workers
[90336] PumaWorkerKiller: Consuming 135.046875 mb with master and 2 workers
T_OBJECT=18 T_STRING=194 T_ARRAY=120 T_HASH=12 T_DATA=68 T_IMEMO=30 
[90336] PumaWorkerKiller: Consuming 135.08203125 mb with master and 2 workers
T_OBJECT=9 T_STRING=109 T_ARRAY=63 T_HASH=7 T_DATA=34 T_IMEMO=15 
[90336] PumaWorkerKiller: Consuming 127.75390625 mb with master and 2 workers
```

**Comment by evanphx** [comment]
@schneems he is running `PumaWorkerKiller` from `config/initializers` with preload on. Pretty sure that should absolutely NOT be done, correct?

**Comment by ThomasCelen** [comment]
@evanphx I'll run my test environment for a while without Puma_Auto_tune so that I can show you a screenshot of my memory usage. Thanks already for your checks.

**Comment by ThomasCelen** [comment]
<img width="1223" alt="screen shot 2016-06-30 at 16 46 17" src="https://cloud.githubusercontent.com/assets/9250287/16492492/4de09916-3ee2-11e6-8a6c-203324dd7420.png">
@evanphx This is a screenshot from 24hrs ago. Please know that Puma_Worker_killer is still turned on here. During the time frame of the screenshot there was very little traffic on the app.

**Comment by jjb** [comment]
@ThomasCelen that looks like pretty typical behavior of a rails app

the thrashing around and then slow growth could be from a lot of things

to get a more focused look at the "real" memory growth, try this:

* set the worker count to 1 (you may of course need to scale the # of dynos accordingly)
* `heroku config:set RUBY_GC_HEAP_GROWTH_FACTOR=1.10` (reference: https://devcenter.heroku.com/articles/ruby-memory-use#gc-tuning)

leave that running for a day or two, the graph should be more informative.

and may as well update to ruby 2.3.1, if possible.

**Comment by jjb** [comment]
(and also perhaps remove PumaWorkerKiller)

**Comment by evanphx** [comment]
@ThomasCelen Please update to 2.3.1 and see what the memory looks like there. There are definitely slow memory growth issues with older versions of ruby and they should be corrected in 2.3.

**Comment by TomLiu** [comment]
@ThomasCelen have you found out what the problem is?

**Comment by ce07c3** [comment]
@ThomasCelen I'm seeing this (Puma, Rails 2.3.1):

<img width="627" alt="screen shot 2016-10-20 at 15 46 51" src="https://cloud.githubusercontent.com/assets/6344545/19562397/76bd9f6c-96dc-11e6-8080-a48472b5c136.png">

Pretty similar to your memory growth between 1AM and 4AM, occurring once an hour. What could this be? Using New Relic, I was able to see that it coincides with Ruby GC runs:

<img width="1045" alt="screen shot 2016-10-20 at 13 45 58" src="https://cloud.githubusercontent.com/assets/6344545/19562255/ea8ed56a-96db-11e6-92a3-b8912a8d0994.png">

@evanphx could this be related to a GC memory leak?

**Comment by schneems** [comment]
That looks like normal growth

**Comment by ce07c3** [comment]
@schneems the same growth happens on idle dynos. 

Why do the large memory jumps cooincide with the GC spiking? I have no recurring tasks, no "unusual calls" once an hour either.

**Comment by ce07c3** [comment]
And most importantly, shouldn't the GC reduce memory? I am open for suggestions on what to do; profiling, benchmarking, ....

**Comment by schneems** [comment]
Here's a primer http://www.schneems.com/2015/05/11/how-ruby-uses-memory.html

No, GC should not reduce memory. Up to Ruby 2.3 it will not free aggressively, or not enough to matter for most apps. It also takes a larger memory overhead before it would start to reclaim memory. There is a GC setting for 2.4 that can be set, but it won't impact this use case.

Even if the app isn't doing any thing there are still event loops that create objects and do things like set timeouts, wait for incoming requests, etc. Not just from puma but other places in your code or libraries can run loops in new threads.

Your seeing memory grow and then level off. It's totally normal.

**Comment by ce07c3** [comment]
Thanks! Will read up on it.

**Comment by ce07c3** [comment]
Thanks a bunch, will read up on it.

21 okt. 2016 kl. 17:11 skrev Richard Schneeman <notifications@github.com>:

Here's a primer http://www.schneems.com/2015/05/11/how-ruby-uses-memory.html

No, GC should not reduce memory. Up to Ruby 2.3 it will not free aggressively, or not enough to matter for most apps. It also takes a larger memory overhead before it would start to reclaim memory. There is a GC setting for 2.4 that can be set, but it won't impact this use case.

Even if the app isn't doing any thing there are still event loops that create objects and do things like set timeouts, wait for incoming requests, etc. Not just from puma but other places in your code or libraries can run loops in new threads.

Your seeing memory grow and then level off. It's totally normal.

**Comment by nateberkopec** [comment]
@ThomasCelen's graph looks normal to me. 

@ce07c3 - do you have some "RUBY_" environment variables set? Your graph shows you have no free heap slots, which is abnormal. I'm guessing you have some GC variables tuned to incorrect values, probably `RUBY_GC_HEAP_GROWTH_FACTOR`.
