### ISSUE TITLE
Outgoing TCP Socket writing to other service hangs

### ISSUE THREAD

**Issue by sgringwe** [puma/puma#1005]
I have a web application which we are currently transitioning to puma from unicorn. Everything works fine, except for outgoing ldap requests using the ruby-net-ldap gem.

In unicorn, all is fine and the requests to ldap take around 2s max. With puma, however, it seems to always take up to the timeout in seconds, but still work fine. For example, if I set a ldap bind timeout of 5 seconds it will take exactly 5 seconds and continue on like normal.

The relevant code is:

```
def self.connect_to_socket(host, port, timeout = nil)
      addr = Socket.getaddrinfo(host, nil)
      sock = Socket.new(Socket.const_get(addr[0][0]), Socket::SOCK_STREAM, 0)

      if timeout
        secs = Integer(timeout)
        usecs = Integer((timeout - secs) * 1_000_000)
        optval = [secs, usecs].pack("l_2")
        sock.setsockopt Socket::SOL_SOCKET, Socket::SO_RCVTIMEO, optval
        sock.setsockopt Socket::SOL_SOCKET, Socket::SO_SNDTIMEO, optval
      end

      begin
        puts "[LDAP] [#{Time.now}] (Initial) connect where timeout is #{timeout}"
        if ENV['LDAP_FORCE_BLOCKING_SOCKET'] != 'true'
          sock.connect_nonblock(Socket.pack_sockaddr_in(port, addr[0][3]))
        else
          sock.connect(Socket.pack_sockaddr_in(port, addr[0][3]))
          puts "[LDAP] [#{Time.now}] (Initial) Normal connect is finished"
        end
      rescue Errno::EINPROGRESS
        puts "[LDAP] [#{Time.now}] (Initial) Rescued from Errno::EINPROGRESS"
        if IO.select(nil, [sock], nil, timeout).nil?
          sock.close rescue nil
          raise Errno::ETIMEDOUT, "TCP Socket connection timeout"
        end
        puts "[LDAP] [#{Time.now}] (Initial) Nonblocking connect is finished"
      end

      sock
    end
```

It will print `"[LDAP] [#{Time.now}] (Initial) Rescued from Errno::EINPROGRESS"` and then always wait 5 seconds before printing `"[LDAP] [#{Time.now}] (Initial) Nonblocking connect is finished"`.

Again - with unicorn, fine. I've spent the past week trying to debug this and cannot figure out why it's hanging on the `IO.select` call. Has this been seen before on other apps running puma?

Ldap gem and relevant file (the code above is a slight modification of current rubygems.org gem, which had the same issue on the `Socket.tcp` call) https://github.com/ruby-ldap/ruby-net-ldap and https://github.com/ruby-ldap/ruby-net-ldap/blob/master/lib/net/ldap/connection.rb

This is on ruby 2.3.0p0 MRI

**Comment by evanphx** [comment]
Could it be because you're passing the socket in the write position for `IO.select`? Seems like doing `IO.select([sock], nil, nil, timeout}` is what you want, which will detect if the socket is ready for read, which is what connection signals generally.

**Comment by sgringwe** [comment]
Thanks @evanphx . I had previously lightly tried that, but ended up getting lots of actual timeouts. I will try it again though, thanks for the response.

**Comment by sgringwe** [comment]
@evanphx FWIW, I did try that and the library did not work. It's unclear to me if that's because LDAP protocool does not work that way or another reason. For now, I'm searching for alternative solutions.

**Comment by evanphx** [comment]
@sgringwe Ok. I'm at a loss what is going on. Are you sharing the connection across threads accidentally maybe?

**Comment by sgringwe** [comment]
@evanphx I don't believe so, since in almost all cases there is only one authentication going on at a time. For now I'll close this and will re-open if I have further information.
