### ISSUE TITLE
Difference between Puma threaded and Puma clustered with 1 worker

### ISSUE THREAD

**Issue by VladFarion** [puma/puma#1006]
Hello, Puma team.

Thanks for awesome project you made. It's really great.

Can you clarify to me is there any difference between using Puma in threaded mode and Puma in clustered mode with a single worker and the same amount of threads? What is better in terms of memory consumption and response time?

Thank you in demand.

**Comment by evanphx** [comment]
There is really no difference. The features that require cluster mode (phased-upgrade) require multiple workers to work, so it's really unnecessary.
