### ISSUE TITLE
Puma not up to the mark with respect to Unicorn

### ISSUE THREAD

**Issue by brahamshakti** [puma/puma#1008]
Hi I have puma.rb which look exactly like

    directory '/home/rubyist/applications/current/MyApp'
    rackup "/home/rubyist/applications/current/MyApp/config.ru"
    environment 'production'

    pidfile "/home/rubyist/applications/shared/tmp/pids/puma.pid"
    state_path "/home/rubyist/applications/shared/tmp/pids/puma.state"
    stdout_redirect '/home/rubyist/applications/shared/log/puma_access.log',     /home/rubyist/applications/shared/log/puma_error.log', true

    threads 0,5

    bind 'unix:/tmp/sockets/puma.sock'

    workers 3

    preload_app!

    on_restart do
      puts 'Refreshing Gemfile'
      ENV["BUNDLE_GEMFILE"] = "/home/rubyist/applications/current/Gemfile"
    end

    before_fork do
      ActiveRecord::Base.connection_pool.disconnect!
    end

    on_worker_boot do
      ActiveSupport.on_load(:active_record) do
        ActiveRecord::Base.establish_connection
      end
    end

and my nginx conf file is like

    upstream puma_MyApp_production { 
      server unix:/tmp/sockets/puma.sock fail_timeout=0;
    }
    server {

      listen 80;
      client_max_body_size 4G;
      keepalive_timeout 10;

      error_page 500 502 504 /500.html;
      error_page 503 @503;

      server_name production.myapp.in;
      root /home/rubyist/applications/current/MyApp/public;
      try_files $uri/index.html $uri @puma_MyApp_production;

      location @puma_MyApp_production {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
       proxy_redirect off;
       proxy_pass http://puma_MyApp_production;
       # limit_req zone=one;
       access_log /home/rubyist/applications/shared/log/nginx.access.log;
       error_log /home/rubyist/applications/shared/log/nginx.error.log;
      }
    }

and I am still getting these errors

>  upstream prematurely closed connection while reading response header from upstream
>  upstream timed out (110: Connection timed out) while reading response header from upstream
>  failed (104: Connection reset by peer) while reading response header from upstream.
>  502 Badgateway

Some time request fulfilled but some time I get this response. Do you guys have any idea what wrong with these configuration. 

I shifted from unicorn to puma thinking that it will handle 2000 request with a ramp time of 20 sec. Unicorn was handling around 1500 request in 20 sec ramp period but with puma it is limited to only 500 request and all I get above errors. 

Please do provide some light on this behavior of  puma w.r.t unicorn and why puma is not up to the mark in handling request. My system is 2 core cpu with 8 GB ram centos server/

**Comment by evanphx** [comment]
Are you getting any errors on the app side? Those errors are just on the nginx side indicating that there was an issue talking to puma.

**Comment by brahamshakti** [comment]
What could be the reason for such error like if my nginx conf file is right, my puma.rb file is right then what else I can check. Means I randomly getting 502 bad gateway and above error. If this is the nginx error then what should I add in nginx file so that it can work correctly with puma. 

Any suggestion to resolve this issue?

**Comment by evanphx** [comment]
Does the ruby app show any errors?

**Comment by brahamshakti** [comment]
Are you talking about ruby code so to be honest my ruby app is not showing any error but my method has so many iterations apart from 20 mysql queries, May be that could be the reason why puma could not handled those thousands request which is coming to nginx in time ramp of 20 seconds

But still, Is my configuration is not right or am I doing something wrong.

**Comment by brahamshakti** [comment]
Are you talking about ruby code so to be honest my ruby app is not showing any error but my method has so many iterations apart from 20 mysql queries, May be that could be the reason why puma could not handled those thousands request which is coming to nginx in time ramp of 20 seconds

But still, Is my configuration is not right or am I doing something wrong.

**Comment by evanphx** [comment]
I'm not sure what is going on here. Basically if nginx is reporting a 502, I'd expect the puma side to also be showing some kind of error. Are the workers getting restarted or killed is some way maybe? Are there OOM entries in the system logs?

**Comment by evanphx** [comment]
If this is still ongoing, please reopen.
