### ISSUE TITLE
SystemStackError Being Ignored

### ISSUE THREAD

**Issue by mneumark** [puma/puma#1010]
I accidentally introduced an infinite loop in my app yesterday, and ran into an issue where nginx returned a 502 and puma was completely silent. I finally confirmed it was getting to puma and the rest of my app and spent an entire day digging through my code to see where the `SystemStackError` was getting rescued and ignored.

Finally I narrowed it down to [line 117 of lib/puma/thread_pool.rb](https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb#L117). It just rescues `Exception` and does nothing with it. It isn't even spitting out the error.

This lead to a huge hassle in debugging. Is there something I didn't set up right? Or is this genuinely a bug? (Using the latest version of Grape, Ruby 2.2.3, Rack 1.6.2, on Mac OS X 10.11 if that helps).

**Comment by evanphx** [comment]
Sorry about that! I'm going to have a message sent to STDERR when that happens now so hopefully that would help you.
