### ISSUE TITLE
How to pass Java options to Puma server?

### ISSUE THREAD

**Issue by oss92** [puma/puma#1013]
I have a Rails application running on `jruby-9.0.4.0` and using Puma as the web server.

I am trying to increase the memory limit of `puma`; the current flags are `-Xmx500m -Xss2048k`. I added `_JAVA_OPTIONS=-Xss4096k -Xmx2048m` to my `env` and all the `jruby` processes use it like `rake assets:precompile` for example but the `puma` instance itself does not.

**Part of capistrano trace**

    DEBUG [0aec947c] Command: cd 
    /dummy/production/releases/20160707071111 && ( 
    export RBENV_ROOT="/usr/local/rbenv" RBENV_VERSION="jruby-9.0.4.0" 
    RAILS_ENV="production" ; /usr/local/rbenv/bin/rbenv exec bundle exec 
    rake assets:precompile )

    DEBUG [0aec947c] 	Picked up _JAVA_OPTIONS: -Xss4096k -Xmx2048m

**config/puma.rb**

    # Min and Max threads per worker
    threads 8, 512

    # Default to production
    rails_env = ENV['RAILS_ENV'] || 'production'
    environment rails_env

    app_dir = "/dummy/#{rails_env}/current"

    # Set up socket location
    bind "tcp://localhost:3000"

    # Logging
    stdout_redirect "#{app_dir}/log/puma.stdout.log", "#{app_dir}/log/puma.stderr.log", true

    # Set master PID and state locations
    pidfile "#{app_dir}/pids/puma.pid"
    state_path "#{app_dir}/pids/puma.state"
    activate_control_app

Machine is an 8-core with 24GB of RAM.

How can I let the `puma` instance also pick up the `Java` options?

**Comment by marc** [comment]
Have you tried adding the Java parameters as `JAVA_OPTS`? That should work.

**Comment by evanphx** [comment]
Yes, you use whatever jruby env vars exist for this (pretty sure it's `JAVA_OPTS`).
