### ISSUE TITLE
Access the server from other device

### ISSUE THREAD

**Issue by walidvb** [puma/puma#1020]
I'm trying to access my server from another device by visiting my IP address, but the server is not responding. This is probably related to https://github.com/puma/puma/issues/782 , but i can't find a way to fix this.

Any hints welcome, thanks! :)

**Comment by jrafanie** [comment]
@walidvb Can you try 3.5.0, released today?

9b1de100044a45a810927c1da0ca3a4dea413890 is supposed to fix #782 and is included in 3.5.0

**Comment by walidvb** [comment]
@jrafanie apologies, should have mentioned that i am using 3.5.0 indeed. Was a coincidence the issue came the same day as the upgrade, but that happened on both 3.4 and 3.5.0

**Comment by jrafanie** [comment]
@walidvb 3.5.2 was shipped yesterday with https://github.com/puma/puma/commit/84fdc1bb14b72856a3dac40db1a43a560435706b, I'm not sure if this helps.

If you want to bind to different address, maybe bind [(-b)](https://github.com/puma/puma/blob/c2d1577feae2aa0c351a1dc1fe6e679bd900541b/README.md#binding-tcp--sockets) is what you want?

**Comment by walidvb** [comment]
@jrafanie that version doesn't help, unfortunately. 

In all fairness, maybe this is out of the scope of this gem. However, why would a locally run server not listen to network calls? It's not an external address in the end, it is the address of the machine, no?

In my case, i'm using puma via rails, so i presume i'd need to config rails to bind the IP when starting puma.

**Comment by jrafanie** [comment]
Did you try binding to 0.0.0.0 via the rails s -b option? I think that's right. rails s --help to double check. It might bind to 127.0.0.1 by default.

**Comment by jrafanie** [comment]
Note, 0.0.0.0 is not very secure and will raise flags in government security audits.

**Comment by jrafanie** [comment]
A firewall could also be dropping requests on the rails server machine.

**Comment by evanphx** [comment]
Basically, either use `-b 0.0.0.0` or have something figure out the IP of the interface that you want to listen and pass that. Most people do the former.
