### ISSUE TITLE
Puma start issue on Ruby on Windows using Cygwin bash

### ISSUE THREAD

**Issue by fera2k** [puma/puma#1023]
When you have a **Windows** environment with **Cygwin** set, and you try to start a Rails 5 app, with "rails s", which uses Puma by default, I had this exception:

`C:/Ruby22/lib/ruby/gems/2.2.0/gems/puma-3.5.0/lib/puma/launcher.rb:323:in \'stat': No such file or directory @ rb_file_s_stat - /c/Projects/test1 (Errno::ENOENT)`

Looking inside the code, on **launcher.rb,** line 321, it tries to get the current dir using **ENV['PWD']**, but **Cygwin** returns something like this: '/c/foldername' which is not ok for Ruby on Windows (version 2.2 x86 installed from RubyInstaller.org).

So, I've monkey patched the code, changing **ENV['PWD']** for **Dir.pwd** ruby command, and now it runs fine.

**Comment by evanphx** [comment]
Strange that `ENV["PWD"]` doesn't work there. I'll use `Dir.pwd` on cgywin.

**Comment by fera2k** [comment]
Thanks for the fix. Working fine!

**Comment by evanphx** [comment]
@fera2k My pleasure!

**Comment by carlos-ssh** [comment]
I had the same issue but i saw that i has different directory and i can't run the server. Please check if you have the same issue than me watching your directory on the command line using "pwd".
