### ISSUE TITLE
How to specify no worker timeout?

### ISSUE THREAD

**Issue by banister** [puma/puma#1024]
I'm using puma in development as well as production, and during *development* it's useful not to have a worker timeout at all as i have a debugging console started inside the request. How do i tell puma never to timeout a worker?

**Comment by evanphx** [comment]
You can set `worker_timeout` to some comically large value, say 1,000,000,000 and that should do the trick.

**Comment by banister** [comment]
Thanks homie

**Comment by evanphx** [comment]
@banister My pleasure.
