### ISSUE TITLE
Socket leak

### ISSUE THREAD

**Issue by collimarco** [puma/puma#1026]
Yesterday I switched to Puma in production. It uses the default configuration with 0-16 threads. In puma config file I don't close any connection explicitly, but I don't think it's necessary since I am not in cluster mode.

This morning the server is down and every second this error message gets written to the Puma error log:

LogStashLogger::Device::UDP - Errno::EMFILE - Too many open files - socket(2) - udp

I had never seen this error when  I used Passenger. I don't know if it is the gem itself, or the gem just cannot open the connection because another component has exhausted the connections.

The fact is that using `lsof` I see a constantly increasing number of unix sockets opened by Puma. The puma error log [looks like this](https://gist.github.com/collimarco/adcb2ec45d86c37a20560b942b3058bb#file-puma-error-log) initially and ~~probably~~ after some time just outputs " Errno::EMFILE - Too many open files", while the [lsof output is this](https://gist.github.com/collimarco/adcb2ec45d86c37a20560b942b3058bb#file-lsof-txt).

My puma config file is simply this:

```
path = File.expand_path('../../..', __FILE__)
environment 'production'
pidfile "#{path}/tmp/pids/puma.pid"
stdout_redirect "#{path}/log/puma.log", "#{path}/log/puma-error.log"
bind "unix://#{path}/tmp/sockets/puma.sock"
```

**Comment by collimarco** [comment]
At the moment is an hour that I have disabled the `LogStashLogger` gem and Puma seems to work.

My guess (it's just a guess) is that if an exception is raised by the gem and propagates up to Puma, it will try to start the application again, thus creating the same error again and again until the socket limit is reached. However I think that Puma isn't managing that situation properly: Puma shouldn't create that many puma.sock (until it eventually reaches the limit).

**Comment by evanphx** [comment]
Sounds more like that gem is creating sockets and not cleaning them up. How
are you using that gem?

**Comment by evanphx** [comment]
Looking at the lsof dump from the other issue, that is pretty odd. Did you restart puma a bunch of times? How long was it running? The sockets there could easily be client sockets connected from nginx as well, how many worker_connections did you configure in the nginx config?

**Comment by collimarco** [comment]
> Sounds more like that gem is creating sockets and not cleaning them up.

The gem owner said that the bug was like this: when an exception raised inside the gem, the gem would catch it and retry without closing the socket (which thus was leaked). So based on what he said the exception did never propagate to Puma: the thread was stuck on a try / catch loop.

> Did you restart puma a bunch of times?

No, not with hot restarts or things like that: at most I could have restarted the whole service (but that would mean a different process/PID and thus lsof wouldn't have listed those sockets if they were opened by a previous Puma process).

> How long was it running?

In that case it was running for **less than an hour**. 

> how many worker_connections did you configure in the nginx config?

I have never changed that setting, so it should be the default (512).


If it's like TCP sockets where for each connection you open a new socket it can be happened as follows:

- open the first socket and process the first request
- an exception occurs inside the gem
- the thread gets stuck
- nginx has to open a new connection (and the previous one i still there...) 
- the new request is processed and a second thread get suck
- ...
- all 16 threads get suck
- nginx still tries to open new connections for the incoming requests...
- and thus Puma opens new sockets even if it hasn't any thread left to process them

Probably the scenario is slightly more complex since I also have rack-timeout installed which at some point should have terminated the stuck requests (I don't know if it actually worked). However terminating the processing probably frees the thread but not the sockets (leaked by the LogStashLogger  gem).

It would be useful if Puma could **free all sockets opened by a thread every time it finishes the processing of a request** (I don't know if Ruby provides an easy way to detect the sockets opened by a given thread).

**Comment by evanphx** [comment]
Ah. So the other gem basically locked up all the Threads. Nginx kept sending in requests and puma was just queueing them internally, creating the proliferation of descriptors for `puma.socket`.

Perhaps puma needs to limit it's internal queueing in this case, so that if the threads are really locked up, it's not making the situation worse by continuing to accept connections. On the other hand, the situation is pretty dire it sounds like, it's unlikely those Threads were going to come back anyway and so even if puma was limiting it's internal queue, the process was probably dead.

Limiting the internal queueing would allow nginx to see that puma could no longer accept connections and deal with the situation (though not sure what that remediation would be either).

**Comment by evanphx** [comment]
There isn't a way to cleanup all the thread's sockets though the GC will do that anyway, closing sockets when they're garbage collected.

**Comment by evanphx** [comment]
I'm going to close this issue while I consider if/how puma should limit it's internal queueing.

**Comment by barbolo** [comment]
I'm using the Mechanize gem and I think I have a similar problem with leaking TCP Sockets.

Have anyone evolved this issue?
