### ISSUE TITLE
Puma does not handle SyntaxError properly

### ISSUE THREAD

**Issue by rosenfeld** [puma/puma#1027]
Please take a look at the responses for these two Rack apps. It seems Puma doesn't handle SyntaxError properly as it does for regular errors:

```ruby
# config.ru for regular error
run ->(env) { raise 'Error' }

# config.ru for SyntaxError
run ->(env) { require_relative 'abc' }

# abc.rb
class # invalid syntax
```

Would it be possible for Puma to fix the HTTP response in the latter case?

**Comment by jeremyevans** [comment]
Roda rescues both StandardError and ScriptError in its error handling plugin, it might be a good idea for Puma to do something similar.

**Comment by evanphx** [comment]
Fixed! Thanks for pointing it out, I agree (and thusly followed suit with the code change) that it should catch more exceptions here.

**Comment by rosenfeld** [comment]
Thanks! Any reasons for not simply rescue Exception?

**Comment by evanphx** [comment]
I've done that before though I'm generally against it because it also catches NoMemoryError, for which there is really no recovery and the process needs to just die.

Though, ThreadPool does rescue Exception so, actually, I should probably change it to Exception.

**Comment by rosenfeld** [comment]
I see, it makes sense. Even when no memory is available I believe it's a valid attempt trying to better handle the response. Thanks.
