### ISSUE TITLE
Jungle needs to have explicit systemd support

### ISSUE THREAD

**Issue by evanphx** [puma/puma#1029]
The init scripts don't work on many systemd releases now (see #999 for example). So we need to add system scripts for folks to use.

**Comment by t27duck** [comment]
This is a (sanitized) system service file I use for a Rails app if you'd like an example to go off of.

````
[Unit]
Description=My App Puma Server
Requires=redis.service postgresql-9.4.service
Wants=redis.service postgresql-9.4.service memcached.service
After=redis.service postgresql-9.4.service

[Service]
Type=simple
User=appuser
PIDFile=/path/to/my/app-puma.pid
WorkingDirectory=/path/to/my/app/current
Environment=RAILS_ENV=production
ExecStart=/path/to/my/app/current/bin/bundle exec puma -e production -C ./config/puma.rb config.ru
ExecReload=/bin/kill -s USR1 $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
Restart=always

[Install]
WantedBy=multi-user.target
````

**Comment by t27duck** [comment]
I should also note that I have `pidfile "/path/to/my/app-puma.pid"` set in my Puma configuration file to get puma to create a pid file for systemd to monitor and use.

**Comment by evanphx** [comment]
Does systemd need a pid file? If puma runs in the foreground it shouldn't be necessary, right?

**Comment by t27duck** [comment]
It technically doesn't, but it's handy to use to make `ExecReload` and `ExecStop` easier to implement.

**Comment by t27duck** [comment]
I suppose if you want the absolute minimum needed, this might do it:

````
[Unit]
Description=My App Puma Server

[Service]
Type=simple
User=appuser
WorkingDirectory=/path/to/my/app/current
ExecStart=/path/to/my/app/current/bin/bundle exec puma -e production -C ./config/puma.rb config.ru
Restart=always

[Install]
WantedBy=multi-user.target
````

Also, I just noticed that the docs directory in the puma repo has a section about systemd: https://github.com/puma/puma/blob/master/docs/systemd.md

Would that be a better starting point for you?

**Comment by evanphx** [comment]
@t27duck I did start that direction but wanted to get someone that has a production unit to at least weigh in.

**Comment by t27duck** [comment]
@evanphx - Gotcha. I've come from the land of unicorn and was used to working with Pids, Socks, and signal sending so I based my systemd file off of that pattern since puma supported it. I personally prefer the pid method as it makes it easier to track the master process.

**Comment by dekellum** [comment]
Sorry if what I authored in https://github.com/puma/puma/blob/master/docs/systemd.md is short of jungle, but the config described, including the socket activation and thus systemd managed "hot restart" is working well for me in production.  There is a usage component to the doc that I don't think would fit in jungle alone, but people might not be finding the doc?

@t27duck's unit is otherwise pretty similar.  I don't follow using SIGQUIT for ExecStop when the default SIGTERM is handled by puma as a graceful shutdown. Is QUIT for immediate shutdown?  Also not sure if rolling restart should be integrated by default in ExecReload (which would normally be for reloading config).  In general though I hope the recommend config is improved.

**Comment by evanphx** [comment]
@dekellum If you feel that the doc is fine (and it's fine by me), then I'll add docs to point people do it more readily.

**Comment by dekellum** [comment]
Oh, I might just be confused.  Previously I had thought part of /tools/jungle was some templates and generation of these other init-system scripts/config.  Looking again I see that isn't the case—its just the individual files with comments and then an overview README.  What I added to /docs/systemd.md could certainly be adopted to this same format, e.g. /tools/jungle/systemd with puma.service, puma.socket and remainder of the documentation in a README.md.

Given that the existing doc now ranks first here:

https://www.google.com/search?q=puma+systemd

I suggest that [/docs/systemd.md](https://github.com/puma/puma/blob/master/docs/systemd.md) be made a symlink if github gracefully handles that, or a "Moved to..." markdown link.

Also note the [Process Monitors](https://github.com/puma/puma/blob/master/README.md#process-monitors) section of toplevel README.md has a reference.

One others thing that might be found lacking in the puma.service as documented is lack of any particular support for RVM, rbenv, et al.   I don't use those in production myself, preferring a /usr/local/bin/ruby, as I don't like how these complicate this very scenario!   SystemD config isn't bash so its not as simple as a bash `source`. The bundler binstub (prefering WorkDirectory/sbin to avoid conflicts with /bin) approach seems nicer than `bundle exec --keep-file-descriptors.`  Do Bundler's binstubs play nice with RVM, etc.?  Or does RVM, etc. provide its own binstub mechanism that could be referenced here?

**Comment by bdewater** [comment]
I'm almost done migrating a CentOS 6 server to a fresh installation of CentOS 7 w/ systemd. Regarding RVM/rbenv I've run in to the issue that systemd runs commands in pristine environment, e.g. shell hooks from RVM/rbenv do not 'just work'.

A common workaround for this seems to be to spawn an interactive shell, e.g. `ExecStart=/bin/bash -lc 'bundle exec puma'` but that looks like a bit of a hack. A cleaner solution for RVM seems to be to [generate a wrapper](https://rvm.io/deployment/init-d) but I haven't tried it myself. rbenv recommends [setting PATH and using binstubs](https://github.com/rbenv/rbenv/wiki/Deploying-with-rbenv) but that didn't work for me (journalctl reports '/usr/bin/env: bash: No such file or directory'). 

I did get it to work by using rbenv [shims](https://github.com/rbenv/rbenv#understanding-shims) directly (example below is from a systemwide install so the directories are a bit different from default):
```
WorkingDirectory=/var/www/my_rails_app/current
ExecStart=/usr/local/rbenv/shims/bundle exec puma -C config/puma.rb
SyslogIdentifier=my_rails_app
```
The SyslogIdentifier bit ensures that `journalctl` output does not default to 'bundle'. Hope this helps!

**Comment by macarthy** [comment]
@bdewater nice SyslogIdentifier=my_rails_app tip. Thanks!

**Comment by ndrsv** [comment]
Using rvm (system install, no gemsets, set default ruby) the default wrapper works. For example:

`ExecStart=/usr/local/rvm/wrappers/default/bundle exec puma ...`

**Comment by daz** [comment]
What about multiple sites? Can anyone point me in the right direction?

**Comment by stiig** [comment]
@daz for multiple sites create systemd script for each site and it all

**Comment by dekellum** [comment]
In 17a81f2a (PR #1329) I added a link to /docs/systemd from the tools/jungle/README.md. Does that sufficiently satisfy the original issue expressed here: that people starting at /tools/jungle didn't know about /docs/systemd?  If so, close this?

**Comment by Dombo** [comment]
@daz my recommendation if you were to have multiple sites would be to look at the concept of [Instantiated Services](http://0pointer.de/blog/projects/instances.html) in SystemD.
