### ISSUE TITLE
Monitoring Puma with God

### ISSUE THREAD

**Issue by ankit-ricardokaka** [puma/puma#1030]
I am using god to monitor the processes. I want to monitor puma. The problem is it is giving me this error: 'ERROR: No application configured, nothing to run' on starting puma. Same command when i am using manually, puma is starting up successfully.
 
God configuration file for reference: 

`w.name = "puma"
w.interval = 60.seconds
w.start = "RAILS_ENV=staging bundle exec puma -C #{RAILS_ROOT}/config/puma.rb"

w.stop = "kill -s QUIT $(cat #{pid_file})"
w.restart = "kill -s HUP $(cat #{pid_file})"
w.start_grace = 20.seconds
w.restart_grace = 20.seconds
w.pid_file = pid_file
w.behavior(:clean_pid_file)`
 
I do not know what am i doing wrong. I could not find a puma community forum so asking it here.

**Comment by ankit-ricardokaka** [comment]
No problem with Puma. Instead of 
  w.start = "RAILS_ENV=staging bundle exec puma -C #{RAILS_ROOT}/config/puma.rb"
if you write this,
  w.start = "cd #{RAILS_ROOT} && RAILS_ENV=staging bundle exec puma -C #{RAILS_ROOT}/config/puma.rb" then it will start working.

**Comment by stereobooster** [comment]
You need to use `USR1` (or `USR2`) for restart.  `HUP` is for log rotation
