### ISSUE TITLE
initscript not stopping puma

### ISSUE THREAD

**Issue by giovdk21** [puma/puma#1037]
Hello,
I'm using the [init.d script](https://github.com/puma/puma/blob/master/tools/jungle/init.d/puma#L99) on ubuntu 16.04 with Rails 5

At the moment it is searching the pid and state files in:

```
PIDFILE=$1/tmp/puma/pid
STATEFILE=$1/tmp/puma/state
```

but I couldn't find anything on the documentation that mention this so I realised that the stop command wasn't working just because I saw the process still alive.

With Rails 5 I think it would default to $1/tmp/pids (using rake tmp:create) instead of  $1/tmp/puma but I'm not an expert with Rails and I know that Puma isn't just for rails, but it would be good to have some documentation mentioning this (sorry if I missed it).

thanks

**Comment by evanphx** [comment]
Those paths are set by a puma configuration, not used from the rails configuration. I'll agree though, the init scripts need some work and documentation. I'll add that to my todo list.
