### ISSUE TITLE
pumactl not found when using rbenv

### ISSUE THREAD

**Issue by giovdk21** [puma/puma#1038]
Hi,
using rbenv I get the following error message when stopping puma using the init.d script (ubuntu 16.04):

`/etc/init.d/puma: 111: /etc/init.d/puma: pumactl: not found`

Puma starts "the jungle" just fine using the list of paths provided in /etc/puma.conf even if they are using rbenv, but during the stop command ~/.rbenv/shims/ is not in the path and it looks like it is failing to enter the following [condition](https://github.com/puma/puma/blob/master/tools/jungle/init.d/puma#L109):

`if [ "$USE_LOCAL_BUNDLE" -eq 1 ]; then`

**Comment by evanphx** [comment]
It's probably run under the wrong user and without the rbenv bits loaded. You'll need to add the bits to load rbenv to the init scripts.

**Comment by giovdk21** [comment]
Hello,
what do you mean? As far as I understand, that script is ran by root and it should be able to identify which user should run rbenv by looking at the /etc/puma.conf file, correct?

At the moment it is working that way when you start the service, but not when you stop it.

**Comment by spotscale** [comment]
I have the same issue.

**Comment by jaybloke** [comment]
Also getting the same issue.

**Comment by giovdk21** [comment]
@evanphx hi,
I tried the latest version of the script and still getting this; could you please check my previous message and clarify on that? Did I misunderstand how it's meant to be used?

thanks
