### ISSUE TITLE
Stats should include actively serving threads

### ISSUE THREAD

**Issue by ebpitts** [puma/puma#1039]
From https://github.com/puma/puma/issues/811#issuecomment-195463421 

> Any chance of getting the control server to report the # of "actively serving threads"? It currently reports the count of spawned threads per worker, but not how many are serving a request.

**Comment by evanphx** [comment]
The number is highly volatile and requires additional mechanisms to have the the master and the workers communicate. I'll put this on the feature request bin.

**Comment by nateberkopec** [comment]
FWIW I think a "thread utilization" metric would be extremely useful for most people. I've seen lots of pumas with threadcounts that are waaaaay too high for their work.
