### ISSUE TITLE
Where do I put the environment variable?

### ISSUE THREAD

**Issue by edwinlunando** [puma/puma#1040]
Hi, I'm managing some puma app server in my server. How do I separate the environment variables?

Usually I put the env in the `.bashrc` file or `.env`. But, I think the puma upstart did not look these files? 

I'm using the upstart script.

**Comment by mwpastore** [comment]
There are a few ways to do it. If you're using [rbenv](https://github.com/rbenv/rbenv), for example, you can use the [rbenv-vars](https://github.com/rbenv/rbenv-vars) plugin and store your variables in a `.rbenv-vars` file in your application directory or any parent directory thereof. The upstart script that comes with Puma will automatically detect rbenv and load it before starting. I'm sure chruby and RVM have similar solutions. 

Upstart doesn't invoke the bashrc of the target user. It has nothing to do with Puma; it's just a bad default behavior for init systems. You can, however, manually source (dot in) a file with environment variables in your upstart script, e.g.:

```
script
. /path/to/your/environment
exec bundle exec puma -C config/puma.rb
end script
```

You'll need to update your upstart script to source this file. (Sorry, my upstart is a little rusty after learning systemd, so the above may not be 100% correct.)

Yet a third option is to use something like [dotenv](https://github.com/bkeepers/dotenv) and load the environment in your application. The hitch would be if you want to use these environment variables within your Puma configuration. It might be tricky to get the order of operations right.
