### ISSUE TITLE
Puma silent crash with nginx reverse proxy

### ISSUE THREAD

**Issue by CaptainStiggz** [puma/puma#1045]
Originally posted this issue on stackoverflow here: http://stackoverflow.com/questions/38848200/puma-silent-crash-with-nginx-reverse-proxy

I have a puma server running a ruby on rails app on an AWS EC2 instance. It was working fine for a while, but I found it responding with 502 errors a few hours later. The app is deployed with capistrano.

A simple restart of puma fixed the problem temporarily, but I want to prevent it happening again. Not quite sure what to try first.

Here's my capistrano puma config:

``` ruby
set :puma_rackup, -> { File.join(current_path, 'config.ru') }
set :puma_state, "#{shared_path}/tmp/pids/puma.state"
set :puma_pid, "#{shared_path}/tmp/pids/puma.pid"
set :puma_bind, "unix://#{shared_path}/tmp/sockets/puma.sock"
set :puma_conf, "#{shared_path}/puma.rb"
set :puma_access_log, "#{shared_path}/log/puma.error.log"
set :puma_error_log, "#{shared_path}/log/puma.access.log"
set :puma_role, :app
set :puma_env, fetch(:rack_env, fetch(:rails_env, 'production'))
set :puma_threads, [0, 8]
set :puma_workers, 0
set :puma_worker_timeout, nil
set :puma_init_active_record, true
set :puma_preload_app, false
set :bundle_gemfile, -> { release_path.join('Gemfile') }
``` 

Puma error log doesn't show any crashes.

Nginx error log shows (xx'd out client ip): 2016/08/09 06:25:52 [error] 1081#0: *348 connect() to unix:///home/deploy/myapp/shared/tmp/sockets/puma.sock failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: example.com, request: "POST /mypath HTTP/1.1", upstream: "http://unix:///home/deploy/myapp/shared/tmp/sockets/puma.sock:/mypath", host: "example.com"

**Comment by evanphx** [comment]
Do you have the stdout and stderr of puma available? Usually when this happens it's ruby crashing because of a bad C extension.

**Comment by wdrury** [comment]
I've had this happen too, several times over the last few days, running in development mode on an AWS instance running Ubuntu 14.04.4 where I simply started it with $ nohup rails server &

All I see in the logs, besides normal web activity, is what looks like an orderly shutdown, although I don't know what initiates it:

> - Gracefully stopping, waiting for requests to finish
> === puma shutdown: 2016-08-16 00:35:59 +0000 ===
> - Goodbye!
> Exiting

The only change to the environment is a bundle update I did a few days ago.  I could revert my Gemfile and re-install to see if that causes the random exits to stop.

**Comment by CaptainStiggz** [comment]
@evanphx As far as I can tell, all I have is puma.access.log and puma.error.log. Do I need to configure puma to send stdout and stderr to one of these logs?

I am using the gem 'mimemagic' https://github.com/minad/mimemagic which depends on the Ubuntu package 'libmagic' or 'libmagic-dev', I forget which one. Could be the bad extension.

**Comment by evanphx** [comment]
@wdrury That looks like puma is being told to quit. You might want to check for a bad log rotation script?

**Comment by evanphx** [comment]
@CaptainStiggz Can you paste in your config file?

**Comment by CaptainStiggz** [comment]
I assume we're talking about puma.rb created with initial rails configuration? 

```ruby
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum, this matches the default thread size of Active Record.
#
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }.to_i
threads threads_count, threads_count

# Specifies the `port` that Puma will listen on to receive requests, default is 3000.
#
port        ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked webserver processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
# workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory. If you use this option
# you need to make sure to reconnect any threads in the `on_worker_boot`
# block.
#
# preload_app!

# The code in the `on_worker_boot` will be called if you are using
# clustered mode by specifying a number of `workers`. After each worker
# process is booted this block will be run, if you are using `preload_app!`
# option you will want to use this block to reconnect to any threads
# or connections that may have been created at application boot, Ruby
# cannot share connections between processes.
#
# on_worker_boot do
#   ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
# end

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

**Comment by evanphx** [comment]
@CaptainStiggz Ok, thanks for the config. That all looks fine so my guess is you're getting a process crash due to a bad extension. Since you're in production, I'd suggest uncommenting the workers line and using at least 2 workers. That will at least shield you from the crashes a little because the other worker will be able to handle traffic while the crashed one is automatically restarted.

**Comment by CaptainStiggz** [comment]
@evanphx Sorry I forgot to respond. Good advice, thanks!

**Comment by Vipala** [comment]
I am facing the same issue. I increased the number of workers too. No luck can you please help me with this
