### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by kaihendry** [puma/puma#1050]
Is there a good canonical starting point for Dockerizing a Rails/Puma application?

Be good to see some pointers in the Documentation at least. Many thanks,

**Comment by evanphx** [comment]
We don't have any specific docs at the moment, but most folks get a good base image with their preferred ruby and just bundle install into it. There are probably some tutorials elsewhere.

**Comment by kaihendry** [comment]
Struggling to understand how puma is supposed to be deployed. Via a .sock to nginx, similar to php-fpm?
