### ISSUE TITLE
Fixed CommonName verify mode

### ISSUE THREAD

**Issue by mieko** [puma/puma#1057]
I need Puma's client certificate authentication to allow me to verify against a fixed Common Name (i.e., the inverse of Nginx's `proxy_ssl_name`, a model that's possible with stunnel and PostgreSQL that we've used to great success).  The idea is: I don't know what host front-end servers will spring up at, but with a pre-configured CA and a valid client certificate with a common name I expect, I'm fine with puma accepting it (and otherwise not).

I'll be implementing this over the next few days into Puma/MiniSSL, but I was wondering if this is something that'd be considered useful to Puma proper, or is it too special case to upstream.  (e.g., I'm wondering if I should structure it as a PR against Puma or a monkey-patching Gem).  If it's something that'd be useful in Puma, what would it need to look like to get merged?

The way I'm thinking about it now, it'd work something like `verify_mode=peer&verify_name=something`.  Also, I'm not familiar with JRuby (other than knowing it's awesome), but would MRI-only support be a blocking issue for getting something like this merged?

Thoughts?

**Comment by evanphx** [comment]
I'm totally willing to give it a look. If it's too specific, we could probably build some hooks in for you to be able to implement the logic properly.

**Comment by evanphx** [comment]
Being MRI only isn't a blocker, we'll just need to to add JRuby support before releasing.

**Comment by mieko** [comment]
Thanks, Evan.  I'll see what I can put together.

**Comment by MikaelSmith** [comment]
This is a problem I'm also looking at. I may be able to help finish the C and Java work.

I was originally looking at https://github.com/square/rails-auth, which gives a more complete authorization solution, but it requires that the certificate is passed through in the request header. Where do you fall on having multiple ways to handle authorization in the future?

**Comment by MikaelSmith** [comment]
If anyone's interested in an example, here's an excerpt of my puma config
```
require 'rails/auth/rack'
whitelist = ['certA', 'certB']
...
impl = MySinatraApp.new
acls = []
whitelist.each do |entry|
  acls << {
    'resources' => [{ 'method' => 'ALL', 'path' => '/.*' }],
    'allow_x509_subject' => { 'cn' => entry }
  }
end
acl = Rails::Auth::ACL.new(acls, matchers: { allow_x509_subject: Rails::Auth::X509::Matcher })
impl = Rails::Auth::ACL::Middleware.new(impl, acl: acl)
impl = Rails::Auth::X509::Middleware.new(impl,
                                         ca_file: '/path/to/ca.pem',
                                         cert_filters: { 'puma.peercert' => proc { |x| x } },
                                         require_cert: true)
app impl
```
