### ISSUE TITLE
A server is already running. When restarting

### ISSUE THREAD

**Issue by juanpastas** [puma/puma#1060]
I tried `touch tmp/restart.txt`, `pumactl -P tmp/pids/server.pid`, and `kill -USR2 $(cat tmp/pids/server.pid`.

All of them restart server but when starting again I get error because pid file is not removed.

Is this the intended behavior? It should be stated in readme that pid file needs to be deleted. Or better make restart include remove pid file?

**Comment by evanphx** [comment]
Hm. Can you gist the output when doing this? The pid file should be removed, yes.

**Comment by steakknife** [comment]
This worked:

1. `bin/bundle exec pumactl start -P tmp/pids/server.pid`
1. Wait for app to boot
1. `touch tmp/restart.txt`
1. App reboots just fine

Maybe needs a minimal broken example in a gist/github?

### Environment Setup
- Rails 5.0.0.1
- Puma 3.6.0
- Rack 2.0.1
- Ruby 2.3.1

**Comment by jdblack** [comment]
I saw this same thing as well.   I have attached a screenshot, as I can't seem to get markdown out of the way.    Its probably important to note that I'm using  a chef deploy resource that uses a symlink farm to handle multiple releases, but this may not be pertinent as rails was sufficiently satisfied to start up.   The symlink farm has the following appearance (which I manually pruned to remove extraneous directories and files) looks like this:
![screen shot 2017-03-19 at 5 59 12 pm](https://cloud.githubusercontent.com/assets/1109549/24086520/f7283f9c-0ccd-11e7-888c-1fed5014dc2a.png)



![screen shot 2017-03-19 at 5 49 08 pm](https://cloud.githubusercontent.com/assets/1109549/24086430/6f0275ac-0ccc-11e7-87cc-a11c2e22da1c.png)

**Comment by grosser** [comment]
The issue seems to be some kind of miscommunication between rack and puma.
Both think they are responsible for the pid file ... and when the server restarts, rack finds that the pidfile is still there and the process is still running ... patch below ... I think the core issue is that puma should not mess with the pidfile at all and let rack handle it completely ... thoughts ?

```Ruby
# Make rack not complain when puma restarts the server with the same pid
# see https://github.com/puma/puma/issues/1060
::Rack::Server.prepend(Module.new do
  def pidfile_process_status
    if ::File.exist?(options[:pid]) && ::File.read(options[:pid]).to_i == Process.pid
      :dead
    else
      super
    end
  end
end)
```

**Comment by steakknife** [comment]
I already fixed Rack in this PR in Nov 2016, but you're holding it up for! Why? https://github.com/rack/rack/pull/1127

**Comment by ThomasDebek** [comment]
You have try  to reset your terminal

**Comment by steakknife** [comment]
All good now. Close this issue.
