### ISSUE TITLE
Cannot assign requested address - bind(2) for "::1" port 3000 (Errno::EADDRNOTAVAIL)

### ISSUE THREAD

**Issue by schuetzm** [puma/puma#1062]
This is the same issue as #1022, the bugfix for which (84fdc1b) doesn't actually work in all cases.

To reproduce, put the following lines into your `/etc/hosts`:
```
127.0.0.1	localhost
::1         localhost ipv6-localhost ipv6-loopback
```

**Comment by evanphx** [comment]
I believe that means you already have something listening on that port, not that it's not working. Can you check if there is something else listening on 3000?

**Comment by schuetzm** [comment]
Yes, nothing else is listening on port 3000. But looking at the error again, it is `EADDRNOTAVAIL`, not `EADDRINUSE`. And indeed, I can't bind to any port on `::1` (even when I skip binding `127.0.0.1`). As it turns out, my system configuration was somehow messed up: IPv6 was disabled, but there were IPv6 entries in `/etc/hosts`. Go figure... Sorry for the noise.

**Comment by SurinderDhillon** [comment]
You need to enable IPv6. It will work.

**Comment by jeanlescure** [comment]
This is not only a Rails 5 IPV6 issue, having same exact problem with Rails 4+, issue has to do with having both `127.0.0.0` and `::1` pointing to `localhost` on `/etc/hosts`.

I downgraded to Puma `3.4.0` and issue goes away, but thought I should drive by and let you know.

Cheers

**Comment by daya** [comment]
@jeanlescure thanks that saved my day

**Comment by gcaracausi** [comment]
You have to modify /etc/hosts and remove localhost from the ipv6 line.
From ::1 localhost ip6-localhost ip6-loopback to ::1 ip6-localhost ip6-loopback

**Comment by znley** [comment]
> You have to modify /etc/hosts and remove localhost from the ipv6 line. From ::1 localhost ip6-localhost ip6-loopback to ::1 ip6-localhost ip6-loopback

Sorry to bother you, I want to know WHY this is happening.

**Comment by tannakartikey** [comment]
It's quite an old issue, but I wanted to share some insights in case anyone stumbles upon it. You may encounter this problem while booting up Puma, regardless of the framework you're using. I recently faced this issue while running Puma tests on a local machine.

On GNU/Linux, this error generally indicates that IPv6 is not enabled.

### Temporary Fix
You can temporarily enable IPv6, though this change will revert after a reboot.

```bash
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=0
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
```

### Permanent Fix
If you'd like to enable IPv6 permanently, you can modify the configuration files:

```bash
sudo su
echo "# Enable IPv6" >> /etc/sysctl.conf
echo "net.ipv6.conf.all.disable_ipv6 = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.lo.disable_ipv6 = 0" >> /etc/sysctl.conf
```

After making these changes, you may need to restart your networking service:

```bash
sudo service networking restart
```
