### ISSUE TITLE
Logging issue on jruby 9.0.0.0

### ISSUE THREAD

**Issue by lkananowicz** [puma/puma#1080]
Hi.
I have a custom setup of Nginx + Puma + jruby 9.0.0.0 + lotusrb app. It seems that there are no logs in files specified in config/puma.rb, neither stdout nor stderr. 

Did anyone faced similar issue with jruby or have any ideas why there are no logs?

Thanks
Leon

**Comment by evanphx** [comment]
There is no logging by default with puma in production mode, it's whatever the app uses. You'll need to see how lotusrb is logging to answer this question.
