### ISSUE TITLE
200 OK going to STDERR?

### ISSUE THREAD

**Issue by adamdavis40208** [puma/puma#1082]
My pumaconf.rb has this line:

```stdout_redirect '/var/log/puma/puma.log', '/var/log/puma/puma-err.log', true```

puma.log contains:
```=== puma startup: 2016-09-07 23:33:01 +0000 ===
[4433] - Worker 0 (pid: 4436) booted, phase: 0```

puma-err.log contains:

```10.10.10.1 - - [08/Sep/2016:00:03:27 +0000] "GET /health HTTP/1.0" 200 - 0.0005``` 
```10.10.10.1 - - [08/Sep/2016:00:03:27 +0000] "GET /health HTTP/1.0" 200 - 0.0005```

Any tips on what I may have incorrectly setup?

**Comment by adamdavis40208** [comment]
A little more info on my side -- I set up a new test on a copy of your master branch, with the following config:

`log_requests
stdout_redirect "t4-stdout", "t4-stderr", true
pidfile "t4-pid"
bind "tcp://0.0.0.0:10103"
rackup File.expand_path('../hello.ru', File.dirname(__FILE__))
daemonize false
`

And wrote a test around "200 OK should only be in stdout, not in stderr" and everything is passing.

I'm pretty stumped why spinning up a puma server from the base repo is acting so differently, but I will keep digging.

**Comment by evanphx** [comment]
@adamdavis40208 What is your whole puma config for when you have the issue?

**Comment by adamdavis40208** [comment]
hey @evanphx, I'm going to close this issue. It truly does seem like a "me/my app" problem considering the tests still work. We're using a logger in sinatra that also uses Rack::CommonLogger. 

I will throw a pull request to get my test cases pulled in though, I didn't run into any that were testing the stderr log path for puma.
