### ISSUE TITLE
Puma no longer serving http

### ISSUE THREAD

**Issue by sepastian** [puma/puma#1092]
I have upgraded to `3.6.0`.

If I do `rackup`, puma will listen on `tcp://0.0.0.0:9292`. If I then connect with a browser, all requests timeout. As far as I understand, puma should server `http`, not `tcp`. How can I tell it to do so?

My `config.ru` is simply:

```
run MyAPP
```

**Comment by sepastian** [comment]
I found the `--tcp-mode` paramter, which forces to run in TCP mode. I need the opposite of that.

**Comment by frodsan** [comment]
Do you have a `config/puma.rb` file that you can post here?

**Comment by sepastian** [comment]
No, I'm not using a `config/puma.rb` file.

**Comment by evanphx** [comment]
The `tcp` there just means it's bound to that port and will be doing http over it.

TCP mode (I'm realizing now that the name is confusing) is a separate mode for using puma to run non-HTTP apps entirely.

Now, the real issue here is that you can't connect. If you typed `tcp://0.0.0.0:9292` that won't work. Does `http://127.0.0.1:9292` work?

**Comment by sepastian** [comment]
@evanphx, thanks for your reply, took me a while to test this.

So I tested with puma and thin; invoking both `http://0.0.0.0:9292`, `http://127.0.0.1:9292` and `http://locahost:9292`; using both Firefox, Chrome and curl as a client.

When using `rackup -s puma --host 127.0.0.1`, all clients timed out for all URLs. The console did not show any clients trying to connect.

When using `rackup -s thin --host 127.0.0.1` instead, Chrome and curl would connect and return as expected. Firefox would connect but returned a 404 error for some reason.

Firefox returning a 404 from thin may point at a problem on my end. On the other hand, why does everything work fine in Chrome and curl using thin? What's the difference here between thin and puma?

**Comment by sepastian** [comment]
Here's some information about my environment:

```
$ uname -a
Linux sebastian 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ rbenv -v
rbenv 1.0.0-21-g9fdce5d
$ bundle show puma
/home/sebastian/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.6.0
$ thin -v
thin 1.7.0 codename Dunder Mifflin
```

**Comment by evanphx** [comment]
@sepastian You didn't indicate if `0.0.0.0` or `localhost` work with puma. Do they? It sounds like this might be a  IPv4/IPv6 issue.

**Comment by sepastian** [comment]
No, neither did work with puma.

How can I verify whether of not this has to do with my network configuration?

As I said, the strange thing is that is works with thin...

**Comment by evanphx** [comment]
That's really odd. What about using just a hello world rack app? Does that work? Try this: https://raw.githubusercontent.com/puma/puma/master/test/hello.ru

**Comment by sepastian** [comment]
That works, must be something in my app then!

Last question: can I debug puma somehow? Can I hook into the request cycle?

Sorry for bothering you and thanks for you help!

**Comment by sepastian** [comment]
**Update.**

I have been digging deeper into this. The timeout occurs, if I define a rackup app as a class *and* require `mongoid`. It does not occur if I either don't require `mongoid` or define my app as a `lambda`.

```
# cat Gemfile 
source 'https://rubygems.org'
gem 'mongoid'
gem 'grape'
gem 'roar'
gem 'grape-roar'
gem 'puma'
```

This works:

```
# cat config.ru
require 'mongoid'
require 'grape'
require 'grape-roar'
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]]  }
```

As does this:

```
# cat config.ru
# require 'mongoid'
require 'grape'
require 'grape-roar'
module GGAT
  class API < Grape::API
    get '/test' do
      "HALLO"
    end
  end
end
run GGAT::API
```

But this does not (puma starts up but requests never show up on the console and, eventually, timeout):

```
# cat config.ru
require 'mongoid'
require 'grape'
require 'grape-roar'
module GGAT
  class API < Grape::API
    get '/test' do
      "HALLO"
    end
  end
end
run GGAT::API
```

Although things start to fail as `mongoid` gets required, this has to do with puma, because the last version is working as expected in thin.

Could this have to do with how/at which point puma is loading dependencies?

I'm puzzled...

**Comment by sepastian** [comment]
Found a solution. It made a stupid mistake, I didn't add `rack` to my bundle, but used Ruby's `rackup` command instead.

FYI:

```
# add rack to Gemfile
gem 'rack'
```

```
# generate binstubs for rack
$ bundle binstubs rack
$ bin/rackup # instead of just rackup
```

Thanks for you help!
