### ISSUE TITLE
phased restart 50% work

### ISSUE THREAD

**Issue by u007** [puma/puma#1093]
#it works only 50% of the time.
here is my capistrano output
```
  INFO [f547cdd6] Running /usr/local/rvm/bin/rvm 2.3.1 do bundle exec pumactl -S /home/project/rails-stg/shared/tmp/sockets/puma.state phased-restart as project@stg.project
 DEBUG [f547cdd6] Command: cd /home/project/rails-stg/current && ( export RACK_ENV="staging" ; /usr/local/rvm/bin/rvm 2.3.1 do bundle exec pumactl -S /home/project/rails-stg/shared/tmp/sockets/puma.state phased-restart )
 DEBUG [f547cdd6] 	Command phased-restart sent success
  INFO [f547cdd6] Finished in 3.545 seconds with exit status 0 (successful).
```
even with minor tweak on view file, it could fail. with all instance down..

using:
  rails (5.0.0)
  puma (3.6.0)
  rack (2.0.1)

**Comment by u007** [comment]
even with restart, 50% of the time it wont start

**Comment by evanphx** [comment]
Could you be a bit more specific with what the issue is? Are you saying that when you request a phased restart nothing happens?

**Comment by u007** [comment]
with the pumactl command for restart nor phased-restart,
it seems all instance are shutted down (not sure forcefully or gracefully), 
but it does not spawn new instance

**Comment by evanphx** [comment]
Does the log have any indication what happened? I don't have anything to
diagnose what you're seeing.

**Comment by u007** [comment]
1st, it seems to kill all workers at once, is this how phased-restart suppose to work?

**Comment by u007** [comment]
got this
SSHKit::Runner::ExecuteError: Exception while executing as wspine@live.wheelspine: bundle exit status: 1
bundle stdout: No pid '1808' found
bundle stderr: Nothing written

why for no reason the pid does not exists, but process are still active on server

**Comment by evanphx** [comment]
Can you please gist the output of puma when you perform a phased restart? It should not stop all the workers at once, it should be doing them one at a time.

**Comment by u007** [comment]
okay i found the problem,
i didnt have remote deployment, therefore my Capfile was wrong,
was:
```
require 'capistrano/bundler'
# require 'capistrano/rails/assets'
require 'capistrano/rails' # this is the biggest issue if i dont precompile on server
```
changed to this works:
```
require 'capistrano/bundler'
require 'capistrano/rails/migrations'
```
