### ISSUE TITLE
test.com for test_timeout_in_data_phase test?

### ISSUE THREAD

**Issue by junaruga** [puma/puma#1098]
This is just question.
Can I ask about test_timeout_in_data_phase test?

https://github.com/puma/puma/blob/v3.6.0/test/test_puma_server.rb#L313

> client << "POST / HTTP/1.1\r\nHost: test.com\r\nContent-Type: text/plain\r\nContent-Length: 5\r\n\r\n"

is this test connecting http://test.com/ ?
What is this site?

If possible, I do not want to connect to internet outside for test because of my test environment's situation.

### System configuration

**Ruby version**:

ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

**Rails version**:

None

Thanks.

**Comment by evanphx** [comment]
No, it's not connecting to test.com, it's just sending that as the Host header. There isn't really a reason to be doing that either, that's just a really old test.
