### ISSUE TITLE
Configure puma without `config.ru` file

### ISSUE THREAD

**Issue by shahkia** [puma/puma#1099]
I'm not using `config.ru` or `puma.rb` config file, so, I run puma like below:

    Rack::Server.start(
    :app => app,
    :server => 'puma',
    :port => 9292,
    :workers => 4,
    :environment => 'development',
    :min_threads => 4,
    :max_threads => 16,
    # :quiet =>true,
    #:stdout_redirect => '/var/log/myapp/app.log',
    :before_fork => Proc.new do;end
     )
 
Now, I want to use `stdout_redirect` or disabling `stdout` and `stderr` writes. in `start` all parameters(options) are passed into a hash, so I'm not able to use methods such as `stdout_redirect` or `preload!`.

How can I do that? I mean:   **use `stdout_redirect` or disabling `stdout` and `stderr` writes without a `config.ru` file.**

### System configuration

**Ruby version**:
2.3.0

**Comment by evanphx** [comment]
You can not use those when running it via Rackup, because puma doesn't have control of the process so there is no ability to do that. Is there a reason you're not launching your app via `puma`?

**Comment by shahkia** [comment]
@evanphx Thank you for your reply. 
Actually, all parameters such as `min_thread`,`workers` and even `before_fork` which is a `Proc`  work well. The problem is exactly where I need to use something line `stdout_redirect` or `preload!` which can not be used like other (`before_fork`,...) .

The reason why I can't lunch my app via `puma`, is that, my main app containing another services(`drb server`, `job runner service` ,...) and each service is forked from main app. Actually, I need main app process in each service(sub-processes). So, I only run `ruby myapp.rb`.

**Comment by evanphx** [comment]
Ok, I suggest you use `Puma::Launcher` instead of `Rack::Server` then. You have access to the Puma configuration DSL that way and can set all those things.

**Comment by shahkia** [comment]
@evanphx **Thank you so much**

`Puma::Launcher` and `Puma::Configurtion` did that:

    conf = Puma::Configuration.new do |c|
      c.threads @conf.min_threads, @conf.max_threads
      c.app @app
      c.bind "tcp://#{@conf.bind}:#{@conf.port}"
      c.bind "unix:///#{MAIN.root_path}/tmp/puma-rest.sock"
      c.workers @conf.workers
      c.environment MAIN.environment.to_s
      c.stdout_redirect '/var/log/oopq/app.log','/var/log/oopq/app.log',false
      c.quiet
      c.before_fork do;end
      c.on_worker_boot do;end
    end
    Puma::Launcher.new(conf).run

Thank you once again.

though, issue is closed, can I hide following outputs from puma?

    [12705] Puma starting in cluster mode...
    [12705] * Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
    [12705] * Min threads: 16, max threads: 32
    [12705] * Environment: development
    [12705] * Process workers: 4
    [12705] * Phased restart available
    [12705] * Listening on tcp://127.0.0.1:9292
    [12705] Use Ctrl-C to stop

**Comment by evanphx** [comment]
You can control that output by passing `events: Puma::Events.strings` to `Launcher.new`. You can see how the events are created here: https://github.com/puma/puma/blob/master/lib/puma/events.rb

Puma's internal output all goes through an event object, using a default event object that uses stdout.
