### ISSUE TITLE
Sudden "Listen loop error: #<SocketError: problem when accepting>" After Couple Hours of Running

### ISSUE THREAD

**Issue by SimonKaluza** [puma/puma#1100]
After running Puma Version 3.6.0 (jruby 9.0.1.0 - ruby 2.2.2) with a Rails application for a couple hours, the server suddenly stops receiving any HTTP requests.  Once this critical point hits, as soon as a request comes in, Puma throws the following error visible in our Rails logs:

```
2016-09-22_15:25:21.74362 15:25:21 web.1              | 2016-09-22 15:25:21 +0000: Listen loop error: #<SocketError: problem when accepting>
2016-09-22_15:25:21.74385 15:25:21 web.1              | org/jruby/ext/socket/RubyTCPServer.java:204:in `accept_nonblock'
2016-09-22_15:25:21.74410 15:25:21 web.1              | /web/path_to_rails_application/vendor/bundle/jruby/2.2.0/gems/puma-3.6.0-java/lib/puma/server.rb:333:in `block in handle_servers'
2016-09-22_15:25:21.74433 15:25:21 web.1              | org/jruby/RubyArray.java:1560:in `each'
2016-09-22_15:25:21.74457 15:25:21 web.1              | /web/path_to_rails_application/vendor/bundle/jruby/2.2.0/gems/puma-3.6.0-java/lib/puma/server.rb:328:in `handle_servers'
2016-09-22_15:25:21.74480 15:25:21 web.1              | /web/path_to_rails_application/vendor/bundle/jruby/2.2.0/gems/puma-3.6.0-java/lib/puma/server.rb:301:in `block in run'

```

All server processes continue to run, but then each HTTP request that gets sent is immediately disconnected and logs another entry of the error above.

Could this be race condition related to us setting our thread workers count too high and overloading the CPU?  We have plenty of RAM when I observe the server through the `top` command, but all 4 CPUs on the server seem to be working.

**Comment by evanphx** [comment]
This must be a JRuby bug? /cc @headius

**Comment by headius** [comment]
Could be a JRuby bug, but 9.0.1.0 is over a year old, and there have been hundreds of fixes since then.

@SimonKaluza Can you try with JRuby 9.1.5.0?

**Comment by SimonKaluza** [comment]
@headius Sure I will try with JRuby 9.1.5.0 tonight and leave it running overnight

FWIW I can confirm that using a more conservative thread count in the puma.rb config did not help, the error had returned when I checked the server this morning.

**Comment by headius** [comment]
@SimonKaluza Hopefully I haven't missed out on your run for the night, but if you pass -Xbacktrace.style=full to JRuby we might be able to get more context out of any trace that results.

Oh, and I just noticed you said this fails in Ruby 2.2.2 as well? If that's the case, it really takes the spotlight off JRuby and puts it back on Puma, eh @evanphx?

**Comment by evanphx** [comment]
Oh, I didn't think that's what was meant by that. If it fails under MRI, do you have a backtrace or error output? MRI doesn't have a "problem when accepting" error I've seen.

**Comment by SimonKaluza** [comment]
No this error doesn't come up in MRI Ruby, I just included that as the Ruby version as extra information since that was the one that the JRuby version I was running conforms to.

Interestingly enough my web application crashes even more quickly when using JRuby 9.1.5.0 due to a different error.  With JRuby 9.1.5.0 my application responds to a 2 or 3 requests just fine, but on one particular request that loaded fine in JRuby 9.0.1.0 (but is relatively heavy in ActiveRecord operations) we get the following stacktrace:

```
2016-09-23 21:42:04 +0000: Listen loop error: java.lang.InternalError: BMH.reinvoke=Lambda(a0:L,a1:L)=>{
    t2:L=BoundMethodHandle$Species_LL.argL1(a0:L);
    t3:L=MethodHandle.reinvokerTarget(a0:L);
    t4:L=MethodHandle.invokeBasic(t3:L,t2:L);t4:L}
java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:97)
java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:460)
java.lang.invoke.LambdaForm.checkInvocationCounter(LambdaForm.java:634)
webroot.my_application.vendor.bundle.jruby.$2_dot_3_dot_0.gems.puma_minus_3_dot_6_dot_0_minus_java.lib.puma.server.RUBY$block$handle_servers$0(/webroot/my_application/vendor/bundle/jruby/2.3.0/gems/puma-3.6.0-java/lib/puma/server.rb:332)
org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
org.jruby.runtime.MixedModeIRBlockBody.yieldDirect(MixedModeIRBlockBody.java:122)
org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
org.jruby.runtime.Block.yield(Block.java:167)
org.jruby.RubyArray.each(RubyArray.java:1734)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:497)
org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
org.jruby.ir.instructions.CallBase.interpret(CallBase.java:428)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:356)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:78)
org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:144)
org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:130)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:189)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:340)
org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:66)
org.jruby.runtime.Block.call(Block.java:126)
org.jruby.RubyProc.call(RubyProc.java:324)
org.jruby.RubyProc.call(RubyProc.java:249)
org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
java.lang.Thread.run(Thread.java:745)
```

Subsequent requests after this one will yield an exception like this:

```
Error reached top of thread-pool: identity=Lambda(a0:L,a1:L,a2:L)=>{
    t3:L=Species_L.argL0(a0:L);
    t4:L=ValueConversions.identity(t3:L);t4:L} (Java::JavaLang::InternalError)
```

Googling for errors like these leads me to StackOverflow posts that point to Out of Memory errors being a likely culprit, but increasing the JVM Heap size and adding full backtraces with `JRUBY_OPTS="-J-Xmx2g -Xbacktrace.style=full"` does not seem to fix the problem.

**Comment by headius** [comment]
What Java version is this? That looks like an internal JDK bug.

**Comment by SimonKaluza** [comment]
Oracle JDK 7, specifically:

```
root@development-application-a:/usr/local/share/ruby-build# java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)
```

**Comment by headius** [comment]
Do you get this just starting up puma with JRuby? Maybe we can try to reproduce with a trivial app.

If you can, try a more recent JDK, like any recent Java 8 (1.8).

**Comment by SimonKaluza** [comment]
It is an admittedly complex application that is currently hosted via Unicorn on MRI in production.  We've been migrating to JRuby compatible gems and Puma to improve our concurrent request throughput.

I will see if I can reproduce the conditions in a simpler application, and I will test a more recent JDK as well and report back

**Comment by SimonKaluza** [comment]
Interestingly enough, with the combination of the JDK update to 8 (1.8) and JRuby 9.1.5.0 the problem I experienced with JDK 7 and JRuby 9.1.5.0 immediately after launching went away.

I will continue to monitor it and see how it performs overnight then report back.  Hopefully the original `Listen loop error: #<SocketError: problem when accepting>` I received after an extended time running with JRuby 9.0.1.0 and JDK 7 will go away as well.

**Comment by headius** [comment]
@SimonKaluza Well, that's good news! It seems to support my belief that the issue you saw with 9.1.5.0 + JDK 7 was a JDK bug. Here's hoping the SocketError is gone too, or else I'll have to convince @etehtsea to help us investigate this :-D
