### ISSUE TITLE
Failed to start puma_manager.service

### ISSUE THREAD

**Issue by pawel2105** [puma/puma#1104]
I have created a puma manager file at `/etc/init/puma-manager.conf`. This file is the standard manager configuration file:

```
# /etc/init/puma-manager.conf - manage a set of Pumas

description "Manages the set of puma processes"

# This starts upon bootup and stops on shutdown
start on runlevel [2345]
stop on runlevel [06]

# Set this to the number of Puma processes you want
# to run on this machine
env PUMA_CONF="/etc/puma.conf"

pre-start script
  for i in `cat $PUMA_CONF`; do
    app=`echo $i | cut -d , -f 1`
    logger -t "puma-manager" "Starting $app"
    start puma app=$app
  done
end script
```

When I run `sudo service puma-manager start` I get the following error:

`Failed to start puma-manager.service: Unit puma-manager.service not found.`

This is on Ubuntu 16.04.1 x64

**Comment by pawel2105** [comment]
After some digging I've found that Ubuntu now doesn't support the upstart scripts you'd expect to work from `/etc/init/`. I see that https://github.com/puma/puma/blob/master/docs/systemd.md does a bit of an intro but I'm still lost to be honest, because I'm not too familiar with systemd.

Wonder if the docs could become idiot-proof?

**Comment by gnazarkin** [comment]
@pawel2105 How'd you go about solving it?

**Comment by dekellum** [comment]
[/docs/systemd](https://github.com/puma/puma/blob/master/docs/systemd.md) has had some recent improvements.  Without something more specific about what is missing (or a PR improving the doc) I'd suggest closing this.
