### ISSUE TITLE
Files uploading issues

### ISSUE THREAD

**Issue by mitchenkod** [puma/puma#1115]
### Steps to reproduce

1) Use dropzone.js. http://www.dropzonejs.com/

2) start uploading up to 6 files in parallel, size of each file is 150 mb

The web server become not responsible. I can not even load a page, until the upload is finished. 
I look at the server logs and I see, that no information about the requests are logged, until the uploading is in progress. So I've decided this is Puma issue, or may be Rack issue (I was quiet surprised, when I found this https://github.com/rack/rack/issues/1075)
### System configuration

Puma has 16 threads and 8 workers. I have tested it on local machine in production environment, and I have deployed it on the server. There is 4 cores CPU and GB RAM on my machine. I have not expected, that it can leads to the issue
Ralis 5, ruby 2.2.2

So the question is, what to do with that? I don't think, that uploading 6 files in the same time is a highload, so may be there is something can be done with the configurations of Puma?

**Comment by chewi** [comment]
Perhaps this is #1107?

**Comment by mitchenkod** [comment]
Yes, seems like this it it
