### ISSUE TITLE
Puma's tmp_restart plugin fails to restart properly.

### ISSUE THREAD

**Issue by CodeGnome** [puma/puma#1117]
### Steps to reproduce

Using a fresh installation of Rails, plain vanilla with no modifications, results in improper behavior from Puma when touching _tmp/restart_txt_. To reproduce the behavior, start Rails and then `touch tmp/restart.txt` from another terminal. For example:

```
rails new rails_foo
cd rails_foo
bin/rails server
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.0 (ruby 2.4.0-p-1), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
* Restarting...
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /private/tmp/rails_foo/tmp/pids/server.pid.
Exiting
```
### Expected behavior

Puma should restart cleanly when _tmp/restart.txt_ has been touched.
### Actual behavior

Puma will not restart because it thinks it's already running.
### System configuration
- ruby-2.4.0-preview2
- rails (5.0.0.1)
- puma (3.6.0)

**Comment by steakknife** [comment]
Seeing this also.

`bin/bundle exec puma` seems to work correctly, but `bin/rails s` should work too.

**Comment by steakknife** [comment]
https://github.com/rails/rails/issues/24331

https://github.com/rails/rails/issues/23910

**Comment by steakknife** [comment]
So it's not puma, not the tmp_restart plugin... it's fixed in rails dev, but it needs to be merged into rails stable branches.

**Comment by steakknife** [comment]
It's rack and puma stepping on the same pidfile (`tmp/pids/server.pid`)

- `rack-2.0.1/lib/rack/server.rb:360 -> Rack::Server.write_pid` 
- `puma-3.6.0/lib/puma/launcher.rb:126 -> Puma::Launcher#write_pid`

Ideally, puma and rack should always use different pid files. (Say `tmp/pids/puma.pid`, `tmp/pids/rack.pid` in order to not play favorites.)

**Comment by steakknife** [comment]
Hacky puma plugin until Rails pushes out a fix 

```ruby
# config/puma.rb
threads_count = Integer(ENV.fetch('RAILS_MAX_THREADS') { 16 })
threads 0, threads_count

port        Integer(ENV.fetch('PORT') { 3000 })

environment ENV.fetch('RAILS_ENV') { 'development' }

plugin :rails_restart_fix # doesn't work with custom rack/rails --pid / :pid
plugin :tmp_restart
pidfile 'tmp/pids/puma.pid'

# lib/puma/rails_restart_fix.rb
require 'puma/plugin'

Puma::Plugin.create do
  def config(dsl)
    Rails.application.config.before_initialize do
      pidfile = Rails::Server.new.options[:pid]
      ::File.delete pidfile
    end
  end
end if Rails.env.development?

**Comment by prathamesh-sonpatki** [comment]
I have opened https://github.com/puma/puma/pull/1120 to fix this issue.

**Comment by steakknife** [comment]
And @prathamesh-sonpatki maybe still working on the non-trivial issue of reusing listeners so it works similarly as when run via `puma`.

**Comment by steakknife** [comment]
There is yet another reproducible bug somewhere, which causes the rails server to deadlock. (Issue TBD)

**Comment by nateberkopec** [comment]
Should be fixed by #1120 / puma 3.7.0 (coming soon).

**Comment by steakknife** [comment]
@nateberkopec There's still an unaddressed deadlock in #1137

**Comment by steakknife** [comment]
All issues puma-rails addressed.
