### ISSUE TITLE
Semicolon in url-path

### ISSUE THREAD

**Issue by elvoblin** [puma/puma#1122]
I use puma with redmine.
If redmine attachment filename contains ";" (semicolon) puma drop it and symbols which follows after, so filename does not match, and we get error.

on puma:
In browser we go to "http://localhost:3000/attachments/download/301/attachment-with-;-semicolon.txt"
and in logs we have:

```
Started GET "/attachments/download/301/attachment-with-" for ::1 at 2016-10-25 16:37:02 +0300
Processing by AttachmentsController#download as HTML
  Parameters: {"id"=>"301", "filename"=>"attachment-with-"}
```

on webrick:
url in browser: "http://localhost:3000/attachments/download/301/attachment-with-;-semicolon.txt"
logs:

```
Started GET "/attachments/download/301/attachment-with-;-semicolon.txt" for ::1 at 2016-10-25 16:41:39 +0300
Processing by AttachmentsController#download as HTML
  Parameters: {"id"=>"301", "filename"=>"attachment-with-;-semicolon.txt"}
```

I also did test with "thin" and "passenger" but problem confirmed only with puma.

**Comment by sbull** [comment]
That's most likely because semicolon is a reserved character (https://tools.ietf.org/html/rfc1738#section-3.3). It should probably be encoded as %3B to work (i.e. http://localhost:3000/attachments/download/301/attachment-with-%3B-semicolon.txt)

**Comment by nateberkopec** [comment]
Yeah. Puma's doing the right thing here, `webrick` is wrong. See https://github.com/puma/puma/blob/f5f23aaac7aaccff1b6b138d93dd4b1755ebf1c2/ext/puma_http11/http11_parser_common.rl#L13

**Comment by elvoblin** [comment]
Thanks for explanation.
I think issue may be closed.

**Comment by ixti** [comment]
Sorry for necroposting, but, how is Puma doing the right thing here, if according to URI spec, `;` is a valid char in path? o_O

**Comment by sbull** [comment]
Well, that section of RFC 1738 I referenced says `;` is "reserved", meaning it can't just be used at will in the path. Likewise, `?` is reserved and can't be used in the path - it designates the separation between the `path` and `searchpath`. It also elaborates that `/` may be used "to designate a hierarchical structure", but doesn't say anything about how `;` may be used - so the presumption is that it may not be used, the same that `?` may not be used in the path.

"Reserved" can mean that a defined use may be codified for it in the future, so you can't use it at present without going against the spec and taking the risk of being forward-incompatible. So spec-conforming services can't use it. Unless there's an updated spec you're referencing?

**Comment by ixti** [comment]
Oh, indeed, I was referencing [updated URI spec](https://tools.ietf.org/html/rfc3986), which actually clarifies [reserved chars](https://tools.ietf.org/html/rfc3986#section-2.2) situation by splitting it into 2 groups:


```
      reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

And then [explicitly allowing](https://tools.ietf.org/html/rfc3986#section-3.3) `sub-delims` in paths:

```
      path          = path-abempty    ; begins with "/" or is empty
                    / path-absolute   ; begins with "/" but not "//"
                    / path-noscheme   ; begins with a non-colon segment
                    / path-rootless   ; begins with a segment
                    / path-empty      ; zero characters

      path-abempty  = *( "/" segment )
      path-absolute = "/" [ segment-nz *( "/" segment ) ]
      path-noscheme = segment-nz-nc *( "/" segment )
      path-rootless = segment-nz *( "/" segment )
      path-empty    = 0<pchar>
      segment       = *pchar
      segment-nz    = 1*pchar
      segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
                    ; non-zero-length segment without any colon ":"

      pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"
```

**Comment by jmchambers** [comment]
Sir Tim Berners-Lee uses semicolons in his ["Matrix URI" proposal](https://www.w3.org/DesignIssues/MatrixURIs.html), and while they're not _widely_ used, [Angular 2 adopted them](https://angular.io/guide/router#heroes-list-optionally-selecting-a-hero), and [Apigee recommend using them in REST APIs](https://cloud.google.com/files/apigee/apigee-web-api-design-the-missing-link-ebook.pdf). Here's an example:

`/people;name=jon/dogs;color=brown;size=medium?page=2`

So I'm pretty sure the use of unescaped semicolons _is_ valid when they're used as delimiters for parameters defined in the path. If they're used for any other purpose, then they should be escaped:

`/attachments;name=attachment-with-%3B-semicolon.txt`

There's a good discussion about this here:

https://stackoverflow.com/questions/2048121/url-matrix-parameters-vs-request-parameters

Puma chops off the path at the first semicolon, and so parses the above examples as:

`/people`
`/attachments`

This is incorrect behaviour, and so I would say this is a bug that needs fixing.

**Comment by nateberkopec** [comment]
@jmchambers Please open a new issue.
