### ISSUE TITLE
MiniSSL JRuby Java ext needs #init? and #shutdown

### ISSUE THREAD

**Issue by olleolleolle** [puma/puma#1125]
It seems that the MiniSSL C extension has two new methods that are not present in the Java version of the extension.

This commit https://github.com/puma/puma/commit/46416cb49ed2f16614f019cee969bb8f5d0a6146 added the C extension methods.

### Steps to reproduce

1) Run the tests on jruby-9.1.5.0 in Travis, see its output

### Expected behavior

There should be no mention of NoMethodError for MiniSSL::Engine.

### Actual behavior

Noting that the usage of [MiniSSL::Engine#init?](https://github.com/puma/puma/blob/master/lib/puma/minissl.rb#L88) is a NoMethodError on this platform.

Output in tests:

```
  test_form_submit:					Error in reactor loop escaped: undefined method `init?' for #<Puma::MiniSSL::Engine:0x226affa7> (NoMethodError)
/home/travis/build/puma/puma/lib/puma/minissl.rb:88:in `close'
/home/travis/build/puma/puma/lib/puma/client.rb:112:in `close'
/home/travis/build/puma/puma/lib/puma/reactor.rb:54:in `block in run_internal'
org/jruby/RubyArray.java:2784:in `delete_if'
/home/travis/build/puma/puma/lib/puma/reactor.rb:50:in `block in run_internal'
org/jruby/ext/thread/Mutex.java:151:in `synchronize'
/home/travis/build/puma/puma/lib/puma/reactor.rb:44:in `block in run_internal'
org/jruby/RubyArray.java:1734:in `each'
/home/travis/build/puma/puma/lib/puma/reactor.rb:42:in `run_internal'
/home/travis/build/puma/puma/lib/puma/reactor.rb:153:in `block in run_in_thread'
```

[Link to build with this failure](https://travis-ci.org/puma/puma/jobs/172301308#L338)

### System configuration

**Ruby version**: jruby-9.1.5.0

---

**Comment by hapan** [comment]
Hello, any plan to fix this issue? I am getting such error too.

**Comment by olleolleolle** [comment]
@hapan Thanks for asking - I'm not planning on finishing this investigation by fixing the issue.

**Comment by davidarnold** [comment]
@hapan Currently, this is just a cosmetic error and can be ignored.  The error is trapped and the socket is still closed correctly [here](https://github.com/puma/puma/blob/0b3626091e7ca7013312586a54a2f6c150f861b7/lib/puma/minissl.rb#L114-L116)

**Comment by rfischer20** [comment]
@davidarnold I am also receiving this error in jruby and it causes the server to hang for a period of time before completing the request. I plan to look more into it myself but just found this reference and it is impacting the app performance due to slow requests.

**Comment by davidarnold** [comment]
@rfischer20 There could be some overhead from throwing the exception, but I wouldn't expect it to make the server hang.  Maybe this message is being output at the same time something else is causing it to hang?

Can you post which version you are running along with some logs?

**Comment by rvictory** [comment]
A real hack, but for now this is what we're doing to work around the issue:

`require 'puma/minissl'

# Fix Puma SSL in JRuby
if RUBY_ENGINE == 'jruby'
  module Puma
    module MiniSSL
      class Socket
        def should_drop_bytes?
          false
        end
      end
    end
  end
end`

**Comment by perlun** [comment]
I can confirm that the @rvictory-suggested hack "works" in the sense that the error I was previously getting went away:

> Error reached top of thread-pool: undefined method `init?' for #<Puma::MiniSSL::Engine:0x7a2f2ffc> (NoMethodError)

It would be great if someone could carry #1146 to completion.

**Comment by perlun** [comment]
However, I still get errors like this after each HTTPS request:

```
2018-04-24 09:55:04 +0300: Read error: #<EOFError: EOFError>
/Users/plundberg/.rvm/gems/jruby-9.1.17.0/gems/puma-3.11.3-java/lib/puma/client.rb:292:in `try_to_finish'
/Users/plundberg/.rvm/gems/jruby-9.1.17.0/gems/puma-3.11.3-java/lib/puma/client.rb:106:in `reset'
/Users/plundberg/.rvm/gems/jruby-9.1.17.0/gems/puma-3.11.3-java/lib/puma/server.rb:450:in `process_client'
/Users/plundberg/.rvm/gems/jruby-9.1.17.0/gems/puma-3.11.3-java/lib/puma/server.rb:302:in `block in run'
/Users/plundberg/.rvm/gems/jruby-9.1.17.0/gems/puma-3.11.3-java/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by schneems** [comment]
Looks like i'm getting this (and/or) another error over on CI on this PR. Any ideas on a fix? https://github.com/puma/puma/pull/1604
