### ISSUE TITLE
Suggestions to reduce memory

### ISSUE THREAD

**Issue by frazboyz** [puma/puma#1131]
I'm looking for some suggesting to limit memory consumption. I run 3 app servers on my ec2 instance and they each consume roughly 145mb's of memory each, that includes the whole ruby 2.3.1 process.

I currently launch puma like this...
`bundle exec puma -e production -d -b unix:///tmp/socketfile.sock --pidfile /tmp/puma.pid`

What launch parameters could I add to reduce puma's footprint?

**Comment by nateberkopec** [comment]
Lucky for you, my Rubyconf talk was exactly about this. Here are the notes from that talk: https://gist.github.com/nateberkopec/2b1f585046adad9a55e7058c941d3850

Is there a reason you're running three separate app servers instead of running Puma in clustered mode?

**Comment by frazboyz** [comment]
@nateberkopec They are all different apps/websites. Not all the same.

**Comment by nateberkopec** [comment]
👍 145mb isn't bad to be honest. Check out the suggestions linked and see if any make any difference, but you're currently already at "above-average" memory performance for a Ruby web process.

**Comment by frazboyz** [comment]
@nateberkopec puma website advertises 78 megabytes of memory usage but yea 145 aint bad.

**Comment by nateberkopec** [comment]
Ah, I have no idea how that benchmark was conducted but it was probably just conducted with a bare Rack app, which your apps definitely aren't. Your Mileage Will Vary.
