### ISSUE TITLE
Empty response body causes spurious error with SSL enabled

### ISSUE THREAD

**Issue by chewi** [puma/puma#1132]
I've recently started seeing this in my production monitoring.

```
SSL error, peer: 127.0.0.1, peer cert: /C=GB/ST=Midlothian/L=Edinburgh/O=Yakara Ltd/CN=localhost, #<Puma::MiniSSL::SSLError: System error: Success - 0>
```

I reproduced the issue under Vagrant and found that it's triggered by empty response bodies. The Content-Length header is present. It doesn't happen when serving empty static files.

```
< HTTP/2.0 200
< server:nginx
< date:Mon, 14 Nov 2016 12:33:36 GMT
< content-type:text/csv
< content-length:0
< cache-control:no-cache
< x-request-id:9f56b28b-f14a-4f10-9e29-03f0f205b5e7
< x-runtime:0.010231
```

The client (browser, curl, wget) doesn't report that anything is wrong. I'm seeing this with 3.6.0, which is proxied by nginx 1.9.10 using SSL.

**Comment by schneems** [comment]
Can you give us an example app that reproduces the problem? Is the error coming from nginx or from Puma?

**Comment by chewi** [comment]
I'll do that tomorrow. The error appears in Puma's output, probably from [this line](https://github.com/puma/puma/blob/3f66b3d7d4413f843e4e541c4d282238318c4cd2/ext/puma_http11/mini_ssl.c#L236).

**Comment by alexandrecardinal** [comment]
I have the same issue. I can live with the error for now but I'll post a small project that reproduces this issue, probably this week. The error is coming from Puma.

**Comment by chewi** [comment]
Sorry for not coming back to this. I was reminded of it recently but it's way down on my todo list at work.

**Comment by YannHulot** [comment]
Hi there. I am kind of new to this so I'll try to be accurate. I am currently working on an application and I saw an error like this in the logs:  #<Puma::MiniSSL::SSLError: System error: Success - 0>

After careful investigation it looks like it happens after a request hits a controller with a method rendering "nothing". As such: 

```
def create
  Service.link(params[:user_id], params[:id], params[:action_name], params[:important])
  render nothing: true, status: :ok
end
```

I know this method is deprecated in Rails 5 as per:

http://stackoverflow.com/questions/34688726/the-nothing-option-is-deprecated-and-will-be-removed-in-rails-5-1

But the app I am working on hasn't been upgraded to rails 5 yet and our users do not seem to be impacted by the error. Therefore, I am debating just leaving it be for now but would appreciate a solution if possible.

**Comment by YannHulot** [comment]
Left a comment there a little while ago, just wondering if anyone had any ideas on how to solve this problem?

**Comment by nateberkopec** [comment]
If I'm reading this correctly, this should be reproducible by just serving a 0-length response over SSL? Can anyone confirm that?

**Comment by chewi** [comment]
Yes.

**Comment by nateberkopec** [comment]
Great! Sounds like somebody can write a test and we can be on our way here 👍
