### ISSUE TITLE
uninitialized constant #<Class:#<Puma::DSL:0x000000024dec00>>::Rails

### ISSUE THREAD

**Issue by jakesorce** [puma/puma#1134]
### Steps to reproduce

1) bundle exec cap staging deploy

### Expected behavior

Deploy should happen successfully

### Actual behavior

command being run: `cd /home/ec2-user/apps/taxzilla/current && ( export RACK_ENV="production" ; ~/.rvm/bin/rvm default do bundle exec pumactl -S /home/ec2-user/apps/taxzilla/shared/tmp/pids/puma.state restart)`

error: uninitialized constant #<Class:#<Puma::DSL:0x000000024dec00>>::Rails

### System configuration

**Ruby version**: 2.3.1
**Rails version**: 5

**Comment by evanphx** [comment]
You're trying call out to Rails in your puma config file but you don't have rails loaded/preloaded. Can you paste your config file?

**Comment by jakesorce** [comment]
```if Rails.env.production?
	# Change to match your CPU core count
	workers 2

	# Min and Max threads per worker
	threads 1, 6

	daemonize
	prune_bundler

	app_dir = File.expand_path("../..", __FILE__)
	shared_dir = "#{app_dir}/shared"

	# Default to production
	rails_env = ENV['RAILS_ENV'] || "production"
	environment rails_env

	# Set up socket location
	bind "unix://#{shared_dir}/sockets/puma.sock"

	# Logging
	stdout_redirect "log/puma.log", "log/puma.log", true

	# Set master PID and state locations
	pidfile "#{shared_dir}/pids/puma.pid"
	state_path "#{shared_dir}/pids/puma.state"
	#activate_control_app

	on_worker_boot do
	  #require "active_record"
	  #ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
	  #ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
	end
end```
