### ISSUE TITLE
Fail to build on debian sid

### ISSUE THREAD

**Issue by nicoe** [puma/puma#1136]
I tried to install puma using the following command line on my debian box (unstable up to date):

```
gem install puma -v '3.6.0' --user-install
```

It failed to build with the following message:

```
WARNING:  You don't have /home/nicoe/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
	ERROR: Failed to build gem native extension.

    current directory: /home/nicoe/.gem/ruby/2.3.0/gems/puma-3.6.0/ext/puma_http11
/usr/bin/ruby2.3 -r ./siteconf20161119-32550-kwzs7p.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/nicoe/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/puma-3.6.0/mkmf.log

current directory: /home/nicoe/.gem/ruby/2.3.0/gems/puma-3.6.0/ext/puma_http11
make "DESTDIR=" clean

current directory: /home/nicoe/.gem/ruby/2.3.0/gems/puma-3.6.0/ext/puma_http11
make "DESTDIR="
compiling http11_parser.c
compiling io_buffer.c
compiling mini_ssl.c
mini_ssl.c: In function 'get_dh1024':
mini_ssl.c:90:5: error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'
   dh->p = BN_bin2bn(dh1024_p, sizeof(dh1024_p), NULL);
     ^~
mini_ssl.c: In function 'engine_init_client':
mini_ssl.c:197:3: warning: 'DTLSv1_method' is deprecated [-Wdeprecated-declarations]
   conn->ctx = SSL_CTX_new(DTLSv1_method());
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from mini_ssl.c:15:
/usr/include/openssl/ssl.h:1614:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *DTLSv1_method(void)) /* DTLSv1.0 */
 ^
Makefile:239: recipe for target 'mini_ssl.o' failed
make: *** [mini_ssl.o] Error 1

make failed, exit code 2
```

**Ruby version**: ruby 2.3.2p217 (2016-11-15) [x86_64-linux-gnu]
**Rails version**: 4.2.7.1

**Comment by deepj** [comment]
@nicoe Check https://github.com/puma/puma/issues/783

**Comment by nicoe** [comment]
I might be mistaken but I doubt this is #783 because the error is not a missing file.

**Comment by spk** [comment]
This might be because Debian sid is currently moving to [libssl1.1](https://packages.debian.org/sid/libssl1.1) and `mini_ssl` only support `libssl1.0` ABI

**Comment by yob** [comment]
I was able to build puma on debian sid once I installed the new `libssl1.0-dev` package.

Installing it might be a challenge, as it conflicts with `libssl-dev` (v1.1.0). You should only need it installed while puma builds though, then you can re-install `libssl-dev`. It's a hack, but might be helpful as an interim solution.

**Comment by junaruga** [comment]
This also happens on Fedora rawhide (It may be like Debian sid?).

Build puma with openssl-devel 1.0.2j: Success
Build puma with openssl-devel 1.1.0b: Failure

Same error on nginx.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=209434

**Comment by scifisamurai** [comment]
For anyone else that finds this thread like I did (via google) due to getting a similar error trying to install puma 2.16.0 for ruby 2.3.0 on Arch Linux.  

Doing the following worked to install puma using openssl-1.0
`gem install puma -v '2.16.0' -- --with-cppflags=-I/usr/include/openssl-1.0  --with-ldflags=-L/usr/lib/openssl-1.0`

References:
1. https://github.com/puma/puma/issues/971 (shows the syntax for passing cppflags & ldfags switches to gem install )
2. https://wiki.archlinux.org/index.php/RVM (shows the cppflags & ldflags appropriate for openssl 1 on Arch Linux)

**Comment by kinduff** [comment]
Method above from @scifisamurai works to compile puma v3.2.0 for ruby 2.3.0 on ArchLinux.

**Comment by artkirienko** [comment]
Works fine for an old project after `bundle update` :+1:
