### ISSUE TITLE
A way to change cipher being used?

### ISSUE THREAD

**Issue by matobinder** [puma/puma#1166]
So I have an client that is being really picky about what cipher is being used. when doing ssl.
I had my service using thin, but switched over to puma. But this one app(very black box) doesn't want to connect.

I think the issue is what cipher the server is picking to use.
When using puma, and curl verbose I see it use
DHE-RSA-AES256-SHA256

When using puma, and curl verbose I see it use
AES256-SHA256

This client is a very black box and I can't tell exactly what the error is. But this was what I found.
Is there a way to tell Puma which one to default to?

**Comment by nateberkopec** [comment]
Good point, I don't think there is at the moment.

**Comment by olleolleolle** [comment]
@matobinder Can you edit your description text a little? Both of the cases that you contrast are labeled "When using puma, and curl verbose I see it use [...]".

**Comment by matobinder** [comment]
Sorry for delaying getting back at this. Puma wasn't the problem at all in this case, nor was the application access it, they had changed some networking on me .
