### ISSUE TITLE
How to close server connections?

### ISSUE THREAD

**Issue by twiduch** [puma/puma#1171]
I fork part of my Rails app on Puma server

    fork do
      Process.daemon
      sleep
    end

How to close connections in this forked part, which inherits connections to unix socket from Rails app?  
Anything like Puma.close_all_connections ???

**Comment by nateberkopec** [comment]
Hi - we generally try to reserve the issue tracker for bugs and features rather than support. You should ask this question on gitter or StackOverflow, since this question is about general Ruby behavior rather than being Puma-specific.

**Comment by twiduch** [comment]
My use case is Ruby app, true. But it is Puma specific. I need to close all connections. 
Tried to find any class method for that, but no luck.
If that is not implemented than maybe that feature should be added. Anybody using fork can face this problem.
