### ISSUE TITLE
jruby puma can not be restarted

### ISSUE THREAD

**Issue by zouqilin** [puma/puma#1177]
i have a sinatra project, use puma.
but i can not restart puma process with signal USR2
and i try `bundle exec pumactl -S tmp/pids/app_server.state restart`, but it doesn't work,

both of restart methods output as follows:
```shell
Command restart sent success
```
but puma did not restart

note: jruby 9.1.5
os: mac osx

**Comment by zouqilin** [comment]
![screen shot 2016-12-16 at 8 12 46 pm](https://cloud.githubusercontent.com/assets/3761283/21262666/8a1cbc14-c3cd-11e6-833b-4c303d926b03.png)

**Comment by zouqilin** [comment]
is there any update? @nateberkopec

**Comment by nateberkopec** [comment]
@zouqilin Please try with Puma 3.8.1, we've changed a lot of the restart code since you opened this issue.

**Comment by zouqilin** [comment]
![default](https://cloud.githubusercontent.com/assets/3761283/26647047/93f51dd2-4670-11e7-9058-1ece0d12b010.png)
jdk1.8.0_60
jruby-9.1.10.0(rvm)
debian
@nateberkopec  failed again.

**Comment by perlun** [comment]
FWIW, I just happened to verify this. Our use case is slightly different: we have a magic URL that runs this code:

```ruby
    Process.kill('USR2', Process.pid)
```

This works fine on both MRI and JRuby. @zouqilin, could you try it out in your use case?

**Comment by zouqilin** [comment]
![image](https://user-images.githubusercontent.com/3761283/30020242-ca09d578-9195-11e7-8162-41749aca960b.png)
@perlun It's so perfect. thank you

**Comment by zouqilin** [comment]
![image](https://user-images.githubusercontent.com/3761283/30020476-7e397f8a-9196-11e7-905c-35d4cd2251ed.png)
it did. but I found process id not changed.

**Comment by kajisaap** [comment]
Confirming @zouqilin 's observation. 

- code seems to get reloaded as the proxy started throwing connect failed after sending USR2 signal. 

- PID did not change.

```shell
:> cat .ruby-version
jruby-9.1.16.0

:>puma --version
puma version 3.7.1

:>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

Is this an expected behaviour?

**Comment by zouqilin** [comment]
if code got reloaded, maybe it is ok.
