### ISSUE TITLE
documentation in development environment

### ISSUE THREAD

**Issue by jjb** [puma/puma#1180]
seems like once a year or so i forget that setting

```ruby
config.cache_classes = false
config.eager_load = false
```

makes rails not thread safe, and i'm wondering why my app is locked up in development, and figure out it's because i'm using multiple threads.

1) this is correct, right?
2) am i crazy or is there zero documentation about this anywhere, other than vaguely in this blog post https://tenderlovemaking.com/2012/06/18/removing-config-threadsafe.html
3) would you be interested in a PR for the readme with a sentence or 2 about this.

**Comment by nateberkopec** [comment]
@jjb Have you changed `autoload_paths`?

**Comment by jjb** [comment]
@nateberkopec no, why?
