### ISSUE TITLE
Release Puma 3.7.0

### ISSUE THREAD

**Issue by deepj** [puma/puma#1188]
The changelog says Puma 3.7.0 was released (see https://github.com/puma/puma/blob/master/History.md#370--2017-01-04). 

But there is nothing on rubygems.org (see https://rubygems.org/gems/puma/)

**Comment by nateberkopec** [comment]
Waiting on @evanphx to either do it or give me ownership on rubygems.org.

**Comment by nateberkopec** [comment]
Donezo.
