### ISSUE TITLE
puma.sock failed

### ISSUE THREAD

**Issue by gotqn** [puma/puma#1191]
Hi,

I am getting the following errors in `nginx.error.log` file:

```
2017/01/19 23:51:57 [crit] 809#809: *1 connect() to unix:///home/deploy/Production01/appname/shared/tmp/sockets/Production01-puma.sock failed (2: No such file or home/deploy/Production01/appname/shared/tmp/sockets/Production01-puma.sock:/axis-cgi/jpg/image.cgi", host: "185.123.188.98", referrer: "1"
2017/01/19 23:51:57 [info] 809#809: *1 client 217.118.84.185 closed keepalive connection
```

and in the puma.log I have:

```
=== puma startup: 2017-01-19 23:53:00 +0200 ===
* Listening on unix:///home/deploy/apps/Production01/shared/tmp/sockets/Production01-puma.sock
```

Note: I am beginner / first time deploying rails app.

### Steps to reproduce

1) Here is my production application - https://github.com/gotqn/Production01

2) https://github.com/gotqn/Production01/blob/master/config/deploy.rb

3) https://github.com/gotqn/Production01/blob/master/config/puma.rb

### Expected behavior

On my local machine everything is working fine.

### Actual behavior

The capistrano is deploying everything without errors, but I get the following message:

> We're sorry, but something went wrong.
> 
> If you are the application owner check the logs for more information.

### System configuration

**Ruby version**: 2.3.3p222 
**Rails version**: 5.0.1
**puma**: 3.6.2

https://github.com/gotqn/Production01/blob/master/Gemfile

**Comment by pabloisrael** [comment]
Hi there, i'm having the same problem. Do you remember how did you fix it?
