### ISSUE TITLE
Puma server becomes unresponsive after a while ....

### ISSUE THREAD

**Issue by chavikram** [puma/puma#1194]
I am runninng an application using Puma 3.6.0 and rails 4.2 ...
At the start, application is running fine .. for next couple of hours ... but later it the application become either very slow or become totally unresponsive ... 
Memory and CPU uses on both web and db server are also optimal... not more than 10% 
This issue is causing trouble for last many months... but with best of efforts, i could n't figure out its cause... 
If anybody here has gone through similar kind of issue , please help me out.. 

With Regards

**Comment by nateberkopec** [comment]
This could be any of a million issues. We're going to need some kind of reproduction steps to help you.
