### ISSUE TITLE
Backlog parameter does not work as intended

### ISSUE THREAD

**Issue by faucct** [puma/puma#1197]
Here is an example app - https://github.com/faucct/puma_backlog_issue_example.
There is an nginx server proxy with 5 second read timeout and a puma server with 2 workers, 2 processes and a backlog of size 8. I do 100 slow requests taking 10 seconds each. They will be timed-out by an nginx in 5 seconds and won't be accepted from puma when it is done with them.

### Expected behavior

I expect puma not to handle more than 12 slow requests (4 are being taken right now and 8 are laying in the socket backlog), deal with them in 30 seconds and to handle the last request properly.

### Actual behavior

The puma hangs until it deals with all the slow requests though the nginx won't accept them anyway.

**Comment by faucct** [comment]
I can disable `queue_requests` and it decreases the time until puma becomes available again, but it is still more than 30 seconds. Are my calculations correct?

**Comment by nateberkopec** [comment]
Why would you expect nginx to accept any response from Puma at all if your proxy_read_timeout is 5 and the response takes 10 seconds to generate?

**Comment by faucct** [comment]
Please, see the example. The request I expect nginx to take does not have any delays in it.

**Comment by nateberkopec** [comment]
There are actually two backlogs in Puma - one at the socket (which is what you have configured with `bind 'tcp://0.0.0.0:9292?backlog=8'` and one at each worker (the thread pool's backlog). The threadpool backlog. Disabling `queue_requests` disables the threadpool backlog, which seems to be the behavior you expect. Does that answer your question?

**Comment by faucct** [comment]
Yes, I guess so. Thanks.

**Comment by nateberkopec** [comment]
@faucct I'm taking a look at your Vagrant example r/n to see if I can duplicate the "greater than 30 seconds" behavior.

**Comment by faucct** [comment]
It seems to me that something is blocking those curl requests from running in parallel since they are not going from processes list simultaneously.

**Comment by nateberkopec** [comment]
So I think what's happening here is nginx is timing out the requests (causing them to finish from curl's perspective), but your last request fails because Puma is still processing requests from its backlog. If you just `vagrant up` and `time curl localhost` everything works fine.

**Comment by faucct** [comment]
Wel, this is obvious that the single request will succeed. I think I have meant to put nginx `proxy_connect_timeout` and `proxy_send_timeout` to 5 seconds too. Then most of the curl requests completes at the same time. The nginx still cannot answer after 30 seconds though. I have updated the repo.

**Comment by faucct** [comment]
Okay, if I configure it to 1 worker, 1 process and the backlog of size 2 then it does not respond within 30 seconds, but it obviously responds in less than 1000 seconds, so good enough. I guess I am just bad at math. :(
