### ISSUE TITLE
Parameters passed to Rack::Handler::Puma.run overwritten by config/puma.rb

### ISSUE THREAD

**Issue by twalpole** [puma/puma#1199]
Capybara provides support for using Puma as the server when testing an app.  
Puma is started by calling Rack::Handler::Puma.run and passing the :Host and :Port options to bind to.   Upgrading to Puma 3.7.0 is breaking things because the passed in host and port are overwritten by any settings in `config/puma.rb` if that file exists - https://github.com/teamcapybara/capybara/issues/1831.  I would expect the parameters passed to `run` to be the ones used. I think - https://github.com/puma/puma/commit/8509829729648f6b87e4e6c3fa611799e18e8353 - is the commit that changed the behavior.

**Comment by richpeck** [comment]
Confirmed issue with new puma gem. Removing options set in config pass correctly

**Comment by nateberkopec** [comment]
See #1200 for resolution.
