### ISSUE TITLE
Puma 3.7.0 halt when used as Capybara server

### ISSUE THREAD

**Issue by oslyak** [puma/puma#1201]
### Steps to reproduce

1) bundle update
 to install Puma 3.7.0
2) rails test test/integration/

### Expected behavior
With Puma
Version 3.6.2 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
Every thing work just fine.
Test just runs with selenium and I see Firefox window.

### Actual behavior
After update Puma to 
Version 3.7.0 (ruby 2.3.3-p222), codename: Snowy Sagebrush
When runs test.
Puma runs, but tests doesn't runs!
After few minutes exit with error:
**RuntimeError: Rack application timed out during boot**

### System configuration
OS: Ubuntu 16.10 x64
**Ruby version**: 2.3.3p222
**Rails version**: 5.0.1

### test/test_helper.rb
```
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'database_cleaner'
require 'rails/test_help'
require 'capybara/rails'
require 'selenium-webdriver'
DatabaseCleaner.strategy = :truncation
DatabaseCleaner.clean
Capybara.javascript_driver = :selenium
Capybara.server = :puma
```

**Comment by twalpole** [comment]
This is the same as issue #1199 and #1200 - There is a workaround in the Capybara issue about it - https://github.com/teamcapybara/capybara/issues/1831

**Comment by nateberkopec** [comment]
See #1200 as resolution.
