### ISSUE TITLE
Problem with nohup

### ISSUE THREAD

**Issue by frazboyz** [puma/puma#1202]
### Steps to reproduce

1) ... Deploy a puma app

2) ... Within a random amount of time, the app server stops

### Expected behavior

The app server should continue to run.

### Actual behavior

The app server stops.

### System configuration

**Ruby version**: 2.3.1p112
**Rails version**: 4.2.7
**Puma version**: 3.6.0

This issue has happened with a client's website twice over the past month and I am starting to get a little worried. I have three websites running on an ubuntu server, all using Rails and Puma although this is the only puma server that dies. They are all using the same version of Puma.

I do not want to disrupt my client's website with debugging so hopefully this is an easy fix.

**Comment by evanphx** [comment]
Is there any output? Any indication of it dying? I don't have much to go on.

**Comment by frazboyz** [comment]
@evanphx I looked at the production.log and there were no errors.

**Comment by roeintense** [comment]
Not sure if this is the same issue that @frazboyz is having, but I see similar symptoms. Same, no output to my production log at all except that it shut down (polite 'Goodbye!'). 

I deploy using the background task with a nohup:

`nohup rails s -b 0.0.0.0 -e production &`

I had a colleague recommend daemonizing with the `-d` tag on `rails s` and it starts fine. Haven't tested for very long. Only thing I notice is that it ignores my `config/puma.rb` completely and doesn't fire workers. When I daemonize and force the config using the `-c` flag, I get:

```
=> Booting Puma
=> Rails 4.1.2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Notice: server is listening on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--binding option)
=> Ctrl-C to shutdown server
Exiting
/var/www/jawa/config/puma.rb:4:in `<top (required)>': undefined method `workers' for main:Object (NoMethodError)
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `block in require'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/activesupport-4.1.2/lib/active_support/dependencies.rb:247:in `require'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/builder.rb:42:in `parse_file'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/server.rb:277:in `build_app_and_options_from_config'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/server.rb:199:in `app'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/commands/server.rb:50:in `app'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/server.rb:314:in `wrapped_app'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/rack-1.5.5/lib/rack/server.rb:250:in `start'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/commands/server.rb:69:in `start'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/commands/commands_tasks.rb:81:in `block in server'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/commands/commands_tasks.rb:76:in `tap'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/commands/commands_tasks.rb:76:in `server'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/railties-4.1.2/lib/rails/commands.rb:17:in `<top (required)>'
        from /var/www/jawa/bin/rails:9:in `require'
        from /var/www/jawa/bin/rails:9:in `<top (required)>'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
        from /home/gar573/.rvm/gems/ruby-2.3.3/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
        from /var/www/jawa/bin/spring:13:in `require'
        from /var/www/jawa/bin/spring:13:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

**Comment by nateberkopec** [comment]
@roeintense Puma version?

**Comment by roeintense** [comment]
Nevermind. It was dying because I wasn't demonizing properly. I figured it
out, but I can't run rails s, I have to run pumactl -F.

**Comment by herregroen** [comment]
We're consistently experiencing this issue with any Puma version above 3.6.0.

Unsure what's causing it but starting puma using `nohup puma config.ru &` with puma 3.5.2 and lower properly detaches the process. So once the ssh-session that initially started the process finishes puma stays active.

Doing the same with puma 3.6.0 and higher keeps the process attached to the ssh-session that initially started it, so once you disconnect you also kill puma.

**Comment by herregroen** [comment]
Having done some more research this seems to be directly caused #911. Undoing that commit fixes the issue entirely.

**Comment by stereobooster** [comment]
@herregroen maybe you having the same problem as in https://github.com/puma/puma/issues/1346

Try to provide `redirect_stdout` in configuration if this not the case yet.

**Comment by stereobooster** [comment]
here is reproduction

test.rb

```ruby
loop do
  Signal.trap("HUP") do
    puts "HUP"
    exit 1
  end
  sleep 1
end
```

```bash
vagrant ssh # or any other ssh to linux box
nohup ruby test.rb &
# nohup: ignoring input and appending output to 'nohup.out'
exit
cat nohup.out
HUP # nohup sends HUP signal when parent process (ssh session) closed
```

This is documented, that `HUP` signal server as `INT` if no `redirect_stdout` provided. Not a bug
