### ISSUE TITLE
Cannot connect to a rails development server on custom port in Puma 3.7.0

### ISSUE THREAD

**Issue by roberts1000** [puma/puma#1207]
I use VirtualBox with an Ubuntu Guest OS for Rails development on a Windows PC.  I start the Rails server with `rails s -p 3333`.  As of Puma 3.7.0, I can no longer connect to the rails server when trying to access `localhost:3333` in a browser.

With Puma 3.6.2, I get the following output when Puma starts

```
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://0.0.0.0:3333
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.6.2 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3333
Use Ctrl-C to stop
```

However, with Puma 3.7.0, I get the following output.

```
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://0.0.0.0:3333
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.3-p222), codename: Snowy Sagebrush
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
```

The second to last line has changed in Puma 3.7.0.  Instead of `Listening on tcp://0.0.0.0:3333`, we now have `Listening on tcp://0.0.0.0:3000`.

**Comment by twalpole** [comment]
Same as issue #1199 #1200 #1201 #1203 #1204

**Comment by nateberkopec** [comment]
See #1200 for resolution.
