### ISSUE TITLE
puma 3.7.0 does not create unix socket

### ISSUE THREAD

**Issue by Pepan** [puma/puma#1209]
### Steps to reproduce

1) use puma 3.7.0 in gemfile

2) call rvm_puma -e production -b unix:///var/run/puma/something.sock

3) /var/run/puma/something.sock is not created

### Expected behavior

/var/run/puma/something.sock must be created

### Actual behavior

creates nothing - no file

### System configuration

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
**Rails version**: Using rails 5.0.1
OS: CentOS Linux release 7.2.1511 (Core) 

---------------
Fall back to puma 3.6.2 restores correct behavior and it creates unix socket file.

**Comment by marcmarcet** [comment]
+1

I have exactly the same issue with:

Ruby 2.4.0p0
Rails 5.0.1
Ubuntu 16.04

Fallback to 3.6.2 solves the issue as well.

**Comment by nateberkopec** [comment]
Works for me on Puma (all versions) and Mac.

**Comment by noma4i** [comment]
Same here. Ubuntu 16.04
````
bundle exec puma --daemon --bind unix://$PUMA_SOCKET --pidfile $PUMA_PID_FILE"
````
Puma is running and serving content while never creating socket file

**Comment by stereobooster** [comment]
Not reproducible on linux

Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
end
```

```
vagrant ssh
bundle exec puma --bind unix:///tmp/puma.sock
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.4-p301), codename: Snowy Sagebrush
* Min threads: 0, max threads: 16
* Environment: development
* Listening on unix:///tmp/puma.sock
Use Ctrl-C to stop
```

**Comment by noma4i** [comment]
I believe thats kind of bug due to misconfiguration and eventually reproducible. So we can close that issue as no complains since late march 2017.

**Comment by juansecaro** [comment]
Is happening to me now. 
I got everything working the first time I deployed with capistrano. In the second deployment the file disappeared, and I couldn't create it back. Now, I cannot make it work, even using "-b unix:///home/.../puma.sock"

**Comment by MSP-Greg** [comment]
@juansecaro

Need more info.  What version of Puma are you using?  Any errors shown in logs?

**Comment by juansecaro** [comment]
> gs?

I was using Puma 5.2.2. The only error was this: 

"PID: 2361 2021-05-02 03:12:13 +0200 ERROR: No application configured, nothing to run"

I've managed to recreate the socket using also a config file. But nothing else worked.

Sorry not being to be able to provide more details.

**Comment by MSP-Greg** [comment]
@juansecaro

That message has nothing to do with the socket.  Your application isn’t configured.  Without an app, Puma can’t reply to any requests, so it shuts down.  Maybe google that error message, along with puma and/or Capistrano…
