### ISSUE TITLE
"Expect: 100-continue" behaviour

### ISSUE THREAD

**Issue by defsprite** [puma/puma#1210]
### Steps to reproduce

Considering the following "test" case (needs a local installation of `curl`, edited from [here](https://github.com/puma/puma/blob/master/test/test_puma_server.rb#L465))

```
  def test_curl_Expect_100
    @server.app = proc { |env| [200, {}, ["Some Response"]] }

    @server.add_tcp_listener @host, @port
    @server.run

    TCPSocket.new @host, @server.connected_port
    puts `curl -v --tcp-nodelay -w "\n\n%{time_starttransfer}\n%{time_total}\n" -XPOST -d '{}' -H 'Expect: 100-continue' -H 'Connection: close' #{@host}:#{@server.connected_port}`
  end
```

which yields something like this in my case:

```
bundle exec ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_helper.rb"; require "puma/events"; require "test/test_puma_server.rb";' -- --name test_curl_Expect_100
Run options: --name test_curl_Expect_100 --seed 37549

# Running:

* Rebuilt URL to: 127.0.0.1:62220/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 62220 (#0)
POST / HTTP/1.1
> Host: 127.0.0.1:62220
> User-Agent: curl/7.43.0
> Accept: */*
> Expect: 100-continue
> Connection: close
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* Done waiting for 100-continue
* We are completely uploaded and fine
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Connection: close
< Content-Length: 13
< 
{ [13 bytes data]
* Closing connection 0
Some Response

1.002
1.003
.

Fabulous run in 1.022017s, 0.9785 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```
### Expected behavior

The request should take a lot less than 1s, which is curl's timeout for a `HTTP/1.1 100 Continue` header.   

### Actual behavior

The curl client times out waiting for the continuation header, then sends the body anyway (as per RFC). The continuation gets sent along with the whole response.

Looking at the code is becomes clear that [`process_client`](https://github.com/puma/puma/blob/master/lib/puma/server.rb#L404) (and with it sending of the `100 Continue` only gets processed when [`client.eagerly_finish`](https://github.com/puma/puma/blob/master/lib/puma/server.rb#L253) becomes true (in the default case of request queuing). This seems only to be the case when the whole body has been uploaded, which the client is waiting to do AFTER receiving `100 Continue` 

Is this intended? Am I doing something wrong? Is this basically a no-go with the rack spec?

### System configuration

**Ruby version**: 2.3.3
**Puma version**: 3.7.0

**Comment by tristanholl** [comment]
:+1:

**Comment by decoomanj** [comment]
I'm running a small Go-client which has `ExpectContinueTimeout: 1 * time.Second,` in its client. This causes a delay of 1s when doing posts to a Ruby service. I had to remove it for the Ruby services. So, yes, this should be fixed, I suppose.

**Comment by evanphx** [comment]
Totally good catch, yes, it's waiting for the request to finish uploading. This was an oversight when I added support for this, looking to add the simplest version possible to satisfy the requirement. It should be fixed.

**Comment by defsprite** [comment]
Excellent, this is great news! Thank you very very much! 🎉  :1st_place_medal:
