### ISSUE TITLE
Cannot run upstart on Ubuntu 16.04

### ISSUE THREAD

**Issue by aconfee** [puma/puma#1211]
### Steps to reproduce

1) Following this tutorial: https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04.

2) After completing everything down to the section 'Start Puma Applications Manually', run 'sudo start puma-manager'.

### Expected behavior

Application should start.

### Actual behavior

Receiving the error: 'Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused'.

### System configuration

Ubuntu: 16.04
Ruby: 2.3.3p222
Rails: 5.0.1
Puma: 3.6.2

Please let me know if you need any other details! I have a slightly wordier description of the problem here: https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04?comment=55899

**Comment by hackedunit** [comment]
That is because Ubuntu 16.04 now uses systemd rather than Upstart (as described in that tutorial). So you will need to use systemd (there is an option to go back to using upstart though). 

I created a systemd service [here](https://gist.github.com/hackedunit/451a43a212f3868ed9c8c4fa84008191) - after following the example from [here](https://github.com/puma/puma/blob/master/docs/systemd.md)  

You could download that gist and put it at `/etc/systemd/system/puma.service`

which will let you use the following commands:

`systemctl start puma`
`systemctl stop puma`
`systemctl status puma`

If you want to start puma on boot:

`systemctl enable puma`

**Comment by aconfee** [comment]
@hackedunit Thanks for your quick response! This is helpful, but I still have a couple of questions. (Thanks for your patience, I'm really new to RoR and Linux). 

With respect to provided example:

1) /usr/local/bin/puma does not exist in my directory, although Puma is installed and working. What is /usr/local/bin/puma? Might this be installed somewhere else on my machine or did I miss an install step?

2) Do I need an ExecStop action as well?

Before seeing your response, I tried going down a different path creating my .service file ( https://gist.github.com/aconfee/294e9ba8f9b5da8f93a8b14282925680 ) and ran into the following issue. Not to derail your current example, but could you shed any light onto this? http://stackoverflow.com/questions/42264408/cannot-run-puma-state-stop-missing-tmp-puma-status-xxxxxx.

As of now, I haven't been able to get this thing to run with rbenv, rvm, or puma. I'm sure I'm missing one tiny detail on all accounts. Thanks for your help!

**Comment by hackedunit** [comment]
You could simply do `which puma` to see the complete path to your puma binary. 

I'm not sure you need an ExecStop as the stop command seems to work for me but using `pumactl -S` seems to be the recommended method to stop Puma server.

**Comment by aconfee** [comment]
Perfect! That's extremely useful to know. Thanks for hanging in with me. 

My Puma server is now kicking off with that start command, but I'm receiving an error: 
`ERROR: No application configured, nothing to run`

I don't get this error if I run the entire start command from a terminal in my app directory, but the error appears when starting in systemd, or any other outer directory. This surprises me since my working directory is defined in puma.service (I copy/pasted my working dir and cd'd to it just to make sure no typos). Am I possibly not defining my app directory somewhere else?

I started digging into Puma's source code, and it looks like it's failing on:
`def load_and_bind
      unless @launcher.config.app_configured?
        error "No application configured, nothing to run"
        exit 1
end`

app_configured seems to check for the existence of a Puma config file or Rack config file (but maybe I'm mistaken) 

I can't seem to figure out what's wrong with my configuration. Do you see anything blatantly wrong or missing from my configs below?

config.ru
https://gist.github.com/aconfee/899ce7e7a4c720d634159fe844ea396b

puma.rb
https://gist.github.com/aconfee/85cef926b7462bb9c0ce7ba0e53f1d97

puma.service
https://gist.github.com/aconfee/8ad3fb3a96dad045bdff60a5ad8823ea

I want to thank you one more time. I can't tell you how helpful this is.

**Comment by hackedunit** [comment]
I think its a problem with defining the Rails env in your puma.rb file. You seem to have used the `rails_env` directive but haven't defined it [here](https://gist.github.com/aconfee/85cef926b7462bb9c0ce7ba0e53f1d97#file-puma-rb-L63).

Here is my [puma.rb](https://gist.github.com/aconfee/899ce7e7a4c720d634159fe844ea396b) in case it helps you.

**Comment by aconfee** [comment]
@hackedunit 

Thanks! That was an issue, and I also had to specify my 'directory' in puma.config. It looks like systemd is successfully starting puma now :) (Although, there are still a few unrelated kinks: https://github.com/puma/puma/issues/1218) 

Thank you for all of your help!

**Comment by adisos** [comment]
http://codepany.com/blog/rails-5-puma-capistrano-nginx-jungle-upstart/ - alternative usage of upstart instead of systemd

**Comment by thefonso** [comment]
alternative usage of upstart does not work.

**Comment by thadeu** [comment]
install upstart-sysv solve my problem

**Comment by markgarrigan** [comment]
In case anyone is searching for answers...
The only ExecStart that worked for me was this...

```ExecStart=/bin/bash -lc 'puma -C /path/to/puma.rb```
