### ISSUE TITLE
Puma >= 3.6.1 + SSL + Persistent Connections. Puma Hangs :( 

### ISSUE THREAD

**Issue by soulnafein** [puma/puma#1214]
Since we've upgraded to puma 3.7.0 from 3.6.0 we started to experience a very annoying issue in development. Puma would hang sometimes.

After an intense Friday afternoon we've managed to pin-point the problem.

### Steps to reproduce

1) Run any basic rack app using puma greater than or equal to 3.6.1. With the approriate configuration to run in SSL mode: puma -b 'ssl://0.0.0.0:3000?cert=/path/to/cert/localhost.crt&key=/path/to/key/localhost.key'

2) Request a page from an IRB session using a library with persistent connections like Typhoeus: Typhoeus.get('https://localhost:3000')

3) Press CTRL+C on puma process, puma says: "Gracefully stopping, waiting for requests to finish" but it never stops

4) Run the request again from the IRB console: Typhoeus.get('https://localhost:3000')

5) Puma unstuck itself

I wonder if it has been caused by this commit: https://github.com/puma/puma/commit/df18d9331dd9c07f76859e2605dbfb88e71fd92d 
just because it mentions SSL and it's in 3.6.1 tag.

I hope it helps.

**Comment by tadas-s** [comment]
So I tried this with puma v3.6.1 + ssl + `persistent_timeout 2` while watching `netstat -nt | grep ":3000"`:

```
Every 0.3s: netstat -nt | grep ":3000"                                                                       Fri Feb 17 17:05:37 2017

tcp        1 262552 10.0.2.15:3000          10.0.2.2:61111          LAST_ACK
tcp        0 275236 10.0.2.15:3000          10.0.2.2:61197          LAST_ACK
tcp        0  11629 10.0.2.15:3000          10.0.2.2:61230          LAST_ACK
tcp        0 189813 10.0.2.15:3000          10.0.2.2:61393          LAST_ACK
tcp        1  96197 10.0.2.15:3000          10.0.2.2:61421          LAST_ACK
tcp        0      0 127.0.0.1:3000          127.0.0.1:58170         ESTABLISHED
tcp        0 224615 10.0.2.15:3000          10.0.2.2:65076          LAST_ACK
tcp        0 275566 10.0.2.15:3000          10.0.2.2:65088          LAST_ACK
tcp       31      0 127.0.0.1:58170         127.0.0.1:3000          ESTABLISHED
tcp        1  94945 10.0.2.15:3000          10.0.2.2:59847          LAST_ACK
```

Connection stays in ESTABLISHED and won't time out.

With v3.6.0 connections stay ESTABLISHED for 2 seconds and then close:

```
Every 0.3s: netstat -nt | grep ":3000"                                                                       Fri Feb 17 17:08:18 2017

tcp        1 262552 10.0.2.15:3000          10.0.2.2:61111          LAST_ACK
tcp        0 275236 10.0.2.15:3000          10.0.2.2:61197          LAST_ACK
tcp        0      0 127.0.0.1:3000          127.0.0.1:58172         FIN_WAIT2
tcp        0  11629 10.0.2.15:3000          10.0.2.2:61230          LAST_ACK
tcp        0 189813 10.0.2.15:3000          10.0.2.2:61393          LAST_ACK
tcp        1      0 127.0.0.1:58172         127.0.0.1:3000          CLOSE_WAIT
tcp        1  96197 10.0.2.15:3000          10.0.2.2:61421          LAST_ACK
tcp        0 224615 10.0.2.15:3000          10.0.2.2:65076          LAST_ACK
tcp        0 275566 10.0.2.15:3000          10.0.2.2:65088          LAST_ACK
tcp        1  94945 10.0.2.15:3000          10.0.2.2:59847          LAST_ACK
```

**Comment by nateberkopec** [comment]
Thanks so much for a repro, linking this issue to #1202.

**Comment by tadas-s** [comment]
After some debugging I found that the [`socket.sysread` @ minissl.rb:105](https://github.com/puma/puma/blob/v3.7.0/lib/puma/minissl.rb#L105) call blocks and causes this issue.

**Comment by respire** [comment]
i believe it's related to the fix for this issue https://github.com/puma/puma/issues/1002
the commit https://github.com/puma/puma/commit/46416cb49ed2f16614f019cee969bb8f5d0a6146

i'm still looking into that issue and trying to understand the code.
anyone who gets hints are welcome

**Comment by respire** [comment]
I submit a PR #1331 as one possible solution.
It works under my env: openssl 1.0.2k, osx Sierra, puma 3.6.1
However, I'm not sure whether it's the correct way to fix this issue.

**Comment by fedebello** [comment]
Is this issue solved?

I'm trying with version (3.11.3) and server hangs connections.

If issue is solved, could you please tell me how to fix this?

Thanks in advance!
