### ISSUE TITLE
Version 3.7.1 has issues with rails s command

### ISSUE THREAD

**Issue by Stefflan00** [puma/puma#1221]
**As a user i want to start my Server after initialising a Rails Project**
I am Running on ruby-2.3.1@rails5.0.1/gems/puma-3.7.1/

After init  'rails s --db=postgresql --api i am not able to run rails s.

```
puma/binder.rb:269:in `initialize': Can't assign requested address - bind(2) for "185.27.174.169" port 3000 (Errno::EADDRNOTAVAIL)
```

Solution for now:
When downgrading to 3.7.0 it works. 
gemfile => gem 'puma', '3.7.0'

**Comment by nateberkopec** [comment]
You have an server still running. Please `spring stop` and/or kill all existing puma processes.

**Comment by Stefflan00** [comment]
@nateberkopec actually that is not true.
It must be s.th. else because running lsof -wni tcp:3000 does not give me any processes to kill.

**Comment by nateberkopec** [comment]
You're going to need to give a repro app then, because the steps you provided do not reproduce.

**Comment by nateberkopec** [comment]
Also you're trying to bind to a WAN address, not sure what's up with that.
