### ISSUE TITLE
puma crashes with nginx reverse proxy

### ISSUE THREAD

**Issue by jasonheffner** [puma/puma#1224]
I'm running a puma server for a fairly low use web application. I'm finding errors identical to ticket #1045 "connect() to unix:/var/www/app/tmp/sockets/puma.sock failed (111: Connection refused) while connecting to upstream"

Restarting puma did fix the error and I'm now running in cluster mode. I did capture this error from stdout in the logs..

*** glibc detected *** puma 3.6.2 (unix:///var/www/app/tmp/sockets/puma.sock) [app]: realloc(): invalid next size:               0x00007fd4806c8f90 ***
======= Backtrace: =========
/lib64/libc.so.6[0x342c275f3e]
/lib64/libc.so.6[0x342c27be1a]
/lib64/libc.so.6(realloc+0x158)[0x342c27c058]

I'm assuming this is ruby crashing because of a bad extension. Is there a way to trace this down?

ruby 2.2.4p230
rails (4.1.14)

**Comment by jasonheffner** [comment]
I tracked this to an issue with the eventmachine gem. Is there a way to restart the worker after crash ? Crashes do happen, just want to be able to recover.

**Comment by nateberkopec** [comment]
I don't think there's anything you can do in the event of a segfault. You'd need some kind of external process-monitoring solution (e.g. Monit).

Closing because this isn't a problem w/Puma.

**Comment by jasonheffner** [comment]
Thanks
