### ISSUE TITLE
Callbacks for single mode?

### ISSUE THREAD

**Issue by swrobel** [puma/puma#1230]
### Steps to reproduce

config/puma.rb:
```ruby
after_worker_boot do
  puts 'hello from a worker'
end
```

example:
```
$ bundle exec puma
Puma starting in single mode...
* Version 3.7.0 (ruby 2.3.2-p217), codename: Snowy Sagebrush
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop

$ bundle exec puma -w 2
[59172] Puma starting in cluster mode...
[59172] * Version 3.7.0 (ruby 2.3.2-p217), codename: Snowy Sagebrush
[59172] * Min threads: 0, max threads: 16
[59172] * Environment: development
[59172] * Process workers: 2
[59172] * Phased restart available
[59172] * Listening on tcp://0.0.0.0:9292
[59172] Use Ctrl-C to stop
hello from a worker
```

### Expected behavior

`after_worker_boot` or some equivalent callback is available in single mode after the server has booted successfully.

### Actual behavior

`after_worker_boot` callback doesn't run in single mode.

### System configuration

**Ruby version**: 2.3.2
**Rails version**: 5.0.1
**Puma version**: 3.7.0

**Comment by nateberkopec** [comment]
`after_worker_boot` only runs in cluster mode (more than 1 worker).

**Comment by swrobel** [comment]
So you don't see the value in having callbacks in single mode?

**Comment by nateberkopec** [comment]
*shrug* Just pointing out that it's clearly documented that this is a cluster_mode only callback: https://github.com/puma/puma/blob/f5f23aaac7aaccff1b6b138d93dd4b1755ebf1c2/lib/puma/dsl.rb#L337

What's your use case for doing something after boot in single mode?

**Comment by swrobel** [comment]
I'll respectfully disagree with your definition of "clearly documented" but that's sort of moot.

My use case is that I'm using the `tmp_restart` plugin and I want to display a notification using `terminal-notifier` when the restart completes.

**Comment by swrobel** [comment]
I discovered that I'm able to get access to the callbacks by setting `workers 1` which basically forces clustered mode. Seems like an arbitrary distinction to me, but I guess *shrug*, it works.

**Comment by swrobel** [comment]
Circling back to this since Puma now warns when running cluster mode with a single worker (understandably), and what I previously posted was a hack. It seems that the best way to do this would be to hook into [on_booted](https://github.com/puma/puma/blob/v5.3.1/lib/puma/single.rb#L58) which fires in single mode, but after spending a while walking circles through the code, I don't see a straightforward way to do that from the config file. @nateberkopec, hate to bug you here, but any simple way to do this?

**Comment by nateberkopec** [comment]
Feature request tracking at #2635
