### ISSUE TITLE
3.7.0 tag is pointing to, uhm, where exactly?

### ISSUE THREAD

**Issue by halfbyte** [puma/puma#1231]
Hi, sorry, this is not really a Puma bug, but I still think it is an appropriate place to report? Correct me if I'm wrong, though.

### Steps to reproduce

1) Try to look up diff between 3.7.1 and 3.7.0

2) Look at the commit that the tag v3.7.0 is pointing to

3) Try to figure out what's going on

### Expected behavior

Release tags ideally point to valid commits in the master branch, I guess?

### Actual behavior

my best assumption is that the v3.7.0 tag points to a commit only existing on @evanphx's harddrive? :)

Let me explain briefly why I noticed this: I'm currently working on [depfu.io](https://depfu.io) and I noticed that our mechanism to look up the commits between two versions broke down spectacularly with over 2000 commits returned. The way I look up commits might actually be a bit brittle, because I simply walk back from the version commit until I hit the commit of the previous version, but in most cases this should (and does) work fine.

Could someone please force the tag to point to the correct commit which I believe is 7dfc50a434c50051ac3 ? I know this sounds like pedantery, but I hope that I'm not the only one interested in somewhat correct project histories :)

If you would do this, we could replay the corresponding depfu updates with a correct commit history (and not one that's truncated by security mechanisms I try to put in place now).

### System configuration

Not relevant.

**Comment by nateberkopec** [comment]
Hm, here's the output of `git diff --stat v3.7.0 v3.7.1` on my machine:

```
nodachi:puma nateberkopec$ git diff --stat v3.7.0 v3.7.1
 .hoeignore                   |  2 --
 .travis.yml                  |  3 ++-
 History.md                   |  6 ++++++
 Manifest.txt                 |  2 ++
 lib/puma/binder.rb           |  2 +-
 lib/puma/configuration.rb    |  8 +++++++-
 lib/puma/const.rb            |  2 +-
 test/config/settings.rb      |  2 ++
 test/test_config.rb          | 11 +++++++++++
 tools/jungle/init.d/run-puma |  4 ++++
 10 files changed, 36 insertions(+), 6 deletions(-)
```

Which looks correct to me.

**Comment by nateberkopec** [comment]
Also `git tag -v v3.7.0`:

```
nodachi:puma nateberkopec$ git tag -v v3.7.0
object f413b61f4ba9a453528b1ea44a0dbdd4a6f030f1
type commit
tag v3.7.0
tagger Evan Phoenix <evan@phx.io> 1485563714 -0800

Tagging v3.7.0.
error: no signature found
```

**Comment by nateberkopec** [comment]
Paging @evanphx

**Comment by halfbyte** [comment]
@nateberkopec Anyway, thanks for looking at this, I know it is somewhat of an esoteric issue.

**Comment by nateberkopec** [comment]
No problem, I agree that our history should be valid and point to objects that actually exist!

**Comment by nateberkopec** [comment]
🤷‍♂️ Can't really fix this.
