### ISSUE TITLE
dev configuration for Rails

### ISSUE THREAD

**Issue by jjb** [puma/puma#1233]
previously with puma 3.6.2, I had this in boot.rb

```ruby
if "vagrant" == ENV["USER"]
  require 'rails/commands/server'
  module Rails
    class Server
      alias :default_options_bk :default_options
      def default_options
        default_options_bk.merge!(Host: '0.0.0.0', Port: "8080")
      end
    end
  end
end
```

based on this: http://stackoverflow.com/questions/28668436/

I was surprised that there wasn't a more straightforward and official way to achieve this, but it's been working fine for me.

now with puma 3.7.1, this is no longer working. here what I get at boot:

```
$ rails s
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://0.0.0.0:8080
=> Run `rails server -h` for more startup options
[1885] Puma starting in cluster mode...
[1885] * Version 3.7.1 (ruby 2.4.0-p0), codename: Snowy Sagebrush
[1885] * Min threads: 1, max threads: 1
[1885] * Environment: development
[1885] * Process workers: 1
[1885] * Preloading application
[1885] * Listening on tcp://0.0.0.0:3000
[1885] Use Ctrl-C to stop
[1885] - Worker 0 (pid: 1888) booted, phase: 0
```

Note it says port 8080 on line 3 and port 3000 on line 11.

I looked in the release notes and didn't find anything that I could interpret to be related to this.

Did something change about how rails tells puma which port to use?

This is under rails 5.0.2.

**Comment by nateberkopec** [comment]
Could you please post your `config/puma.rb?`

**Comment by jjb** [comment]
```ruby
plugin :heroku
```

**Comment by jjb** [comment]
Okay, commenting that out fixed the problem :-D 🤦‍♂️

**Comment by jjb** [comment]
Reopening this because I'm realizing there's a larger question. `rails s` or `rails s Puma` ignores config in puma.rb. Is this by design? Unavoidable because of how Rails interacts with servers? Is there a common workaround? Am I doing something wrong?

**Comment by jjb** [comment]
Okay, I found discussion here: https://github.com/puma/puma/issues/939#issuecomment-209000933

closing again...

**Comment by jjb** [comment]
More info if anyone finds this ticket with a similar situation:

My final setup was actually quite simple. I kept my puma.rb as

```ruby
plugin :heroku
```

I've also been using dotenv-rails. in Gemfile

```ruby
gem 'dotenv-rails', groups: [:development, :test]
```

I removed the code in my boot.rb shown above, and added this to my .env:

```
PORT=8080
```

🎉 everything works now

**Comment by jjb** [comment]
related: #1277 #1290
