### ISSUE TITLE
puma ~>3.8.0 broken on Windows Subsystem Linux

### ISSUE THREAD

**Issue by aoozdemir** [puma/puma#1240]
### Steps to reproduce

1) On Bash on Windows, run `rails new testapp --skip-spring --skip-listen`
Spring and file watcher is broken, See: https://github.com/Microsoft/BashOnWindows/issues/216 & https://github.com/rails/rails/issues/26054

Edit the gem file to install puma@~>3.8.0 if isn't installed.

2) Run `rails s`

3) Try to access `localhost:3000` and BOOM. 💣 

### Expected behavior

Rails server should work fine.

### Actual behavior

I get an error like this

```bash
2017-03-12 12:34:31 +0300: Read error: #<Errno::EINVAL: Invalid argument - getsockopt(2)>
/home/ao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.8.1/lib/puma/server.rb:124:in `getsockopt'
/home/ao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.8.1/lib/puma/server.rb:124:in `closed_socket?'
/home/ao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.8.1/lib/puma/server.rb:563:in `handle_request'
/home/ao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.8.1/lib/puma/server.rb:425:in `process_client'
/home/ao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.8.1/lib/puma/server.rb:289:in `block in run'
/home/ao/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.8.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

### PR Reference

I believe, the issue origin is here: https://github.com/puma/puma/pull/1227

### System configuration

**Ruby version**: 2.3.3p222
**Rails version**: 5.0.2
**OS**: Windows 10 OS Build 14393.693, Bash on Ubuntu on Windows.

### Works Fine

puma@3.7.1 works fine.

**Comment by nateberkopec** [comment]
Now that we're the Official Web Server Of Rails (tm) we should probably test on Windows. Don't need to do the full matrix or whatever but just a smoke test of the latest Ruby on windows would be good.

**Comment by nateberkopec** [comment]
I still think we should do windows tests, but based on #1241 this may not be Windows-specific.

**Comment by aoozdemir** [comment]
Probably it is not. Because I'm running Rails under subsystem, which is Linux. But doing Windows tests might be helpful in the future. We can cc someone from WSL, if that helps.

**Comment by nateberkopec** [comment]
Folding into #1241.

**Comment by abdulrehman3222** [comment]
I was having a similar issue with

WSL: 1, Ruby: 2.5.0, Rails: 4.2.1, and Puma: 3.8.0

my rails s was working I was getting the following error whenever I send a Get request:

```
    Read error: #<Errno::ENOPROTOOPT: Protocol not available - getsockopt(2)>
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:124:in `getsockopt'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:124:in `closed_socket?'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:563:in `handle_request'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:425:in `process_client'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/server.rb:289:in `block in run'
    /home/abr/.rvm/gems/ruby-2.5.0@helpy/gems/puma-3.8.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

I struggle a lot for fixing that issue at last, I found a simple solution that I need to update my Pum from 3.8 to 3.12+ and it works perfectly for me.
