### ISSUE TITLE
There is no 3.8.2 java release

### ISSUE THREAD

**Issue by axfcampos** [puma/puma#1243]
Hello,

I am having problems running puma with jruby as it was downloading `3.8.2` from rubygems, I went to check and there is no java release.

I understand `3.8.2` was released about an hour ago, so someone may be taking care of it. Just submitting the issue in case you forgot 😄

Thanks!

**Comment by evanphx** [comment]
Sorry about that, fixed!

**Comment by axfcampos** [comment]
Thank you! 🙇
