### ISSUE TITLE
What's the recommended way to prevent requests running for longer than we'd like?

### ISSUE THREAD

**Issue by yob** [puma/puma#1244]
Apologies for asking a question via issues, but I wasn't sure where else to ask it.

We recently switched an app from unicorn to puma, and discovered we'd been unknowingly relying on unicorns 60s request timeout to prevent occasional poor performing requests running for an unreasonably long time.

We can resolve that, but I'm interested in puma's viewpoint on the best way to tackle it.

In issues like #160 and #681, it's made clear that puma doesn't have a request timeout intentionally. One option is to add rack-timeout to the middleware stack.

In our case, the app is a data warehouse and the long requests are usually waiting on long (60+ second) SQL SELECTs. In that context, an alternative solution would be to add a timeout to our SQL query and use that to limit overall request time.

Is there a preference from puma's perspective? What's the philosophy behind puma having no request timeout? We'd like to pick a solution that aligns well with the way puma is intended to be used.

Note: we're not running on heroku, so avoiding H12 timeout errors from them isn't a concern. We just want to cap our requests to ~60 seconds so any poorly written SQL can't monopolise our worker pool.

We're running puma 3.7.1 on ruby 2.3. Servers are dedicated hardware, and we use postgresql for persistence.

**Comment by nateberkopec** [comment]
Usually, the best practice is to put your timeout code as close as possible to where the actual slow code is. So, in your case, a timeout on ActiveRecord reads would probably be appropriate. 

That said, rack-timeout could work well for you too.
