### ISSUE TITLE
Start up quiet mode

### ISSUE THREAD

**Issue by ioquatix** [puma/puma#1250]
I can see an option `quiet` but it doesn't suppress the startup output. This makes it pretty messy when running with guard-puma. I'd like an option to suppress the startup message, but additionally, i still want to print out individual requests. Does this make sense?

https://github.com/jc00ke/guard-puma/issues/24

**Comment by nateberkopec** [comment]
I'm not sure if we can really do anything for you here. Both events are logged at the same level. You can provide your own Logger to Puma which filters it out I suppose. I'll reopen if more people want this, but surpressing startup while wanting the request log is a little weird.

**Comment by hkroger** [comment]
@nateberkopec AFAIK there is no way to suppress start up messages at all, right?

**Comment by nateberkopec** [comment]
yup. same still applies as above.
