### ISSUE TITLE
Reset environment to initial state when restarting with USR1 or USR2

### ISSUE THREAD

**Issue by grosser** [puma/puma#1258]
### Steps to reproduce

```
# config/application.rb
puts "RAND #{ENV['TEST'] ||= rand(1212121212).to_s}"
```

```
kill -SIGUSR1 puma-pid
```

### Expected behavior

A new number is shown on every restart, showing that the env is reset

### Actual behavior

The same number is printed, showing that the env is not cleared.
This makes loading environment vars from a .env file fail since it won't update the previously set variables.

### System configuration

**Ruby version**: 2.3.1
**Rails version**: 5.0.1

### Monkey-patch

from https://github.com/zendesk/samson/pull/1862
```
added = ENV["SAMSON_ENV_ADDED_VIA_DOTENV"].to_s.split(',')
added.each { |e| ENV.delete(e) }

require 'dotenv'
before = ENV.keys
Dotenv.load(Bundler.root.join('.env'))
ENV["SAMSON_ENV_ADDED_VIA_DOTENV"] = (ENV.keys - before).join(",")
```

**Comment by grosser** [comment]
see https://github.com/puma/puma/issues/1258

**Comment by nateberkopec** [comment]
Does this happen with a USR2 restart as well?

**Comment by grosser** [comment]
yes, update the title
