### ISSUE TITLE
Hot restart clarification

### ISSUE THREAD

**Issue by codykrieger** [puma/puma#126]
With Unicorn's `preload_app` option set to `true`, when the Unicorn master is sent `SIGUSR2`, your app will spin up in the background (with any code changes, etc.) while the currently running app processes continue to serve requests. Only when the application is fully booted do the new processes start receiving the requests. Additionally, the old processes continue to hang onto any existing requests until they're finished, and then the old processes gracefully disappear.

Does (or can) Puma's hot restart functionality work anything like that? Or does it just queue up the requests until your application has fully restarted and can handle them once again?

Thanks much!
-ck

**Comment by 1c7** [comment]
Hi, can anyone post a update info on this?
it's 2018
I am confusing how to do hot reload
