### ISSUE TITLE
From 2.16.0 to 3.8.2 = segmentation fault

### ISSUE THREAD

**Issue by benoittgt** [puma/puma#1262]
### Steps to reproduce

1) Updated puma from 2.16.0 to 3.8.2 on rails 4.2.8 and ruby 2.4.1 
2) Start server and access to `/`

### Expected behavior
Same as 2.16.0. 
### Actual behavior

Segfault error. https://gist.github.com/benoittgt/fbc36e443aa8697719858cf0228efb4a

I tried to create an app to reproduce this behavior without success (rails 4.2.8, ruby 2.4.1, pg adapter, puma 3.8.2). The segfault link to a PGconnect method in postgresql_adapter but the error happens only when updating puma... 😞 

Also in the log I have : 
```
-- Ruby level backtrace information ----------------------------------------
/Users/bti/.rvm/gems/ruby-2.4.1@app/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
/Users/bti/.rvm/gems/ruby-2.4.1@app/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
/Users/bti/.rvm/gems/ruby-2.4.1@app/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
/Users/bti/.rvm/gems/ruby-2.4.1@app/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
/Users/bti/.rvm/gems/ruby-2.4.1@app/gems/puma-3.8.2/lib/puma/configuration.rb:224:in `call'
/Users/bti/.rvm/gems/ruby-2.4.1@app/gems/rack-1.6.5/lib/rack/content_length.rb:15:in `call'
```

**Comment by benoittgt** [comment]
No repro so closing the issue.

**Comment by kyle776** [comment]
Did you find a solution for this ? I have a similar/same issue.

**Comment by benoittgt** [comment]
@kyle776 I think we upgrade ruby, remove spring, clear bootsnap cache. :)
