### ISSUE TITLE
better_errors/binding of caller performance

### ISSUE THREAD

**Issue by leifcr** [puma/puma#1263]
### Steps to reproduce

1) Create new rails app with puma better_errors and binding_of_caller setup.

Add to gemfile and run bundle install:

```ruby
gem 'better_errors'
gem 'binding_of_caller'
gem 'puma'
```

2) Write invalid code in a controller, to trigger better_errors

### Expected behavior

Expected to return fast (similar to thin/webrick)

### Actual behavior

Response takes from 5-20 seconds depending on the request.

### System configuration
**Ruby version**: 2.4 
**Rails version**: 4.2.8, 5.0.2 and 5.1.0rc1
Rails 4.2.8 also tested with ruby 2.3

**Comment by leifcr** [comment]
See also https://github.com/charliesome/better_errors/issues/341 and https://github.com/banister/binding_of_caller/issues/59

**Comment by nateberkopec** [comment]
This isn't really an issue w/Puma as noted in https://github.com/charliesome/better_errors/issues/341. Yes, we end up including `@app` in the stacktrace, but that's not really *our fault*. In any case, `binding_of_caller` is basically abandonware and so this isn't likely to be fixed on their side anytime soon, so I'll leave this open.

**Comment by nateberkopec** [comment]
I don't think there's anything we can do about this on our side. Recommend people affected follow https://github.com/charliesome/better_errors/issues/341.
