### ISSUE TITLE
What is the default configuration file path for a specified environment?

### ISSUE THREAD

**Issue by mattdipasquale** [puma/puma#1265]
According to [Puma README: Configuration file][1]:

> If an environment is specified . . . through the RACK_ENV environment variable, the default file location will be config/puma/environment_name.rb.

Is this still true for Puma 3.8.2 with Ruby 2.4.1?

  [1]: https://github.com/puma/puma/blob/master/README.md#configuration-file

**Comment by nateberkopec** [comment]
[Yes](https://github.com/puma/puma/blob/master/lib/puma/configuration.rb#L194).

**Comment by mattdipasquale** [comment]
OK. Thank you. :•)

**Comment by mattdipasquale** [comment]
Hmm... 🤔 When I run the command below, Puma seems to use its default configurations instead of the ones I've specified in `config/puma/development.rb`.

```bash
RACK_ENV=development bundle exec puma --debug
```

How should I debug this?

**Comment by mattdipasquale** [comment]
Oh, nice! I found this handy method called [`p`][1]. 🤓

So, I added `p @options[:environment]` right above [`lib/puma/configuration.rb:194`][2] and then ran Puma again (with the command in my comment above). And, the output showed that `@options[:environment]` is a `Proc`. Huh?

Ahah! It's defined as a lambda literal at [`lib/puma/configuration.rb:183`][3].

Adding `.call` to the end of `@options[:environment]` on [line 194][2] seemed to fix this issue for me.

`p` to the rescue! 🎉


  [1]: http://ruby-doc.org/core-2.4.1/Kernel.html#method-i-p
  [2]: https://github.com/puma/puma/blob/master/lib/puma/configuration.rb#L194
  [3]: https://github.com/puma/puma/blob/master/lib/puma/configuration.rb#L183
