### ISSUE TITLE
avoid checking socket type per-request

### ISSUE THREAD

**Issue by jjb** [puma/puma#1267]
as of https://github.com/puma/puma/pull/1227, this is being done per-request:

```ruby
def closed_socket?(socket)
  return false unless socket.kind_of? TCPSocket
```

But whether or not it's a TCPSocket isn't a per-request state but a per-server-instantiation state, right? If so, then I believe it's an opportunity to optimize.

I hunted around a bit for where to short-circuit this check but first wanted to ask:

1. am i right that once a server has started, the socket type can't change?
2. what other things can `socket` be? this will help me understand where in the code to put the new logic.

**Comment by nateberkopec** [comment]
> am i right that once a server has started, the socket type can't change?

^^^ @evanphx

**Comment by nateberkopec** [comment]
The answer appears to be "we don't know either."
