### ISSUE TITLE
Puma verbose logging

### ISSUE THREAD

**Issue by jakemack** [puma/puma#1273]
I'm trying to track down the cause of our puma process randomly restarting. To that end, I wanted puma to log more verbosely but I couldn't find any setting to do that. Is there such a setting? As it is, I don't have a sense if it is being killed by the OS and restarted by supervisord, sent a restart signal from chef, or any of the other possible scenarios for a restart. No matter what, I always get the same output from puma, which is

```
[23061] - Gracefully shutting down workers...
[23061] === puma shutdown: 2017-04-12 06:47:20 +0000 ===
[23061] - Goodbye!
[31568] Puma starting in cluster mode...
[31568] * Version 3.6.0 (ruby 2.3.3-p222), codename: Sleepy Sunday Serenity
[31568] * Min threads: 5, max threads: 5
[31568] * Environment: production
[31568] * Process workers: 4
[31568] * Preloading application

```

Even just the addition of a log line saying puma received X signal would at least be a start in my investigations. Any ideas? Thanks in advance!

**Comment by peteygao** [comment]
You can attempt to monkey patch the `SIGTERM` trap handler and have it log whatever info you think you might need to debug this issue. Here's where it's implemented:
https://github.com/puma/puma/blob/ba7fa8a94f30ded70e4d6077c032f8814d4c49ac/lib/puma/cluster.rb#L263

**Comment by jakemack** [comment]
Thanks for the feedback! I'll give it a shot

**Comment by seyonv** [comment]
Somewhat Similar question but more related to formatting. After installing Puma, logs are far uglier and are on multiple lines rather than one HTTP request per line. Don't know if this a result of Puma or another change I made in a configuration setting. The same problem does occur even when booting with Webrick. @jakemack have you had any experience with this issue?

**Comment by jakemack** [comment]
@seyonv, I haven't had any experience with that issue. We've been using a gem called lograge to keep our Rails logs in check as Rails logs are a bit unwieldy by default. Feel free to check it out if you're using Rails, it might just solve all of your anger over log formatting.

@peteygao, thanks for the pointer, I've been able to monkey patch successfully so we'll see if it helps with tracking down our problem! I'll close this issue as my question has been answered

**Comment by seyonv** [comment]
Hope I didn't come across as angry! And the source of the issues was the log entries gem, installed around the same time as I installed Puma. Removing this fixed the issue and now I nice logs while using puma. Thanks for pointing me toward logrsge @jakemack, looked interesting
