### ISSUE TITLE
Does not start without redirect-stdout or redirect-stderr as daemon

### ISSUE THREAD

**Issue by molfar** [puma/puma#1276]
### Steps to reproduce

1) Use mina and mina-puma deploy scripts

2) Try mina puma:start

### Expected behavior

Puma should start as daemon

### Actual behavior

Puma does not start. No visible errors.

### System configuration

ruby 2.3.1p112
rails 5.0.1
puma version 3.8.2

Startup command:
cd /.../current && RAILS_ENV="production" bundle exec puma -q -d -e production -b "unix:///...sockets/puma.sock"  -S /.../sockets/puma.state --pidfile /.../pids/puma.pid --control 'unix:///.../pumactl.sock'

But when I run the same command (generated by mina) manually, in terminal, through ssh session - it works! The same command, no changes.

One more moment. When I add option --redirect-stdout or --redirect-stderr - it successfully starts puma from mina deploy script.

All config for app, puma etc is correct. When testing start puma with no daemon mode - it starts fine in both ways: mina and terminal without any modifications.

**Comment by molfar** [comment]
I notices, when I add custom pause (sleep) after startup command - it works.
It looks like when "* Daemonizing..." is printed, script immediately completes - and puma cant start.
But when I add a extra pause (3 sec) after this command - puma starts well.
This is the second way, in addition to "--redirect-stdout or --redirect-stderr args" i wrote earlier.

**Comment by vonchristian** [comment]
I am experiencing this also. can you please share your systemd service config?

**Comment by molfar** [comment]
I have default rails puma config. No modifications. Rails 5.0.1 and 5.1.1 also.

**Comment by stereobooster** [comment]
> `HUP` reopen log files defined in `stdout_redirect` configuration parameter. If there is no `stdout_redirect` option provided it will behave like `INT`.
> `INT` equivalent of sending `Ctrl-C` to cluster. Will attempt to finish then exit.

I suppose mina uses `HUP` at some point.

**Comment by svoboda-jan** [comment]
I can reproduce this issue with latest puma using only SSH. It seems to happen only when using SSH with the option `-tt` (Force pseudo-tty allocation).

The `-tt` (Force pseudo-tty allocation) option is set by default in all mina ssh commands.

I would recommend something like the following Puma options for Rails applications:
`--redirect-stdout log/production.log --redirect-stderr log/production.log`

**Comment by dekellum** [comment]
I think @stereobooster was correct, the HUP is from ssh session close, and Puma is not going to somehow subvert/work-around this feature of UNIX by doing something different with that signal.  Cc: @nateberkopec, suggest closing.
