### ISSUE TITLE
Warming up puma workers before accepting connections

### ISSUE THREAD

**Issue by raimondasv** [puma/puma#1280]
You can do this in Unicorn, by accessing worker's rack app directly:
```ruby
before_fork do |server, worker|
  require 'rack/test'
  client = Rack::MockRequest.new server.app
  Array(...).each do |url|
    client.get url
  end
end
```

Is there a way of accessing rack app of the Puma worker in `on_worker_boot`?

We cannot use preload_app! because we are using phased restarts.

**Comment by nateberkopec** [comment]
This works for me:

```ruby
APP = Rails.application
on_worker_boot do
  client = ::Rack::MockRequest.new APP
  %w[/].each do |url|
    client.get url
  end
end
```

**Comment by brauliobo** [comment]
do you have an updated code for puma 5? I get `uninitialized constant Rails` with this
