### ISSUE TITLE
: incompatible library version .../gems/puma-3.8.2/lib/puma/puma_http11.so (LoadError)

### ISSUE THREAD

**Issue by jaswinder-trantor** [puma/puma#1286]
### Steps to reproduce

1) Change database from sqlite to postgresql

2) Run rails server

### Expected behavior

It should run rails app server on port 3000

### Actual behavior

Incompatible library error

### System configuration

**Ruby 2.3.1 **:
**Rails 5.1.0 **:

**Comment by nateberkopec** [comment]
This is a problem with your environment. [Try gem pristine.](https://stackoverflow.com/questions/34536351/how-do-i-resolve-incompatible-library-version-for-mysql2-gem-with-ruby-2-3-on)
