### ISSUE TITLE
low-level error reporting broken when used with a plugin

### ISSUE THREAD

**Issue by jjb** [puma/puma#1287]
After upgrading to 3.8.2, low-level error reporting stopped working. Under 3.7.1, it did work. Here is my puma.rb:

```ruby
puts "starting puma config"
plugin :heroku

class PumaRollbarTools
  include Rollbar::RequestDataExtractor
end

lowlevel_error_handler do |error, env|
  puts "lowlevel_error_handler is being invoked"
  Rollbar.scope(request: PumaRollbarTools.new.extract_request_data_from_rack(env)).critical(error)
  [ 500, {},
    [ "An error has occurred, and our engineers have been informed. Please reload the page.\n" ]
  ]
end
puts "ending puma config"
```

Under both versions, "starting puma config" and "ending puma config" are printed when the server starts up. Under 3.7.1, "lowlevel_error_handler" is printed when a low-level error happens and errors are reported to rollbar. Under 3.8.1, "lowlevel_error_handler" is not printed and errors are not reported to rollbar.

Let me know if this isn't enough information. Thanks!

**Comment by nateberkopec** [comment]
I can't repro this on master. 

```ruby
lowlevel_error_handler do |error, env|
  puts "lowlevel_error_handler is being invoked"
  puts error
  puts env
end
```

...followed by 

```
curl -v -X P "http://localhost:3000"
```

...and the error handler is invoked.

**Comment by jjb** [comment]
@nateberkopec thanks for trying, I will attempt to make a minimal reproduction. What does `-X P` do? Send an unhandleable request? curl manpage doesn't seem to explain `P`... thanks!

**Comment by jjb** [comment]
When I remove the `heroku` plugin, behavior returns to normal. I think maybe a bug was introduced in 3.8 which changed how plugins share config with the rest of the config. Here are some possible clues.

I put in these log lines (all the `p`s)

### lib/puma/dsl.rb

```ruby
module Puma
  class DSL
    def initialize(options, config)
p ">>> initializing with #{options.object_id}"
...

    def lowlevel_error_handler(obj=nil, &block)
p ">>> setting lowlevel error handler on #{@options.object_id}"
...
```

### lib/puma/configuration.rb

```ruby
module Puma
  class UserFileDefaultOptions
    def initialize(user_options, default_options)
p ">>> initializing new UserFileDefaultOptions"
...

    def []=(key, value)
p ">>> setting #{key}=#{value}"
...
```

### lib/puma/server.rb

```ruby
module Puma
  class Server
    def lowlevel_error(e, env)
      if handler = @options[:lowlevel_error_handler]
p ">>> there is a handler"
...
      end
p ">>> there is not a handler."
...
```

Here's the output when I start my server:

```
$ rails s
=> Booting Puma
=> Rails 5.1.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
">>> initializing new UserFileDefaultOptions"
">>> initializing with 23033980"
">>> initializing with 36279040"
">>> initializing with 36279260"
starting puma config
">>> setting lowlevel error handler on 36279040"
ending puma config
">>> setting environment=development"
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 1, max threads: 1
* Environment: development
* Listening on tcp://0.0.0.0:8080
Use Ctrl-C to stop
```

note that

1. Puma::DSL is initialized 3 times
2. lowlevel error handler is not set on the most recent one
3. the "setting key=val" message is never printed for lowlevel_error_handler

here's the output when i make a request which raises a lowlevel error:

```
2017-06-01 02:53:11 +0000: Rack app error handling request { GET / }
#<RuntimeError>
config.ru:23:in `call'
/var/lib/gems/2.4.0/gems/puma-3.8.2/lib/puma/configuration.rb:226:in `call'
/var/lib/gems/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:600:in `handle_request'
/var/lib/gems/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:435:in `process_client'
/var/lib/gems/2.4.0/gems/puma-3.8.2/lib/puma/server.rb:299:in `block in run'
/var/lib/gems/2.4.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
">>> there is not a handler."
```

Note that "there is not a handler" is printed.

I didn't do an analogous set of print statements for 3.7. If the above isn't enough to make you know what the problem is, then I can work on making a standalone rails app demonstrating the problem.

Thanks!

**Comment by nateberkopec** [comment]
Pinging @schneems

**Comment by jjb** [comment]
Let me know if the info above isn't sufficient to make a good guess about what happened, then I'll try to make a minimal reproduction.

**Comment by lucascartaxo** [comment]
I feel I've been having the same issue here.

In order to display some custom error pages, I've added a `lowlevel_error_handler` block to handle errors, such as

```ruby
lowlevel_error_handler do |error|
  puts "lowlevel_error_handler is being invoked"
  [500, { 'Content-Type': 'text/html' }, File.open('public/500.html')]
end
```

In order to test it, I forced an exception in my ApplicationController, such as

```ruby
class ApplicationController < ActionController::Base
  before_filter :throw_error

  def throw_error
    throw "error!"
  end
```

However, the `lowlevel_error_handler` was never invoked, even though the `>>> setting lowlevel error handler on [...]"` debug is being printed when I launch my app


After a lot of digging and by following the debug steps proposed by @jjb , the only way I could call the `lowlevel_error_handler` block was by manually thowing an exception around [here](https://github.com/puma/puma/blob/master/lib/puma/server.rb#L606), forcing Puma to rescue [this Exception](https://github.com/puma/puma/blob/master/lib/puma/server.rb#L622)

To me, the `lowlevel_error_handler` block should work like a charm out of the box, but unfortunately that is not the case 😢 

 Is there any other configuration that need to be set up in order to proper call the lowlevel block?

@jjb how are you testing and/or ensuring your `lowlevel_error_handler` is being called?

**Comment by nateberkopec** [comment]
> In order to test it, I forced an exception in my ApplicationController

Yeah, lowlevel_error_handler isn't called in that case. It's only called in particular cases internal to Puma.

**Comment by lucascartaxo** [comment]
That's what I was afraid of. But it makes sense, though. A `lowlevel_error` is not a high level error in the application.

@nateberkopec could you provide some more info about those "particular cases internal to Puma"?

Since my case is not the same as @jjb , I'll slowly retreat.

Thanks for all the help.

**Comment by nateberkopec** [comment]
@lucascartaxo Just search the Puma source for areas where it's called. There's not too many.

**Comment by nateberkopec** [comment]
@jjb can you retry on 3.10.0?

**Comment by jjb** [comment]
Still broken on 3.10.0

With this config.ru

```ruby
require_relative 'config/environment'

class LowLevelTester
  def initialize(app)
    @app = app
  end

  def call(env)
    raise "low level error"

    @app.call(env)
  end
end

use LowLevelTester
run Rails.application
```

and this puma.rb

(puma-heroku plugin is `gem "puma-heroku", github: "jjb/puma-heroku", ref: "78c14f4"`)

```ruby
puts "starting puma config"
plugin :heroku

class PumaRollbarTools
  include Rollbar::RequestDataExtractor
end

lowlevel_error_handler do |error, env|
  puts "lowlevel_error_handler is being invoked"
  Rollbar.scope(request: PumaRollbarTools.new.extract_request_data_from_rack(env)).critical(error)
  [ 500, {},
    [ "An error has occurred, and our engineers have been informed. Please reload the page. If you continue to have problems, contact support@example.com\n" ]
  ]
end
puts "ending puma config"
```

## 3.7.1

```
$ rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development 
=> Run `rails server -h` for more startup options
starting puma config
ending puma config
Puma starting in single mode...
* Version 3.7.1 (ruby 2.4.1-p111), codename: Snowy Sagebrush
* Min threads: 1, max threads: 1
* Environment: development
* Listening on tcp://0.0.0.0:8080
Use Ctrl-C to stop

2017-09-20 21:22:43 +0000: Rack app error handling request { GET / }
#<RuntimeError: low level error>
config.ru:11:in `call'
/var/lib/gems/2.4.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
/var/lib/gems/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
/var/lib/gems/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
/var/lib/gems/2.4.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
/var/lib/gems/2.4.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
lowlevel_error_handler is being invoked
```

```
➔ curl http://platform:8080/
An error has occurred, and our engineers have been informed. Please reload the page. If you continue to have problems, contact support@example.com
```

### 3.10.0

```
$ rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development 
=> Run `rails server -h` for more startup options
starting puma config
ending puma config
Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.1-p111), codename: Russell's Teapot
* Min threads: 1, max threads: 1
* Environment: development
* Listening on tcp://0.0.0.0:8080
Use Ctrl-C to stop
2017-09-20 21:28:17 +0000: Rack app error handling request { GET / }
#<RuntimeError: low level error>
config.ru:11:in `call'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

```
➔ curl http://platform:8080/
Puma caught this error: low level i hope (RuntimeError)
config.ru:11:in `call'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/var/lib/gems/2.4.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'%
```

**Comment by jjb** [comment]
@nateberkopec 🎉 I've made a minimal reproduction repo: https://github.com/jjb/reproduce-puma-1287

**Comment by jjb** [comment]
@nateberkopec maybe whoever deals with the code regarding plugins could look at this?

**Comment by jjb** [comment]
This bug is still happening on 3.11.0. I've updated my repo to reflect this.

**Comment by jjb** [comment]
@evanphx thanks for taking a look at my puma-heroku PRs! Maybe you could also take a look at this issue. It makes lowlevel_error_handler (and maybe other/all config?) not work when using a plugin. I have a recreation repo linked above.

**Comment by nateberkopec** [comment]
This is a misunderstanding of lowlevel_error_handler. Lowlevel_error_handler does not wrap the rack execution context. @jjb's second example made it a little more clear as to what you were expecting to happen.

lowlevel_error_handler is called only for internal puma errors, such as HTTP parse errors.
