### ISSUE TITLE
Puma does not create server.pid  file 

### ISSUE THREAD

**Issue by GBardis** [puma/puma#1288]
I had a problem with puma when i was trying to start my server with rails s command . Server is not starting at all and the error in console was **puma/binder.rb:249:in `gethostbyname': Inappropriate ioctl for device - getaddrinfo (Errno::ENOTTY)**  .The server start only with rails -b 0.0.0.0 and with rails s -b 0.0.0.0 -p 3000 command and not with rails s - p . I finally surpass the problem when i downgrade my version to 3.4.0. 

The issue i have found is that when was in version 3.8.2 i did not have any server.pid file in my rails app and the sever never generate one . The moment i have downgrade to 3.4.0 puma started to generate this file and started working flawlessly.

I hope to help someone with the same problem!!

**Ruby version**: 2.4.0
**Rails version**: 5.0.2

**Comment by nateberkopec** [comment]
I can't reproduce this. Can you please provide your entire config?

It's worth noting what that line actually does:

```ruby
TCPSocket.gethostbyname "localhost"
```

**Comment by GBardis** [comment]
Do you want to see what my  gemfile has inside ?

**Comment by GBardis** [comment]
I found a solution to this problem . The problem was that puma gem was missing from gemfile.lock so delete the file and run bundle install again and the new gemfile.lock has the gem inside and everything came back to normal
