### ISSUE TITLE
Release blocker: JRuby 9k failures

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1292]
Seeing two new failures locally since 3.8:

```
  1) Error:
TestIntegration#test_restart_closes_keepalive_sockets:
Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 9998
    org/jruby/ext/socket/RubyTCPSocket.java:134:in `initialize'
    org/jruby/RubyIO.java:877:in `new'
    /Users/nateberkopec/Code/puma/test/test_integration.rb:218:in `test_restart_closes_keepalive_sockets'


  2) Error:
TestIntegration#test_restart_restores_environment:
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 9998
    org/jruby/ext/socket/RubyTCPSocket.java:134:in `initialize'
    org/jruby/RubyIO.java:877:in `new'
    /Users/nateberkopec/Code/puma/test/test_integration.rb:248:in `test_restart_restores_environment'
```

**Comment by FooBarWidget** [comment]
You sure this is only a JRuby bug? I remember running into macOS kernel bugs that look similar to this. Sometimes when you connect to a TCP server right after creating it, you get connection refused.

**Comment by nateberkopec** [comment]
> macOS kernel bugs that look similar to this 

o great

**Comment by nateberkopec** [comment]
[It looks like it happens on Travis too, so probably not a kernel bug](https://travis-ci.org/puma/puma/jobs/232411633)

**Comment by nateberkopec** [comment]
[Actually, they seem to happen on CRuby too](https://travis-ci.org/puma/puma/jobs/232411625), so not sure why it passes for me locally.

**Comment by nateberkopec** [comment]
Can confirm this started after #1260 was merged.

**Comment by grosser** [comment]
reverting the test changes fixes the issue ... so something went wrong there :/

**Comment by grosser** [comment]
found it ... https://github.com/puma/puma/pull/1304
