### ISSUE TITLE
Port option overridden by default value from puma.config

### ISSUE THREAD

**Issue by msyvr** [puma/puma#1297]
### Steps to reproduce

1) bin/rails s -p4000

### Expected behavior

localhost:4000 should run my app

### Actual behavior

localhost:3000 runs my app (or, if another server is already running on port 3000, the port 4000 server attempt exits)

### System configuration

**Ruby version**: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
**Rails version**: Rails 5.1.1

---
bash command: bin/rails s -p4000

1. output with no other port 3000 server running (browser: app runs on localhost:3000):
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:4000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
Started GET "/" for 127.0.0.1 at 2017-05-18 11:44:54 +0200
Processing by WelcomeController#index as HTML
  Rendering welcome/index.html.erb within layouts/application
  Rendered welcome/index.html.erb within layouts/application (1.3ms)
Completed 200 OK in 351ms (Views: 186.4ms)

2. output with other server on port 3000:
=> Booting Puma
=> Rails 5.1.1 application starting in development on http://localhost:4000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.4.1-p111), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Exiting
/Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/binder.rb:269:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 3000 (Errno::EADDRINUSE)
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/binder.rb:269:in `new'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/binder.rb:269:in `add_tcp_listener'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/binder.rb:105:in `block in parse'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/binder.rb:88:in `each'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/binder.rb:88:in `parse'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/runner.rb:144:in `load_and_bind'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/single.rb:87:in `run'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/puma-3.8.2/lib/rack/handler/puma.rb:64:in `run'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/rack-2.0.3/lib/rack/server.rb:297:in `start'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:44:in `start'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:131:in `block in perform'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1@global/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1@global/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1@global/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/mspisar/code/projects/funkysite/bin/rails:9:in `require'
	from /Users/mspisar/code/projects/funkysite/bin/rails:9:in `<top (required)>'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /Users/mspisar/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/mspisar/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/mspisar/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Users/mspisar/code/projects/funkysite/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by msyvr** [comment]
Relevant note on https://github.com/rails/rails/issues/28971#issuecomment-301613719 by micahbf:
The issue occurs in relation to missed whitespace after -p.
I.e., all clear if -p 4000; issue if -p4000

**Comment by schneems** [comment]
Can you try with puma master? I think this is already fixed

- https://github.com/puma/puma/pull/1277
- https://github.com/puma/puma/pull/1290
