### ISSUE TITLE
Puma as app server and web server in one

### ISSUE THREAD

**Issue by lkananowicz** [puma/puma#1299]
Hi.
First I want to point out that it is more of a question than issue.
We have our current RoR application served by Apache + Passenger stack. However we want to simplify things on the production server and use only one embedded ruby server. The idea is basically to use Puma to serve both static and dynamic resources (no Apache nor nginx required at all). So the question is: do you think Puma will handle it easily on ruby MRI and are there any downsights of such a solution in your opinion?

Thanks
Leon

**Comment by nateberkopec** [comment]
I do this all the time, not a problem.

FWIW you should be smart about HTTP caching and use a CDN - which are things you should be doing with Passenger or any other web server anyway.

**Comment by lkananowicz** [comment]
Thanks for the answer. Sure, CDN is almost a must here. How does puma handle static assets serving, is it serving them directly or leaves that job for Rails (or other framework)?

**Comment by nateberkopec** [comment]
@lkananowicz Puma *and* Rails are involved with serving static files, via http://api.rubyonrails.org/classes/ActionDispatch/Static.html
