### ISSUE TITLE
SO_REUSEPORT

### ISSUE THREAD

**Issue by yosiat** [puma/puma#1307]
Hi!

I am using in Puma and after reading a bit the source code and reading about servers programming.
I found out there is Linux kernel feature which is called SO_REUSEPORT which looks like a great candidate for Puma.

As I understand, what SO_REUSEPORT enables, is instead of creating master/slave processes and share between them the TCP server socket, you create a socket (same port, same address, with SO_REUSEPORT enabled) per worker - and the Linux kernel load balance between all workers.

http://freeprogrammersblog.vhex.net/post/linux-39-introdued-new-way-of-writing-socket-servers/2
https://github.com/rbishop/butterflies

Looks like nice performance opportunity here, what do you think?

**Comment by nateberkopec** [comment]
Creating parent/child processes may still be useful due to the copy-on-write savings. However, I think this option could reduce some of the complexity in the Reactor and improve capacity.

Windows does not support SO_REUSEPORT.

**Comment by stereobooster** [comment]
> However, I think this option could reduce some of the complexity in the Reactor and improve capacity.

Even without this optimisation, it would be possible to start two pumas on the same port with SO_REUSEPORT.

**Comment by yosiat** [comment]
@nateberkopec If I want to try and start implementing it can you give me pointers?

**Comment by yosiat** [comment]
@waghanza this is RESUEADDR which is different than REUSEPORT

**Comment by waghanza** [comment]
@yosiat agreed

`SO_REUSEPORT` is behaving the same way, but **only** on `windows`
https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

my bad

**Comment by waghanza** [comment]
@yosiat I have started PR #1712, feel free to contribute

**Comment by nateberkopec** [comment]
Closing. #1712 investigated this issue and found there was little benefit.

**Comment by schneems** [comment]
Cross-linking my other research and thoughts into SO_REUSEPORT on https://github.com/puma/puma/issues/2078#issuecomment-2394401709

**Comment by nateberkopec** [comment]
Ironically, Claude hallucinated for me yesterday that Puma _already_ used SO_REUSEPORT, probably influenced by this issue!
