### ISSUE TITLE
/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.9.0/lib/puma/launcher.rb:166:in `run': undefined method `clean_env' for Bundler:Module (NoMethodError)

### ISSUE THREAD

**Issue by wangyuan99** [puma/puma#1312]
### Steps to reproduce

1) ...rails new myapp

2) ...cd myapp

3) ...rails server

### Expected behavior

should see:

=> Booting Puma
=> Rails 5.0.3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.8.2 (ruby 2.2.3-p173), codename: Sassy Salamander
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

### Actual behavior

got this:

=> Booting Puma
=> Rails 5.0.3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/usr/local/lib/ruby/gems/2.2.0/gems/puma-3.9.0/lib/puma/launcher.rb:166:in `run': undefined method `clean_env' for Bundler:Module (NoMethodError)

### System configuration

**Ruby version**: 2.2.3
**Rails version**: 5.0.2

**Comment by wangyuan99** [comment]
I was creating new rails applications, and start rails server, everything was working. Then I started creating new applications, then when i start rails server, I got that error message. All new application I created afterward, got that error message. Then  I tried copy the previous working application, the copied application works fine too.

**Comment by nateberkopec** [comment]
Run `gem install bundler`, make sure `bundler -v` says 1.15.0, then try again.

**Comment by nateberkopec** [comment]
What's the best way for us to solve this? You can't do optional dependencies, so I guess we just have to have a code path for "bundler is defined but is old"

**Comment by matobinder** [comment]
I was too about to submit an issue on this, I'm stuck for a bit since I'm building apps in CloudFoundry and the ruby-buildpacks don't yet have the latest version of bundler.

Note I was just looking at bundler source, not that it would probably fix having an older version of bundler, but it looks like Bundler.clean_env is deprecated
https://github.com/bundler/bundler/blob/master/lib/bundler.rb#L257

**Comment by grosser** [comment]
https://github.com/puma/puma/pull/1314

**Comment by nateberkopec** [comment]
@wangyuan99 @matobinder Can either of you try again with Puma master and tell me if that fixes the problem for you? 

```ruby
gem 'puma', github: 'puma/puma'
```

**Comment by matobinder** [comment]
Fixed it for me. I tried it with bundler 1.9.7 and bundler 1.15.1
Going against puma master (fec20f0f05a565a8f5f20e87d1280795ffee901c)

**Comment by nateberkopec** [comment]
Alright, I'll roll up a patch release in a few hours.

**Comment by magedmakled** [comment]
Worked for me as well.  Thanks @nateberkopec

**Comment by nateberkopec** [comment]
Fixed in 3.9.1, out now.

**Comment by wangyuan99** [comment]
yeah, working now. thanks very much!

**Comment by roneen31** [comment]
@nateberkopec  Worked perfectly, thanks.
