### ISSUE TITLE
Loading environment file is broken since 3.8.0

### ISSUE THREAD

**Issue by allaire** [puma/puma#1327]
Loading the right environment file according to the rack environment is broken (https://github.com/puma/puma#configuration-file).

### Steps to reproduce

1) Make sure to create different `config/puma/production.rb`, `config/puma/development.rb` file (you can put `raise "foo"` in the production one)

2) Run `RACK_ENV=production bundle exec puma start`

3) Puma loads development configuration (or at least doesn't load the RACK_ENV's configuration file)

### Expected behavior

Puma should load the right environment file according to the RACK_ENV variable.

### Actual behavior

Puma isn't loading the environment file, even if it shows the right env in the start message. I think it's related to @schneems 's refactor here https://github.com/puma/puma/pull/1234

It works correctly on puma 3.7.x.

It works correctly when we manually specify the configuration file using `-C` switch.

### System configuration

**Ruby version**: 2.2.2
**Rails version**: 4 & 5

**Comment by schneems** [comment]
Broken on 3.9 as well?

**Comment by allaire** [comment]
@schneems Yep!

**Comment by allaire** [comment]
@schneems Great catch, thanks for fixing! 🍻
