### ISSUE TITLE
Need more information about 'Malformed request'

### ISSUE THREAD

**Issue by acearth** [puma/puma#1333]
Today, when I do  a HTTP test,  the HTTP server(puma) tell me the request is malformed. But no more information left.
Server Environment:
Ruby 2.4.1;
Rails  5.1.1;
Puma: Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller

My Request is made by following code snippets:
```
require 'socket'

Socket.tcp("localhost", 3000) {|sock|
  sock.print "POST /info HTTP/1.1\r\n"
  sock.print "HOST: localhost\r\n"
  sock.print "User-Agent: Mozilla/4.o\r\n"
  sock.print "Cookie: name=axq;id=123\r\n"
  sock.print  "\r\n"
  sock.print "body_info=hello&body_title=showMe"
  sock.close_write
  puts sock.read
}
```
The server console log is

---
2017-06-13 21:55:14 +0800: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>

Can anyone tell me how to show detail message about malformed request ?

**Comment by nateberkopec** [comment]
If you register a handler for [`lowlevel_error`](https://github.com/puma/puma/blob/master/lib/puma/dsl.rb#L378), it will be called and you'll have access to the request environment when the parse error occurs.

**Comment by mraj-rpx** [comment]
@acearth: If content-length header is not present then puma client considers the content(After empty CRLF) as another chunk of header and trying to parse using **HttpParser** and hence parser throws **Invalid HTTP format**.

From your code body content **body_info=hello&body_title=showMe** is not a http/1.0 or 1.1 request format and hence parser is raising this error. Also **content-length** is mandatory for http/1.0 or 1.1.

Of course we can improve the parser to raise actual error message, I am looking at the right way. Please share if you have some suggestions.
