### ISSUE TITLE
Question: Workers and Thread counts on clustered mode

### ISSUE THREAD

**Issue by tarciosaraiva** [puma/puma#1343]
### Steps to reproduce

1) Have the following configuration on my `puma.rb`

```
workers 2
threads 1, 1

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  ActiveRecord::Base.establish_connection
end
```

2) Start the app by running `bundle exec puma -C config/puma.rb -d -b tcp://0.0.0.0:3000`

3) Logs say

```
[15819] Puma starting in cluster mode...
[15819] * Version 3.7.1 (ruby 2.3.3-p222), codename: Snowy Sagebrush
[15819] * Min threads: 1, max threads: 1
[15819] * Environment: testing
[15819] * Process workers: 2
[15819] * Preloading application
```

### Expected behavior

App starts, all is well. But I expected to see only 1 thread and 2 workers.

### Actual behavior

Instead I got this
![processes](https://user-images.githubusercontent.com/893428/27523517-fd2ee026-5a70-11e7-89ec-d4ab8e1f47bb.png)

As you can see I can see 2 workers. I'm assuming (big one here) that the subprocesses under each worker are the threads BUT I've setup only 1 thread per process...

What are those?

The documentation says that, in [clustered mode, we should set the number of workers based on the number of cores.](https://github.com/puma/puma#clustered-mode) but it never really goes into detal about the threads.

My knowledge of thread programming is quite shallow and I would like to better understand what's going on here.

### System configuration

**Box**: t2.small on AWS (1 vCPU, 2 GB RAM)
**Ruby version**: 2.3
**Rails version**: 4.2

**Comment by nateberkopec** [comment]
I'm not familiar with the tool you've screenshotted there, so I can't tell you how to interpret it's output. There were issues prior to 3.9 with incorrect configurations being picked up (or defaults overriding options being set elsewhere), please do upgrade.

As for thread counts, it's something of a guess - w/CRuby, you want only as many threads as could possibly be used at the same time. That number is very application-dependent. Rails' default of 5 threads is sane.

**Comment by tarciosaraiva** [comment]
@nateberkopec thanks for the response. The tool in question is `htop`.

I did upgrade but got the same results. Not sure if it's a puma thing or a Rails thing, probably gotta investigate a bit further.

Anyway, will do a bit more digging.

Thanks! :+1:
