### ISSUE TITLE
prune_bundler should optionally allow env variables to be refreshed

### ISSUE THREAD

**Issue by stereobooster** [puma/puma#1351]
There is `prune_bundler` which is good place for env variables reloading. See `imaginary code` part

```ruby
  def prune_bundler
      return unless defined?(Bundler)
      puma = Bundler.rubygems.loaded_specs("puma")
      dirs = puma.require_paths.map { |x| File.join(puma.full_gem_path, x) }
      puma_lib_dir = dirs.detect { |x| File.exist? File.join(x, '../bin/puma-wild') }

      unless puma_lib_dir
        log "! Unable to prune Bundler environment, continuing"
        return
      end

      deps = puma.runtime_dependencies.map do |d|
        spec = Bundler.rubygems.loaded_specs(d.name)
        "#{d.name}:#{spec.version.to_s}"
      end

      log '* Pruning Bundler environment'
      home = ENV['GEM_HOME']
      Bundler.with_clean_env do
        ######## imaginary code start
        ENV.update get_new_env_variables_callback
        ######## imaginary code end
        ENV['GEM_HOME'] = home
        ENV['PUMA_BUNDLER_PRUNED'] = '1'
        wild = File.expand_path(File.join(puma_lib_dir, "../bin/puma-wild"))
        args = [Gem.ruby, wild, '-I', dirs.join(':'), deps.join(',')] + @original_argv
        # Ruby 2.0+ defaults to true which breaks socket activation
        args += [{:close_others => false}] if RUBY_VERSION >= '2.0'
        Kernel.exec(*args)
      end
    end
```

**Comment by salimane** [comment]
any update on this issue ? we are having the same problem

**Comment by jeffling** [comment]
Hi, Any update here?

**Comment by nateberkopec** [comment]
Hm, we already do this [here](https://github.com/puma/puma/blob/70f309b0260815ce5dec5faacf7e51cc742f0dd5/lib/puma/launcher.rb#L192). I don't understand, is there a problem with this?

**Comment by nateberkopec** [comment]
No response, please open a new issue if you're having an issue with env replacement.

**Comment by nateberkopec** [comment]
Nevermind, I misunderstood. The feature request is that we load NEW env variables when restarting, not replace with the old ones.

**Comment by nateberkopec** [comment]
If anyone is watching this issue, commenting with your use case for this feature would help.

**Comment by nateberkopec** [comment]
I've decided we will not support this.

@tlynam made a heroic effort in #2611, but we quickly realized it would me starting a new process and then reading the env variables out of it... yuck.

In general, [POSIX processes are not designed in such a way](https://stackoverflow.com/questions/205064/is-there-a-way-to-change-the-environment-variables-of-another-process-in-unix) that changing environment variables is possible while the process is running. If you want to change environment variables, you need to do a rolling restart.
