### ISSUE TITLE
 *1 connect() to unix:/home/deploy/shared/tmp/sockets/puma.sock failed (2: No such file or directory) 

### ISSUE THREAD

**Issue by rekha014** [puma/puma#1353]
while connecting to upstream, client: , server: localhost, request: "GET / HTTP/1.1", upstream: "http://unix:/home/deploy/shared/tmp/sockets/puma.sock:/500.html", host: "

**Ruby version**: 2.2.2
**Rails version**:5.0.3
Amazon ec2 sever

**Comment by stereobooster** [comment]
Can you provide example application, where it is possible to reproduce error?

**Comment by rekha014** [comment]
https://github.com/rekha014/sawariya_kisan....

Error logs 

[crit] 32144#0: *2 connect() to unix:/home/deploy/sawariya_kisan/shared/tmp/sockets/puma.sock failed (2: No such file or directory) while connecting to upstream, client: 122.175.206.55, server: localhost, request: "GET / HTTP/1.1", upstream: "http://unix:/home/deploy/sawariya_kisan/shared/tmp/sockets/puma.sock:/500.html", host: "34.211.143.161"

**Comment by stereobooster** [comment]
@rekha014 this seems to be log of nginx not Puma, am I right? If so can you post log of Puma

**Comment by hiteshranaut** [comment]
@rekha014 are you able to solve this issue?

**Comment by EssenKh** [comment]
I got the same error  in nginx log errors
