### ISSUE TITLE
tmp_restart without write access to restart.txt

### ISSUE THREAD

**Issue by sriedel** [puma/puma#1355]
I want to propose removing the following check if restart.txt is writable: https://github.com/puma/puma/blob/master/lib/puma/plugin/tmp_restart.rb#L10

Expectation: In a  setup involving multiple users (one deploys and owns any non-runtime writeable file, and another, different user runs the actual application). 
I'd want to be able to restart the application by having the deployment user touching the restart.txt file, without the effective user of the puma process having to have write access to this file. 

Took me a while to figure out why the plugin wasn't working. I see where this test is coming from (issues with the deployment user not having write permissions). However I'd expect to have a warning in the logfile when this situation is encountered, instead of silently just ignoring the file.

**Comment by nateberkopec** [comment]
This was fixed in 3.8. You can now create the file yourself (the deployment user), so the application user doesn't need write permissions.
