### ISSUE TITLE
Puma seems to time out on returning a response

### ISSUE THREAD

**Issue by batasrki** [puma/puma#1359]
### System configuration
Puma --> 3.9.1
JRuby --> 9.1.12.0
Rails --> 4.2.8
nginx --> 1.12.0
Red Hat Enterprise Linux Server release 6.9 (Santiago)
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

### Puma config
```ruby

#!/usr/bin/env puma

directory '/opt/verto/mindmerge-demo/current'
rackup "/opt/verto/mindmerge-demo/current/config.ru"
environment 'production'

tag ''

pidfile "/opt/company/demo/shared/tmp/pids/puma.pid"
state_path "/opt/company/demo/shared/tmp/pids/puma.state"
stdout_redirect '/opt/company/demo/current/log/puma.error.log', '/opt/company/demo/current/log/puma.access.log', true

threads 8,16

bind 'unix:///opt/company/demo/shared/tmp/sockets/puma.sock'

#preload_app!

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/opt/company/demo/current/Gemfile"
end
```
Puma started with: `bundle exec puma -e production -d -C /opt/company/demo/shared/puma.rb`

nginx config:

```
upstream demo {
  server unix:///opt/company/demo/shared/tmp/sockets/mindmerge-puma.sock;
}

server {
      listen   80;
      server_name demo.mindmergeapp.com;
      ## redirect http to https ##
      rewrite        ^ https://demo.mindmergeapp.com$request_uri? permanent;
}

server {
  listen 443 ssl;
  server_name demo.mindmergeapp.com; # change to match your URL
  root /opt/company/demo/current/public;

  ssl on;
  ssl_certificate /etc/ssl/app/SSL.crt;
  ssl_certificate_key /etc/ssl/app/app.net.key;

  access_log /var/log/nginx/nginx.demo.ourpp.com.access.log;
  error_log /var/log/nginx/nginx.demo.ourapp.com.error.log;

  location / {
    proxy_pass http://demo; # match the name of upstream directive which is defined above
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
```

### Steps to reproduce

1) Rails app on JRuby with puma as app server

2) Configure nginx as a reverse proxy. Set up forward of HTTP traffic to HTTPS. Puma is bound to a socket file and nginx points to it correctly.

3) Tail `production.log` and nginx access/error logs.

### Expected behavior

I expect the request to complete without any problems. There is no traffic on the server other than me testing.

### Actual behavior

Even though the Rails app responds right away to the request and logs the response to the `production.log`, there is no view rendered. Only a `504 - Gateway Timeout` is shown, both in the browser and nginx logs.

Here's an example request/response from logs:

```
==> log/production.log <==
# Rails log

Started GET "/" for 99.234.241.234 at 2017-07-07 23:02:47 -0400
Processing by MccsController#index as HTML
  User Load (4.1ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
  Setting Load (1.8ms)  SELECT  `settings`.* FROM `settings`  ORDER BY `settings`.`id` ASC LIMIT 1
  CACHE (0.2ms)  SELECT  `settings`.* FROM `settings`  ORDER BY `settings`.`id` ASC LIMIT 1
  Mcc Load (2.1ms)  SELECT  `mccs`.* FROM `mccs` WHERE `mccs`.`id` = 0 LIMIT 1
  Mcc Load (3.0ms)  SELECT `mccs`.* FROM `mccs` INNER JOIN `mccs_users` ON `mccs`.`id` = `mccs_users`.`mcc_id` WHERE `mccs_users`.`user_id` = 2
  Rendered mccs/index.html.erb within layouts/application (93.9ms)
  Role Load (2.2ms)  SELECT  `roles`.* FROM `roles` WHERE `roles`.`name` = 'admin' LIMIT 1
  Role Exists (2.0ms)  SELECT  1 AS one FROM `roles` INNER JOIN `users_roles` ON `roles`.`id` = `users_roles`.`role_id` WHERE `users_roles`.`user_id` = 2 AND `roles`.`id` = 3 LIMIT 1
  Rendered layouts/_header.html.erb (100.6ms)
  Rendered layouts/_mcc_nav.html.erb (4.7ms)
  Rendered registrations/_edit.html.erb (24.4ms)
  Rendered layouts/_footer.html.erb (3.0ms)
Completed 200 OK in 989ms (Views: 331.9ms | ActiveRecord: 44.2ms)
```

```
# nginx access and error logs
==> /var/log/nginx/nginx.demo.ourapp.com.error.log <==
2017/07/07 23:03:47 [error] 7559#7559: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 99.234.241.234, server: demo.ourapp.com, request: "GET / HTTP/1.1", upstream: "http://unix:///opt/company/demo/shared/tmp/sockets/puma.sock/", host: "demo.ourapp.com"

==> /var/log/nginx/nginx.demo.ourapp.com.access.log <==
99.234.241.234 - - [07/Jul/2017:23:03:47 -0400] "GET / HTTP/1.1" 504 585 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

```

Any help is appreciated.

**Comment by nateberkopec** [comment]
I think your UNIX address for the upstream is wrong. I don't know why you have three slashes after unix:. Docs say just one is necessary, e.g. `unix:/tmp/backend2;`

In any case, this is a problem with your NGINX config, not Puma.

**Comment by batasrki** [comment]
@nateberkopec the unix address for the upstream isn't wrong. I did remove the slashes, as per advice, to no effect.

As you can see in the initial log, the Rails app receives the request proxied by nginx. nginx then times out _waiting_ for the response from upstream. The Rails app completes in a few hundred milliseconds, so it's not a slow upstream client. The _only other_ software sitting in between is puma.

Please re-open this ticket and try the reproduction steps.

**Comment by batasrki** [comment]
@nateberkopec further to the point, I just created an empty Rails app, that has nothing in it other than single controller that does not hit the database.

Everything else is the same, same version of all the things listed above. Same pattern too

### nginx logs

```
==> /var/log/nginx/nginx.demo.toyapp.com.error.log <==
2017/07/08 14:26:27 [error] 27182#27182: *10 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 99.234.241.234, server: demo.toyapp.com, request: "GET / HTTP/1.1", upstream: "http://unix:/opt/company/toyapp/tmp/sockets/puma.sock/", host: "demo.toyapp.com"

==> /var/log/nginx/nginx.demo.toyapp.com.access.log <==
99.234.241.234 - - [08/Jul/2017:14:26:27 -0400] "GET / HTTP/1.1" 504 585 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"
```

### rails log
```
I, [2017-07-08T14:25:27.295651 #27512]  INFO -- : Started GET "/" for 99.234.241.234 at 2017-07-08 14:25:27 -0400
I, [2017-07-08T14:25:27.801902 #27512]  INFO -- : Processing by HomesController#index as HTML
I, [2017-07-08T14:25:28.262647 #27512]  INFO -- :   Rendered homes/index.html.erb within layouts/application (9.6ms)
I, [2017-07-08T14:25:28.288006 #27512]  INFO -- : Completed 200 OK in 484ms (Views: 74.4ms | ActiveRecord: 0.0ms)
```

**Comment by batasrki** [comment]
This pretty much isolates puma as the issue. Do re-open the ticket and take a look, please.

**Comment by nateberkopec** [comment]
```
events { worker_connections 1024; }

http {
  include /etc/nginx/sites-enabled/*;

  upstream demo {
    server unix:/tmp/puma.sock;
  }

  server {
    listen 127.0.0.1:8000;
    server_name  localhost;
    access_log /tmp/demo.access.log;
    error_log /tmp/demo.error.log;

    location / {
      proxy_pass http://unix:/tmp/puma.sock:/uri/; # match the name of upstream directive which is defined above
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_redirect off;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
```

a config.ru

```
run(proc { |_env| ['200', { 'Content-Type' => 'text/plain' }, ['A barebones rack app']] })
```

and running Puma 3.9.1 under JRuby with...
```
puma -b unix:///tmp/puma.sock config.ru
```

...works fine for me. I need you to give me a repository with an nginx.conf that I can run against the config.ru and puma command above to reproduce.

**Comment by batasrki** [comment]
Hey @nateberkopec, is this what you are looking for, https://github.com/batasrki/nginxconf

**Comment by nateberkopec** [comment]
No. [This file](https://github.com/batasrki/nginxconf/blob/master/nginx.conf) has a bunch of stuff related to your application that I will have to delete/modify. What I want is an nginx.conf that reproduces your issue against a basic Rack app and puma command (like above).

I've proven that Puma works properly over a Unix socket with nginx. I can't just debug your nginx.conf for you, so please give me a simple nginx.conf which reproduces the issue.

**Comment by batasrki** [comment]
@nateberkopec in this commit, I've added the default `nginx.conf` as installed by RHEL. The _only_ thing changed is to point to `sites-enabled` conf files, https://github.com/batasrki/nginxconf/commit/4ea769389809728da21985045da710f3161eebab. The problem still happens in the exactly the same manner.

**Comment by batasrki** [comment]
@nateberkopec any news here? I've added a default `nginx.conf` as requested.

**Comment by batasrki** [comment]
@nateberkopec here's a stock `nginx.conf` for Ubuntu 16.04. _Same_ timeout issue happens there.

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    #tcp_nopush     on;
    keepalive_timeout  65;
    #gzip  on;
    #include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*.conf;
}
```

I'm not sure why you are ignoring this.

**Comment by batasrki** [comment]
One thing I noticed in your "works for me" example is that you aren't daemonizing the puma process. I have observed that passing the `-d` flag starts up 2 JVM processes and eventually one ends. I think this is some sort of forking going on. This also occasionally fails to complete, resulting in a hang on startup, but that's a different issue.

**Comment by poc7667** [comment]
@batasrki  any update on this issue? I ran into the same problem for me.
Using the reverse proxy and puma listening on the socket as well. Ubuntu 14

**Comment by batasrki** [comment]
It's a JRuby problem, @poc7667. See the #1375 for details on how to solve it.

**Comment by poc7667** [comment]
thanks so much!

**Comment by austinarchibald** [comment]
@batasrki I am having 504 gateway timeout issue, and any changes to the nginx.conf file is not increasing timeout from 60 seconds. I have a process that can sometimes take longer than 60 seconds. I clicked on the link, but I don't get it. How do I increase the timeout setting if I'm using nginx and puma on my rails server?

**Comment by batasrki** [comment]
@austinarchibald ok, let's unpack this a bit.

## Long requests
You should probably aim to remove any 60 second-plus requests from your system. Not only are those requests far far longer than humans are willing to wait for, it's also a very unnecessary burden on your system. If I were faced with this issue, I'd look to move as much of the processing logic for such a request offline and re-architect the external interface accordingly. For example, if this is a user request, I'd make a UI saying things will take longer to process and provide a link to the eventual result (e-mail or otherwise). If this is an API call, I'd look to leverage a callback URI of some kind and respond to the original request later.

## Direct answer to your question
Having said all of that, I don't know what situation you're facing. Therefore, I will also directly answer your question.
If a request is taking 60+ seconds, you need to adjust both the nginx timeout value _and_ puma's. Here's an [example](https://github.com/puma/puma/blob/master/examples/config.rb#L181-L188) of the puma config.

Feel free to e-mail me directly for any follow-up, so that we don't ping others on this closed issue.

**Comment by ryan2johnson9** [comment]
that link is a 404: https://github.com/puma/puma/blob/master/examples/config.rb#L181-L188

I was interested because my app times out when people are uploading a large image in a post request. But yes the sensible answer would be to process the image upload in a background task. Still I am interested in that link.
