### ISSUE TITLE
Why is Puma starting in cluster mode... with `--workers 1` ?

### ISSUE THREAD

**Issue by ahx** [puma/puma#1364]
### Steps to reproduce
`puma --workers 1`

### Expected behavior
`[98939] Puma starting in single mode...`

### Actual behavior
`[98939] Puma starting in cluster mode...`

### System configuration
**Ruby version**: 2.4.1p111

Is this intended behaviour? 
Is there a difference between single mode and cluster moder with workers = 1?

**Comment by nateberkopec** [comment]
Yes. Single mode is `--worker 0`.

In single mode, there is only one process. In cluster mode, you'll see a worker and master process.
