### ISSUE TITLE
systemd socket activation fails on jruby

### ISSUE THREAD

**Issue by dekellum** [puma/puma#1367]
In #976 a similar problem was reported but without reporter followup. I've finally gotten around to testing on jruby using most recent versions of everything. With later jruby the exception is now somewhat different. At minimum, we could document the incompatibly in /docs/systemd and/or warn/raise a better error message if an attempt is made to use socket activation with jruby. 

### Steps to reproduce

1. Follow /docs/systemd recipe and configure socket activation for a simple test app using latest puma and a recent MRI ruby (2.2.7).  Confirm that this works correctly (e.g. app works through activated socket)

2. Now switch the application to use jruby (9.1.12.0) and restart via systemctl

### Expected behavior

Socket activation works on jruby the same as it does on MRI ruby.

### Actual behavior

Works fine on MRI ruby, but with jruby it fails on startup:

~~~
IOError: closed stream
                    for_fd at org/jruby/ext/socket/RubyBasicSocket.java:109
  block in import_from_env at /home/david/.gem/jruby/2.3.0/gems/puma-3.9.1-java/lib/puma/binder.rb:65
                     times at org/jruby/RubyFixnum.java:305
  block in import_from_env at /home/david/.gem/jruby/2.3.0/gems/puma-3.9.1-java/lib/puma/binder.rb:63
                      each at org/jruby/RubyHash.java:1343
           import_from_env at /home/david/.gem/jruby/2.3.0/gems/puma-3.9.1-java/lib/puma/binder.rb:57
                initialize at /home/david/.gem/jruby/2.3.0/gems/puma-3.9.1-java/lib/puma/launcher.rb:52
                initialize at /home/david/.gem/jruby/2.3.0/gems/puma-3.9.1-java/lib/puma/cli.rb:68
                    <main> at /home/david/.gem/jruby/2.3.0/gems/puma-3.9.1-java/bin/puma:8
                      load at org/jruby/RubyKernel.java:979
                    <main> at /home/david/src/guppy_puma/sbin/puma:17
~~~

### System configuration

**Puma**: 3.9.1
**Ruby version**: jruby 9.1.12.0 (2.3.3) 2017-06-15 33c6439 OpenJDK 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [linux-x86_64]
**Rails version**: N/A

**Comment by dekellum** [comment]
I extracted a minimum reproducible case outside of puma and reported this as jruby/jruby#4715.  I suggest giving them a little time to respond. If this becomes a "known limitation" or not something that will be fixed soon, then I'll submit a PR to document this, advising people not to configure socket activation when using Puma with jruby.

**Comment by nateberkopec** [comment]
Closing this since you merged the warning in #1373.

**Comment by dekellum** [comment]
Fair enough, as there is no clear workaround that puma could implement here and no response on the upstream jruby/jruby#4715 issue.   If you are compiling release notes than please consider this more a _Won't/Can't Fix_ than a _Fix_.

**Comment by nateberkopec** [comment]
Can do.
