### ISSUE TITLE
Contradictory port information on startup

### ISSUE THREAD

**Issue by brian-kephart** [puma/puma#1369]
This is working fine, but giving bad information.

### Steps to reproduce

1) In .env: `PORT=5000`

2) In config/puma.rb (rails app): `port ENV.fetch("PORT") { 5000 }`

3) `rails s`

### Expected behavior

`Rails 5.1.2 application starting in development on http://localhost:5000`
`* Listening on tcp://0.0.0.0:5000`

App is viewable at http://localhost:5000

### Actual behavior

<img width="645" alt="screen shot 2017-07-15 at 3 22 45 pm" src="https://user-images.githubusercontent.com/21235090/28242473-5113a82e-6972-11e7-95eb-882b5e5ffb1e.png">

App is viewable at http://localhost:5000
App is not viewable at http://localhost:3000 (this is correct but contradicts the startup message)

### System configuration

**Ruby version**: 2.4.1
**Rails version**: 5.1.2

**Comment by NickLaMuro** [comment]
@brian-kephart This looks to be a `rails` bug, and not a `puma`.  The correct port is being passed to puma, but Rails is displaying the line incorrectly when outputing `"=> Rails 5.1.2 application starting in development on http://localhost:3000"`:

https://github.com/rails/rails/blob/f8f3d70/railties/lib/rails/commands/server/server_command.rb#L69

I think you probably should report the bug there.

**Comment by brian-kephart** [comment]
Thanks @NickLaMuro. I've created an issue in the Rails repo.
