### ISSUE TITLE
If `user_supplied_variables` is an empty array, puma listens on two addresses

### ISSUE THREAD

**Issue by NickLaMuro** [puma/puma#1371]
Introduced in #1234 (really easier PR number to remember, I must say).

Reproduction steps defined below, but effectively when not providing a `port` option in the `config/puma.rb`, instead of using just the rack defaults of `:Host` and `:Port`, they get combined with the default `binds` of the options because `:user_supplied_variables` de-escalates the user options to "default options" in `lib/rack/handler/puma.rb` when provided, regardless if there are any actually supplied.

This is a bit of a perfect storm things lining up get to this point, and I am not covering the whole picture, but I don't think this the ideal behavior, and is quiet confusing to the end user (the Rails developer in this case).

### Steps to reproduce

1) `rails new --skip-spring new_rails_app`

2) `cd new_rails_app`

3) Delete `port` config in `puma.rb`

4) Run `bin/rails s`

### Expected behavior

The output of the `bin/rails s` startup should show that it is only listening on one address:

```console
$ bin/rails s
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
```

### Actual behavior

Instead, `puma` is booted and listening on two ports:

```console
$ bin/rails s
=> Booting Puma
=> Rails 5.1.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.9.1 (ruby 2.3.3-p222), codename: Private Caller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:9292   <<<<<<
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
```

### System configuration

**Ruby version**:  2.3.3 (probably irrelevant)
**Rails version**:  Rails >= 5.0.3 (when `user_supplied_variables` was added to `rails server`)

**Comment by NickLaMuro** [comment]
cc @schneems

**Comment by nateberkopec** [comment]
Fixed in #1383, I think @schneems just forgot to close.

**Comment by schneems** [comment]
Hmm, it should have been closed automatically by github. Apparently I got my issue number wrong. Thanks for the eyes

**Comment by schneems** [comment]
Ahh, multiple duplicate issues
