### ISSUE TITLE
pumactl restart or SIGUSR2 actually kills puma server instead of restarting

### ISSUE THREAD

**Issue by vizcay** [puma/puma#1378]
### Environment
Puma: 3.9.1
Ruby:  2.3.3p222

I've just configured puma in a new rails 5.0 application, config/puma/production.rb:

```
threads 4, 8
workers 2
bind "unix://tmp/sockets/puma.sock"
daemonize true
preload_app!
activate_control_app "unix://tmp/sockets/pumactl.sock", { auth_token: '12345' }
pidfile "tmp/pids/puma.pid"
state_path "tmp/pids/puma.state"
plugin :tmp_restart

on_worker_boot do
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
end
```
### Problem

Puma runs great by ```bundle exec puma -e production```. I can stop and restart the server by ```bundle exec pumactl -P tmp/pids/puma.pid start``` and ```bundle exec pumactl -P tmp/pids/puma.pid stop```.

But when I try to restart ```bundle exec pumactl -P tmp/pids/puma.pid restart``` the puma server gets killed. Also, I've tried to send the signal directly by ```sudo kill -SIGUSR2 #pid#``` to be sure pumactl is not responsible.

Any ideas?

**Comment by prashantvithani** [comment]
The issue might be similar to https://github.com/puma/puma/issues/1308

**Comment by vizcay** [comment]
@prashantvithani yes it's looks like an exact duplicate, sorry.
