### ISSUE TITLE
Exception handling servers: OpenSSL error: (Puma::MiniSSL::SSLError)

### ISSUE THREAD

**Issue by coldnebo** [puma/puma#1381]
### Steps to reproduce

1) Look at https://github.com/savonrb/httpi

2) bundle exec rake ci

Exception handling servers: OpenSSL error: error:00000001:lib(0):func(0):reason(1) - 1 (Puma::MiniSSL::SSLError)

These errors don't seem to be fatal for some reason, but I'd like to know what they mean.

I suspect that the stored certificates in https://github.com/savonrb/httpi/tree/master/spec/integration/fixtures might be part of the problem considering the configuration in https://github.com/savonrb/httpi/blob/master/spec/integration/support/server.rb:

```ruby
  def self.ssl_ca_file;   integration_fixture("ca_all.pem")  end
  def self.ssl_key_file;  integration_fixture("server.key")  end
  def self.ssl_cert_file; integration_fixture("server.cert") end
 ...
 def ssl_context
    context = Puma::MiniSSL::Context.new

    context.key         = IntegrationServer.ssl_key_file
    context.cert        = IntegrationServer.ssl_cert_file
    context.verify_mode = Puma::MiniSSL::VERIFY_PEER

    context
  end
```

Perhaps these keys/certs are written with outdated or incompatible versions of OpenSSL?  Sorry, I'm not an expert and the error is pretty vague.

### Expected behavior

Puma shouldn't fail with an SSL error.

### Actual behavior

```
$ bundle exec rake ci
/DONOTDELETE/shared/rvm/rubies/ruby-2.3.3/bin/ruby -S rspec spec/httpi/adapter/base_spec.rb spec/httpi/adapter/curb_spec.rb spec/httpi/adapter/em_http_spec.rb spec/httpi/adapter/excon_spec.rb spec/httpi/adapter/http_spec.rb spec/httpi/adapter/httpclient_spec.rb spec/httpi/adapter/net_http_persistent_spec.rb spec/httpi/adapter/net_http_spec.rb spec/httpi/adapter/rack_spec.rb spec/httpi/adapter_spec.rb spec/httpi/auth/config_spec.rb spec/httpi/auth/ssl_spec.rb spec/httpi/cookie_spec.rb spec/httpi/cookie_store_spec.rb spec/httpi/error_spec.rb spec/httpi/httpi_spec.rb spec/httpi/request_spec.rb spec/httpi/response_spec.rb
.........................................................................................................................................................................................................................................................................D, [2017-07-31T16:25:51.455632 #17723] DEBUG -- : Server does not support NTLM/Negotiate. Trying NTLM anyway
.................................................................................*..........................

Pending:
  HTTPI::Adapter::HTTPClient settings: proxy have should specs
    # Not yet implemented
    # ./spec/httpi/adapter/httpclient_spec.rb:72

Finished in 41.29 seconds
373 examples, 0 failures, 1 pending

Randomized with seed 40804

[Coveralls] Outside the CI environment, not sending data.
/DONOTDELETE/shared/rvm/rubies/ruby-2.3.3/bin/ruby -S rspec spec/integration/curb_spec.rb spec/integration/em_http_spec.rb spec/integration/excon_spec.rb spec/integration/http_spec.rb spec/integration/httpclient_spec.rb spec/integration/net_http_persistent_spec.rb spec/integration/net_http_spec.rb
..Exception handling servers: OpenSSL error: error:00000001:lib(0):func(0):reason(1) - 1 (Puma::MiniSSL::SSLError)
/DONOTDELETE/shared/rvm/gems/ruby-2.3.3@httpi/gems/puma-2.3.2/lib/puma/minissl.rb:32:in `read'
/DONOTDELETE/shared/rvm/gems/ruby-2.3.3@httpi/gems/puma-2.3.2/lib/puma/minissl.rb:32:in `read_nonblock'
/DONOTDELETE/shared/rvm/gems/ruby-2.3.3@httpi/gems/puma-2.3.2/lib/puma/client.rb:142:in `try_to_finish'
/DONOTDELETE/shared/rvm/gems/ruby-2.3.3@httpi/gems/puma-2.3.2/lib/puma/client.rb:212:in `eagerly_finish'
/DONOTDELETE/shared/rvm/gems/ruby-2.3.3@httpi/gems/puma-2.3.2/lib/puma/server.rb:137:in `block in run'
/DONOTDELETE/shared/rvm/gems/ruby-2.3.3@httpi/gems/puma-2.3.2/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
.............................................................*..........

Pending:
  HTTPI::Adapter::HTTP http requests supports chunked response
    # Needs investigation
    # ./spec/integration/http_spec.rb:71

Finished in 1.08 seconds
74 examples, 0 failures, 1 pending

Randomized with seed 27043

[Coveralls] Outside the CI environment, not sending data.
```

This also happens within the Travis CI build system.  Ex: 

* https://travis-ci.org/savonrb/httpi/jobs/138746094

### System configuration

**Ruby version**:  ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
**Rails version**: N/A  (httpi is a gem)

**Comment by coldnebo** [comment]
Actually, [this commit](https://github.com/savonrb/httpi/pull/187/commits/696f65027f6480925518126bd9b8c0023a8cdc37) (which unifies two rake subtasks into one) seemed to fix that issue:

```
$ bundle exec rake ci
/DONOTDELETE/shared/rvm/rubies/ruby-2.3.3/bin/ruby -S rspec spec/httpi/adapter/base_spec.rb spec/httpi/adapter/curb_spec.rb spec/httpi/adapter/em_http_spec.rb spec/httpi/adapter/excon_spec.rb spec/httpi/adapter/http_spec.rb spec/httpi/adapter/httpclient_spec.rb spec/httpi/adapter/net_http_persistent_spec.rb spec/httpi/adapter/net_http_spec.rb spec/httpi/adapter/rack_spec.rb spec/httpi/adapter_spec.rb spec/httpi/auth/config_spec.rb spec/httpi/auth/ssl_spec.rb spec/httpi/cookie_spec.rb spec/httpi/cookie_store_spec.rb spec/httpi/error_spec.rb spec/httpi/httpi_spec.rb spec/httpi/request_spec.rb spec/httpi/response_spec.rb spec/integration/curb_spec.rb spec/integration/em_http_spec.rb spec/integration/excon_spec.rb spec/integration/http_spec.rb spec/integration/httpclient_spec.rb spec/integration/net_http_persistent_spec.rb spec/integration/net_http_spec.rb
......................................................................................................................................*....................................................................*...............................................D, [2017-08-01T15:13:21.867062 #21125] DEBUG -- : Server does not support NTLM/Negotiate. Trying NTLM anyway
......................................................................................................................................................................................................

Pending:
  HTTPI::Adapter::HTTPClient settings: proxy have should specs
    # Not yet implemented
    # ./spec/httpi/adapter/httpclient_spec.rb:72
  HTTPI::Adapter::HTTP http requests supports chunked response
    # Needs investigation
    # ./spec/integration/http_spec.rb:71

Finished in 42.26 seconds
449 examples, 0 failures, 2 pending

Randomized with seed 9756

[Coveralls] Outside the CI environment, not sending data.
```

I assume that the original issue was trying to run two instances of the integration server from two Rake subtasks in parallel.

Closing.

**Comment by coldnebo** [comment]
I spoke too soon.  While the issue is fixed on my local, it [still occurs](https://travis-ci.org/savonrb/httpi/jobs/259906318) in Travis.

**Comment by coldnebo** [comment]
It's not fixed on my local either... it seems to be intermittent, not sure why that would be.

Puma is invoked by Rspec before and shutdown by after:

```ruby
  if RUBY_PLATFORM =~ /java/
    pending "Puma Server complains: SSL not supported on JRuby"
  else
    context "https requests" do
      before :all do
        @server = IntegrationServer.run(:ssl => true)
      end
      after :all do
        @server.stop
      end

      it "works when set up properly" do
        request = HTTPI::Request.new(@server.url)
        request.auth.ssl.ca_cert_file = IntegrationServer.ssl_ca_file

        response = HTTPI.get(request, adapter)
        expect(response.body).to eq("get")
      end
    end
  end
```

**Comment by coldnebo** [comment]
The integration server's self-signed certs seem to work ok:

```
$ openssl verify -CAfile ca_all.pem server.cert
server.cert: OK
```

**Comment by nateberkopec** [comment]
I don't understand. You think this is a bug in Puma?

**Comment by nateberkopec** [comment]
Please reopen if you think there's a bug here, but we can't debug your build for you.

**Comment by coldnebo** [comment]
@nateberkopec the error is intermittent and happens in Puma.  We need assistance to figure out what this means:

```
Exception handling servers: OpenSSL error: error:00000001:lib(0):func(0):reason(1) - 1 (Puma::MiniSSL::SSLError)
/home/travis/.rvm/gems/ruby-2.3.0/gems/puma-2.3.2/lib/puma/minissl.rb:32:in `read'
/home/travis/.rvm/gems/ruby-2.3.0/gems/puma-2.3.2/lib/puma/minissl.rb:32:in `read_nonblock'
/home/travis/.rvm/gems/ruby-2.3.0/gems/puma-2.3.2/lib/puma/client.rb:142:in `try_to_finish'
/home/travis/.rvm/gems/ruby-2.3.0/gems/puma-2.3.2/lib/puma/client.rb:212:in `eagerly_finish'
/home/travis/.rvm/gems/ruby-2.3.0/gems/puma-2.3.2/lib/puma/server.rb:137:in `block in run'
/home/travis/.rvm/gems/ruby-2.3.0/gems/puma-2.3.2/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

What does this error actually mean?

And we get this afterwards:

```
Net::HTTP::Persistent::Error:
       too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 7 requests on 38597740, last used 60.479127685 seconds ago
```

**Comment by nateberkopec** [comment]
Obviously our error messages kind of suck (thanks, c extensions!) but you have something misconfigured in your ssl, obviously. There's nothing more you can tell from the error message than that.

**Comment by coldnebo** [comment]
@nateberkopec hmm, if it was misconfigured, it should happen consistently, not intermittently, no?

I was hoping that more details from the underlying libs might shed some light on the specific problem we are running into, but barring that, I still suspect that it has something to do with rspec starting two or more IntegrationServers in parallel.

Conceptually, I can't see much difference between starting two puma servers vs. one, except maybe the server listen address bind?  Or perhaps our IntegrationServer wrapper has some singleton state that isn't threadsafe... this is where I have to dig into the actual details a bit more.

I'll keep looking on my end.  Thanks!

**Comment by coldnebo** [comment]
_Logging my investigations for posterity_

Problem solved on my end. It seemed to be a combination of two issues:

* `OpenSSL error`: a bit of a red-herring that only happened on Puma::Server.stop in a spec intentionally testing a misconfigured SSL connection.
* `Net::HTTP::Persistent::Error: too many connection resets`: when POSTs in the underlying adapter had too long a timeout set.


Here's the details for the interested:

## first (non) issue 

The `Exception handling servers: OpenSSL error` issue was a red herring.  Looking closely at the [Travis CI logs](https://travis-ci.org/savonrb/httpi/jobs/259906318), this error is being raised by the Puma thread pool straight to STDERR, so it doesn't actually register as an error within Rspec.

Next, I added some logging and discovered that error always happens after [the test case](https://github.com/savonrb/httpi/blob/master/spec/integration/curb_spec.rb#L104) where the certs are intentionally **not setup correctly**, duh!  As @nateberkopec said, the error did refer to incorrectly setup SSL:

```ruby
      it "raises when no certificate was set up" do
        expect { HTTPI.post(@server.url, "", adapter) }.to raise_error(HTTPI::SSLError)
      end
```

When this spec runs, the error is raised from HTTPI as expected (client-side), but when the Puma::Server is stopped, there is an intermittent chance of generating the OpenSSL error (server-side) as it tries to gracefully shutdown.  Looking at the Travis log, the server-side error is logged to STDERR directly by the Puma worker thread as it shuts down, so it doesn't actually register in the rspec thread as an error.

## second (real) issue

The second issue **is caught** by rspec as an error:
```
1) HTTPI::Adapter::NetHTTP http requests executes POST requests
     Failure/Error: response = HTTPI.post(@server.url, "<some>xml</some>", adapter)
     Net::HTTP::Persistent::Error:
       too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) after 7 requests on 38597740, last used 60.479127685 seconds ago
     # ./lib/httpi/adapter/net_http_persistent.rb:19:in `perform'
     # ./lib/httpi/adapter/net_http.rb:47:in `block in request'
     # ./lib/httpi/adapter/net_http_persistent.rb:24:in `do_request'
     # ./lib/httpi/adapter/net_http.rb:38:in `request'
     # ./lib/httpi.rb:161:in `request'
     # ./lib/httpi.rb:133:in `post'
     # ./spec/integration/net_http_persistent_spec.rb:40:in `block (3 levels) in <top (required)>'
```

The default timeout in Net:HTTP::Persistent is 5, and [the docs recommend lowering it](https://github.com/drbrain/net-http-persistent/blob/dad5d682a6299e1bb9ef4fed3e2e5837011490bb/History.txt#L181) to avoid resets on POST.  Setting them to 1 seems to have solved the actual issue.

```ruby 
    it "executes POST requests" do
      request = HTTPI::Request.new(url: @server.url, open_timeout: 1, read_timeout: 1, body: "<some>xml</some>")
      
      response = HTTPI.post(request, adapter)
      expect(response.body).to eq("post")
      expect(response.headers["Content-Type"]).to eq("text/plain")
    end
```

Case closed! :)

**Comment by nateberkopec** [comment]
Thanks for reporting back!
