### ISSUE TITLE
30-40% performance difference between single and clustered mode with one worker

### ISSUE THREAD

**Issue by knovoselic** [puma/puma#1387]
I've been working on performance improvements in my app. I've identified a few of critical points in code which I've optimized, and when I was done I've created a script to benchmark my app after each optimization.
After a few days I've mistakenly started puma in cluster mode instead of single mode (I always use single mode while developing). The results were confusing, I thought I did something wrong as all requests were 30-40% slower. Then I've switched back to single mode and got the performance improvement... I'm not sure if this happens only during certain workloads, or applies to all requests. My requests were big JSON uploads, which take some time unfortunately. Check out graph for more info.

### Steps to reproduce

1) Start puma in single mode, measure performance of one longer request (not sure if it applies to fast executing requests)

2) Start puma in clustered mode with only 1 workers, measure performance again. You should see about 30 to 40 percent degradation in performance.

### Expected behavior

I am under impression that puma in single mode and in clustered mode with one worker should perform identically (or very close to identical).

### Actual behavior

Clustered mode is 30-40% slower than single mode. Does that mean that each puma worker is 30-40% slower than when puma is running in single mode?

### System configuration

**Ruby version**: 2.2.5-p319
**Rails version**: 4.2.8

### Puma clustered mode config
```
[34076] Puma starting in cluster mode...
[34076] * Version 3.9.1 (ruby 2.2.5-p319), codename: Private Caller
[34076] * Min threads: 2, max threads: 16
[34076] * Environment: production
[34076] * Process workers: 5
[34076] * Phased restart available
[34076] * Listening on unix:///path/to/puma.sock                                   
[34076] * Daemonizing...
```

### Puma clustered mode boot
```
[34076] Puma starting in cluster mode...
[34076] * Version 3.9.1 (ruby 2.2.5-p319), codename: Private Caller
[34076] * Min threads: 2, max threads: 16
[34076] * Environment: production
[34076] * Process workers: 5
[34076] * Phased restart available
[34076] * Listening on unix:///path/to/puma.sock
[34076] * Daemonizing...
```

### Puma single mode boot
```
Puma starting in single mode...
* Version 3.9.1 (ruby 2.2.5-p319), codename: Private Caller
* Min threads: 0, max threads: 16
* Environment: production
* Listening on unix:///path/to/puma.sock
Use Ctrl-C to stop
```

![puma](https://user-images.githubusercontent.com/7026420/29068995-5007bf86-7c39-11e7-93d6-da383052d3e7.png)

**Comment by nateberkopec** [comment]
> My requests were big JSON uploads, which take some time unfortunately. 

This could definitely have something to do with it.

Can you share any kind of test application for this? Just a Rack app that accepts some file uploads, I guess?

**Comment by nateberkopec** [comment]
Never got a repro here. My guess is that system calls tend to be slower in forked processes, especially on Mac.
