### ISSUE TITLE
Return incorrect header value

### ISSUE THREAD

**Issue by Maghraby** [puma/puma#1400]
### Steps to reproduce

1- Running rails with puma server, sending `version` in headers
```bash
curl -X GET "http://localhost:3000" -H "accept: application/json" -H "version: 6"
```
### Expected behavior
expect to get `version` value with `6`
### Actual behavior
Get this value` "HTTP/1.1, 6"`
### System configuration

**Ruby version**: 2.4.1
**Rails version**: 5.1.2
**Puma version**: 3.9.1

**Comment by stereobooster** [comment]
Need more steps of reproduction. How exactly you send response headers?
