### ISSUE TITLE
rackup file from puma command line is ignored and server won't start.

### ISSUE THREAD

**Issue by nitzanav** [puma/puma#1401]
### Steps to reproduce

1) updrade to puma 3.10.0

2) rename the config.ru to config2.ru for example

3) run `bundle exec puma -C config/puma2.rb config2.ru`

### Expected behavior
The puma server should load with no error.

When I renamed config_sidekiq_web.ru to config.ru it works. But I need two "ru" files to enable two separate applications on the same codebase.

### Actual behavior

```
$ ls -l *.ru
-rw-r--r--  1 Nitzan  staff  951 Aug 28 16:36 config_sidekiq_web.ru
$ bundle exec puma -C app/workers/client_web_puma.rb config_sidekiq_web.ru
[34150] Puma starting in cluster mode...
[34150] * Version 3.10.0 (ruby 2.3.0-p0), codename: Russell's Teapot
[34150] * Min threads: 20, max threads: 20
[34150] * Environment: development
[34150] * Process workers: 2
[34150] * Preloading application
[34150] ERROR: No application configured, nothing to run
```
BUT, when I renamed the `config_sidekiq_web.ru` file to `config.ru` it works, it doesn't even tell me that the `config_sidekiq_web.ru` file is not in place.

```
$ ls -l *.ru
-rw-r--r--  1 Nitzan  staff  951 Aug 28 16:36 config_sidekiq_web.ru
$ mv config_sidekiq_web.ru config.ru
$ ls -l *.ru
-rw-r--r--  1 Nitzan  staff  951 Aug 28 16:36 config.ru
$ bundle exec puma -C app/workers/client_web_puma.rb config_sidekiq_web.ru
[34258] Puma starting in cluster mode...
[34258] * Version 3.10.0 (ruby 2.3.0-p0), codename: Russell's Teapot
[34258] * Min threads: 20, max threads: 20
[34258] * Environment: development
[34258] * Process workers: 2
[34258] * Preloading application
[34258] * Listening on tcp://0.0.0.0:3000
[34258] Use Ctrl-C to stop
[34258] - Worker 0 (pid: 34259) booted, phase: 0
[34258] - Worker 1 (pid: 34260) booted, phase: 0
```

### System configuration

**Ruby version**: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
**Rails version**: none - no rails.
**Puma version**: Version 3.10.0 (ruby 2.3.0-p0)

### Workarounds I tried
```
$ rackup -s puma config_sidekiq_web.ru
.../config_sidekiq_web.ru:26:in `block in <main>': uninitialized constant Sinatra (NameError)
```

because I don't know how to pass the "-C app/workers/client_web_puma.rb" parameter to rackup command line.

# Update:
my Gemfile.lock:
```
    puma (3.10.0)
    puma_worker_killer (0.1.0)
      get_process_mem (~> 0.2)
      puma (>= 2.7, < 4)
````
And this is the last version that works for me:
```
    puma (3.6.2)
    puma_worker_killer (0.1.0)
      get_process_mem (~> 0.2)
      puma (>= 2.7, < 4)
```

**Comment by stereobooster** [comment]
What is inside `config/puma2.rb`?

```
$ rackup -s puma config_sidekiq_web.ru
.../config_sidekiq_web.ru:26:in `block in <main>': uninitialized constant Sinatra (NameError)
```

`bundle exec` ?

**Comment by nitzanav** [comment]
Hi,

the `config/puma2.rb` had `active_record` and `sinatra/activerecord` gems dependency which caused the Name Error. I happened to remove those dependencies from the entire app.

And I managed to use the same and default puma.rb file cross all runtime of the app (I added "if" based on the environment variables").

So, I managed to solve it, I personally don't need the fix.

But you might want to fix it anyway since `bundle exec puma -C config/puma2.rb config2.ru` still doesn't work.

so if you like I can verify it once the bug is fixed.

**Comment by Epigene** [comment]
This is still relevant on v3.11.2

I am following along Rails' [ActionCable standalone](https://github.com/rails/rails/tree/master/actioncable#standalone) server setup and having a cable-booting binstub like so

```rb
#!/bin/bash
bundle exec puma -C cable/puma.rb cable/config.ru
```
ignores the "cable/config.ru" and instead uses the default `config.ru` file in project root. This can be easily confirmed by renaming the default `config.ru` and having puma fail at boot with:

```
Cable Puma initializing for 'development'
Puma starting in single mode...
* Version 3.11.2 (ruby 2.4.2-p198), codename: Love Song
* Min threads: 1, max threads: 8
* Environment: development
ERROR: No application configured, nothing to run
```

**Comment by 99cm** [comment]
I run into similar error:
# puma start
[10574] Puma starting in cluster mode...
[10574] * Version 3.11.2 (ruby 2.5.0-p0), codename: Love Song
[10574] * Min threads: 2, max threads: 8
[10574] * Environment: development
[10574] * Process workers: 4
[10574] * Phased restart available
[10574] ERROR: No application configured, nothing to run

**Comment by khmunkhbat** [comment]
is there any progress?

**Comment by nateberkopec** [comment]
This kind of reminds me of 9faca801b07cfd4cda5d4bf69dafb0

**Comment by blelump** [comment]
With version 3.12.0 the problem still occurs.

**Comment by Overload119** [comment]
I had a similar error message after upgrading to 3.12
You want to make sure in `puma.rb` you are configuring the application directory and the rackup.

```
app_dir = File.join(File.expand_path("../../..", __FILE__), 'current')
directory app_dir
rackup "#{app_dir}/config.ru"
```

In `config.ru` I have this:

```
# This file is used by Rack-based servers to start the application.

require_relative 'config/environment'

run Rails.application
```

To help with debugging, using something like `puts app_dir` to make sure the directory makes sense for your use case.

**Comment by blelump** [comment]
@Overload119 , please note that the issue is not about `config.ru` internals, but about using config with different file name.

**Comment by nateberkopec** [comment]
I think this is probably not a Puma bug. We actually have plenty of test coverage on this, and I can confirm this works on master. I suspect there is an issue with people's envs that we're not seeing.

If you're experiencing this issue, please ask for reopen if you have a set of files or a docker container than can repro.

**Comment by Uysim** [comment]
I am facing this problem in elastic beanstalk for 2 two days already. Anyone got idea what is the cause of this?

**Comment by HassanAkbar** [comment]
Hi @Uysim, I am having the same issue. Were you able to figure this out?
