### ISSUE TITLE
Rack app instantiated multiple times in worker

### ISSUE THREAD

**Issue by tja** [puma/puma#1402]
### Steps to reproduce

1) Take a simple web app (framework shouldn't matter, but I used Sinatra) and dump the `pid` during setup, like this:

```ruby
class TestApp < Sinatra::Base
  def initialize(app = nil)
    super
    puts "===> #{Process.pid}"
  end

  # Route implementation omitted for simplicity
end
```

2) Start `puma` in cluster mode (one worker is enough)

3) Blast a bunch of requests to the app, e.g. with `ab`

### Expected behavior

The app should only be instantiated once, i.e. each `pid` should be printed out only once.

### Actual behavior

The same `pid` is printed multiple times, i.e. the rack app has been instantiated multiple times.

Maybe this is by design, in which case I would recommend pointing out the behaviour more prominently in the documentation. I wasn't expecting multiple instances of my rack app in a worker, and several threads I spawned during app setup where stepping on each others feet.

### System configuration

**Ruby version**: `2.4.1`
**Puma version**: `3.10`

**Comment by nateberkopec** [comment]
> I wasn't expecting multiple instances of my rack app in a worker

This doesn't happen if you run Puma with 1 thread, correct?

**Comment by tja** [comment]
I would assume you're right, but It'll take a few days to get a definitive answer to that.

However, do you say this is expected behavior for threads>1? Wouldn't it be useful to protect the app creation be a mutex or spin lock?

**Comment by nateberkopec** [comment]
If you want just one instance of an application in Puma, use Rack::Lock or 1 thread.
