### ISSUE TITLE
omitting empty header values in 3.9 on generating strange behaviour for x-frame-options

### ISSUE THREAD

**Issue by ilgianlu** [puma/puma#1404]
### Steps to reproduce

1) rails 5.0.5 application with a page
2) set in application.rb
config.action_dispatch.default_headers['X-Frame-Options'] = ''
3) include the page in another page as iframe

### Expected behavior
I know "X-Frame-Options" header has (at least) blurry support for browsers
but until puma 3.8.1
in chrome console no errors, in firefox console no errors
(x-frame-options is recognized and iframe loaded)

From puma 3.9 on
error in chrome console
Invalid 'X-Frame-Options' header encountered when loading 'http://localhost:3000/widg.....': '' is not a recognized directive. The header will be ignored.
(x-frame-options is recognized anyway and iframe loaded)

in firefox console no errors

### System configuration

Ruby 2.3.3
Rails 5.0.5
Upgrading 3.8.1 to 3.9.1

**Comment by nateberkopec** [comment]
Can you post the actual response headers you're getting from 3.8.1 and 3.9?

**Comment by nateberkopec** [comment]
Also, relevant commit & test: https://github.com/puma/puma/commit/eea4dbb4379011dbb78d0a957836cff20dcebc51

**Comment by ilgianlu** [comment]
sure! 
from chrome console network: 
puma 3.8
```
Cache-Control:max-age=0, private, must-revalidate
Content-Type:text/html; charset=utf-8
ETag:W/"9c561b253093388e19645ac3480121be"
Set-Cookie:_test_x_frame_session=OEFvK540; path=/; HttpOnly
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
X-Request-Id:fe93ea84-df83-4594-9706-cc40ba60c01d
X-Runtime:0.467880
X-XSS-Protection:1; mode=block
```

puma 3.9
```
Cache-Control:max-age=0, private, must-revalidate
Content-Type:text/html; charset=utf-8
ETag:W/"a730b5d9c62c65d0724f0bd2b42bf020"
Set-Cookie:_test_x_frame_session=MzBJeDd1a0ee; path=/; HttpOnly
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
X-Frame-Options:
X-Request-Id:dcc5dec8-d30b-40bb-8b6f-d27db99c5f3e
X-Runtime:0.420466
X-XSS-Protection:1; mode=block
```

(I compressed Set-Cookie header for convenience)

**Comment by nateberkopec** [comment]
3.9 is showing the correct behavior. You set the header to an empty string, which is a valid header value. In 3.8 we omitted the header, which was incorrect.

Instead of setting the header to an empty string, delete the key:

```ruby
config.action_dispatch.default_headers.delete('X-Frame-Options')
```
