### ISSUE TITLE
High queue latency over TCP when under heavy load

### ISSUE THREAD

**Issue by stereobooster** [puma/puma#1405]
On high load requests stay too long in queue. Reproducible example is [here](https://github.com/stereobooster/puma-benchmarks). For comparison:

Puma (unix socket) requests in queue wait for **6-14s** (9 in average)

![](https://raw.githubusercontent.com/stereobooster/puma-benchmarks/master/img/latency-puma-unix.png)

Puma (TCP) requests in queue wait for **8-52s**

![](https://raw.githubusercontent.com/stereobooster/puma-benchmarks/master/img/latency-puma.png)

Time in queue - time from the moment when request arrived to nginx to the moment when request dispatched to rack server. Example code contains code responsible for measuring and code to build graphs with gnuplot 

**But** [unix socket can not detect disconnected clients](https://github.com/puma/puma/blob/1f8e92af42627fef9172df0dc1dacd0617d8848c/lib/puma/server.rb#L126)

<details>
<summary>Old description of issue</summary>
So I want to migrate one of my servers to Puma. I did small stress test. Test setup:
- AWS t2.small instance, Ubuntu 14.04.5 LTS x86_64
- attacking with [vegeta](https://github.com/tsenart/vegeta) (`vegeta attack -targets=targets.txt -rate=100 -workers=100`)
- Rails application v4.2.8, Ruby 2.3.3 MRI, Puma 3.9.1, behind reverse proxy (nginx)

And I see something I wasn't expecting. **Is there any chance this is known issue?** I assume this is not the problem of OS or Application, because Unicorn performs fine. Also I wonder why TCP socket performs so poor compared to unix socket. Did I misconfigured something?

1. Puma setup 1:
```
workers "1"
bind "unix:///srv/app/shared/sockets/app.sock?backlog=1024"
threads_count = 20
threads threads_count, threads_count
```

2. Puma setup 2:
```
workers "1"
bind "tcp://127.0.0.1:9292?backlog=1024"
threads_count = 20
threads threads_count, threads_count
```

3. Unicorn setup:
```
worker_processes 4
listen "unix:///srv/app/shared/sockets/app.sock", backlog: 1024
```

### Response statuses distribution

<img width="745" alt="status distribution" src="https://user-images.githubusercontent.com/179534/29920659-add843fc-8e4e-11e7-904c-62cb20c88f17.png">

### Queue latency

I measure queue latency by setting timestamp as a header in nginx and reading it in Rack middleware. The same way as [newrelic does it](https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples). Values are in milliseconds. Graph shows 1, 50 and 99 percentiles.

<img width="814" alt="queue latency" src="https://user-images.githubusercontent.com/179534/29920728-0f8e8f16-8e4f-11e7-937f-8aa51195fd2d.png">

#### 1. Puma over Unix socket

![vegeta-plot 1](https://user-images.githubusercontent.com/179534/29920771-5461b9b0-8e4f-11e7-9e5b-f2049922395c.png)

#### 2. Puma over TCP socket

![vegeta-plot 2](https://user-images.githubusercontent.com/179534/29920776-5f86bf16-8e4f-11e7-86b3-198be054e493.png)

#### 3. Unicorn

![vegeta-plot 3](https://user-images.githubusercontent.com/179534/29920783-6a248b4c-8e4f-11e7-8db2-ccc0b2b2d39d.png)

Related https://github.com/puma/puma/issues/1387 ?

UPD: **500** errors in "Response statuses distribution" were coming  from nginx `failed (24: Too many open files)`.  Increased `worker_rlimit_nofile` and it went away.
</details>

**Comment by stereobooster** [comment]
This is not resolved. I runed test for a longer time and there is still an issue.

Setup:

```
workers 0
bind "tcp://127.0.0.1:9292?backlog=1024"
threads_count = 50
threads threads_count, threads_count
```

Queue delay:

<img width="839" alt="screen shot 2017-09-04 at 17 05 19" src="https://user-images.githubusercontent.com/179534/30032152-7f0979bc-9194-11e7-9efd-4562b29d3b64.png">

While memory and CPU are stabile

<img width="538" alt="screen shot 2017-09-04 at 17 04 04" src="https://user-images.githubusercontent.com/179534/30032206-ca15e210-9194-11e7-9358-a23c3a1f0a35.png">

<img width="540" alt="screen shot 2017-09-04 at 17 04 23" src="https://user-images.githubusercontent.com/179534/30032207-ca1c0c1c-9194-11e7-8e8f-276857b70916.png">

**Comment by stereobooster** [comment]
@nateberkopec do I get it right?

From `queue_requests` docs

    # When set to true (the default), workers accept all requests
    # and queue them before passing them to the handlers.

So in my scenario I'm able to flood request queue and queue latency gets super high. This is why on vegeta plot time of response is jumping that much. While unicorn does not accept more items in queue than backlog specifies, and that is why it is able to keep queue latency stabile.

**Comment by danshultz** [comment]
Hmm - it seems `queue_requests` was accidentally removed in this PR https://github.com/puma/puma/pull/1278

**Comment by stereobooster** [comment]
I got reports on GC with trashed gem - to make sure there is no issues due to GC pauses. Also looking into how to instrument Puma to report queue length and number of threads. Related https://github.com/basecamp/trashed/pull/12

@danshultz thanks for the clue

**Comment by danshultz** [comment]
@stereobooster - I'm using a similar process as I [outlined for unicorn](weavingcode.blogspot.com/2014/03/keeping-track-of-unicorn-workers.html) for tracking queue depth with Puma. The difference is, the `active` requests are all those within a worker, waiting to be serviced by a thread.

In Puma <= 1.8.x, with `queue_requests(false)`, you should never see more requests active than you have workers. You would see queued requests in the event you have more requests than workers available.

**Comment by stereobooster** [comment]
As of queue delay. Here is how I measure it:

nginx conf

```
server {
  ...
  proxy_set_header X-Request-Start "${msec}";
  ...
}
```
Rack middleware

```ruby
module Application
  module Rack
    class RequestLogger
      HTTP_X_REQUEST_START = "HTTP_X_REQUEST_START"

      def initialize(app)
        @app = app
      end

      def call(env)
         began_at = Time.now.to_f
         if env[HTTP_X_REQUEST_START]
           request_latency = ((began_at - env[HTTP_X_REQUEST_START].to_f) * 1000).round(3)
         end
         @app.call(env)
      end
   end
end
```

As soon I will get other recipes will post it too

**Comment by stereobooster** [comment]
Backlog vs response time

![vegeta-plot 10](https://user-images.githubusercontent.com/179534/30649439-8ffc189a-9e20-11e7-9e8b-6e3e2c8d0f6e.png)

![requests](https://user-images.githubusercontent.com/179534/30649462-9e6e66da-9e20-11e7-81c8-0aae8cb78212.png)

**Comment by nateberkopec** [comment]
Your last comment looks almost like "expected behavior" if ~100 requests show up at once and each take 10-300 ms to process. The backlog will immediately get pretty long and take a while to process with a single Puma worker.

**Comment by stereobooster** [comment]
But I want to be able to instruct Puma, to reject requests immediately if it is more than some number, like in Unicron I'm able to set backlog size to 1024, so delay in queue never gets higher than 2s. While in Puma that number can get upto 60s (after which connection will be reseted by nginx).

**Comment by nateberkopec** [comment]
@stereobooster Ah, but you can: https://github.com/puma/puma/blob/4db1dcd28181f83bca94db41f736d3d6f6aad8ed/lib/puma/binder.rb#L102

**Comment by stereobooster** [comment]
I did

```
bind "unix:///srv/app/shared/sockets/app.sock?backlog=1024"
```

but it has no effect. At least it is not the same as in Unicorn. In Unicorn if I get higher than 70rps I start to get errors, but time in queue does not get higher than 2s. In Puma start to get errors and time in queue can jump up to 25s. If I get to 100rps time in queue jumps to 10s in average

**Comment by stereobooster** [comment]
I want to create reproducible benchmark https://github.com/stereobooster/puma-benchmarks

**Comment by stereobooster** [comment]
So I created reproducible benchmarks https://github.com/stereobooster/puma-benchmarks. It is clearly shows how Puma queue is much slower than Unicorn (see graphs for latency).

**Comment by eprothro** [comment]
@stereobooster replying here from your ping on #1453:

Short answer, yes, the `Reactor` (e.g. `queue_requests=true`) could certainly be sucking up more requests than it should be.

Some details:

The backlog stat may not be what you think it is. 

  * The puma 'backlog' stat is NOT the depth of the socket backlog (see link below).
  * A puma "backlog" of zero does NOT necessarily mean that puma is keeping up with the pressure from the client (the request "queue" buffer and/or the socket could have their own backlogs)
  * The puma "backlog" stat is only updated once every 5 seconds

https://github.com/eprothro/puma/blob/4cad6b449e1dc89ff492752b62f4016b7261869e/docs/architecture.md

Those things I'm pretty sure of. To be clear, I will refer to the puma backlog stat as the "work queue", as to clearly differentiate it from the "socket backlog".

I'm less sure of the rest, but if I'm reasoning about this correctly, as of 3.9: 

1. puma should only accept a request if there is a waiting worker thread
2. waiting worker threads will be signaled immediately when a connection is added to the work queue

So, in my mind:
* The work queue should essentially always be zero or nearly zero
*  If it's not, there is a bug with Puma (e.g. 1453)

Questions:
* What version of puma are you using?
  * You say above _I tested `queue_requests` false it doesn't change the picture. But I still believe the problem is in how Puma processes queue_. This should not be the case as of 3.9. disabling this option should make a **drastic** difference for a test driving saturation.
* How deep is your socket backlog?
* Are your errors 502's from Nginx? See #1449 
* Are you measuring response time at the nginx plane or the puma/app plane?

**Comment by stereobooster** [comment]
> What version of puma are you using?

3.10.0 https://github.com/stereobooster/puma-benchmarks/blob/master/benchmark/Gemfile.lock

> How deep is your socket backlog?

1024 https://github.com/stereobooster/puma-benchmarks/blob/master/benchmark/puma-config.rb

> Are your errors 502's from Nginx

Need to check. Do not remember

> Are you measuring response time at the nginx plane or the puma/app plane?

I measure the time between request landed in nginx and it get to Rack app. https://github.com/stereobooster/puma-benchmarks/blob/master/benchmark/config.ru#L44

**Comment by eprothro** [comment]
Regarding the last question, I was asking about the latency on the `Backlog vs response time` chart. I assume that is nginx `$request_time` or `$upstream_response_time`.

To be specific:

1. Ngnix waits to establish a connection to the socket
    * This will happen immediately unless the **socket** backlog is full
    * If backlog is full, the connection is refused
1. Nginx waits for puma to accept the connection
    * The connection is in the socket backlog at this point
    * This happens as soon as there is a non-busy worker
    * If never accepted, the connection will eventually time-out
1. Puma waits for the request to be read from connection
    * With `queue_requests` enabled, this happens asynchronously from the worker thread pool
1. Puma waits for a worker thread to begin work on the request
    * This **should** happen immediately as of 3.9
    * This might not happen immediately because of #1453 
1. Puma waits for a response from the app
1. Puma waits for the response to be written to the connection

Seeing the time spent in the app (step 5) as distinct from the total time nginx waited (Steps 1-6, plus other items too) could help isolate the issue further and aid diagnosis.

**Comment by stereobooster** [comment]
response time in "vegeta" graphs is total time from client point of view. Vegeta is a tool like wrk. https://github.com/tsenart/vegeta

**Comment by eprothro** [comment]
@stereobooster if you want to test your theory, here is a spike at a version of puma that shouldn't overcommit it's worker pool:

https://github.com/eprothro/puma/tree/eprothro-14353-fix

I would NOT use this in production, yet, for the record ;)

**Comment by dalpo** [comment]
Any news about this issue?

I'm having the same troubles... 🤔

**Comment by nateberkopec** [comment]
Request queue time is usually not a Puma bug but a sign that you have too few server resources or you have misconfigured Puma.

**Comment by stereobooster** [comment]
As far as I remember I resolved issue using nginx config. I restricted number of simultaneous connection to 1024, so nginx drops connections over the limit (without sending it to puma).

**Comment by dalpo** [comment]
Thank you @nateberkopec and @stereobooster for your quick answer. I really appreciated that :)

I was working on a small industrial single board computer, with a lot of TCP traffic, and probably the main reason for this behavior were the small hardware resources.

Anyway I noticed that after the upgrade to puma `v4.0.1` from `v3.12.0` the issue related to socket backlog overload disappeared. Maybe due to the refactor of the Reactor with nio4r?

**Comment by Jesus** [comment]
I can't assure that the issue disappeared due to switching to nio4r, but I can tell you that nio4r should be taking less resources under same heavy loads. So yes, it could be due to that.
