### ISSUE TITLE
502 Bad Gateway nginx + puma + ruby 2.3.0 

### ISSUE THREAD

**Issue by 99cm** [puma/puma#1406]
### Steps to reproduce

1) ... # RAILS_ENV=production rails s
=> Booting Puma
=> Rails 5.0.2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
[8534] Puma starting in cluster mode...
[8534] * Version 3.8.2 (ruby 2.3.0-p0), codename: Sassy Salamander
[8534] * Min threads: 2, max threads: 8
[8534] * Environment: production
[8534] * Process workers: 4
[8534] * Phased restart available
[8534] * Listening on tcp://0.0.0.0:3000
[8534] Use Ctrl-C to stop

2) ...browser url https://ypill.com/
response: 502 Bad Gateway
nginx/1.10.2

3) ... If directly run puma
# puma
[11972] Puma starting in cluster mode...
[11972] * Version 3.8.2 (ruby 2.3.0-p0), codename: Sassy Salamander
[11972] * Min threads: 2, max threads: 8
[11972] * Environment: development
[11972] * Process workers: 4
[11972] * Phased restart available
[11972] * Listening on unix:///home/ypill/tcm/shared/sockets/puma.sock
[11972] Use Ctrl-C to stop

4) ... browser url: https://ypill.com
response: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)

### Expected behavior

Tell us what should happen ...

### Actual behavior

Tell us what happens instead ...

### System configuration

**Ruby version**: 2.3.0
**Rails version**: 5.0.2
**Puma version**: 3.8.2

Here is config/puma.rb:
`# Change to match your CPU core count
workers 4

# Min and Max threads per worker
threads 2, 8

app_dir = File.expand_path("../..", __FILE__)
shared_dir = "#{app_dir}/shared"

# Default to production
rails_env = ENV['RAILS_ENV'] || "development"
environment rails_env

# Set up socket location
bind "unix://#{shared_dir}/sockets/puma.sock"

# Logging
stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true

# Set master PID and state locations
pidfile "#{shared_dir}/pids/puma.pid"
state_path "#{shared_dir}/pids/puma.state"
activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
end
`
Here is config/nginx.conf:
`upstream ypill {
  # fail_timeout=0 means we always retry an upstream even if it failed
  # to return a good HTTP response (in case the Unicorn master nukes a
  # single worker for timing out).
  server unix:/home/ypill/tcm/shared/sockets/puma.sock fail_timeout=0;
  #server 127.0.0.1:3000;
}

server {
  listen 80 default_server deferred;
  server_name ypill.com;
  listen 443 ssl http2 default_server;
  
  ssl_certificate /home/ypill/ssl/certs/_wildcard__ypill_com_b1902_2cf85_1512234387_5a202e0ca8b461a2820e4b479148df47.crt;
  ssl_certificate_key /home/ypill/ssl/keys/b1902_2cf85_98f6dd894c31d6e7e0e222e013d4c7ef.key;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers         HIGH:!aNULL:!MD5;
  ssl_prefer_server_ciphers on;

  add_header Strict-Transport-Security max-age=15768000;
  root /home/ypill/tcm/public;
  access_log /home/ypill/tcm/log/nginx_access.log;
  error_log /home/ypill/tcm/log/nginx_error.log info;
  rewrite_log on;

  location ^~ /assets/  {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }

  try_files $uri/index.html $uri @ypill;
  location @ypill {
    #all requests are sent to the UNIX socket
    proxy_pass http://ypill;
    proxy_redirect off;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    client_max_body_size 10m;
    client_body_buffer_size 2m;
    
    proxy_connect_timeout 90;
    proxy_send_timeout 90;
    proxy_read_timeout 90;

    proxy_buffer_size 4k;
    proxy_buffers 4 32k;
    proxy_busy_buffers_size 64k;
    proxy_temp_file_write_size 64k;
  }
  error_page 500 502 503 504 /500.html;
  keepalive_timeout 10;
  gzip on;
  gzip_min_length  1100;
  gzip_buffers  4 32k;
  gzip_types    text/plain application/x-javascript text/xml text/css;
  gzip_vary on;
}`

The web has worked about three months after rails app deployed until yesterday. I did not make any change to rails app code, yesterday I went to front page, got "No products found" anywhere. Whenever  puma start, front page is the error:

"Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)" , application trace to app/controllers/spree/home_controller_decorator.rb:9:in `index'

`@products = @searcher.retrieve_products`
 
I doubt it's puma with elasticsearch issue, I can't solve it.
Here is config/initializers/elasticsearch.rb:
`if Rails.env.production?
  ENV['RAILS_ELASTIC_URL'] = 'https://search-ypill-searcher-mgvqun2xozlinlvdespsrmc4pm.us-east-1.es.amazonaws.com'
else
  ENV['RAILS_ELASTIC_URL'] = 'localhost:9200'
end
Elasticsearch::Model.client = Elasticsearch::Client.new url: ENV['RAILS_ELASTIC_URL']
Searchkick.client = Elasticsearch::Client.new(hosts: ENV['RAILS_ELASTIC_URL'], retry_on_failure: true, transport_options: {request: {timeout: 250} })`

Any help is really appreciated.

**Comment by stereobooster** [comment]
Just make sure you use everywhere same values for server and same port, then restart Puma and nginx. I see you tried different combinations:

```
[8534] * Listening on tcp://0.0.0.0:3000
...
[11972] * Listening on unix:///home/ypill/tcm/shared/sockets/puma.sock
response: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
```

**Comment by 99cm** [comment]
The same question "Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)" answered by stackoverflow.com,  suggest changing the transport.tcp.port:
`network.host: 127.0.0.1
transport.tcp.port: 9300
http.port: 9200`
https://stackoverflow.com/questions/42526394/failed-to-open-tcp-connection-to-localhost9200-connection-refused-connect2

However, in my case, I don't have elasticsearch.yml, setting remote elasticsearch url (amazon aws) with puma, configuring port 9200. I can't solve it.

thank you for your time to read and answer.

**Comment by stereobooster** [comment]
All you need is carefully walk through all setup again.

Stop nginx and puma. Clean log files. Start puma, check if it works (in browser or via curl). Start nginx, check if it works.
