### ISSUE TITLE
Previous workers taking a lot of time to close with Puma phased restart

### ISSUE THREAD

**Issue by bhavya0692** [puma/puma#1407]
I am deploying my rails application with the help of mina and using the phased-restart feature of puma. By using phased-restart, I understand that there will be times during the deployment where processes belonging to the previous version and processes belonging to the new version both exist at the same time. I am facing a problem that when a newer version of code is deployed, the previous version workers take a lot of time to close (up to 2-3 hours in my case) which takes up a lot of memory and I end up hard-restarting puma to free up the memory. Is there any way to close the previous version workers quickly or anything that can resolve the problem ?

Below is my puma.rb,

`require 'puma_worker_killer'`

`# Set your full path to application`
`app_dir = "/path/to/current/folder"`
`shared_dir = "/path/to/shared/folder"`

`# Set puma options`
`workers 3`
`prune_bundler`

`# Min and Max threads per worker`
`threads 3, 5`

`# Set up socket location`
`bind "unix://#{shared_dir}/sockets/puma.sock"`
`activate_control_app "unix://#{shared_dir}/sockets/pumactl.sock"`
`pidfile "#{shared_dir}/pids/puma.pid"`
`state_path "#{shared_dir}/sockets/puma.state"`
`directory "#{app_dir}"`

`# Logging`
`stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true`
`ENV['BUNDLE_GEMFILE'] = "#{app_dir}/Gemfile"`

`PumaWorkerKiller.config do |config|`
 `config.ram           = 3000 # mb`
 `config.frequency     = 5    # seconds`
 `config.percent_usage = 0.7`
 `config.rolling_restart_frequency = false`
 `config.reaper_status_logs = true`
`end`

`before_fork do`
  `PumaWorkerKiller.start`
`end`

`on_restart do`
  `PumaWorkerKiller.start`
`end`

**Comment by nateberkopec** [comment]
Fixed in Puma 4.0 by 64db36c01ee2fb56f24
