### ISSUE TITLE
Suppressing the Thread warning during boot

### ISSUE THREAD

**Issue by binarylogic** [puma/puma#1413]
Hi, we have customers complaining about [the warning](https://github.com/puma/puma/blob/137a80d766478ba03f5c5fecbe152a2b26ee2359/lib/puma/cluster.rb#L404) that [our library (timber-ruby)](https://github.com/timberio/timber-ruby) causes during Puma boot.

[`timber`](https://github.com/timberio/timber-ruby) is a logging library that starts a thread for log delivery whenever the logger is used. This appears to be valid in this context. And when the puma process is forked, another thread is lazily started that performs delivery for that process.

Is there anyway to suppress this warning for valid use cases like this?

**Comment by nateberkopec** [comment]
This warning is related to https://github.com/puma/puma/issues/1421 and the reason why creating threads before forking is dangerous is explained [here](https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/). I believe the warning to be valid here.

**Comment by binarylogic** [comment]
Right, I understand the context and why the warning was added, but this is a scenario where it is valid to start a thread during boot. The main thread is generating logs, and as I mentioned previously, the `timber` gem is a logging gem. The thread created enables timber to deliver logs asynchronously, as to not block runtime execution. Does that make sense?

I understand why the warning was added, most of the time it will prevent mistakes, but considering it is not an absolute condition, there should be a way to mute it for specific threads that are valid.

**Comment by nateberkopec** [comment]
Valid warning, closing.
