### ISSUE TITLE
Init.d script does not work. Does not print any output and does not start puma either.

### ISSUE THREAD

**Issue by Kafkalasch** [puma/puma#1419]
Hello,

somehow the init.d scripts do not seem to do anything on my raspberry pi (using jessie).

I followed the steps found on https://github.com/puma/puma/tree/master/tools/jungle/init.d
and used this configuration file
puma.production.rb
```
# Change to match your CPU core count
workers 4

# Min and Max threads per worker
threads 1, 6

app_dir = File.expand_path("../..", __FILE__)
shared_dir = "#{app_dir}/tmp/puma"

# Default to production
rails_env = ENV['RAILS_ENV'] || "production"
environment rails_env

# Set up socket location
bind "unix://#{shared_dir}/puma.sock"

# Logging
stdout_redirect "#{shared_dir}/puma.stdout.log", "#{shared_dir}/puma.stderr.log", true

# Set master PID and state locations
pidfile "#{shared_dir}/pid"
state_path "#{shared_dir}/state"
activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablis$
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.y$
end
```
my /etc/puma.conf looks like this:
`/var/www/RailsApp,www-data,/var/www/RailsApp/config/puma.production.rb`

### Expected behavior

If I call `sudo service puma start` I would expect some output (like found in the script with log_daemon_msg) and puma to start.

### Actual behavior

Nothing happens at all. Nothing gets printed to the console and puma does not start.

![image](https://user-images.githubusercontent.com/11166464/30809900-a53e282e-a203-11e7-984f-3518f70b0f45.png)

`sudo service puma status` gives me the following output
```
puma.service - LSB: Puma web server
   Loaded: loaded (/etc/init.d/puma)
   Active: active (exited) since Mon 2017-09-25 13:59:37 CEST; 1h 3min ago

Sep 25 13:59:37 raspberrypi systemd[1]: Started LSB: Puma web server.
Sep 25 13:59:37 raspberrypi puma[13542]: => Running the jungle...:--> Woke up puma...g:
Sep 25 14:17:36 raspberrypi systemd[1]: Started LSB: Puma web server.
Sep 25 14:25:47 raspberrypi systemd[1]: Started LSB: Puma web server.
Sep 25 14:26:28 raspberrypi systemd[1]: Started LSB: Puma web server.
Sep 25 14:35:38 raspberrypi systemd[1]: Started LSB: Puma web server.
Sep 25 14:36:05 raspberrypi systemd[1]: Started LSB: Puma web server.
Sep 25 14:53:38 raspberrypi systemd[1]: Started LSB: Puma web server.

```

If I start the puma server manually with `puma -C config/puma.production.rb` everything works as expected.

I did not find anything related on the internet. Does any one has a hint how to solve this?

### System configuration

**Ruby version**:
ruby 2.4.1p111 (2017-03-22 revision 58053) [armv7l-linux-eabihf]
**Rails version**:
Rails 5.1.4
**Puma version**:
puma version 3.10.0

**Comment by dekellum** [comment]
Looks like your system is using systemd, so follow instructions in [docs/systemd](https://github.com/puma/puma/blob/master/docs/systemd.md), not the legacy init.d documentation.

**Comment by Kafkalasch** [comment]
Thanks a lot, this worked.
