### ISSUE TITLE
Puma command GemRequireError

### ISSUE THREAD

**Issue by maha99tests** [puma/puma#1422]
### Steps to reproduce

1) rails s puma

2) puma 

3) ...

### Expected behavior

Puma should start fine in both cases

### Actual behavior

Puma fails to start when I try to run it directly via the `puma` command. The error is a GemRequireError, unable to load gem red cloth

### System configuration

**Ruby version**:

2.3.5 in $HOME/.ruby and set in path but there's another 2.3.1 ruby installed as root via apt on ubuntu 16.04 LTS

**Rails version**:

Rails 4.2

**Puma version**:

3.10

**Comment by nateberkopec** [comment]
> GemRequireError, unable to load gem red cloth

This is a problem with your application, please try the #ruby IRC channel or another avenue for support.
