### ISSUE TITLE
Clustered mode with 1 worker should not create master process or at least warn

### ISSUE THREAD

**Issue by vizcay** [puma/puma#1426]
I was trying to improve the memory usage of an small internal app used in our organization when I realized that a misconfiguration in my config/puma.rb was responsable for more memory than needed. At some point this app was running with multiple workers and now we switched back to only one because of low usage. Instead of removing completely the workers line, **I changed it to to **workers 1** believing it was the same.**

But according to htop is not, because puma still creates its master process, that it won't be used ever. Worst, I was using preload_app! so it was created with all the code loaded. I know that at the beginning that master process has almost all memory shared with it's only child so it's not twice as memory. Still, at some point when the copy on write mechanism starts to work some memory will be wasted.

Makes any sense to allow this configuration?

### System configuration

**Ruby version**: 2.3.3
**Sinatra version**: 1.4.7
**Puma version**: 3.8.1

**Comment by nateberkopec** [comment]
Probably not. If you want one process, use single mode.
