### ISSUE TITLE
pumactl example in README doesn't work

### ISSUE THREAD

**Issue by garybernhardt** [puma/puma#1427]
### Steps to reproduce

Here's what happens when I copy and paste the two commands in the "Control/Status Server" section of the README. (My only change is the `&` to put the server in the background.)

```text
$ puma --control tcp://127.0.0.1:9293 --control-token foo&
Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.1-p111), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
* Starting control server on tcp://127.0.0.1:9293
Use Ctrl-C to stop

$ pumactl restart --control-token foo
Neither pid nor control url available
/Users/grb/proj/japanese/.gem/ruby/2.4.1/gems/puma-3.10.0/lib/puma/control_cli.rb:180:in `send_signal'
/Users/grb/proj/japanese/.gem/ruby/2.4.1/gems/puma-3.10.0/lib/puma/control_cli.rb:230:in `run'
/Users/grb/proj/japanese/.gem/ruby/2.4.1/gems/puma-3.10.0/bin/pumactl:8:in `<top (required)>'
/Users/grb/proj/japanese/.gem/ruby/2.4.1/bin/pumactl:22:in `load'
/Users/grb/proj/japanese/.gem/ruby/2.4.1/bin/pumactl:22:in `<main>'
```

### Expected behavior

It restarts the server, as the README says it will.

### Actual behavior

See above.

### System configuration

**Ruby version**:2.4.1p11
**Rails version**:nil
**Puma version**:3.10.0

The same thing happens if I run the server via `puma --control tcp://127.0.0.1:9293 --control-token foo&`, then try to restart it with `pumactl restart -C 'tcp://127.0.0.1:9293' --control-token foo`. So maybe the docs are right but my puma installation is broken in some way? It's a fresh install with no configuration or anything, though.

**Comment by nateberkopec** [comment]
Whoops, yeah in the docs that should say something like:

```ruby
pumactl -C 'tcp://127.0.0.1:9293' --control-token foo restart
```

or

```ruby
pumactl -p <puma-pid> --control-token foo restart
```


We're just using OptionParser so it's too dumb to allow "command-before-arguments", even though it feels more natural here. All options must come before the command.

**Comment by garybernhardt** [comment]
That did it, thanks!
