### ISSUE TITLE
Phased restart reload Puma config

### ISSUE THREAD

**Issue by ktimothy** [puma/puma#1432]
### Steps to reproduce

1) redirect stdout to some logfile
2) run puma in cluster mode
3) change logfile in puma.rb
4) run phased restart (which, I guess reads puma.rb config)
5) kill -HUP puma master process

### Expected behavior

Puma should write logs to new path.

### Actual behavior

Puma continues to redirect stdout to old path.

### System configuration

**Ruby version**: 2.3.1
**Rails version**: there are no rails =)
**Puma version**: 3.10.0

**Comment by stereobooster** [comment]
No phased restart does not reload config file. Documented here https://github.com/puma/puma/blob/master/docs/signals.md#send-usr1

**Comment by ktimothy** [comment]
I saw it in the docs. Is it intended behavior? If it is, why?

**Comment by nateberkopec** [comment]
@ktimothy What part of the docs are you talking about exactly?

**Comment by ktimothy** [comment]
@nateberkopec I mean restarting puma server. Why does not puma reload config file on phased restart (USR1), while it does so with normal restart (USR2)?

**Comment by KapilSachdev** [comment]
@nateberkopec is this feature still under consideration?
In case yes, I can try to resolve the issue but will need some direction :upside_down_face:.

**Comment by nateberkopec** [comment]
Yes, but I think we're probably going in this direction: https://github.com/puma/puma/issues/1875.

If you have a different approach that you think might be better (or want to try to implement the solution described there), let me know.

**Comment by KapilSachdev** [comment]
Then I think we can close this issue in favour of the #1875.
