### ISSUE TITLE
Incompatibility with Ruby < 2.1 (undefined method `to_h')

### ISSUE THREAD

**Issue by sigmike** [puma/puma#1440]
### Steps to reproduce

1) Install Ruby 1.9.3

2) Install puma gem

3) Run `puma`

### Expected behavior

No Ruby exception.

### Actual behavior

```
/home/mike/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/puma-3.10.0/lib/puma/launcher.rb:174:in `run': undefined method `to_h' for #<Object:0x00000001edca28> (NoMethodError)
        from /home/mike/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
        from /home/mike/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
        from /home/mike/.rbenv/versions/1.9.3-p551/bin/puma:23:in `load'
        from /home/mike/.rbenv/versions/1.9.3-p551/bin/puma:23:in `<main>'
```

### System configuration

**Ruby version**: 1.9.3-p551
**Rails version**: N/A
**Puma version**: 3.10.0

The problem was introduced in Puma 3.9.0 with this commit: https://github.com/puma/puma/commit/b548b624ea98f8382de2cb002705db54d16a9e5a. Puma version 3.8 works.

The `to_h` method was added in Ruby 2.1.

**Comment by stereobooster** [comment]
If ruby 2.1 or less supported it should be listed in travis https://github.com/puma/puma/blob/master/.travis.yml

**Comment by HoneyryderChuck** [comment]
[it is](https://travis-ci.org/puma/puma). Time to add coverage?

**Comment by stereobooster** [comment]
> If ruby 2.1 or less supported 

I meant versions less than ruby 2.1. Ruby 2.1 obviously supported

**Comment by HoneyryderChuck** [comment]
ups, my bad. time to add ruby version requirement in the gemspec?
