### ISSUE TITLE
Can't shutdown rspec when running Puma

### ISSUE THREAD

**Issue by Nerian** [puma/puma#1443]
Hi,

I updated to Rails 5.1 and I am trying to deal with the Puma changes. I noticed that I cannot kill the rspec process when running the feature tests. When I do ctrl+c it only kills the Puma server, but rspec tests continue to run – and fail – until the end.

Here is a demo:

https://github.com/Nerian/sample-capybara-rspec-issue

Try running `rspec` and `ctrl+c` in the middle of it. I expect rspec to stop the execution, instead the Puma server is killed but rspec continue executing all tests. Doing `ctrl+c` multiple times has no effect. If I change the server to webrick is works fine.

Ruby: ruby 2.4.2p198
Rails: 5.1.4
Puma: 3.10.0

**Comment by lacco** [comment]
Quick note: Bug can be fixed by reverting back to rspec 3.6.0, see https://github.com/rspec/rspec-rails/issues/1887

**Comment by nateberkopec** [comment]
This is a Rails issue, not Puma. See above.
