### ISSUE TITLE
RACK_ENV set and not loading correct config/puma/ENV.rb file

### ISSUE THREAD

**Issue by allaire** [puma/puma#1447]
### Steps to reproduce

1) Set a configuration file in `config/puma/development.rb` using different thread values

2) Run RACK_ENV=development puma start

3) Notice that the thread counts are not the one you've set in the config

4) Run `puma -e development` and it should work

### Expected behavior

I think puma should respect the `RACK_ENV` and load the correct environment config file.

We can read in the README:

> If no configuration file is specified, Puma will look for a configuration file at config/puma.rb. If an environment is specified, either via the -e and --environment flags, or through the RACK_ENV environment variable, the default file location will be config/puma/environment_name.rb.

### System configuration

**Ruby version**: 2.3.1
**Rails version**: 5.1 stable
**Puma version**: 3.10

**Comment by ViliusLuneckas** [comment]
Hi @allaire, could you try version 3.11. I think the fix (#1340) was released with that version.

**Comment by allaire** [comment]
@ViliusLuneckas I'll try to repro on 3.11, but we switched to a single config file, with some `if/else` around the `RACK_ENV`

**Comment by nateberkopec** [comment]
(Marking as fixed, please re-open if it isn't)
