### ISSUE TITLE
Resource temporarily unavailable with default unix socket configuration

### ISSUE THREAD

**Issue by eprothro** [puma/puma#1449]
During some recent load testing and optimization, we switched from a TCP socket to UNIX socket. 

With high throughput (>500 connections/sec), the client (nginx reverse proxy in this case) experienced errors connecting to the socket. We saw no such issues with the TCP socket.

```
connect() to unix:/path/to/socket/puma.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client...
```

Trying to isolate/debug I noticed that the [default backlog for unix sockets is `nil`](https://github.com/puma/puma/blob/master/lib/puma/binder.rb#L347) (not `1024` like with TCP). And further, that with a falsy backlog, [`listen` is not called on the socket](https://github.com/puma/puma/blob/master/lib/puma/binder.rb#L368).

Setting a backlog (via bind path uri query param) resolved the connection issues in our tests.

Excuse any ignorance as I'm no unix socket expert, but is the `backlog=nil` default and not calling `listen` intentional and desirable for UNIX sockets?

If it is intentional/recommended, how should users expect to buffer bursty clients?

If not, I'm happy to issue PR.

**Comment by nateberkopec** [comment]
> Trying to isolate/debug I noticed that the default backlog for unix sockets is nil  

Hm, that does seem wrong.

**Comment by nateberkopec** [comment]
@eprothro I talked to Evan about this, he said this behavior is not intentional and is definitely a bug. We should change the default Unix backlog to 1024.

**Comment by ernestojpg** [comment]
Hi all, I have updated to latest version of Puma (3.12.0) and I'm still having the same issue: Nginx returns 502 (Bad Gateway) error codes, and I see error messages like this in the logs:
```
connect() to unix:/path/to/socket/puma.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client...
```
It only happens when connecting Nginx and Puma using Unix Sockets and under heavy load (300 new connections per second). I have tried setting the backlog to 1024 in the configuration file:
```
bind 'unix:///tmp/run/puma.sock?backlog=1024'
```
And I have also tried to leave it empty, which should default the value to 1024 as well, but nothing works.

Any idea?

**Comment by jack-nie** [comment]
same issue here， i'm using puma 3.4.0

**Comment by himberjack** [comment]
Any news regarding the 5xx error on load?

**Comment by nkokkos** [comment]
I believe the behaviour is influenced by the kernel parameters too. I had the same problem but I was able to resolve it as follows:

I set ``bind 'unix:///tmp/run/puma.sock?backlog=1024' `` as instructed

I took a look at this example:  https://easyengine.io/tutorials/linux/sysctl-conf and changed the default somaxconn from 128 to 4096.

You can see the current somaxconn  with ``cat /proc/sys/net/core/somaxconn``

I also used https://github.com/wg/wrk to load test the app. 
Used the default example
``wrk -t12 -c400 -d30s http://127.0.0.1:3000/``

I ran only one puma worker behind nginx; the response was very slow but I got no errors in /var/logs/nginx/error.log

**Comment by microweb10** [comment]
Hi @ernestojpg I'm kinda facing the same issue, and the solution of nkokkos doesn't work for me. I guess there's something else involved (linux kernel settings, linus networking settings...) that I didn't find out yet. Did you resolve your issue? If you did, could you share how? 🙏  Thanks ☺️

**Comment by arpu** [comment]
any more infos on this?  when i set worker to 1  no error with worker 2 i get the same errors any idea how to debug this more?

**Comment by julienbfabre** [comment]
Same issue here, adding ?backlog=1024 didn't help, any ideas?

**Comment by nkokkos** [comment]
There seems to be similar problem here: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5752

From what I read here: https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/5752, it is resolved by setting somaxconn to puma default backlog. So if you set the same number to both somaxconn  and backlog, you should be ok?

Try this and see if it works: 

echo 1024 > /proc/sys/net/core/somaxconn

stop your puma server

set bind 'unix:///tmp/run/puma.sock?backlog=1024' in puma.rb

start your puma server
