### ISSUE TITLE
Can't send images (or data of significant size) over wss (web socket over SSL) from browser not on same machine as web app

### ISSUE THREAD

**Issue by twocanoes** [puma/puma#1454]
Sample App showing this behavior is here:

https://bitbucket.org/twocanoes/websocket_pics

### Steps to reproduce

1.  Set up puma to use SSL by adding lines like these to the puma.conf file in a rails app:

bind "ssl://0.0.0.0:4567?cert=sample_certs/server.crt&key=sample_certs/server.key&verify_mode=none"

2.  On a browser that is not on the same machine as the rails app, connect to rails app, upgrade the browser connection to a a WSS connection and attempt to send an text-encoded image over the socket. 
### Expected behavior

The rails app should receive the data.

### Actual behavior

The socket is closed and then reopened.  The data is sent from the browser but never received. Looking at the network trace and developer inspector in chrome shows the data sent from the browser.

 If the connect is made on a the local machine or via non-ssl, the data is sent successfully. Attempted on multiple machines.  The exact amount of data sent seems variable to trigger this, but it seems to be around 2k or greater.

Sample App showing this behavior is here:

https://bitbucket.org/twocanoes/websocket_pics

### System configuration

Testing done on macOS 10.13 and macOS10.12 on both the rails app side and the browser side. Browsers tested include Chrome and Safari on 10.13 and 10.12.

**Ruby version**:
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Rails version**:
5.0.5
**Puma version**:
3.10.0

**Comment by wdiechmann** [comment]
any progress? I somewhat suspect https://sucker.alco.dk/messages/new to suffer from this illness although it display in a slightly different way:

I can attach 1 small file (less than 8-ish KB) - anything bigger than that will fail (but only in production and I have not had any luck logging anything from the POST /messages endpoint :(

the entire project is at https://github.com/wdiechmann/sucker.git

**Comment by nateberkopec** [comment]
Try master branch, as the new nio4r reactor will probably affect this.

**Comment by nateberkopec** [comment]
No reports in a long time, closing.
