### ISSUE TITLE
ActiveSupport::TimeWithZone is significantly slower when Puma runs in cluster mode.

### ISSUE THREAD

**Issue by bblimke** [puma/puma#1458]
I have found that `ActiveSupport::TimeWithZone` is significantly slower when used in a Rails application started with Puma in cluster mode. 

When I run the following code inside a Rails controller action:
````
   10000.times{
        Time.use_zone "Europe/London" do
          Time.zone.local 2017, 11, 16, 11, 58, 00
        end
    }
````
the code runs about **5 seconds** on my machine, when I run Puma in cluster mode.

When Puma runs in single mode, the code takes about **150ms** to execute.

### Steps to reproduce

Here is a fresh Rails 4.2.10 app, without a database required, with only one controller action
https://github.com/bblimke/puma_cluster_activesupport_timewithzone_test

The steps to reproduce the issue are listed in the README.md

### Expected behavior

I would expect the time needed to perform operations on `ActiveSupport::TimeWithZone` under Puma cluster mode to be as low as the one for single mode.

### Actual behavior

`Time.zone.local` is much slower when Puma runs in cluster mode.

### System configuration

**Ruby version**: 2.3.1 or 2.4.2, same results
**Rails version**: 4.2.10
**Puma version**: 3.10

**Comment by nateberkopec** [comment]
I feel like I've seen this issue before...it involved system calls being slower after a fork. What's your OS?

**Comment by nateberkopec** [comment]
[Here's](https://stackoverflow.com/questions/41353532/why-is-time-utc-slower-in-a-forked-process-in-ruby-on-os-x-and-not-in-python?noredirect=1&lq=1) what I was thinking of.

**Comment by bblimke** [comment]
MacOS 10

This doesn't seem to be an issue on Heroku, just on my dev machine.

**Comment by bblimke** [comment]
@nateberkopec thanks for pointing me to that stackoverflow question. It looks like it's a problem with Ruby on MacOS, and not something that Puma or Rails can fix.

In that case please feel free to close this issue.

**Comment by nateberkopec** [comment]
OS bug, syscalls are slower after fork on Mac.
