### ISSUE TITLE
Combination of Puma::ConnectionError / SystemCallError

### ISSUE THREAD

**Issue by aryeh-looker** [puma/puma#1460]
Thanks you kindly for taking the time to consider this issue. Here, we are getting both a `Puma::ConnectionError` and `SytemCallError`. I am a little confused about what a `SystemCallError` means here.

For example, I can reproduce a `Puma::ConnectionError` / `Errno::EPIPE` error by streaming some data and closing the remote connection before streaming is complete, but am confused, in this context, what a `SystemCallError` might mean and am not sure how to reproduce it.

### Steps to reproduce

Unfortunately no known reliable steps to reproduce.

### Expected behavior

Data should successfully stream

### Actual behavior

`SystemCallError` is raised

```
SystemCallError: Unknown error (SystemCallError) - No message available
  from org/jruby/RubyIO.java:1440:in `write'
  from org/jruby/RubyIO.java:1411:in `write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/minissl.rb:65:in `write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:852:in `fast_write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:671:in `block in handle_request'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:88:in `write'
  from org/jruby/ext/zlib/JZlibRubyGzipWriter.java:374:in `write'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:78:in `block in each'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `block in <<'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:378:in `schedule'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `<<'
... application code here

Puma::ConnectionError: Socket timeout writing data
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:860:in `fast_write'
  from /bundler/gems/puma-aae7c7a5342a/lib/puma/server.rb:671:in `block in handle_request'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:88:in `write'
  from org/jruby/ext/zlib/JZlibRubyGzipWriter.java:374:in `write'
  from /gems/rack-1.5.4/lib/rack/deflater.rb:78:in `block in each'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `block in <<'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:378:in `schedule'
  from /gems/sinatra-1.4.3/lib/sinatra/base.rb:405:in `<<'
... application code here
```

### System configuration

**Ruby version**: JRuby `9.1.8.0`
**Rails version**: n/a — Sinatra `1.4.3`
**Puma version**: `2.12.3`
**Rack**: `1.5.4`

**Comment by nateberkopec** [comment]
🤷‍♂️ [Looks like the socket isn't writable.](https://github.com/jruby/jruby/blob/9.1.8.0/core/src/main/java/org/jruby/RubyIO.java#L1440) Please reopen if you have a reproduction or can show this is Puma's fault, otherwise there's nothing we can really do here 😢

**Comment by aryeh-looker** [comment]
No problem, thanks @nateberkopec.

**Comment by aryeh-looker** [comment]
No problem, thanks @nateberkopec. Just to clarify — this means that the socket is simply unavailable, correct? It doesn't merely mean that the socket is blocking writing for a long period of time?

**Comment by nateberkopec** [comment]
I'm honestly not sure. I'd open an issue with the JRuby repo - not b/c it's a JRuby bug, but I think JRuby could provide a better error message here.
