### ISSUE TITLE
sudo start puma-manager : start: Job failed to start

### ISSUE THREAD

**Issue by Ume1931** [puma/puma#1461]
I installed nginx 1.12.1 on **Amazon Linux(AWS)** and then configured Puma as mentioned in following digital ocean tutorial :https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04 

Downloaded Jungle Upstart tool & followed all steps.
But when i run sudo start puma-manager, i got following error:
**start: Job failed to start**

Can anyone help?

**Comment by nateberkopec** [comment]
Hi - this doesn't sound like a bug but more of a support issue. You can use our Gitter channel or contact the person that wrote that tutorial to get help.
