### ISSUE TITLE
3.11

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1462]
* [x] Release notes
* [x] Fix 2.2 CI build (IOError) (#1459)
* [x] Come up with a good release name, either after the band or the NYC info hotline.

cc @guilleiguaran @rafaelfranca @tenderlove @eileencodes (dunno who 5.2 release manager is lol)

**Comment by claudiob** [comment]
> Come up with a good release name after the band

"Universal Pulse" ?
https://en.wikipedia.org/wiki/Universal_Pulse

<img src="https://upload.wikimedia.org/wikipedia/en/f/f2/311-UniversalPulse%282011%29.jpg" alt="311-UniversalPulse(2011).jpg">

**Comment by rafaelfranca** [comment]
> dunno who 5.2 release manager is

I'm 😄

**Comment by nateberkopec** [comment]
Donezo https://github.com/puma/puma/releases/tag/v3.11.0

**Comment by rafaelfranca** [comment]
Thanks!

**Comment by eileencodes** [comment]
Thank you @nateberkopec!!!!!!!! 🎉
