### ISSUE TITLE
sinatra config.ru

### ISSUE THREAD

**Issue by r11s** [puma/puma#1465]
### Steps to reproduce

Using the proposed config.ru for sinatra.

### Expected behavior

Start puma and the web server should run.

### Actual behavior

Puma crashes with config.ru

### Solution

change the following line in config.ru:

```
require 'main'
```
to
```
require './main'
```

### System configuration

**Ruby version**: ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin16]
**Sinatra version**: sinatra (2.0.0)
**Puma version**: puma (3.10.0)

**Comment by nateberkopec** [comment]
I'm confused - we don't propose a config.ru file anywhere for Sinatra. Sinatra doesnt typically use rackup files (which is why the README says to use `ruby app.rb -s Puma`).

**Comment by nash8114** [comment]
The readme does, but the github wiki page states `require 'main'`. Perhaps that is what is being referred to by the OP?

Link to the wiki page:
https://github.com/puma/puma/wiki/Running-sinatra-classic-with-puma
