### ISSUE TITLE
Rails Server Fails at Startup - undefined symbol OPENSSL_init_ssl 

### ISSUE THREAD

**Issue by oshanley** [puma/puma#1467]
Been having this issue trying to develop locally, but haven't been able to find anything on it. I've tried everything from re-installing puma, to completely reinstalling rails, but nothing has worked. I have libssl, libssl-dev, and openssl installed, if that helps.

### Steps to reproduce

1) run `rails server`

### Expected behavior

Server starts

### Actual behavior

Puma throws an error: 

> rails server           
> => Booting Puma
> => Rails 5.1.4 application starting in development 
> => Run `rails server -h` for more startup options
> Exiting
> /var/lib/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require': /var/lib/gems/2.3.0/gems/puma-3.10.0/lib/puma/puma_http11.so: undefined symbol: OPENSSL_init_ssl - /var/lib/gems/2.3.0/gems/puma-3.10.0/lib/puma/puma_http11.so (LoadError)

### System configuration

**Ruby version**: 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
**Rails version**: 5.1.4
**Puma version**: 3.10.10

**Comment by nateberkopec** [comment]
Looks like you compiled Puma's extensions without OpenSSL configured correctly. 

Did you recently upgrade your OS version or SSL package? Uninstall puma completely and reinstall, see if that fixes.

Please try StackOverflow or Gitter.

**Comment by tuda2008** [comment]
rvm reinstall [your ruby version] --with-openssl-dir=/[your ssl dir]

for example
> rvm reinstall 2.4.0 --with-openssl-dir=/usr/local/src/openssl-1.1.0e

then puma start is ok
