### ISSUE TITLE
Incorrect chunked transfer encoding handling

### ISSUE THREAD

**Issue by petr666** [puma/puma#1480]
Hi,
version 3.7.0 (probably change "Pickup any remaining chunk data as the next request") introduced bug with consequent chunked requests.
It seems puma implementation does not conform to https://tools.ietf.org/html/rfc7230#section-4.1. Valid chunked body is:

chunked-body = *chunk
                           last-chunk
                           trailer-part
                           CRLF

but Puma does not count with the last CRLF which is wrongly appended to consequent request, while printing:

HTTP parse error, malformed request (): #<Puma::HttpParserError [047a99aabe6323c0020b9e290f19d997]: Invalid HTTP format, parsing fails.>

I've tested this via Wireshark. When last CRLF is not present, puma sends response without printing any error. But Wireshark does not display request, because it is incomplete/invalid. In case last CRLF is present, Wireshark prints request, but puma prints error and consequent request within same connection fails.

**Comment by ademars94** [comment]
+1 Also experiencing issues with chunked request.

**Comment by 100cm** [comment]
its's still not work in puma 3.12.0

![image](https://user-images.githubusercontent.com/12691638/55848437-86ad7680-5b7f-11e9-8f84-a9fff93b6823.png)

and the error is 

![image](https://user-images.githubusercontent.com/12691638/55848452-9036de80-5b7f-11e9-8d4e-6fbe06b5f62d.png)

May rack still read content_Length?

![image](https://user-images.githubusercontent.com/12691638/55848479-a47adb80-5b7f-11e9-8a5d-47375ae5dbb2.png)
