### ISSUE TITLE
checking with shopify app

### ISSUE THREAD

**Issue by MassMadankumar** [puma/puma#1481]
root@instance-2:/mnt/disks/brady/zapapp/zapstore# rails s
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/app_loader.rb:40: warning: Insecure world writable dir /usr in PATH, mode 040777
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.0 (ruby 2.4.2-p198), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2017-12-06 08:50:12 +0000 ===
- Goodbye!
Exiting

Next process?
 how to check with shopify app run
 or not

**Comment by nateberkopec** [comment]
Sorry, but this looks like you're asking for support with a particular Rails application. This issue tracker is for Puma bugs and requests. I think you would be better off asking a general Rails forum or chat.
