### ISSUE TITLE
A server is already running. 

### ISSUE THREAD

**Issue by MassMadankumar** [puma/puma#1486]
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
A server is already running. Check /mnt/zapstore.com/shopifyapp/zap/tmp/pids/server.pid.
Exiting
root@instance-2:/mnt/zapstore.com/shopifyapp/zap#
### System configuration

**Ruby version**: 2.4.2p198
**Rails version**:5.1.4
**Puma version**:3.11.0

**Comment by TheKidCoder** [comment]
Likely you accidentally started a server in a terminal and killed the terminal without killing the server. You can do something like this: `kill $(cat /mnt/zapstore.com/shopifyapp/zap/tmp/pids/server.pid)` Which will kill the server process.

**Comment by MassMadankumar** [comment]
how to change server

**Comment by MassMadankumar** [comment]
this dir of the server

**Comment by MassMadankumar** [comment]
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run rails server -h for more startup options
Puma starting in single mode...

Version 3.11.0 (ruby 2.4.2-p198), codename: Love Song
Min threads: 5, max threads: 5
Environment: development
Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

**Comment by TheKidCoder** [comment]
Looks like you're up and running. If you're using this on a remote server, however, you'll need to bind to the right eth interface. I would consider reading a tutorial on this: https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma

**Comment by CoderMiguel** [comment]
kill -9 $(pgrep puma) 
worked for me
