### ISSUE TITLE
Puma dies after SIGUSR2 sent simultaneously

### ISSUE THREAD

**Issue by pavelvasev** [puma/puma#1488]
### Steps to reproduce

1) Start puma with 2 workers under linux

2) Invoke: seq 20 | parallel kill -12 7435
where 7435 is a puma master process id (replace it with your own).

3) Observe puma crash and it's final messages:
```
[7435] - Gracefully shutting down workers...
[7435] * Restarting...
User defined signal 2
```

### Expected behavior

Puma should just restart as expected.

### Actual behavior

Puma crashes.

### System configuration

**Ruby version**: 2.3 v222
**Rails version**: 5
**Puma version**: 3.11

### Comment

This scenario comes from our logrotate process, which have 2 sections in config file of app log rotation: one for rails *.log files sitting in app log dir, and another for puma server itself sitting in /var/log/pumaapp.log. Each logrotate section has a `kill -12 xxx` command in postrotate script. The logrotate invokes those postrotate script seems simultaneously, and we observe puma crash after each logrotate pass.

**Comment by nateberkopec** [comment]
Can't repro :( Please reopen if you're still having this issue.
