### ISSUE TITLE
Not working for puma with nginx on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by poc7667** [puma/puma#1489]
It's really strange that I'm using reverse nginx to pass the request to puma.
It won't work using foreman to run the upstart. (Although the puma is running well)
My service only working when I manually trigger the exact same run command for puma after boot.

I know this issue is so broader.

I checked the puma process using `ps aux | grep puma`. Everything looks fine.
But it's always hang and doesn't take any request unless I kill the service and run it manually.

# Nginx not working for the reverse proxy

        upstream appwordsService {
          server unix:///tmp/puma.appwords.sock;
        }

    server {
        listen 443 ssl;

        server_name appwords.co www.appwords.co;

        ....

        location /api/v1 {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_connect_timeout 4s;
            proxy_read_timeout 20s;
            proxy_pass http://appwordsService/api/v1;
        }

    }

    server {
         listen      80;
         server_name appwords.co www.appwords.co;
         return 301 https://$server_name$request_uri;
     }

# Puma config

    pidfile "/tmp/puma.appwords.pid"
    bind "unix:///tmp/puma.appwords.sock"
    stdout_redirect "/tmp/puma.stdout.appwords.log", "/tmp/puma.stderr.appwords.log", true
    workers 1 # because my linode only has 2 CPU cores
    threads 4, 8

    #port        7617
    rails_env = "production"
    environment rails_env
    activate_control_app

# Procfile

    web: /home/deployer123/.rbenv/shims/bundle exec puma -C config/puma.rb

# Workaround

manually execute  pkill -9 -f 'rb-fsevent|rails|spring|puma'
then the deamon will restart again . then everything is working again.
What a hell LOL ~ the bug is definitely on timing issue and it's caused by PUMA.

**Comment by karpa13a** [comment]
what exact error from nginx do u see?

**Comment by poc7667** [comment]
# -1 (11: Resource temporarily unavailable)

			2017/12/27 08:22:54 [debug] 5808#0: *7 http cleanup add: 00000000017779D8
			2017/12/27 08:22:54 [debug] 5808#0: *7 get rr peer, try: 1
			2017/12/27 08:22:54 [debug] 5808#0: *7 http upstream connect: 0
			2017/12/27 08:22:54 [debug] 5808#0: *7 http upstream send request
			2017/12/27 08:22:54 [debug] 5808#0: *7 http finalize request: -4, "/api/v1/query?" a:1, c:2
			2017/12/27 08:22:54 [debug] 5808#0: *7 http request count:2 blk:0
			2017/12/27 08:22:54 [debug] 5808#0: *8 http run request: "/api/v1/get_registered_email?token=fwfmfi"
			2017/12/27 08:22:54 [debug] 5808#0: *8 http upstream check client, write event:1, "/api/v1/get_registered_email"
			2017/12/27 08:22:54 [debug] 5808#0: *8 http upstream recv(): -1 (11: Resource temporarily unavailable)
			2017/12/27 08:22:54 [debug] 5808#0: *8 http upstream request: "/api/v1/get_registered_email?token=fwfmfi"
			2017/12/27 08:22:54 [debug] 5808#0: *8 http upstream dummy handler
			2017/12/27 08:22:54 [debug] 5808#0: *6 http run request: "/api/v1/statistics?token=fwfmfi"
			2017/12/27 08:22:54 [debug] 5808#0: *6 http upstream check client, write event:1, "/api/v1/statistics"
			2017/12/27 08:22:54 [debug] 5808#0: *6 http upstream recv(): -1 (11: Resource temporarily unavailable)
			2017/12/27 08:22:54 [debug] 5808#0: *6 http upstream request: "/api/v1/statistics?token=fwfmfi"
			2017/12/27 08:22:54 [debug] 5808#0: *6 http upstream dummy handler
			2017/12/27 08:22:54 [debug] 5808#0: *7 http run request: "/api/v1/query?"
			2017/12/27 08:22:54 [debug] 5808#0: *7 http upstream check client, write event:1, "/api/v1/query"
			2017/12/27 08:22:54 [debug] 5808#0: *7 http upstream recv(): -1 (11: Resource temporarily unavailable)
			2017/12/27 08:22:54 [debug] 5808#0: *7 http upstream request: "/api/v1/query?"
			2017/12/27 08:22:54 [debug] 5808#0: *7 http upstream dummy handler
			2017/12/27 08:22:54 [debug] 5808#0: *8 http upstream request: "/api/v1/get_registered_email?token=fwfmfi"
			2017/12/27 08:22:54 [debug] 5808#0: *8 http upstream process header
			2017/12/27 08:22:54 [debug] 5808#0: *8 http proxy status 304 "304 Not Modified"
			2017/12/27 08:22:54 [debug] 5808#0: *8 http proxy header: "X-Frame-Options: SAMEORIGIN"
			2017/12/27 08:22:54 [debug] 5808#0: *8 http proxy header: "X-XSS-Protection: 1; mode=block"

**Comment by karpa13a** [comment]
can you post whole log?
example about *8 request?
i see, there is starting a reply from upstream:
```
		2017/12/27 08:22:54 [debug] 5808#0: *8 http upstream process header
		2017/12/27 08:22:54 [debug] 5808#0: *8 http proxy status 304 "304 Not Modified"
		2017/12/27 08:22:54 [debug] 5808#0: *8 http proxy header: "X-Frame-Options: SAMEORIGIN"
		2017/12/27 08:22:54 [debug] 5808#0: *8 http proxy header: "X-XSS-Protection: 1; mode=block"
```

usually pair of http upstream recv(): -1 (11: Resource temporarily unavailable) / http upstream dummy handler
mean that upstream not ready to send data. ie upstream currently processing request.
