### ISSUE TITLE
Error running rails new [Puma]

### ISSUE THREAD

**Issue by Thalliuz** [puma/puma#1494]
### Steps to reproduce
rails new test_file

### Expected behavior

Expected rails to create the files and install the gemfile with no errors.

### Actual behavior

The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.

Fetching puma 3.11.0
Installing puma 3.11.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

An error occurred while installing puma (3.11.0), and Bundler cannot
continue.
Make sure that `gem install puma -v '3.11.0'` succeeds before bundling.

### System configuration

**Ruby version**: 2.3.0
**Rails version**: 5.4.1
**Puma version**: 3.10.0

**Comment by adityasinghz** [comment]
Your 1st command is giving me this error

Fetching source index from https://rubygems.org/
Resolving dependencies...
Could not verify the SSL certificate for
https://rubygems.org/quick/Marshal.4.8/rails-5.1.7.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most
likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.
