### ISSUE TITLE
 long parameters on GET request to get Puma::HttpParserError: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length

### ISSUE THREAD

**Issue by poc7667** [puma/puma#1495]
I need to pass long parameters on GET request to get the results.
That request is fine on Nginx. The exception only happens at puma server.

		---
		2017-12-24 06:42:49 -0800: HTTP parse error, malformed request (127.0.0.1): #<Puma::HttpParserError: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length (was 11416)>
		2017-12-24 06:42:49 -0800: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:/tmp/puma.stderr.birchwords.log>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"puma 3.6.2 Sleepy Sunday Serenity", "GATEWAY_INTERFACE"=>"CGI/1.2", "REMOTE_ADDR"=>"127.0.0.1", "REQUEST_METHOD"=>"GET", "REQUEST_PATH"=>"/api/v1/fetch_definitions"}
		---

		GET //api/v1/fetch_definitions?token=04f2-01d9f32d65e0&words[]=submit&words[]=premiumdns&words[]=generated&words[]=request&words[]=address&words[]=details&words[]=impede&words[]=generation&words[]=recommended&words[]=working&words[]=wire+format&words[]=guest_account_detail_view&words[]=familiarization&words[]=approach&words[]=democracy&words[]=problematic&words[]=objections&words[]=imperative&words[]=residual&words[]=streamlined&words[]=glossary&words[]=lead&words[]=orchestrate&words[]=tapping&words[]=scalable&words[]=balloon&words[]=cues&words[]=streamline&words[]=objectives&words[]=suite&words[]=escalated&words[]=criteria&words[]=with+ease&words[]=beneath&words[]=stemming&words[]=mustaches&words[]=tailored&words[]=chatter&words[]=campaigns&words[]=obsolete&words[]=consents&words[]=pledge&words[]=collateral&words[]=collectively&words[]=document&words[]=party&words[]=loan&words[]=lease&words[]=origination&words[]=signifying&words[]=underwriting&words[]=expanded&words[]=mandatory&words[]=appraising&words[]=stakeholders&words[]=compliance&words[]=pledged&words[]=spyglass&words[]=leverages&words[]=subordinate&words[]=estate&words[]=appraisers&words[]=county&words[]=shrine&words[]=foresight&words[]=granite&words[]=available&words[]=permitted&words[]=accessible&words[]=academy&words[]=amazing&words[]=travel&words[]=broker&words[]=to+this+end&words[]=subject+to&words[]=verification&words[]=declarative&words[]=prospective&words[]=signatory&words[]=voe&words[]=perm&words[]=sav&words[]=force&words[]=pertinent&words[]=facsimile&words[]=sidetracked&words[]=colleague&words[]=hygenic&words[]=desperate&words[]=rustic&words[]=glamorous&words[]=mediocre&words[]=horrendous&words[]=intended&words[]=barrels&words[]=injured&words[]=alyssa&words[]=honda&words[]=expected&words[]=drunken&words[]=groovy&words[]=committee&words[]=cumbersome&words[]=administer&words[]=disburse&words[]=binding&words[]=supplementary&words[]=medium&words[]=affairs&words[]=personas&words[]=cadence&words[]=minutes&words[]=mandating&words[]=expedite&words[]=covenants&words[]=personnel&words[]=snob&words[]=unabashed&words[]=bespoke&words[]=deck&words[]=mortals&words[]=wfh&words[]=inked&words[]=gutter&words[]=popup&words[]=hopping&words[]=respects&words[]=tuck&words[]=broader&words[]=extensively&words[]=roll&words[]=confidence&words[]=chill&words[]=tinyurl&words[]=%E6%97%85%E9%A4%A8%E9%A3%AF%E5%BA%97%E5%85%A5%E4%BD%8F%E7%AF%87&words[]=rewarding&words[]=federal&words[]=commission&words[]=fidelity&words[]=brokerage&words[]=%E5%88%86%E4%BA%AB%E7%B6%93%E9%A9%97%E8%AB%87&words[]=covfefe&words[]=card-element&words[]=ovient&words[]=sloopy&words[]=upbeat&words[]=immersion&words[]=shelves&words[]=trolley&words[]=till&words[]=cashier&words[]=chemist%27s&words[]=toothpaste&words[]=loose&words[]=gents&words[]=nutritional&words[]=banknote&words[]=greengrocer%27s&words[]=florist%27s&words[]=newsagent%27s&words[]=delicatessen&words[]=sporting+goods&words[]=anticipate&words[]=eclectic&words[]=with&words[]=alfredo&words[]=mesmerized&words[]=tenants&words[]=facility&words[]=cob&words[]=up+and+running&words[]=admittedly&words[]=pull+in&words[]=bone&words[]=prerequisites&words[]=deep+dive&words[]=affords&words[]=covenant&words[]=springboard&words[]=leverage&words[]=augmented&words[]=appraisal&words[]=logical&words[]=leveraged&words[]=thumbnail&words[]=hang&words[]=rants&words[]=tearing&words[]=shout&words[]=employ&words[]=duped&words[]=paginated&words[]=engulfed&words[]=maintenance&words[]=executive&words[]=focus&words[]=companies&words[]=admin&words[]=wrap+up&words[]=solicitor&words[]=forrest&words[]=gump&words[]=mafia&words[]=doable&words[]=affection&words[]=awe&words[]=sake&words[]=ripping&words[]=entice&words[]=opt+in&words[]=opponents&words[]=tactics&words[]=untapped&words[]=struck&words[]=gravy&words[]=characteristics&words[]=probably&words[]=founder&words[]=familiarize&words[]=wondered&words[]=disseminate&words[]=grail&words[]=trump&words[]=opinion&words[]=aguas&words[]=cemented&words[]=chaff&words[]=mediterranean&words[]=displaced&words[]=troll&words[]=rep&words[]=adore&words[]=hilarious&words[]=crumbs&words[]=courtesy&words[]=slump&words[]=racism&words[]=snares&words[]=hygiene&words[]=ingesting&words[]=badgered&words[]=citation&words[]=convenience&words[]=pier&words[]=ramps&words[]=reel&words[]=lure&words[]=critters&words[]=bait&words[]=moseyed&words[]=tug&words[]=slack&words[]=taut&words[]=finance+lease&words[]=mobster&words[]=cater&words[]=immersive&words[]=cervical&words[]=choppy&words[]=changes&words[]=prism&words[]=cameraman&words[]=premise&words[]=vase&words[]=rivals&words[]=scorecard&words[]=caliber&words[]=members&words[]=pray&words[]=autism&words[]=dig+up&words[]=glamour&words[]=toll&words[]=%E7%99%BD%E5%90%83%E7%9A%84%E5%8D%88%E9%A4%90&words[]=acquisition&words[]=jack-of-all-trades&words[]=motto&words[]=diminishing&words[]=motivations&words[]=stretch&words[]=shattered&words[]=sheeperic@gmail.com&words[]=benz+c300&words[]=vbwulf&words[]=student638701&words[]=easeries&words[]=eurasian&words[]=pastry&words[]=knockoff&words[]=shred&words[]=hush&words[]=kento&words[]=%E9%B3%B3%E5%87%B0%E5%90%8D%E7%B2%A5&words[]=16.625&words[]=json.stringify&words[]=esidua&words[]=circular_dependency&words[]=fits+into+the+space&words[]=managementfeature&words[]=borrowing+entity&words[]=collateral+documents&words[]=company+letterhead&words[]=best+day+to+contact&words[]=time+being&words[]=.toutcstring()&words[]=chamber+of+commerce+number&words[]=raboenco+number&words[]=notify_a_user_to_register&words[]=tsung-yao+chang&words[]=loan+committee+dashboard&words[]=loan+committee+minutes&words[]=application+scorecard+result&words[]=lifellow&words[]=documentapi&words[]=autopricinggenerator1&words[]=autoscoregenerator1&words[]=npm+install+stripe+--save&words[]=stripe::charge.list&words[]=commoditizes&words[]=mindflash&words[]=stripe::charge.retrieve&words[]=frickin&words[]=member+vote&words[]=meetingagenda&words[]=dogfood&words[]=bumodbljlnflhcj0uykaryqe&words[]=in+the+example+below&words[]=that+needs+to+be+made&words[]=mindbear&words[]=interim&words[]=genesis&words[]=fledged&words[]=peon&words[]=coliseum&words[]=venue&words[]=concurr&words[]=genesis__committee_member__c&words[]=documentscovenents&words[]=00000586&words[]=otes+for&words[]=showing+rows+1-2+of+2&words[]=industry%27s+standard+dummy&words[]=est+product+123&words[]=30-7-2017+2:00&words[]=standard+object+detail+page&words[]=equirescript&words[]=me+remaining&words[]=indirect+exposure&words[]=toaster+pastries&words[]=cling+to&words[]=taming&words[]=stump&words[]=display&words[]=sync+up&words[]=zamberlan&words[]=dasher&words[]=nectar&words[]=muffs&words[]=snagged&words[]=shoved&words[]=prescription&words[]=defer&words[]=adoption&words[]=daunting&words[]=nitty-gritty&words[]=agnostic&words[]=mitigate&words[]=advocate&words[]=proprietary&words[]=syndication&words[]=password&words[]=decisive&words[]=concession&words[]=disputes&words[]=disputed&words[]=delinquent&words[]=legitimate&words[]=migraine&words[]=dysfunctions&words[]=unabridged&words[]=work&words[]=rules&words[]=just&words[]=procure&words[]=shallots&words[]=paste&words[]=blockbuster&words[]=sciatica&words[]=propane&words[]=darn&words[]=maternity&words[]=valet&words[]=decommissioned&words[]=linens&words[]=loft&words[]=haul&words[]=dolly&words[]=casters&words[]=incandescent&words[]=panicking&words[]=adverse&words[]=consolidating&words[]=might&words[]=hurdles&words[]=barn&words[]=glorious&words[]=voila&words[]=disproportionate&words[]=morals&words[]=incorporation&words[]=drawn&words[]=cease&words[]=flakey&words[]=precludes&words[]=tenant&words[]=jeopardize&words[]=compromise&words[]=obfuscate&words[]=pessimal&words[]=canonical&words[]=fastidiously&words[]=cave&words[]=intermingle&words[]=are&words[]=architecture&words[]=operating&words[]=save&words[]=daryl+hannah&words[]=disruptive&words[]=inadvertently&words[]=signer&words[]=signers&words[]=misled&words[]=received&words[]=close&words[]=protagonists&words[]=regressed&words[]=mucus&words[]=intelligent&words[]=advisable&words[]=patch&words[]=renovated&words[]=cypress&words[]=state&words[]=suggest&words[]=versatility&words[]=palatable&words[]=intake&words[]=glitch&words[]=ceramic&words[]=parrot&words[]=gag&words[]=tacky&words[]=provision&words[]=purge&words[]=transform&words[]=punishable&words[]=chilling&words[]=sophistication&words[]=dissolutions&words[]=remarkable&words[]=network&words[]=networker&words[]=diverted&words[]=bruise&words[]=bruises&words[]=bruised&words[]=seeking&words[]=craft&words[]=demandware&words[]=oversight&words[]=centurion&words[]=express&words[]=locations&words[]=lounge&words[]=tumble&words[]=cunningly&words[]=devalued&words[]=reframes&words[]=entrepreneurs&words[]=extremist&words[]=narrowest&words[]=paying+off&words[]=fault&words[]=crease&words[]=daemonizing&words[]=process&words[]=parlor&words[]=unwavering&words[]=dispassionate&words[]=immovable&words[]=prematurely&words[]=spiral&words[]=drill&words[]=secretive&words[]=opposed&words[]=accumulated&words[]=cobbled-together&words[]=bluegrass&words[]=transmission&words[]=capturing&words[]=payment&words[]=point&words[]=transaction&words[]=items&words[]=distinctly&words[]=leftist&words[]=openly&words[]=disdain&words[]=pathologizing&words[]=linguistic&words[]=interventions&words[]=attributable&words[]=hesitate&words[]=ooo&words[]=plausible&words[]=provisional&words[]=estranged&words[]=deniability&words[]=futile&words[]=reconciliation&words[]=ricin&words[]=custody&words[]=junkie&words[]=cuff&words[]=rashly&words[]=revive&words[]=paramedics&words[]=flow&words[]=contemptible&words[]=probing&words[]=cartel&words[]=shove&words[]=catalyst&words[]=whereabouts&words[]=snappy&words[]=savvy&words[]=astray&words[]=upsertrecord&words[]=incidental&words[]=subsidize&words[]=cozy&words[]=fabric&words[]=garment&words[]=furnished&words[]=50+conversations+h&words[]=comprehensive&words[]=cords&words[]=flashy&words[]=enlightment&words[]=restocking&words[]=tangle&words[]=tangle+with&words[]=solely&words[]=value+proposition&words[]=mrr&words[]=maverick&words[]=maniac&words[]=homicidal&words[]=wool&words[]=chalk&words[]=sober&words[]=self-acceptance&words[]=ethnicity&words[]=hispanic&words[]=anticipated&words[]=alleged&words[]=throttling&words[]=resurgence&words[]=deliberately&words[]=prolong&words[]=surfaced&words[]=settle&words[]=unravel&words[]=fiction&words[]=spun+up&words[]=lien&words[]=dodged&words[]=untenable&words[]=slick&words[]=plastered&words[]=spank&words[]=pediatric&words[]=buzz&words[]=preoccupation&words[]=profusely&words[]=reputable&words[]=despise&words[]=trick&words[]=cripple&words[]=ploy&words[]=hectic&words[]=salvage&words[]=metric&words[]=further&words[]=furthering&words[]=blackmail&words[]=expenditure&words[]=sturdy&words[]=precursor&words[]=methylamine&words[]=sloppy&words[]=duly&words[]=ramping&words[]=pistol&words[]=shipment&words[]=s05e05&words[]=breaking&words[]=piddling&words[]=rip+off&words[]=marginally&words[]=dilution&words[]=spillage&words[]=pride&words[]=busted&words[]=locomotive&words[]=wack&words[]=intimidation&words[]=dispose+of&words[]=screwing&words[]=bastard%27s&words[]=slip+up&words[]=steep&words[]=stalking&words[]=tossed&words[]=errand&words[]=erran&words[]=toss&words[]=hairy&words[]=brevity&words[]=aforementioned&words[]=solace&words[]=scholastic&words[]=tweak&words[]=ligaments&words[]=ligament&words[]=remitting&words[]=permanente&words[]=ibuprofen HTTP/1.1" 400 5 "https://www.birchwords.co/" "Mozilla/5.0 (Macintosh; 
Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"

**Comment by nateberkopec** [comment]
Yeah, we have several buffers which have to have limits on their size. We chose a different one than nginx. You should be using a POST here. Marking as wontfix.

**Comment by nhaglind** [comment]
Is there a better way around this? I also have a similar situation in which I need to use GET to gather long parameters and I'm not sure if's that specific of a use case.

```
2018-03-22 11:08:51 -0500: HTTP parse error, malformed request (): #<Puma::HttpParserError: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length (was 16162)>
```

**Comment by sekmo** [comment]
Nothing new from the front?

**Comment by smarjin** [comment]
@sekmo @poc7667 not sure if it's still relevant but [**these docs**](https://github.com/puma/puma/blob/15b079439222e489915380021b9dca7b9fa5ff65/docs/compile_options.md#compile-options) show a workaround by increasing the value of QUERY_STRING.
