### ISSUE TITLE
HOWTO: log memory/object allocations per request

### ISSUE THREAD

**Issue by karpa13a** [puma/puma#1496]
Hello here!
it's there any way to log memory/object allocated per request in rails application?
currently i investigating memory bloat at our app server, running only rails app under puma in -w 6 -t 1:16 configuration
in monitoring this looks like
![memory-day-leaks](https://user-images.githubusercontent.com/454114/34376906-3ab227f2-eb10-11e7-93c5-8d5eea6921da.png)
/rolling restart at 07-30, OOM-killer working well, restarts after deploy - working well/ :)
we have increased memory to 8Gb, to check out, may be this is normal behavior. but not.
we can raise to 16Gb, but i think this is useless)
unfortunately i don't see any consistency in this problem( 

I make the assumption, that some request to app generate too many objects (and eats memory), and memory do not return to system.
GC.stat from "leaked" worker:
```
{:count=>372, 
:heap_allocated_pages=>7433,
:heap_sorted_length=>15250,
:heap_allocatable_pages=>0, 
:heap_available_slots=>3029629, 
:heap_live_slots=>1062327, 
:heap_free_slots=>1967302, 
:heap_final_slots=>0, 
:heap_marked_slots=>1062326, 
:heap_eden_pages=>7433, 
:heap_tomb_pages=>0, 
:total_allocated_pages=>15253, 
:total_freed_pages=>7820, 
:total_allocated_objects=>354993817, 
:total_freed_objects=>353931490, 
:malloc_increase_bytes=>448, 
:malloc_increase_bytes_limit=>16777216, 
:minor_gc_count=>337, 
:major_gc_count=>35, 
:remembered_wb_unprotected_objects=>14716, 
:remembered_wb_unprotected_objects_limit=>29432, 
:old_objects=>1038881, 
:old_objects_limit=>2077762, 
:oldmalloc_increase_bytes=>1260208, 
:oldmalloc_increase_bytes_limit=>131586007}
```
from "not leaked":
```
{:count=>693, 
:heap_allocated_pages=>4340, 
:heap_sorted_length=>4340, 
:heap_allocatable_pages=>0, 
:heap_available_slots=>1768974, 
:heap_live_slots=>1054787, 
:heap_free_slots=>714187, 
:heap_final_slots=>0, 
:heap_marked_slots=>1054703, 
:heap_eden_pages=>4340, 
:heap_tomb_pages=>0, 
:total_allocated_pages=>4357, 
:total_freed_pages=>17, 
:total_allocated_objects=>228155211, 
:total_freed_objects=>227100424, 
:malloc_increase_bytes=>9392, 
:malloc_increase_bytes_limit=>16777216, 
:minor_gc_count=>640, 
:major_gc_count=>53, 
:remembered_wb_unprotected_objects=>14371, 
:remembered_wb_unprotected_objects_limit=>28742, 
:old_objects=>1031588, 
:old_objects_limit=>2063176, 
:oldmalloc_increase_bytes=>9832, 
:oldmalloc_increase_bytes_limit=>27318891}
```

no, i do not trying to use jemalloc. yes, i will, but i need to solve root cause(as i think).
no, i do not tune GC or somthing.

my question in topic: it's there any way to log memory/object allocated per request in rails application running under puma?

### System configuration

ubuntu 16.04 at ec2

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux-gnu]
**Rails version**: rails (5.1.4)
**Puma version**: puma (3.10.0)

**Comment by benoittgt** [comment]
Did you check https://github.com/schneems/derailed_benchmarks ?

**Comment by karpa13a** [comment]
@benoittgt memory_profiler i'll use after i get "fat" request. but i need a "light" version to use in production(
i'm looking at https://github.com/MiniProfiler/rack-mini-profiler, description says,
can log allocations/memory usage. but i cannot locate my case(

**Comment by karpa13a** [comment]
well
after switching to jemalloc, memory usage looks like
![memory-day-leaks-jm](https://user-images.githubusercontent.com/454114/35196918-5b235026-fefa-11e7-9efb-3d6ef79fe8ea.png)

"commited" going to sky. this is VSZ from ps aux output. RSS size looks ok.
but, i think this situation with server "not optimal"

**Comment by nateberkopec** [comment]
VSZ isn't important, though. On a 64-bit system virtual address space is practically infinite.

Closing because this is outside the scope of the Puma issue tracker.
