### ISSUE TITLE
Symbol not found: _SSL_library_init

### ISSUE THREAD

**Issue by nratter** [puma/puma#1497]
### Steps to reproduce

1) `rails s` (using puma)

### Expected behavior

Expect it to run :)

### Actual behavior

`➜  keymash git:(master) ✗ rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run 'rails server -h' for more startup options
dyld: lazy symbol binding failed: Symbol not found: _SSL_library_init
  Referenced from: /Users/nratter/.rvm/gems/ruby-2.5.0@keymash/gems/puma-3.10.0/lib/puma/puma_http11.bundle
  Expected in: flat namespace

dyld: Symbol not found: _SSL_library_init
  Referenced from: /Users/nratter/.rvm/gems/ruby-2.5.0@keymash/gems/puma-3.10.0/lib/puma/puma_http11.bundle
  Expected in: flat namespace

[1]    25476 trace trap  rails s`

### System configuration

**Ruby version**: 2.5.0p0 (also tried 2.4.3)
**Rails version**: 2.1.4
**Puma version**: 2.11 (also tried 2.10)

**Comment by rrosen** [comment]
seeing this too when I try to run https://github.com/puma/puma-dev/

OSX 10.11 El Capitan
Ruby 2.4.1
Puma 3.10

**Comment by stetsonthree** [comment]
Same error

Mac OS 10.13.2 High Sierra
Ruby 2.5.0
Rails 5.0.6
Puma 3.11.0

**Comment by jmealo** [comment]
FWIW, This is related to compiling `uws`. I'm having the same issue right now on OSX.

**Comment by toroc** [comment]
I'm also having this issue on OSX.

**Comment by pjscopeland** [comment]
I was having this issue in a test suite. Downgrading Ruby from 2.4.2 to 2.3.6 fixed it for me.

**Comment by seanstewart** [comment]
Try pointing puma to your brew-installed OpenSSL installation:
`gem install puma -v '3.11.0' --with-cppflags=-I$(brew --prefix openssl)/include`

OR

Configure your system to always build puma with the additional include paths:
`bundle config build.puma --with-opt-include=/usr/local/opt/openssl/include`
`bundle install`

**Comment by 2potatocakes** [comment]
Thanks @seanstewart 👍  - the `bundle config` option you suggested didn't work for me, but it works fine using your other suggestion
`bundle config build.puma --with-cppflags=-I$(brew --prefix openssl)/include`

**Comment by rrosen** [comment]
Thanks @seanstewart!  I had to run `gem install puma -v '3.11.0' -- --with-cppflags=-I$(brew --prefix openssl)/include` (note the extra --)

**Comment by filipkis** [comment]
Stumbled on this issue recently. I actually didn't do any changes to my gems or anything ruby related. However, what I think broke it in my case is that Java SDK had an update. That's at least the only thing I remember doing outside my code between moment it worked and moment it didn't work.

Anyhow, none of the above fixes worked for me. What eventually worked was

```
 PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig" gem install puma -v "5.6.1"
 ```
 
 I did reinstall openssl with brew a few times, even whole ruby, so I cannot be sure if above command alone would have fixed in on the first try, but I think it would.

**Comment by SealsRock12** [comment]
@filipkis That worked for me, tysm!

**Comment by oferreiro** [comment]
I'm using Macports. The default openssl lib is openssl3, wich is the version 3.0.1 today. 

`$ pkg-config openssl --cflags`
**-I/opt/local/libexec/openssl3/include**

I cannot make it works with puma 5.6.1.
I have use these commands fix.

`bundle config --local build.puma --with-pkg-config=/opt/local/lib/openssl-1.1/pkgconfig`
`bundle install`
