### ISSUE TITLE
systemd socket activation Errno::EBADF: Bad file descriptor - not a socket file descriptor

### ISSUE THREAD

**Issue by olegantonyan** [puma/puma#1499]
### Steps to reproduce

1) Follow the instructions here https://github.com/puma/puma/blob/master/docs/systemd.md and create `puma.socket` and `puma.service` files for systemd socket activation
2) After starting the service check its status `systemctl status puma.socket puma.service`

### Expected behavior

Successful start

### Actual behavior

```
● puma.socket - puma accept sockets
   Loaded: loaded (/etc/systemd/system/puma.socket; enabled; vendor preset: enabled)
   Active: failed (Result: service-start-limit-hit) since Wed 2018-01-03 08:59:03 UTC; 3s ago
   Listen: 127.0.0.1:3000 (Stream)

Jan 03 08:58:59  systemd[1]: Listening on puma accept sockets.
Jan 03 08:59:03  systemd[1]: puma.socket: Unit entered failed sta

● puma.service - puma server
   Loaded: loaded (/etc/systemd/system/puma.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-01-03 08:59:03 UTC; 3s ago
  Process: 11775 ExecStart=/bin/bash -lci bundle exec puma --config ./config/puma.rb -b tcp:/
 Main PID: 11775 (code=exited, status=1/FAILURE)
      CPU: 581ms
```

Puma's log:
```
Errno::EBADF: Bad file descriptor - not a socket file descriptor
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/binder.rb:65:in `for_fd'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/binder.rb:65:in `block (2 levels) in import_from_env'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/binder.rb:63:in `times'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/binder.rb:63:in `block in import_from_env'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/binder.rb:57:in `each'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/binder.rb:57:in `import_from_env'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/launcher.rb:52:in `initialize'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/cli.rb:68:in `new'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/lib/puma/cli.rb:68:in `initialize'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/bin/puma:8:in `new'
shared/bundle/ruby/2.4.0/gems/puma-3.11.0/bin/puma:8:in `<top (required)>'
shared/bundle/ruby/2.4.0/bin/puma:22:in `load'
shared/bundle/ruby/2.4.0/bin/puma:22:in `<top (required)>'
```

### System configuration

**Ruby version**: 2.4.1p111
**Rails version**: 5.1.4
**Puma version**: 3.11.0

puma.rb
```
FileUtils.mkdir_p 'tmp/sockets'

threads 1, 16
environment ENV['RAILS_ENV']
```

Without socket it works just fine

**Comment by molfar** [comment]
I have very similar situation. Errors:
There is already a server bound to: tmp/puma/puma.sock
Address already in use - bind(2) for "0.0.0.0" port 9295
Depending on puma config (tcp or socket).

**Comment by dekellum** [comment]
Hi, I try to help with Puma and systemd but I only check for new issues periodically.

Could you include your specific systemd socket and service config files? The extra indirection through `bash -lci` on ExecStart, or bundle exec without --keep-file-descriptors, are both opportunities to have the socket FDs closed before they reach puma.   If the bash is due to some RVM/rbenv/etc., they tend to have some provision for building at least a bundle command wrapper (with the right ruby), if not a working puma command wrapper (and right bundle and ruby) that makes this all one ruby process with no further execs, etc.

**Comment by dekellum** [comment]
@molfar, your error message doesn't sound the same at all to me.  Can't help without seeing the configs. Likely better in a new issue.

**Comment by molfar** [comment]
@dekellum I didnt dive into this problem, just tried to follow instructions from puma's doc. I'm not linux administrator at all... I also asked my hosting support to solve this problem, they spent a while day long and could not resolve it. Thats why I decided to inform with issue. For now I gave up with this socket activation feature and use simple systemd service. So you could close this issue if you wish.

**Comment by olegantonyan** [comment]
https://github.com/olegantonyan/puma_systemd_bug here is a fresh new rails app with `puma.service` and `puma.socket`

`~/.bashrc`
```
# nodenv
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
```

**Comment by olegantonyan** [comment]
Works without `/bin/bash -lci` 
puma.service
```
[Unit]
Description=Puma HTTP Server
After=network.target

Requires=puma.socket

[Service]
Type=simple
WorkingDirectory=/home/oleg/projects/github/puma_systemd_bug
Environment=PUMA_DEBUG=1
Environment=PATH=/home/oleg/.nodenv/shims/:/bin:/usr/bin
ExecStart=/home/oleg/.rbenv/shims/bundle exec puma --config config/puma.rb
Restart=always
User=oleg
Group=users

[Install]
WantedBy=multi-user.target
```

thx @molfar

**Comment by tagliala** [comment]
Hi everyone 👋 

I'm getting the same issue when upgrading from Ruby 2.5.3 to Ruby 2.6.0

I think there is something wrong in my configuration, but any help/hint/suggestion would be appreciated

### Ruby 2.6.0
```
Jan 04 14:28:14 machine systemd[1]: Started Puma HTTP Server (app staging).
Jan 04 14:28:14 machine systemd[1]: Starting Puma HTTP Server (app staging)...
Jan 04 14:28:15 machine rvm[15524]: /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:65:in `for_fd': Bad file descriptor - not a socket file descriptor (Errno::EBADF)
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:65:in `block (2 levels) in import_from_env'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:63:in `times'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:63:in `block in import_from_env'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:57:in `each'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/binder.rb:57:in `import_from_env'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/launcher.rb:52:in `initialize'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/cli.rb:69:in `new'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/lib/puma/cli.rb:69:in `initialize'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/bin/puma:8:in `new'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/gems/puma-3.12.0/bin/puma:8:in `<top (required)>'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/bin/puma:23:in `load'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/bin/puma:23:in `<main>'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
Jan 04 14:28:15 machine rvm[15524]: from /var/www/app/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
Jan 04 14:28:15 machine systemd[1]: puma_app_staging.service: main process exited, code=exited, status=1/FAILURE
Jan 04 14:28:15 machine systemd[1]: Unit puma_app_staging.service entered failed state.
Jan 04 14:28:15 machine systemd[1]: puma_app_staging.service failed.
Jan 04 14:28:16 machine systemd[1]: puma_app_staging.service holdoff time over, scheduling restart.
Jan 04 14:28:16 machine systemd[1]: start request repeated too quickly for puma_app_staging.service
Jan 04 14:28:16 machine systemd[1]: Failed to start Puma HTTP Server (app staging).
Jan 04 14:28:16 machine systemd[1]: Unit puma_app_staging.service entered failed state.
Jan 04 14:28:16 machine systemd[1]: puma_app_staging.service failed.
```

### Ruby 2.5.3
```
Jan 04 14:30:33 machine systemd[1]: Started Puma HTTP Server (app staging).
Jan 04 14:30:33 machine systemd[1]: Starting Puma HTTP Server (app staging)...
Jan 04 14:30:35 machine rvm[21579]: * Pruning Bundler environment
Jan 04 14:30:35 machine rvm[21579]: [21579] Puma starting in cluster mode...
Jan 04 14:30:35 machine rvm[21579]: [21579] * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
Jan 04 14:30:35 machine rvm[21579]: [21579] * Min threads: 0, max threads: 16
Jan 04 14:30:35 machine rvm[21579]: [21579] * Environment: staging
Jan 04 14:30:35 machine rvm[21579]: [21579] * Process workers: 4
Jan 04 14:30:35 machine rvm[21579]: [21579] * Phased restart available
Jan 04 14:30:35 machine rvm[21579]: [21579] * Activated unix:///var/www/app/shared/tmp/sockets/puma.sock
Jan 04 14:30:35 machine rvm[21579]: [21579] Use Ctrl-C to stop
```

**Comment by daveallie** [comment]
Hi @tagliala did you have any luck here? Stumbled into the same problem.

**Comment by tagliala** [comment]
@daveallie , no, sorry. 😢 

I did not tried 2.6.1 and 2.6.2 but I think it will be the same.

Please let me know if you will be luckier than me

**Comment by daveallie** [comment]
I'm on 2.6.2 and it's still failing. Tried replacing the `/bin/bash` wrapper in systemd with a bundle rvm wrapper, but it still fails with the same error.

I'll have a bit more a dig, but could just be stuck on 2.5 for a while 😢

**Comment by tagliala** [comment]
@daveallie I've tried a lot of things, including the bundle rvm stuff and permissions on socket, but I did not have a list of what I've tried.  I will try to provide you the details of the machine that is failing. Maybe it is OS related

**Comment by daveallie** [comment]
For reference, machine it's failing on for me:

```
ruby@ip-10-2-29-241:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
ruby@ip-10-2-29-241:~$ uname -a
Linux ip-10-2-29-241 4.4.0-1077-aws #87-Ubuntu SMP Wed Mar 6 00:03:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by tagliala** [comment]
Completely different for me: 
```sh
$  hostnamectl
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-693.el7.x86_64
      Architecture: x86-64

$  systemctl --version
systemd 219
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

Here it is my configuration:

Service:
```
[Unit]
Description=Puma HTTP Server (application staging)
After=network.target
Requires=puma_application_staging.socket

[Service]
Type=simple
User=user
WorkingDirectory=/var/www/application/current

# Helpful for debugging socket activation, etc.
# Environment=PUMA_DEBUG=1
Environment=RACK_ENV=staging
Environment=RAILS_ENV=staging
Environment=RAILS_SERVE_STATIC_FILES=enabled
Environment=BUNDLE_GEMFILE=/var/www/application/current/Gemfile

ExecStart=/home/user/.rvm/bin/rvm /var/www/application/current do bundle exec puma -C /var/www/application/shared/puma.rb

Restart=always

[Install]
WantedBy=multi-user.target
```

Socket:
```
$ cat /etc/systemd/system/puma_application_staging.socket 
[Unit]
Description=Puma HTTP Server Accept Sockets (application staging)

[Socket]
ListenStream=/var/www/application/shared/tmp/sockets/puma.sock

# Socket options matching Puma defaults
NoDelay=true
ReusePort=true
Backlog=1024

[Install]
WantedBy=sockets.target
```

socket permissions:
```
srw-rw-rw- 1 root root 0 Jan  4 14:17 /var/www/application/shared/tmp/sockets/puma.sock
```

Puma:
```
#!/usr/bin/env puma

directory '/var/www/application/current'
rackup "/var/www/application/current/config.ru"
environment 'staging'

tag ''

pidfile "/var/www/application/shared/tmp/pids/puma.pid"
state_path "/var/www/application/shared/tmp/pids/puma.state"
stdout_redirect '/var/www/application/shared/log/puma_access.log', '/var/www/application/shared/log/puma_error.log', true

threads 0,16

bind 'unix:///var/www/application/shared/tmp/sockets/puma.sock'

workers 4

prune_bundler

# on_restart do
#  puts 'Refreshing Gemfile'
#  ENV["BUNDLE_GEMFILE"] = ""
# end
```

**Comment by daveallie** [comment]
Updated my comment to include the same config files, we have pretty different setups, single-threaded vs multi-threaded, CentOS (Linux kernel v3) vs Ubuntu (Linux kernel v4). It's all pretty strange. I'm getting a growing suspicion that underlying code in `TCPServer.for_fd` has changed in Ruby 2.5 to 2.6 causing issues.

**Comment by daveallie** [comment]
Ok this is where I'm at:

The ruby line that is failing is:

```ruby
sock = TCPServer.for_fd(fd)
```

Which calls to https://github.com/ruby/ruby/blob/ruby_2_6/ext/socket/basicsocket.c#L25
Which then calls to https://github.com/ruby/ruby/blob/ruby_2_6/ext/socket/init.c#L78

The raise happens on line 83: `rb_syserr_fail(EBADF, "not a socket file descriptor");`, only if the condition `!is_socket(fd) || rb_reserved_fd_p(fd)` is true.

`is_socket` source hasn't changed. This is the diff from Ruby 2.5 to 2.6 of the source of `rb_reserved_fd_p` (in `thread_pthread.c`)

```diff
@@ -1766,20 +1908,23 @@ ruby_stack_overflowed_p(const rb_thread_t *th, const void *addr)
 int
 rb_reserved_fd_p(int fd)
 {
-#if USE_SLEEPY_TIMER_THREAD
-    if ((fd == timer_thread_pipe.normal[0] ||
-        fd == timer_thread_pipe.normal[1] ||
-        fd == timer_thread_pipe.low[0] ||
-        fd == timer_thread_pipe.low[1]) &&
-       timer_thread_pipe.owner_process == getpid()) { /* async-signal-safe */
+    /* no false-positive if out-of-FD at startup */
+    if (fd < 0)
+        return 0;
+
+#if UBF_TIMER == UBF_TIMER_PTHREAD
+    if (fd == timer_pthread.low[0] || fd == timer_pthread.low[1])
+        goto check_pid;
+#endif
+    if (fd == signal_self_pipe.normal[0] || fd == signal_self_pipe.normal[1])
+        goto check_pid;
+    if (fd == signal_self_pipe.ub_main[0] || fd == signal_self_pipe.ub_main[1])
+        goto check_pid;
+    return 0;
+check_pid:
+    if (signal_self_pipe.owner_process == getpid()) /* async-signal-safe */
        return 1;
-    }
-    else {
-       return 0;
-    }
-#else
     return 0;
-#endif
 }
```

![image](https://user-images.githubusercontent.com/968573/55198237-41eb0e00-5183-11e9-977c-bf27cc23356f.png)

Might need to compile ruby with some debug symbols or something to find which specific branch is being hit.

**Comment by daveallie** [comment]
@schneems I'm not really sure how much deeper it's worth going into here. Have you found any issues with people running Puma on Ruby 2.6 at Heroku? Does anything in that method diff jump out at you?

**Comment by dekellum** [comment]
Does ruby 2.6 work if you use a TCP socket instead of a UNIX-domain socket?  Do you really *need* a UNIX domain socket for your setups? I believe the _activation_ feature for UNIX-domain sockets has always been a bit of a kluge, since the activation feature was added to puma.  Maybe ruby 2.6 is just more precise in validating its socket types?

**Comment by tagliala** [comment]
@dekellum thanks for the information

> Does ruby 2.6 work if you use a TCP socket instead of a UNIX-domain socket?

My knowledge as a DevOp is limited, I do not know if I really need a UNIX-domain socket.

In reference to https://github.com/puma/puma/blob/master/docs/systemd.md#socket-activation and my configuration https://github.com/puma/puma/issues/1499#issuecomment-477782017

Should I change

```
[Socket]
ListenStream=/var/www/application/shared/tmp/sockets/puma.sock
```

to

```
ListenStream=0.0.0.0:<PUMA_PORT>
```

to switch from UNIX to TCP sockets?

**Comment by dekellum** [comment]
Yes, that is what I'm suggesting. Then whatever server you have in front of puma (on the same host given the unix socket) just needs to use the same port. Also, this is an old bug that had nothing to do with ruby 2.6. Might we open something new for this, perhaps with your findings regarding TCP vs UNIX domain socket?

**Comment by tagliala** [comment]
@daveallie have you the chance to try with a TCP socket and check if it works?

I'm working on a complete different thing at the moment, I don't know how much time it will require this test on my side

**Comment by daveallie** [comment]
TCP socket seems to give the same result: `Bad file descriptor - not a socket file descriptor`.

Removing the socket service and avoiding socket activation works perfectly fine.

**Comment by daveallie** [comment]
Seems like it's a configuration issue on our side, there are other people using TCP socket activation fine with Puma 3.12.1, MRI 2.6.2. (https://serverfault.com/questions/960132/puma-with-systemd-and-socket-activation-errnoeaddrinuse)

I'm curious if running this all on Ubuntu 18.04 would fix this for me.

**Comment by tagliala** [comment]
@daveallie thanks for the heads-up, please let me know if you manage to solve this

@dekellum sorry for the spam/off-topic on this thread. Is it fine to open a new issue related to the [systemd wiki page](https://github.com/puma/puma/blob/master/docs/systemd.md#socket-activation) for our problem under some configurations?

**Comment by dekellum** [comment]
@tagliala I think it would be appropriate, yes!  If I'm reading this post-closed thread correctly, something has more recently changed with the release of ruby 2.6.  I suspect its just a coincidence that it produces the same error as this old issue (which was ultimately just a user configuration error, associated with extra exec's). The same exact config works with ruby 2.5, correct?

**Comment by tagliala** [comment]
> The same exact config works with ruby 2.5, correct?

Correct! https://github.com/puma/puma/issues/1499#issuecomment-451445795

**Comment by tagliala** [comment]
@dekellum I've created this repository: https://github.com/tagliala/puma-socket

I was trying to reproduce the issue via Docker... but I was eventually able to start puma + systemd + ruby 2.6.2 with a UNIX socket, with both ubuntu and centos 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/556268/55594666-c79d2980-5740-11e9-92a5-a983a98fdcaf.png)

I know it is not the same environment as the other machine (and everything is running as root), but this is the best I can do at the moment

We can further discuss this issue on the other repo, feel free to start an issue. We could report something here if needed

**Comment by itolosa** [comment]
I think that I found a solution for this problem. It's related to shell interactivity. I believe that systemd does socket activation assigning the socket to the called executable, so when you call puma through some sort of interactivity like `bundle exec`, you are actually trying to bind the socket to `bundle` and not to puma directly. So a solution would be to call puma directly in `ExecStart`. This workaround works for me:
1. Create a binstub like official documentation says:
```
bundle binstubs puma --path ./sbin
```
2. Modify sbin/puma to update ruby path. Change the first line of the file to use the full path of ruby instead. In my case:
```
#!/home/deploy/.rbenv/shims/ruby
```
3. Then change `ExecStart` to use the recently created binstub to run puma:
```
ExecStart=/var/www/myapp/sbin/puma -C /var/www/myapp/config/puma.rb
```
I Hope that helps you

**Comment by tagliala** [comment]
@itolosa thanks!!!

I confirm it works

```
Apr 18 20:17:14 linux systemd[1]: Starting Puma HTTP Server (application staging)...
Apr 18 20:17:15 linux rvm[28648]: * Pruning Bundler environment
Apr 18 20:17:15 linux rvm[28648]: [28648] Puma starting in cluster mode...
Apr 18 20:17:15 linux rvm[28648]: [28648] * Version 3.12.1 (ruby 2.6.3-p62), codename: Llamas in Pajamas
Apr 18 20:17:15 linux rvm[28648]: [28648] * Min threads: 0, max threads: 16
Apr 18 20:17:15 linux rvm[28648]: [28648] * Environment: staging
Apr 18 20:17:15 linux rvm[28648]: [28648] * Process workers: 4
Apr 18 20:17:15 linux rvm[28648]: [28648] * Phased restart available
Apr 18 20:17:15 linux rvm[28648]: [28648] * Activated unix:///var/www/application/shared/tmp/sockets/puma.sock
```

For the records, with `rvm`, I'm using:

```
ExecStart=/home/carpool/.rvm/bin/rvm /var/www/application/current do /var/www/application/current/sbin/puma -C /var/www/application/shared/puma.rb
```

**Comment by daveallie** [comment]
As mentioned in #1777, `--keep-file-descriptors` does solve the issue for my specific bundler / rvm setup.
I just completely misread dekellum's comment and thought the suggestion was to remove that flag 😅
Thanks for the help everyone!

**Comment by augustocbx** [comment]
I've solved this issue with the following changes in the puma.rb (config file). In my case, I use capistrano to deploy and restart puma. The are 2 requirements to use the command **phased-restart**: workers >= 2 and don't use preload

```
workers 2
#preload_app! 
```

My restart command (**phased-restart**): 


`pumactl -S /srv/apps/my_app/shared/tmp/pids/puma.state -F /srv/apps/my_app/shared/config/puma.rb phased-restart
`

**Comment by h0jeZvgoxFepBQ2C** [comment]
> As mentioned in #1777, `--keep-file-descriptors` does solve the issue for my specific bundler / rvm setup.
> I just completely misread dekellum's comment and thought the suggestion was to remove that flag 😅

Could you show how you specified the ```bundle exec --keep-file-descriptors puma``` flag? I somehow can't find any code example on google somehow.

**Comment by tagliala** [comment]
@h0jeZvgoxFepBQ2C 

this is how it works for my systemd service

```
[Unit]
Description=Puma HTTP Server (ridesharing staging)
After=network.target
Requires=puma_ridesharing_staging.socket

[Service]
Type=simple
User=deployuser
WorkingDirectory=/home/deployuser/apps/appname/current
# Helpful for debugging socket activation, etc.
# Environment=PUMA_DEBUG=1
Environment=RACK_ENV=staging
Environment=RAILS_ENV=staging
Environment=RAILS_SERVE_STATIC_FILES=enabled
ExecStart=/home/deployuser/.rvm/bin/rvm /home/deployuser/apps/appname/current do bundle exec --keep-file-descriptors puma -C /home/deployuser/apps/appname/shared/puma.rb
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Hm ok, I have nearly the same setup, but I get following error:

```
Errno::ENOENT: No such file or directory @ apply2files - /home/user/apps/myapp/shared/sockets/puma.myapp.sock
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:368:in `unlink'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:368:in `block in close_listeners'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:363:in `each'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:363:in `close_listeners'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:205:in `close_binder_listeners'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cluster.rb:391:in `block in setup_signals'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cluster.rb:521:in `rescue in run'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cluster.rb:481:in `run'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/lib/puma/cli.rb:80:in `run'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/gems/puma-4.3.5/bin/puma:10:in `<top (required)>'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/bin/puma:23:in `load'
  /home/user/apps/myapp/shared/bundle/ruby/2.6.0/bin/puma:23:in `<top (required)>'
```

I have set:

```
ExecStart=/home/user/.rbenv/bin/rbenv exec bundle exec --keep-file-descriptors puma -C ..puma_config_path..
ExecStop=/home/user/.rbenv/bin/rbenv exec bundle exec --keep-file-descriptors pumactl -F ..puma_config_path.. stop
ExecReload=/home/user/.rbenv/bin/rbenv exec bundle exec --keep-file-descriptors pumactl -F ..puma_config_path.. restart
```

but also with removing ```ExecStop``` and ```ExecReload``` my call to ```sudo  systemctl restart puma.service``` deletes the socket?

**Comment by dentarg** [comment]
@h0jeZvgoxFepBQ2C from https://github.com/puma/puma/blob/v4.3.6/docs/systemd.md#socket-activation

> Note: Any wrapper scripts which exec, or other indirections in ExecStart, may result in activated socket file descriptors being closed before they reach the puma master process. ...

I can see that you are wrapping your `bundle exec` call in a `rbenv exec` call, maybe try without rbenv if you can, and see if it works?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Oh sorry, it looks like I only forgot to add ```Requires=puma-admin.socket``` 🙈 
Works fine with adding rbenv before and no ExecStop or ExecReload:

```
ExecStart=/home/user/.rbenv/bin/rbenv exec bundle exec --keep-file-descriptors puma -C ..puma_config_path..
```

**Comment by dentarg** [comment]
Since bundler-v2.3.0, `--keep-file-descriptors` is the default behaviour (no need to use the flag if your Bundler is recent enough): https://github.com/rubygems/rubygems/issues/3254, https://github.com/rubygems/rubygems/pull/4812
