### ISSUE TITLE
headers['Transfer-Encoding'] = 'chunked' -- makes server fail

### ISSUE THREAD

**Issue by arkadiyk** [puma/puma#150]
ENV: JRuby 1.7p2, jruby-rack 1.1.10, Rails 3.2.8

I noticed a request fails when I set `Transfer-Encoding` to `'chunk'`

Probably in `server.rb:486` should be `true` rather than `false` ? 

``` ruby
       when TRANSFER_ENCODING
            allow_chunked = false
            content_length = nil
```

**Comment by alexanderadam** [comment]
I'm very sorry to comment on this, quite old issue. I'm not sure whether it is _exact_ the same issue but for me it looks pretty much like it.

I tried to reproduce a minimal example [mentioned here](https://coderwall.com/p/kad56a/streaming-large-data-responses-with-rails):

```ruby
headers['X-Accel-Buffering'] = 'no'
headers['Cache-Control'] = 'no-cache'
headers['Transfer-Encoding'] = 'chunked'
headers.delete('Content-Length') # this breaks the request

self.response_body = Enumerator.new do |lines|
  1000.times do
    lines << [rand, rand].to_csv
  end
end
```
