### ISSUE TITLE
tmp_restart does not work with cluster mode app preloading

### ISSUE THREAD

**Issue by molfar** [puma/puma#1501]
### Steps to reproduce

1) start puma in cluster mode with preloading app

2) touch tmp/restart.txt

### Expected behavior

Rails should have reload changes from code

### Actual behavior

puma's output show restart messages, but rails does not reload new code

### System configuration

**Ruby version**: 2.5.0
**Rails version**: 5.1.4
**Puma version**: 3.11.0

**Comment by nateberkopec** [comment]
Cannot reproduce on a basic Rails app. Please re-open if you still have this problem and have any more clues/reproduction steps.
