### ISSUE TITLE
Problems shutting down gracefully after EOFErrors in 3.11.2

### ISSUE THREAD

**Issue by vincentwoo** [puma/puma#1507]
Following @evanphx's recent fixes for `read_nonblock`, things seem to be working better. One last issue may remain: following the thread pool catching `EOFError`, shutdown of puma can take quite a while, with another EOFError being displayed before shutdown:

```
^C[19337] - Gracefully shutting down workers...
Error reached top of thread-pool: EOFError (EOFError)
```

**Comment by chytreg** [comment]
As for me and some others, it happens also during runtime as well. ref: https://github.com/puma/puma/issues/1502#issuecomment-362289871
