### ISSUE TITLE
Example config.rb fails ruby syntax check

### ISSUE THREAD

**Issue by anovadox** [puma/puma#1509]
### Steps to reproduce
1) `git clone https://github.com/puma/puma`
2) `cd puma`
3) `ruby -wc examples/config.rb`
 
### Expected behavior
`Syntax OK`

### Actual behavior
`ruby: no Ruby script found in input (LoadError)`

### System configuration

**Ruby version**: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
**Puma version**: puma version 3.11.0

**Comment by olleolleolle** [comment]
The reason is the shebang line: `ruby -wc` can't tell that this example is a Ruby script.

If we'd change `ruby` in the shebang line to `puma`, or remove the shebang line, the syntax check would output "Syntax OK".

**Comment by nateberkopec** [comment]
> If we'd change ruby in the shebang line to puma

Other way around but this is correct. Puma is the correct shebang line here.
