### ISSUE TITLE
TypeError: no implicit conversion of Puma::MiniSSL::Socket into Integer

### ISSUE THREAD

**Issue by savanr** [puma/puma#1516]
Setting up server using Apache, Puma and Faye. Server is already running on  https://. Was trying to start Faye server over https:// though starting server over http:// was very easy in production mode.\

After few tweaks I got success to get Faye up over https://.  When trying to listen Faye it throws this error.

`		#<TypeError: no implicit conversion of Puma::MiniSSL::Socket into Integer>
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:763:in `attach_fd'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:763:in `attach_io'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:741:in `attach'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/faye-websocket-0.9.0/lib/faye/rack_stream.rb:26:in `initialize'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/faye-websocket-0.9.0/lib/faye/websocket.rb:70:in `new'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/faye-websocket-0.9.0/lib/faye/websocket.rb:70:in `initialize'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/faye-1.0.3/lib/faye/adapters/rack_adapter.rb:172:in `new'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/faye-1.0.3/lib/faye/adapters/rack_adapter.rb:172:in `handle_websocket'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/faye-1.0.3/lib/faye/adapters/rack_adapter.rb:78:in `call'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `call'
		/mnt/i3/shared/bundle/ruby/2.2.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'`

Getting issue over production server. Locally works fine.

**Comment by nateberkopec** [comment]
This is not a Puma bug. We reserve the issue tracker for bug reports, feature requests and the like. This looks like you have some sort of misconfiguration with Faye.
