### ISSUE TITLE
Binding.pry is difficult to use with Puma.

### ISSUE THREAD

**Issue by j3pic** [puma/puma#1517]
### Steps to reproduce

1) Write a Puma-based Rails app

2) Put a `binding.pry` in a controller or view.

3) Navigate to a URL that will activate that controller or view.

### Expected behavior

I would like it to be possible to configure special worker_timeout behavior just for Pry. A way to dynamically set this timeout from the `pry>` prompt would be shitty, but good enough.

### Actual behavior

The default `worker_timeout` will cut you off in the middle of a Pry session, and the only way
around it is to set it to a higher value statically in `config/puma.rb`, which applies to *all* requests, not just those that you interrupt with Pry. I still want it to time out in 60 seconds
if it's stuck for a reason other than me using `binding.pry`.

**Comment by vfonic** [comment]
You could specify different timeout for `Rails.env.development?`. I wouldn't rely on request timeout locally.

**Comment by nateberkopec** [comment]
Yeah, what @vfonic said.
