### ISSUE TITLE
RACK_ENV ignored inside a rails application

### ISSUE THREAD

**Issue by tigris** [puma/puma#1518]
### Steps to reproduce

1) rails new test-app && cd test-app

2) RACK_ENV=production puma

3) RAILS_ENV=production puma

I ran some extensive tests in docker containers: https://gist.github.com/tigris/a1c49d983753a921524b3b06317ff444

### Expected behavior

Both of the commands in (2) and (3) should result in a puma server being run in production mode. Since rails itself will honor a value of RACK_ENV when running rake tasks etc. E.g. `RACK_ENV=production rake db:migrate` will migrate a production database (as will setting RAILS_ENV, either is acceptable by rails).

### Actual behavior

puma will only listen to RAILS_ENV when the directory looks like a rails app, however when it does not look like a rails app, it's just a general rack app, then only RACK_ENV is listened to

### System configuration

**Ruby version**: 2.4.3p205 (also tested 2.3.3p222)
**Rails version**: 5.0.6 (also tested 5.1.4)
**Puma version**: 3.11.2

**Comment by nateberkopec** [comment]
[Puma doesn't have any awareness of RAILS_ENV.](https://github.com/puma/puma/search?utf8=%E2%9C%93&q=RAILS_ENV&type=)

**Comment by nateberkopec** [comment]
I think what you're seeing is probably that Puma's default environment is "development". Puma isn't reading RAILS_ENV.
