### ISSUE TITLE
Gracefully handle termination when puma process being killed

### ISSUE THREAD

**Issue by phuongnd08** [puma/puma#1519]
### Steps to reproduce

1) having a method that take some time to complete but responding to signal exception:
class SnailController < ApplicationController
  def perform
    sleep 1000
  rescue SignalException => e
    p [:exception, e.inspect]
  end
end

2) route to it from config/routes.rb
get '/snail' => 'snail#perform'

3) curl to it
curl -v "http://localhost:3000/snail"

4) kill puma with TERM then KILL
$ ps aux | grep puma | awk '{ print $2 }' | xargs -I{} kill -s TERM {}
$ sleep 10
$ ps aux | grep puma | awk '{ print $2 }' | xargs -I{} kill -s KILL {}

### Expected behavior
A signal exception being thrown and catched (and inspected)

### Actual behavior
No exception thrown/catched. The process being forcefully killed

### System configuration

**Ruby version**: 2.3.6
**Rails version**: 4.2.6
**Puma version**: 3.6.2

**Comment by nateberkopec** [comment]
Puma catches the TERM/KILL signal before it bubbles up to Rails. There's really nothing we can do about this, I would say the current behavior is what is expected.
