### ISSUE TITLE
Abort requests that are taking too long

### ISSUE THREAD

**Issue by fertobar** [puma/puma#1520]
hello,
I wonder if there is a way to set a max request timeout to abort long app requests with Ruby and Puma?

according doc seems worker_timeout is not suitable for this.

I was using https://github.com/heroku/rack-timeout but was is generating some memory leak issues.

Is is possible to config this setting in Puma?

**Comment by nateberkopec** [comment]
No, you've judged the situation correctly - rack-timeout is the proper tool here. If it has a memory leak, you'll have to open an issue with them.

**Comment by fertobar** [comment]
ok, thanks for the update
