### ISSUE TITLE
500 errors during phased reload

### ISSUE THREAD

**Issue by dstokes** [puma/puma#1522]
### Steps to reproduce

1) Start Puma with systemd configuration similar to
```systemd
[Unit]
Description=Puma HTTP Server
After=network.target

[Service]
Type=simple
User=deploy
WorkingDirectory=/srv/
EnvironmentFile=/srv/app.env
ExecStart=/bin/bash -c "exec /srv/vendor/bundle/bin/bundle exec puma -C /srv/config/puma.rb >>/var/log/puma/stdout.log 2>>/var/log/puma/stderr.log"
TimeoutStopSec=5
Restart=on-failure
RestartSec=10
ExecReload=/bin/kill -USR1 $MAINPID

[Install]
WantedBy=multi-user.target
```

2) Run a Siege against the web server to simulate production traffic
```
siege -c30 http://my_host
```

3) Trigger a phased reload
```
systemctl reload puma.service
```

### Expected behavior

Puma should do a phased reload without dropping any connections
```log
[6627] - Starting phased worker restart, phase: 1
[6627] + Changing to /srv
[6627] - Stopping 6632 for phased upgrade...
[6627] - TERM sent to 6632...
[6667] + Gemfile in context: /srv/Gemfile
[6627] - Worker 0 (pid: 6667) booted, phase: 1
[6627] - Stopping 6635 for phased upgrade...
[6627] - TERM sent to 6635...
[6690] + Gemfile in context: /srv/Gemfile
[6627] - Worker 1 (pid: 6690) booted, phase: 1
```

### Actual behavior

Puma returns 500 errors during a phased reload. The block responsible seems to be https://github.com/puma/puma/blob/42580133a8e9bdb42f55371a7dd0d1dbb02364b9/lib/puma/thread_pool.rb#L140-L144

```
[6627] - Starting phased worker restart, phase: 1
[6627] + Changing to /srv
[6627] - Stopping 6632 for phased upgrade...
[6627] - TERM sent to 6632...
[6667] + Gemfile in context: /srv/Gemfile
[6627] - Worker 0 (pid: 6667) booted, phase: 1
[6627] - Stopping 6635 for phased upgrade...
[6627] - TERM sent to 6635...
lowlevel_error_handler is being invoked
Unable to add work while shutting down
[6690] + Gemfile in context: /srv/Gemfile
[6627] - Worker 1 (pid: 6690) booted, phase: 1
```

### System configuration

**Ruby version**: 2.5.0p0
**Rails version**: 5.1.4
**Puma version**: 3.11.2

### Puma Config
```
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count
port        ENV.fetch("PORT") { 3000 }
environment ENV.fetch("RAILS_ENV") { "development" }
workers ENV.fetch("WEB_CONCURRENCY") { 2 }
plugin :tmp_restart
lowlevel_error_handler do |error, env|
  puts "lowlevel_error_handler is being invoked"
  puts error
  puts env
end
```

**Comment by dstokes** [comment]
I've reproduced the same issue with USR1, USR2 and systemd restarts with a systemd.socket configured.

**Comment by nateberkopec** [comment]
This is performing as documented. Phased restarts are done with `pumactl phased-restart`, not USR1/USR2. [See here](https://github.com/puma/puma/blob/2bc00e54716856cee22dee902a2dcceb229b9192/docs/restart.md).

**Comment by allaire** [comment]
We are experiencing the same issue.

@nateberkopec you mention to use `pumactl phased-restart` but AFAIK, it used USR1 under the hood:

https://github.com/puma/puma/blob/6d0efee913905c6b2b9046475cf5f18939ce6b1c/lib/puma/control_cli.rb#L204

I'm using inspeqtor with systemd:

`ExecReload=/bin/kill -USR1 $MAINPID`

**Comment by allaire** [comment]
@dstokes Sorry to bother, but I'm running the same exact setup as you, Did you figure it out?

Thanks!
