### ISSUE TITLE
Loading gems inside puma configuration does not respect bundler after pruning bundler environment

### ISSUE THREAD

**Issue by catphish** [puma/puma#1526]
### Steps to reproduce

1) Require and use a gem within the puma configuration script `config/puma.rb`. I do this frequently to generate configuration dynamically.

2) Have a newer version of the gem installed but an older version in a bundle.

3) Enable multiple workers `-w 2` and set `prune_bundler` in the config.

### Expected behavior

During start or restart, I would expect the "bundle" to be discarded and reloaded either before the configuration file is loaded, or after it is loaded.

### Actual behavior

During restart, the "bundle" is discarded, the config file is loaded *without bundler*, then bundler is activated, conflicting with the incorrect gem that was loaded by the config file.

### System configuration

**Ruby version**: 2.4.0p0
**Puma version**: 3.9.1

**Comment by nateberkopec** [comment]
This was fixed by #1105, which should be in 4.2.0.
