### ISSUE TITLE
Close connection to database if using preload ActiveRecord is not recommended anymore?

### ISSUE THREAD

**Issue by letrungkien** [puma/puma#1528]
Hi sorry. This is a merely a question out of curiosity, not an issue at all.

Thanks to `puma` team for making this great gem.

I am in a research phase for moving from `unicorn` to `puma` in production using Heroku.

And currently, we disconnect connection in `before_fork` and re-establish in `after_fork` (unicorn).

I read through your `README` and noticed that practice was recommended before but was removed by this [commit](https://github.com/puma/puma/commit/3006f267e943cc01f913f3b2c8a18d381972f7ac#diff-04c6e90faac2675aa89e2176d2eec7d8)

I also noticed that Heroku's `puma-heroku` gem adopted this recommendation in 2016: [PR](https://github.com/puma/puma-heroku/pull/2/files)

Could you please share your reason you don't suggest to close connection to database in `before_fork` anymore?

Thanks

**Comment by nateberkopec** [comment]
Your understanding is correct - this was a change in how Rails works though, not Puma.

**Comment by nateberkopec** [comment]
If you look around you can probably find the commit in Rails that changed this. I think it was @matthewd's commit.

**Comment by letrungkien** [comment]
Thank you very much @nateberkopec 
Good day to you.
