### ISSUE TITLE
Sintra+Puma+SSL

### ISSUE THREAD

**Issue by BlackNightFury** [puma/puma#1530]
Hi. I am currently trying to run sinatra+puma server with ssl.

I already had certificate and key file but cannot find the option to have the server working over https traffic.
I am not using config.ru

My current configuration is as followings:
  configure do
    set :server, :puma
    set :environment, :production
    set :daemonize, false

    if($use_tls)
      set :bind, "ssl://#{$localhostName}:#{$localhostPort}?key=./key.key&cert=./cert.crt"
    else
      set :bind, "tcp://#{$localhostName}:#{$localhostPort}"
    end
  end

**Comment by nateberkopec** [comment]
Sorry, we only have the time/resources to deal with bug reports and feature requests on the Puma issue tracker. Please try StackOverflow.
