### ISSUE TITLE
phased restart

### ISSUE THREAD

**Issue by khmunkhbat** [puma/puma#1531]
Hi

I'm trying to set puma(3.10.0) and capistrano(3) on rails(5.1.4).
And export to systemd by foreman like a below.

```
> [Unit]
> StopWhenUnneeded=true
> 
> [Service]
> User=centos
> WorkingDirectory=/var/www/rails/project_name/releases/20180312050734
> 
> Environment=RAILS_ENV=...
> Environment=PORT=...
> Environment=DB_HOST=...
> Environment=DB_NAME=...
> Environment=DB_USER=...
> Environment=DB_PASS=...
> Environment=NODE_ENV=...
> ExecStart=/bin/bash -lc 'bundle exec pumactl start'
> ExecReload=/bin/bash -lc 'bundle exec pumactl phased-restart'
> ExecStop=/bin/bash -lc 'bundle exec pumactl stop'
> PIDFile=/var/www/rails/project_name/releases/20180312050734/tmp/pids/puma.pid
> Restart=always
> StandardInput=null
> StandardOutput=syslog
> StandardError=syslog
> SyslogIdentifier=%n
> KillMode=process
```

And my puma's config

```
> require 'active_support'
> require 'active_support/core_ext'
> 
> rails_root = Dir.pwd
> 
> env = ENV.fetch('RAILS_ENV') { 'development' }
> environment env
> 
> port ENV.fetch('PORT') { 3000 }
> 
> directory rails_root
> if ['production', 'staging'].include?(env)
>   workers ENV.fetch("WEB_CONCURRENCY") { 2 }
>   threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
>   threads threads_count, threads_count
>   bind "unix://#{rails_root}/tmp/sockets/puma.sock"
>   stdout_redirect(
>     File.join(rails_root, 'log', 'puma.log'),
>     File.join(rails_root, 'log', 'puma-error.log'),
>     true
>   )
>   pidfile rails_root + '/tmp/pids/puma.pid'
>   state_path rails_root + '/tmp/pids/puma.state'
>   activate_control_app
> end
```

When i deploy start and stop is ok, but phased restart(hot restart) does not reload app.

If i execute "bundle exec pumactl phased-restart", puma's 2worker processes are changed, but there are no change in my app.

My environment

puma(3.10.0)
foreman (0.84.0)
capistrano(3)
ruby 2.4.1
rails(5.1.4)

any idea?

Apologize if there have any English mistake.

**Comment by nateberkopec** [comment]
> Apologize if there have any English mistake.

Don't worry about it, your English is great.

Not sure if this is a misconfiguration or a bug, but given the information you've provided I'm guessing it has to be a misconfiguration somewhere or we'd have a lot more bug reports about restarts.

**Comment by dekellum** [comment]
If the OP is still interested in this, it might be better to start with a recommended config of [systemd] doc, get it working,  and then see what the delta is/figure out how to automate the same with foreman or otherwise.  Most immediately, if puma is daemon'ing itself via pumactl/config, then the _Alternative Forking Configuration_ (linked doc) is definitely needed.  Otherwise and since this issue is old, I would suggest closing it.

[systemd]: https://github.com/puma/puma/blob/master/docs/systemd.md
