### ISSUE TITLE
Server locks when handling identical request even though it has available threads

### ISSUE THREAD

**Issue by alanhala** [puma/puma#1549]
### Steps to reproduce

1) Create a rack sample app simulating a slow IO operation like this one
```ruby
run Proc.new { |env|
  puts 'Request arrived'
  sleep(10)
  ['200', {'Content-Type' => 'text/html'}, ['get rack\'d']]
}
```

2) Run a server with puma, using 5 threads
```ruby
puma config.ru -t 5
```
3) Open the browser and make 5 request simultaneously  

### Expected behavior
The server should print exactly 5 times the 'Request arrived' message, as it has 5 threads than can take the request, wait 10 seconds, and then return the response.

### Actual behavior

Instead, it takes only the first request, waits until it finishes, then takes two other request, waits, and then takes the last two request.

This is a bit strange because it has some idle threads, but for some reason it's not using them to handle the requests.

I made more tests and I found out that if you send different query params in each request, it works as I expect it to work. So I'm assuming that this happens only when the received requests are completely identical, from the same browser and same parameters.

Does it look like a bug or something like that? Is it the expected behavior?

### System configuration

**Ruby version**: 2.3.1
**Puma version**: 3.11.3

**Comment by nateberkopec** [comment]
Probably something to do with your browser.

Does `$ curl -X GET localhost:9292 & curl -X GET localhost:9292 & curl -X GET localhost:9292 & curl -X GET localhost:9292 & curl -X GET localhost:9292` (where 9292 is the correct port obviously) behave as expected for you? Because it does for me.

**Comment by alanhala** [comment]
@nateberkopec Yes, it works as I expect. It handles the 5 request simultaneously. I think it's a Chrome issue. I've just checked in Safari and it works the same way as curl.

In my opinion, for some reason, Chrome is not sending all the requests simultaneously when they are all completely identical. Maybe it could be a Chrome's bug.
