### ISSUE TITLE
Exception handling for `on_worker_boot`

### ISSUE THREAD

**Issue by austinthecoder** [puma/puma#1551]
When an exception is raised in `on_worker_boot`, it will retry ad infinitum. I suppose there are situations when this is a good thing. E.g., a db instance is rebooting and a connection can't be made for a few seconds.

What's the best way to handle exceptions that should halt the server? How _do_ you actually halt the server in this case?

```
on_worker_boot do
  raise 'error'
end
```

I'm sorry if this is not the place for this question. I couldn't find a general discussion board.

**Comment by nateberkopec** [comment]
I've thought about this and I think this is actually a Bad Thing. If any hook (e.g. anything run by run_hooks) raises an exception we should rescue it, log and notify that the hook was not run successfully. Essentially run_hooks should just rescue and log everything.
