### ISSUE TITLE
leak_stack_on_error should be true in test environment as well

### ISSUE THREAD

**Issue by swrobel** [puma/puma#1554]
It seems that Puma is configured to only `leak_stack_on_error` [in development environment](https://github.com/puma/puma/blob/v3.11.3/lib/puma/runner.rb#L169), but I believe it should in test as well. I can submit a PR to change, but wanted to discuss the rationale here first.

### Steps to reproduce

1) Use puma in test mode (ie: rails system tests) and raise an exception

### Expected behavior

Puma should return the entire exception backtrace, like it does in the development environment

### Actual behavior

Puma returns "An unhandled lowlevel error occurred. The application logs may have details."

### System configuration

**Ruby version**: 2.5.1
**Rails version**: 5.2.0.rc2
**Puma version**: 3.11.3

**Comment by schneems** [comment]
I’m fine with this.
