### ISSUE TITLE
Long running db transaction causes Puma to stop handling requests

### ISSUE THREAD

**Issue by chadwilken** [puma/puma#1556]
### Steps to reproduce

1) Create a `ActiveRecord::Base.transaction` that has a very long running (10 min +) set of work. In our case, we created a temporary table in the transaction to load some data and backfill a table.

2) While this is running have requests flowing in. We have 8 worker processes per instance and receive several hundred requests per minute.

3) If you watch puma in htop you will see after a few minutes that the CPU usage falls to 0 and nginx says that the connection to the socket is refused.

### Expected behavior
I didn't expect a long running db transaction to prevent Puma from handling requests.

### Actual behavior
After a few minutes of the transaction running Puma stops handling requests. Nothing is output in the error log for puma either.

### System configuration

**Ruby version**: 2.5.0
**Rails version**: 5.1.4
**Puma version**: 3.11.3

Nginx Log Entry
```
2018/04/05 15:33:42 [error] 21971#21971: *104650 connect() to unix:///home/deploy/apps/production/shared/tmp/sockets/puma.sock failed (111: Connection refused) while connecting to upstream, client: 172.31.9.64, server: {hostname}, request: "GET /v2/projects/20531745 HTTP/1.1", upstream: "http://unix:///home/deploy/apps/production/shared/tmp/sockets/puma.sock:/500.html", host: "{hostname}"
```

**Comment by stereobooster** [comment]
Do you have small reproducible example?

**Comment by chadwilken** [comment]
@stereobooster I could probably reproduce it if I make an example Rails app and share the repo. Would that be sufficient?

**Comment by stereobooster** [comment]
Yes sure

**Comment by chadwilken** [comment]
I tried replicating locally and was unable to do so, not sure what the issue was but I guess we can close for now.
