### ISSUE TITLE
Errno::EINVAL when SSL is enabled and Firefox does not trust self-signed cert

### ISSUE THREAD

**Issue by perlun** [puma/puma#1564]
### Steps to reproduce

1) Use a self-signed certificate with Puma.
2) Browse to the https://localhost:12345 port.
3) Firefox will show a security warning, asking you to add an exception.

### Expected behavior

The request should be processed without errors.

### Actual behavior

```
Error in reactor loop escaped: Invalid argument - getpeername(2) (Errno::EINVAL)
/Users/plundberg/.rvm/gems/ruby-2.5.1/gems/puma-3.11.3/lib/puma/minissl.rb:155:in `peeraddr'
/Users/plundberg/.rvm/gems/ruby-2.5.1/gems/puma-3.11.3/lib/puma/minissl.rb:155:in `peeraddr'
/Users/plundberg/.rvm/gems/ruby-2.5.1/gems/puma-3.11.3/lib/puma/reactor.rb:93:in `rescue in block in run_internal'
/Users/plundberg/.rvm/gems/ruby-2.5.1/gems/puma-3.11.3/lib/puma/reactor.rb:73:in `block in run_internal'
/Users/plundberg/.rvm/gems/ruby-2.5.1/gems/puma-3.11.3/lib/puma/reactor.rb:43:in `each'
/Users/plundberg/.rvm/gems/ruby-2.5.1/gems/puma-3.11.3/lib/puma/reactor.rb:43:in `run_internal'
/Users/plundberg/.rvm/gems/ruby-2.5.1/gems/puma-3.11.3/lib/puma/reactor.rb:154:in `block in run_in_thread'
```

This is mostly a minor annoyance; after adding the exception it seems to work fine.

### System configuration

**Ruby version**: 2.5.1
**Rails version**: N/A
**Puma version**: 3.11.3

**Comment by sevenseacat** [comment]
I added the security exception in Firefox and I'm still seeing the error in my logs.

Ruby version: 2.5.1
Rails version: 5.1
Puma version: 3.12.0

**Comment by sevenseacat** [comment]
False alarm - there were a few other domains I needed to add security exceptions for as well!
