### ISSUE TITLE
Puma still has very bad SSL issues in OSX

### ISSUE THREAD

**Issue by vincentwoo** [puma/puma#1584]
Still seeing strange hanging requests all the time on Puma, even on latest. The SSL support in Puma feels very rough. Is there a comprehensive plan to address?

Here's an error I got just now after Puma failed to pass the request to Rails for 30 seconds or so:

```
19:20:22 web.1     | Error in select: closed stream (IOError)
19:20:22 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.4/lib/puma/reactor.rb:29:in `select'
19:20:22 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.4/lib/puma/reactor.rb:29:in `run_internal'
19:20:22 web.1     | /Users/vwoo/.gem/ruby/2.5.0/gems/puma-3.11.4/lib/puma/reactor.rb:154:in `block in run_in_thread'
```

### System configuration

**Ruby version**: 2.5
**Rails version**: 5.x
**Puma version**: 3.11.4

**Comment by wyattbenno777** [comment]
Have this exact same issue in Ubuntu with Puma 3.11.4 using ssl. 
Works fine on my mac with a fake ssl certificate. Does not work on production with a real one.

`Error in select: closed stream (IOError)
/usr/share/rvm/gems/ruby-2.3.3@rails-devise/gems/puma-3.11.4/lib/puma/reactor.rb:29:in `select'
/usr/share/rvm/gems/ruby-2.3.3@rails-devise/gems/puma-3.11.4/lib/puma/reactor.rb:29:in `run_internal'
/usr/share/rvm/gems/ruby-2.3.3@rails-devise/gems/puma-3.11.4/lib/puma/reactor.rb:154:in `block in run_in_thread'`

**Comment by wyattbenno777** [comment]
I ended up using NGINX on prod for https. Works very fast with Puma.

**Comment by baibinja** [comment]
+1 After the test is successfully ended, appears error. Usually only last 4 lines.

`Error in reactor loop escaped: closed stream (IOError)`
`org/jruby/RubyIO.java:3064:in 'read'`
`org/jruby/RubyIO.java:3046:in 'read'`
`C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/puma-3.12.0-java/lib/puma/reactor.rb:143:in 'block in run_internal'`
`org/jruby/ext/thread/Mutex.java:159:in 'synchronize'`
`C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/puma-3.12.0-java/lib/puma/reactor.rb:142:in 'block in run_internal'`
`org/jruby/RubyArray.java:1792:in 'each'`
`C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/puma-3.12.0-java/lib/puma/reactor.rb:140:in 'run_internal'`
`C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/puma-3.12.0-java/lib/puma/reactor.rb:251:in 'block in run_in_thread'`
`Error in select: closed stream (IOError)`
`org/jruby/RubyIO.java:3549:in 'select'`
`C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/puma-3.12.0-java/lib/puma/reactor.rb:126:in 'run_internal'`
`C:/jruby-9.2.5.0/lib/ruby/gems/shared/gems/puma-3.12.0-java/lib/puma/reactor.rb:251:in 'block in run_in_thread'`

JRuby version - 9.2.5.0
Puma version - 3.12.0
Windows 10

**Comment by nateberkopec** [comment]
This will be a tough one to repro. I've added an example Dockerfile to the repository if someone wants to get started on it.

I would also encourage anyone seeing `closed stream (IOError)` raised by the `select` call in reactor.rb to try Puma 4.0+, which changed the IO implementation.

**Comment by nateberkopec** [comment]
Closing. If you can create a reproducible example, please open a new issue.
