### ISSUE TITLE
why local variables in threads?

### ISSUE THREAD

**Issue by jjb** [puma/puma#1586]
Why are these local variables created?

https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb#L86-L90

Thanks!

**Comment by alexdowad** [comment]
It's a performance optimization.

Look at `git blame` on that file. (https://github.com/puma/puma/blame/master/lib/puma/thread_pool.rb) You can see some commits with commit message: "Add missing localvars. **Accessing localvars is faster than accessing ivars.**"
