### ISSUE TITLE
use # frozen_string_literal: true

### ISSUE THREAD

**Issue by jjb** [puma/puma#1587]
Has the project considered adding `# frozen_string_literal: true` to all source files? AFAIK this has possibly significant benefits with no drawbacks.

**Comment by schneems** [comment]
If you can send a PR that passes the test I see no reason not to use it.

> AFAIK this has possibly significant benefits with no drawbacks.

I've done memory benchmarking with derailed benchmarks and never found a hotspot inside of puma. That being said, every little bit helps as long as it doesn't cause significant pain or errors, i'm for it 👍.

**Comment by jjb** [comment]
done in #1649 🎉
