### ISSUE TITLE
Thread work needs to be inside mutex?

### ISSUE THREAD

**Issue by jjb** [puma/puma#1588]
Looks like the thread doing its work is inside the mutex which figures out if there is work to do

https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb#L128-L132

Could this instead go directly after the close of the mutex block?

I'm guessing i'm missing something, because otherwise this would be a huge performance problem that someone would have noticed.

**Comment by nateberkopec** [comment]
I'm not sure what this is referring to, and the link is now broken.
