### ISSUE TITLE
SEG FAULTS not logged in log file

### ISSUE THREAD

**Issue by aaronbartell** [puma/puma#1594]
We recently migrated a Sinatra application from using Thin to Puma.  We sometimes get SEG FAULTS in the app and Thin would give us the full log of the SEG FAULT.  

With  Puma we can tell in the logs where the SEG FAULT occurs because we can see `=== puma startup...` but we don't see the full stack trace like we did with Thin.  We currently have the following in `config/puma.rb`:

```
stdout_redirect './stdout', './stderr', true
```

**My question:** Should Puma be logging SEG FAULTS and isn't?  If it should, are there other settings I can alter?

### System configuration

**Ruby version**: 2.1.0
**Rails version**: Using Sinatra
**Puma version**: 3.3.0
**Operating system:** IBM i

**Comment by nateberkopec** [comment]
Sounds like you're not reading stderr?
