### ISSUE TITLE
SSL infinite loop upon client close

### ISSUE THREAD

**Issue by mirelon** [puma/puma#1596]
I have a Rails application with Puma and SSL. It runs well, but after some time (minutes, sometimes hours) it begins to use 100% CPU. I tried to analyze it with gdb:

```
sudo gdb `which ruby` 20697
```
And there I typed `call rb_backtrace()`. The server logs now contains:

```
.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:282:in `block in run'
.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:303:in `rescue in block in run'
.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.11.4/lib/puma/client.rb:112:in `close'
.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.11.4/lib/puma/minissl.rb:144:in `close'
.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.11.4/lib/puma/minissl.rb:126:in `read_and_drop'
.rvm/rubies/ruby-2.4.1/lib/ruby/gems/2.4.0/gems/puma-3.11.4/lib/puma/minissl.rb:126:in `select'
```

Without SSL the issue don't happen. I think the issue is the infinite loop in `minissl.rb`:

(I think either IO.select returns correctly or raises Errno::EAGAIN all the time)

```
def read_and_drop(timeout = 1)
  return :timeout unless IO.select([@socket], nil, nil, timeout)
  read_nonblock(1024)
  :drop
rescue Errno::EAGAIN
  # do nothing
  :eagain
end

def should_drop_bytes?
  @engine.init? || !@engine.shutdown
end

def close
  begin
    # Read any drop any partially initialized sockets and any received bytes during shutdown.
    # Don't let this socket hold this loop forever.
    # If it can't send more packets within 1s, then give up.
    while should_drop_bytes?
      return if read_and_drop(1) == :timeout
    end
  rescue IOError, SystemCallError
    Thread.current.purge_interrupt_queue if Thread.current.respond_to? :purge_interrupt_queue
    # nothing
  ensure
    @socket.close
  end
end
```

ruby version 2.4.1
rails version 5.2.0
puma version 3.11.4

**Comment by sayuridt** [comment]
Hello, 

I'm suffering the same problem, I have two Ruby on Rails applications that communicate with each other by https and it seems that after a while they are left hanging in the minssl.rb and CPU goes to 100%


Ruby Backtrace(s):
	from /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:154:in `block in run_in_thread'
	from /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:124:in `run_internal'
	from /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:124:in `synchronize'
	from /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:130:in `block in run_internal'
	from /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/client.rb:112:in `close'
	from /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:144:in `close'
	from /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:127:in `read_and_drop'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:56: [BUG] Segmentation fault at 0x0000000000a027
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0010 p:---- s:0042 e:000041 CFUNC  :read_nonblock
c:0009 p:0049 s:0037 e:000036 METHOD /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:56
c:0008 p:0041 s:0029 e:000028 METHOD /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:127
c:0007 p:0020 s:0025 e:000024 METHOD /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:144
c:0006 p:0011 s:0022 e:000021 METHOD /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/client.rb:112
c:0005 p:0051 s:0019 e:000018 BLOCK  /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:130 [FINISH]
c:0004 p:---- s:0015 e:000014 CFUNC  :synchronize
c:0003 p:0079 s:0012 e:000011 METHOD /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:124
c:0002 p:0009 s:0005 e:000004 BLOCK  /opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:154 [FINISH]
c:0001 p:---- s:0002 e:000001 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:154:in `block in run_in_thread'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:124:in `run_internal'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:124:in `synchronize'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/reactor.rb:130:in `block in run_internal'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/client.rb:112:in `close'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:144:in `close'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:127:in `read_and_drop'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:56:in `read_nonblock'
/opt/www/front.esios.com/releases/11/vendor/bundle/ruby/2.1.0/gems/puma-3.11.4/lib/puma/minissl.rb:56:in `read_nonblock'

-- C level backtrace information -------------------------------------------
puma: cluster worker 1: 16948 [11](+0x1867fc) [0x7f793b7df7fc]
puma: cluster worker 1: 16948 [11](+0x1f8103) [0x7f793b851103]
puma: cluster worker 1: 16948 [11](rb_bug+0xb3) [0x7f793b8522e3]
puma: cluster worker 1: 16948 [11](+0xfc51e) [0x7f793b75551e]
/lib64/libpthread.so.0(+0xf370) [0x7f793b22a370]
puma: cluster worker 1: 16948 [11](+0x154ced) [0x7f793b7adced]
puma: cluster worker 1: 16948 [11](+0x154e20) [0x7f793b7ade20]
puma: cluster worker 1: 16948 [11](rb_iseq_compile_node+0xa54) [0x7f793b7bc9a4]
puma: cluster worker 1: 16948 [11](rb_iseq_new_with_opt+0xe3) [0x7f793b7c1c13]
puma: cluster worker 1: 16948 [11](+0x15a370) [0x7f793b7b3370]
puma: cluster worker 1: 16948 [11](rb_iseq_compile_node+0xa54) [0x7f793b7bc9a4]
puma: cluster worker 1: 16948 [11](+0x167193) [0x7f793b7c0193]
puma: cluster worker 1: 16948 [11](rb_iseq_compile_with_option+0x19a) [0x7f793b7c283a]
puma: cluster worker 1: 16948 [11](+0x178943) [0x7f793b7d1943]
puma: cluster worker 1: 16948 [11](rb_protect+0x195) [0x7f793b67fa85]
[0x7ffd0e1a3c4f]


O.S.: Red Hat 7.3
ruby version 2.1.2p95 (2014-05-08 revision 45877)
rails version 4.1.8
puma version 3.11.4

**Comment by BlackNightFury** [comment]
I am facing the same problem. Is anyone here to solve this problem?

**Comment by timkrins** [comment]
There was a SSL fix in 3.12.0 - maybe give that a try

**Comment by mirelon** [comment]
Seems like fixed - probably IO.select was returning :eof all the time.

**Comment by jainankita90** [comment]
I am getting same issue
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/reactor.rb:154:in `block in run_in_thread'
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/reactor.rb:124:in `run_internal'
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/reactor.rb:124:in `synchronize'
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/reactor.rb:130:in `block in run_internal'
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/client.rb:112:in `close'
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/minissl.rb:144:in `close'
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/minissl.rb:126:in `read_and_drop'
	from /usr/local/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.11.4/lib/puma/minissl.rb:56:in `read_nonblock'

**Comment by BlackNightFury** [comment]
@jainankita90 Can you try with the new version? I think it will fix your issue. Try with 3.12.0

**Comment by jainankita90** [comment]
@BlackNightFury  Thanks.
I upgraded to puma 3.12.0, it worked like charm.
But sometimes, server response is too slow.
