### ISSUE TITLE
Trouble with puma.sock file

### ISSUE THREAD

**Issue by oniofchaos** [puma/puma#1597]
### Steps to reproduce

This happens when we run our Ansible deploy script or when we reboot the AWS EC2 instances we are hosting on.

Unfortunately it's unclear how the problem is happening or how to reproduce it other than "deploy code". I'm hoping to find that out as part of this issue. Any help is appreciated - if I can provide extra info let me know.

### Expected behavior

After a deploy/reboot/etc, puma continues to respond to requests.

### Actual behavior

The following error happens and we have to remove the `puma.sock` and `puma.pid` files and re-launch puma.

```
2018/06/18 13:28:34 [crit] 997#997: *993 connect() to unix:/tmp/puma.sock failed (2: No such file or directory) while connecting to upstream, client: $IP, server: $SITE request: "GET #LOGIN HTTP/1.1", upstream: "http://unix:/tmp/puma.sock:/$LOGIN", host: "$SITE" 
```

### System configuration

**Ruby version**: 2.5.0
**Rails version**: 5.2.0
**Puma version**: 3.11.4

Note that we have puma behind NGINX.

**Comment by ernestojpg** [comment]
When you restart Puma, have you checked that the file ```/tmp/puma.sock``` is created?

**Comment by oniofchaos** [comment]
It is, the problem is that the PID doesn't match with the PID of the new process

**Comment by Abbas** [comment]
tes saja lah
htlm code
<a href="http://www.undangancinta.com">undangan pernikahan</a>
<a href="http://www.undangancinta.com">undangan pernikahan unik</a>
<a href="http://www.undangancinta.com">undangan pernikahan unik</a>


ini cuma pake ling
http://www.undangancinta.com

bb code 
[url=http://www.undangancinta.com]undangan pernikahan[/url]
[url=http://www.undangancinta.com]undangan pernikahan simple[/url]
[url=http://www.undangancinta.com]undangan pernikahan unik[/url]

᯸ҀĬ
