### ISSUE TITLE
Puma doesn't respect to config `bind` if params '-b' or '-p' specified

### ISSUE THREAD

**Issue by mbaev** [puma/puma#1602]
### Steps to reproduce

1) Write the next part of config into `config/puma.rb` of rails app.
```ruby
bind "unix://#{shared_dir}/sockets/puma.sock"
```
This is usual place for socket, that offers Capistrano.
2) Start the server with defaults `rails s` and see logs
```
$ rails s
=> Booting Puma
=> Rails 5.0.7 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 1, max threads: 3
* Environment: development
* Listening on tcp://0.0.0.0:3000
* Listening on unix:///var/www/my-app/shared/sockets/puma.sock
* Starting control server on unix:///tmp/puma-status-1529779450781-30275
Use Ctrl-C to stop
```
3) Then just Ctrl+C and start again with specified args `-b` or `-p`, or both of they (as it does RubyMine)
```
$ rails s -b 0.0.0.0 -p 3000
=> Booting Puma
=> Rails 5.0.7 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 1, max threads: 3
* Environment: development
* Listening on tcp://0.0.0.0:3000
* Starting control server on unix:///tmp/puma-status-1529779583499-30520
Use Ctrl-C to stop
```
and required Listener will not be created.

### Expected behavior
Regardless of arguments in time of starting a server, I expect that the Puma will start listeners that are specified in config file. If this is impossible then, maybe, need to add ability to specify listeners separately.

### Actual behavior
Instead of this, listeners with necessary socket doesn't created.

### System configuration
**Ruby version**:  ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
**Rails version**: Rails 5.0.7
**Puma version**: 3.11.4

My `config/puma.rb`
```ruby
min_threads = ENV.fetch("MIN_THREADS") { 1 }.to_i
max_threads = ENV.fetch("MAX_THREADS") { 6 }.to_i
app_dir     = File.expand_path("../..", __FILE__)
shared_dir  = "#{app_dir}/shared"


threads         min_threads, max_threads
port            ENV.fetch("PORT") { 3000 }
environment     ENV.fetch("RAILS_ENV") { "development" }
bind            "unix://#{shared_dir}/sockets/puma.sock"
pidfile         "#{shared_dir}/pids/puma.pid"
state_path      "#{shared_dir}/pids/puma.state"
stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true
activate_control_app


plugin :tmp_restart
```

**Comment by timkrins** [comment]
I would actually _expect_ Puma to operate this way - as the `-b` flag to the Rails server specifies what address to bind to.

It's not really a Puma issue in any case - you want to bring it up with Rails if you think it should be different (but I have a feeling many people would not agree with you)
