### ISSUE TITLE
test suite hangs against openssl 1.1.1-pre8

### ISSUE THREAD

**Issue by sebastianas** [puma/puma#1609]
### Steps to reproduce

1) install openssl 1.1.1-pre8. Available in debian experimantal.

2) build  debian puma package against the openssl version

3) run the puma test suite

### Expected behavior

test suite passes

### Actual behavior

test suite hangs. [full log](https://breakpoint.cc/openssl-rebuild/2018-07-06-rebuild-openssl1.1.1-pre8/attempted/puma_3.11.3-1_amd64-2018-07-05T21%3A24%3A41Z).
There was discussion in https://github.com/openssl/openssl/issues/6228 regarding the SSL_ERROR_WANT_READ, SSL_ERROR_WANT_WRITE error during a read operation which triggers now with TLS1.3. I expected this was the cause for the failure and AUTO_RETRY would fix this but it is not the case. Can you take a look and figure out is wrong?

### System configuration

**Ruby version**: 2.5.1
**Rails version**: no idea. The build log should reveal it
**Puma version**: 3.11.3

**Comment by MSP-Greg** [comment]
@sebastianas

I'm running trunk with 1.1.1 and also built puma with it (windows).

Your test froze, my test run had the following four tests as errors with `Errno::EADDRINUSE: Only one usage of each socket address (protocol/network address/port) is normally permitted. - bind(2) for "127.0.0.1" port 3212`.  Might you be able to see if you have the same issue with the other three tests?

Ruby's OpenSSL may have an issue also.  WIP.

```
TestPumaServerSSLClient#test_verify_fail_if_client_expired_cert
TestPumaServerSSLClient#test_verify_client_cert
TestPumaServerSSLClient#test_verify_fail_if_no_client_cert
TestPumaServerSSLClient#test_verify_fail_if_client_unknown_ca
```

**Comment by MSP-Greg** [comment]
I've been testing 1.1.1 on both Ruby OpenSSL & Puma.

If I force all connections to use TLSv1.2, all tests pass in Puma and the Ruby OpenSSL tests.

In Puma, if I leave connections able to use TLSv1.3, and account for a possible issue with net/http, all tests also pass.

**Comment by sebastianas** [comment]
I can't tell if this is the same. I can rerun the test and give you parts of the build folder or run it with the arguments you tell me to use.
The net/http part is probably the TLS1.3 thing. Besides the autorety that should be part of pre8 there is also https://github.com/openssl/openssl/pull/6340 which might help. I didn't have time to retry this yet, and I will be offline for the next month, just that you know.

**Comment by MSP-Greg** [comment]
@sebastianas

Being a windows type, I'm not sure about what happens with your setup.  Is Ruby using the same OpenSSL version as Puma?  Also, Ruby built with the same version?

Generally with windows, the suggestion is that everything using OpenSSL (digest, ruby openssl, eventmachine, puma, etc) should be built with the same OpenSSL package.

FWIW, using `ruby 2.6.0dev (2018-08-09 trunk 64237) [x64-mingw32]` built with an OpenSSL 1.1.1 package built from OpenSSL master, and using Puma built with the same, all Puma tests pass as is.

**Comment by voxik** [comment]
For me, the situation was improved by 6a7112d51b3de3439c4be512f68a8d4e33e02665

**Comment by nateberkopec** [comment]
Adding as bug, should be pretty easy to create a reproducing Dockerfile.

**Comment by sebastianas** [comment]
I think this can be closed.  3.12 got uploaded to Debian including commit 6a7112d and this passes the testsuite against OpenSSL 1.1.1
