### ISSUE TITLE
Puma server WEB_CONCURRENCY not working

### ISSUE THREAD

**Issue by mayur-techcompose** [puma/puma#1610]
Hello guys puma server web_concurrency not working.
I fetch issue when generate pdf and send to email but some how in production mode it's working fine but in development mode is not working.

Please help me to resolve this issue

**Ruby version**: 2.3.3-p222
**Rails version**: 4.2.9
**Puma version**:  3.11.4

**Comment by hakusaro** [comment]
Hi there. Though this question is really old, you need to verify that you're actually referencing the `WEB_CONCURRENCY` environment variable when starting puma and allocating workers. If you're using rails, posting your `puma.rb`/puma config file would be great help.

If this issue isn't relevant anymore, though, please everyone know so the backlog can be cleaned up.

**Comment by Manifold0** [comment]
I'm having the same issue in 
Rails 5.2.1
Ruby 2.5.3
Puma 3.12.0

Whenever the worker count is greater than 1 there's a seg fault error.

puma.rb
```
threads 0, 1
workers 3
preload_app!
port ENV.fetch("PORT") { 3000 }

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ApplicationRecord.establish_connection
  end
end
```
