### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by naveenanilabs** [puma/puma#1633]
### Steps to reproduce
rails version 5.0.7
ruby version 2.5.1
puma version 3.12

i am running puma without nginx behind elastic load balancer.

### Expected behavior
Is it possible to run puma without nginx in production with actioncable.
puma should run without nginx.
### Actual behavior
All working fine but actioncable not working.

**Comment by nateberkopec** [comment]
Yes, it is possible.
