### ISSUE TITLE
Puma in forking mode fails to restart: pumactl and systemd clash?

### ISSUE THREAD

**Issue by Onumis** [puma/puma#1634]
### Steps to reproduce

1) Setup puma and systemd on a ubuntu 18.04 machine:

puma config: 
```
#!/usr/bin/env puma

directory '/home/ubuntu/app/current'
rackup "/home/ubuntu/app/current/config.ru"
environment 'production'

tag ''

pidfile "/home/ubuntu/app/shared/tmp/pids/puma.pid"
state_path "/home/ubuntu/app/shared/tmp/pids/puma.state"
stdout_redirect '/home/ubuntu/app/shared/log/puma_access.log', '/home/ubuntu/app/shared/log/puma_error.log', true

threads 0,16

bind 'unix:///home/ubuntu/app/shared/tmp/sockets/puma.sock'

workers 0

prune_bundler

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = ""
end
```

```
# /etc/systemd/system/puma.service

[Unit]
Description=Puma HTTP Forking Server
After=network.target
Requires=puma.socket

[Service]
Type=forking

User=ubuntu
Group=ubuntu

WorkingDirectory=/home/ubuntu/app/current

ExecStart=/home/ubuntu/.rvm/bin/rvm default do bundle exec puma -C /home/ubuntu/app/shared/puma.rb --daemon

ExecStop=/home/ubuntu/.rvm/bin/rvm default do bundle exec pumactl -S /home/ubuntu/app/shared/tmp/pids/puma.state -F /home/ubuntu/app/shared/puma.rb stop

PIDFile=/home/ubuntu/app/shared/tmp/pids/puma.pid

Restart=no

[Install]
WantedBy=multi-user.target
```

```
# /etc/systemd/system/puma.socket

[Unit]
Description=Puma HTTP Server Accept Sockets

[Socket]
ListenStream=0.0.0.0:9292
ListenStream=0.0.0.0:9293

NoDelay=true
ReusePort=true
Backlog=1024

[Install]
WantedBy=sockets.target

```

2) Enable: `systemctl enable puma` and restart the machine

3) Notice that puma is running :tada:

4) Issue a restart command from `pumactl` (either manually or using capistrano):
`~/.rvm/bin/rvm default do bundle exec pumactl -S /home/ubuntu/app/shared/tmp/pids/puma.state -F /home/ubuntu/app/shared/puma.rb restart`

5) puma crash

### Expected behavior

Pumactl and systemd should go along like good old pals.

### Actual behavior

The pid file gets into a state that cannot recover:
pumactl says nothing, but issuing a `pumactl start` afterwards works (puma starts)

systemd says:

> puma.service: New main PID 7267 does not belong to service, and PID file is not owned by root. Refusing.

and does not start puma.

**why is this a problem?** Because when using capistrano for deployments or w/e, this can cause puma.service to be on an irregular "state" - have to reboot instance in order to systemd to recover.

### System configuration

**Ruby version**: 2.5
**Rails version**: 5.2
**Puma version**: 3.12.0

on a ubuntu 18.04 instance, configured with nginx.

**Comment by oLeVanNghia** [comment]
```
ExecStart=/home/ubuntu/.rvm/bin/rvm default do bundle exec puma -C /home/ubuntu/app/shared/puma.rb --daemon
```
how about if remove option "--daemon" in abow command?

**Comment by dekellum** [comment]
There may be other configuration issues, but the forking systemd setup is not compatible with socket activation, see https://github.com/puma/puma/blob/master/docs/systemd.md (emphasis mine):

> ## Alternative Forking Configuration
> Other systems/tools might expect or need puma to be run as a "traditional" forking server, for example so that the pumactl command can be used directly and outside of systemd for stop/start/restart. **This use case is incompatible with systemd socket activation, so it should not be configured.**

**Comment by jetsgit** [comment]
Is the information in [systemd documentation](https://github.com/puma/puma/blob/master/docs/systemd.md) relevant?

It advocates using the flag

```--keep-file-descriptors```

with bundle exec in order to not close sockets prematurely.


>Note: Any wrapper scripts which exec, or other indirections in ExecStart, may result in activated socket file descriptors being closed before they reach the puma master process. For example, if using bundle exec, pass the --keep-file-descriptors flag. bundle exec can be avoided by using a puma executable generated by bundle binstubs puma. This is tracked in [#1499].
