### ISSUE TITLE
Run puma from specified user/group

### ISSUE THREAD

**Issue by csandanov** [puma/puma#1639]
Hi, I haven't found user/group configuration in the example config file. Normally HTTP servers run as a non-root user different from the codebase owner, it's especially important for production. Recommendations to specify user/group in systemd will not suffice because sometimes you just don't have any init system like in case of containers.

I wonder what is your recommendation on this matter? Thank you.

**Comment by dekellum** [comment]
Assuming you want this to use a low port number like 80, which would otherwise require starting as root, one alternative is to use (Linux) OS port forwarding, for example 80 to 8080, and then puma can be run as unprivileged user, listening on port 8080.

**Comment by csandanov** [comment]
I didn't say I wanted to run it on port 80. I just want to specify under which user I want to run puma, e.g. in a docker container I have a default non-root user (codebase owner) but I don't want to run the web server under this user because I don't want it to have writing access.

**Comment by nateberkopec** [comment]
Closing as stale. Deployment docs non-specific to Puma are also a bit out of scope for us.
