### ISSUE TITLE
Early hints + javascript_include_tag = Puma:ConnectionError

### ISSUE THREAD

**Issue by pjforde1978** [puma/puma#1640]
### Steps to reproduce

1) Procfile enables early hints eg. web: bundle exec puma -C config/puma.rb --early-hints

2) Make use of `javascript_include_tag` helper

3) Production environment on Heroku

### Expected behavior

Testing out --early-hints on Heroku, I would expect the hints to be generated as described in [Implement H2 Early Hints for Rails](https://github.com/rails/rails/pull/30744).

### Actual behavior

I'm seeing some intermittent socket timeout errors when I have --early-hints enabled on my app, which is hosted on Heroku. It's only showing up about once a day, and only in production.

Some lucky visitor's request is throwing one Puma:ConnectionError for each `javascript_include_tag` in my application layout. If one call fails, they all fail in the order they appear in the template. I've never experienced the end-result personally, leading me to guess that the visitor probably won't notice as their script tags would just load normally.

```Aug 16 12:34:37 #<Puma::ConnectionError: Socket timeout writing data> 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:972:in 'rescue in fast_write' 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:963:in 'fast_write' 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/puma-3.11.4/lib/puma/server.rb:609:in 'block in handle_request' 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/http/request.rb:217:in 'send_early_hints' 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/actionview-5.2.0/lib/action_view/helpers/asset_tag_helper.rb:96:in 'javascript_include_tag' 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:156:in 'block in javascript_include_tag' 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:154:in 'map' 
Aug 16 12:34:37 /app/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:154:in 'javascript_include_tag' 
Aug 16 12:34:37 /app/app/views/layouts/application.html.erb:97:in 'block in _app_views_layouts_application_html_erb__4118899528439397404_70152019751760' 
Aug 16 12:34:37 /app/app/views/layouts/application.html.erb:95:in 'each' 
Aug 16 12:34:37 /app/app/views/layouts/application.html.erb:95:in '_app_views_layouts_application_html_erb__4118899528439397404_70152019751760'
```

### System configuration

**Ruby version**: 2.4.1
**Rails version**: 5.2.0
**Puma version**: 3.11.4

**Comment by johngallagher** [comment]
I'm also seeing this error - any ideas to fix would be greatly appreciated!

**Comment by Jesus** [comment]
This error happens when the connection is lost before we're able to send any early hints.

We could have the same situation even without early hints if the connection is lost before any response headers are sent, however Puma swallows these errors which I think is fine.

A simple way to reproduce this is running this against your web server:
```ruby
require 'socket'

request = [
  "GET /buildings HTTP/1.1",
  "Host: 127.0.0.1:3000",
  "\r\n"
]

socket = TCPSocket.new '127.0.0.1', 3000
socket.puts request.join("\r\n")

# Close socket without reading anything back from the server...
socket.close
```

No error will appear in the client but the reported error will appear in the app logs.
