### ISSUE TITLE
Inconsistent default value of daemonize option

### ISSUE THREAD

**Issue by francordie** [puma/puma#1651]
I was looking for the default values of Puma options when setting the config file or using CLI commands and saw that **daemonize** option appears to be default to **true** in the [DSL daemonize method](https://github.com/puma/puma/blob/master/lib/puma/dsl.rb#L167) but **false** in both [config.rb example file](https://github.com/puma/puma/blob/master/examples/config.rb#L35) and [lib Configuration file](https://github.com/puma/puma/blob/master/lib/puma/configuration.rb#L176)

This should be consistent obviously between docs and code.

**Ruby version**: 2.5.1
**Rails version**: 5.2.1
**Puma version**: 3.12

**Comment by evanphx** [comment]
That's incorrect, nothing defaults daemonize to true. The example file is just that, an example. The method you see in the DSL makes it so that if you call `daemonize` in your configuration, it means that you do want daemonization. But it is not used unless you actually call that method.
