### ISSUE TITLE
puma server keeps crashing in production?

### ISSUE THREAD

**Issue by sanjaygir** [puma/puma#1654]
I am using puma (3.12.0) in production.

It crashes silently. When i check my app url it shows

We're sorry, but something went wrong

I dont know how long it has been down. I then redeploy using capistrano and it show the server started

`Puma starting in single mode...
      01
      01 * Version 3.12.0 (ruby 2.4.2-p198), codename: Llamas in Pajamas
      01
      01 * Min threads: 4, max threads: 16
      01
      01 * Environment: production
      01
      01 * Daemonizing...`
it happens like once a month. This has happened enough times i am compelled to post this issue. Please note that i have increased my ram size to 4gb and this problem still persists. I appreciate any guide to what is killing puma silently in production. Thanks

**Comment by evanphx** [comment]
Without any other details, there isn't much we can do here.
