### ISSUE TITLE
How are "hakiri" reports handled for this project?

### ISSUE THREAD

**Issue by nasifimtiazohi** [puma/puma#1658]
https://hakiri.io/github/puma/puma/master contains vulneraibilty report for this projects (only on commits that merges Pull Request to master I believe from the pattern).

It shows 9 warnings for a lot of recent commits.

I was wondering if these vulnerability reports from hakiri are addressed by the project maintainers?  If not, why?

**Comment by evanphx** [comment]
They are all likely in tests, not in the code base itself. I've never heard of hakiri until today.

**Comment by evanphx** [comment]
Yup, double checked and 100% of them are either rack or jruby-openssl, so nothing about puma itself.
