### ISSUE TITLE
Plugins run in_background per worker

### ISSUE THREAD

**Issue by shaqq** [puma/puma#1660]
Hi party people! Thanks for all the work in puma!

I'm curious if we'd consider allowing Plugins to have a `in_worker_background`-esque method that'd allow plugins to run a background function per worker.

If there's a more formal way to present this, let me know! I'd be happy to write up an RFC or something.

### But... why would you want to do this?

I'm exploring avenues to doing runtime ENV updates, where the ENV vars are stored in something like [consul](https://www.consul.io/) or [etcd](https://coreos.com/etcd/). This is incredibly helpful for teams that want to easily tweak settings in production without having to shell into a box and run a console. Use cases include changing the log level, feature flags, and probably a host of other things if there's a crisis going on and you need to change something quickly.

Runtime env updates (or runtime config updates) have existed in other language platforms for a while, and I'm hoping to bring it to Ruby apps. The benefit could be especially high for large, monolith Ruby apps where updating an ENV var and restarting can take 15-20 minutes.

Anywho, let me know if this is reasonable or just another wacky idea. Thanks!

**Comment by evanphx** [comment]
You can implement this yourself pretty easily by just starting a thread in the `after_fork` block.

**Comment by shaqq** [comment]
@evanphx I ended up starting a thread in `on_worker_boot`:

https://github.com/shaqq/puma-runtime_env/blob/50d452f8af496137818e6a23163ed8eded66a4b2/lib/puma/plugin/runtime_env.rb#L37

I was mainly curious if something like this should be handled as a first class API.... but if people aren't asking for it, then it's probably not worth it. Just figured I'd ask!

Thanks!
