### ISSUE TITLE
Ability to configure max header size?

### ISSUE THREAD

**Issue by ccarterc** [puma/puma#1661]
### Steps to reproduce

1) Send a header of length: 16kb.

### Expected behavior

We should be able to increase this limit via configuration.

### Actual behavior

Returns 400

### System configuration

**Ruby version**: 2.3.1p112
**Rails version**: 5.0.0.1
**Puma version**: 3.6.0

**Comment by evanphx** [comment]
You can implement this with a middleware, puma will not do it itself.
