### ISSUE TITLE
Non preload worker boot failure infinite loop

### ISSUE THREAD

**Issue by stefansedich** [puma/puma#1663]
When running in clustered mode without preloading and if my worker fails to boot (unable to connect to database in this example) it will forever create a new worker and never fail, ideally I would like to be able to say to terminate if a worker fails to boot in the same way that the entire process will terminate if I were using preloading.

Becomes an issue as in my case it sat there spamming my logs without ever terminating, when running with preload or without clustrering obviously it just terminates the entire process right away, is it possible to achieve what I need at the moment?

**Comment by stefansedich** [comment]
Having a play around with this, I experimented by adding a new `max_worker_terminations` configuration parameter which can control the number of worker terminations we accept before we want to nuke the entire process.

Any feedback or thoughts would be appreciated and I can wrap it up into a PR if everyone agrees this would be valuable.

**Comment by evanphx** [comment]
Unsure what a better way to handle this is. The point of the cluster mode is that the workers are restarted because they might have crashed.
