### ISSUE TITLE
warning: CRLF will be replaced by LF in docs/images/puma-connection-flow-no-reactor.png.

### ISSUE THREAD

**Issue by graywolf-at-work** [puma/puma#1672]
### Steps to reproduce

1) git clone https://github.com/puma/puma

2) cd puma

### Expected behavior

No errors.

### Actual behavior

```
warning: CRLF will be replaced by LF in docs/images/puma-connection-flow-no-reactor.png.
The file will have its original line endings in your working directory
```

### System configuration

**Ruby version**: N/A
**Rails version**: N/A
**Puma version**: master

**Comment by mdkent** [comment]
Seeing this on git version 1.9.1 (linux) and git version 2.17.2 (Apple Git-113) (osx). 

Seems worse here, git is actually modifying the files and preventing me from working in the repo.
