### ISSUE TITLE
phased-restart keeps serving old assets

### ISSUE THREAD

**Issue by roulili** [puma/puma#1680]
Hi,

I think there's something wrong with my config. I want to deploy new code, along with newly compiled assets to my production server with phased-restart to avoid downtime.

However, if the new code in controllers or models or views is correctly taken into account, the server keeps serving the old version of precompiled assets. Any idea how I can start serving the new assets ?
If I do a full restart then it works, but I have downtime...

Full description of the problem was submited here: https://stackoverflow.com/questions/53501825/puma-phased-restart-serving-old-assets

Any help appreciated!

Rouli

**Comment by nateberkopec** [comment]
StackOverflow is the correct venue for this question.
