### ISSUE TITLE
gc-stats returns invalid json

### ISSUE THREAD

**Issue by jdsundberg** [puma/puma#1687]
### Steps to reproduce

1) puma --control-url 'tcp://127.0.0.1:9293' --control-token foo
2) curl http://localhost:9293/gc-stats?token=foo

Issue is ... 
lib/puma/app/status.rb
line 63        json = "{" + GC.stat.map { |k, v| "\"#{k}\": #{v}" }.join(",") + "}"
That is not a valid JSON builder ... especially when v is a complex object.
A better approach for line 63
require 'json'
json = GC.stat.to_json

But ... that is a require 'json' / etc... 
So ... I didn't know if you would like my solution or not.

### Expected behavior
{"count":7,"time":93,"committed":437256192.0,"init":295698432.0,"max":4294967292.0,"used":318792416.0,"peak_committed":599785472.0,"peak_init":295698432.0,"peak_max":4294967292.0,"peak_used":318792416.0,"last_committed":337641472.0,"last_init":295698432.0,"last_max":4294967292.0,"last_used":27262976.0,"G1 Young Generation":{"count":7,"time":93,"pools":{"G1 Survivor Space":{"committed":13631488,"init":0,"max":-1,"used":13631488,"peak_committed":13631488,"peak_init":0,"peak_max":-1,"peak_used":13631488,"last_committed":13631488,"last_init":0,"last_max":-1,"last_used":13631488}}},"G1 Old Generation":{"count":0,"time":0,"pools":{"G1 Old Gen":{"committed":99614720,"init":241172480,"max":4294967296,"used":27288288,"peak_committed":241172480,"peak_init":241172480,"peak_max":4294967296,"peak_used":27288288,"last_committed":0,"last_init":241172480,"last_max":4294967296,"last_used":0}}}}

### Actual behavior
{"count": 245,"time": 602,"committed": 526385152.0,"init": 295698432.0,"max": 4294967292.0,"used": 353164384.0,"peak_committed": 687865856.0,"peak_init": 295698432.0,"peak_max": 4294967292.0,"peak_used": 491576416.0,"last_committed": 406847488.0,"last_init": 295698432.0,"last_max": 4294967292.0,"last_used": 2097152.0,"G1 Young Generation": {:count=>245, :time=>602, :pools=>{"G1 Survivor Space"=>{:committed=>1048576, :init=>0, :max=>-1, :used=>1048576, :peak_committed=>20971520, :peak_init=>0, :peak_max=>-1, :peak_used=>20971520, :last_committed=>1048576, :last_init=>0, :last_max=>-1, :last_used=>1048576}}},"G1 Old Generation": {:count=>0, :time=>0, :pools=>{"G1 Old Gen"=>{:committed=>119537664, :init=>241172480, :max=>4294967296, :used=>63757408, :peak_committed=>241172480, :peak_init=>241172480, :peak_max=>4294967296, :peak_used=>63757408, :last_committed=>0, :last_init=>241172480, :last_max=>4294967296, :last_used=>0}}}}

### System configuration

**Ruby version**: jruby-9.2.4.0 (Probably all JRuby)
**Puma version**: puma (3.12.0 java)

**Comment by nateberkopec** [comment]
Sure. Let's require `json` and use to_json.
