### ISSUE TITLE
Rails app calling api server refuses connection when api server calls back

### ISSUE THREAD

**Issue by gtibbitts** [puma/puma#1692]
We have a temporary situation with our rails application, due to an architectural migration. This requires us to initiate an api request from our puma rails server to our goliath api server, which in turn will make an http request back to the original puma rails server to retrieve additional data, then return the response back to the puma rails server.

Rails server ------> Api Server (Initial api request)

Rails server <------ Api Server (Get additional data via http endpoint)

Rails server <------ Api Server (Response to initial api request)

The problem we're having is the Rails server refuses to respond to the request from the api server for additional data. The error is: Internal Error: Errno::ECONNREFUSED but there is nothing in the rails log to indicate what went wrong or that it even attempted to receive the connection. It just refuses to respond. I am using puma on rails 5.2.0 for the rails application. The api is served by goliath and uses the grape gem.

I have the following in my config: config.cache_classes = false

config.allow_concurrency = true

Connections from the api server to the the rails server are successful when the original request isn't initiated from the rails server. Any ideas would be appreciated.

**Comment by evanphx** [comment]
If you're getting that error, that means that one of the servers isn't even listening on the port you gave. It was was listening and not accepting the connection, you'd like get a hang.

If for some reason you're making so many connections that the accept limit is reached, you might be over your thread limit. What do you have it set to? If you're making a request from puma => goliath => puma, you'll need at least 2 available threads to make that happen.
