### ISSUE TITLE
Travis - Ruby head/trunk test failures

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1703]
Travis tests on ruby-head/trunk have been failing for while, so 2.6 will probably do they same.  I'm a Windows type, and the tests involve fork, which isn't available on Windows.   Hence, I'm challenged as to this issue.

Could the following Ruby change affect it (very possibly a stupid question)?

[process.c: defaults to close_others false](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/64399)

**Comment by dentarg** [comment]
Linking this issue to our discussion in https://github.com/puma/puma/issues/1674#issuecomment-451973891. https://bugs.ruby-lang.org/issues/15499 may be the cause of the test failures.

**Comment by MSP-Greg** [comment]
Issue with Ruby 2.6.x & 2.7.x (trunk) involves bug introduced in `waitpid`.  See #1741.  Should revert it when Ruby Core fixes issue.
