### ISSUE TITLE
TestIntegration#test_term_signal_exit_code_in_clustered_mode fails

### ISSUE THREAD

**Issue by voxik** [puma/puma#1720]
### Steps to reproduce

Running test suite, I observe the following test suite error:

~~~
TestIntegration#test_term_signal_exit_code_in_clustered_mode = [1218] Puma starting in cluster mode...
[1218] * Version 3.12.0 (ruby 2.6.0-p0), codename: Llamas in Pajamas
[1218] * Min threads: 0, max threads: 16
[1218] * Environment: development
[1218] * Process workers: 2
[1218] * Phased restart available
[1218] * Listening on tcp://127.0.0.1:9998
[1218] Use Ctrl-C to stop
[1218] - Worker 0 (pid: 1219) booted, phase: 0
[1218] - Worker 1 (pid: 1221) booted, phase: 0
[1218] - Gracefully shutting down workers...
60.00 s = E
~~~

This breaks various subsequent test cases. It reminds #1675 a bit.

### System configuration

Testing on Fedora Rawhide:

~~~
$ rpm -q ruby  
ruby-2.6.0-111.fc30.x86_64

$ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]

$ rpm -q openssl-devel
openssl-devel-1.1.1a-1.fc30.x86_64
~~~

**Puma version**:
3.12.0

With two patches:

https://src.fedoraproject.org/rpms/rubygem-puma/blob/master/f/rubygem-puma-3.12.0-TLS13-fix.patch
https://src.fedoraproject.org/rpms/rubygem-puma/blob/master/f/rubygem-puma-3.6.0-fedora-crypto-policy-cipher-list.patch

**Comment by guilleiguaran** [comment]
I think this is fixed with https://github.com/puma/puma/pull/1738

**Comment by voxik** [comment]
@guilleiguaran I applied your patch and run 30 builds on different architectures and none of the builds failed with the error in question, so you are probably right :relaxed:

**Comment by AlexWayfer** [comment]
#1738 is closed in favor of #1741, which is already merged. Is this issue should be closed?

**Comment by guilleiguaran** [comment]
Yes! I think this can be closed, @voxik can you test with master and confirm?

**Comment by voxik** [comment]
The patch from #1741 appears to work for me. Thx :+1:

**Comment by evanphx** [comment]
This is the ruby 2.6 bug.
