### ISSUE TITLE
Errno::ECHILD: No child processes

### ISSUE THREAD

**Issue by silva96** [puma/puma#1725]
### Steps to reproduce

1) Update puma from 3.8.2 to 3.12.0

2) Configure puma to have 4 workers and 0, 16 threads 

3) Wait some hours, errors appear randomly

### Expected behavior

No error should appear.

### Actual behavior

Errors appear

![image](https://user-images.githubusercontent.com/4019924/52411323-2edc8b80-2aba-11e9-8ac8-c95e0c751107.png)

![image](https://user-images.githubusercontent.com/4019924/52411598-1faa0d80-2abb-11e9-8de4-1a62a8c072e8.png)

### System configuration

**Ruby version**: 2.4.0
**Rails version**: 5.0.2
**Puma version**: 3.12.0

**Comment by schneems** [comment]
I'm not sure where to start with this one. Does it happen if the server is under load? What command do you use to boot the server? Can you reproduce this in a docker container? Approximately how long are you having to wait for? If you change the worker or thread number does it no longer crash?


> Ruby version: 2.4.0

The first thing I would have you do is upgrade to the latest minor version which would be 2.4.5.

>  Rails version: 5.0.2

Same here, upgrade to the latest version of Rails, you didn't mention Rails earlier, does this only happen on one specific Rails project? Does it happen without Rails?

>  Puma version: 3.12.0

I just released 3.12.1 today, give that a shot, probably won't help. But it likely won't hurt.

**Comment by silva96** [comment]
This actually happens when PumaWorkerKiller kills a puma worker. I understand that this may be caused because of old versions of ruby/rails/puma so probable we should close it until I upgrade (wont be so soon)

regards.
