### ISSUE TITLE
Feature Request: Logger support

### ISSUE THREAD

**Issue by egtra** [puma/puma#1726]
I'm trying to get log from Puma as JSON format. Because a my Rails app uses [Semantic Logger](https://rubygems.org/gems/semantic_logger) for JSON format.

But `Puma::Events#initialize` accepts only IO-compatible objects for stdout and stderr. It's great if it accepts Ruby-stdlib's [Logger](https://docs.ruby-lang.org/en/2.6.0/Logger.html) object.

There are many gems that has compatible to Logger class.

- [ActiveSupport::Logger](https://api.rubyonrails.org/v5.2/classes/ActiveSupport/Logger.html)
- [Logging](https://rubygems.org/gems/logging)
- [Semantic Logger](https://rubygems.org/gems/semantic_logger)
- [Ougai](https://rubygems.org/gems/ougai)

I intend to make PR.

**Comment by evanphx** [comment]
Feel free to open that PR.
