### ISSUE TITLE
Error (closed stream)

### ISSUE THREAD

**Issue by glebm** [puma/puma#173]
Running ab -c 100 on a puma -t 8:32 -b unix://... on jruby in front of nginx I get a lot of exceptions (more than 30% of requests) like this:

```
[2012-12-05 00:20:24] FATAL Rails : 
ActionView::Template::Error (closed stream):
  # snipped: random empty line of a haml view backtrace 
```

What is this error and could it be related to puma?

Looks like IO gets closed while the request is still processing
Full backtrace here: https://gist.github.com/4215614
## 

If I use TCP instead of unix sockets, the error is:

```
RuntimeError (Missing rack.input):
```

---

Also happens on jruby-head + puma trunk

**Comment by prcongithub** [comment]
Is this resolved? I am getting the below error with JRuby-9.1.7.0 and Puma-3.7.0-java.

NoMethodError (undefined method `names' for nil:NilClass):
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:116:in `block in find_routes'
  org/jruby/RubyArray.java:2517:in `map!'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:113:in `find_routes'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  exception_notification (4.2.1) lib/exception_notification/rack.rb:32:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  org/jruby/RubyKernel.java:1120:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (1.6.5) lib/rack/etag.rb:24:in `call'
  rack (1.6.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.5) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:-1:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  puma-3.7.0 (java) lib/puma/configuration.rb:226:in `call'
  puma-3.7.0 (java) lib/puma/server.rb:578:in `handle_request'
  puma-3.7.0 (java) lib/puma/server.rb:415:in `process_client'
  puma-3.7.0 (java) lib/puma/server.rb:275:in `block in run'
  puma-3.7.0 (java) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by nateberkopec** [comment]
@prcongithub The last line of your stacktrace in the Rails router. Report it at the Rails repo, this is not a Puma issue.
