### ISSUE TITLE
uninitialized constant Puma::Cluster

### ISSUE THREAD

**Issue by Fudoshiki** [puma/puma#1731]
Rails master 6.0.0.beta1
Puma master

**puma.rb**
```rb
max_threads_count = ENV.fetch('RAILS_MAX_THREADS') { 5 }
min_threads_count = ENV.fetch('RAILS_MIN_THREADS') { max_threads_count }
threads min_threads_count, max_threads_count
environment ENV.fetch('RAILS_ENV') { 'development' }
workers ENV.fetch('WEB_CONCURRENCY') { 2 }
bind ENV.fetch('PUMA_SOCK') { 'unix://tmp/sockets/puma.sock' }
state_path ENV.fetch('SERVER_STATE') { 'tmp/pids/puma.state' }
activate_control_app ENV.fetch('PUMACTL_SOCK') { 'unix://tmp/sockets/pumactl.sock' }
pidfile 'tmp/pids/puma.pid'
worker_timeout 10
plugin :tmp_restart
```

```cmd
/usr/local/rvm/bin/rvm 2.6.1 do bundle exec pumactl -S ~/repository/shared/tmp/pids/puma.state -F ~/repository/current/config/puma.rb stop
uninitialized constant Puma::Cluster
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/lib/puma/dsl.rb:455:in `worker_timeout'
/srv/webapp/repository/current/config/puma.rb:69:in `_load_from'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/lib/puma/dsl.rb:43:in `instance_eval'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/lib/puma/dsl.rb:43:in `_load_from'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/lib/puma/configuration.rb:194:in `block in load'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/lib/puma/configuration.rb:194:in `each'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/lib/puma/configuration.rb:194:in `load'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/lib/puma/control_cli.rb:85:in `initialize'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/bin/pumactl:5:in `new'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bundler/gems/puma-0991396844fe/bin/pumactl:5:in `<top (required)>'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bin/pumactl:23:in `load'
/srv/webapp/repository/shared/bundle/ruby/2.6.0/bin/pumactl:23:in `<top (required)>'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/srv/webapp/.rvm/gems/ruby-2.6.1/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/srv/webapp/.rvm/gems/ruby-2.6.1/bin/bundle:23:in `load'
/srv/webapp/.rvm/gems/ruby-2.6.1/bin/bundle:23:in `<main>'
```

**Comment by MSP-Greg** [comment]
The error (uninitialized constant Puma::Cluster) is from puma/dsl.rb:466, which is required by puma/configuration.

https://github.com/puma/puma/blob/ca03c520757e4ed1caab28bf4f60ec2ffe5b2585/lib/puma/dsl.rb#L464-L466

The code causing the error was due to commit 64db36c0, 'Enforce a minimum worker_timeout' on 2019-01-24.

With the error shown, the call stack starts with puma/control_cli

```
puma/control_cli.rb:242 (#start) which requires:
puma/cli                         which requires:
puma.launcher                    which requires:
puma/cluster
```

Options to fix:

1. In control_cli, move `require 'puma/cli'` from the start method to the initialize method.

2. In puma/dsl, add `require 'puma/cluster'` to the worker_timeout method.

3. Adding `require` elsewhere.

**Comment by schneems** [comment]
It looks like that line in the control_cli was added in https://github.com/puma/puma/commit/274350a2e69cc86e3fa9d8f30ac8dea9f4afeef0 about 6 years ago. I generally don't like having requires in methods unless there's a really good reason. 

I don't see a downside to having the require be outside of the method and at the top of the file, though feel free to let me know if that causes issues.

**Comment by MSP-Greg** [comment]
> I generally don't like having requires in methods unless there's a really good reason.

Agreed.  I didn't mention that `puma/cli.rb` requires `puma`, so I wasn't sure if it was a circular require issue.  I haven't looked into all the various ways one can start Puma, so I left it alone.

https://github.com/puma/puma/blob/2f57c8e403fd76927b484f3945f5f7408186e0c0/lib/puma.rb#L11-L14

Since it's autoloading three files, maybe add `:Cluster`?

**Comment by schneems** [comment]
Can you try out a fix on a branch and we can see if the tests pass? I'm fine with an autoload, but it does seem like overkill for that one little constant. I think once we get this fix in then we can probably ship another version I'm working on a history.md now.

**Comment by MSP-Greg** [comment]
I'll give a try with Autoload.  Dumb question - if we're autoloading Cluster, should the same be done with Single?

> Actually looks like there are other release plans.

nio4r?  etc?

**Comment by schneems** [comment]
> nio4r? etc?

Likely, a slightly more purposeful release rather than just the cobbled together remnants of master. Ideally targeting RailsConf timeframe.

**Comment by nateberkopec** [comment]
We should probably just Zeitwerk everything for the future, eh?
