### ISSUE TITLE
CI is fixed? #1736 & #1738

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1739]
With the long standing failure in ruby 2.6 (and trunk in Q4 2018) fixed by PR #1738 (thanks to @guilleiguaran), along with the JRuby fixes in #1736, it would seem that CI should work.

Also, both 2.6 & JRuby 9.2.6.0 can be removed from 'allow failure' in Travis?

**EDIT:** Should 2.6 JIT be 'allow failure' in Travis?

Hence, please consider merging the two PR's...

**Comment by evanphx** [comment]
#1738 isn't right I don't think. I merged #1736.
