### ISSUE TITLE
no log output in prodution.log or development.log

### ISSUE THREAD

**Issue by shisongsong** [puma/puma#1740]
### Steps to reproduce
When I run `puma` in the local, can't print any log info

### System configuration

**Ruby version**:2.1.2
**Rails version**:3.2.9
**Puma version**:3.9.1

**Comment by evanphx** [comment]
puma does not log anythingn by default, you must use a rack middleware for that.

**Comment by shisongsong** [comment]
@evanphx Logger is configured but no log data in it
