### ISSUE TITLE
ActionCable requests High Response Time

### ISSUE THREAD

**Issue by cesar3030** [puma/puma#1742]
High Response Time on `/cable` endpoint when using ActionCable with Puma server.

Here is a screenshot of the requests to my Puma server deployed on Heroku (Professional Dyno with 512Mo RAM). Most of the requests to `/cable` endpoint are taking a very long time.

Am I the only one experiencing this?

![Screen Shot 2019-03-12 at 12 05 29 PM](https://user-images.githubusercontent.com/3688337/54235714-43aca480-44e8-11e9-8278-806b0e7178df.png)

### Expected behavior

`/cable` requests should be processed in a few ms.

### Actual behavior

`/cable` requests are taking ages to be processed.

### System configuration

**Ruby version**: 2.5.1
**Rails version**: 5.2.2
**Puma version**: 3.12.0

**Comment by cesar3030** [comment]
Created a Rails [issue](https://github.com/rails/rails/issues/35590)

**Comment by tonydehnke** [comment]
> Created a Rails [issue](https://github.com/rails/rails/issues/35590)

@cesar3030 I’m running into this too. Did you find a solution or fix?

**Comment by cesar3030** [comment]
@tonydehnke No I didn't and I stopped working with this rails app so It won't have any further investigation regarding this issue from my end sorry. Good luck!

**Comment by birthdaycorp** [comment]
@tonydehnke did you find a solution? I'm having the same problem. I'm the only person using my app at the moment, and I'm getting HUGE response times as a result of `/cable` GET requests

**Comment by tonydehnke** [comment]
No I have not.. it still an ongoing thing in my app :(

**Comment by mariosouto** [comment]
Hi, i was following this issue https://github.com/rails/rails/issues/35590 and i ended up here. This is happening to me too. My system configuration is

*Ruby version: * 2.6.3
*Rails version: * 5.2.3
*Puma version: * 4.3.1

I'm using a Heroku hobby dyno with very few traffic. Although Action Cable is working fine and fast, i get `ALERT High Response Time` from Heroku and seeing huge times like these

`dyno=web.1 connect=0ms service=101463ms status=101 bytes=2259 protocol=https`

Does anyone know what could be the reason? Thanks!

**Comment by birthdaycorp** [comment]
> Hi, i was following this issue [rails/rails#35590](https://github.com/rails/rails/issues/35590) and i ended up here. This is happening to me too. My system configuration is
> 
> **Ruby version:** 2.6.3
> **Rails version:** 5.2.3
> **Puma version:** 4.3.1
> 
> I'm using a Heroku hobby dyno with very few traffic. Although Action Cable is working fine and fast, i get `ALERT High Response Time` from Heroku and seeing huge times like these
> 
> `dyno=web.1 connect=0ms service=101463ms status=101 bytes=2259 protocol=https`
> 
> Does anyone know what could be the reason? Thanks!

Same here. What are your puma configurations?

**Comment by mariosouto** [comment]
> > Hi, i was following this issue [rails/rails#35590](https://github.com/rails/rails/issues/35590) and i ended up here. This is happening to me too. My system configuration is
> > **Ruby version:** 2.6.3
> > **Rails version:** 5.2.3
> > **Puma version:** 4.3.1
> > I'm using a Heroku hobby dyno with very few traffic. Although Action Cable is working fine and fast, i get `ALERT High Response Time` from Heroku and seeing huge times like these
> > `dyno=web.1 connect=0ms service=101463ms status=101 bytes=2259 protocol=https`
> > Does anyone know what could be the reason? Thanks!
> 
> Same here. What are your puma configurations?

It's pretty basic actually

```rb
threads_count = ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i
threads threads_count, threads_count
port ENV.fetch('PORT') { 3000 }
environment ENV.fetch('RAILS_ENV') { 'development' }
plugin :tmp_restart
```

my `RAILS_ENV` variable is `staging`, which is pretty much the same as the `production` environment. The rest is the same, i didn't override any variables

**Comment by birthdaycorp** [comment]
> > > Hi, i was following this issue [rails/rails#35590](https://github.com/rails/rails/issues/35590) and i ended up here. This is happening to me too. My system configuration is
> > > **Ruby version:** 2.6.3
> > > **Rails version:** 5.2.3
> > > **Puma version:** 4.3.1
> > > I'm using a Heroku hobby dyno with very few traffic. Although Action Cable is working fine and fast, i get `ALERT High Response Time` from Heroku and seeing huge times like these
> > > `dyno=web.1 connect=0ms service=101463ms status=101 bytes=2259 protocol=https`
> > > Does anyone know what could be the reason? Thanks!
> > 
> > 
> > Same here. What are your puma configurations?
> 
> It's pretty basic actually
> 
> ```ruby
> threads_count = ENV.fetch('RAILS_MAX_THREADS') { 5 }.to_i
> threads threads_count, threads_count
> port ENV.fetch('PORT') { 3000 }
> environment ENV.fetch('RAILS_ENV') { 'development' }
> plugin :tmp_restart
> ```
> 
> my `RAILS_ENV` variable is `staging`, which is pretty much the same as the `production` environment. The rest is the same, i didn't override any variables

I think I figured it out. This alert isn't an issue at all, and it's to be expected. The `/cable` connection needs to be open so that it can send and receive updates. Heroku's Logentries add-on is just miscategorizing it as a problem. Turning the alert off solves the problem.

**Comment by jpwynn** [comment]
FWIW I think there is SOME way in Logentries to edit the High Response Time alert to EXCLUDE /cable

Unfortunately Logentries' docs stink as bad as their support, whose sole answer last time I asked how to filter something was "use regex".

**Comment by jpwynn** [comment]
FWIW the following seems to work in Logentries to OMIT /cable for High Response Time alerts, so only the normal routes have the alert:

In your Logentries dashboard, edit Tags&Alert > High Response Time > Pattern

from: (service > 5000)

to: (service > 5000) AND NOT (path cable)
