### ISSUE TITLE
ANN: Puma master docs available

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1743]
I've got a doc site that I ignored for a while, but I decided to start updating it.  Works pretty well on a tablet; it's YARD based with several changes and additional features.

All source code is included, and all methods are shown.

Several repos are shown on the home page, most are generated from repo master branches.

[Puma home](https://msp-greg.github.io/puma/)

[Main home](https://msp-greg.github.io/)

I'll close in a few days...

**Comment by evanphx** [comment]
I'd be happy to move these under the puma site as well.

**Comment by MSP-Greg** [comment]
I think that should work.  The link above is to master, and shows private & :nodoc: methods, and source code.

I can easily remove any or all.   Preference?

Do you want the most recent gem release?

I've fired up Jekyll with a kind of 'hello world'  example.  Never tried it with a mix of 'generated' & static content...

JFYI: I quickly looked thru the methods list, and `Puma::Server##handle_check` and `Puma::ThreadPool##spawn_thread` were the only :nodoc: methods.  `spawn_thread` is private, `handle_check` isn't, but looks like it could be...

**Comment by MSP-Greg** [comment]
@evanphx

I had some monkeying around to do, but I think it's correct. See [Puma.io PR 23](https://github.com/puma/puma.io/pull/23)

**Comment by nateberkopec** [comment]
Merged on puma.io
