### ISSUE TITLE
Puma not accepting requests under Ruby 2.5.4 in cluster mode

### ISSUE THREAD

**Issue by jmccartie** [puma/puma#1744]
### Steps to reproduce

1) New Rails app. 5.2.2.1

2) Use Ruby 2.5.4

3) Change to cluster mode:

```
workers ENV.fetch("WEB_CONCURRENCY") { 2 }
preload_app!
```

4) Boot app

```
* Version 3.12.0 (ruby 2.5.4-p155), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:5000
```

4) Make a request

### Expected behavior

Rails and Puma should serve the request.

### Actual behavior

Nothing is returned. The process must be killed.

This works fine in single mode, but fails in clustered mode.

### System configuration

**Ruby version**: 2.5.4
**Rails version**: 5.2.2.1
**Puma version**: 3.12

**Comment by jmccartie** [comment]
Also: same app setup, downgrading to Ruby 2.5.3, and all is well.

```
➜  test-app git:(master) ✗ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
➜  test-app git:(master) ✗ rs -p 5000
=> Booting Puma
=> Rails 5.2.2.1 application starting in development
=> Run `rails server -h` for more startup options
[95310] Puma starting in cluster mode...
[95310] * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
[95310] * Min threads: 5, max threads: 5
[95310] * Environment: development
[95310] * Process workers: 2
[95310] * Preloading application
[95310] * Listening on tcp://localhost:5000
[95310] Use Ctrl-C to stop
[95310] - Worker 0 (pid: 95324) booted, phase: 0
[95310] - Worker 1 (pid: 95325) booted, phase: 0
Started GET "/" for ::1 at 2019-03-13 19:07:05 -0700
Processing by HomeController#index as HTML
  Rendering home/index.html.erb within layouts/application
  Rendered home/index.html.erb within layouts/application (1.3ms)
Completed 200 OK in 163ms (Views: 160.9ms | ActiveRecord: 0.0ms)
```

**Comment by ledowong** [comment]
same issue here.

**Comment by zunda** [comment]
It might be worth while waiting for the release of 2.5.5.

https://twitter.com/nagachika/status/1106317614903521281

> Hi Rubyists. I have bad news and good news. The Ruby 2.5.4 releasd at day before yesterday has serious deadlock issue with multi thread app (ex: puma). Thanks to @k0kubun pointed me the root cause, I will release 2.5.5 sooner.

**Comment by jmccartie** [comment]
This is resolved with Ruby 2.5.5

**Comment by bennibu** [comment]
We have run into the same issue, but came to another conclusion. Not the cluster mode (--worker) was the issue, but the fixed thread pool (--thread 5:5) caused the problem. So `puma --workers 2 --threads 0:2` is working just fine in ruby 2.5.4.

**Comment by bennibu** [comment]
Sorry, I have made another checks and have to withdraw my first comment. It's the worker mode. But with the dynamic thread pool the first request will be properly served, instead with fixed threads no request will get through the stack.
