### ISSUE TITLE
bundle exec puma with bundler 2 fails

### ISSUE THREAD

**Issue by mortik** [puma/puma#1745]
Start puma with ```bundle exec puma -C config/puma.rb```

puma.rb:
```
# frozen_string_literal: true

workers Integer(ENV['WEB_CONCURRENCY'] || 3)
threads_count = Integer(ENV['MAX_THREADS'] || 16)
threads threads_count, threads_count

pidfile "#{ENV['APP_DIR']}/tmp/pids/puma.pid"
state_path "#{ENV['APP_DIR']}/tmp/pids/puma.state"

prune_bundler

rackup      DefaultRackup
port        ENV['PORT']      || 3000
environment ENV['RAILS_ENV'] || 'development'
```

### Expected behavior

Puma starts normally

### Actual behavior

Puma logs the following error:
```
You must use Bundler 2 or greater with this lockfile
```

### System configuration

**Ruby version**: 2.6.2
**Rails version**: 5.2.2.1
**Puma version**: 3.12.0
**Bundler version**: 2.0.1
**Rubygems version**: 3.0.3

**Comment by deivid-rodriguez** [comment]
Can you upgrade to Ruby 2.6.2 and try again?

**Comment by mortik** [comment]
Already did that, no change sadly

**Comment by schneems** [comment]
I think this is a bundler/rubygems bug and not an issue with Puma. Does the bundle command fail with other commands such as `bundle exec ruby -v` or only with `bundle exec puma ...`?

If it fails across the board I would recommend building a reproduction application that you can share with the bundler team over at bundler/bundler.

**Comment by mortik** [comment]
No this issue only occurs with bundle exec puma

Ok i will try that, thanks

**Comment by schneems** [comment]
> No this issue only occurs with bundle exec puma

That's weird. Makes me think the problem might be with your binstubs. Check `bin/puma` maybe it's accidentally pointing to a different version of Ruby.

**Comment by mortik** [comment]
Another weird thing is that this issue only occurs on CircleCI and not locally but only when i upgrade to bundler 2 :/

**Comment by mortik** [comment]
Maybe you are right and this is really an issue with bundler 2 and/or the Setup on CircleCI
