### ISSUE TITLE
conditional method definition - documentation

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1754]
While looking at various 'documentation' edge cases, I was reminded of the issue involving conditional method definition.  Puma has a handful of them, most seem to be JRuby related.

If one would prefer that both methods are visible in documentation, one option is to prefix/suffix a method, so the MRI version would be:

```
Puma::Client#eagerly_finish
```

and the JRuby version might be:
```
Puma::Client#jruby_eagerly_finish
```

Then adding the following in the JRuby conditional block:
```ruby
send(:alias_method, :eagerly_finish, :jruby_eagerly_finish)
```

The statement would be hidden from doc systems, but would allow both methods to appear.  A comment could be added to inform of the 'hidden' alias.  I haven't checked with RDoc yet.

As to prefix or suffix, since most doc systems will show an alpha sort of methods, a prefix groups them all together, but a suffix shows that both 'eagerly_finish' & 'eagerly_finish_jruby' exist.  I think a suffix would be better, maybe...

Would changes like this be acceptable?

**Comment by nateberkopec** [comment]
Yes - I like the idea very much. I have no preference on suffix or prefix.
