### ISSUE TITLE
puma cluster 100% cpu usage

### ISSUE THREAD

**Issue by cryo28** [puma/puma#176]
Puma 2.0.0.b4 is run as rails app backend server by the means of upstart as:

```
bundle exec puma -C config/puma.rb -e staging >> log/puma.log 2>&1
```

If there are no **workers 1** line in the config file puma uses cpu quite ordinary (less than 1% if there is not load. No problem for now).

As soon as I add **workers 1** (or any higher number) to the puma's config file (effectively enabling puma cluster mode), puma master process consumes 100% CPU (under no load). The rails app is perfectly operatable at the same time. Don't know what will happend under high load though. The puma's stdout and stderr report no errors of any kind:

`
[25912] Puma 2.0.0.b4 starting in cluster mode...
[25912] * Process workers: 1
[25912] * Min threads: 1, max threads: 16
[25912] * Environment: staging
[25912] * Listening on unix:///srv/projects/projectname/current/tmp/sockets/puma.sock
[25912] Use Ctrl-C to stop
`

**Comment by ozzyaaron** [comment]
I'm hitting this problem with the latest Puma (2.11.3) in development after I have used the debugger. There is an issue in byebug that seems to be getting worked on https://github.com/deivid-rodriguez/byebug/issues/144
