### ISSUE TITLE
Impossible to load plugins with prune_bundler and workers > 0

### ISSUE THREAD

**Issue by ylecuyer** [puma/puma#1761]
### Steps to reproduce

1) Create a gem with a plugin inside `puma/plugin/test.rb`

2) Create a `config/puma.rb` with

```
plugin 'test'

workers 2

prune_bundler
```

3) start with `./bin/puma`

```
/home/ylecuyer/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/plugin.rb:50:in `rescue in find': Unable to find plugin: test (Puma::UnknownPlugin)
```

### Expected behavior

It should boot the worker with the plugin loaded

### Actual behavior

It fails to find the plugin when starting the workers because bundler as been pruned and when requiring the plugin it is not in `$LOAD_PATH` for the plugin to work in this condition it has to be in the core puma gem. kind of useless

### System configuration

**Ruby version**: ruby 2.5.3p105
**Rails version**: Rails 4.2.11.1
**Puma version**: puma 3.12.1

**Comment by ylecuyer** [comment]
I have created a test repo that will allow you to reproduce the bug : https://github.com/puma/puma/issues/1761

**Comment by SwagDevOps** [comment]
Same issue!

**Comment by ylecuyer** [comment]
@SwagDevOps can you test the workaround in #1763 to see if it fits your case too?

**Comment by SwagDevOps** [comment]
I don't use plugins (atm), but my issue is similar.

**Comment by ylecuyer** [comment]
As I said in the PR the naming is not good atm. Really if the thing you require in the `config/puma.rb` is in the Gemfile you can use the same trick.

**Comment by nateberkopec** [comment]
I think this was fixed with 809a3f4c7beb2b803e068bad.

This config file now works:

```ruby
plugin 'heroku'

workers 2
extra_runtime_dependencies "puma-heroku" # this is the critical added line
prune_bundler

app do |env|
  [200, {}, ["embedded app"]]
end

```

**Comment by nateberkopec** [comment]
So, perhaps what we should be doing instead is adding anything found via `plugin <somegem>` to extra_runtime_dependencies automatically.

**Comment by nateberkopec** [comment]
<img width="695" alt="Screen Shot 2019-10-22 at 11 41 35 AM" src="https://user-images.githubusercontent.com/845662/67257943-ebe40c00-f4c0-11e9-9c26-34e130517a5d.png">

Slightly different idea.

Basically it seems to me that we can fix this without adding any new DSL commands or requiring the user to do anything at all. The information is all there, we just need to use it correctly.

**Comment by hahmed** [comment]
@nateberkopec I agree it would be much better if users did not have to be concerned with adding any DSL, that is my preferred route too. 

> The information is all there, we just need to use it correctly.

Where is the info for all the plugins loaded?

```
    def dependencies_and_files_to_require_after_prune
      puma = spec_for_gem("puma")

      deps = puma.runtime_dependencies.map do |d|
        "#{d.name}:#{spec_for_gem(d.name).version}"
      end

      puts @config.plugins.inspect
...
```

the puts outputs something like the below, which is not an array of the plugins..

`#<Puma::PluginLoader:0x00007fb92e9af8a0 @instances=[#<#<Class:0x00007fb92e96df68>:0x00007fb92e96d888 @loader=Puma::Plugin>]>`

**Comment by nateberkopec** [comment]
So neither I or @hahmed can repro this anymore, so I'm going to close. Please comment if you have the same happen to you.
