### ISSUE TITLE
Feature Request: bind to multiple ip:port pairs

### ISSUE THREAD

**Issue by mistergibson** [puma/puma#1762]
What would it take to implement a stack-able 'bind' aspect of puma? I mean that in Unicorn, one can give the 'listen' directive in unicorn.rb multiple times to bind to several network adapters all at once. Puma gives no hint of supporting this, so I assume it currently does not.

unicorn.rb:
...
listen 127.0.0.1:8080
listen 192.168.1.100:80
listen 10.0.0.100:80
...
... like that.

Would you consider adding this feature to Puma? What would that entail if so?

**Comment by evanphx** [comment]
It does support it! https://github.com/puma/puma/blob/master/lib/puma/dsl.rb#L125-L140

**Comment by mistergibson** [comment]
wow, I'm sorry --> I completely misread the info. My mistake, thanks for the speedy response ;)
