### ISSUE TITLE
More debug to QUERY_STRING max length

### ISSUE THREAD

**Issue by ylecuyer** [puma/puma#1768]
### Steps to reproduce

1) Make an HTTP query with a query string bigger than 1024*10

2) read the output of puma stderr

```
2019-04-11 11:37:02 +0200: HTTP parse error, malformed request (127.0.0.1): #<Puma::HttpParserError: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length (was 15839)>
```

### Expected behavior

The actual HTTP uri should be logged to know which query triggered the error

### Actual behavior

The error message only shows the error and not the associated URI

### System configuration

**Ruby version**: ruby 2.5.3p105
**Rails version**: Rails 4.2.11.1
**Puma version**: puma-3.12.0

**Comment by nateberkopec** [comment]
I wonder if we should log something other than the URL too.

**Comment by nateberkopec** [comment]
Merged on master.

**Comment by ylecuyer** [comment]
Thanks
