### ISSUE TITLE
ability to turn off backtraces in pumactl

### ISSUE THREAD

**Issue by jessebs** [puma/puma#1769]
### Steps to reproduce

1) run `pumactl badcommand`

### Expected behavior

An error message that the command is invalid

### Actual behavior

An error message that the command is invalid, as well as a stacktrace that is useless to end users

### System configuration

**Ruby version**: 2.5.1
**Puma version**: 3.12.1

**Comment by nateberkopec** [comment]
Great PR as well. I wonder if we should show the stacktrace at all though? Maybe we should just remove the stacktrace entirely?

**Comment by jessebs** [comment]
I fully agree with removing the trace.

**Comment by nateberkopec** [comment]
It looks like it was added by @schneems in #1239 as a sort of temporary debugging measure, but it was committed. I think it's really only useful for us maintainers, and we can add it back in locally if we need it.

Please close your old PR and open a new one removing the line and I will merge.
