### ISSUE TITLE
NoMethodError: undefined method `each' for "":String in Ruby 2.6.3 and Rails 5.2.3

### ISSUE THREAD

**Issue by noctivityinc** [puma/puma#1782]
### Steps to reproduce

1) Upgrade rails app to 5.2.3 and Ruby 2.6.3

2) Run rspec feature specs

3) check logs

### Expected behavior

No errors stemming from puma

### Actual behavior

Read error about undefined string in rack resulting from PUMA:

2019-04-23 16:46:43 -0400: Read error: #<NoMethodError: undefined method `each' for "":String>
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/puma-3.12.1/lib/puma/server.rb:793:in `handle_request'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/Users/jlippiner/.rvm/gems/ruby-2.6.3@dmvcs/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'

### System configuration

**Ruby version**: 2.6.3
**Rails version**: 5.2.3
**Puma version**:3.12.1

**Comment by evanphx** [comment]
That is from you passing a string as the body. The body needs to something that responds to .each.

**Comment by noctivityinc** [comment]
Yes I see that error but why is the body blank?  This only started after
upgrading to the latest ruby and rails versions.  Nothing else changed in
our app which doesn’t have this error in rails 5.1 on ruby 2.6.1

**Comment by evanphx** [comment]
String#each was removed in I think ruby 2.4, what version were you upgrading from? I don't have any insight other than that sadly.

**Comment by noctivityinc** [comment]
Ive been running 2.6.1 for some time without issue.

How would I go about trying to find the source of this if all stack traces
start with puma?

Thanks.

**Comment by kbabou** [comment]
Use instead .each_char, .each_line or .each_bytes depending on your need.
