### ISSUE TITLE
cannot load such file -- puma/minissl

### ISSUE THREAD

**Issue by robinsingh-bw** [puma/puma#1789]
### Steps to reproduce
puma -b 'ssl://127.0.0.1:3000key=/Users/name/.ssh/server.key&cert=/Users/name/.ssh/server.crt'

Errors:
´´´
➜  myapp git:(master) ✗ puma -b 'ssl://127.0.0.1:3000?key=/Users/Robin/.ssh/server.key&cert=/Users/Robin/.ssh/server.crt'
[49048] Puma starting in cluster mode...
[49048] * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
[49048] * Min threads: 5, max threads: 5
[49048] * Environment: development
[49048] * Process workers: 2
[49048] * Preloading application
Traceback (most recent call last):
	15: from /Users/robin/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
	14: from /Users/robin/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	13: from /Users/robin/.rvm/gems/ruby-2.5.1/bin/puma:23:in `<main>'
	12: from /Users/robin/.rvm/gems/ruby-2.5.1/bin/puma:23:in `load'
	11: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/bin/puma:10:in `<top (required)>'
	10: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/cli.rb:78:in `run'
	 9: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/launcher.rb:184:in `run'
	 8: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/cluster.rb:397:in `run'
	 7: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/runner.rb:144:in `load_and_bind'
	 6: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/binder.rb:88:in `parse'
	 5: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/binder.rb:88:in `each'
	 4: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/puma-3.11.4/lib/puma/binder.rb:147:in `block in parse'
	 3: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	 2: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	 1: from /Users/robin/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/Users/robin/.rvm/gems/ruby-2.5.1/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require': cannot load such file -- puma/minissl (LoadError)
´´´

It says this was resolved in a similar issue but its not.

**Comment by dannyfallon** [comment]
I've tried to reproduce this without any luck, either on 3.11.4 or 3.12.1. 

```
➜  foremanapp git:(master) ✗ bundle exec puma -b 'ssl://127.0.0.1:3000key=/Users/danny/src/foremanapp/localhost.key&cert=/Users/danny/src/foremanapp/localhost.crt'
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.5-p157), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
bundler: failed to load command: puma (/Users/danny/.rbenv/versions/2.5.5/bin/puma)
URI::InvalidURIError: bad URI(is not URI?): ssl://127.0.0.1:3000key=/Users/danny/src/foremanapp/localhost.key&cert=/Users/danny/src/foremanapp/localhost.crt
  /Users/danny/.rbenv/versions/2.5.5/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split'
```

Cool, so let's put in a `?key` instead, since that's a valid URI (assuming this is just a mistake on your part):

```
➜  foremanapp git:(master) ✗ bundle exec puma -b 'ssl://127.0.0.1:3000?key=/Users/danny/src/foremanapp/localhost.key&cert=/Users/danny/src/foremanapp/localhost.crt'
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.5-p157), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on ssl://127.0.0.1:3000?key=/Users/danny/src/foremanapp/localhost.key&cert=/Users/danny/src/foremanapp/localhost.crt
Use Ctrl-C to stop
```

Works just fine :+1:

Let's try with 2 workers in clustered mode with preloading, because from your example output that's what you've got going on:

```
➜  foremanapp git:(master) ✗ bundle exec puma -b 'ssl://127.0.0.1:3000?key=/Users/danny/src/foremanapp/localhost.key&cert=/Users/danny/src/foremanapp/localhost.crt' -w 2 --preload
[17036] Puma starting in cluster mode...
[17036] * Version 3.11.4 (ruby 2.5.5-p157), codename: Love Song
[17036] * Min threads: 5, max threads: 5
[17036] * Environment: development
[17036] * Process workers: 2
[17036] * Preloading application
[17036] * Listening on ssl://127.0.0.1:3000?key=/Users/danny/src/foremanapp/localhost.key&cert=/Users/danny/src/foremanapp/localhost.crt
[17036] Use Ctrl-C to stop
[17036] - Worker 0 (pid: 17049) booted, phase: 0
[17036] - Worker 1 (pid: 17050) booted, phase: 0
```

Can you please supply a reproduceable test case, up to and including your testing app with `config/puma.rb`.

**Comment by nateberkopec** [comment]
No repro in ~6 months, please let us know if you can provide one and we'll reopen.
