### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by spuyet** [puma/puma#1796]
Can we have a new `puma` release ? we're really interested by [this feature](https://github.com/puma/puma/commit/3be7a8ec2eef833539e42322448abf0439a4f775) to help us debug performances issues on a app that we're trying to switch from `passenger` to `puma`.

**Comment by nateberkopec** [comment]
Thanks for using Puma. A release is forthcoming. One of our maintainers is having some medical issues right now. Please maintain a fork with any features you need in the meantime.
