### ISSUE TITLE
Error starting Puma through Rails Server command

### ISSUE THREAD

**Issue by ultrasam** [puma/puma#1797]
I´ve been trying to install rbenv, ruby and rails in my Raspberry Pi 3 B+ in the past couple of days and after some issues here and there I've managed to get everything installed with no errors

With rbenv I installed both Ruby 2.6.3 and Ruby 2.5.5
Using Rails 5.2.3

and with both ruby versions I am getting the same problem when I execute the command:
```
rails server
```

### Steps to reproduce

1) On a Raspberry Pi install rbenv using brew
```
brew install rbenv
```

2) Then use the following command to install ruby
```
rbenv install 2.6.3
``` 

3) Then install rails:
```
gem install rails -v 5.2.3
```

4) Create a new folder to hold your application and go to that folder:
```
$ cd                  # Change to the home directory.
$ mkdir environment     # Make a environment directory.
$ cd environment/       # Change into the environment directory.
```

5) Use rails to create the application inside the previous folde:
```
rails _5.2.3_ new hello_app
```

6) Go to the recently created 'hello_app' folder
```
cd hello_app
```
7) Start the rails server
```
rails server
```
### Expected behavior

```
pi@raspberrypi:~/environment/hello_app $ rails server
=> Booting Puma
=> Rails application starting on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
```
And then it should just stay there to be able to access the web app on the address indicated

### Actual behavior

First the output shows this:
```
pi@raspberrypi:~/environment/hello_app $ rails server
=> Booting Puma
=> Rails 5.2.3 application starting in development 
=> Run `rails server -h` for more startup options
```
And then the contents of the text file in the next link are shown.

Here is a link with the whole output:

https://www.dropbox.com/s/gjgo81zqeekfnvt/railsservererror.txt?dl=0
### System configuration

**Ruby version**: I´ve tried with both 2.6.3 and Ruby 2.5.5
**Rails version**: I've tried with 6.0.0.rc1 and with 5.2.3
**Puma version**: I've tried with 3.12.1 and a previous one too

I would really appreciate if someone could give me a hand to solve this problem.

Thanks,

**Comment by dannyfallon** [comment]
According to your segfault's `Control frame information` you never even reached Puma. I would think that since Puma was never reached if you swapped `puma` in your gemfile for `thin` or `webrick` you still wouldn't be able to run `rails server`. 

When you run `rails server` the application does a bunch of stuff before actually passing off the `Rails::Application` to a Rack server to run. In development Rails creates an `EventedFileWatcher` to watch for file changes so it can reload your app without you having to stop/start your server all the time. This uses the `listen` gem, which under the hood uses some OS-specific file events so it doesn't have to keep polling. In trying to create a watch (which `listen` does through `rb-inotify` for Linux), Ruby encountered a segmentation fault:

```
/home/pi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:57: [BUG] Segmentation fault at 0xe92d000e
ruby 2.5.5p157 (2019-03-15 revision 67260) [armv7l-linux-eabihf]

-- Control frame information -----------------------------------------------
c:0095 p:---- s:0527 e:000526 CFUNC  :inotify_init
c:0094 p:0041 s:0523 e:000522 METHOD /home/pi/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rb-inotify-0.10.0/lib/rb-inotify/notifier.rb:57 [FINISH]
```

Because `rb-inotify` is using FFI and some C functions, when things go wrong it does tend to blow up badly with segmentation faults.

There's lots of stuff you can do if you want to go deeper like report a bug over at FFI, attempt to recompile Ruby from source, test `inotify` on your distro outside of Ruby but you probably just want to get on with some development given you've been at it a few days.

I believe to fix this you can open `config/development.rb` and replace this:

```ruby
  # Use an evented file watcher to asynchronously detect changes in source code,
  # routes, locales, etc. This feature depends on the listen gem.
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker
```

with 

```ruby
  # Use a simple file watcher to detect changes in source code
  config.file_watcher = ActiveSupport::FileUpdateChecker
```

Caveat: The `EventedFileWatcher` is supposed to use OS events to detect file changes. The `FileWatcher` will poll for changes. This may slow down reloads or cause higher system load.

**Comment by ultrasam** [comment]
OMG, that totally worked!!!
![image](https://user-images.githubusercontent.com/688251/57886772-9d389480-77f3-11e9-8238-60dce658a814.png)
Thank you very much @dannyfallon , now what would you suggest in order for me try to fix this problem and be able to continue using:
config.file_watcher = ActiveSupport::EventedFileUpdateChecker
Where do I report this problem to FFI?

**Comment by ultrasam** [comment]
by the way @dannyfallon I get the same segmentation fault when I try create a new rails app with rails version 6.0.0.rc1:
´´´
rails _6.0.0.rc1_ new hello_app
´´´
but if I use version 5.2.3 I don´t get the error
´´´
rails _5.2.3_ new hello_app
´´´

Do you know if there is a workaround for that?

**Comment by dannyfallon** [comment]
:wave: Now we're into trying to debug Ruby/your variant of Linux and I don't have a Raspberry Pi I'm afraid. When you generate a new app I believe it'll default to the evented file watcher again so you'll have to be sure to change it. 

If you want to try to fix the issue it might be worth trying to compile and install Ruby from source - perhaps the version that you're getting with rbenv is incompatible with your flavour of Linux. Maybe your kernel doesn't support it? I'm afraid I can't really help you on that one, sorry.

**Comment by ultrasam** [comment]
Thank you very much for all your help @dannyfallon I will continue this discussion in the FFI github site

**Comment by iAaquibjawed** [comment]
> I´ve been trying to install rbenv, ruby and rails in my Raspberry Pi 3 B+ in the past couple of days and after some issues here and there I've managed to get everything installed with no errors
> 
> With rbenv I installed both Ruby 2.6.3 and Ruby 2.5.5
> Using Rails 5.2.3
> 
> and with both ruby versions I am getting the same problem when I execute the command:
> 
> ```
> rails server
> ```
> 
> ### Steps to reproduce
> 1. On a Raspberry Pi install rbenv using brew
> 
> ```
> brew install rbenv
> ```
> 
> 1. Then use the following command to install ruby
> 
> ```
> rbenv install 2.6.3
> ```
> 
> 1. Then install rails:
> 
> ```
> gem install rails -v 5.2.3
> ```
> 
> 1. Create a new folder to hold your application and go to that folder:
> 
> ```
> $ cd                  # Change to the home directory.
> $ mkdir environment     # Make a environment directory.
> $ cd environment/       # Change into the environment directory.
> ```
> 
> 1. Use rails to create the application inside the previous folde:
> 
> ```
> rails _5.2.3_ new hello_app
> ```
> 
> 1. Go to the recently created 'hello_app' folder
> 
> ```
> cd hello_app
> ```
> 
> 1. Start the rails server
> 
> ```
> rails server
> ```
> 
> ### Expected behavior
> ```
> pi@raspberrypi:~/environment/hello_app $ rails server
> => Booting Puma
> => Rails application starting on http://localhost:3000
> => Run `rails server -h` for more startup options
> => Ctrl-C to shutdown server
> ```
> 
> And then it should just stay there to be able to access the web app on the address indicated
> 
> ### Actual behavior
> First the output shows this:
> 
> ```
> pi@raspberrypi:~/environment/hello_app $ rails server
> => Booting Puma
> => Rails 5.2.3 application starting in development 
> => Run `rails server -h` for more startup options
> ```
> 
> And then the contents of the text file in the next link are shown.
> 
> Here is a link with the whole output:
> 
> https://www.dropbox.com/s/gjgo81zqeekfnvt/railsservererror.txt?dl=0
> 
> ### System configuration
> **Ruby version**: I´ve tried with both 2.6.3 and Ruby 2.5.5
> **Rails version**: I've tried with 6.0.0.rc1 and with 5.2.3
> **Puma version**: I've tried with 3.12.1 and a previous one too
> 
> I would really appreciate if someone could give me a hand to solve this problem.
> 
> Thanks,

you just need to go to routes file and remove the indentation of all the simple match routes ('two spaces of simple match routes')
