### ISSUE TITLE
Please prove me wrong - but I cannot get NGINX,Puma, and websockets to work together 

### ISSUE THREAD

**Issue by wdiechmann** [puma/puma#1804]
The comments below are originally posted a little while back - on _ https://github.com/puma/puma/issues/1189#issuecomment-493840826_

Since then I've done what I'd ask of anybody else - set up a project demonstrating that it (at least to me appears that it) doesn't work either with or without SSL. If anybody is up for battling this dragon, here is the _https://github.com/wdiechmann/sucker_ project

- What's worse: my websocket/puma/ nor ruby-fu for that matter is bad enough to take on this issue by myself :(

Obviously, I lean on the conclusion that there is some stupid detail that I keep missing - and if you can help me find that, I'll hurry back [to that stone from where I crawled](https://quotecatalog.com/quotes/movies/beverly-hills-cop/) [parafrazing Victor Maitland (the boss villain) in Beverly Hills Cop]

If on the other hand Puma just does not work with websockets at the moment - then perhaps you will know what other setup does?

-----8<---- 
original comment 

Any ideas what I'm to do? I'm seeing this in production on Rails 5.2.0 and Puma 3.11 - from this thread I was under the impression that the issue was only in development, and already solved?

My development env has ActionCable working ok - but when I deploy to production (with NgINX in front of puma with the conf below) this is what my log/production.log tells me

```
I, [2019-05-20T06:29:15.602963 #10201]  INFO -- : [35efda4b-0f24-4642-9c8f-b25fe7649f09] Started GET "/cable" for 92.246.28.33 at 2019-05-20 06:29:15 +0200
I, [2019-05-20T06:29:15.603595 #10201]  INFO -- : [35efda4b-0f24-4642-9c8f-b25fe7649f09] Started GET "/cable/" [WebSocket] for 92.246.28.33 at 2019-05-20 06:29:15 +0200
I, [2019-05-20T06:29:15.603693 #10201]  INFO -- : [35efda4b-0f24-4642-9c8f-b25fe7649f09] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
D, [2019-05-20T06:29:15.607244 #10201] DEBUG -- :   User Load (1.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 1 LIMIT 1
I, [2019-05-20T06:29:15.608120 #10201]  INFO -- : [ActionCable] [supervip] Registered connection (Z2lkOi8vc3BlaWNoZXIvVXNlci8x)
I, [2019-05-20T06:29:26.794676 #10201]  INFO -- : [ActionCable] [supervip] Finished "/cable/" [WebSocket] for 92.246.28.33 at 2019-05-20 06:29:26 +0200
I, [2019-05-20T06:29:28.108587 #10201]  INFO -- : [99ab0747-3fcb-4440-a527-3e92a542a2f2] Started GET "/cable" for 92.246.28.33 at 2019-05-20 06:29:28 +0200
I, [2019-05-20T06:29:28.109198 #10201]  INFO -- : [99ab0747-3fcb-4440-a527-3e92a542a2f2] Started GET "/cable/" [WebSocket] for 92.246.28.33 at 2019-05-20 06:29:28 +0200
I, [2019-05-20T06:29:28.109291 #10201]  INFO -- : [99ab0747-3fcb-4440-a527-3e92a542a2f2] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
D
```

In Chrome this is what I see:

```
WebSocket connection to 'wss://speicher.ltd/cable' failed: WebSocket is closed before the connection is established.
```

My NgINX conf:

```
# Upstream server (Puma socket)
upstream speicher {
  server unix:/var/www/speicher/shared/tmp/sockets/puma.sock;
}

# Config for vhost
server {
  listen 80;
  server_name speicher.ltd;
  return 301 https://$host$request_uri;
 }
 server {
  listen 443 ssl; # managed by Certbot
  server_name speicher.ltd;
  client_max_body_size 4G;

  access_log /var/log/nginx/speicher.access.log;
  error_log /var/log/nginx/speicher.error.log;

  root /var/www/speicher/current/public;

  # direct to maintenance if this file exists
  if (-f $document_root/system/maintenance.html) {
    rewrite  ^(.*)$  /system/maintenance.html last;
    break;
  }

  ssl_certificate /etc/letsencrypt/live/speicher.ltd/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/speicher.ltd/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

  # assets caching
  location ~ ^/(assets)/ {
    access_log  off;
    # gzip_static on;
    expires     max;
    add_header  Cache-Control public;
    add_header  Last-Modified "";
    add_header  ETag "";

    open_file_cache          max=1000 inactive=500s;
    open_file_cache_valid    600s;
    open_file_cache_errors   on;
    break;
  }

  # serve static file directly
  try_files $uri/index.html $uri @speicher;

  # App proxying
  location @speicher {
    proxy_redirect     off;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   Host $host;
    proxy_set_header   X-NginX-Proxy true;
    proxy_set_header   Connection "";
    proxy_http_version 1.1;
    proxy_pass         http://speicher;
  }

  location /cable {
    proxy_pass http://speicher;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }


  error_page 500 502 503 504 /500.html;
  keepalive_timeout 10;

  location = /favicon.ico {
    expires    max;
    add_header Cache-Control public;
  }
}

```

_Originally posted by @wdiechmann in https://github.com/puma/puma/issues/1189#issuecomment-493840826_

**Comment by toxaq** [comment]
Looking at your config the only difference to mine that stands out is your Connection "upgrade". I'm using what is shown in this StackOverflow answer

https://stackoverflow.com/a/15198581/97429

My websockets with faye work fine. Although I'm trying to get to the bottom of a hung thread issue which prevents me from reliably restarting the server and leads to eventual death of all responses if not restarted every few days.

**Comment by wdiechmann** [comment]
thx for chipping in @toxaq - I really appreciate (and if you can confirm running websockets exactly like my sucker demo - and like how the Rails documentation is prescribing - then I'm in serious serious trouble) 


The

```
# config/sucker.nginx.conf
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
...
  location /cable {
    proxy_set_header    Upgrade     $http_upgrade;
    proxy_set_header    Connection  "upgrade";
    ...
  }
```
changed, alas, nothing :(

**Comment by toxaq** [comment]
Looks like you're missing the Connection change?
    
    proxy_set_header Connection $connection_upgrade;

**Comment by toxaq** [comment]
I'm using faye but with websockets

    location /faye {
        proxy_pass http://my_puma;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;
      }

**Comment by wdiechmann** [comment]
faye?

I don't see the action cable having any requirement using faye?

**Comment by wdiechmann** [comment]
hmmm - and even with the 
```
proxy_set_header Connection $connection_upgrade;
```

I still see 

```
WebSocket connection to 'ws://sucker.alco.dk/cable' failed: WebSocket is closed before the connection is established.
```
in my DevTools in Chrome :(

**Comment by toxaq** [comment]
ActionCable has no dependency on Faye but does (or did) use the websocket library from the project. My point is that whilst we don't have identical configurations I have been successfully running websockets, fronted by nginx through to Puma. I'm guessing there is something else. It's finicky with SSL to get going that first time but it does work.

**Comment by toxaq** [comment]
Shouldn't `ws://sucker.alco.dk/cable` be wss ? Two s's? Since everything is SSL?

**Comment by wdiechmann** [comment]
so true - on all accounts :)

(but as I understand it, action_cable "should" work with ws as well - or is that where i'm getting it all wrong! 

Good to know that the NGiNX proxying infront of Puma part of it does in fact work 👍

**Comment by wdiechmann** [comment]
This project met with a happy ending - eventually :)

I've committed all the changes to the https://github.com/wdiechmann/sucker project.

Please allow me to excuse to anybody who are left feeling insulted by my brash style! 

The gist of it was: when I started from the top, built a fresh CentOS virtual machine, and disabled SELinux, suddenly everything was dandy!

(I sure would have loved to point a finger at that 'WebSocket closed before...' message in my DevTools console, but that will have to be another time)

cheers,
Walther
