### ISSUE TITLE
Rev the minimum Ruby Version >= Ruby 2.5

### ISSUE THREAD

**Issue by schneems** [puma/puma#1811]
I'm proposing we raise the default Ruby version to 2.5 which allows us to rescue inside of a block as well as some other niceties such as `match?`. Rails 6 targets 2.5+, as well as the sprockets beta. 

2.2 and 2.3 are already EOL. 2.4 will be EOL come this december.

Pros: Use latest language features for fun and performance.
Cons: Customers stuck on older rubies or older rails versions cannot use.

What do you think? In the process of this conversation, maybe we can make an official upgrade policy.

If we update to 2.5, I would say that we will guarantee to support the last 2 major releases, and may choose to support further back as we see fit, so when 2.7 comes out we would guarantee support of 2.6 and 2.7 and it would be up to us to continue maintenance of 2.5.

**Comment by nateberkopec** [comment]
> If we update to 2.5, I would say that we will guarantee to support the last 2 major releases, and may choose to support further back as we see fit, so when 2.7 comes out we would guarantee support of 2.6 and 2.7 and it would be up to us to continue maintenance of 2.5.

Proposed policy works for me.

**Comment by mperham** [comment]
FWIW Sidekiq's official policy is to match Rails major.  Sidekiq 5 is Ruby 2.2.2+, just like Rails 5.  Sidekiq 6 will be Ruby 2.5+ just like Rails 6.

**Comment by schneems** [comment]
Going to re-open for now. We might revert. There's some discussion happening off of GitHub, once that's settled I'll post back the results.

**Comment by schneems** [comment]
After talking about it we decided to be less aggressive setting minimum ruby versions (for now). Setting a minimum version like this would force us to support multiple releases which we're currently not doing. 

Our policy is currently: We maintain and support the latest release of Puma. We will provide best effort to support older versions of Rubies but we reserve the right to change our supported versions at any time, for the foreseeable future we'll at least support non EOL versions of Ruby, though we may support older versions as well. If we get to be a larger team or if there is significant feature work in the future then we might need a more specific policy.
