### ISSUE TITLE
'Can't open page' error on when accessing from mobile phone on 3.12.1

### ISSUE THREAD

**Issue by brenogazzola** [puma/puma#1819]
### Steps to reproduce

1) Create a new rails project and set puma version to 3.12.0
2) Start the server and access it from mobile phone.
3) Update puma to 3.12.1
4) Start the server and access it from mobile phone.

### Expected behavior

The page 'Yay! You are on Rails' should appear in steps 2 and 4;

### Actual behavior

On step 4 the browser displays the error message: `Safari cannot open the page because it could not connect to the server`

### System configuration

**Ruby version**: 2.6.3
**Rails version**: 6.0rc1
**Puma version**: 3.12.1
**Browser**: iOS Safari

**Comment by nateberkopec** [comment]
See https://github.com/puma/puma/pull/1699
