### ISSUE TITLE
Errno::ENAMETOOLONG: Filename too long

### ISSUE THREAD

**Issue by K-Sato1995** [puma/puma#1823]
I'm using puma with nginx and docker and getting the error below.
What are the possible causes of the error??

```
app_1          | Puma starting in single mode...
app_1          | * Version 3.12.1 (ruby 2.5.3-p105), codename: Llamas in Pajamas
app_1          | * Min threads: 5, max threads: 5
app_1          | * Environment: development
app_1          | * Listening on tcp://0.0.0.0:3000
app_1          | bundler: failed to load command: puma (/bundle/bin/puma)
app_1          | Errno::ENAMETOOLONG: Filename too long - connect(2) for /app_path/tmp/sockets/puma.sock
app_1          |   /bundle/gems/puma-3.12.1/lib/puma/binder.rb:371:in `initialize'
```

**Comment by nateberkopec** [comment]
Looks like the unix socket you're connecting to has a really long name. [See here](https://github.com/puma/puma/blob/master/lib/puma/binder.rb#L368).

You can post your config and we may be able to help more. But the only solution would be to make that shorter. I think the limit is set by the OS.

**Comment by K-Sato1995** [comment]
@nateberkopec 
Thanks for the quick response.

Here is my `config/puma.rb`(I'm using rails).

```
threads_count = ENV.fetch('RAILS_MAX_THREADS') { 5 }
threads threads_count, threads_count

port        ENV.fetch('PORT') { 3000 }

environment ENV.fetch('RAILS_ENV') { 'development' }
plugin :tmp_restart

app_root = File.expand_path("../..", __FILE__)
bind "unix://#{app_root}/tmp/sockets/puma.sock"
```

The path to the socket is something like `app/tmp/sockets/puma.sock`.  
Don't think this is considered to be too long.

Am I missing something?

**Comment by dentarg** [comment]
> Looks like the unix socket you're connecting to has a really long name. [See here](https://github.com/puma/puma/blob/master/lib/puma/binder.rb#L368).

Permalink version: https://github.com/puma/puma/blob/c242e76f4d14dd7582ce27062c6b0d26ff4abaf5/lib/puma/binder.rb#L368

**Comment by Jesus** [comment]
According to your config file it's an absolute path because `File.expand_path("../..", __FILE__)` will return an absolute path, this may be short or long depending on the location of the Ruby script being executed.

What's the absolute path to your Rails app?

**Comment by K-Sato1995** [comment]
@Jesus 
I'm using Docker. It's not the actual path on my project but the path is very similar to `app/application_name/tmp/sockets/puma.sock`.

The exact error message I'm getting is this. (I modified the path.)

```
bundler: failed to load command: puma (/bundle/bin/puma)
Errno::ENAMETOOLONG: Filename too long - connect(2) for `app/application_name/tmp/sockets/puma.sock
bundle/gems/puma-3.12.1/lib/puma/binder.rb:371:in `initialize'
```

**Comment by nateberkopec** [comment]
🤷‍♂ I mean, whatever it is, it's too long I guess. Would a relative path work, I wonder? What OS are you on exactly?

**Comment by K-Sato1995** [comment]
@nateberkopec @dentarg @Jesus 

We changed the configuration of our Dockerfile and we are not getting the error anymore.

We're still not sure what exactly was causing the error but guessing the problem was how we configured our Dockerfile, not puma. 

Thank you very much for your time.
Really appreciate it.
