### ISSUE TITLE
Puma removing socket after graceful restart since 4.0

### ISSUE THREAD

**Issue by tbk303** [puma/puma#1834]
We are launching Puma like this on a Rails app:

```
puma -b unix:///home/deploy/app/shared/tmp/sockets/puma.sock -C config/puma.rb --dir /home/deploy/app/current --pidfile /home/deploy/app/current/tmp/pids/puma.pid
```

And during deployment, we issue a graceful restart command like this:

```
pumactl -P /home/deploy/app/current/tmp/pids/puma.pid restart
```

Our logfiles indicate that Puma is properly doing a graceful restart and outputs info about running workers afterwards, but the socket file has disappeared after the restart.

This has worked in the latest 3.12 versions and started happening with 4.0

**Comment by nateberkopec** [comment]
Thanks - please see #1775.

**Comment by tbk303** [comment]
Sorry, did not find that one...
