### ISSUE TITLE
Unable to retrieve body from "Transfer-Encoding: chunked" request

### ISSUE THREAD

**Issue by dpalumbo** [puma/puma#1839]
Does Puma support `Transfer-Encoding: chunked`? Recent PRs make me think it does, but I can't find a clear answer. I'm able to receive the request but the body content is empty.

1) Send a POST request with chunked encoding. 
```
curl -H "Transfer-Encoding: chunked" -H "Content-Type: application/json" -d '{"abc": "123"}' -X POST http://localhost:3000/aendpoint
```

2) Check value of raw body received in a Rails controller: 
```ruby
request.raw_post
""
```

I've seen these PRs: 
https://github.com/puma/puma/pull/1607
https://github.com/puma/puma/pull/1812

But it's not clear to me if they solve the issue of receiving the body of a POST.

### Expected behavior

Body should be populated with data

### Actual behavior

Body is empty

### System configuration

**Ruby version**:  2.5.0
**Rails version**: 5.2.2
**Puma version**: 4.0.0

**Comment by hahmed** [comment]
Hey @nateberkopec 

I looked into this issue, does not look like an issue with puma -- I suspect its a rails bug (managed to repro, just seeing if I can find a fix for it).

1. create rack file and run `bundle exec bin/puma -t 5 test/rackup/chunked-post.ru & PID1=$!`
```
run lambda { |env|
  STDERR.puts env['rack.input'].read # => {"abc": "123"}
  [200, {"Content-Type" => "application/json"}, [""]]
}
```
2. send post chunked request (below) --  the output is correctly coming through via puma
`curl -H "Transfer-Encoding: chunked" -H "Content-Type: application/json" -d '{"abc": "123"}' -X POST http://localhost:9292`

I can see a few tests for post chunked requests, none with `application/json` not sure if we need it? but let me know if we do (we also don't have a form post chunked test too)

**Comment by hahmed** [comment]
Here is a repro of the issue https://github.com/hahmed/chunk-puma-test -- hope this clears up why I think this is a rails issue and not a puma issue
