### ISSUE TITLE
`clear_cache_if_necessary': undefined method `execute_if_updated' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Siwarr** [puma/puma#1843]
i excute this command in terminal
 rails generate migration add_user_id_to_docs user_id:integer

i don't know why i get this error

### System configuration

**Ruby version**: 2.6.3
**Rails version**: 6.0.0rc1
**Puma version**: 3.12.1
any help please ?

**Comment by nateberkopec** [comment]
This is not a problem with Puma. Please ask for help in Rails-related IRC channel or other support group.
