### ISSUE TITLE
UNIXSockets - possible copy/paste error in Binder#inherit_unix_listener

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1856]
While reviewing all the code involving UNIXSockets, etc, I noticed the following:

https://github.com/puma/puma/blob/099a4476a3e27dce83d63e890e3150d05666ef2f/lib/puma/binder.rb#L398-L405

Note line 401.  The commit is at https://github.com/puma/puma/commit/32088ec6ed30dd09069e42c10a73e9fc3ed93688, I'm wondering if it's a copy/paste mistake, and hence,

```ruby
if fd.kind_of? TCPServer
```

should be:

```ruby
if fd.kind_of? UNIXServer
```

I could add to PR #1851

**EDIT:** I pushed the change to the PR

**Comment by nateberkopec** [comment]
@evanphx's [comment at the time](https://github.com/puma/puma/pull/231#issuecomment-18757133) seems to indicate this was intentional, but likely a misuse/over-extension of the method.

**Comment by MSP-Greg** [comment]
Ok, maybe I need to reread PR #231...

I'm wondering if line 402 is ever executed.  I pushed the change, tests passed.

If `fd` is a UNIXServer, and hence the current code runs the `else` code, `UNIXServer.for_fd` creates a new object, which should fail if one already exists?

The only place I can find `Binder#inherit_unix_listener` being called is here:

https://github.com/puma/puma/blob/099a4476a3e27dce83d63e890e3150d05666ef2f/lib/puma/binder.rb#L118-L126

So how does a TCPServer get thru that, or why is a TCPServer associated with a UNIX URI?

Wonder if we need test coverage info for a while just to get things straightened out...

**Comment by MSP-Greg** [comment]
Closing, See Issue #1881
