### ISSUE TITLE
test/test_http11.rb - stability

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1869]
Recently, there was a failure in an Appveyor job that halted the testing. It occurred in `Http11ParserTest#test_horrible_queries`.  The method is below.

Looking at the code, the `parser.reset` statements are never executed since an error is raised in the statement preceding them.  So, I moved all of them to where they would be executed.

Ran it in my fork, and now some of the `assert_raises` are not triggered, which implies an error is not being raised.  So, are some of the 'rand' minimums set to  low (or something)?  Confused, and my knowledge of http protocol is not up to this issue...

**EDIT:** the new failed `assert_raises` statements all happened in the loop containing line 162...

https://github.com/puma/puma/blob/31d91c351a2bdd4d1aad3ec5434ae3da8306a8ae/test/test_http11.rb#L147-L183

**Comment by dentarg** [comment]
How can one reproduce the failures @MSP-Greg?

**Comment by MSP-Greg** [comment]
@dentarg 

See my fork, commit here: https://github.com/MSP-Greg/puma/commit/232e088f76c55d580e696a821c616cffeebd1c5e

Travis: https://travis-ci.org/MSP-Greg/puma/builds/565613341

AppVeyor: https://ci.appveyor.com/project/MSP-Greg/puma/builds/26350320

**Comment by MSP-Greg** [comment]
See Travis build above, if this is an issue, it is not Windows specific...

**Comment by nateberkopec** [comment]
Hasn't been an issue for a while
