### ISSUE TITLE
systemd, Binder#import_from_env, Binder#inherit_unix_listener

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1881]
Recently came across some odd code, so I've got a question.  In `Binder#import_from_env`, the following code exists:
https://github.com/puma/puma/blob/6b13202a6f607b9b4ccb75e1864d7be75b537290/lib/puma/binder.rb#L66-L89

`ENV['PUMA_INHERIT']` is created by Puma for restarts and loads `@inherited_fds`.
`ENV['LISTEN_FDS']` is used by systemd and loads `@activated_sockets`.

If the code in lines 74 thru 76 does not raise an error, `@inherited_fds` has a key/value pair set where the key implies a UNIXSocket, but the value is a TCPServer.  Now going to `Binder#inherit_unix_listener`:

https://github.com/puma/puma/blob/6b13202a6f607b9b4ccb75e1864d7be75b537290/lib/puma/binder.rb#L398-L406

I'm wondering if line 402 should be changed to:
```
s = UNIXServer.new path
```

I don't believe systemd is checked in any tests, I can't test locally, so I opened the issue...

**Comment by nateberkopec** [comment]
This was brought up at the time when Evan merged it. I'm looking at this now and I'm not sure it's an issue.

**Comment by nateberkopec** [comment]
#1976 possibly related tho
