### ISSUE TITLE
How do I route a request path to a single dedicated thread?

### ISSUE THREAD

**Issue by midnight-wonderer** [puma/puma#1895]
Hi there,  
I have a problem that I don't know where to look for the resolution.  
So I came here to get some pointers.  
  
I have a Rails application that under some complicated circumstances, need to call an external service that fetches more data from the application itself via another HTTP call.
(Simply put, an application with cyclic HTTP calls)

There is no other obvious way around it business-wise, and the call cannot be made asynchronous. (Like using ActiveJobs)

These can cause a deadlock on the production server.

One way to prevent the deadlock is to dedicate a single thread to that specific Rails action, allowing external service to fetch the data.
So it is guaranteed there is always a thread available to handles that particular action. 

I wonder how do I accomplish this with Puma?
Or this does not related to Puma at all?

**Comment by nateberkopec** [comment]
"How can I safely make a request to myself when running multi-threaded" is a common question. Usually our answer is "run single threaded, use JRuby, or just don't do that".

**Comment by midnight-wonderer** [comment]
Hey @nateberkopec  
I could not comprehend why using JRuby would prevent the lock in any way, so I try looking for more references.  
  
I found that you explained this phenomenon in 2018; Let me make a quote

> You have an application with two workers, Worker A and Worker B. Worker A makes a request to itself (localhost:3000 or whatever). As soon as this happens, thanks to Puma's multithreaded Reactor architecture, Worker A's thread releases the GVL and is "free".
>
> The reason this doesn't happen in Unicorn is because Worker A would never go back and listen again on the socket, but in Puma, it will. Worker A tries to connect to itself, and voila, a lock.

The part that I don't understand is:  
Why would a worker connecting to themselves form a lock in the multi-threaded setup?  
  
Since the former request has released the GVL, another thread from the same worker should be able to handle the latter request without forming a lock no?

**Comment by oshanz** [comment]
@midnight-wonderer I'm facing the same issue. now thinking of make first part of logic async ([suckpunch](https://github.com/brandonhilkert/sucker_punch)) and then send to client using socket connect (Action Cable)
- JRuby threads are os kernel threads without any locking mechanism from JVM.
