### ISSUE TITLE
What's the meaning of `CXN` ?

### ISSUE THREAD

**Issue by justqyx** [puma/puma#1907]
Hi, I was confused by the `CXN` words when I read the [architecture document](https://github.com/puma/puma/blob/master/docs/architecture.md). After read the source code I can't find any words that maybe related to the `CXN`. Anyone can explain what it's meaning or tell me the full form of `CXN` ?

![puma-connection-flow](https://user-images.githubusercontent.com/1448539/62858387-c900e300-bd2c-11e9-8179-06791f6a6306.png)

**Comment by justqyx** [comment]
@eprothro I found this document is created by you, could you pls to answer this quest?

**Comment by nateberkopec** [comment]
Connection.

I wonder what a better way to label those boxes could be ... connection is a long word and would probably not fit in the diagram.

**Comment by eprothro** [comment]
@justqyx Nate is correct, it stands for connection.

**Comment by justqyx** [comment]
@nateberkopec @eprothro thanks. :blush:
