### ISSUE TITLE
Use a 2048-bit Diffie-Hellman group

### ISSUE THREAD

**Issue by seandilda** [puma/puma#1921]
A puma server gets the 'This server supports weak Diffie-Hellman (DH) key exchange parameters. Grade capped to B.' warning from SSL Labs.  (https://weakdh.org/)

As best I can tell, the 1024 bit params are hard coded in ext/puma_http11/mini_ssl.c

I tested this on puma 4.1.0 on ruby 2.6.3p62

**Comment by nateberkopec** [comment]
Great idea!
