### ISSUE TITLE
Testing - global constants

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1929]
While running tests to check for intermittent issues, I came across something that I had fixed locally, but never added to a PR:

https://github.com/puma/puma/blob/1046165a9c8766ce5c1db8db4d894e200f4c981c/test/test_puma_server_ssl.rb#L206-L208

Line 207 should be `port = UniquePort.call`.  Along with it, I noticed line 208, which is set in many test files.

Question - should  `127.0.0.1` be made a 'global' test constant, and if so:

1. Name - `HOST4`, `IP4`, or something else?  We want both short and clear, and we may add IPv6 tests in the future...

2. Where to put it?  For now, maybe just add it to the code below?

https://github.com/puma/puma/blob/1046165a9c8766ce5c1db8db4d894e200f4c981c/test/helper.rb#L121-L126

**Comment by nateberkopec** [comment]
I think the string is clearer than a constant, yeah? If you had never seen Puma's tests before, what you *guess* HOST4 or IP4 was? IDK if I could guess 127.0.0.1

**Comment by MSP-Greg** [comment]
I'd agree.

I have a knee jerk reaction to always creating constants for repeated strings.

But, for instance, what if I had an app running on 127.0.0.1 locally, and wanted to test Puma?  With the current code, it would really be a pita to change that...  That's the main reason I brought it up.

Also, assuming we may be able to start using more shared test methods in `helper.rb` or another file, adding some constants there isn't much of a change, as anyone writing tests should be (at least briefly) reviewing the file...
