### ISSUE TITLE
macOS - intermittent failures - test_sigterm_closes_listeners_on_forked_servers

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1930]
Current Travis macOS CI is having intermittent failures in the
TestIntegration#test_sigterm_closes_listeners_on_forked_servers test.  Below is a section of the code from  commit https://github.com/puma/puma/commit/184e1510a97c236c6b7ab345e6508559f757045a (the line numbers are different than master).

https://github.com/puma/puma/blob/b823060002bf9f7037961b5a1c95aa4e58e478fb/test/test_integration.rb#L165-L177

Line 166 calls a method that creates a TCPSocket and the writes to it.  The write statement  intermittently raises `Errno::EPIPE: Broken pipe`.

Line 167 calls a method that reads from the socket.  The error here is `EOFError: end of file reached`.

The rescue statement on line 173 is the 'passing' error rescue.

Not knowing that much about the 'client' TCP error handling, should either of the above errors be added to the rescue clause?  If so, it may not eliminate the intermittent CI failures, but anything to reduce the frequency...

@schneems, sorry for the ping, any thoughts?

Note: the code listing above is from PR #1925

**Comment by nateberkopec** [comment]
I believe this test is now called `#test_term_closes_listeners`. But the fail still exists.

**Comment by nateberkopec** [comment]
This is fixed in Github Actions + our new tests, haven't seen a fail there yet.
