### ISSUE TITLE
CETP and Puma not works

### ISSUE THREAD

**Issue by dmtask** [puma/puma#1936]
Hi,

I need to connect a CETP (Connector Event Transport Protocol) interface to a Rails system. It uses Puma as server and now I have the problem that I get the following error when sending the request: `2019-08-28 16:03:19 +0200: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`

The problem is that the CETP request simply returns plain XML (a valid HTTP header is missing) and the HTTP server can't do anything with it. At least that's what my research via Wireshark showed. Now my question, can you set Puma to ignore this check or is there any other way to process the requests? Unfortunately there is no option to ask the manufacturer of the interface, they don't change anything.

**XML Structure from Request:**
```
CETP....
<Event xmlns="****">
    <Topic>****</Topic>
    <Type>****</Type>
    <Severity>****</Severity>
    <SubscriptionID>****</SubscriptionID>
    <Message>
        <Parameter>
            <Key>*****</Key>
            <Value>*****</Value>
        </Parameter>
        .....
    </Message>
</Event>
HTTP/1.1 400 Bad Request
```

**Route in Rails:**
`post 'card_reader/read_via_cetp', to: 'card_reader#read_via_cetp'`

### System configuration

**Ruby version**: 2.6.3p62
**Rails version**: 5.2.3
**Puma version**: 4.0.0

**Comment by dentarg** [comment]
Can you reproduce this without Rails? For example a curl command that does the request against vanilla Puma. I think that would be helpful to understand what's going on.

**Comment by nateberkopec** [comment]
> The problem is that the CETP request simply returns plain XML (a valid HTTP header is missing) and the HTTP server can't do anything with it.

Puma is an HTTP server - we can't do anything with a malformed request. My advice would be to put something else in front of Puma that can modify the response and give Puma what it needs.

**Comment by Jesus** [comment]
Hi @dmtask,

you might be interested in adding a layer to handle CETP and running Puma in TCP mode.

Unfortunately looks like TCP mode isn't documented, but basically it lets you run the server without the HTTP parser.

I've added #1937 to acknowledge that this piece of doc is missing.

**Comment by dmtask** [comment]
@nateberkopec Yes, I know, but unfortunately don't solve my problem...
@Jesus Thanks a lot, that sounds good and I think I can work with that. I'll try that right away.

**Comment by dmtask** [comment]
Info: I could solve my problem with a node.js TCP socket server.
