### ISSUE TITLE
Puma 4.1.0 very slow with failing requests

### ISSUE THREAD

**Issue by brauliobo** [puma/puma#1939]
With Puma 3.8.2 a case where the endpoint return 404 takes about 50ms to complete the request.
By upgrading only puma (no other gems) from 3.8.2 to 4.1.0, this same request take at least 8s, many times 14s or more.
Other erroring (400 or 500 codes) are also slow, although not all of them.

We are using ELB classic and Nginx in front of Puma. Sinatra is the base Rack application.
We could really isolate the revert of the puma gem upgrade to fix the slowdown.

We could not reproduce this in a small sample application.

**Comment by nateberkopec** [comment]
We’re going to need a lot more information, unfortunately. That’s years of Puma code in between those two versions. If you could try other versions and see which version first displays the issue, that would help a lot. And of course, a reproducing application.



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nateberkopec** [comment]
Closing. If you can create a reproducible example, please open a new issue.
