### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rus-max** [puma/puma#1940]
./shared/bundle/ruby/2.6.0/gems/puma-4.1.0/lib/puma/cluster.rb:166: [BUG] Segmentation fault at 0x00000000000004c8
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

-- Machine register context ---------------------------------------------
---
 RIP: 0x00007f96cd825c56 RBP: 0x00007f96cd161338 RSP: 0x00007f964807df00
 RAX: 0x0000000000000000 RBX: 0x000000000732def0 RCX: 0x00007f964807e700
 RDX: 0x00007f96ba01a810 RDI: 0x000000000732def0 RSI: 0x00007f96cd744b28
  R8: 0x000000000732df50  R9: 0x0000000000000000 R10: 0x00007f964807deb0
 R11: 0x0000000000000206 R12: 0x0000000000000000 R13: 0x00007f96cd1612c8
 R14: 0x0000000000000004 R15: 0x00007f964807ec18 EFL: 0x0000000000010206

-- C level backtrace information ----------------------------------------
--

### System configuration

**Ruby version**: 2.6.3
**Rails version**: 5.2.3
**Puma version**: 4.1.0

**Comment by dentarg** [comment]
I guess this needs a repro, not much to go on here

**Comment by nateberkopec** [comment]
https://github.com/puma/puma/blob/v4.1.0/lib/puma/cluster.rb#L166

That's the line where we fork your workers. Pretty much anything could have caused this, we need more info.

**Comment by nateberkopec** [comment]
Closing. If you can create a reproducible example, please open a new issue.
