### ISSUE TITLE
Make "puma-heroku" the default config

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1949]
The gem is a bit misnamed, it's just "good practices in config". I think we could mainline most of the settings in there for 5.0 and sunset the gem.

**Comment by olleolleolle** [comment]
The items in [puma/puma-heroku](https://github.com/puma/puma-heroku/blob/master/lib/puma/plugin/heroku.rb) to be moved into [lib/puma/configuration.rb](https://github.com/puma/puma/blob/master/lib/puma/configuration.rb) could include:

- [ ] Worker Count via ENV variable where supported: query the environment variable `WEB_CONCURRENCY` (default: 1) for workers count (unless JRuby or Windows, then do not set it)
- [ ] if using workers, preload the app
- [ ] Set min and max threads via ENV variable(s): min_threads, max_threads set to `Integer(ENV['RAILS_MAX_THREADS'] || ENV['MAX_THREADS'] || 5)` (perhaps w/ a RAILS_MIN_THREADS, too?)
- [ ] Listen to RAILS_ENV for environment: `:environment => -> { ENV['RACK_ENV'] || "development" },` to also include `ENV['RAILS_ENV']`
- [ ] Rails 5.2 and lower: pre-fork & on_worker_boot database connecting

Any these items that have higher priority?

**Comment by olleolleolle** [comment]
@nateberkopec From memory: I've only used it because the option setting was there, and then used the same values for "max". Merging them into one useful setting: a good thing.

**Comment by nateberkopec** [comment]
Also re: Set min and max threads via ENV variable(s): min_threads, max_threads set to Integer(ENV['RAILS_MAX_THREADS'] || ENV['MAX_THREADS'] || 5) (perhaps w/ a RAILS_MIN_THREADS, too?)

We should keep the default of 16 on non-MRI platforms - so we should use a new default of 5 on MRI only.

**Comment by jalevin** [comment]
Was having issues getting all tests to run locally. need to add to history / docs #2143

**Comment by ukolovda** [comment]
Hello!
Also it will be useful in Docker containers. 
I need setup default parameters from environment variables, not from command-line parameters.
