### ISSUE TITLE
[Bug] External term of worker PID broken

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1950]
@nateberkopec

I saw you mention that you wanted to release an updated gem.  There were a few things gnawing at me:

1. Concern for whether the 'stuck' workers tests I wrote in test_integration.rb were really correct.  It's a tricky thing to mimic/mock, and the current implementation is somewhat indeterminate.

2. Changing the two stuck worker tests to use a cli based server, which, by not doing so, was interfering with running test_integration.rb parallel.

End result is that an external TERM signal sent to a worker is not being handled correctly.  I've got code to fix it, but I tested on top of something similar to PR #1925 in GitHub Actions.

So, I need to bring the 'lib' code back into master, see if it works (it should), and do another PR. 

I need to go AFK for a bit... Sorry...

**EDIT:** Done, see PR #1952

**Comment by nateberkopec** [comment]
Fixed in #1952.
