### ISSUE TITLE
Restarting process with USR2 doesn't always work

### ISSUE THREAD

**Issue by grk** [puma/puma#197]
I've deployed Puma on production a few days ago, and noticed that after some deploys we have to kill -9 puma processes and start a new master.

Our setup is the following:
- ruby 1.9.3p374 from rvm
- rails 3.2.12
- puma 2.0.0.b6

We're running Puma with `bundle exec puma 
-C /path/to/config -e production --dir /path/to/current -p 8888 
--pidfile /path/to/pidfile -d 2>&1 >> /path/to/log`

config is:

```
threads 5, 20
workers 20
activate_control_app 'tcp://127.0.0.1:8889'
```

On some restarts with USR2, I get a few worker processes failling to close. I ran strace on them, some are looped in `sched_yield`, and some give this output:

```
Process 7374 attached - interrupt to quit
futex(0x23ff5b4, FUTEX_WAIT_PRIVATE, 3, NULL
```

I also observed strange behaviour on those restarts that seem to succeed. There are 'waves' of requests that show up in log, then they stop, and after a few seconds I get ActiveRecord messages that db connection was established.

What would be next steps for debugging this? I should probably have something in the `on_restart` hook, but not sure what.

**Comment by nachogiljaldo** [comment]
I just noticed this issue and mine might be similar: #649

**Comment by yaminil** [comment]
Any updates on this issue team? It's creating huge issues in production envrionment
Thanks!

**Comment by dentarg** [comment]
@yaminil please open a new issue where you describe how the problem can be reproduced 

this bug is from 2013 and closed (with last comment from 2015) so I wouldn't expect any updates here
