### ISSUE TITLE
Test Reorganization

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1971]
1. Cluster Integration Tests - Two recent concerns are correct handling of unlinking UNIXSocket files and requests being handled correctly during 'stop'.  Regarding controlling Puma, the code paths are different dependent on whether control is via a socket or via a signal.  So, a 'full matrix' would have the following:<br/><br/>Server Bind: TCP, UNIX<br/>Server Control: TCP, UNIX, Signal<br/><br/>I'm not suggesting all tests be performed on all six combinations, but there certainly some critical tests that should be tested on more than the current two.  This would require changing the arguments for `cli_server` and `cli_pumactl`, allowing code to be shared between tests.<br/><br/>Maybe two kwargs - `bind:` & `ctrl:` for `cli_server`, and `ctrl` would set an instance variable so `cli_pumactl` would sense it?

2. `TestIntegrationPumactl#cli_pumactl` (test_integration_pumactl.rb)  - Rather than spinning up `ruby  pumactl`, should we just use `Puma::ControlCLI.new(<args>).run`?  Any IO issues?

3. test_cli.rb - Given that every call to `cli_server` is using Puma::CLI, I don't see a reason to start Puma in its tests.  But, since breakage in it will cascade to other tests, testing using its instance variables, etc is certainly a good idea.  May need to run up a server to test Puma::Events.  Maybe add a test_events.rb file?

Thoughts?

**Comment by nateberkopec** [comment]
Re: 1, great point. two kwargs makes sense.

2. I think we need a few test for "full up integration" of the ControlCLI. If removing that one would mean there are no tests that run a real control process, then we should not remove it. Otherwise, we can.

3. More tests is always better!

**Comment by MSP-Greg** [comment]
Cool.  Given the rebasing and dicing/chopping I've done with current code changes, I'd like to get a few PR's merged before I start on these changes.

**Comment by MSP-Greg** [comment]
Re point 2, I did say 'Any IO issues?'

After wrestling with #1973, yes, there are IO issues.  I started with a simple test and `Puma::ControlCLI.new(<args>).run`.  No, just no.  There's some IO mapping in Puma::ControlCLI, and tests just got weird.  So, we should stick with `cli_pumactl`...

**Comment by MSP-Greg** [comment]
Once we get the current set of PR's merged, I will start working on this.  After some more thought, the above:

Server Bind (bind: kwarg): TCP, UNIX
Server Control (ctrl: kwarg): TCP, UNIX, Signal

should be:

Server Bind (bind: kwarg): :TCP, :UNIX
Server Control (ctrl: kwarg): :TCP, :UNIX, :state, :pid

My thinking is that both are passed to `cli_server`, it sets up everything so they aren't needed for `cli_puma_ctl`, and it's just passed the command?  Also, since `test_integration_cluster.rb` and `test_integration_single.rb` should have some (or all) tests using `cli_puma_ctl`, it should be moved to `helpers/integration.rb`?

Thoughts?

**Comment by MSP-Greg** [comment]
See [Gist MSP-Greg/puma_new_test_methods.rb](https://gist.github.com/MSP-Greg/78976afc41247a452667e2071a3020d6) for a draft (just RuboCop'd it) of new`cli_server` & `cli_pumactl` methods.

If you get a chance to look at it, wondering in general and also whether I've forgotten anything in the two methods or setup/teardown.  I haven't given much thought to additional methods yet...

**Comment by nateberkopec** [comment]
Novel concept. I don't have quite the time to tell you whether or not you've missed anything, but the way you've setup the instance variables and named them looks good to me.

**Comment by MSP-Greg** [comment]
Thanks.  I'd like to see if the tests are stable after #1965, then start re-writing using this concept.

It does add some complexity to it; I'll add comments to it.  I think it will make the actual test code more compact, clearer, and easier to test the bind/control matrix with whatever we feel is necessary.
