### ISSUE TITLE
File.open command, not closed?

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#1985]
Normally `File.open` commands either close the io or work with a block.  The following exists:

https://github.com/puma/puma/blob/120f2470068b3c065a60fa5868c567a90c3b2893/lib/puma/control_cli.rb#L131-L134

We could:
1. Use `File.read`

2. Use a block for the return value.

Wasn't sure if there's a preference, but it should be cleaned  up...

**Comment by nateberkopec** [comment]
Yup, `File.read` makes more sense.

**Comment by MSP-Greg** [comment]
@mariokostelac

It's yours.

**Comment by mariokostelac** [comment]
@MSP-Greg any chance you could explain the idea behind the second point?

> Use a block for the return value.

**Comment by MSP-Greg** [comment]
@mariokostelac

> the idea behind the second point?

Sorry, I wasn't clear.  Code something like:

```ruby
File.open('/dev/urandom') { |f| bytes = f.read(count) }
```

Sometimes I use code like that if the block might be used for debugging. etc...
