### ISSUE TITLE
Remove Puma::Server#connected_port

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1996]
If it's only used in tests, it shouldn't be a public method.

* [ ] Make connected_port not public
* [ ] Provide a different way of allowing tests to see what ports we're connected to. It should support ALL ports we are currently bound to w/tcp AND ssl, not just the last one we bound to w/TCP.

**Comment by nateberkopec** [comment]
A big upside of this will be that we can then rm UniquePort and use port 0 everywhere in the tests, using connected_ports (? suggested name) to figure out what we got bound to.

**Comment by MSP-Greg** [comment]
> A big upside of this will be that we can then rm UniquePort

I'm not thinking about this right now (systemd).  But, what may work with 'normal Puma use'  may not work with parallel testing.

Personally, I always considered sockets to be two objects communicating on an agreed upon channel/port.  So 'port 0' always seemed odd.  Puma is only creating one of the objects.  If it was creating both, that would be different...
