### ISSUE TITLE
Next steps for 4.2.1

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#1998]
https://github.com/puma/puma/issues/1988#issuecomment-535576818 moving disco with @MSP-Greg here to keep stuff on-topic on the bug report thread

> Puma has always worked fine if the UNIXSocket files were not removed, so I think we should remove all code that does so. Maybe even test for that

This annoys me, but it might be true. It annoys me because if we create a file, we should clean it up when we don't need it anymore. I'll have to look at the original issue more to reflect. So, gut feeling, I don't like this course of action.

> I think there are some duplicate test method names, so maybe we should use file names that also include the test class...

Dunno what you mean.

> Maybe get this, #1986, and whatever else patched, do a point release, let the dust settle, and start back on the refactoring work?

Yup. I think the socket-closed bug + #1986 is a good point release.

> Also, maybe set JRuby back to 'allow-failure' until it can be made stable? After all the work on tests, always having to check logs, etc, I'd really like to see a few green checks...

NO, NO GREEN CHECKS FOR YOU! \</soup-nazi\> Forgetting about JRuby dug us into a hole the last time we did this. For now, I want to feel the pain of JRuby constantly failing, so that when 4.2.1 is released JRuby is the first thing we want to go and fix.

If you _really really want to_ we can allow_fail until 4.2.1 is released, but I'm going to add it back in as soon as that release is tagged.

**Comment by mcg** [comment]
> > Puma has always worked fine if the UNIXSocket files were not removed, so I think we should remove all code that does so. Maybe even test for that

> This annoys me, but it might be true. It annoys me because if we create a file, we should clean it up when we don't need it anymore. I'll have to look at the original issue more to reflect. So, gut feeling, I don't like this course of action.

Just to clarify, in the case of systemd socket activation, systemd initially creates the socket file, not Puma.

**Comment by MSP-Greg** [comment]
@mcn

> systemd initially creates the socket file

Is that true before the **first** start of Puma?

If so, maybe what we need to do is when Puma starts, check for whether the file(s) exist, and set a flag that is used to determine whether to unlink the file(s) on shutdown?  Or, just not add them to the Binder @unix_paths array if they do exist?

**Comment by mcg** [comment]
@MSP-Greg Correct. systemd socket unit, creates the socket(file or port).

**Comment by MSP-Greg** [comment]
@nateberkopec

Sorry, I've got a really squirrely ruby master bug that I'm trying to understand, just happened with a build early this morning...

> Dunno what you mean.

Sorry, being stupid.  Deleting the UNIXSocket files in Puma is different than deleting the files in test teardown.

Re JRuby, I've tried it with Actions (both 9.2.8.0 & head), and they freeze all the time, but sometimes have only a few failures/errors.  Until they stop freezing, I don't think I can be of any help, but I'll certainly watch for the fix.

**Comment by MSP-Greg** [comment]
I believe https://github.com/puma/puma/pull/1987 solves the original bug.

https://github.com/puma/puma/pull/1992 needs to be modified to work with systemd, as it was done as a 'please try this' PR.

Puma currently unlinks all binder UNIXSocket files on shutdown or (hard/exec) restart.

Puma should only unlink UNIXSocket files that it creates, and leave the files created by systemd alone.  We can change the Binder `@unix_paths` array to only include files created by Puma.

I think the changes will cause merge conflicts with https://github.com/puma/puma/pull/1987, or https://github.com/puma/puma/pull/1987 blocks https://github.com/puma/puma/pull/1992.

**Comment by nateberkopec** [comment]
> Puma should only unlink UNIXSocket files that it creates, and leave the files created by systemd alone. 

Got it, definitely agree with this.

**Comment by nateberkopec** [comment]
https://github.com/puma/puma/milestone/9
