### ISSUE TITLE
Public contributor chat

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2004]
I mentioned to @MSP-Greg in another issue to contact me offline, because we're constantly talking about X different issues across Y different pull requests, and it's honestly getting really confusing.

However, I don't want to exclude any of our other contributors, like @dentarg or @olleolleolle or others in the future!

There will always be a "private" communication channel for maintainers-only to discuss security issues, but for everything else we should absolutely keep it public. It's just that GH issues are really not a great place to do this.

So, what would:

* Keep communication public and open to all to contribute
* Keep a high signal-to-noise ratio
* Be easy to use/install/whatever.

**Comment by nateberkopec** [comment]
Also, I really want this chat to be for "contributors" or "first-time contributors" only. i.e. this is not support chat, this is not general "how do I X with Puma" chat, this is only for people contributing or interested in contributing patches/features/maintenance to Puma.

**Comment by olleolleolle** [comment]
@nateberkopec I like the goal a lot, but I have a hard time figuring out the next step.

An example of another project that does things _like_ this (not exactly the same):

- JRuby uses Gitter, as a talk channel, no barrier to join.

**Comment by nateberkopec** [comment]
Actually, JRuby just moved to Matrix: https://twitter.com/jruby/status/1178776721899900930

> The JRuby team is making a move! After several months of evaluating options, we are moving our official chat to @matrixdotorg
. Connect to us via https://matrix.to/#/#jruby:matrix.org and hang out with the JRuby community today!

...with an IRC bridge.

**Comment by dentarg** [comment]
> ...with an IRC bridge

Sweet 👍 I would join that.

**Comment by olleolleolle** [comment]
Hey, I just checked in here again, and we perhaps didn't move in to Matrix. Should pick that, real quick?

**Comment by nateberkopec** [comment]
I like the idea of Matrix but I don't really want to run my own Synapse server :|

**Comment by nateberkopec** [comment]
Matrix.org lets you run a channel on their homeserver.

Testing for now, but join #puma-contrib on matrix.org: https://matrix.to/#/!blREBEDhVeXTYdjTVT:matrix.org?via=matrix.org

**Comment by cjlarose** [comment]
FWIW I think Gittr was acquired by Element (who owns Matrix) since this issue was first brought up. I think the plan is to essentially extend Matrix to support the features that Gittr has, and then essentially make Gittr a Matrix client.

Either seems appropriate for now for open source projects since they're both open source themselves.
