### ISSUE TITLE
history.md (changelog) workflow

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2008]
I like the idea of having a good changelog (history.md).  But, the workflow as it exists is going to generate constant merge issues with PR's.

Also, it is an md file, so we can use real links in it

Thoughts?

**Comment by dentarg** [comment]
What about using https://github.com/github-changelog-generator/github-changelog-generator? It could possibly be automated with GitHub Actions

**Comment by nateberkopec** [comment]
FWIW I don’t really like automating Changelogs. Most commit messages that are used to generate them are not very descriptive.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nateberkopec** [comment]
This is possibly overdoing it, but you could have a folder of changelog entries (/changelogs), everyone adds a new file containing an entry, and the release process concats all of them, inserts into history.md, and then deletes all the files?

but surely there's a way to insert these without creating merge conflicts right? Always at the bottom of the list or something? I mean there's probably a merge strategy you can use that would avoid the conflict but that's not gonna work in the github UI

**Comment by boazsegev** [comment]
A Japanese based date-stamp could be useful to order the list of changes, along with the issue / PR number.

i.e., an update from January 21, 2020 related to PR 9999 could be marked as `20200121-9999.md` 

By using the `YYYYMMDD` prefix, all files will be ordered on a timeline. It's an easy matter to reverse the order or combine them into yearly reports (maybe naming them `YYYY9999`).

Multiple PRs / issues could be separated using a `-` or a `,`. i.e., `20191011-3456-3458-3459.md` could reference an updated dated Oct. 11th, 2019, related to PRs / issues 3456, 3458 and 3459.

This way, just parsing the file name would give actual information related to change.

This information could be used for automating the changelog, alongside the content of the file (which probably needs to be standardized as well).

Just my 2¢.

**Comment by nateberkopec** [comment]
For now we'll leave as-is.
