### ISSUE TITLE
SIGUSR2 signal not handled correctly after 4.2.0 update

### ISSUE THREAD

**Issue by micred** [puma/puma#2009]
**Describe the bug**
The signal SIGUSR2 doesn't restart puma. Process is keep active, but unresponsive.

**To Reproduce**
kill -SIGUSR2 $(cat tmp/pids/puma.pid)
The process with pid tmp/pids/puma.pid is still running, but it doesn't respond to requests.

**Expected behavior**
SIGUSR2 should restart puma.

**Comment by nateberkopec** [comment]
Hello, please consult our [bug report template](https://github.com/puma/puma/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) for instructions on how to provide a reproducible example. 

Here's what I'm seeing:

```
bundle exec puma --pidfile ./tmp/pids/puma.pid test/rackup/hello.ru
kill -SIGUSR2 $(cat tmp/pids/puma.pid)
```

Results:

```
Puma starting in single mode...
* Version 4.2.0 (ruby 2.6.4-p104), codename: Distant Airhorns
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
* Restarting...
Puma starting in single mode...
* Version 4.2.0 (ruby 2.6.4-p104), codename: Distant Airhorns
* Min threads: 0, max threads: 16
* Environment: development
* Inherited tcp://0.0.0.0:9292
Use Ctrl-C to stop
```

And then I can still:

```
$ curl http://localhost:9292
Hello World
```

**Comment by sigmike** [comment]
We also have trouble restarting puma after the upgrade to 4.2.0. It works fine with 4.1.1. We bind to a socket and I'm not sure how to make a minimal example.

Puma is behind nginx and we get a Bad Gateway after a `restart`. We have to explicitly `stop` and `start` to make it work again. We use `pumactl` to run these commands.

Here's our puma.conf:
```
environment 'staging'
daemonize true
pidfile '/path/to/app/tmp/puma/pid'
state_path '/path/to/app/tmp/puma/state'
stdout_redirect '/path/to/puma.stdout', '/path/to/puma.stderr', true
bind 'unix:///path/to/app/tmp/puma/sock'
prune_bundler
activate_control_app 'unix:///path/to/app/tmp/puma/ctl.sock', { auth_token: 'redacted' }
```

**Comment by nateberkopec** [comment]
@sigmike It's possible you're experiencing something that we're about to fix on Puma 4.2.1. Please give master a shot if you can, otherwise give that a try when it is released.

**Comment by sigmike** [comment]
@nateberkopec indeed it works fine on master and 4.2.1. Thanks.

**Comment by micred** [comment]
I confirm. Works fine again. Thank you.
