### ISSUE TITLE
SSL support for activate_control_app

### ISSUE THREAD

**Issue by Nowaker** [puma/puma#2015]
Valid:
```
activate_control_app 'tcp://127.0.0.1:9000', auth_token: token
```
Also valid:
```
ssl_bind '127.0.0.1', 8443, cert: 'config/cert-dev.pem', key: 'config/cert-dev.key'
```

Invalid:
```
activate_control_app 'ssl://127.0.0.1:9000', auth_token: token

[44959] ERROR: Invalid control URI: ssl://127.0.0.1:9000
```

It would be great for Puma to allow control app to be run behind a TLS certificate to ensure confidentiality of the token.

I know I can TLS-ify it using nginx but so we could use the same argument against `ssl_bind` :-)

**Comment by nateberkopec** [comment]
Closed by #2046
