### ISSUE TITLE
cannot install 2.0.* on windows

### ISSUE THREAD

**Issue by pickerel** [puma/puma#202]
on my win7

gem install puma --version ">=2.0.b7"

Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
        ERROR: Failed to build gem native extension.

```
    E:/dev/env/RailsInstaller/Ruby1.9.3/bin/ruby.exe extconf.rb
```

creating Makefile

make
generating puma_http11-i386-mingw32.def
compiling http11_parser.c
ext/http11/http11_parser.rl: In function 'http_parser_execute':
ext/http11/http11_parser.rl:111:3: warning: comparison between signed and unsign
ed integer expressions
compiling io_buffer.c
compiling mini_ssl.c
In file included from mini_ssl.c:2:0:
e:/dev/env/RailsInstaller/Ruby1.9.3/include/ruby-1.9.1/ruby/backward/rubyio.h:2:
2: warning: #warning use "ruby/io.h" instead of "rubyio.h"
mini_ssl.c:3:25: fatal error: openssl/bio.h: No such file or directory
compilation terminated.
make: **\* [mini_ssl.o] Error 1

**Comment by nicohvi** [comment]
I just wanted to thank @luislavena for the solution, worked ilke a charm! :+1:

**Comment by pancakeCaptain** [comment]
@luislavena 
Thank you so much for the solution you provided, this was extremely helpful!
