### ISSUE TITLE
When using port/bind more than once, Listening... is reported too often

### ISSUE THREAD

**Issue by zarqman** [puma/puma#2029]
**Describe the bug**
On Puma 4.2.1, using port/bind more than once causes "Listening ... " to be duplicated for previously bound ports. (Tested on macOS; unsure on Linux or other *nix.)

The problem does not occur on Puma 4.1.1.

**Puma config:**

puma.rb:
```
port 3900
bind "tcp://[::]:3901"
# bind "tcp://[::]:3902"
threads 2, 2
workers 0
preload_app!
```

launch cmd: `bundle exec puma -C config/puma.rb`

**To Reproduce**
Bind to 2 or more ports using port and/or bind commands. The same behavior happens if bind is used twice (as opposed to port + bind).

Our use case is to listen on both IPv4 and IPv6 sockets separately. With only a single port/bind command, only a single Listening line is present.

Issue _can_ be reproduced with `hello.ru`.

`lsof` indicates that only 1 IPv4 and 1 IPv6 socket are being opened, so I believe this is merely visual/informative. Traffic works properly on both sockets as well.

**Actual behavior**

```
Puma starting in single mode...
* Version 4.2.1 (ruby 2.6.4-p104), codename: Distant Airhorns
* Min threads: 2, max threads: 2
* Environment: development
* Listening on tcp://0.0.0.0:3900
* Listening on tcp://0.0.0.0:3900
* Listening on tcp://[::]:3901
Use Ctrl-C to stop
```

If a 3rd bind command is added (uncomment the extra line in puma.rb above), then there's an extra round of repeated lines:

```
Puma starting in single mode...
* Version 4.2.1 (ruby 2.6.4-p104), codename: Distant Airhorns
* Min threads: 2, max threads: 2
* Environment: development
* Listening on tcp://0.0.0.0:3900
* Listening on tcp://0.0.0.0:3900
* Listening on tcp://[::]:3901
* Listening on tcp://0.0.0.0:3900
* Listening on tcp://[::]:3901
* Listening on tcp://[::]:3902
Use Ctrl-C to stop
```

**Expected behavior**

Just one 'Listening' line per port/bind command:

```
Puma starting in single mode...
* Version 4.2.1 (ruby 2.6.4-p104), codename: Distant Airhorns
* Min threads: 2, max threads: 2
* Environment: development
* Listening on tcp://0.0.0.0:3900
* Listening on tcp://[::]:3901
Use Ctrl-C to stop
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Puma Version: 4.2.1

**Comment by composerinteralia** [comment]
It looks like this changed in d9131ca1f00041df95f2743ed11a8d7cb0040f57. We iterate through the `@ios` so we can log [all the localhost addresses](https://github.com/puma/puma/blob/master/lib/puma/binder.rb#L277-L282). But if we are binding with multiple tcp addresses `@ios` will already having the first address in it when we get to logging for the second one.

I am not sure what the best way to fix this is. The easiest solution would be to move the logging into `Binder#add_tcp_listener`, but I am not sure we can do that because it is called in other places (i.e. to start the control server). Another option would perhaps be to return the list of addresses instead of returning nil for the localhost case. But it might be strange to have that method sometimes return a single `TCPServer` and other times a list of them.

---

I also noticed that if we bind multiple tcp addresses we end up overwriting `@connected_port`. So that method will always return the last address. I don't know if that will cause any major problems, since that value doesn't seem to be used by puma itself except in test.

**Comment by composerinteralia** [comment]
A failing test for test/test_binding.rb

```rb
  def test_logs_each_tcp_binding_only_once
    @binder.parse ["tcp://127.0.0.1:10001", "tcp://127.0.0.1:10002"], @events

    stdout = @events.stdout.string
    logs = stdout.split("\n")

    assert_equal logs.uniq, logs
  end
```

**Comment by nateberkopec** [comment]
> we end up overwriting @connected_port

I'm ok with this, that method is not supposed to be public and never really worked anyway, see #1996.

The proposed failing test is perfect.

**Comment by MSP-Greg** [comment]
>  all the localhost addresses

While working on Binder, the issue with localhost mapping to more than one IP address (maybe IPv4 & IPv6) may affect the current logic for restart (`Kernel.exec`) with the `ENV["PUMA_INHERIT_\d+"]` mechanism, and also systemd usage.  Using port 0 may also affect things.

I recall that some of logic may be assuming one-to-one, and localhost to sockets is not...

At the time, I decided to set that aside and work on the test suite, and also get working/stable  coverage of some of the inheritance/activation code.  My two cents...

**Comment by composerinteralia** [comment]
I think this may get fixed on its own with the refactoring work from https://github.com/puma/puma/pull/1989.

> I think it's time for me to stop the spike for now and pull back a few of these things into master.

Let me know if I can help with that.

**Comment by nateberkopec** [comment]
Master still does this as of today. I sort of stopped midway through my binding refactor, it's still "on the list".

**Comment by dentarg** [comment]
This was solved by https://github.com/puma/puma/pull/2533

```
$ puma -C puma.rb test/rackup/hello.ru
Puma starting in single mode...
* Puma version: 5.2.1 (ruby 2.7.1-p83) ("Fettisdagsbulle")
*  Min threads: 2
*  Max threads: 2
*  Environment: development
*          PID: 30897
* Listening on http://0.0.0.0:3900
* Listening on http://[::]:3901
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2021-02-06 18:41:53 +0100 ===
- Goodbye!
```
