### ISSUE TITLE
Add PID to log strings?

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2031]
While working on updated tests, I (again) came across an issue with testing, specifically the integration testing.

When a `restart`  is used in testing, the PID changes, so closing Puma requires some way to determine the new PID.

A workaround is to always write a pid file, and read the PID in the teardown.  Another option would be to write the PID in the log strings.

Would a change like the below be considered a breaking change?
```
Puma starting in single mode...
```

to:
```
Puma (pid: 3008) starting in single mode...
```

Rather read a string from IO rather than write read a file....

**Comment by nateberkopec** [comment]
Hm, what’s wrong with the pidfile option?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by natematykiewicz** [comment]
Isn’t this already achievable via this PR? https://github.com/puma/puma/pull/1816

Just set your config to:

```ruby
log_formatter do |str|
  "[#{Process.pid}]: #{str}"
end
```

and it’ll output:

"[3008]: Puma starting in single mode...“
