### ISSUE TITLE
Working in forks - Actions, Rakefile

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2038]
While working in a fork, the currrent Actions yml file will only allow tests run on master.  This needs to be updated to support contributors workflows.

Also, I've always had a 2nd Rakefile which is "just the tests please ma'am", as most of the time I'm not changing anything in the c source files, and I'm precompiled to run Ruby 2.2. thru trunk...

**Comment by nateberkopec** [comment]
> While working in a fork, the currrent Actions yml file will only allow tests run on master. This needs to be updated to support contributors workflows.

Ohhh, so that's why you were adding it.

**Comment by MSP-Greg** [comment]
Yes.  As a Windows user, any work I do I test in my fork.  Remember, no fork and no UNIXSockets.  Kind of important functionality for Puma.

Way too many branches have a duplicate (with some kind of suffix) that I use with the patched Actions file.  Spent too much time rebasing.  I stash the Rakefile file, as I just use that locally...

**Comment by nateberkopec** [comment]
Go ahead and open a new PR to add it and close this issue then 👍

**Comment by MSP-Greg** [comment]
PR https://github.com/puma/puma/pull/2042
