### ISSUE TITLE
Add processed requests count feature

### ISSUE THREAD

**Issue by spuyet** [puma/puma#2057]
**Is your feature request related to a problem? Please describe.**
This feature could allow to have some data about the number of processed requests for a puma process like in passenger: https://www.phusionpassenger.com/library/admin/apache/overall_status_report.html

**Describe the solution you'd like**
The feature seems easy to implement with a counter in the server instance incremented each time that we process a request.

I can do a PR if you accept this feature request.
I check the code a bit and it seems there is an internal variable incremented in the client object but not really used anywhere, not sure if we should remove this or use it: https://github.com/puma/puma/blob/a51206514c5ec9547f66ecbfed98a145c63c7023/lib/puma/client.rb#L490

**Comment by nateberkopec** [comment]
Makes sense. Could be exposed in `stats`.
