### ISSUE TITLE
warning: conflicting chdir during another chdir block

### ISSUE THREAD

**Issue by wellington1993** [puma/puma#2067]
**Describe the bug**
After update ruby, and trying to run `bundle update`:
```
...
Using psych 3.1.0
Using puma 4.2.1 from https://github.com/puma/puma.git (at master@3203159)
/home/wellington/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
/home/wellington/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block
Using puma_worker_killer 0.1.1 from https://github.com/schneems/puma_worker_killer.git (at master@4552de0)
Using rack-cors 1.0.3 from https://github.com/cyu/rack-cors.git (at master@145a5df)
...
```

**To Reproduce**
Update ruby and try bundle update

**Expected behavior**
No errors

**Desktop (please complete the following information):**
 - OS: Linux
 - Puma Version: 4.2.1

**Comment by wellington1993** [comment]
I found similar problem:
fastlane/fastlane#643

**Comment by wellington1993** [comment]
And found this:
test-kitchen/test-kitchen#1416
test-kitchen/test-kitchen#1430
test-kitchen/test-kitchen@312cf93

**Comment by nateberkopec** [comment]
I don't think this is a Puma issue. Puma doesn't call (AFAICT) chdir during gem installation.

**Comment by Climbtaylorc** [comment]
I'm having the same issue!  
![Ruby1](https://user-images.githubusercontent.com/29851869/69518392-a29a3880-0f14-11ea-89b1-31fc18095fb4.png)

![Ruby_2](https://user-images.githubusercontent.com/29851869/69518406-b0e85480-0f14-11ea-8b4e-17cd1430c5a8.png)

![Ruby_3](https://user-images.githubusercontent.com/29851869/69518415-b9d92600-0f14-11ea-8af9-369a41036e1a.png)

**Comment by Climbtaylorc** [comment]
I also had to add gem 'sqlite3', git: "https://github.com/larskanis/sqlite3-ruby", branch: "add-gemspec"
to the gem file.
![Ruby_4](https://user-images.githubusercontent.com/29851869/69518595-38ce5e80-0f15-11ea-8472-721489dba3bc.png)

https://github.com/sparklemotion/sqlite3-ruby/issues/224

This  only fixes the sqlite3 issue.  However when you insert: rails server, you do not get a localhost:3000 option,  just  Listening on tcp://[::1]:3000, the thats when you get the above error message.
