### ISSUE TITLE
Puma web server - worker process

### ISSUE THREAD

**Issue by yaminil** [puma/puma#2080]
**Describe the bug**
under which circumstances would a worker process be not terminated but a new master puma process will be launched post restart?

I'm encountering one such scenario where I see an old worker binding to the old stock along with a new parent process which doesn't have it's own set of workers.

I've the stack traces of these processes.. will appreciate your  help on the same 

**Puma config:**

AWS performs an initctl restart puma during app deployment..

directory '/var/app/current'
      threads 8, 16
      procs = %x(grep -c processor /proc/cpuinfo)
      workers (procs.to_i > 4 ? "6\n" : (procs.to_i > 2 ? "3\n" : procs))
      bind 'unix:///var/run/puma/my_app.sock'
      pidfile '/var/run/puma/puma.pid'
      stdout_redirect '/var/log/puma/puma.log', '/var/log/puma/puma.log', true
      daemonize false

**To Reproduce**
i don't know how to reproduce, i believe a worker is hanging for some reason during a restart and a new process as well without worker is spinned off.. I don't see puma.pid updated in process ID file neither the socket.. these seem to belong to  the old process.

strace -p 25690 -q -f
[pid  6335] futex(0x7f5280000020, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
[pid 26203] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874717, NULL <unfinished ...>
[pid 26158] futex(0x557aaf34cad4, FUTEX_WAIT_PRIVATE, 11, NULL <unfinished ...>
[pid 26155] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874721, NULL <unfinished ...>
[pid 26146] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874719, NULL <unfinished ...>
[pid 25991] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874720, NULL <unfinished ...>
[pid 25956] futex(0x7f52f0075534, FUTEX_WAIT_PRIVATE, 5, NULL <unfinished ...>
[pid 25955] futex(0x7f52f004efd4, FUTEX_WAIT_PRIVATE, 9, NULL <unfinished ...>
[pid 25954] futex(0x7f52f00459a4, FUTEX_WAIT_PRIVATE, 9, NULL <unfinished ...>
[pid 25953] futex(0x557aaae78654, FUTEX_WAIT_PRIVATE, 19, NULL <unfinished ...>
[pid 25693] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874718, NULL <unfinished ...>
[pid 25692] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid 26203] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 26146] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 25991] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 25693] <... futex resumed> )       = -1 EAGAIN (Resource temporarily unavailable)
[pid 26203] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874721, NULL <unfinished ...>
[pid 26146] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874721, NULL <unfinished ...>
[pid 25991] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874721, NULL <unfinished ...>
[pid 25693] futex(0x557aa2e2a054, FUTEX_WAIT_PRIVATE, 374874721, NULL <unfinished ...>
[pid 25692] <... restart_syscall resumed> ) = 0
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)
[pid 25692] poll([{fd=3, events=POLLIN}], 1, 100) = 0 (Timeout)

Your issue will be solved very quickly if you can reproduce it with a "hello world" rack application. To do this, copy this into a file called `hello.ru`:

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma -C <where_your_config_is> hello.ru
```

If you cannot reproduce with a hello world application or other simple application, we will have a lot more difficulty helping you fix your issue, because it may be application-specific and not a bug in Puma at all.  

There is also a Dockerfile available for reproducing Linux-specific issues. To use:

```
$ docker build -f tools/docker/Dockerfile -t puma .
$ docker run -p 9292:9292 -it puma
```

This will help you to create a container that reproduces your issue.

**Expected behavior**
upon restart, all worker processes should gracefully exit.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux] Linux
 - Puma Version [e.g. 4.1.1] 2.16

**Comment by nateberkopec** [comment]
How are you restarting?

**Comment by yaminil** [comment]
Initctl restart puma.. this happens as part of aws deployment ..

**Comment by MSP-Greg** [comment]
@yaminil

Sorry, your first post seems to indicate that you're using Puma 2.16?  Can you please confirm the Puma version you're having problems with?

**Comment by yaminil** [comment]
SSure..@MSP-Greg , its  puma 2.16.0..

**Comment by MSP-Greg** [comment]
@yaminil

Puma 2.16.0 was released on January 28, 2016.    Puma 4 uses nio4r, but Puma 3 did not.

Can you repo the issue with a newer Puma version?

**Comment by yaminil** [comment]
I don't have any reliable steps to repro it even with 2.16... I'm thinking
if a new thread has accepted a connection is processing the request and is
making  the process get into a hung state all while during restart..

I can try though.. Is there anything that you can relate with the stack
traces posted above?
gdb) thread apply all btThread 1 (process 25690):
#0 0x00007f53044de975 in pthread_cond_wait () from /lib64/libpthread.so.0
#1 0x0000557aa2697328 in native_cond_wait (mutex=0x557aa2e2a7e8,
cond=<optimized out>) at thread_pthread.c:338
#2 native_sleep (th=th@entry=0x557aa2e2a6c0, timeout_tv=0x0) at
thread_pthread.c:1127
#3 0x0000557aa2698d57 in sleep_forever (deadlockable=1, spurious_check=0,
th=0x557aa2e2a6c0) at thread.c:1046
#4 thread_join_sleep (arg=arg@entry=140729803095040) at thread.c:833
#5 0x0000557aa2536bd8 in rb_ensure (b_proc=b_proc@entry=0x557aa2698cb0
<thread_join_sleep>, data1=data1@entry=140729803095040,
e_proc=e_proc@entry=0x557aa2694720 <remove_from_join_list>,
data2=data2@entry=140729803095040) at eval.c:935
#6 0x0000557aa2695ab0 in thread_join (delay=<optimized out>,
target_th=0x557aaf34ca20) at thread.c:875
#7 thread_join_m (argc=<optimized out>, argv=0x7f53048001d8,
self=<optimized out>) at thread.c:955
#8 0x0000557aa2674e5e in vm_call_cfunc_with_frame (ci=0x0,
reg_cfp=0x7f53048ffc50, th=0x557aa2e2a6c0) at vm_insnhelper.c:1380
#9 vm_call_cfunc (th=th@entry=0x557aa2e2a6c0,
reg_cfp=reg_cfp@entry=0x7f53048ffc50,
ci=ci@entry=0x557aa3977410) at vm_insnhelper.c:1473
#10 0x0000557aa26837ee in vm_call_method (th=0x557aa2e2a6c0,
cfp=0x7f53048ffc50, ci=0x557aa3977410) at vm_insnhelper.c:1689
#11 0x0000557aa267a7fb in vm_exec_core (th=th@entry=0x557aa2e2a6c0,
initial=initial@entry=0) at insns.def:1069
#12 0x0000557aa267dcd4 in vm_exec (th=th@entry=0x557aa2e2a6c0) at vm.c:1440
#13 0x0000557aa26814f6 in invoke_block_from_c (th=0x557aa2e2a6c0,
block=<optimized out>, self=93985218832840, argc=<optimized out>,
argv=<optimized out>, blockptr=<optimized out>, cref=0x0,
defined_class=93985218924800, splattable=1) at vm.c:818
#14 0x0000557aa2689bd0 in vm_yield (argc=0, argv=0x0, th=<optimized out>)
at vm.c:858
#15 rb_yield_0 (argv=0x0, argc=0) at vm_eval.c:993
#16 rb_yield (val=val@entry=52) at vm_eval.c:1000
#17 0x0000557aa25369b1 in rb_protect (proc=0x557aa26897f0 <rb_yield>,
data=data@entry=52, state=state@entry=0x7ffe35ec44ec) at eval.c:904
#18 0x0000557aa25ac0b9 in rb_f_fork (obj=<optimized out>) at process.c:3707
#19 0x0000557aa2674e5e in vm_call_cfunc_with_frame (ci=<optimized out>,
reg_cfp=0x7f53048ffd40, th=0x557aa2e2a6c0) at vm_insnhelper.c:1380
#20 vm_call_cfunc (th=0x557aa2e2a6c0, reg_cfp=0x7f53048ffd40, ci=<optimized
out>) at vm_insnhelper.c:1473
#21 0x0000557aa267a878 in vm_exec_core (th=th@entry=0x557aa2e2a6c0,
initial=initial@entry=0) at insns.def:1039
#22 0x0000557aa267dcd4 in vm_exec (th=th@entry=0x557aa2e2a6c0) at vm.c:1440
#23 0x0000557aa2689c87 in invoke_block_from_c (splattable=1,
defined_class=93985218924800, cref=0x0, blockptr=0x0, argv=0x7ffe35ec48c8,
argc=1,
self=93985218832840, block=0x7f53048ffe00, th=0x557aa2e2a6c0) at vm.c:818
#24 vm_yield (argv=0x7ffe35ec48c8, argc=1, th=0x557aa2e2a6c0) at vm.c:858
#25 rb_yield_0 (argv=0x7ffe35ec48c8, argc=1) at vm_eval.c:993
#26 rb_yield (val=val@entry=5) at vm_eval.c:1003
#27 0x0000557aa25903be in int_dotimes (num=13) at numeric.c:3862
#28 0x0000557aa2674e5e in vm_call_cfunc_with_frame (ci=0x0,
reg_cfp=0x7f53048ffde0, th=0x557aa2e2a6c0) at vm_insnhelper.c:1380
#29 vm_call_cfunc (th=th@entry=0x557aa2e2a6c0,
reg_cfp=reg_cfp@entry=0x7f53048ffde0,
ci=ci@entry=0x557aa3967f00) at vm_insnhelper.c:1473
#30 0x0000557aa26837ee in vm_call_method (th=0x557aa2e2a6c0,
cfp=0x7f53048ffde0, ci=0x557aa3967f00) at vm_insnhelper.c:1689
#31 0x0000557aa267a878 in vm_exec_core (th=th@entry=0x557aa2e2a6c0,
initial=initial@entry=0) at insns.def:1039
#32 0x0000557aa267dcd4 in vm_exec (th=0x557aa2e2a6c0) at vm.c:1440
#33 0x0000557aa268a106 in rb_iseq_eval (iseqval=<optimized out>) at
vm.c:1672
#34 0x0000557aa2537de7 in rb_load_internal0 (th=th@entry=0x557aa2e2a6c0,
fname=93985209496640, wrap=<optimized out>) at load.c:612
#35 0x0000557aa2538536 in rb_load_internal (wrap=<optimized out>,
fname=<optimized out>) at load.c:642
#36 rb_f_load (argc=<optimized out>, argv=<optimized out>) at load.c:714
---Type <return> to continue, or q <return> to quit---
#37 0x0000557aa2674e5e in vm_call_cfunc_with_frame (ci=0x1,
reg_cfp=0x7f53048fff70, th=0x557aa2e2a6c0) at vm_insnhelper.c:1380
#38 vm_call_cfunc (th=th@entry=0x557aa2e2a6c0,
reg_cfp=reg_cfp@entry=0x7f53048fff70,
ci=ci@entry=0x557aa3331528) at vm_insnhelper.c:1473
#39 0x0000557aa26837ee in vm_call_method (th=0x557aa2e2a6c0,
cfp=0x7f53048fff70, ci=0x557aa3331528) at vm_insnhelper.c:1689
#40 0x0000557aa267a7fb in vm_exec_core (th=th@entry=0x557aa2e2a6c0,
initial=initial@entry=0) at insns.def:1069
#41 0x0000557aa267dcd4 in vm_exec (th=th@entry=0x557aa2e2a6c0) at vm.c:1440
#42 0x0000557aa268a373 in rb_iseq_eval_main
(iseqval=iseqval@entry=93985207168720)
at vm.c:1685
#43 0x0000557aa2532d84 in ruby_exec_internal (n=0x557aa2e32ed0) at
eval.c:254
#44 0x0000557aa2535ecd in ruby_exec_node (n=0x557aa2e32ed0) at eval.c:319
#45 ruby_run_node (n=<optimized out>) at eval.c:311
#46 0x0000557aa2531f9b in main (argc=4, argv=0x7ffe35ec5718) at main.c:36
(gdb)
(gdb)
(gdb)
00:56 <https://fourkites.slack.com/archives/DDRJKV3TJ/p1575142000001200>

**Comment by dentarg** [comment]
@yaminil can you edit your last comment and surround it with \`\`\` ([code fencing](https://guides.github.com/features/mastering-markdown/#examples) that is) so the trace becomes readable?

also, if the problem can't be reproduced with the latest Puma versions, it is unlikely that anyone will look into it

**Comment by nateberkopec** [comment]
We've improved restarts a lot over the years. Please upgrade to a 4.x Puma version and if you can still reproduce, please let us know. We don't support old Puma versions.
