### ISSUE TITLE
Checking for puma version causes segmentation fault on ubuntu 18.04

### ISSUE THREAD

**Issue by sahaynishant342** [puma/puma#2085]
**Describe the bug**
Checking for puma version `puma -v` causes segmentation fault on Ubuntu 18.04

**Puma config:**

**To Reproduce**
1. Install puma : `gem install puma -v 2.9.2`
2. If successfully installed, check for puma version `puma -v`
3. Following is snippet of error:
```
/home/nishant/.rvm/gems/ruby-2.1.4/gems/puma-2.9.2/lib/puma/puma_http11.so: [BUG] Segmentation fault at 0x00000000000000
ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0012 p:-11811710004486 s:0044 e:000043 TOP    [FINISH]
c:0011 p:---- s:0042 e:000041 CFUNC  :require
c:0010 p:0119 s:0038 e:000037 TOP    /home/nishant/.rvm/gems/ruby-2.1.4/gems/puma-2.9.2/lib/puma/server.rb:18 [FINISH]
c:0009 p:---- s:0036 e:000035 CFUNC  :require
c:0008 p:0023 s:0032 e:000031 TOP    /home/nishant/.rvm/gems/ruby-2.1.4/gems/puma-2.9.2/lib/puma/cli.rb:4 [FINISH]
```

**Expected behavior**
It should have listed the version of puma installed.

**Desktop**
 - OS: Zorin OS 15 (Ubuntu 18.04)
 - Puma Version 2.9.2

**Comment by dentarg** [comment]
Sorry, but you are using too old versions of Puma and Ruby, please try with a supported Ruby version and Puma 4.

**Comment by sahaynishant342** [comment]
ok @dentarg the problem got solved by installing newer version of `puma` (version _3.8.2_) thanks
