### ISSUE TITLE
Can't start Ruby on Rails server using Ruby 2.6.5 version - I suspect of puma gem

### ISSUE THREAD

**Issue by lnimet** [puma/puma#2094]
I get this error when I run **rails s**

I had try update all my gems, but didn't works for me :(
When I was using with ruby 2.6.1 everything worked fine.
But I had to update the ruby version because my environment in the Elastic Beanstalk on AWS is works with ruby 2.6.5.

Can anyone help me?

Updating the post...

I tried rebuild all my gems, but I still have the same error.

After that I redid the following:

> gem pristine --all
 
> bundle install

> bundle exec spring binstub --all

The error I got:

> nimet@nimet-PC:~/Projects/belle.api$ rails s
> => Booting Puma
> => Rails 5.2.4 application starting in development 
> => Run `rails server -h` for more startup options
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/puma_http11.so: [BUG] Segmentation fault at 0x0000000000000000
> ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
> 
> -- Control frame information -----------------------------------------------
> c:0052 p:-11804295380244 s:0281 e:000280 TOP    [FINISH]
> c:0051 p:---- s:0278 e:000277 CFUNC  :require
> c:0050 p:0008 s:0273 e:000272 BLOCK  /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0049 p:0068 s:0270 e:000269 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257
> c:0048 p:0011 s:0263 e:000262 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0047 p:0076 s:0257 e:000256 TOP    /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/server.rb:15 [FINISH]
> c:0046 p:---- s:0254 e:000253 CFUNC  :require
> c:0045 p:0008 s:0249 e:000248 BLOCK  /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0044 p:0068 s:0246 e:000245 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257
> c:0043 p:0011 s:0239 e:000238 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0042 p:0006 s:0233 e:000232 TOP    /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/runner.rb:3 [FINISH]
> c:0041 p:---- s:0230 e:000229 CFUNC  :require
> c:0040 p:0008 s:0225 e:000224 BLOCK  /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0039 p:0068 s:0222 e:000221 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257
> c:0038 p:0011 s:0215 e:000214 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0037 p:0006 s:0209 e:000208 TOP    /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/cluster.rb:3 [FINISH]
> c:0036 p:---- s:0206 e:000205 CFUNC  :require
> c:0035 p:0008 s:0201 e:000200 BLOCK  /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0034 p:0068 s:0198 e:000197 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257
> c:0033 p:0011 s:0191 e:000190 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0032 p:0020 s:0185 e:000184 TOP    /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/launcher.rb:5 [FINISH]
> c:0031 p:---- s:0182 e:000181 CFUNC  :require
> c:0030 p:0008 s:0177 e:000176 BLOCK  /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0029 p:0068 s:0174 e:000173 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257
> c:0028 p:0011 s:0167 e:000166 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291
> c:0027 p:0031 s:0161 e:000160 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/rack/handler/puma.rb:17
> c:0026 p:0012 s:0152 e:000151 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/rack/handler/puma.rb:65
> c:0025 p:0195 s:0143 E:001538 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/rack-2.0.8/lib/rack/server.rb:297
> c:0024 p:0045 s:0136 E:002620 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands/server/server_command.rb:53
> c:0023 p:0042 s:0132 e:000131 BLOCK  /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands/server/server_command.rb:147 [FINISH]
> c:0022 p:---- s:0128 e:000127 CFUNC  :tap
> c:0021 p:0030 s:0124 e:000123 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands/server/server_command.rb:142
> c:0020 p:0064 s:0120 e:000119 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27
> c:0019 p:0047 s:0112 e:000111 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127
> c:0018 p:0259 s:0105 e:000104 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392
> c:0017 p:0043 s:0092 e:000091 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/command/base.rb:69
> c:0016 p:0130 s:0085 e:000084 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/command.rb:46
> c:0015 p:0059 s:0074 e:000073 TOP    /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands.rb:18 [FINISH]
> c:0014 p:---- s:0069 e:000068 CFUNC  :require
> c:0013 p:0053 s:0064 e:000063 TOP    /home/nimet/Projects/belle.api/bin/rails:9 [FINISH]
> c:0012 p:---- s:0060 e:000059 CFUNC  :load
> c:0011 p:0135 s:0055 e:000054 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28
> c:0010 p:0009 s:0050 e:000049 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7
> c:0009 p:0014 s:0045 e:000044 METHOD /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30
> c:0008 p:0295 s:0039 e:000038 TOP    /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49 [FINISH]
> c:0007 p:---- s:0033 e:000032 CFUNC  :load
> c:0006 p:0115 s:0028 e:000027 TOP    /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11 [FINISH]
> c:0005 p:---- s:0022 e:000021 CFUNC  :require
> c:0004 p:0130 s:0017 e:000016 TOP    /home/nimet/Projects/belle.api/bin/spring:15 [FINISH]
> c:0003 p:---- s:0012 e:000011 CFUNC  :load
> c:0002 p:0018 s:0007 E:000db8 EVAL   bin/rails:3 [FINISH]
> c:0001 p:0000 s:0003 E:000900 (none) [FINISH]
> 
> -- Ruby level backtrace information ----------------------------------------
> bin/rails:3:in `<main>'
> bin/rails:3:in `load'
> /home/nimet/Projects/belle.api/bin/spring:15:in `<top (required)>'
> /home/nimet/Projects/belle.api/bin/spring:15:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
> /home/nimet/Projects/belle.api/bin/rails:9:in `<top (required)>'
> /home/nimet/Projects/belle.api/bin/rails:9:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands.rb:18:in `<top (required)>'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/command.rb:46:in `invoke'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/command/base.rb:69:in `perform'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands/server/server_command.rb:142:in `perform'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands/server/server_command.rb:142:in `tap'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands/server/server_command.rb:147:in `block in perform'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/railties-5.2.4/lib/rails/commands/server/server_command.rb:53:in `start'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/rack-2.0.8/lib/rack/server.rb:297:in `start'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/rack/handler/puma.rb:65:in `run'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/rack/handler/puma.rb:17:in `config'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/launcher.rb:5:in `<top (required)>'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/cluster.rb:3:in `<top (required)>'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/runner.rb:3:in `<top (required)>'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/puma-4.3.1/lib/puma/server.rb:15:in `<top (required)>'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
> /home/nimet/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'

**Comment by nateberkopec** [comment]
Not a lot to go on here, but your stacktrace does show that you're segfaulting during the require of Puma's C extension.

Given how this issue hasn't been reported by anyone else it's probably an issue with your local environment, but I could be wrong. `gdb` may provide more information.

**Comment by nateberkopec** [comment]
Closing, if you can provide more info we can take a look.
