### ISSUE TITLE
How can I know when the thread is removed from the pool?

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [puma/puma#2100]
How can I know when the thread is removed from the pool?

I need to perform some actions on thread die but I can't.
The thread removed from the pool without any hooks.
https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb#L142

Thanks

**Comment by nateberkopec** [comment]
Confirming there's no way to do this in Puma today and I can't think of a way to do it in Ruby by yourself without some absolutely jank polling.

Can you please expand on your use-case?

**Comment by Serhiy-Nazarov** [comment]
Hi @nateberkopec 
As an example, I want to have TCP connection per worker and Socket per Thread. But Puma can remove the thread from pool and I can't disconnect my Socket. After some time I will have a lot of sockets.
So, I need to have a hook on thread added to the pool and hook on removed from the pool. The same as worker hooks.

**Comment by nateberkopec** [comment]
I think you should do what Rails does with database connections and use a Rack middleware that checks connections in and out of the pool on a per-request basis. Make sense?

**Comment by Serhiy-Nazarov** [comment]
I was able to create a socket per thread. But I can't disconnect it when thread removed from the pool.
In my case, I try to setup the bunny (RabbitMQ) for creating a separate channel for each thread.
And also, threads never die after kick out from the pool.

**Comment by Serhiy-Nazarov** [comment]
@nateberkopec are you mean something like this? https://github.com/mperham/connection_pool

**Comment by nateberkopec** [comment]
@Serhiy-Nazarov exactly. Now write a Rack middleware that checks out a connection from the pool when you start a request, and then checks it back in when there's an exception or the request is completed.

**Comment by Serhiy-Nazarov** [comment]
Much thanks @nateberkopec 
But what about thrown away threads in general? - The thread never dies and continues to live in memory.

**Comment by nateberkopec** [comment]
Take a look at Rails’ Reaper class for an example of how they take care of this.

**Comment by nateberkopec** [comment]
Just noted: thread destruction hooks has been proposed before and we said we would accept it https://github.com/puma/puma/issues/356
