### ISSUE TITLE
Puma is (randomly) reloading application code before a restart is issued in production

### ISSUE THREAD

**Issue by feliperaul** [puma/puma#2101]
**Describe the bug**
After noticing weird exceptions during our deployment (we noticed new code that relied on migrations that were still running was already being served before we issued puma restart), we could confirm that puma is reloading application code as soon as we update the codebase via GIT, even tough we're running in production ENV and Puma should wait for the restart to be issued. 

**Puma config:**

We're using socket activation:

```
shared_dir = "/var/www/app/shared"

workers 25
threads 1, 1

bind "unix://#{shared_dir}/tmp/sockets/puma-app.sock"

# environment ENV.fetch("RAILS_ENV", "production")
environment "production"

stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true

pidfile "#{shared_dir}/tmp/pids/puma.pid"

preload_app!

before_fork do
  ActiveRecord::Base.connection_pool.disconnect! if defined?(ActiveRecord)
end

on_worker_boot do

  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)

end

```

Puma socket:

```
[Unit]
Description=Puma HTTP Server Accept Sockets for app

[Socket]
SocketUser={{ param_user_name }}
SocketGroup={{ param_user_name }}
ListenStream=/var/www/app/shared/tmp/sockets/puma-app.sock

# Socket options matching Puma defaults
NoDelay=true
ReusePort=true
Backlog=1024

[Install]
WantedBy=sockets.target
```

**Expected behavior**
Puma should not start serving new code immediately after we update the application's codebase with a git pull. It should wait for us to issue a `sudo systemctl restart puma-app.service`. 

 - OS: Ubuntu 18.04 LTS
 - Puma Version 4.3.0

**Comment by feliperaul** [comment]
I should also point that by trailing `tail -f` puma's stdout log file, we can confirm that nothing else is triggering a puma restart; it's just simply picking up new code on the applications folder as soon as it's updated, before puma's service restart command is issued.

**Comment by feliperaul** [comment]
Here's a short 1 min video about what's going on: 
https://www.loom.com/share/710d2d617f0746c8b418fc162a1c2016

**Comment by nateberkopec** [comment]
It looks like Puma is starting new workers during your test. 

Here's what happens:

1. You make 1 request to the socket to the "old" version. One Puma child process runs the request, caching that template.
2. You change the template. 1 worker has the "old" version of the template cached, 3 do not.
3. You make 1 request. At this point, whether or not your request is fulfilled by the 1 worker with the cached template or the 3 workers which do not have the template yet cached is a matter of chance.

If you can reproduce with a single worker, please let me know.

**Comment by feliperaul** [comment]
@nateberkopec Nate, if you don't mind me asking, how do you deal with long-running migrations during deploy, to avoid exceptions?

I'm here watching a slow migration (15 minutes) and exceptions being raised because of a newly created column that is present in the view templates, but whose migration to create it is still running, and I assume the scenario you described is playing out.

Should I first deploy the migration to create the new column, and only then do a second deploy to only update the view templates? Any easier way than having to slice commits like this?

**Comment by nateberkopec** [comment]
> Should I first deploy the migration to create the new column

Yup, you got it exactly.
