### ISSUE TITLE
413 Payload Too Large

### ISSUE THREAD

**Issue by collins-b** [puma/puma#2127]
**Describe the bug**

When I upload a file larger than 8MB, I get the message: `413 Payload Too Large`
**Puma config:**

Please copy-paste your Puma config AND your command line options here.

```
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 1 }
threads threads_count, threads_count

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
port        ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked webserver processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
workers ENV.fetch("WEB_CONCURRENCY") { 1 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory.
#
# preload_app!

stdout_redirect(stdout = '/dev/stdout', stderr = '/dev/stderr', append = true)

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

Is there a configuration value that needs to be changed in Puma? I'm using Nginx and I set it to upload large files. So Nginx isn't the issue here.
**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux]
 - Puma Version [e.g. 4.1.1]

**Comment by dentarg** [comment]
Have you reproduce your issue without Nginx? E.g. making the request directly to Puma?

If you can include all the steps to reproduce the problem, that would be good.

**Comment by nateberkopec** [comment]
I'm 99% sure that Puma doesn't limit request body size and so cannot return a 413 on its own. The only way would be your application itself limiting upload sizes, which is possible. Must be coming from NGINX or your application.

**Comment by collins-b** [comment]
@nateberkopec @dentarg I have confirmed it's not Puma. I think it's an issue with Kong which is running Kong. I'm going to close this.
