### ISSUE TITLE
4.3.2 broke rails system tests that use Devise sign_in helper

### ISSUE THREAD

**Issue by jeffblake** [puma/puma#2131]
I imagine the security fix in version 4.3.2 is rejecting the header that the devise helper adds to the request?

This is the helper being used in `ApplicationSystemTestCase`:
https://github.com/heartcombo/devise/blob/master/lib/devise/test/integration_helpers.rb

Trying to follow that code, it goes somewhere in here https://github.com/wardencommunity/warden/blob/997055a511ae65b1d0b84112f1f35813e3f4cd84/lib/warden/proxy.rb#L170 then elsewhere

Not sure the best solution, can you skip this security check in RACK_ENV test?

**Comment by nateberkopec** [comment]
Merging to #2132
