### ISSUE TITLE
Add configurable max URI length to meet HTTP/1.1 spec

### ISSUE THREAD

**Issue by Laukei** [puma/puma#2134]
## Problem

I am developing an endpoint to `GET` information on a large number of values which are supplied as array parameters `/get_thing?ids[]=1&ids[]=2...` but the number of values I can retrieve is limited by Puma's [max URI limit](https://github.com/puma/puma/pull/408/files#diff-a59f94a30a1e4fd79523ef77ba8fa711) which was set based on what Internet Explorer would accept in 2013. This is no longer a reasonable metric against which to set the URI length. The [IETF updated HTTP/1.1 spec](https://tools.ietf.org/html/rfc7230) from 2014 says in [section 3.1.1](https://tools.ietf.org/html/rfc7230#section-3.1.1):

> HTTP does not place a predefined limit on the length of a
> request-line, as described in Section 2.5. [...]
> Various ad hoc limitations on request-line length are found in
> practice.  It is RECOMMENDED that all HTTP senders and recipients
> support, at a minimum, request-line lengths of 8000 octets.

In [section 2.5](https://tools.ietf.org/html/rfc7230#section-2.5):

> HTTP does not have specific length limitations for many of its
> protocol elements because the lengths that might be appropriate will
> vary widely, depending on the deployment context and purpose of the
> implementation.  Hence, interoperability between senders and
> recipients depends on shared expectations regarding what is a
> reasonable length for each protocol element.  Furthermore, what is
> commonly understood to be a reasonable length for some protocol
> elements has changed over the course of the past two decades of HTTP
> use and is expected to continue changing in the future.
> 
> At a minimum, a recipient MUST be able to parse and process protocol
> element lengths that are at least as long as the values that it
> generates for those same protocol elements in other messages.  For
> example, an origin server that publishes very long URI references to
> its own resources needs to be able to parse and process those same
> references when received as a request target.

## The solution I'd like

To comply with RFC7230 and the HTTP/1.1 spec the server _should_ have a configurable `MAX_REQUEST_PATH_LENGTH`. This could be set in the `config\puma.rb` file if required.

## Alternatives considered

At a minimum the server should implement the recommended 8000 octets (which for ASCII URLs I _think_ would be 8000 characters), which would reduce the number of calls my application would have to make. This is imperfect however as it doesn't meet the requirement that the server should have no hard upper limit.

**Comment by dentarg** [comment]
Here's some more issues/PRs about this topic besides https://github.com/puma/puma/issues/404 you refer to: https://github.com/puma/puma/pull/2002, https://github.com/puma/puma/issues/757

**Comment by Laukei** [comment]
I suppose the main difference between this request and those requests is that I'm hoping for the hard limit to be replaced by a config parameter, to allow the server to _in principle_ be able to meet the RFC7230 spec as use case requires.

**Comment by dentarg** [comment]
I think the config option was requested back in 2016 too: https://github.com/puma/puma/issues/757#issuecomment-207039904

Maybe maintainers will reconsider this time... I suspect a pull request could help them do that ;-)

**Comment by Laukei** [comment]
I'll see what I can do!

**Comment by dentarg** [comment]
@Laukei Just a heads-up, I'm not a maintainer, so you might want to wait for input from @nateberkopec before spending too much time on something

**Comment by Laukei** [comment]
Having had a look at the changes in the code for [#404](https://github.com/puma/puma/issues/404) it would be a lot of work for me to make the changes myself anyway, it seems like the values are defined in Java and C modules and I'm not very well versed in these languages, nor do I understand how that interacts with the rest of the application - definitely don't want to spend a lot of time learning about all this just for the PR to be rejected anyway. I'll wait!

**Comment by nateberkopec** [comment]
> It is RECOMMENDED that all HTTP senders and recipients
support, at a minimum, request-line lengths of 8000 octets.

I'm confused about our current limit. Are we at 8000 bits or are we shorter/longer than that?

**Comment by Laukei** [comment]
The current limit is 2048 characters, but how that converts to bits/octets is entirely down to encoding I believe.

**Comment by nateberkopec** [comment]
True. For UTF-8, that would become 4096 bits right? 

I am OK with just cranking the limit up to what an RFC recommends.

**Comment by Laukei** [comment]
UTF-8 varies between 8 bits per character and 32 bits depending on how far up the list the character's encoded value is. If you want to meet the minimum recommendation of 8000 octets without explicitly counting the bytes in the string you could set it to 8000 characters, which would assume they're all 8 bits (which all the ASCII characters will be) - it is after all a recommended _minimum_.

**Comment by nateberkopec** [comment]
That works for me, we'll have to talk about it during review but I'm more or less fine with the approach.
