### ISSUE TITLE
Update Security Advisory for Cookie Bug?

### ISSUE THREAD

**Issue by jules2689** [puma/puma#2142]
**Describe the bug**

The Security Advisory (https://github.com/advisories/GHSA-84j7-475p-hp8v) is suggesting people update to 3.12.3 and 4.3.2.

Both of these versions have a bad bug in cookie setting: https://github.com/puma/puma/issues/2132

Can we update the advisory to update 3.12.3 -> 3.12.4 and 4.3.2 -> 4.3.3?

**Comment by nateberkopec** [comment]
Done

**Comment by dentarg** [comment]
Oh, https://github.com/puma/puma/security/advisories/GHSA-84j7-475p-hp8v is updated but https://github.com/advisories/GHSA-84j7-475p-hp8v still has the older versions... maybe you can't change that @nateberkopec?

**Comment by dentarg** [comment]
To avoid the GitHub link magic: 

* `https://github.com/puma/puma/security/advisories/GHSA-84j7-475p-hp8v` (updated)
* `https://github.com/advisories/GHSA-84j7-475p-hp8v` (not updated, originally linked in this issue)

**Comment by nateberkopec** [comment]
@dentarg Exactly. No edit button on that page for me.

**Comment by jules2689** [comment]
Hey @nateberkopec thanks for updating the advisory!
@dentarg thanks for bringing the sync issue between the advisories.

I'm actually a developer at GitHub, so I've raised this as an issue with the relevant team.

`/advisories` is a curated catalog by us, but we didn't update properly when you changed yours. We've gone ahead and manually updated the `https://github.com/advisories/GHSA-84j7-475p-hp8v` link with the proper versions, which you should see now!

We also have an issue filed to address this properly! <3 

Many thanks again!

**Comment by nateberkopec** [comment]
Thanks Julian! It's a great feature and really made management of these issues 100x easier from a maintainer perspective.
