### ISSUE TITLE
Ruby 2.2 build failing

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2145]
https://github.com/puma/puma/pull/2112#issuecomment-594171653

**Comment by nateberkopec** [comment]
Man, even getting 2.2 installed locally is such a pain 😆

**Comment by MSP-Greg** [comment]
Assuming you're on macOS, you might look at ruby-2.2.10-macos-latest.tar.gz at:

https://github.com/ruby/ruby-builder/releases

These are the binaries used by Actions.  Of course, only for CI...

**Comment by MSP-Greg** [comment]
I'll try updating RubyGems / Bundler...

**Comment by MSP-Greg** [comment]
It just passed on Ubuntu & macOS, I'll do a PR
