### ISSUE TITLE
test_term_not_accepts_new_connections() may fail in non-English locale enviroment

### ISSUE THREAD

**Issue by dleidert** [puma/puma#2149]
**Describe the bug**
The test `test_term_not_accepts_new_connections()` can fail if the locale is not English. `curl` then will report a localized error and the test will fail. The fix is quite easy:
<https://salsa.debian.org/ruby-team/puma/-/blob/debian/experimental/debian/patches/0013-fix-test-term-not-accepts-new-connections.patch>

**Expected behavior**
The test should be locale independent.

**Desktop (please complete the following information):**
Debian Linux Sid
puma 4.3.1, 4.3.3

**Comment by nateberkopec** [comment]
Thanks for the report @dleidert!
