### ISSUE TITLE
Open all state/sock files in their own temporary directory, and rm them after receiving stop/kill signal

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2150]
I was just wondering why my tests were failing locally, then I realized that I had the sock/state files in my test directory because they hadn't been cleaned up properly:

```
/test/test_puma.state
/test/test_server.sock
/test/test_control.sock
```

I used to like not having these in .gitignore because I use `git status` to see if my current state is "clean", but now I have to look for those socket files manually (which is kinda hard because when alphabetically sorted in the test dir they really blend in).

Thoughts anyone?

**Comment by nateberkopec** [comment]
Maybe we could just put them in a different folder so I can just `rm -rf test/tmp/*`

**Comment by cjlarose** [comment]
I just got bitten this also. I think removing the files from `.gitignore` is a good first step.

It'd also be nice to figure out how to clean these up automatically long term. I think I was getting them after running tests, but sending `^C` to them before they finished. It seems like there might be an opportunity to make sure those files are still cleaned up on interrupt exceptions (SIGINT).

**Comment by dentarg** [comment]
Is it possible to use [`Tempfile`](https://ruby-doc.org/stdlib-2.2.4/libdoc/tempfile/rdoc/Tempfile.html) for these files?

**Comment by cjlarose** [comment]
`Tempfile`'s a good idea, too. Some tests already use `Tempfile`, so maybe it's just a matter of making sure all tests do the same.

**Comment by nateberkopec** [comment]
>  It seems like there might be an opportunity to make sure those files are still cleaned up on interrupt exceptions (SIGINT).

Yeah, that would be great!

**Comment by nateberkopec** [comment]
Changed title to reflect what I think could be done.
