### ISSUE TITLE
Fold the old integration tests into the new test suite.

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2172]
These tests are run with `ruby test/shell/run.rb`. 

They should be replaced with new tests in the regular test suite, or removed if they are covering behavior already covered in the regular suite.

**Comment by harrylewis** [comment]
Hey @nateberkopec! I've been digging into `puma` more recently, and would love to make a contribution. This seems like a good place for me to start, given that it is not feature-based.

I have managed to get the test suite to run locally, and will continue to review all the contributing guidelines and code of conduct. I see that there are already some `test/*_integration_*.rb` in the regular suite. I'm assuming the ones in question here should be migrated to a similar format?

Do you have any other advice?

**Comment by nateberkopec** [comment]
Yup, you've got it right!

I think (hope?) that the three old tests should all be able to "fit" in the new format. It may be easier to open PRs one-by-one as you convert each test.

**Comment by harrylewis** [comment]
Really happy to have contributed to this amazing project! I can continue to migrate the remaining 2 tests. I noticed a lot of test readability/speed improvements in #2241, which also make changes to the integration tests in question.

Do you want to defer to those changes, or should I go ahead and continue migrating these?

**Comment by wjordan** [comment]
I would encourage you to continue! #2241 has a whole bunch of changes that are all going to need to be broken out into smaller PRs anyway, so I'll leave this particular change to you. I prefer the approach you took of folding the tests into the existing test class to take advantage of the existing helpers as well.

**Comment by sudheer-meka** [comment]
Hey @nateberkopec I have created a PR 2346, one of the check is failing, can you please check why.

**Comment by sudheer-meka** [comment]
Hey @nateberkopec I have created a PR [2347](https://github.com/puma/puma/pull/2347) which moved the final integration test to regular suite but few of the checks are failing again, can you please check why.
