### ISSUE TITLE
request.ip returns ip with 0 port

### ISSUE THREAD

**Issue by JonasJasas** [puma/puma#2175]
**Describe the bug**
In development stage if `set_remote_address header: 'X-Forwarded-For'` is used, `request.ip` returns IP address followed by `:0`

**Puma config:**
set_remote_address header: 'X-Forwarded-For'

**To Reproduce**
Create rails app, add `set_remote_address header: 'X-Forwarded-For'` to config and call `request.ip` in action.

**Expected behavior**
`request.ip` should return just IP address.

**Desktop (please complete the following information):**
 - OS: Linux
 - Puma Version: 4.3.3

**Comment by nateberkopec** [comment]
Repro: 

```ruby 
Rails.application.routes.draw do
  root to: proc { |env| [200, {}, [Rack::Request.new(env).ip]] }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
```

**Comment by nateberkopec** [comment]
Confirming also that `"REMOTE_ADDR"=>"127.0.0.1:0"`

**Comment by nateberkopec** [comment]
OK, so this is because [we set it to that here](https://github.com/puma/puma/blob/761a093446eaefd7aae3b778a7ed30ed5a05039a/lib/puma/client.rb#L268). I'm not sure if we're wrong or not yet, though. Certainly it would be weird to get this back from an IPv6-bound connection, though.

**Comment by nateberkopec** [comment]
I did some looking around and I think including the port here is probably a mistake, as I can't see anyone else including it. It's also not very useful information in this case.
