### ISSUE TITLE
Fix the JRuby tests that skip/fail for no good reason

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2183]
The only tests we should be skipping on JRuby are the ones where the feature isn't supported by the platform. I had to add a bunch of skips to get us back to green (`skip_on`). We should remove these test-by-test. 

I'm 99% confident that the problem in all these cases is just racy tests rather than code, but the only way to be sure is a passing test.

**Comment by dentarg** [comment]
Related issue about JRuby build failures (back when tests ran on Travis CI): https://github.com/puma/puma/issues/1982

**Comment by dentarg** [comment]
Here are the recent commits that skipped tests for JRuby: https://github.com/puma/puma/compare/00e20d8bcadfa3871099a96b3043af4f179be204...e42d3a65cd387d689d615f18b46d16d3acc1ed50
