### ISSUE TITLE
Systemd notify and watchdog support

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2184]
https://github.com/mperham/sidekiq/issues/4488

**Comment by acmh** [comment]
Hi @nateberkopec , is this still relevant? I want to take a look at this feature.

**Comment by nateberkopec** [comment]
Yes, definitely relevant!

**Comment by TheoLassonder** [comment]
+1 We'd like this, too

**Comment by dentarg** [comment]
Solved by https://github.com/puma/puma/pull/2438 (merged to master at https://github.com/puma/puma/commit/288a4cf756852a4837c77ee70d7fdcca1edb8e82)
