### ISSUE TITLE
Docs: missing doc for Alternative Forking Configuration 

### ISSUE THREAD

**Issue by tasawar-hussain** [puma/puma#2196]
**Describe the bug**
In the [systemd](https://github.com/puma/puma/blob/master/docs/systemd.md#alternative-forking-configurationl) docs, link to **Alternative Forking Configuration** is missing from the second paragraph of **Service Configuration** section.

**Comment by dentarg** [comment]
It is because it has been removed from the upcoming Puma version: https://github.com/puma/puma/commit/636732c44774a3dc49474f3fb0627fb3a6aaafb3#diff-38e9e6fc9e4f94c189480d539dbbcda9

I created a PR to remove the old link: #2197

**Comment by dentarg** [comment]
You can view the docs with this link: https://github.com/puma/puma/blob/v4.3.3/docs/systemd.md#alternative-forking-configuration
