### ISSUE TITLE
How does one see the number of threads set?

### ISSUE THREAD

**Issue by krzkrzkrz** [puma/puma#2199]
How does one see the number of threads set per worker process? i.e. not active running, just the total number set?

I cant seem to find this anywhere in the documentation. Would be great to have as a feature

**Comment by nateberkopec** [comment]
It's the third line of the startup output:

```
 speedshop $ be puma test/rackup/hello.ru
Puma starting in single mode...
* Version 4.3.3 (ruby 2.7.0-p0), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
```

Or were you referring to something else?

**Comment by krzkrzkrz** [comment]
Is there any way to show this information via a command line?

**Comment by nateberkopec** [comment]
I think I still don't understand.

Maybe you can share an example of what you're trying to accomplish? i.e. do you wish you could call `Puma.threads` or `$ puma --show-config` or something? Or tell me more about what you're trying to get this number for?

**Comment by krzkrzkrz** [comment]
Its related to this issue https://github.com/ajgon/opsworks_ruby/issues/235

Basically, I need to be verify how many threads were set for Puma

**Comment by nateberkopec** [comment]
Threads in Puma are named. Maybe iterate through `Thread.list` and check each thread's `.name`?

**Comment by nateberkopec** [comment]
Wait, misunderstood your Q. You need the number of maximum threads, not active.

**Comment by nateberkopec** [comment]
I don't think this is possible, because Puma's launcher is not global, so there is no constant or globally accessible variable to access the configuration through. 

Why can't you just check your logs?

**Comment by dentarg** [comment]
@krzkrzkrz  What about using the control/status server? https://github.com/puma/puma/tree/3bf45fbf34ab1de4b3c3baeaa1f84686fef1f2b3#controlstatus-server

```
$ bundle e puma --threads 11 --control-url tcp://127.0.0.1:9293 --control-token foo hello.ru
Puma starting in single mode...
* Version 4.3.3 (ruby 2.6.5-p114), codename: Mysterious Traveller
* Min threads: 11, max threads: 11
* Environment: development
* Listening on tcp://0.0.0.0:9292
* Starting control server on tcp://127.0.0.1:9293
Use Ctrl-C to stop
```

```
$ pumactl --control-url tcp://127.0.0.1:9293 --control-token foo stats
Command stats sent success
{ "started_at": "2020-03-24T11:12:09Z", "backlog": 0, "running": 11, "pool_capacity": 11, "max_threads": 11 }
```

**Comment by nateberkopec** [comment]
Oh yeah! `Puma.stats` too.

**Comment by krzkrzkrz** [comment]
Where are you supposed to execute `Puma.stats`?

**Comment by nateberkopec** [comment]
Should be accessible anywhere. You'd have to run it after Puma was configured, which I think would be pretty much anywhere in your application (rails initializer, for example).

**Comment by feliperaul** [comment]
`Puma.stats` is great, but notice it won't obviously work in your Rails console.

If you want to display that info inside your Rails app, like /admin/debug or something, you can use:

```erb
<pre>
  <%= JSON.pretty_generate(JSON.parse(Puma.stats)) %>
</pre>
```
