### ISSUE TITLE
test_control_ssl aborting with openssl-1.1.1e

### ISSUE THREAD

**Issue by junaruga** [puma/puma#2205]
**Describe the bug**
> A clear and concise description of what the bug is.

test_control_ssl test is aboring with the latest version OpenSSL 1.1.1e. This issue does not happen on Openssl 1.1.1d.

```
$ bundle exec rake test TEST=test/test_pumactl.rb TESTOPTS="--name=test_control_ssl -v"
install -c tmp/x86_64-linux/puma_http11/2.7.0/puma_http11.so lib/puma/puma_http11.so
cp tmp/x86_64-linux/puma_http11/2.7.0/puma_http11.so tmp/x86_64-linux/stage/lib/puma/puma_http11.so
Run options: --name=test_control_ssl -v --seed 44885

# Running:

TestPumaControlCli#test_control_ssl = rake aborted!
Command failed with status (1)
/home/jaruga/git/puma/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/ruby-2.7.0/bin/bundle:23:in `load'
/usr/local/ruby-2.7.0/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Puma config:**

> Please copy-paste your Puma config AND your command line options here.

Puma config is not needed to this issue, as it can be reproduced in `rake test`.

**To Reproduce**
> Please add reproduction steps here.

> Your issue will be solved very quickly if you can reproduce it with a "hello world" rack application. To do this, copy this into a file called `hello.ru`:

I could not reproduce the issue with the `hello.ru`.

> There is also a Dockerfile available for reproducing Linux-specific issues. To use:

I can work to reproduce it with `Dockerfile`.

This PR https://github.com/puma/puma/pull/2204 is to reproduce the issue with openssl-1.1.1.e . You can see [the log](https://github.com/puma/puma/pull/2204/checks?check_run_id=537473558#step:7:137).

Here is the reproducing steps on your local.

1. Install openssl-1.1.1e. (in case of your host CPU architecture is x86_64).

```
$ uname -m
x86_64
```

```
OPENSSL_VERSION=1.1.1e
OPENSSL_DIR="/usr/local/openssl-${OPENSSL_VERSION}"

wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
tar xzvf openssl-${OPENSSL_VERSION}.tar.gz

cd openssl-${OPENSSL_VERSION}
./Configure --prefix=${OPENSSL_DIR} linux-x86_64
make
make install_sw

export PATH="${OPENSSL_DIR}/bin:${PATH}"
export CFLAGS="-I${OPENSSL_DIR}/include"
export LDFLAGS="-L${OPENSSL_DIR}/lib"
export LD_LIBRARY_PATH="${OPENSSL_DIR}/lib"
export PKG_CONFIG_PATH="${OPENSSL_DIR}/lib/pkgconfig"
```

2. Check if the openssl is installed correctly.

```
$ openssl version
OpenSSL 1.1.1e  17 Mar 2020
```

3. Run tests.

```
bundle install --path=.bundle/puma
bundle exec rake compile
bundle exec rake test TEST=test/test_pumactl.rb TESTOPTS="--name=test_control_ssl -v"
```

**Expected behavior**
> A clear and concise description of what you expected to happen.

The `test_control_ssl` test passes with on openssl-1.1.1e.

**Desktop (please complete the following information):**
 - OS: Linux Fedora 31
 - Puma Version: The latest master branch `0b737cce42746d8226701520f35685e0624e061b`.

**Comment by junaruga** [comment]
As a reference, here is the result of `strace ...`.

```
$ strace bundle exec rake test TEST=test/test_pumactl.rb TESTOPTS="--name=test_control_ssl -v"
...
# Running:

TestPumaControlCli#test_control_ssl = ) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=0, si_uid=28707, si_status=1, si_utime=30, si_stime=4} ---
getpid()                                = 75120 
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
timer_settime(0, 0, {it_interval={tv_sec=0, tv_nsec=100000000}, it_value={tv_sec=0, tv_nsec=100000000}}, NULL) = 0
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
timer_settime(0, 0, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=0, tv_nsec=0}}, NULL) = 0
read(3, "\1\0\0\0\0\0\0\0", 8)          = 8
wait4(75123, [{WIFEXITED(s) && WEXITSTATUS(s) == 1}], WNOHANG, NULL) = 75123 
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
read(3, "\1\0\0\0\0\0\0\0", 8)          = 8
write(2, "rake aborted!\n", 14rake aborted!
...
```

**Comment by MSP-Greg** [comment]
@junaruga

The MinGW build is passed with 1.1.1e.  See the test at:

https://github.com/puma/puma/runs/537473450?check_suite_focus=true#step:6:47

The top of the test log shows the OpenSSL versions.

Interesting.  I've got a patch (for OpenSSL 1.1.1e) added to the Ruby build, but that means that the test is using Ruby's OpenSSL stdlib?

**Comment by junaruga** [comment]
> The MinGW build is passed with 1.1.1e. See the test at:
> ...
> Interesting. I've got a patch (for OpenSSL 1.1.1e) added to the Ruby build, but that means that the test is using Ruby's OpenSSL stdlib?

Seeing your log, possibly I assume the build is succeeded because the patch used for the openssl-1.1.1e MinGW package.

Yes, the test `test_control_ssl` is using Ruby's OpenSSL stdlib by `Puma::ControlCLI` class, as you mentioned.

This issue is originally observed on Fedora rawhide (= Fedora 33).

The issue happens with `openssl-libs 1:1.1.1e-1.fc33` (`1.1.1e`'s release version `1`).
And now I confirmed that it does not happen with `openssl-libs 1:1.1.1e-2.fc33` (`1.1.1e`'s release version `2`) that was released last night.

Here is [the patch file: openssl-1.1.1-eof-error-revert.patch](https://src.fedoraproject.org/rpms/openssl/c/ea310218f3fb1a363940c95a2bb452d2e07d951b?branch=master) applied to `1:1.1.1e-2.fc33`, and [the email](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/O6L32KT4H2ZRK4E5JLZ2FFTVCJFYUGU6/) posted by the Fedora openssl RPM package maintainer.

**Comment by MSP-Greg** [comment]
I'm kind of waiting for the dust to settle on this.  I would consider this to be a breaking change to OpenSSL, maybe they'll revert it and release 1.1.1f.

If not, band-aid time.

Brief description - lots of code that interfaces to OpenSSL translates SSL errors to errors more friendly to the app/platform.  Both Puma and the Ruby OpenSSL stdlib do this.

With 1.1.1e, the handling of an SSL error that was previously translated to a socket style eof error was changed, such that the translation doesn't work anymore and the native SSL error passes thru the OpenSSL stdlib...

I believe the change in handling breaks line 170 (more investigating later):
https://github.com/puma/puma/blob/0b737cce42746d8226701520f35685e0624e061b/lib/puma/control_cli.rb#L168-L172

**Comment by junaruga** [comment]
Alright. Let's wait. Thanks for the explanation about the brief description.

**Comment by MSP-Greg** [comment]
> Alright. Let's wait.

Screw it.  I've dealt with OpenSSL re a breaking change issue during a beta, and they're good people, but this might take some time to sort out.

Re this PR, I think it should either be accepted as is, or make it a separate workflow file that can be disabled when not needed.  Certainly helpful for testing against brand new OpenSSL releases. [ruby/openssl](https://github.com/ruby/openssl/blob/2c43241dc0ed90062f160d24fc9fcae7bec86518/.github/workflows/test.yml#L81-L96) does something similar in their CI.

I'm submitting a PR that fixes the issue shortly.

**Comment by junaruga** [comment]
> Re this PR, I think it should either be accepted as is, or make it a separate workflow file that can be disabled when not needed. Certainly helpful for testing against brand new OpenSSL releases. ruby/openssl does something similar in their CI.

Sure. I agree with it.

> I'm submitting a PR that fixes the issue shortly.

Thanks for PR!

**Comment by MSP-Greg** [comment]
@junaruga

With the breaking change in 1.1.1e reverted, I'll close this.  I'm sure we'll all met again when CI starts running against OpenSSL 3.0...

**Comment by junaruga** [comment]
@MSP-Greg Sure. I am okay to close it for now. Yeah let' wait the coming OpenSSL 3.0..
