### ISSUE TITLE
Socket timeout writing data

### ISSUE THREAD

**Issue by ArtemVarnavskiy** [puma/puma#2217]
**Describe the bug**
I I'm developing a web-app using sinatra+puma. 
But my web-app sometimes hangs during http-request (sometimes everything works correctly).
Only helps a key combination "CTRL+C" in CMD.
In the logs I see an error: "Broken pipe" and "Socket timeout writing data"
![image](https://user-images.githubusercontent.com/50958354/78700050-83bda100-790d-11ea-917b-4b9a17164923.png)

Most likely the problem is not in Puma, but I need help.

**Puma config:**
I don't have Puma config

**To Reproduce**
1. Start app
2. Send requests (get/post) by clicking on sections of my site.

Run it with:
bundle exec rackup

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Puma Version: 4.3.3
 - Sinatra: 2.0.8.1

**Comment by nateberkopec** [comment]
Looks like you're having a problem with loading ERB - see: those other exceptions. The socket timeout is just a consequence of that.
