### ISSUE TITLE
Rackup overrides CLI preference for app

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2225]
**Describe the bug**

Puma should always prefer the rackup file specified by the CLI, but if the `rackup` DSL command is used, it does not.

Related: #1401

**Puma config:**

Using the test fixtures in the repo: 

```
rackup "test/rackup/hello-env.ru"
```

**To Reproduce**

```
bin/puma -C my_rackup_config.rb test/rackup/hello.ru
```

...should return a Hello World! response, but runs the hello-env app instead.

**Comment by acmh** [comment]
@nateberkopec, can you help me to solve this? I want to do my first contribution to this amazing project that I have been using for the last 3 years! And I want to solidify my knowledge on puma web server.

Thanks for your time!

**Comment by nateberkopec** [comment]
Hi @acmh. Look at CONTRIBUTING.md if you haven't already. Glad to have you on board!

1. Write a test first. Take a look at the tests in the `integration` files, they're probably the closest. There are probably a few existing tests for config that may help too. Once you have a failing test, you can look at solutions.
2. Solution: Will probably involve setting the underlying options correctly in either `dsl.rb` or `configuration.rb`.
