### ISSUE TITLE
Debug logging for 4xx/5xx

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2235]
We need opt-in settings for dumping all info we have about bad requests/exceptions. This happens in many places in the code and we should use a unified interface as well.

Related to #2232

**Comment by acmh** [comment]
@nateberkopec, how do you imagine this feature? We will permit users to provide a logger and set a default for people that don't want to set one? Do we need to be Rails compliant? I mean, use the Rails logger when defined.

I don't understand when you say:

> we should use a unified interface as well

**Comment by nateberkopec** [comment]
@acmh basically for anywhere that Puma can rescue exceptions, I'd like options to dump the entire stack. Anywhere that Puma rescues exceptions, it should call _the same method_ (the "unified interface" part).

**Comment by nateberkopec** [comment]
For example in #2232, I don't know what request caused that error. I'd like the stack, the rack env, and the request, but I can't get any of that info. There should be a "debug mode" that flips to log all of this info (default off OFC). That means that all places that rescue exceptions should use the same method for logging exceptions, so they can all check this option and dump everything we know to the logger.
