### ISSUE TITLE
No such file or directory - /tmp/puma-status-1363809668331-14055

### ISSUE THREAD

**Issue by ponny** [puma/puma#224]
Every time I try to get a status from my app, it sends this message: "No such file or directory - /tmp/puma-status-1363809668331-14055"

I've tracked the code down to this point: pumactl --state /home/rails/MyApp/current/tmp/puma/state stats

The state file does contain a reference to this file but it does not exist:
    :control_url: unix:///tmp/puma-status-1363809668331-14055
    :control_url_temp: /tmp/puma-status-1363809668331-14055
    :control_auth_token: [hex]

Is there anything I might be missing that would create these files?  I had my app started a while ago but now I cannot seem to get it started.

**Comment by slavajacobson** [comment]
I am getting the same problem here... please help!

**Comment by slavajacobson** [comment]
```
# Change to match your CPU core count
workers 2

# Min and Max threads per worker
threads 1, 6

app_dir = File.expand_path("../../../..", __FILE__)
shared_dir = "#{app_dir}/shared"

# Default to production
rails_env = ENV['RAILS_ENV'] || "production"
environment rails_env

# Set up socket location
bind "unix://home/deployer/apps/loco-engine/shared/tmp/sockets/loco-engine-puma.sock"

#{}"unix://#{shared_dir}/sockets/puma.sock"

# Logging
stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true

# Set master PID and state locations
pidfile "/home/deployer/apps/loco-engine/shared/tmp/pids/puma.pid"
state_path "/home/deployer/apps/loco-engine/shared/tmp/pids/puma.state"
activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
end
```

**Comment by lalitlogical** [comment]
I have also facing the same issue as below.

No such file or directory - connect(2) for "/tmp/puma-status-1438845213892-27028"

I have set up production server on EC2 and using Nginx and puma for my Rails app. I am using capistrano 3 for deployment. It has worked fine for initial deployment. Puma start successfully, but when I want to restart the puma server, I am getting such error.

Please help!

**Comment by lalitlogical** [comment]
Hi @ponny, Can you please help me to resolve this issue?

I am able to run 'cap production deploy:initial' command successfully. But when I want to redeploy something, puma does not restart and gave this error.

**Comment by godalphul** [comment]
@lalitlogical what does your /config/puma.rb and /config/deploy.rb file look like

**Comment by lalitlogical** [comment]
/config/puma.rb
# ------------------------------------------------------
# Change to match your CPU core count
workers 1

# Min and Max threads per worker
threads 4, 16

# app_dir = File.expand_path("../..", __FILE__)
app_dir = "/var/deploy/myapp/current"
shared_dir = "/var/deploy/myapp/shared"

# Default to production
port        ENV['PORT']     || 3000
rails_env = ENV['RAILS_ENV'] || "production"
environment rails_env

# Set up socket location
bind "unix://#{shared_dir}/tmp/sockets/puma.sock"

# Logging
stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true

# Set master PID and state locations
pidfile "#{app_dir}/tmp/pids/puma.pid"
state_path "#{app_dir}/tmp/pids/puma.state"
activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
end
# ------------------------------------------------------

/config/deploy.rb
# ------------------------------------------------------
# Puma Server Configuration
set :puma_threads,    [4, 16]
set :puma_workers,    1

# Don't change these unless you know what you're doing
set :pty,             true
set :use_sudo,        false
set :puma_bind,       "unix://#{shared_path}/tmp/sockets/puma.sock"
# set :puma_conf,       "#{shared_path}/puma.rb"
set :puma_state,      "#{shared_path}/tmp/pids/puma.state"
set :puma_pid,        "#{shared_path}/tmp/pids/puma.pid"
set :puma_access_log, "#{release_path}/log/puma.error.log"
set :puma_error_log,  "#{release_path}/log/puma.access.log"
set :puma_preload_app, true
set :puma_worker_timeout, nil
set :puma_init_active_record, true

namespace :puma do
  desc 'Create Directories for Puma Pids and Socket'
  task :make_dirs do
    on roles(:app) do
      execute "mkdir #{shared_path}/tmp/sockets -p"
      execute "mkdir #{shared_path}/tmp/pids -p"
    end
  end

  before :start, :make_dirs
end

namespace :deploy do
  desc "Make sure local git is in sync with remote."
  task :check_revision do
    on roles(:app) do
      unless `git rev-parse HEAD` == `git rev-parse origin/capistrano`
        puts "WARNING: HEAD is not the same as origin/capistrano"
        puts "Run `git push` to sync changes."
        exit
      end
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      before 'deploy:restart', 'puma:start'
      invoke 'deploy'
    end
  end

  desc 'Restart application'
  task :restart do
    on roles(:app), in: :sequence, wait: 5 do
      invoke 'puma:restart'
    end
  end

  before :starting,     :check_revision
  after  :finishing,    :compile_assets
  after  :finishing,    :cleanup
  after  :finishing,    :restart
end
# ------------------------------------------------------

**Comment by h0lyalg0rithm** [comment]
@lalitlogical I have the same configuration as yours.

**Comment by lalitlogical** [comment]
@h0lyalg0rithm, Are you running the below commands as in sequence?

cap production deploy:check
cap production puma:config
/*If you need nginx config also*/
cap production puma:nginx_config 
/* First time deploy */
cap production deploy:initial

/* After first time deploy */
cap production deploy

If yes, then check your app directories paths for same. 

For some thime(when you are not able to setup it properly) you just need to clear your root folder's (i.e. '/home/dev/apps/dev') files, folder and run again above commands in same sequence.

**Comment by h0lyalg0rithm** [comment]
I tried the above.I even deleted the apps directory.
I set the puma bind to the default as well as /var/run/puma.sock 
None of these work.

My current project is running puma 2.12.2
I had project running puma 2.11.3 with same config and it works.
They both run the same version of capistrano3-puma

**Comment by skinofstars** [comment]
Did this ever get resolved? Hitting the same issue. The curious thing to me is the attempted connection to `/tmp/puma-status-1444...`, whereas pid/state/sock files locations are explicitly declared. 

@lalitlogical how did you solve this?

**Comment by lalitlogical** [comment]
@skinofstars, I have posted another issue for above at https://github.com/seuros/capistrano-puma/issues/120. Please take a look into this.

But for now, I am using pro version of phusion passenger (with thread functionality).

**Comment by aleks** [comment]
Same problem here. Any results?

**Comment by lalitlogical** [comment]
https://github.com/seuros/capistrano-puma/issues/120

**Comment by aconfee** [comment]
Hello,

Did anyone figure out what the root cause of this is? I'm not using capistrano and seeing this issue. Does puma.rb config need to be in a specific folder? Or puma.state? Any help is very much appreciated!

**Comment by Rolando-Barbella** [comment]
@aconfee Did you manage to fix this?

**Comment by Rolando-Barbella** [comment]
I did: 
pkill -f rpush
start-nameoftheapp
It work for now
