### ISSUE TITLE
pumactl: How to specify root dir?

### ISSUE THREAD

**Issue by anon987654321** [puma/puma#2243]
Is there a way to specify the root dir of my app so I don't have to cd to it first in my [startup script](https://gist.github.com/anon987654321/72ab1ad50bf44ec0fac0214ca4fb55c9)?

Thanks!

**Comment by anon987654321** [comment]
I notice puma has this option:

    --dir DIR                    Change to DIR before starting

**Comment by dentarg** [comment]
Seems like the same answer I gave in #2242 solves this too, `pumactl -F app/production_config.rb start` seems to work for me. I guess it gets more complicated if you are using Bundler.

Why do you want to avoid `cd` into your app directory?

**Comment by anon987654321** [comment]
I can live with that, thanks!

> Why do you want to avoid cd into your app directory?

Just for simplicity I guess. Would look a bit out of place in my startup script as well, but that's just cosmetics.

**Comment by anon987654321** [comment]
Specifying the full path to the config file and having Puma automatically find everything else does not work here:
```
/root# pumactl --config-file /var/www/htdocs/myapp/config/puma.rb start
Puma starting in single mode...
* Version 4.3.3 (ruby 2.6.6-p146), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
* Environment: production
ERROR: No application configured, nothing to run
/root# cd /var/www/htdocs/myapp
/var/www/htdocs/myapp# pumactl --config-file /var/www/htdocs/myapp/config/puma.rb start
Puma starting in single mode...
* Version 4.3.3 (ruby 2.6.6-p146), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
* Environment: production
* Listening on tcp://127.0.0.1:8000
* Listening on ssl://127.0.0.1:8001?key=/etc/ssl/private/myapp.key&cert=/etc/ssl/myapp.crt
Use Ctrl-C to stop
```

I also tried adding `dir` to the config but to no avail:
```
undefined method `dir' for #<Puma::DSL:0x000007e3a21617e0>
```
