### ISSUE TITLE
Are puma and pumactl unnecessary duplicates?

### ISSUE THREAD

**Issue by anon987654321** [puma/puma#2244]
Is it just me or is there some inconcistency between the startup options in puma and pumactl? Some switches are missing, some named differently etc.

Wouldn't it be simpler if pumactl was just a wrapper for the puma command, except ofcourse with the additional daemon management options?

Or maybe pumactl is deprecated, and one is supposed to just use puma combined with the `--daemon` switch and some [kill tool](http://ports.su/sysutils/zap)?

Thanks!

**Comment by dentarg** [comment]
There might be some inconsistencies, I think the CLI tools have just grown organically with contributions to the Puma project.

Please not that daemonization (`--daemon`) [has been removed](https://github.com/puma/puma/blob/774c460e609f6ab9886cc8559bf985db31b585c6/History.md#master) (#2170, #1983) from the master branch and will not be in the next release of Puma (5.0). So it is probably wise to adjust your deployment after that.

**Comment by anon987654321** [comment]
Gonna cram all this stuff into a new feature request and do my best to help once I become skilled enough.

> Please not that daemonization (--daemon) has been removed (#2170, #1983) from the master branch and will not be in the next release of Puma (5.0). So it is probably wise to adjust your deployment after that.

Awesome, thanks for the heads up!
