### ISSUE TITLE
Cannot get puma to work with systemctl when configured for multiple workers 

### ISSUE THREAD

**Issue by benwalsh** [puma/puma#2246]
**Disclaimer**
This is happening on the interface between `puma` and `systemctl` so I'm not 100% certain if it's a `puma` issue 🐅 .

**The Issue**
With `workers` set to 1, everything works as expected. When `workers` is set to a higher number, the service appears to fail, according to `systemctl status puma` and `/var/log/syslog`, saying that there is already a server bound to the socket. However, the puma process is running and the site is serving traffic.

`systemctl status puma` shows:
```
lib/puma/binder.rb:323:in `add_unix_listener': There is already a server bound to: /tmp/puma.sock (RuntimeError)

systemd[1]: puma.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Puma HTTP Server.
```

Similarly `systemctl is-active puma` says:
```
failed
```

But! `puma` is running:
```
root     28063  0:00 puma 4.3.3 (unix:///tmp/puma.sock) [20200502141845]
root     28069  0:16 puma: cluster worker 0: 28063 [20200502141845]
root     28070  0:16 puma: cluster worker 1: 28063 [20200502141845]
```

The `puma.state` file shows the correct process ID:
```
---
pid: 28063
control_url: unix:///tmp/puma-status-<numbers>-28061
control_auth_token: <token>
```

And the server is live and serving traffic.

However, `systemctl` doesn't believe any of this, so the service cannot be stopped or restarted.

Given the error message, I thought about how to bind each worker to its own socket. I tried this in `puma.rb`:

```
bind 'unix:///tmp/puma.1.sock'
bind 'unix:///tmp/puma.2.sock'
```

And did something similar in my `nginx.conf`:

```
upstream puma {  
  server unix:///tmp/puma.1.sock fail_timeout=0;
  server unix:///tmp/puma.2.sock fail_timeout=0;
}
```

I remove the `puma.state` file, manually kill the `puma` processes, restart `nginx`, and start `puma` again.

The same error shows in `systemctl status` and in `syslog`:

```
`add_unix_listener': There is already a server bound to: /tmp/puma.1.sock
```

But `ps` shows that `puma` is running happily, as before, but now with two bindings:

```
root     28299  0:00 puma 4.3.3 (unix:///tmp/puma.1.sock,unix:///tmp/puma.2.sock) [20200502141845]
root     28305  19:03   0:16 puma: cluster worker 0: 28299 [20200502141845]
root     28306  19:03   0:16 puma: cluster worker 1: 28299 [20200502141845]
```

**The questions**
- Why does `systemctl` not maintain its awareness and control the puma process?
- How do I configure `puma` to work with `systemctl` when multiple workers are specified?

**Puma configuration**

My `config/puma.rb` file:
```
require 'yaml'

opts = @config.options.user_options
rails_env = opts&.dig(:environment) || ENV['RAILS_ENV'] || 'development'
deployed = %w[staging production].include?(rails_env)
dir = deployed ? '/home/ubuntu/rails/appname/current' : File.expand_path(File.dirname(__dir__))
config = YAML.load_file(File.join(dir, 'config', 'provisioning', 'puma.yml'))[rails_env]

environment rails_env
threads 1, config['max_threads']
workers config['workers']

if deployed
  shared_dir = '/home/ubuntu/rails/appname/shared'
  config['workers'].times { |n| bind "unix:///tmp/puma.#{n + 1}.sock" }
  stdout_redirect "#{shared_dir}/log/puma.access.log", "#{shared_dir}/log/puma.error.log", true
  state_path "#{shared_dir}/pids/puma.state"
  daemonize true
  activate_control_app
else
  port opts&.dig(:port) || config['port']
  preload_app!
end

on_worker_boot do
  require 'active_record'
  begin
    ActiveRecord::Base.connection.disconnect!
  rescue StandardError
    ActiveRecord::ConnectionNotEstablished
  end
  ActiveRecord::Base.establish_connection(YAML.load_file("#{dir}/config/database.yml")[rails_env])
end
```

My `/lib/systemd/system/puma.service` file is:
```
[Unit]
Description=Puma HTTP Server
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/home/ubuntu/rails/appname/current

ExecStart=/home/ubuntu/.rvm/gems/ruby-2.7.1/wrappers/bundle exec puma -e staging -C /home/ubuntu/rails/appname/current/config/puma.rb
ExecStop=/home/ubuntu/.rvm/gems/ruby-2.7.1/wrappers/bundle exec pumactl -e staging -F /home/ubuntu/rails/appname/current/config/puma.rb stop
ExecReload=/home/ubuntu/.rvm/gems/ruby-2.7.1/wrappers/bundle exec pumactl -e staging -F /home/ubuntu/rails/appname/current/config/puma.rb phased-restart
PIDFile=/home/ubuntu/rails/appname/shared/pids/puma.pid
Restart=always
KillMode=process

[Install]
WantedBy=multi-user.target
```

**Environment**
- Ubuntu 18.04.4 LTS (AWS)
- Ruby 2.7.1
- Rails 6.0.2.2
- rvm 1.29.10
- nginx 1.14.0
- Bundler 2.1.4

**Comment by dentarg** [comment]
Looks like the same issue as reported in https://github.com/puma/puma/issues/1976

**Comment by benwalsh** [comment]
Well, I got to dive deep into both `puma` and `systemctl` here and learned a lot about both. Of course, the solution was a much simpler one, there's no need for multiple bind statements or anything like that. Solved by setting the `systemctl` `[Service] Type` directive to `forking`.
