### ISSUE TITLE
Where did examples/puma.rb go?

### ISSUE THREAD

**Issue by anon987654321** [puma/puma#2249]
Didn't that file used to be there showing all available config options so that the average user doesn't have to look through the code to find them?

Thanks!

**Comment by dentarg** [comment]
It did, see https://github.com/puma/puma/pull/1883 and https://github.com/puma/puma/issues/1876

As written there, you can instead look in dsl.rb, and it will have the benefit of always being accurate

**Comment by anon987654321** [comment]
Cool, cheers!
