### ISSUE TITLE
Puma::MiniSSL::SSLError: OpenSSL error: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher

### ISSUE THREAD

**Issue by atul15anand** [puma/puma#2251]
The rails server starts in the terminal. But when loaded in the browser, it gives the above error.

Puma config: puma version 4.3.3

puma (4.3.3, 4.3.0, 4.0.0)
    Author: Evan Phoenix
    Homepage: http://puma.io
    License: BSD-3-Clause
    Installed at (4.3.3): /home/atul/.rvm/gems/ruby-2.6.3
    (4.3.0): /home/atul/.rvm/gems/ruby-2.6.3
    (4.0.0): /home/atul/.rvm/gems/ruby-2.6.3

Desktop version: Ubuntu 20.04.
rails version: Rails 6.0.2.1
ruby version : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

**Comment by nateberkopec** [comment]
This is usually caused by certificate/key misconfiguration (sometimes it can't be found, other times you generated them incorrectly).

If you can post a key, cert and puma config that reproduces the issue, we can help you, otherwise, you have to figure this out yourself.
