### ISSUE TITLE
Puma incompatible with yard server --gems command

### ISSUE THREAD

**Issue by sgeef** [puma/puma#2252]
**Describe the bug**
Within our company a lot of developers are used to pull up the yard documentation of our installed gems, by doing `yard server --gems`. Since I convinced them to switch to puma, with very good results btw, but now have received several complaints that the puma upgrade is breaking the `yard server --gems` command. 

According to the issue report on the yard gem here: https://github.com/lsegal/yard/issues/988
The issue is that there is no way to start puma without config??

**Puma config:**
Does not apply, works with any project that has a yarn gem and puma server to serve the requests, as far as I could confirm.

**To Reproduce**
Install the yard gem in your project (Latest version, although earlier versions have the same issue since first reported in 2016.
Execute the `yard server --gems` command in any puma project.

**Expected behaviour**
Expected is that yard server, can start without having a puma error.

**Desktop (please complete the following information):**
 - OS: Mac
 - Puma Version: 4.3.1

**Comment by sgeef** [comment]
Just in case I missed something, or this might be helpful this is the error:

```
>> YARD 0.9.25 documentation server at http://localhost:8808
[30616] Puma starting in cluster mode...
[30616] * Version 4.3.1 (ruby 2.6.5-p114), codename: Mysterious Traveller
[30616] * Min threads: 5, max threads: 5
[30616] * Environment: development
[30616] * Process workers: 2
[30616] * Preloading application
[30616] * Listening on tcp://0.0.0.0:8808
[30616] Use Ctrl-C to stop
Traceback (most recent call last):
	15: from /Users/x/.rbenv/versions/2.6.5/bin/yard:23:in `<main>'
	14: from /Users/x/.rbenv/versions/2.6.5/bin/yard:23:in `load'
	13: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.25/bin/yard:13:in `<top (required)>'
	12: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:54:in `run'
	11: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:72:in `run'
	10: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.25/lib/yard/cli/command.rb:14:in `run'
	 9: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.25/lib/yard/cli/server.rb:51:in `run'
	 8: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/yard-0.9.25/lib/yard/server/rack_adapter.rb:66:in `start'
	 7: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:327:in `start'
	 6: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.1/lib/rack/handler/puma.rb:73:in `run'
	 5: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.1/lib/puma/launcher.rb:172:in `run'
	 4: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.1/lib/puma/cluster.rb:467:in `run'
	 3: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:279:in `run_hooks'
	 2: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:279:in `each'
	 1: from /Users/x/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:279:in `block in run_hooks'
config/puma.rb:45:in `block in _load_from': uninitialized constant #<Class:#<Puma::DSL:0x00007fd4a8847f40>>::ActiveRecord (NameError)
```

Also there is an active work-around, which does the job for now, but I prefer to have everything correctly working with puma. ❤️ 

Workaround:
`yard server --gems -s webrick`

**Comment by dentarg** [comment]
Sounds like there's a pull request coming from someone at your company soon! 😉

**Comment by sgeef** [comment]
Haha @dentarg, I would love to help out and make a PR if I would understand what is causing it!

**Comment by sgeef** [comment]
@dentarg I feel lightly ashamed.. I spend several hours looking into the source of both projects before posting the issue.. though after your comment saw the stack trace fails on the `block in run_hooks`

So I went to my projects and both configs contain:

```
before_fork do
  ActiveRecord::Base.connection_pool.disconnect!
end

on_worker_boot do
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
end
```

After changing the before_fork to:

```
before_fork do
  ActiveRecord::Base.connection_pool.disconnect! if defined?(ActiveRecord)
end
```

Everything works completely fine! Anyways Thanks for the quick response!

**Comment by dentarg** [comment]
No worries, we all need [the rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) every now and then. :-)
