### ISSUE TITLE
JRuby tests unstable lately

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2262]
Someone wanna take a look?

**Comment by MSP-Greg** [comment]
I combined PR's #2263, #2264, #2265, & #2268 , and JRuby **seemed** stable, including head.

But, there were still some failures in both macOS MRI and TruffleRuby.

**Comment by nateberkopec** [comment]
Merged 'em all, we'll see what happens.

**Comment by MSP-Greg** [comment]
We've still got the issue with UniquePort.  We either have to fix it or remove it.  I think @wjordan  found some other things that are causing intermittent failures.

After I put all of these in PR #2270 and (I think) fixed UniquePort, I was still getting intermittent failures in my fork.  They were less common.  Actions was also a little odd, so IDK...

**Comment by nateberkopec** [comment]
Fixed!
