### ISSUE TITLE
Missing History.md entry for 4.3.4

### ISSUE THREAD

**Issue by movermeyer** [puma/puma#2274]
**Describe the bug**

There is no entry on [History.md](https://github.com/puma/puma/blob/80dc883de611515b291e475ed867a4a2b64bf959/History.md) for v4.3.4.

**Expected behavior**

There would be an entry for 4.3.4. Users of `puma` rely on this file to gain confidence that nothing will break when they bump the version of `puma` they are using.

**Comment by dentarg** [comment]
Also 3.12.5 have been released: https://rubygems.org/gems/puma/versions

```
4.3.4 - May 18, 2020 (171 KB)
4.3.4 - May 19, 2020 java (199 KB)
...
3.12.5 - May 18, 2020 (163 KB)
3.12.5 - May 19, 2020 java (188 KB)
```

**Comment by dentarg** [comment]
Here are the changes:

* https://github.com/puma/puma/compare/v4.3.3...v4.3.4
* https://github.com/puma/puma/compare/v3.12.4...v3.12.5

**Comment by dentarg** [comment]
Now two new versions have been published to RubyGems.org:

4.3.5 - May 19, 2020 (171 KB)
4.3.5 - May 19, 2020 java (199 KB

3.12.6 - May 19, 2020 (163 KB)
3.12.6 - May 19, 2020 java (190 KB)

**Comment by evanphx** [comment]
Yes, this is expected. The information about the releases will be up soon.

**Comment by nateberkopec** [comment]
https://github.com/puma/puma/commit/ce33a7bb52578e3cfea7379fa811a3fac452baaf#commitcomment-39350098
