### ISSUE TITLE
Commits for version 4.3.5 are missing

### ISSUE THREAD

**Issue by mvz** [puma/puma#2278]
**Describe the bug**
Version 4.3.5 is on rubygems.org, but the corresponding changes are not present in this repository.

**Expected behavior**
A tag v4.3.5 is present in this repository and corresponds to the source for version 4.3.5 on rubygems.org.

**Comment by dentarg** [comment]
@evanphx promised more info soon at https://github.com/puma/puma/issues/2274#issuecomment-631148431

**Comment by nateberkopec** [comment]
Nothing more to add, just confirming that the Rubygems pushes are genuine and approved by all maintainers.

**Comment by dentarg** [comment]
I downloaded the gem files from RubyGems and diffed them, here's the changes for 4.3.4 and 4.3.5 in one diff: https://github.com/dentarg/cougar/compare/baa4cec8bd156ae72324c94e722b0bf33d32f5ea...90e9731117ef1d72232fd9dfeb7de447e9a13b7b

**Comment by nateberkopec** [comment]
https://github.com/puma/puma/commit/ce33a7bb52578e3cfea7379fa811a3fac452baaf#commitcomment-39350098
