### ISSUE TITLE
Missing git tags for v4.3.5 and v3.12.6

### ISSUE THREAD

**Issue by dentarg** [puma/puma#2286]
There's no tags for the latest releases at https://github.com/puma/puma/tags

```
~/src/puma master
$ git tag -l | grep 3.12
v3.12.0
v3.12.1
v3.12.2
v3.12.3
v3.12.4
v3.12.5

~/src/puma master
$ git tag -l | grep 4.3
v4.3.0
v4.3.1
v4.3.2
v4.3.3
v4.3.4
```

cc @nateberkopec @evanphx

**Comment by dmexs** [comment]
I also noticed the git tag for 4.3.4 doesn't include the latests commits to ext/puma_http11/puma_http11.c.

Specifically it doesn't include this commit: https://github.com/puma/puma/commit/befe00a86447ffaedfad8b94eb5c4f2208f8bf7a#diff-c4634a338b2a325f468d8cae37ec0eca

Which I suspect fixes the compile error I'm getting for 4.3.4 and 4.3.5 versions of the gem:

```
compiling puma_http11.c
puma_http11.c:203:22: error: implicitly declaring library function 'isspace' with type 'int (int)' [-Werror,-Wimplicit-function-declaration]
  while (vlen > 0 && isspace(value[vlen - 1])) vlen--;
                     ^
puma_http11.c:203:22: note: include the header <ctype.h> or explicitly provide a declaration for 'isspace'
1 error generated.
make: *** [puma_http11.o] Error 1

make failed, exit code 2
```
Please let me know if I"m misunderstanding the structure of the repo/gem. Just trying to get a working up to date version installed and ran into this error.

**Comment by dentarg** [comment]
@dmexs I think you should open up a new issue describing your problem (and add more info, like what commit are you checking out and what commands you are running)

**Comment by mpeltomaa** [comment]
> I also noticed the git tag for 4.3.4 doesn't include the latests commits to ext/puma_http11/puma_http11.c.
> 
> Specifically it doesn't include this commit: [befe00a#diff-c4634a338b2a325f468d8cae37ec0eca](https://github.com/puma/puma/commit/befe00a86447ffaedfad8b94eb5c4f2208f8bf7a#diff-c4634a338b2a325f468d8cae37ec0eca)
> 
> Which I suspect fixes the compile error I'm getting for 4.3.4 and 4.3.5 versions of the gem:
> 
> ```
> compiling puma_http11.c
> puma_http11.c:203:22: error: implicitly declaring library function 'isspace' with type 'int (int)' [-Werror,-Wimplicit-function-declaration]
>   while (vlen > 0 && isspace(value[vlen - 1])) vlen--;
>                      ^
> puma_http11.c:203:22: note: include the header <ctype.h> or explicitly provide a declaration for 'isspace'
> 1 error generated.
> make: *** [puma_http11.o] Error 1
> 
> make failed, exit code 2
> ```
> 
> Please let me know if I"m misunderstanding the structure of the repo/gem. Just trying to get a working up to date version installed and ran into this error.

I have this same error and it even prevents me to compile Puma. Please add that commit to 4.3.5 or 4.3.6.

**Comment by rafaelbiriba** [comment]
Same problem here:
```
Fetching puma 4.3.5
Installing puma 4.3.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/rafael/.rvm/gems/ruby-2.5.1@rails/gems/puma-4.3.5/ext/puma_http11
/Users/rafael/.rvm/rubies/ruby-2.5.1/bin/ruby -I /Users/rafael/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0 -r ./siteconf20200810-20691-1p35w7b.rb
extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version in openssl/ssl.h... yes
creating Makefile

current directory: /Users/rafael/.rvm/gems/ruby-2.5.1@rails/gems/puma-4.3.5/ext/puma_http11
make "DESTDIR=" clean

current directory: /Users/rafael/.rvm/gems/ruby-2.5.1@rails/gems/puma-4.3.5/ext/puma_http11
make "DESTDIR="
compiling http11_parser.c
ext/puma_http11/http11_parser.c:44:18: warning: unused variable 'puma_parser_en_main' [-Wunused-const-variable]
static const int puma_parser_en_main = 1;
                 ^
1 warning generated.
compiling io_buffer.c
compiling mini_ssl.c
mini_ssl.c:145:7: warning: unused variable 'min' [-Wunused-variable]
  int min, ssl_options;
      ^
1 warning generated.
compiling puma_http11.c
puma_http11.c:203:22: error: implicitly declaring library function 'isspace' with type 'int (int)' [-Werror,-Wimplicit-function-declaration]
  while (vlen > 0 && isspace(value[vlen - 1])) vlen--;
                     ^
puma_http11.c:203:22: note: include the header <ctype.h> or explicitly provide a declaration for 'isspace'
1 error generated.
make: *** [puma_http11.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/rafael/.rvm/gems/ruby-2.5.1@rails/gems/puma-4.3.5 for inspection.
Results logged to /Users/rafael/.rvm/gems/ruby-2.5.1@rails/extensions/x86_64-darwin-19/2.5.0/puma-4.3.5/gem_make.out

An error occurred while installing puma (4.3.5), and Bundler cannot continue.
Make sure that `gem install puma -v '4.3.5' --source 'https://rubygems.org/'` succeeds before bundling.
```

**Comment by nateberkopec** [comment]
Fixed tag issue: https://github.com/puma/puma/tags

**Comment by joallard** [comment]
Indeed, upgrading to 4.3.7 fixes the issue. Thanks!
