### ISSUE TITLE
Getting the queue time in headers

### ISSUE THREAD

**Issue by vprigent** [puma/puma#2291]
**Is your feature request related to a problem? Please describe.**
I run a small rails project and we are using ScoutAPM for our monitoring. One feature we really miss when under load is to know how much of the response time is effectively spent in the queue. Because we are running standalone puma, we don't rely on nginx for queueing so we can't collect that metric at this level.. however, I would expect to be able to know how long the request waited in the queue when reaching puma and be able to report that to ScoutAPM/any APM tool.

**Describe the solution you'd like**
An option to enable tracking of the queueing time, or having this enabled by default (I assume there would be a complexity matter as much as a performance matter here?)

**Describe alternatives you've considered**
We could setup nginx but at this stage, the project would really only use nginx for the purpose of tracking the queueing time.
We are running this project on AWS ECS, the traffic goes through an Application Load Balancer. The immediate benefit of another layer like nginx running on our infrastructure isn't obvious.

I may also be wrong here by assuming that it is something that it is puma's role to provide that since it provides a queueing mechanism?

Many thanks!

**Comment by nateberkopec** [comment]
Unfortunately, this is not possible.

Puma actually doesn't provide the queueing mechanism: the operating system does. Requests connect to the socket and get a TCP ACK, but Puma doesn't actually touch the request until a thread starts actually processing it.

Queue time tracking works on the principle of something adding a request start time header, and then a Rack middleware checks Time.now - that-time-in-the-header. Puma cannot add that request start time header, because to do so it would have to actually process the request, defeating the purpose and always reporting near-zero queue time.

I wish Amazon would do this with ALB or ELB, but they do not and you cannot configure it to do so. You must use nginx or another reverse proxy to add this header when using AWS.

**Comment by vprigent** [comment]
Thanks for the reply @nateberkopec and for clarifying how this all works!

**Comment by nateberkopec** [comment]
It's really a limitation of loadbalancers on AWS more than anything else. Heroku adds this header in their load-balancing layer by default, for example, so you can get queue time reporting w/o NGINX on Heroku.

**Comment by sosedoff** [comment]
AWS Application load balancers do inject the request time into their request tracing header, here's the documentation: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html

For the reference: https://github.com/discourse/prometheus_exporter/blob/e4e2413ad170ba6341edb7c4767c13251b7e484f/lib/prometheus_exporter/middleware.rb#L120

**Comment by nateberkopec** [comment]
@sosedoff Most applications are going to want much, much more precision than the epoch time _in seconds_. The standard on Heroku, for example is in milliseconds.

**Comment by sosedoff** [comment]
Right, im just saying there's _some_ availability on AWS, which could be used for general alerting.

**Comment by romainsalles** [comment]
I know we are speaking about AWS here (and we had the same issue as you with AWS)... but we recently discovered that if you're using Cloudflare, you can use [Transform Rules](https://developers.cloudflare.com/rules/transform/) to add custom headers based on these fields ([source](https://developers.cloudflare.com/ruleset-engine/rules-language/fields/)):
- http.request.timestamp.msec
- http.request.timestamp.sec

![Screenshot 2024-03-11 at 22 02 00@2x](https://github.com/puma/puma/assets/4284090/24b24fee-2468-41d7-9fc1-144c0c34e657)

![Screenshot 2024-03-11 at 22 06 18@2x](https://github.com/puma/puma/assets/4284090/8cfb1a45-8ffe-41f1-8562-b9d555677bb1)

It will help you track the different timings.
