### ISSUE TITLE
Uninitialized constant OPENSSL_VERSION - server won't start

### ISSUE THREAD

**Issue by maleksiuk** [puma/puma#2296]
**Describe the bug**

I installed Puma 5.0.0.beta1 on Windows without OpenSSL installed and when I try to start the server I get the error `uninitialized constant Puma::MiniSSL::OPENSSL_VERSION (NameError)` at `lib/puma/minissl.rb:17`.

I believe the problem is from commit https://github.com/puma/puma/commit/ee8596237fb25cbc3a908586f4100e37ff4d77c6 -- it's using constants such as `OPENSSL_VERSION` which are only defined if you build the C extension with OpenSSL installed (see the two alternate definitions of `Init_mini_ssl()`).

**Puma config:**

No Puma config or command line options.

**To Reproduce**

Install Puma on C-Ruby and without OpenSSL on your system, then run `bundle exec puma hello.ru`

**Expected behavior**

I expect the server to start.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Puma Version: 5.0.0.beta1 (master@a72c68b)

**Comment by MSP-Greg** [comment]
Sorry.  I didn't check that locally, and all the CI uses OpenSSL.

I get a patch for that today or tomorrow.

Might I ask why you don't want to install the the MSYS2/MinGW OpenSSL package?

You didn't mention what Ruby version you're using, but the OpenSSL dll's are already included in most Windows Rubies.  IOW, you don't need any OpenSSL exe's added to Path, etc, etc.

**Comment by maleksiuk** [comment]
No problem, and no rush. I was just testing a patch I'm playing around with. I don't use Windows for Ruby development or for running servers, which is why I don't have OpenSSL installed.

I'm using Ruby 2.5.3 which I probably installed with RubyInstaller (but I can't remember).

Thanks for the response @MSP-Greg

**Comment by MSP-Greg** [comment]
If you compiled Puma, you must have the devkit/MSYS2 installed.  Assuming you're 64-bit, OpenSSL can be installed via:
```
ridk exec pacman -S mingw-w64-x86_64-openssl
```

The package is about 5 MB, installed is ~ 70 MB.

I'll still get the patch done soon.

**Comment by MSP-Greg** [comment]
@nateberkopec

Quite a few tests fail.  Should we skip them individually, or ignore them?  If ignore them, group together and use one conditional, or end each method with `end unless SKIP_OPENSSL`?

**Comment by nateberkopec** [comment]
@MSP-Greg Grouping into 1 conditional sounds cleaner to me if they're all in the same file. Otherwise individual `skip unless`.

**Comment by MSP-Greg** [comment]
@maleksiuk

Sorry for the delay.  #2305 should fix this, we're running CI on Windows without OpenSSL support and it's passing.

If this is still an issue, we can re-open.
