### ISSUE TITLE
ability to log POST request body?

### ISSUE THREAD

**Issue by tansaku** [puma/puma#2297]
**Is your feature request related to a problem? Please describe.**
We'd like to see precisely the details of the body of an incoming POST request (and headers) in the logs to help with debugging

**Describe the solution you'd like**
We'd like logging options that increased verbosity for things like post bodies or headers

**Describe alternatives you've considered**
we can use something like wireshark to trace precise http transmissions, but sometimes we don't have install access on the necessary servers, or the comms are https

**Additional context**
Apologies if this is something that's already obvious how to do - we did look through the docs and codebase and it wasn't immediately clear if there were options for this, or how easy it would be to add

**Comment by acmh** [comment]
I think this is related to #2250

**Comment by dentarg** [comment]
Hade you considered writing a rack middleware that does this?

**Comment by tansaku** [comment]
I had not @dentarg - thanks for the suggestion

thanks for mentioning #2250 @acmh - it looks superficially related - I'll have to dig deeper

**Comment by nateberkopec** [comment]
I don't think there's any need for this to be implemented in Puma. A Rack middleware will do the job just fine 👍
