### ISSUE TITLE
Puma MiniSSL Filehandle Leak

### ISSUE THREAD

**Issue by JohnPhillips31416** [puma/puma#2299]
**Describe the bug**
When running with JRuby and configured with a Puma::MiniSSL::Context with a keystore file path MiniSSL will open 2 filehandles to the keystore file on every SSL REST request.  These filehandles do not get closed until a subsequent Java garbage collection occurs.

**Expected behavior**
Ideally MiniSSL should only open/read the keystore file once, not on each https request.  A simpler fix is just to properly close the 2 FileInputStream objects after use.

https://github.com/puma/puma/blob/477479adce25795389a22cc67430a672727caa39/ext/puma_http11/org/jruby/puma/MiniSSL.java#L148
https://github.com/puma/puma/blob/477479adce25795389a22cc67430a672727caa39/ext/puma_http11/org/jruby/puma/MiniSSL.java#L149

**Desktop (please complete the following information):**
 - OS: Linux
 - Puma Version 4.3.5

**Comment by nateberkopec** [comment]
Nice catch. Want to open a PR with your change?

**Comment by JohnPhillips31416** [comment]
I'll do this when I have time, we should probably refactor so the keystore is only read from disk once.

**Comment by JohnPhillips31416** [comment]
fix is here https://github.com/puma/puma/pull/2302

**Comment by MSP-Greg** [comment]
Closed by #2302
