### ISSUE TITLE
ctype.h missing from puma_http11.c

### ISSUE THREAD

**Issue by mpeltomaa** [puma/puma#2304]
**Describe the bug**

`#include <ctype.h>` needs to be added to `ext/puma_http11/puma_http11.c`. Without this include compilation of Puma will fail due to error:

```
include the header <ctype.h> or explicitly provide a declaration for 'isspace' 
1 error generated.
```
This seems to be fixed on 5.0.0.beta1 although it won't help since beta doesn't behave nicely and cannot be used in production.

**To Reproduce**
Just try to compile puma.

**Expected behavior**
Succesfully compiled Puma would be expected behaviour :)

**Desktop (please complete the following information):**
MacOS 15.5.5 and MacOS Big Sur
Puma version 4.3.5

**Comment by RyanMorash** [comment]
The following is what I get when trying to install Puma 4.3.5 in Ruby 2.7.1 under rbenv with RubyGems 3.1.2

```
% sudo gem install puma           
Building native extensions. This could take a while...
ERROR:  Error installing puma:
	ERROR: Failed to build gem native extension.

    current directory: /Users/ryanmorash/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/ext/puma_http11
/Users/ryanmorash/.rbenv/versions/2.7.1/bin/ruby -I /Users/ryanmorash/.rbenv/versions/2.7.1/lib/ruby/2.7.0 -r ./siteconf20200705-62350-nsgo9p.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version in openssl/ssl.h... yes
creating Makefile

current directory: /Users/ryanmorash/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/ext/puma_http11
make "DESTDIR=" clean

current directory: /Users/ryanmorash/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/ext/puma_http11
make "DESTDIR="
compiling http11_parser.c
ext/puma_http11/http11_parser.c:44:18: warning: unused variable 'puma_parser_en_main' [-Wunused-const-variable]
static const int puma_parser_en_main = 1;
                 ^
1 warning generated.
compiling io_buffer.c
compiling mini_ssl.c
mini_ssl.c:145:7: warning: unused variable 'min' [-Wunused-variable]
  int min, ssl_options;
      ^
mini_ssl.c:299:40: warning: function 'raise_error' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
void raise_error(SSL* ssl, int result) {
                                       ^
2 warnings generated.
compiling puma_http11.c
puma_http11.c:203:22: error: implicitly declaring library function 'isspace' with type 'int (int)' [-Werror,-Wimplicit-function-declaration]
  while (vlen > 0 && isspace(value[vlen - 1])) vlen--;
                     ^
puma_http11.c:203:22: note: include the header <ctype.h> or explicitly provide a declaration for 'isspace'
1 error generated.
make: *** [puma_http11.o] Error 1

make failed, exit code 2
```

**Comment by mpeltomaa** [comment]
And unused variables, those could be cleaned up as well? I didn't notice use any of mentioned variables above.

**Comment by georgeclaghorn** [comment]
Went to open a PR and realized this is already fixed in `master` because `isspace` is no longer used.

**Comment by dentarg** [comment]
> Went to open a PR and realized this is already fixed in `master` because `isspace` is no longer used.

The use of `isspace` is still there [in the master branch](https://github.com/puma/puma/blob/master/ext/puma_http11/puma_http11.c#L170)

https://github.com/puma/puma/blob/e2b419341153ff2206e1cb84fca1663639d0ef30/ext/puma_http11/puma_http11.c#L170

Or am I missing something?

**Comment by dentarg** [comment]
Ah, https://github.com/puma/puma/commit/22b135a636bb3a80875e4f46b48610fa32fcd9d6 added the use of `isspace` but `#include <ctype.h>` was added in https://github.com/puma/puma/commit/befe00a86447ffaedfad8b94eb5c4f2208f8bf7a which is only in master and v5.0.0.beta1.

**Comment by dentarg** [comment]
Seeing this is reported for the new macOS version, Big Sur, it is probably related to something that changed in macOS. 

I found a few similar issues when I started searching:

* https://github.com/nyholku/purejavahidapi/issues/75
* https://github.com/golang/go/issues/39832
* https://bugs.python.org/issue41179

The paragraph that these issues all quote...

> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

...is listed under a headline "Known Issues" at https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes, so it might even get fixed, making it work to compile Puma 4.3.5 in Big Sur.

I think this issue can be closed without action. If it persist when Big Sur is out of beta, maybe we can reconsider.

**Comment by mpeltomaa** [comment]
Would it be bad to include `ctype.h` anyway?

**Comment by georgeclaghorn** [comment]
I don’t think it’s the linker cache. Clang now [enables `-Werror=implicit-function-declaration` by default](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes#Resolved-in-Xcode-12-beta):

> Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on). This additional error detection unifies Clang’s behavior for iOS/tvOS and macOS 64-bit targets for this diagnostic. (49917738)

Apple could back out of this particular change, but even if they do, it’s probably a good idea not to rely on the implicit function declaration anyway.

**Comment by georgeclaghorn** [comment]
> The use of isspace is still there in the master branch
> 
> Or am I missing something?

Whoops, yes, I looked in the wrong file. 🤦‍♂️

**Comment by mpeltomaa** [comment]
> I don’t think it’s the linker cache. Clang now [enables `-Werror=implicit-function-declaration` by default](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-beta-release-notes#Resolved-in-Xcode-12-beta):
> 
> > Clang now reports an error when you use a function without an explicit declaration when building C or Objective-C code for macOS (-Werror=implicit-function-declaration flag is on). This additional error detection unifies Clang’s behavior for iOS/tvOS and macOS 64-bit targets for this diagnostic. (49917738)
> 
> Apple could back out of this particular change, but even if they do, it’s probably a good idea not to rely on the implicit function declaration anyway.

I think they won't back out on this. I might be quite much wrong here, but this was changed on newer C standards some time ago and `gcc` for example gave just warning not error on these cases - or do i remember totally wrong?

**Comment by frederikspang** [comment]
Until fixed by ctype and/or Apple default parameters, it's workaround by setting the `-Wno-error` flag for gcc in puma's bundler config.

```bash
$ bundle config build.puma --with-cflags="-Wno-error=implicit-function-declaration"
```

Or just install 4.3.5 with the flags:

```bash
$ gem install puma:4.3.5 -- --with-cflags="-Wno-error=implicit-function-declaration"
```

**Comment by adampal** [comment]
I'm also seeing the same issue in macOS 10.15.6 in a new rails app when trying to install puma 4.3.5
I can install puma v 4.2 without any issues but I had to use @frederikspang's suggestion above (`gem install puma:4.3.5 -- --with-cflags="-Wno-error=implicit-function-declaration"`) to install v 4.3.5 successfully.

**Comment by tri-dang** [comment]
@frederikspang's solution is working well with my issue, thank you so much.

**Comment by chinomnsoawazie** [comment]
@frederikspang solution just worked for me

**Comment by nateberkopec** [comment]
Fixed on master and 4.3.6.

**Comment by CR1AT0RS** [comment]
For latest version of OSX:
```
gem install puma -v '4.3.5' -- --with-opt-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include
```
Or just upgrade gem to 
```
gem 'puma', '~> 5.0'
```

**Comment by codemicky** [comment]
Thank you, @CR1AT0RS! 👍

**Comment by Shtokhman** [comment]
> Until fixed by ctype and/or Apple default parameters, it's workaround by setting the `-Wno-error` flag for gcc in puma's bundler config.
> 
> ```shell
> $ bundle config build.puma --with-cflags="-Wno-error=implicit-function-declaration"
> ```
> 
> Or just install 4.3.5 with the flags:
> 
> ```shell
> $ gem install puma:4.3.5 -- --with-cflags="-Wno-error=implicit-function-declaration"
> ```

It worked earlier, but after removing and setting up the project from scratch does not work now
Trying to install puma 2.11.3 on Big Sur 11.1
Any ideas?

**Comment by dentarg** [comment]
> Trying to install puma 2.11.3 on Big Sur 11.1

Not a battle I would fight 😆

(Is using docker an option?)

**Comment by Shtokhman** [comment]
> Trying to install puma 2.11.3 on Big Sur 11.1
> Not a battle I would fight 😆 (Is using docker an option?)

The most painful is the fact it worked a day ago
Docker as the last option I guess

**Comment by iseth** [comment]
Now the `implicit-function-declaration` is breaking things, when you install puma with the correct `gem install puma -- --with-cppflags=-I/usr/local/opt/openssl/include` and then try to install it with bundle install it will fail because you might have added the `implicit-function-declaration` to bundle which would have added it here:  ~/.bundle/config
if you remove the following line and re run bundle install puma will compile correctly
```
BUNDLE_BUILD__PUMA: "--with-cflags=-Wno-error=implicit-function-declaration"
```

**Comment by iliakan** [comment]
For puma 6, this helped:
```
export PUMA_DISABLE_SSL=1
```

**Comment by atstockland** [comment]
> For puma 6, this helped:
> 
> ```
> export PUMA_DISABLE_SSL=1
> ```

where'd you use this export call?

**Comment by dentarg** [comment]
Before installing Puma.

You can also use it like this: `PUMA_DISABLE_SSL=1 gem install puma`


Or if you are using Bundler (with Puma in your Gemfile): `PUMA_DISABLE_SSL=1 bundle install`
