### ISSUE TITLE
Application/json requests hang

### ISSUE THREAD

**Issue by timminkov** [puma/puma#2309]
**Describe the bug**
When making application/json requests to the server, Puma hangs. I've traced this down to the unistd.h level (system files) so _technically_ it's not a puma issue. All other requests work fine - just `application/json` requests hang. The incredibly frustrating thing is this happens no matter what webserver I use  - Puma, Unicorn, Thin, or Webrick. I've tried nearly everything at this point, including _reformatting and reinstalling everything_. Since Puma is the biggest webserver in the ruby ecosystem, I figured this would be the best place to post this - What the hell is happening?  
  
Note that other users at my org are able to run this code just fine and I haven't noticed any other similar issues popping up here so I'm assuming it's my machine. The only things I've installed since the wipe were Alfred, Slack, iTerm2, ZSH, sequel pro, and some basic necessities for setup (homebrew, rvm, nvm, mysql 5.6, redis, ag).

Edit: This APPEARS to only happen with requests incoming from the browser - both Chrome and Safari have this behavior.

**Puma config:**
No puma config - Just running `rails s puma`.

**To Reproduce**
I wish I could add steps to reproduce this.

**Desktop (please complete the following information):**
 - OS: OSX Catalina 10.15.5
 - Puma Version: Any
- Ruby version: Tested with 4.2.8 and 4.2.10

**Comment by nateberkopec** [comment]
Hm, sorry but this issue tracker is only for issues with Puma, which I think this clearly is not. 

Good luck! In Puma, you can use the new thread-backtrace features to see where Puma is hung: https://github.com/puma/puma/issues/1964

**Comment by timminkov** [comment]
Totally understandable. I JUST figured out what the issue was after probably ~40 hours of debugging. Leaving it here for future reference, incase anyone ever has the same problem:

https://github.com/chimurai/http-proxy-middleware/issues/320
