### ISSUE TITLE
SERVER_PORT and SERVER_NAME should be derived from HTTP_X_Forwarded_Host instead of HTTP_HOST

### ISSUE THREAD

**Issue by mehta-madhur** [puma/puma#2310]
In below method, HTTP_HOST is used to derive the server port and server name
https://github.com/puma/puma/blob/f7b09ddd4696ed77c1d781a366003279b7bbddce/lib/puma/server.rb#L445
Since puma is used as proxy pass, the http_host will have the domain name and port where puma is running. 
Rather, server_name and server_port are required to identify what was the actual name and port where the request was hit. 

To get the actual name, HTTP_X_Forwarded_Host should be given preference over the HTTP_HOST
Similar is done in Rails Request Class also
https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/http/url.rb#L222

**Comment by dentarg** [comment]
That's not what the [Rack SPEC](https://github.com/rack/rack/blob/master/SPEC.rdoc#top) (and [RFC 3875](https://tools.ietf.org/html/rfc3875#section-4.1.14)) says. Why should Puma do it differently?

**Comment by mehta-madhur** [comment]
This RFC is way back when proxy servers were not in use. The recent RFC states that the actual port and host name may be passed in the x-forwarded-for headers. 
https://tools.ietf.org/html/rfc7239

**Comment by nateberkopec** [comment]
Puma is a Rack server, so we set the values in the Rack environment according to what the Rack spec says. I think we're doing it according to spec correctly.

If you have a problem with the spec, please open an issue in `rack`.
