### ISSUE TITLE
Puma loading, History.md questions

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2315]
1. Looking at the issues re loading in Puma.  For instance, building Puma without SSL (see https://github.com/puma/puma/pull/2305), and also JSON/OpenSSL/YAML loading (see https://github.com/puma/puma/pull/2269) 

Not sure how far to try and take minimal loading, but several files may not need to be loaded unless binding to SSL sockets, JSON/Psych/YAML may not need to be loaded, and some engines/platforms cannot use workers/cluster.

Also, given that Puma is relatively 'flat' re namespaces, loading could be centralized, maybe with a specific file like `puma/load.rb`.  It could load all files needed by all configurations, and with comments make clear any files that are loaded outside of it.  Some may work best with autoload, and maybe all other Puma files can be loaded with require_relative.  By using one file, it may help remind everyone that any require statements added in PR's/commits should be reviewed.

Having also been in CI a bit lately, I always dislike having requires in test files, as it may hide issues with proper loading.  Given that CI uses a fair bit of spawned processes to launch Puma, that isn't as much of an issue as with other repos...

Anyway, looking for feedback, thoughts, etc.

2. Small point, but the History.md file.  Should newest go on top or bottom?  I recently added an item in the wrong place, decided to move it, and also wanted to update PR https://github.com/puma/puma/pull/2302, and itvolved History.md...

**Comment by MSP-Greg** [comment]
Re History.md, any objections to the following?  Added linking to PR's:

https://github.com/MSP-Greg/puma/blob/history/History.md

If the most recent release is on the top, seems like the most recent commits/PR's should also go on top?

**Comment by dentarg** [comment]
Solved by https://github.com/puma/puma/pull/2305 and https://github.com/puma/puma/pull/2383 @MSP-Greg?

**Comment by MSP-Greg** [comment]
LGTM
