### ISSUE TITLE
Cyclic restarts with `prune_bundler` and `Bundler.setup` (`require`) and `workers` > 1

### ISSUE THREAD

**Issue by AlexWayfer** [puma/puma#2319]
**Describe the bug**

I'm trying to start a server via `pumactl`, but it fails in an infinity loop without backtraces:

```
> bundle exec pumactl start
[191794] * Pruning Bundler environment
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/launcher.rb:289)
[191794] * Pruning Bundler environment
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/launcher.rb:289)
[191794] * Pruning Bundler environment
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /home/alex/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/launcher.rb:289)
...
```

**Puma config:**

```ruby
# frozen_string_literal: true

## Require gems
require 'bundler/setup'
Bundler.require

prune_bundler

rackup 'config.ru'

workers 2
```

**To Reproduce**

`Bundler.require` (or `.setup`) + `prune_bundler` + `workers` > 1.

Run it with:

```
bundle exec pumactl start
```

**Expected behavior**

Server starts or some descriptive errors (once, not in a loop).

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Puma Version: `4.3.5` and `5.0.0.beta1`

**Comment by dentarg** [comment]
I can't reproduce, I tried both with Ruby 2.6.6 + Bundler 2.1.2 and Ruby 2.7.1 + Bundler 2.1.4, on macOS 10.14. [Code](https://gist.github.com/dentarg/354806be0a74abcc96b23c293ebf5cd5)

```
$ bundle exec pumactl start
Puma starting in single mode...
* Version 4.3.5 (ruby 2.6.6-p146), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2020-07-23 17:12:50 +0200 ===
- Goodbye!
```

```
$ bundle exec pumactl start
Puma starting in single mode...
* Version 4.3.5 (ruby 2.7.1-p83), codename: Mysterious Traveller
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:9292
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2020-07-23 17:13:34 +0200 ===
- Goodbye!
```

**Comment by AlexWayfer** [comment]
Ruby 2.7.1 (rbenv), Arch Linux, Bundler 2.1.4.

My code the same as your.

Unfortunately, I even don't know how to debug, add some backtraces or verbose. There are no such options for `pumactl`.

**Comment by AlexWayfer** [comment]
@dentarg, please, ensure that you have `puma.rb` inside `config/` directory (default config path), or please specify `bundle exec pumactl start -F puma.rb`. Without this I have the same successful output as your, but there is no info about 2 workers (config just not loaded).

**Comment by AlexWayfer** [comment]
I'm trying to debug. Working with `master`-version. I have such output:

```
[18292] * Pruning Bundler environment
[18292] * Pruning Bundler environment
[18292] * Pruning Bundler environment
[18292] * Pruning Bundler environment
...
```

Even when I've added `log '* Pruned'` in this method after `with_unbundled_env do` block.

So, the problem in this block (or `with_unbundled_env` method).

**Comment by AlexWayfer** [comment]
New info: the problem exactly in `Kernel.exec`: https://github.com/puma/puma/blob/47f933d/lib/puma/launcher.rb#L310

I've got `args`:

```ruby
["/home/alex/.rbenv/versions/2.7.1/bin/ruby", "/home/alex/Projects/ruby/puma/bin/puma-wild", "-I", "/home/alex/Projects/ruby/puma/lib:/home/alex/Projects/ruby/extensions/x86_64-linux/2.7.0/puma-5.0.0.beta1", "nio4r:2.5.2", "-C", "puma.rb", {:close_others=>false}]
```

and the result command for me looks like:

```
/home/alex/.rbenv/versions/2.7.1/bin/ruby /home/alex/Projects/ruby/puma/bin/puma-wild -I /home/alex/Projects/ruby/puma/lib:/home/alex/Projects/ruby/extensions/x86_64-linux/2.7.0/puma-5.0.0.beta1 nio4r:2.5.2 -C puma.rb
```

And it cyclic fails in the same way with the same output from `launcher.rb`.

I don't know how to debug further.

**Comment by AlexWayfer** [comment]
Probably it's a simple recursion, what do you think?

**Comment by AlexWayfer** [comment]
Yep, just simple check for `ENV['PUMA_BUNDLER_PRUNED']` inside `prune_bundler` method fixes it. Weird. I'm going to prepare a PR for this.

**Comment by MSP-Greg** [comment]
@AlexWayfer

What happens if you remove the following from Puma config?

```ruby
## Require gems
require 'bundler/setup'
Bundler.require
```

**Comment by AlexWayfer** [comment]
> @AlexWayfer
> 
> What happens if you remove the following from Puma config?
> 
> ```ruby
> ## Require gems
> require 'bundler/setup'
> Bundler.require
> ```

It works, but I require in real-life application another file, like `config/main.rb`, which does `Bundler.require` (for git-versions of gems) and loads Puma-related (YAML) config. So… I'm not sure is it OK to have `Bundler.require` and `prune_bundler` in one runtime or what I should do.

**Comment by AlexWayfer** [comment]
Let's discuss this issue a bit more, please. The decision affect my web applications a lot.

From here: https://github.com/puma/puma/blob/5d02e45/lib/puma/dsl.rb#L572-L585

> When set, if Puma detects that it's been invoked in the context of Bundler, it will cleanup the environment and re-run itself outside the Bundler environment, but directly using the files that Bundler has setup.
> 
> This means that Puma is now decoupled from your Bundler context and when each worker loads, it will be loading a new Bundler context and thus can float around as the release dictates.

In this context `Bundler.require` seems non-sense, but it still can help to load some configuration (especially for Puma) via third-party gems (from `Gemfile`), but (!) it may cause conflicts if some config loading and third-party gem changed in `phased-restart` or so.

I'm not sure for what this options is. Like… `puma` master process will be "dirty" in the Bundler environment (gems versions) at its start, but then it will not be changed but its workers will be with a fresh Bundler environment.

Like… what about case if I want to update the Puma from v4 to v5, for example? `master `process will be at v4 and it will try to start workers v5? I guess conflicts are possible in such cases.

Please, describe, for what cases this option, when conflicts (problems) will be possible and when everything will be 100% OK.

**Comment by AlexWayfer** [comment]
But in the same time I guess `Bundler.setup` is similar to `bundle exec pumactl`, is not it? I still don't understand how it works and how I should design my applications.
