### ISSUE TITLE
Deleted `test_load_path_includes_extra_deps` test

### ISSUE THREAD

**Issue by AlexWayfer** [puma/puma#2322]
**Describe the bug**

I see the `test/config/prune_bundler_with_deps.rb` in current `master` (df57cecce593f1438ae4dde196231ba1b721c73f), but I don't see any test which uses it.

I've found that it was added in this commit: 809a3f4c7beb2b803e068bad8ca6a5fc61fa7d4d with `test_load_path_includes_extra_deps` test. But now there is no such test.

I was looking for this test deletion and found this change: https://github.com/puma/puma/commit/525ecca1607d10ba5451a7a37450fa4530fd7c05#diff-ad8d9f1e0cf07519c2372ca5f60ca4d2L249-L258

So, I don't see reasons for deletion in the commit message. Why have you deleted it?

/cc @MSP-Greg @nateberkopec

**Expected behavior**

More tests, more description of its deletion and no unused files.

**Comment by MSP-Greg** [comment]
@AlexWayfer 

Something many have happened with a rebase/merge operation, as the commit that removed the test came from my PR, which was done before the PR PR https://github.com/puma/puma/pull/1105 / commit https://github.com/puma/puma/commit/809a3f4c7beb2b803e068bad8ca6a5fc61fa7d4d that added the code and the removed test.  I think that made sense...

Regardless, the removed code/tests from PR https://github.com/puma/puma/pull/1105 should be reviewed and added.

**Comment by nateberkopec** [comment]
Marking as contrib-wanted, someone can open a PR adding the missed test.
