### ISSUE TITLE
Suggestion: leave GitHub issues open to comments after resolving them

### ISSUE THREAD

**Issue by earksiinni** [puma/puma#2351]
**Is your feature request related to a problem? Please describe.**
It appears that the project has a policy of locking GitHub issues after they've been closed. I can understand the rationale for this policy. However, it hinders the accumulation of knowledge around certain problems.

For example, I've been working on the exact same problem described in https://github.com/puma/puma/issues/1433 for two years. I didn't even realize that others were having the same problem as myself, I stumbled across the issue thanks to a large search engine headquartered in Palo Alto, California. I finally figured out both the root cause and the correct solution, and I believe that nobody in any online forum has yet to post the complete solution (bold words), even though it's a generic problem that affects many web servers including Puma. I hoped to share my solution directly on the issue, but the issue is locked.

**Describe the solution you'd like**
Leave issues open to comments after resolving them. Or, selfishly, make a one-time exception for https://github.com/puma/puma/issues/1433 so that I can post my solution to the problem 🙂.

**Describe alternatives you've considered**
I considered posting my solution on StackOverflow, but the closest issue describing my own is from 9 years ago and already has an accepted answer (and it's not really a good answer, IMHO).

**Additional context**
N/A

**Comment by nateberkopec** [comment]
Can you just share what your solution is here?

Leaving issues that get good Google Juice (for whatever reason) open muddles the waters, in my opinion, and doesn't help users. That exact thread devolved into people reporting unrelated issues and was going off-topic. It also increases the burden on on of our most scarce resources: maintainer time. 

"How to use Puma" is information that should be contained in our documentation, not in random closed issue threads, so I would prefer you opening a new issue (as you already have) and then discussing what we can add to our docs to help Puma users.

**Comment by earksiinni** [comment]
Makes sense, and I respect and understand your position. Just thought I'd throw it out there.

Rather than continuing to clutter up this thread, I created a new issue for my specific solution: https://github.com/puma/puma/issues/2352. Closing this one now.
