### ISSUE TITLE
Solution: Puma/Rails locks up when performing an HTTP request to self in Rails development mode

### ISSUE THREAD

**Issue by earksiinni** [puma/puma#2352]
This issue is a follow up to https://github.com/puma/puma/issues/1433.

As established in https://github.com/puma/puma/issues/1433, the root issue indeed isn't Puma. The problem is with [Rails' autoload interlock,](https://guides.rubyonrails.org/threading_and_code_execution.html#load-interlock) which prevents a thread from using Rails' autoloading mechanism to load constants when application code is running inside of another thread.

What happens when you do a "loopback" request (i.e., Rails executes a request to a server that in turn executes a request back to Rails before the first request can be completed) is something like this:

1. Rails fires its request (request 1, thread 1) to external service using synchronous HTTP, probably using some lib like Net::HTTP, HTTParty or Typhoeus. As long as the request is pending, Rails counts it as running application code and activates the autoload interlock.
2. The external service makes a request back to Rails (request 2) while request 2 is pending.
3. Puma spawns Rails on a new thread (thread 2) to respond to request 2.
4. However, thread 2 is blocked by the autoload interlock initiated by thread 1. The Rails environment can’t load and request 2 can't be handled, it just remains in limbo until a timeout. (You can confirm this, by the way, with the [`ActionDispatch::DebugLocks` middleware](https://guides.rubyonrails.org/threading_and_code_execution.html#actiondispatch-debuglocks).)
5. So, Rails thread 1 is waiting for a response to request 1, the external service is waiting for a response to request 2 before responding to request 1, and thread 2 is waiting for thread 1 to finish execution and lift the lock before it responds to request 2. Deadlock achieved 💥.

The solution is to [wrap request 1 inside `ActiveSupport::Dependencies.interlock.permit_concurrent_loads`](https://guides.rubyonrails.org/threading_and_code_execution.html#permit-concurrent-loads). Anything wrapped inside that block won't trigger the interlock, allowing new threads to access the Rails environment and boot properly.

So something like:

```
response = ActiveSupport::Dependencies.interlock.permit_concurrent_loads do
  # Your HTTP request code here. For example:
  Faraday.post url, data: 'foo'
end

do_something_with response
```

If you don't use this approach, the workaround is to enable multiple single-threaded workers on Puma or whatever web server you're using. That way you sidestep the problem by forking multiple processes rather than spawning new threads. The problem with this workaround is that in development, Byebug and Pry [work poorly](https://github.com/deivid-rodriguez/byebug/issues/487) with [any multiprocess web server](https://github.com/pry/pry/issues/2153).

Anyway, the `permit_concurrent_loads` fix works for Puma and it should work for any multithreaded server (Thin, Falcon, etc.) because it addresses the underlying issue, which is with Rails.

**Comment by nateberkopec** [comment]
Thanks for the very complete explanation @earksiinni.

> In production, you're depriving yourself of the efficiencies that come with multithreaded concurrency

In production, the autoload interlock isn't used. Did you reproduce this behavior in production mode?

**Comment by earksiinni** [comment]
Ah, I didn't realize that. No, I didn't test or reproduce in production, I just assumed. I'll edit to remove the reference.

**Comment by nateberkopec** [comment]
Ok, then it LGTM. Thank you so much for your patience and your very high quality work that you've done here.

Can you open a PR adding this to the /docs directory, I think in a new file called rails_dev_mode.md? I'll merge.

**Comment by cjlarose** [comment]
> In production, the autoload interlock isn't used.

This is in general, not true. It's possible (though discouraged) to use Rails autoloading in production. The load interlock makes autoloading in multithreaded webservers safe. By default, Rails apps have `eager_load` set to `true`in production, so as long as the `eager_load_paths` is a superset of `autoload_paths`, well-behaved production applications won't ever autoload. That said, the eager-loading/autoloading stuff has a long history in Rails and some older apps (especially those that migrated from older Rails versions, like some I work on myself) still sometimes depend on autoloading in production.

@earksiinni Do you have a specific reproducible test case? I've worked on very similar issues related to the interlock (https://github.com/rails/rails/issues/40009) and it helps to know precisely what the threads were trying to autoload when they get stuck.
