### ISSUE TITLE
Broken MongoDB connections

### ISSUE THREAD

**Issue by mig-hub** [puma/puma#2353]
I get a MongoDB error that occurs on startup as far as I can tell:

```
Mongo::Error::NoServerAvailable - No primary server is available in cluster
```

So the problem is that the connection to the database is broken until the next restart.
It sounds like my puma config is not correct but unfortunately I did not find a good example using both Puma and MongoDB.
The mongo website has an example for Unicorn and puma example are generally using ActiveRecord.

Anybody here has a good puma+mongo config to share?

It sounds to me that the problem is that I need to kill the mongo connection and start one on each fork.
So here is the config I plan to use:

```ruby
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

port ENV['PORT'] || 8080

environment ENV['RACK_ENV'] || 'development'

workers_count = Integer(ENV['WEB_CONCURRENCY'] || 1)

if workers_count > 1
  preload_app!
  workers workers_count
end

before_fork do
  require 'puma_worker_killer'
  PumaWorkerKiller.enable_rolling_restart # Default is every 6 hours

  $mongoclient.close
end

on_worker_boot do
  $mongoclient.reconnect
end
```

Does this look like a correct config for MongoDB ?

**Comment by nateberkopec** [comment]
Yep, that looks reasonable. I'd try asking the people who make you Mongo client gem for more help. But your before/on_worker_boot blocks look correct, so I don't think it's a Puma issue.

**Comment by mig-hub** [comment]
@nateberkopec this is not the config I currently have but te one I was planning to switch to. It seemed alright locally but I wanted to get the advice of somebody more experienced. Thank you for confirming.
