### ISSUE TITLE
pumactrl relies on old bundler version

### ISSUE THREAD

**Issue by rapind** [puma/puma#2356]
**Describe the bug**
After setting up and deploying a new rails app, I noticed that every other deployment would fail. Looks like pumactrl is tied to an old bundler version (I only had 2.1.4 on the server). Adding the old bundler seems to have fixed it: `gem install bundler --default -v "1.17.3"`

**Puma config:**

Auto-generated from the capistrano puma script. Nothing unique or custom added.

**Comment by dentarg** [comment]
I can't find anything about "pumactrl" in the Puma repo. What is it? I can't find much about Capistrano either. A few years ago there was a capistrano script deleted: https://github.com/puma/puma/commit/5762bf98dc6fc2787c220f8224cf11eadefd5971#diff-d3fdfcb667ab45f7cd42fc8933ba6a5c

Can you provide steps to reproduce your problem?

**Comment by nateberkopec** [comment]
I think OP meant pumactl

**Comment by nateberkopec** [comment]
I'm not sure this is Puma's fault. I've seen this issue before but can't recall why Bundler looks for the old version instead of 2.x. 

I don't think Puma actually mentions a Bundler version requirement anywhere.

**Comment by dentarg** [comment]
Could have been a problem with outdated [binstubs](https://bundler.io/man/bundle-binstubs.1.html) perhaps?

Anyway, I agree that this isn't Puma's fault. I'll close. We can re-open if we get instructions how to re-produce (and it looks like Puma is doing something wrong).
