### ISSUE TITLE
History.md doesn't mention 4.3.6

### ISSUE THREAD

**Issue by juliosantos** [puma/puma#2360]
I was going to use the notes found on the 4.3.6 release tag, but then didn't because:
* [this commit](https://github.com/puma/puma/commit/3e3647a32d4c3f6921c80174ada5ee208d71cfa5) deliberately introduces 4.3.6 into History.md
* I noticed there are commit messages that include "[changelog skip]"

So I held back given that perhaps this is deliberate. Happy to contribute a PR if useful.

**Comment by nateberkopec** [comment]
Oh whoops, I missed it on master. Let me cherry-pick it in quick... https://github.com/puma/puma/commit/3e3647a32d4c3f6921c80174ada5ee208d71cfa5

**Comment by nateberkopec** [comment]
Fixed https://github.com/puma/puma/blob/master/History.md#436--2020-09-05
