### ISSUE TITLE
Request: Make MAX_FAST_INLINE a configuration variable

### ISSUE THREAD

**Issue by tim-wovn** [puma/puma#2361]
**Is your feature request related to a problem? Please describe.**

At the company I work at, we're using puma for an internally-consumed service.  This service is currently only consumed by a single client--another internal service.  We are currently on puma version `3.12.1`.  In puma version `3.12.2` a change was made to prevent one client from spamming requests and hogging the service [I think].
https://github.com/puma/puma/compare/v3.12.1...v3.12.2

This change increases our average request duration by about 25% in a load testing environment--regarding load testing, we've integrated k6 load testing into our ci workflow.  As a result of the increased request duration, we have not yet upgraded from version `3.12.1`.

Our load testing is roughly similar [or attempts to be roughly similar] to behaviour we've experienced under peak load.

**Describe the solution you'd like**

Expose `MAX_FAST_INLINE` as a configuration variable.  Then, in use cases such as mine, `MAX_FAST_INLINE` can be set to `Float::INFINITY` to maintain the pre version `3.12.2` behaviour.

`MAX_FAST_INLINE = 10` could continue to be the default value if `MAX_FAST_INLINE` is not set in the configuration, etc.

**Describe alternatives you've considered**

For the moment, we're holding off on upgrading.  It's not an ideal, long-term solution however.

**Additional context**

This was first described in a separate issue:
https://github.com/puma/puma/issues/1981#issuecomment-686903570

**Comment by tim-wovn** [comment]
Thanks for the PR @fdel15 🙇‍♂️

**Comment by amitsaxena** [comment]
If possible, can someone please elaborate a bit on the downsides of setting MAX_FAST_INLINE to 0 🙏 

More context in these comments:
https://github.com/puma/puma/issues/3443#issuecomment-2287287766
https://github.com/puma/puma/issues/3443#issuecomment-2292382376
