### ISSUE TITLE
ERROR - gem install puma -v '2.11.0' 

### ISSUE THREAD

**Issue by dmunozvenegas** [puma/puma#2369]
**Describe the bug**
Error al momento de instalar gem puma - v "2.11.0" con rvm 2.0.0 en OS X Mojave 10.14

Fetching puma 2.11.0
Installing puma 2.11.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/diegomunoz/.rvm/gems/ruby-2.0.0-p648/gems/puma-2.11.0/ext/puma_http11
/Users/diegomunoz/.rvm/rubies/ruby-2.0.0-p648/bin/ruby -r ./siteconf20200917-1438-1qvpmcj.rb extconf.rb --with-cflags=-Wno-error=implicit-function-declaration
checking for BIO_read() in -lcrypto... no
checking for BIO_read() in -llibeay32... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/diegomunoz/.rvm/rubies/ruby-2.0.0-p648/bin/ruby
	--with-puma_http11-dir
	--without-puma_http11-dir
	--with-puma_http11-include
	--without-puma_http11-include=${puma_http11-dir}/include
	--with-puma_http11-lib
	--without-puma_http11-lib=${puma_http11-dir}/
	--with-cryptolib
	--without-cryptolib
	--with-libeay32lib
	--without-libeay32lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/diegomunoz/.rvm/gems/ruby-2.0.0-p648/extensions/x86_64-darwin-18/2.0.0/puma-2.11.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/diegomunoz/.rvm/gems/ruby-2.0.0-p648/gems/puma-2.11.0 for inspection.
Results logged to /Users/diegomunoz/.rvm/gems/ruby-2.0.0-p648/extensions/x86_64-darwin-18/2.0.0/puma-2.11.0/gem_make.out

An error occurred while installing puma (2.11.0), and Bundler cannot continue.
Make sure that `gem install puma -v '2.11.0' --source 'http://rubygems.org/'` succeeds before bundling.

In Gemfile:
  puma

**To Reproduce**
 gem install puma -v "2.11.0"

**Comment by MSP-Greg** [comment]
You're using a very old version of Ruby, and an old version of Puma.

```
checking for BIO_read() in -lcrypto... no
checking for BIO_read() in -llibeay32... no
```

The above indicates that the OpenSSL development files aren't installed.

You can run the below to see what version of OpenSSL the Ruby 2.0.0 build is using, and install the corresponding version of openssl-dev files?

```
ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"
```

I suspect that the version of OpenSSL being used is also very old, and no longer considered secure.

**Comment by dmunozvenegas** [comment]
> You're using a very old version of Ruby, and an old version of Puma.
> 
> ```
> checking for BIO_read() in -lcrypto... no
> checking for BIO_read() in -llibeay32... no
> ```
> 
> The above indicates that the OpenSSL development files aren't installed.
> 
> You can run the below to see what version of OpenSSL the Ruby 2.0.0 build is using, and install the corresponding version of openssl-dev files?
> 
> ```
> ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"
> ```
> 
> I suspect that the version of OpenSSL being used is also very old, and no longer considered secure.



_screen output is_
OpenSSL 1.0.1i 6 Aug 2014

**Comment by MSP-Greg** [comment]
I don't run macOS, so I I'm not sure how to install a version of OpenSSL that old.  Both it and the version after it (1.0.2) are considered 'end of life' and are no longer supported.  The current version of OpenSSL is 1.1.1.
