### ISSUE TITLE
Intermittent critical error in ext/puma_http11/http11_parser.rl 

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2400]
The below error is very intermittently thrown in CI.

```
ext/puma_http11/http11_parser.rl:121: puma_parser_execute: Assertion `parser->nread <= len && "nread longer than length"' failed.
Aborted (core dumped)
```

The link will self destruct in a few weeks, but for now, see:
https://github.com/MSP-Greg/puma/runs/1193838985?check_suite_focus=true#step:8:259

**Comment by dentarg** [comment]
Has been reported before: https://github.com/puma/puma/issues/2321

**Comment by nateberkopec** [comment]
Closing for the other issue
