### ISSUE TITLE
Serve different apps on HTTP and HTTPS

### ISSUE THREAD

**Issue by ekohl** [puma/puma#2404]
**Is your feature request related to a problem? Please describe.**

Perhaps this is already possible, but I couldn't find out. It would be useful if it was easy to behave different on HTTP than on HTTPS. Effectively two Rack applications served on different virtual hosts.

**Describe the solution you'd like**

Instructions on how to achieve a HTTP and HTTPS virtual host.

**Describe alternatives you've considered**

Perhaps this can also be achieved via middleware, but I feel like I have insufficient knowledge to judge that.

**Additional context**

We have a project (https://github.com/theforeman/smart-proxy) that's currently using Webrick. It can bind on both HTTP and HTTPS (also HTTP-only and HTTPS-only). Then each module can be configured to be disabled, HTTP, HTTPS or both. Effectively that means that there are 2 rack applications and 2 webrick instances: one for HTTP and one HTTPS.

Now we are looking at Puma. Our main project https://github.com/theforeman/foreman, a RoR app) is being switched from Passenger to Puma and standardizing on a single application service can provide benefits.

**Comment by nateberkopec** [comment]
Puma serves one Rack app at a time. I think you're probably better off dealing with this functionality at a different level. You could do it at your reverse proxy or load balance, or just in the app itself.

**Comment by ekohl** [comment]
In https://github.com/theforeman/smart-proxy/pull/623 an attempt was made to start two launchers from the same process. Would that be what you mean with "in the app itself"? I have some concerns that the rest of Puma may not be assuming two launcher instances in the same process.

**Comment by nateberkopec** [comment]
Well, there's a lot of ways to do it. It's just a matter of where you want to put the `if` statement, right? 😆 

Rails, for example, mounts Rack apps inside of itself in the router. The Rails router is just a Rack app mounter. Rails controller actions are Rack apps.

What I'm getting at here is Puma supports just knowing about a single Rack app, but the Rack spec doesn't preclude you from putting Rack apps inside your Rack app (dawg!).

**Comment by nateberkopec** [comment]
And I would say multiple instances of anything Puma in the same process at the same time is not currently supported, but it may work, it may not.

**Comment by ekohl** [comment]
Inspired by your suggestion I opened https://github.com/theforeman/smart-proxy/pull/774 and that works surprisingly well for such a small patch. Thanks!

**Comment by nateberkopec** [comment]
Neat! I'm always happy to spread the gospel about how cool Rails' router design is 😆
