### ISSUE TITLE
Test suite aborts with no changes from master

### ISSUE THREAD

**Issue by JalisoCSP** [puma/puma#2415]
**Describe the bug**
Running the test suite failed on an unknown test with `rake aborted!` 

**Puma config:**
Unknown, I just followed the steps here: https://github.com/puma/puma/blob/master/CONTRIBUTING.md#setup

I was using Ruby 2.7.1

**To Reproduce**
This is my first time attempting anything, so I used a fresh clone and followed the steps here: https://github.com/puma/puma/blob/master/CONTRIBUTING.md

The problem happened with `bundle exec rake test:all` and `bundle exec rake test`

Here is a gist with the result of `bundle exec rake test:all --verbose` : https://gist.github.com/JalisoCSP/d6c8c4e930239a9ad450823ef04ef1c7

[Assumption] I think I narrowed this down to `test_sighup_redirects_io_single` being the test responsible for the error. I figured that because I tried to add `puts self.method_name` to `run` in test/helper.rb and got the following, with that test being the last one to error before getting rake aborted.

```
367) Error:
TestRedirectIO#test_sighup_redirects_io_single:
NoMethodError: undefined method `method_name' for #<TestRedirectIO:0x00007fca7915c2c8>
Did you mean?  method
    /Users/jalisocsp/workspace/puma/test/helper.rb:66:in `block (3 levels) in run'

367 runs, 48 assertions, 0 failures, 367 errors, 0 skips
rake aborted!
```

When I put a return at the start of the method (`test_sighup_redirects_io_single`), the test suite ran fine. However, since removing the return, the tests continued to run fine with no problems...

Even though I can't reproduce again now, I'm making the issue as Nate told me to! Source: https://twitter.com/nateberkopec/status/1313508953439969280?s=20 :D

**Expected behavior**
The test suite should run fine after following the steps in the contributing.md file.

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by andrewmcodes** [comment]
@JalisoCSP Did you `brew install ragel`? I just cloned the repo, installed that brew formulae, bundled, and the tests are running fine for me.

**Comment by JalisoCSP** [comment]
@andrewmcodes yep, I followed all the steps in CONTRIBUTING.md

**Comment by nateberkopec** [comment]
I've had similar problems with test suite death, so I'll take a look at that specific test

**Comment by MSP-Greg** [comment]
@JalisoCSP

Little bit confused, as there's mention of 4.1.1 and master.  Is the error info you listed from 4.1.1 or master?  Also, 367 errors is a catastrophic fail, so it's likely something else was wrong.  Lastly. I looked a few places, and I can't find any reference to a method `method_name` anywhere?

> Even though I can't reproduce again now

Is that with master and no code changes, etc?

**Comment by JalisoCSP** [comment]
@MSP-Greg 

> Little bit confused, as there's mention of 4.1.1 and master. Is the error info you listed from 4.1.1 or master?

That has a line through it. It was just what was already on the PR creation thing. I'll remove to help stop the confusion.

>  Also, 367 errors is a catastrophic fail, so it's likely something else was wrong. Lastly. I looked a few places, and I can't find any reference to a method `method_name` anywhere?

That's because of what I said here: > I tried to add puts self.method_name to run in test/helper.rb and got the following, with that test being the last one to error before getting rake aborted.

> Is that with master and no code changes, etc?

Yes. As I said, it was failing, I added a puts and then a return to that test, the suite passed. When I remove those and ran it again it continuted to pass with no changes from master.

I wonder if it's a system thing. Something that needs to be ran once and then it's saved, stored, loaded, whatever? I have a brand new laptop, so...? I don't know, I'm just guessing but Andrew ran it with no problems.

I'm happy to concede that I have no idea what I'm doing haha

**Comment by JalisoCSP** [comment]
I tried uninstalling ragel btw, and the tests still run fine now.

So, I can’t confirm if it was ragel being missing — I did install it, but I don’t know, maybe I needing to restart my terminal or something?

**Comment by nateberkopec** [comment]
No, that's expected. You only need ragel when you build the Puma C-extension. You've already built it. If you blew away the Puma directory and started over, you'd notice that Puma won't build anymore.

**Comment by nateberkopec** [comment]
I thought maybe the problem here would be that we were redirecting the IO of the test process, but I don't see how that could happen.

With nothing more to go on + the fact that this doesn't seem to happen in CI, closing.
