### ISSUE TITLE
question about out_of_band / idea for avoiding all stop-the-world

### ISSUE THREAD

**Issue by jjb** [puma/puma#2420]
I just learned about the experimental `out_of_band`, neat stuff!

## question about out_of_band

I don't understand what is special about [`GC::OOB.run`](http://tmm1.net/ruby21-oobgc). Is there some sense in which it doesn't stop the world and is therefore appropriate for passing to `out_of_band`? But if so that shouldn't matter because it's only run when the process has no busy threads. Is there any reason to not pass `GC.start` or `GC.compact` to `out_of_band`?

## crazy idea

What if we disallowed ruby from doing its own GC and _only_ did it in certain opportune out_of_band situations? Then we would never have the world randomly stopped.

So something like this:

```ruby
nakayoshi_fork

on_worker_boot do
  GC.disable
end

# this probably depends on the answer to my first question above,
# but here's the gist of it
out_of_band do
  return unless 1==rand(100) # or whatever criteria
  GC.compact
end
```

**Comment by nateberkopec** [comment]
`GC::OOB.run` is like a special case of `GC.start`. `GC.start` _always_ runs a major GC. `GC::OOB.run` _might_ run a major GC if conditions are right. [GC::OOB.run is designed to run after every request but before Unicorn listens on the socket again.](https://github.com/tmm1/gctools/blob/master/lib/gctools/oobgc/unicorn_middleware.rb#L14). If you swapped GC.start into that position, you would trigger a GC after every request, which is probably unnecessary and would lead to way too much CPU usage.

> But if so that shouldn't matter because it's only run when the process has no busy threads

It does still matter, because you don't want to GC _every time_ the process is free/no-busy-threads. 

> Is there any reason to not pass GC.start or GC.compact to out_of_band?

You could, but passing `GC::OOB.run` would be better and avoid wasted CPU.

**Comment by nateberkopec** [comment]
> What if we disallowed ruby from doing its own GC and only did it in certain opportune out_of_band situations?

You could, but then you're running the risk of allowing requests to create infinite objects without GC. I've seen some bad things in my consulting, tens of millions of objects created in a single request. If someone took this approach and then created 10 million objects in a single request, they would see a major, major increase in memory usage, as GC's would not occur during the request, keeping heap size down, and instead would probably lead to increased memory bloat and RSS usage.

**Comment by jjb** [comment]
# out_of_band

gotcha - thank you for taking the time to provide that info! I hope it's useful for future googlers.

Maybe there could be an experimental_features.md that describes this and other things not covered in the docs (or is it in the docs and i missed it... sorry). If you like this idea I could make a PR with an initial version with copy lifted from blog posts etc.

# crazy idea

> GC::OOB.run _might_ run a major GC if conditions are right

I'm still wondering if this would be appropriate

```ruby
nakayoshi_fork

on_worker_boot do
  GC.disable
end

# this probably depends on the answer to my first question above,
# but here's the gist of it
out_of_band do
  GC::OOB.run
end
```

I'll ask the gctools folks

**Comment by jjb** [comment]
(never mind, seems that project is abandoned -  but I guess some folks are still using it with recent ruby versions, since puma is supporting it?)

**Comment by jjb** [comment]
(annd, now i saw your response re: GC.disable -- good point! will not do.)

**Comment by nateberkopec** [comment]
GCtools is abandoned because it was maintained by Github, [which no longer uses OOBGC](https://github.blog/2018-05-18-removing-oobgc/):

> For our application, the CPU savings far outdid the price we had to pay in average memory usage. Removing the OOBGC from our system resulted in a great savings for our systems. Taking measurements, acting on data, and questioning assumptions is one of the most difficult and fun parts of being an engineer. This time it paid off for us, and hopefully this post can help you too!
