### ISSUE TITLE
Puma 4.3.6 - Rails 6.0.3.4 - TLS brings in memory leak

### ISSUE THREAD

**Issue by Melchizedech** [puma/puma#2425]
**Describe the bug**
Creating a "hello world" rack application and configuring puma to run using TLS, excessive memory is used by the application.

**Puma config:**

```
threads 1, 1
workers 1
ssl_bind '0.0.0.0', 3000, {
    key: "certificates/certificate.key",
    cert: "certificates/certificate.crt",
    verify_mode: 'none',
    no_tlsv1: true,
    no_tlsv1_1: true
  }

bind 'tcp://0.0.0.0:3500'

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "server.pid" }
```

CLI : docker run --rm -p 3000:3000 -p 3500:3500 puma_tls_memory_leak

**To Reproduce**

I've created a repo and a dockerfile to be able to reproduce, using your hello world rack : 
https://github.com/Melchizedech/rails_puma_tls_memory_leak

Running `while :; do curl -k --location 'https://localhost:3000' -v ; done` will increase the RAM used by the application from 25MB (RSS) to 60MB (RSS). Then every minute or so, another extra MB (RSS) will be consumed.

If we instead run ``while :; do curl --location 'http://localhost:3000/' -v ; done``, the RAM used by the app increase from 25 to 32MB (RSS) and eventually, the app will start consuming extra MB of RAM.

I definitely think there is an issue on Puma with TLS.

Here is the graph of one application that we use, it is a small Rails app that receives close to _no_ user traffic. The "real" traffic it receives comes from the liveness probe. 

Cluster A : 
![App in a production cluster](https://user-images.githubusercontent.com/1233671/95807310-951cb580-0d55-11eb-892b-b18a06a8a490.png)

Cluster B :
![App in another production cluster](https://user-images.githubusercontent.com/1233671/95807312-964de280-0d55-11eb-8651-9aaee369b78f.png)

Here are some screenshots from the ram consumption of a brand new rails app only running the API mode, while we hit a non-existing route, behind a similar configuration.

Just after boot : 
![App after having booted in production mode](https://user-images.githubusercontent.com/1233671/95807377-c301fa00-0d55-11eb-88e5-583ec80b2f76.png)

After 6 min of constant cURL
![App after 6min of stress test on a non-existing route using HTTPS](https://user-images.githubusercontent.com/1233671/95807381-c4332700-0d55-11eb-9f75-3be593ac76ef.png)

After 28min of constant cURL
![App after 28min of stress test on a non-existing route using HTTPS](https://user-images.githubusercontent.com/1233671/95807382-c4cbbd80-0d55-11eb-83ef-0db167bb633a.png)
While I was testing the _brand new_ rails API to reproduce the issue (before swwitching for a Rack hello world app), I tried to use jemalloc, I've seen a strong improvement, _though_, it was still getting more RAM used (but a much, much, slower rate).

**Expected behavior**
I would expect the RAM consumption to not be increasing forever when I use TLS on Puma.

**Desktop (please complete the following information):**
 - OS: ArchLinux, (and also Debian via Dockerization)
 - Puma Version : 4.3.6 (but could also reproduce on 5.0.2)

Any help to debug/investigate that is welcomed.

**Comment by nateberkopec** [comment]
Is there any way you could post a graph of what your cluster looks like _without_ TLS enabled? Maybe put an SSL terminator in front of Puma, like nginx? Of course, we'll also be interested if this reproduces on 5.x.

Your production graphs are compelling. I'll take a look at the repro.

**Comment by Melchizedech** [comment]
I can try to put that app _without_ TLS in place on one of our staging environment and give you the result in several days.

Using such a solution won't work. (TL;DR: this is an app that requires encrypted traffic in our internal network. traffic between [outside, internal] <=> nginx will be encrypted but not nginx <=> puma). We will most likely use service mesh or a similar technology to remove the need for TLS within puma.


Here is three screenshots for puma 4.3.6 with HTTP
At boot time
![puma_http_beg](https://user-images.githubusercontent.com/1233671/95925464-90173f00-0e05-11eb-9e38-ef649e7a3726.png)

After 7min
![puma_http_7min](https://user-images.githubusercontent.com/1233671/95925454-8a215e00-0e05-11eb-99d0-09d318123909.png)

After 27min
![puma_http_27min](https://user-images.githubusercontent.com/1233671/95925459-8e4d7b80-0e05-11eb-89ad-f8171e9ca398.png)

here are 3 screenshots of puma 5.0.2 with HTTPS

At boot time
![puma5_beg](https://user-images.githubusercontent.com/1233671/95925506-ab824a00-0e05-11eb-976d-4a591204e328.png)

After 6 minutes
![puma5_6min](https://user-images.githubusercontent.com/1233671/95925500-a6bd9600-0e05-11eb-991a-0bd41de7c5e8.png)

After 33 minutes
![puma5_33min](https://user-images.githubusercontent.com/1233671/95925505-a91ff000-0e05-11eb-85c1-465d45b34ce6.png)

These screenshots are using the same hello world rack app.
only difference was a change in the gemfile

```
diff --git a/Gemfile b/Gemfile
index 8418cc4..781766f 100644
--- a/Gemfile
+++ b/Gemfile
@@ -3,4 +3,4 @@ git_source(:github) { |repo| "https://github.com/#{repo}.git" }
 
 ruby '2.7.2'
 
-gem 'puma', '~> 4.1'
+gem 'puma', '~> 5.0'
diff --git a/Gemfile.lock b/Gemfile.lock
index 50eda8b..b55ce66 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -2,14 +2,14 @@ GEM
   remote: https://rubygems.org/
   specs:
     nio4r (2.5.4)
-    puma (4.3.6)
+    puma (5.0.2)
       nio4r (~> 2.0)
 
 PLATFORMS
   ruby
 
 DEPENDENCIES
-  puma (~> 4.1)
+  puma (~> 5.0)
 
 RUBY VERSION
    ruby 2.7.2p137

```

**Comment by nateberkopec** [comment]
> Using such a solution won't work.

No problem, it was a long shot. Just figured I'd ask.

I'm less interested in memory usage after 20 to 30 minutes than I am in rate of growth after 6 to 12 hours of uptime.

If you have the same rate of growth in memory T+0 to T+1h as you do T+5h to T+6h, you have a leak. If it slows down over time, you don't.

**Comment by Melchizedech** [comment]
Okay, I'll deploy this hello world rack application with TLS, and I'll let it live for a day or two. I'll come back with the monitoring results.

**Comment by MSP-Greg** [comment]
@Melchizedech

Thanks for all the info.  Any info as to TLS protocols that are most likely being used?

In #1735, several people had issues with AWS not supporting TLSv1.3, which forced downgrade negotiation to TLSv1.2. 
 There wasn't any mention of memory leaks.  Hence, I'm wondering if this could be TLSv1.3 related.

I'll try to send several thousand connections to a server locally and see if I can repo a rise in memory.

**Comment by Melchizedech** [comment]
Hi @MSP-Greg, the TLS conf disables TLS 1.0 and TLS 1.1, leaving us with TLS 1.2 and TLS 1.3.

I don't know what is the protocol used by the liveness probe, but my guess would be 1.3.

The tests I performed were using TLS 1.3.
I have run another test, similar to the one previously, I've got the same increase using only TLS1.2
(`while :; do curl --tls-max 1.2  -k --location 'https://localhost:3000' ; done`) on a period over 30min.

**Comment by Melchizedech** [comment]
FYI : using curl with TLS 1.2 instead of TLS 1.3 (so most likely having one downgrade phase).

at boot
![puma5_tls12_beg](https://user-images.githubusercontent.com/1233671/96058834-0dab7f80-0ed8-11eb-814e-ecd252c3af6f.png)

at 9 min
![puma5_tls12_9min](https://user-images.githubusercontent.com/1233671/96058818-05ebdb00-0ed8-11eb-9de2-92eaa884270b.png)

at 29 min
![puma5_tls12_29min](https://user-images.githubusercontent.com/1233671/96058832-0b492580-0ed8-11eb-899f-a7420dc6b39f.png)

--- 
regarding the HTTP-only test, it is ongoing.

**Comment by Melchizedech** [comment]
Here is the plot for the same app as described in "Cluster A", _but_ using HTTP. We can see there is no change in ram consumption compared to TLS.
![Screenshot_20201015_181228](https://user-images.githubusercontent.com/1233671/96089154-23d63180-0f12-11eb-9ffb-a0c244e72311.png)

**Comment by nateberkopec** [comment]
@Melchizedech Was that app receiving any traffic? I assume your memory graphs from the TLS-on app was constantly receiving traffic.

**Comment by Melchizedech** [comment]
The app is receveing traffic from the liveness probe. 

The real user traffic has not been simulated.
 Though I can give it another go if needed. 


On October 15, 2020 1:23:44 PM UTC, Nate Berkopec <notifications@github.com> wrote:
>@Melchizedech Was that app receiving any traffic? I assume your memory
>graphs from the TLS-on app was constantly receiving traffic.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/puma/puma/issues/2425#issuecomment-709321599

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MSP-Greg** [comment]
@Melchizedech

I tested to see if there were any Ruby objects that GC was having issues with, and that doesn't seem to be an issue, in that running GC released all of them.

This weekend I'll run a few thousand TLS connections at a server and check the memory stats.

**Comment by S3od22** [comment]
Hi

**Comment by dentarg** [comment]
@Melchizedech do you want to try again with the newly release Puma 5.2 series?

**Comment by dentarg** [comment]
@l33z3r maybe you can find out for us?

**Comment by l33z3r** [comment]
Hi guys, just to chime in here. The issue I was having with leaking memory was not related to what is described in this issue.

**Comment by DaryMerckensGT** [comment]
> Hi guys, just to chime in here. The issue I was having with leaking memory was not related to what is described in this issue.

what was it related to?

**Comment by l33z3r** [comment]
> > Hi guys, just to chime in here. The issue I was having with leaking memory was not related to what is described in this issue.
> 
> what was it related to?

It was actually related to a memory leak in this gem: https://github.com/typhoeus/ethon
