### ISSUE TITLE
Better byebug integration

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2440]
[Cluster-mode Puma and byebug (default gem in Rails) play poorly together.](https://stackoverflow.com/questions/40998929/puma-rails-5-binding-pry-only-available-for-60-seconds-before-timeout)

Not sure what a good course of action is here.

**Comment by nateberkopec** [comment]
Unfortunately, I imagine debuggers hold the GVL while they're open, so I'm not sure we can do much.

Maybe we just need to open a PR to Rails to increase worker_timeout (or disable?) in dev.

**Comment by nateberkopec** [comment]
I wonder if we could detect whether or not a debugger session has begun.

**Comment by nateberkopec** [comment]
Other options here:

1. If we go into a debugger session, send something on the pipe that says "stop checking me, I'll be back later" and don't ever terminate that worker
2. Find a way to make the worker checkin pass even during a debugger session

**Comment by cjlarose** [comment]
I'm not sure the linked SO post is related. I use `pry` and `pry-remote` regularly on Rails apps running under cluster-mode puma that I help maintain and I don't encounter timeouts (`worker_timeout` is the default value of 60 seconds). I think `pry` only hijacks the currently-executing thread, so it doesn't affect the worker's check-in/heartbeat thread.

That said, I _think_ byebug is different in that it'll pause the execution of all Ruby threads of the process, so I think the _title_ of the issue might still be correct. Have you seen reports of byebug specifically causing a problem for people? There might be a better issue to link instead.

**Comment by nateberkopec** [comment]
Just took another look here. I'm 95% sure this is because byebug is using a c-ext to do what it does, and that c-ext does not unlock the GVL.

C-extensions hold the GVL unless explicitly unlocked, and other threads will not pre-empt a thread inside a C-extension, holding the GVL.

This is why you can't repro the issue with `pry`, because `pry` is written completely in Ruby.

I believe https://github.com/rails/rails/pull/40503 is the best workaround for this issue.
