### ISSUE TITLE
Puma 5.0.3 deprecation warning in Ruby 2.7 - warning: deprecated Object#=~ is called on Proc

### ISSUE THREAD

**Issue by ndbroadbent** [puma/puma#2455]
I just pushed a new branch to update to puma 5.0.3, and I've configured my CI builds to crash on any warnings. I'm now seeing this warning in the logs:

```
vendor/bundle/ruby/2.7.0/gems/puma-5.0.3/lib/puma/server.rb:94: warning: deprecated Object#=~ is called on Proc; it always returns nil
```
(This is not happening with puma 5.0.2.)

Here is the line: https://github.com/puma/puma/blob/master/lib/puma/server.rb#L94

It looks like it changed 27 days ago in #2389 - this commit: https://github.com/puma/puma/commit/bbce3d61f0ac87c1cc1baa3cd7f6a4157b610c4a

I found out that `:environment` is actually being set to a `Proc` here, in `puma_default_options`: https://github.com/puma/puma/blob/d0f75b472c7c32f0daa7ffd56b1c4d945538efb3/lib/puma/configuration.rb#L196

---

It looks like this case is not being hit in the test suite since I couldn't find "Object#=~" in any of the log output here: https://github.com/puma/puma/runs/1308878188?check_suite_focus=true
It might be a good idea to add a new test case that exercises this code path, and then fail the tests if there are any warnings:

```
module Warning
  def warn(msg)
    raise msg
  end
end
```

**Comment by nateberkopec** [comment]
Thanks for the heads up. The suggested course of action sounds good.

**Comment by MSP-Greg** [comment]
Thanks and interesting. We've also got the following, which is what I based the breaking code line on (I think):
https://github.com/puma/puma/blob/d0f75b472c7c32f0daa7ffd56b1c4d945538efb3/lib/puma/runner.rb#L20-L26

We'll add the warning change to the CI, as I've also seen some running locally...

**Comment by MSP-Greg** [comment]
Something is odd.

I don't know if I've ever really gone thru the configuration code, but `Puma::Configuration#clamp`, which calls `UserFileDefaultOptions#finalize_values`, should 'convert' the lambda's/proc's into values.  I must be missing something, or something's wrong with the code.

One problem with warnings is some are thrown by Ruby classes themselves in older Ruby versions.  We still should be able to check them in the integration tests.

**Comment by MSP-Greg** [comment]
@ndbroadbent

Using 5.0.3, I've started Puma via bin/puma and bin/rackup, and `@options[:environment]` is a String, or, no warnings.  How are you starting Puma?

**Comment by ndbroadbent** [comment]
@MSP-Greg Really sorry for the missing details - I should have mentioned that puma does start correctly during development (and presumably production), but I run into this warning while running my RSpec test suite, which uses Capybara to start the puma server. I'm not familiar with how capybara is calling puma, but it could be skipping this `UserFileDefaultOptions#finalize_values` step. I wonder if this might be a bug in capybara in that case.

**Comment by ndbroadbent** [comment]
Yep, I put a breakpoint in there, and `conf.options[:environment]` was the `Proc`. Calling `conf.options.finalize_values` fixed the issue so that `conf.options[:environment]` now returns `"test"`. So I'll close this and open a PR in Capybara
