### ISSUE TITLE
puma_http11 license clarification

### ISSUE THREAD

**Issue by Silviu-Caprar** [puma/puma#2480]
Hi,

Regarding the following file, https://github.com/puma/puma/blob/v4.3.5/ext/puma_http11/http11_parser.c and others similar in the puma_http11 folder, can you please specify which license apply ?

Is it the Ruby(GPL or BSD 2-Clause from Ruby) ?
Is it the BSD 3-Clause License mentioned in the LICENSE file from root ?
Are both license applicable or just a choice between Ruby(GPL or BSD 2-Clause ?) and BSD 3-Clause License ?

Thank you,

**Comment by nateberkopec** [comment]
The original code from the Mongrel project is Ruby licensed (BSD 2-Clause/GPLv2 choice). The code that we added and changed since then would be BSD 3-clause licensed.

**Comment by nateberkopec** [comment]
IANAL, but the copyright notice in puma_http11 is just there to help us comply with the original BSD license terms:

> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

We already have the conditions and disclaimer (BSD 3-clause), so those are not included in the file.

Perhaps we could remove the "You can redistribute" line for clarity?
