### ISSUE TITLE
Exception raised on Waited connection

### ISSUE THREAD

**Issue by gr790** [puma/puma#2492]
**Describe the bug**
Puma is returning 500 error to client because puma thread couldn't find the db connection and throws this exception. It is happening in production and not able to reproduce in Lab. 1 out of 4 workers is not able to process the http request because of this exception, other 3 workers state is fine. 
I am using redis_cache_store,with pool size of 40 connection, this cache is configured in environments/production.rb.  
Puma config has 4 workers, 10 threads in each worker.
I understand configuring connection_pool in config.cache_store is global and below 40 connections are shared about all 4 workers and master process. So there are sufficient number of db connection available for threads to process the requests. 
Other things I noticed, puma created more threads what is configured in puma.conf. 

**Puma config:**
Rails: 5.2.2
Puma: 3.12.1
OS: RHEL 7.7
connection_pool: 2.2.2
Ruby: 2.5.3-2

I understand we are leaking connection, could you please help us to debug this and throw some insight what might be happening. 
**To Reproduce**
Run the load with HTTP request which is being forwarded to Puma from nginx, and process by internal logic, internally it talks to Redis using Rails.cache.fetch and Rails.cache.write. 

**Expected behavior**
There shouldn't be 500 http error response to client.

Here is the stack.

        exception raised is: Waited 10 sec
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:87:in `block (2 levels) in pop'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `loop'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:79:in `block in pop'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `synchronize'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool/timed_stack.rb:78:in `pop'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:93:in `checkout'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:62:in `block in with'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
        /app/vendor/bundle/ruby/2.5.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/redis_cache_store.rb:331:in `block in read_entry'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/redis_cache_store.rb:446:in `failsafe'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/redis_cache_store.rb:330:in `read_entry'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache.rb:124:in `block in read_entry'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache.rb:78:in `block in fetch_entry'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache.rb:78:in `fetch'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache.rb:78:in `fetch_entry'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache.rb:124:in `read_entry'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/redis_cache_store.rb:74:in `read_entry'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache.rb:313:in `block in fetch'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache.rb:663:in `block in instrument'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache.rb:663:in `instrument'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache.rb:312:in `fetch'
        /app/lib/cdu/nsr_cache/convert_pdp.rb:180:in `ref_to_values'
        /app/lib/cdu/nsr_cache/convert_pdp.rb:78:in `block in convert_pdp'
        /app/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:238:in `block in each'
        /app/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `upto'
        /app/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/node_set.rb:237:in `each'
        /app/lib/cdu/nsr_cache/convert_pdp.rb:76:in `convert_pdp'
        /app/lib/cdu/receiver/request_processor.rb:115:in `convert_response'
        /app/lib/cdu/receiver/request_processor.rb:72:in `response_handler'
        /app/lib/cdu/receiver/request_processor.rb:20:in `block in initialize'
        /app/lib/cdu/receiver/request_processor.rb:44:in `receive'
        /app/app/controllers/cdu_controller.rb:52:in `v82'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:194:in `process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:134:in `process'
        /app/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.2/lib/action_view/rendering.rb:32:in `process'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:191:in `dispatch'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_controller/metal.rb:252:in `dispatch'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `each'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `serve'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
        /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/rack/logger.rb:28:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
        /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
        /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
        /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
        /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'

**Comment by nateberkopec** [comment]
> Other things I noticed, puma created more threads what is configured in puma.conf.

This is mentioned in the README: Puma creates several other threads for internal use.

> I understand configuring connection_pool in config.cache_store is global and below 40 connections are shared about all 4 workers and master process

This is incorrect - the connection pool in that particular gem is per-process. So you should only need 10 connections configured.

It sounds like you have a connection leak. Usually these are related to timeouts: the connection times out while waiting on a response, and then some internal state is corrupted where the connection is still "in the pool" but it is never again marked as free/available.

This is not a Puma bug or issue, so I will close.
