### ISSUE TITLE
Supporting Custom Logger Class

### ISSUE THREAD

**Issue by jchristie55332** [puma/puma#2511]
**Is your feature request related to a problem? Please describe.**

It is possible to have custom loggers that allow for json log aggregation as well as formatting and custom attributes.

Without json log aggregation results in poorly formatted logs and duplication of log formatting rules.

**Describe the solution you'd like**

It would be great to pass a custom logging class to puma that would then be logged to.

I would expect this to result in a new method in the DSL.

**Comment by nateberkopec** [comment]
Does `log_formatter` do what you want?

e.g.

```ruby
log_formatter do |str|
  "[#{Process.pid}] [#{Socket.gethostname}] #{Time.now}: #{str}"
end
```

**Comment by jchristie55332** [comment]
> Does `log_formatter` do what you want?
> 
> e.g.
> 
> ```ruby
> log_formatter do |str|
>   "[#{Process.pid}] [#{Socket.gethostname}] #{Time.now}: #{str}"
> end
> ```

No.  Using `log_formatter` still results in the formatted string being output to STDOUT.

I suggest that we support the use of a custom logger for outputting of log lines (https://github.com/puma/puma/blob/master/lib/puma/events.rb#L65).  I was also thinking that we could include for the `ErrorLogger`

**Comment by kuei0221** [comment]
How about  `stdout_redirect` ? It will save the STDOUT to the file you want.
https://github.com/puma/puma/blob/503b1cde5347ce9e78f81cc3b6b1724508c8ba1a/lib/puma/dsl.rb#L388-L399

**Comment by alexeevit** [comment]
So, do you want to have

**Comment by nateberkopec** [comment]
Generally with a custom logger I would expect a config interface like:

```ruby 
logger Logger.new(STDOUT)
```

**Comment by svoop** [comment]
For reference, the interface is a little different from what @nateberkopec has suggested:

```
custom_logger Logger.new(STDOUT)
```
