### ISSUE TITLE
Reject unregistered HTTP Methods

### ISSUE THREAD

**Issue by jeyraof** [puma/puma#2513]
A lot of bots scan our application with unknown stringified HTTP method such as `XOXBHA`, `SDLDHW` and so on.
In general, people set it at web-server like nginx to:

```config
server {
  if ($request_method !~ ^(GET|HEAD|PUT|POST|DELETE|OPTIONS|PATCH)$ ){
    return 405;
  }
}
```

Is there any way to handle this situation on Puma configuration?

**Comment by dentarg** [comment]
Sounds like something a rack middleware should do (and not Puma).

**Comment by nateberkopec** [comment]
This information is available in the Rack environment as `REQUEST_METHOD`, you can filter it that way. Maybe a feature for the `rack-attack` gem to implement.
