### ISSUE TITLE
puma config 'daemonize' 

### ISSUE THREAD

**Issue by uestcsp** [puma/puma#2518]
puma version 5.1.1
there is no 'daemonize' params?
how can i make my server as a daemonize?

**Comment by dentarg** [comment]
See https://github.com/puma/puma/issues/2488#issuecomment-731580617 and https://github.com/puma/puma/issues/2488#issuecomment-731582093

**Comment by kigster** [comment]
Please see this functionality has been extracted into [puma-daemon](https://github.com/kigster/puma-daemon) ruby gem.
