### ISSUE TITLE
Native request timeouts

### ISSUE THREAD

**Issue by bezoar17** [puma/puma#2523]
**Is your feature request related to a problem? Please describe.**
Why doesn't Puma support native request timeouts which is kind of expected feature from a production worthy server? We have to add Rack middleware to get this.

**Describe the solution you'd like**
A simple config which allows us to terminate requests after the specified timeout, similar to what Unicorn has.

**Describe alternatives you've considered**
Adding rack middleware(rack-timeout). It just feels that an application server should have a request timeout feature out of the box. Rack timeout has it's own issues.

**Comment by dentarg** [comment]
>Rack timeout has it's own issues.

Puma can't magically solve these issues I think. You have to ask yourself why requests are running longer than you think they should.

I think Puma already has some related timeout options, have you read about them?

**Comment by nateberkopec** [comment]
See #265. Rack middleware can solve this just as well as Puma can. There's no reason for us to duplicate the efforts of rack-timeout.
