### ISSUE TITLE
Puma::MiniSSL::SSLError: System error: Undefined error: 0 - 0 with 5.2.0

### ISSUE THREAD

**Issue by mscrivo** [puma/puma#2542]
**Describe the bug**

Since upgrading our app to use 5.2.0 (from 5.1.1), our devs have been getting the following error on particular endpoints:

`SSL error, peer: 127.0.0.1, peer cert: : #<Puma::MiniSSL::SSLError: System error: Undefined error: 0 - 0`

The problem is 100% reproducible on some endpoints, but not other in the same app. I'm still trying to figure out what the difference is, but haven't been able to yet. 

Going back to 5.1.1 results in no SSL errors.

```
Puma starting in single mode...
* Puma version: 5.2.0 (ruby 2.7.1-p83) ("Fettisdagsbulle")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 40350
* Listening on ssl://0.0.0.0:446?key=key&cert=crt
Use Ctrl-C to stop
127.0.0.1 - - [29/Jan/2021:21:34:03 -0500] "GET /feature-gating-new HTTP/1.1" 200 29552 0.2847
2021-01-29 21:34:03 -0500 SSL error, peer: 127.0.0.1, peer cert: : #<Puma::MiniSSL::SSLError: System error: Undefined error: 0 - 0>
127.0.0.1 - - [29/Jan/2021:21:34:05 -0500] "GET /api/pages/home HTTP/1.1" 200 495 0.0305
127.0.0.1 - - [29/Jan/2021:21:34:07 -0500] "GET /api/pages/feature-gating-new HTTP/1.1" 200 20666 0.1790
2021-01-29 21:34:07 -0500 SSL error, peer: 127.0.0.1, peer cert: : #<Puma::MiniSSL::SSLError: System error: Undefined error: 0 - 0>
```

**Puma config:**

command line args:
`bundle exec  puma -v -b "ssl://0.0.0.0:446?key=key&cert=cert" -b "tcp://0.0.0.0:83" app/config.ru`

The cert is a valid wildcard cert from a CA.

config.ru has no special configuration for dev, just loads our sinatra app.

**To Reproduce**

Unfortunately, I cannot reproduce with a simple Hello world app, which indicates it's probably something in the payload of the endpoint?  Is there a way I can enable more verbosity to give us a clue of where the error is coming from?

I did want to bring this up though, in case there's an implementation issue with the SSL changes that went into 5.2

**Expected behavior**
No SSL errors

**Desktop (please complete the following information):**
 - OS: Mac 11.1
 - Puma Version 5.2
 - OpenSSL 1.1.1i  8 Dec 2020, installed with brew and symlinked

**Comment by MSP-Greg** [comment]
@mscrivo

> The problem is 100% reproducible on some endpoints, but not other in the same app.

I'll look at the code, a few things:

1. Is there anything different about the failing endpoints?  It would be helpful to know, and I really mean anything...

2. Just to clarify, when you say '100%', you mean that anytime the endpoint is hit, it errors?  IOW, particular endpoints **always fail**, they do not fail intermittently?

3. The log seems to show the error after the response is logged, do you know if Puma is sending the response?

> Is there a way I can enable more verbosity to give us a clue of where the error is coming from?

At present, no.  'Undefined error: 0 - 0' is obviously not very helpful.  Passing more information from OpenSSL to Ruby/Puma is messy, but I think I have code somewhere that implements it...

> I did want to bring this up though

Thank you for doing so.  I will work on this over the weekend.  A few of us tested this, and I was testing with response bodies from about 10kB up to 200kB, and up to 40k connections.  It was stable, so I'm very interested in sorting this out...

**Comment by mscrivo** [comment]
> 1. Is there anything different about the failing endpoints?  It would be helpful to know, and I really mean anything...

Yeah I'm trying to figure that out, so far I haven't found anything of note.  For example, one endpoint we have to return feature gates for one customer is working fine (5kb response) and one that returns for all is failing (20kb response). But I have other endpoints that are returning over 100kb responses that are working just fine.

> 2. Just to clarify, when you say '100%', you mean that anytime the endpoint is hit, it errors?  IOW, particular endpoints **always fail**, they do not fail intermittently?

yeah the same endpoint, with the same payload always errors.  But I'm noticing now, that it actually returns the response, but in chrome it shows `net::ERR_CONTENT_LENGTH_MISMATCH`

If I run one of the bad ones with curl, it shows: `curl: (18) transfer closed with 46 bytes remaining to read`

> 3. The log seems to show the error after the response is logged, do you know if Puma is sending the response?

It is sending the response as noted above.

**Comment by MSP-Greg** [comment]
Thanks for looking into it.  I'm able to see the error in the server log, but I'm seeing a little different error.
```
peer: 127.0.0.1, peer cert: : #<Puma::MiniSSL::SSLError: System error: Success - 0>
```

> but in chrome it shows net::ERR_CONTENT_LENGTH_MISMATCH

Also working with Chrome.  Hate to ask, where do you see that error?

With curl, I don't see any issues.  Also, it seems that if the body in the rack response is an io, I don't see an error.

Anyway, I'm still trying to track down where the error is being thrown...

**Comment by mscrivo** [comment]
> Also working with Chrome. Hate to ask, where do you see that error?

On the network tab of dev tools, under the status column.

**Comment by MSP-Greg** [comment]
@mscrivo

Might have a solution, the current line:
https://github.com/puma/puma/blob/f7f58ae2ae9e6feb71c1fb80d0fa51471aef9006/lib/puma/minissl.rb#L136

needs to change to:
```ruby
data = data.byteslice(wrote..-1)
```

Is it possible for you to try that?

**Comment by mscrivo** [comment]
That fixes it! Nice work and thanks for looking at it so quickly.

**Comment by MSP-Greg** [comment]
@mscrivo

Hold off on that for a second, it may be truncating a few bytes of the body...  Some of the MiniSSL method is using bytes, some of it is using characters, and...
