### ISSUE TITLE
Puma 5.2 log not flushed

### ISSUE THREAD

**Issue by denisj** [puma/puma#2545]
Since I upgrade to Puma 5.2, the logs are not flushed right away.

```
# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

# Specifies the `worker_timeout` threshold that Puma will use to wait before
# terminating a worker in development environments.
#
worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
port ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked web server processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
# workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory.
#
# preload_app!

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

In Puma 5.1.1, the logs where flush right away on stdout.

 - OS: Ubuntu 18.04
 - Docker version 20.10.3, build 48d30b5
 - Ruby 2.7.2 or 3.0
 - Puma Version 5.2

**Comment by protomonk** [comment]
Can confirm there is an issue. We are running Rails app on Kubernetes with puma 5.2 and logs (collected by Kubernetes) from stdout are delayed up to 30min.

**Comment by lukaspili** [comment]
Same here for a stock rails 6.1 app with puma 5.2: on Heroku, application logs are delayed or require a significant amount of content to be logged in order to be flushed and displayed.

**Comment by nateberkopec** [comment]
Try `STDOUT.sync = true` in an initializer

**Comment by cjlarose** [comment]
@nateberkopec One option to consider is that we might want to add `STDOUT.sync = true` in a bugfix release for puma 5.2, then remove it for `6.0`. I can empathize with the idea that since Puma no longer mutates the global `STDOUT` to be in `sync` mode, that's a breaking change and warrants a major version bump.

**Comment by cjlarose** [comment]
When the 6.0 release is ready, we can prepare documentation around how to update your application so that logs continue to be flushed immediately and verify the instructions on common platforms like Heroku.

**Comment by nateberkopec** [comment]
It's sort of unbelievable that we [just expect application servers to do this](https://github.com/defunkt/unicorn/blob/2c347116305338710331d238fefa23f00e98cf54/lib/unicorn/launcher.rb#L4).

**Comment by cjlarose** [comment]
Oh I agree, but if we're going to change the status quo, we should be loud about it.

**Comment by nateberkopec** [comment]
I didn't actually think people expected us to do it. I kind of thought during the first go around we just missed something, and that this time around we did it right. But the ecosystem really revolves around application servers setting `STDOUT` to `sync`.

**Comment by denisj** [comment]
Thx for your answer.

I created a initiazer in my projects: (config/initializers/puma_logs_fix.rb)
```ruby
# https://github.com/puma/puma/issues/2545
STDOUT.sync = true
```

It solved the issue on my dev env, but not on my prod env.
I'm using docker swarm to deploy on AWS EC2 machines, and I'm using the awslogs driver to send my logs to CloudWatch.
```
logging:
      driver: "awslogs"
      options:
        awslogs-region: "us-east-2"
        awslogs-group: "YYY"
        awslogs-stream: "XXX"
```

**Comment by nateberkopec** [comment]
@denisj re: docker, if you run that container locally with `RAILS_ENV=production` and a different logs driver, like `local`, do you see anything?

**Comment by nateberkopec** [comment]
Rails applications may also want to try [rails_stdout_logging](https://github.com/heroku/rails_stdout_logging)

**Comment by nateberkopec** [comment]
I think @cjlarose is right that we have to bring back `STDOUT.sync=true` until 6.0 and provide the upgrade path from there.
