### ISSUE TITLE
Puma server restarts when pumactl stop

### ISSUE THREAD

**Issue by seoanezonjic** [puma/puma#2551]
**Describe the bug**
I'm deploying my app in AWS Elastic Beanstalk services and I want to stop the app before make a new deployment. I have to do this because the free memory when the app is running is not enough to perform the deployment and the process fail when the gem native extensions are compiled. So I execute the following comand

bundle exec ./bin/pumactl stop

Or kill the puma main process:

kill -9 PID

The puma processes are shut down but then the puma server is loaded again automatically ( i don't execute any command).

**Puma config:**

``` Ruby
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
#
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 3 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
#
port        ENV.fetch("PORT") { 3000 }

# Specifies the `environment` that Puma will run in.
#
environment ENV.fetch("RAILS_ENV") { "development" }

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
directory '/var/app/current'
#threads 8, 32
bind 'unix:///var/run/puma/my_app.sock'
stdout_redirect '/var/log/puma/puma.log', '/var/log/puma/puma.log', true

# Specifies the number of `workers` to boot in clustered mode.
# Workers are forked web server processes. If using threads and workers together
# the concurrency of the application would be max `threads` * `workers`.
# Workers do not work on JRuby or Windows (both of which do not support
# processes).
#
 #workers %x(grep -c processor /proc/cpuinfo)
 workers ENV.fetch("WEB_CONCURRENCY") { 2 }

# Use the `preload_app!` method when specifying a `workers` number.
# This directive tells Puma to first boot the application and load code
# before forking the application. This takes advantage of Copy On Write
# process behavior so workers use less memory.
#
 preload_app!

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

**To Reproduce**
I cannot give a proper reproduction example but I can give more details. The puma server is loaded with a Procfile:

``` bash
web: puma -C ./config/puma_production.rb
```
I use rails 6.0.3.4 and ruby 2.5.8 and nginx server too.

**Expected behavior**
Shutdown all puma processes without start a new puma cluster.

**Desktop (please complete the following information):**
 - OS: AWS platform => Ruby 2.5 running on 64bit Amazon Linux 2
 - Puma Version 5.2.0

**Comment by nateberkopec** [comment]
> The puma processes are shut down but then the puma server is loaded again automatically

Puma can't actually do that by itself. If you tell it to stop via the control server or send it SIGKILL, as you did, it will not restart.

Something else in your deployment is restarting it, probably ElasticBeanstalk. [It looks like this is just something it does.](https://stackoverflow.com/questions/19835455/how-to-restart-node-application-automatically-on-aws-elastic-beanstalk) I have no knowledge about how to configure this behavior.

Because this is not a Puma issue, closing. Good luck!
