### ISSUE TITLE
Undefined constant on platforms without tcp_cork support  and with closed_socket support

### ISSUE THREAD

**Issue by gamecreature** [puma/puma#2556]
Missing constant `Read: #<NameError: uninitialized constant Puma::Server::UNPACK_TCP_STATE_FROM_TCP_INFO>` on platforms that have no 'tcp_cork_support?' and do have 'closed_socket_supported?'

https://stackoverflow.com/questions/66088219/pumaserverunpack-tcp-state-from-tcp-info/66214024#66214024

In file `lib/puma/server.rb`  is the following construct:

```ruby 
    if tcp_cork_supported?
      UNPACK_TCP_STATE_FROM_TCP_INFO = "C".freeze
      # ...
    end 
 
    if closed_socket_supported?
     # ... 
      state = tcp_info.unpack(UNPACK_TCP_STATE_FROM_TCP_INFO)[0]
    end
```

If tcp_cork_supported? is FALSE  and closed_socket_supported? is TRUE, an uninitialized constant Puma::Server::UNPACK_TCP_STATE_FROM_TCP_INFO is used! 

Is it a problem to move  'UNPACK_TCP_STATE_FROM_TCP_INFO = "C".freeze' outside the if condition?

**Comment by MSP-Greg** [comment]
@gamecreature

Thanks. This is a bug, as `UNPACK_TCP_STATE_FROM_TCP_INFO` is defined in the incorrect location.  Not picked up by the available CI OS's...

**Comment by dentarg** [comment]
Regression since Puma v5.0.1: https://github.com/puma/puma/commit/7928173d70f301347d184362afdab740ceb43569 (also  related: https://github.com/puma/puma/commit/55e4ead9b83e46b5e72da0b1a55b61a67f64b14a)

**Comment by gamecreature** [comment]
Thank you!!

**Comment by khustochka** [comment]
It is reproduced for me on FreeBSD  13.0-RELEASE

Puma version: 5.2.2 (ruby 3.0.1-p64) ("Fettisdagsbulle")

Is there anything I may be doing wrong, or any debug information I can provide?

Thank you!

**Comment by MSP-Greg** [comment]
Bug fixed in master by the above referenced PR / commit.  So, next release

**Comment by khustochka** [comment]
Thank you! 

Sorry, I assumed it is released from the dates.
