### ISSUE TITLE
TestCLI#test_control sometimes failing on arm64

### ISSUE THREAD

**Issue by lucaskanashiro** [puma/puma#2562]
**Describe the bug**

In Ubuntu, the `TestCLI#test_control` has been intermittently failing on `arm64`. Ubuntu bug report:

https://bugs.launchpad.net/ubuntu/+source/puma/+bug/1906307

The `pool_capacity` value sometimes is `0` and the expected is `16` due to the `max_threads` value. Not sure exactly what is happening here, any help to understand this is appreciated.

**Puma config:**

Not applicable.

**To Reproduce**

Run the tests in Ubuntu arm64 system.

**Expected behavior**

This test passes reliably on arm64.

**Comment by lucaskanashiro** [comment]
This is still an issue with the current version we are willing to release in Ubuntu 21.04, which is version `4.3.6`. Below an example of this failure (it was executed today):

https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-hirsute-lucaskanashiro-puma/hirsute/arm64/p/puma/20210301_185140_280db@/log.gz

And I just ran the tests against `master` in my testing VM and I was not able to reproduce it. As I mentioned this failure does not happen all the time, it happens intermittently in the Ubuntu infrastructure.

**Comment by MSP-Greg** [comment]
In the past, there wasn't really a clear policy about older versions.  I believe the current policy is that security patches will be applied one major version back, and other bugs are at the discretion of the maintainers.

**Comment by nateberkopec** [comment]
Interesting. The failure is fairly straightforward so might not be too hard to fix.

**Comment by nateberkopec** [comment]
> This bug was fixed in the package puma - 4.3.6-1ubuntu4
