### ISSUE TITLE
Add config option to manually define Rack url scheme

### ISSUE THREAD

**Issue by tarragon** [puma/puma#2569]
We need to run Puma behind a service that is unfortunately not passing down `HTTP_X_FORWARDED` headers. We also need to run Puma on a port other than port 443 and not in SSL mode, while the frontend service handles the SSL.

This has caused a problem within Puma where redirects generated by Rails (notably on session create) use `http` rather than `https` and this is confusing clients and the frontend service.

The only way I can find in Puma itself to set Rack's url scheme is with this line in `lib/puma/request.rb`:

`env[RACK_URL_SCHEME] = default_server_port(env) == PORT_443 ? HTTPS : HTTP`

Following the thread, `default_server_port` checks if Puma is running in SSL mode, then checks if the `X_FORWARDED` headers are there, returning `PORT_443` in this case, otherwise `PORT_80`. To work around this I have monkey patched `default_server_port` to return `PORT_443` in our environment regardless.

It would be great to be able to more explicitly control the Rack url scheme, and I suggest that the port assumptions here could do with refactoring for environments where Puma is running on a custom port (neither 443 or 80).

If there's some other way to achieve what I'm trying to achieve or if I've missed some configuration option, please let me know.

**Comment by tarragon** [comment]
Hey there, I notice this has a contrib-wanted label now, is there anything I can do to help?

**Comment by MSP-Greg** [comment]
I'm adjusting some things in PR #2586, which adds the feature...  Thanks.
