### ISSUE TITLE
How to UrlEncode original url when it include blank space

### ISSUE THREAD

**Issue by Sylor-huang** [puma/puma#2570]
Version: 

```ruby
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'puma', '~> 5.2', '>= 5.2.2'
```

When the original url include blank space, puma will return `Puma::HttpParserError: Invalid HTTP format`

Test Curl: 

```
curl -I "http://127.0.0.1:3000/api/v1/vendor/click?APP_NAME=Bnext -nex "
```
Puma return error:
```
HTTP parse error, malformed request ("HEAD /api/v1/vendor/clickAPP_NAME=Bnext" - (-)): #<Puma::HttpParserError: Invalid HTTP format, parsing fails. Are you trying to open an SSL connection to a non-SSL Puma?>
```

Is there any method  to encode the blank space and then puma handler the new url?

Such like this `curl -I "http://127.0.0.1:3000/api/v1/vendor/click?APP_NAME=Bnext%20-nex%20"`, puma works fine.

Thanks so much~

**Comment by nateberkopec** [comment]
Spaces are disallowed in URLs, so your URL is not valid. Puma is correctly raising an error. You must percent-encode spaces for Puma to parse your URL.
