### ISSUE TITLE
on_refork not working?

### ISSUE THREAD

**Issue by vtt** [puma/puma#2582]
**Describe the bug**
The on_refork doesn't seem to trigger in fork_worker mode in Puma version 5.2.2

**Puma config:**
```ruby
rails_env = ENV.fetch("RAILS_ENV") { "development" }
threads 5, 10
environment rails_env
bind 'unix://tmp/sockets/puma.sock'
workers 5
pidfile 'tmp/pids/puma.pid'
state_path 'tmp/pids/puma.state'
fork_worker
nakayoshi_fork
wait_for_less_busy_worker

on_worker_boot do
  puts "#{Process.pid}: worker boot"
end

on_worker_shutdown do
  puts "#{Process.pid}: worker shutdown"
end

before_fork do
  puts "#{Process.pid}: before fork"
end

on_refork do
  puts "#{Process.pid}: on_refork"
end

after_worker_fork do |worker_index|
  puts "#{Process.pid}: after_worker_fork #{worker_index} of #{@options[:workers]}"
end

on_restart do
  puts "#{Process.pid}: on restart"
end
```
**To Reproduce**
Run puma server with above config but will not see the output for on_refork

**Comment by cjlarose** [comment]
By default reforking only happens once per 1000 requests. Are you sending 100 requests to the server? 

https://github.com/puma/puma/blob/master/docs/fork_worker.md

**Comment by vtt** [comment]
So it only triggers on subsequent reforks, but not on the initial reforks from process 0 at startup...  Thanks.

**Comment by cjlarose** [comment]
That's correct. The relevant code is here:

https://github.com/puma/puma/blob/1acb30d68d8fd57dac8f50af4204522086da7a70/lib/puma/cluster/worker.rb#L79
