### ISSUE TITLE
rails puma unix socket not work in wsl ubunt

### ISSUE THREAD

**Issue by ashotmark** [puma/puma#2594]
"rails s" returns following error
=> Rails 6.0.3.6 application starting in development
....
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://127.0.0.1:3000
* Listening on tcp://[::1]:3000
Exiting
Traceback (most recent call last):
        22: from bin/rails:9:in `<main>'
        21: from bin/rails:9:in `require'
        20: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/commands.rb:18:in `<top (required)>'
        19: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/command.rb:46:in `invoke'
        18: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/command/base.rb:69:in `perform'
        17: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        16: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        15: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        14: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:138:in `perform'
        13: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:138:in `tap'
        12: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        11: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-6.0.3.6/lib/rails/commands/server/server_command.rb:39:in `start'
        10: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
         9: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/rack/handler/puma.rb:73:in `run'
         8: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/launcher.rb:172:in `run'
         7: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/single.rb:98:in `run'
         6: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/runner.rb:161:in `load_and_bind'
         5: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/binder.rb:90:in `parse'
         4: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/binder.rb:90:in `each'
         3: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/binder.rb:151:in `block in parse'
         2: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/binder.rb:327:in `add_unix_listener'
         1: from /home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/binder.rb:327:in `new'
/home/prime/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-4.3.7/lib/puma/binder.rb:327:in `initialize': Operation not supported - connect(2) for /mnt/f/projects/propopen/developments/propopen/shared/sockets/puma.sock (Errno::ENOTSUP)

System configuration
Ruby version: 2.6.6
Rails version: 6.0.3.6
Puma version: 4.1

Using WSL Ubuntu for Win10

**Comment by MSP-Greg** [comment]
@ashotmark

You're using Puma 4.3.7, which does have several tests involving UNIXSockets.

Just to verify, are you using WSL or WSL2?  I haven't used 4.3.7 for a while, but UNIXSockets have worked with WSL2/Ubuntu 20.04 for several months, and the error `Errno::ENOTSUP` implies that UNIXSockets aren't available?

What output do you get with the following?  If it outputs 'nil', you've got to update WSL to WSL2...
```
ruby -rsocket -e "puts defined?(UNIXSocket).inspect"
```

**Comment by ashotmark** [comment]
it outputs constant
![image](https://user-images.githubusercontent.com/79971000/114082853-f06bd280-98b6-11eb-9f2d-da6857c9ec0c.png)

**Comment by MSP-Greg** [comment]
@ashotmark

I think the problem is that a UNIXSocket/Server doesn't seem to be able to be created on a Windows folder, which ` /mnt/f/...`
is?

**Comment by ashotmark** [comment]
Thanks, puma issue was solved with your help!
