### ISSUE TITLE
SSL error, peer: 127.0.0.1, peer cert: : #<Puma::MiniSSL::SSLError: HTTP connection?>

### ISSUE THREAD

**Issue by brendon** [puma/puma#2603]
**Describe the bug**
Running Rails `6.1` system tests using the following config:

```
require "test_helper"

Capybara.app_host = "https://test.spikeatschool.test:#{Capybara.server_port}"
Capybara.server = :puma, {
  Host: "ssl://#{Capybara.server_host}?key=test/ssl/test.spikeatschool.test-key.pem&cert=test/ssl/test.spikeatschool.test.pem"
}

class ApplicationSystemTestCase < ActionDispatch::SystemTestCase
  driven_by :selenium, using: :headless_chrome, screen_size: [1400, 1400]
end
```

causes the following output:

```
Capybara starting Puma...
* Version 5.2.2 , codename: Fettisdagsbulle
* Min threads: 0, max threads: 4
* Listening on ssl://127.0.0.1:55520?key=test/ssl/test.spikeatschool.test-key.pem&cert=test/ssl/test.spikeatschool.test.pem
2021-04-18 21:15:48 +1200 SSL error, peer: 127.0.0.1, peer cert: : #<Puma::MiniSSL::SSLError: HTTP connection?>
```

Whilst then continuing through to successfully run the tests.

I've traced that to here:
https://github.com/puma/puma/blob/7ca15c152f32c4e1dfd5cf5bd5674ff2b9c6c03f/lib/puma/minissl.rb#L102

and

https://github.com/puma/puma/blob/7ca15c152f32c4e1dfd5cf5bd5674ff2b9c6c03f/lib/puma/minissl.rb#L52-L54

Via this commit: https://github.com/puma/puma/commit/ee8596237fb25cbc3a908586f4100e37ff4d77c6

**Puma config:**

ssl://127.0.0.1:55520?key=test/ssl/test.spikeatschool.test-key.pem&cert=test/ssl/test.spikeatschool.test.pem

**To Reproduce**
Per the introduction

**Expected behavior**
I'd not expect to see the error message, or at least some better explanation as to what it means. Having read through the commit, it seems like something is probing the puma server soon after it boots with an http request. Perhaps this is Rails? It certainly happens way before the actual tests start running (I can see that from the test log file as it runs).

**Desktop (please complete the following information):**
 - OS: Mac
 - Puma Version `5.2.2`

**Comment by MSP-Greg** [comment]
@brendon

With TLS protocols previous to TLSv1.3, the OpenSSL files would drop the connection.  With TLSv1.3, that behavior changed.

As most web/app servers today queue up client requests, those connections are added to a queue, and take up space that could be taken by valid requests.

At present Puma log a message for this, it's equivalent to 'a request has not negotiated it's tls handshake, so it's being dropped'.

Could we remove that log message?  I don't have strong feelings about it, but some people may find it helpful...

**Comment by nateberkopec** [comment]
Interesting. Perhaps we can consider if the appropriate log level is being used here. The message in question feels like a `debug`-level message to me.

**Comment by brendon** [comment]
Thanks @MSP-Greg and @nateberkopec. I guess in a way it's a kind of debug message, but I'm more curious about what might be calling it, so it's probably good that it's there.

I suspect rails does a quick probe of the server to verify it's up? Is there a way to see what was requested (in terms of the address)? That might help trace it down.

**Comment by MSP-Greg** [comment]
@brendon

I'm looking at speeding up the detection, as it's rather slow.

> Is there a way to see what was requested (in terms of the address)

Honestly, that might be a bit tricky.  With TLSv1.3, the request can be read before the handshake completes, but at the time that occurs, one doesn't know it's a bad (http) connection.

What is worse is that determination happens in a different read call, so it would need to be held across those calls.  It is held, but by another object.  We **might** be able to log the info in that object, but it would be adding code for a very specific case...

> I suspect rails does a quick probe

Not sure about that.  I would think that if that was the case, we'd have a lot of people asking why it's logged?  Can you start the app by itself (without Capybara)?

**Comment by brendon** [comment]
I've tried booting it up as so:

```
❯ puma -b "ssl://127.0.0.1:60802?key=test/ssl/test.spikeatschool.test-key.pem&cert=test/ssl/test.spikeatschool.test.pem"

Puma starting in single mode...
* Puma version: 5.2.2 (ruby 2.7.3-p183) ("Fettisdagsbulle")
*  Min threads: 5
*  Max threads: 5
*  Environment: development
*          PID: 14718
* Listening on ssl://127.0.0.1:60802?key=test/ssl/test.spikeatschool.test-key.pem&cert=test/ssl/test.spikeatschool.test.pem
Use Ctrl-C to stop
```

It doesn't initially log anything, but if I hit that server on the `http` protocol it logs the line.

It could even be Capybara doing the initial probe on boot. Seems a bit weird. I'm currently looking to see if there's a configuration option to set the default protocol.

**Comment by MSP-Greg** [comment]
One thing I didn't mention.  In production, a 'normal, good intentioned' user doesn't even know how to make software submit an http/tcp connection on an https/ssl port.   That was part of the reason I thought the logging was ok...

**Comment by brendon** [comment]
Haha! True it is somewhat difficult to end up in that situation.

So far I've had no luck tracing what is making that request. I'll keep tapping away at it.

I guess regarding Puma itself, this can probably be closed as at worst, it's just an unclear message and this issue will clarify things for anyone that encounters it. It's likely Rails or Capybara is sending the probe request. I might try to create an empty Rails app that reproduces the issue as it could even be that my app is somehow doing it.

**Comment by nateberkopec** [comment]
@brendon you might try wireshark

**Comment by brendon** [comment]
With some further digging, it is Capybara that is making the request:

https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/server.rb#L56

I'll see if it can't be changed to be ssl friendly :)

**Comment by nateberkopec** [comment]
Awesome! Puma probably doesn't want to easily silence such a log message, because we _added_ it because people kept getting into scenarios like this but where they actually wanted the request to succeed and they didn't know what was happening.

**Comment by brendon** [comment]
Indeed :) Happy to know its there :) On the Capybara side, they're purposefully rescuing from this type of error, but that's probably not the ideal solution :)

**Comment by camilova** [comment]
As a @MSP-Greg said, normal users don't raise this error, so I use it to ban "bad users" as part of an active security rule.
