### ISSUE TITLE
Utilize systemd-notify to add status details

### ISSUE THREAD

**Issue by dgoetz** [puma/puma#2604]
**Is your feature request related to a problem? Please describe.**
I come from a [discussion](https://community.theforeman.org/t/puma-status-monitoring-not-working-at-the-moment/23154) in the Foreman community where we want to get the status for debugging and scaling the system. In the past the [puma-systemd](https://github.com/sj26/puma-plugin-systemd/blob/master/lib/puma/plugin/systemd.rb) plugin was used and now [puma-status](https://github.com/ylecuyer/puma-status), but having this directly in puma without an additional plugin and configuration would be a great feature for us and our users.

**Describe the solution you'd like**
We primarily need the number and state of the workers like the systemd plugin had, but the resource usage of the status plugin could also be helpful. Just think about would a sysadmin perhaps wants to see and can influence and provide this information if gathering it is doable without cause performance issues.

**Describe alternatives you've considered**
We add the status plugin and describe how to use it at the moment or perhaps add some graphical interface for monitoring it into the Foreman webinterface in the future.

**Additional context**
While the considerations are coming from how we use or plan to use it in the Foreman project, I think also other projects and users can benefit from it.

**Comment by jacobherrington** [comment]
@dgoetz Is this still something you'd find useful? It seems that Foreman [added the status plugin](https://github.com/theforeman/foreman/pull/7735), does that solve the issue for you?

**Comment by Nowaker** [comment]
@jacobherrington What you linked isn't very useful. With support for `Type=notify` already built-in, this request is a natural progression towards more integration with systemd.

**Comment by ekohl** [comment]
This comment reminded me that at some point I did play with it. I've submitted it as #2833 but I don't know if I have time to finish it. Anyone should feel free to take it as a start and complete it.

**Comment by nateberkopec** [comment]
Thanks for sharing where you got to @ekohl !

**Comment by DaviidFr** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> I come from a [discussion](https://community.theforeman.org/t/puma-status-monitoring-not-working-at-the-moment/23154) in the Foreman community where we want to get the status for debugging and scaling the system. In the past the [puma-systemd](https://github.com/sj26/puma-plugin-systemd/blob/master/lib/puma/plugin/systemd.rb) plugin was used and now [puma-status](https://github.com/ylecuyer/puma-status), but having this directly in puma without an additional plugin and configuration would be a great feature for us and our users.
> 
> 
> 
> **Describe the solution you'd like**
> 
> We primarily need the number and state of the workers like the systemd plugin had, but the resource usage of the status plugin could also be helpful. Just think about would a sysadmin perhaps wants to see and can influence and provide this information if gathering it is doable without cause performance issues.
> 
> 
> 
> **Describe alternatives you've considered**
> 
> We add the status plugin and describe how to use it at the moment or perhaps add some graphical interface for monitoring it into the Foreman webinterface in the future.
> 
> 
> 
> **Additional context**
> 
> While the considerations are coming from how we use or plan to use it in the Foreman project, I think also other projects and users can benefit from it.

**Comment by dentarg** [comment]
Anyone here that can take a look at #3006? I'm not using Puma with systemd myself

**Comment by ehelms** [comment]
Looks great from my perspective, if you are happy with it I think it's safe to close it out.

**Comment by ekohl** [comment]
It looks like the worker status gets truncated there, so I wonder if it should somehow be made shorter. On the other hand, that's also something that could be iterated on.

**Comment by dgoetz** [comment]
> It looks like the worker status gets truncated there, so I wonder if it should somehow be made shorter. On the other hand, that's also something that could be iterated on.

Truncation happens from systemd not breaking the line at maximum size of my console instead you can scroll sideways, so all information is present even if you do not see it on the first look.

**Comment by nateberkopec** [comment]
Closing out for now, please open new issues if you'd like something added on.
