### ISSUE TITLE
Getting too many 502 with AWS ECS and ELB

### ISSUE THREAD

**Issue by siddhant-mohan** [puma/puma#2608]
**Describe the bug**
I am getting a lot of 502, and after 502 somehow, container gets restarted. I am using ecs with AWS elb and ACM for ssl certification. I am also running rails server directly on 8080 instead of running it on 3000 and then using nginx to bind 80 port to 3000, will that effect the performance in terms of 502?
**Puma config:**

max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 10 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count
worker_timeout 60

port ENV.fetch("PORT") { 3000 }

environment ENV.fetch("RAILS_ENV") { "development" }

pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

plugin :tmp_restart

**To Reproduce**

Run it with (app_server.sh):

```
bundle exec rake db:migrate db:seed
echo "database has been migrated!"

# Remove a potentially pre-existing server.pid for Rails.
rm -f tmp/pids/server.pid

# Run the Rails server
bundle exec rails server -b 0.0.0.0 -p 8080
```

**Expected behavior**

**Desktop (please complete the following information):**
 - AWS EC2 Linux - container size CPU - 2048, memory 2048 
 - Puma Version - 5.2.2

**Comment by nateberkopec** [comment]
Can you post the logs from your load balancer and from Puma at the time when the 502 occurs?

**Comment by calvinxiao** [comment]
> I am also running rails server directly on 8080 instead of running it on 3000 and then using nginx to bind 80 port to 3000

Looks like your nginx should `proxy_pass` to port 3000.
