### ISSUE TITLE
Keepalive connections which exceed request limit closed in a less-than-clean manner with 5.3.1

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2627]
Observable with wrk/your favorite benchmarking tool.

**Comment by justin808** [comment]
@nateberkopec any risk of this affecting normal production deployments? Or just benchmarking. We've been load-testing popmenu.com's infrastructure and we noticed a big reduction in the max load before we hit many errors.

**Comment by nateberkopec** [comment]
I don't think there's much risk. It only affects connections which send more than 10 keepalive requests. We're gonna release a patch fixing this in a day or two.
