### ISSUE TITLE
Allow configuration of on_booted event hooks

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2635]
Originally requested in #1230 

Similar to `after_worker_boot`, but for the `on_booted` event.

**Comment by will-in-wi** [comment]
Hey! I wanted to add my use case to this ticket. I'm trying to get some prometheus instrumentation set up (using the discourse plugin), but it uses the stats object. I'm struggling to find a reasonable place to initialize this where I know that `Puma.stats` is available. I've tried a Rails initializer and a Puma plugin, but the only thing that seems to work is:

```ruby
require "prometheus_exporter/instrumentation"

Puma::Plugin.create do
  def start(_launcher)
    in_background do
      loop do
        # So ugly... We really just need to loop until Puma.stats is initialized. This is happening in another thread, and I can't seem to find a better way.
        sleep(1)
        Puma.stats
        break
      rescue NoMethodError
        # Let the loop retry
      end

      # Defaults to sampling every 30 seconds.
      PrometheusExporter::Instrumentation::Puma.start
    end
  end
end
```

Having some kind of hook where I could initialize them would be excellent! I'm threaded, so the after_worker_boot hook doesn't work.

I'm happy to take a whack at this if someone can point me to where things are set up.

**Comment by x-yuri** [comment]
My use case. Right now the app connects to db on boot. And in clustered mode it disconnects in master, then connects in workers. Which seems pointless (to connect only to disconnect soon). I wanted to make it connect to db in the only process in single mode, and in workers in clustered mode. But... right now it seems impossible.
