### ISSUE TITLE
[Install problem] nio is installed but puma complains

### ISSUE THREAD

**Issue by rubyFeedback** [puma/puma#2636]
I just got the following error:

    /root/.gem/gems/puma-5.3.2/lib/puma/reactor.rb:28:in `initialize': uninitialized constant Puma::Reactor::NIO (NameError)
    Did you mean?  Nio

I may have installed puma incorrectly, however had I run this here:

    Successfully installed nio-0.2.5
    option --opname is deprecated: support discontinued
    Parsing documentation for nio-0.2.5
    Done installing documentation for nio after 0 seconds
    1 gem installed

And it works. Should the puma-related error thus not disappear too?

Perhaps the message could be a bit improved, e. g. notify the user
that something else is missing. I will probably setup my ruby completely
and I know this error will go away (it did not happen a month ago, so
it is most likely ALSO attributable to a user error), but right now I am
a bit clueless as to how such an error can show up if nio has been
installed.

**Comment by nateberkopec** [comment]
The `nio` gem is not what Puma uses - we use `nio4r`. 

I'm still trying to figure out how you could've gotten this error, as `gem install puma` should also install `nio4r`...

**Comment by nateberkopec** [comment]
@rubyFeedback let me know if installing `nio4r` does not fix your issue.

**Comment by AustinRhoads** [comment]
I get the following error when generate a rails api

``An error occurred while installing puma (5.3.2), and Bundler cannot
continue.
Make sure that `gem install puma -v '5.3.2' --source 'https://rubygems.org/'`
succeeds before bundling.``

**Comment by jozefvaclavik** [comment]
I have similar issue where I have a class called `Nio` but puma complains about unitialized constant during boot.

```
rails  | /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:564:in `load_missing_constant': Unable to autoload constant NIO, expected /workspaces/desertcart/app/models/currency/nio.rb to define it (LoadError)
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:213:in `const_missing'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/puma-6.4.2/lib/puma/reactor.rb:23:in `initialize'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/puma-6.4.2/lib/puma/server.rb:248:in `new'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/puma-6.4.2/lib/puma/server.rb:248:in `run'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/puma-6.4.2/lib/puma/single.rb:53:in `run'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/puma-6.4.2/lib/puma/launcher.rb:194:in `run'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/puma-6.4.2/lib/rack/handler/puma.rb:76:in `run'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.9/lib/rack/server.rb:327:in `start'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.0/lib/rails/commands/server/server_command.rb:39:in `start'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.0/lib/rails/commands/server/server_command.rb:144:in `block in perform'
rails  |        from <internal:kernel>:90:in `tap'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.0/lib/rails/commands/server/server_command.rb:135:in `perform'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.0/lib/rails/command/base.rb:69:in `perform'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.0/lib/rails/command.rb:50:in `invoke'
rails  |        from /root/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<top (required)>'
rails  |        from bin/rails:4:in `require'
rails  |        from bin/rails:4:in `<main>'
rails  | Exited
```

**Comment by jozefvaclavik** [comment]
Had to rename my class to get it running, but whats the point of namespacing then?

**Comment by dentarg** [comment]
Bug in Rails? (active support) Ruby? (autoload) 

Looks like a faulty assumption that the file with class `Nio` should load `NIO`. Try their bug tracker if you have an example that reproduces the problem.

Strange that `NIO` wasn't there, should be a runtime dependency of Puma. How are you starting your app?
