### ISSUE TITLE
Introduction of `Puma::JSON` in 5.1.0 is "breaking" in some cases

### ISSUE THREAD

**Issue by walro** [puma/puma#2639]
**Describe the bug**

In #2479, a new class `Puma::JSON` was introduced (later on shipped with 5.1.0). It has an innocent breaking change when it comes to the `JSON` constant lookup.

**Puma config:**
```ruby
require "json"

workers 2

before_fork do
  JSON.dump({}) # or any method not implementation on `Puma::JSON`
end
```

**To Reproduce**

Output from `bundle exec puma -C puma.rb hello.ru` using Puma >= 5.1.0, note the `WARNING`:

```
[37721] Puma starting in cluster mode...
[37721] * Puma version: 5.1.0 (ruby 3.0.1-p64) ("At Your Service")
[37721] *  Min threads: 0
[37721] *  Max threads: 5
[37721] *  Environment: development
[37721] *   Master PID: 37721
[37721] *      Workers: 2
[37721] *     Restarts: (✔) hot (✔) phased
[37721] * Listening on http://0.0.0.0:9292
[37721] Use Ctrl-C to stop
[37721] WARNING hook before_fork failed with exception (NoMethodError) undefined method `dump' for Puma::JSON:Module
Did you mean?  dup
[37721] - Worker 0 (PID: 37722) booted, phase: 0
[37721] - Worker 1 (PID: 37723) booted, phase: 0
```

The problem is the same for any "`Puma::DSL` hook", in our case we actually ran into this for the `lowlevel_error_handler` hook.

**Expected behavior**

While it's easy to fix the problem by simply changing to top-level lookup in the client-code (`::JSON`) it was a bit confusing at first. Ideally, it would be cool if clients do not need to change their implementations, but I understand that probably means the class has to be renamed or moved. Maybe a note in the release notes could be good though?

**Desktop (please complete the following information):**

 - OS: macOS 10.15.7
 - Puma Version: >= 5.1.0

**Comment by nateberkopec** [comment]
Fair enough. We could rename it to something more esoteric like `JSONSerialization`, it's an internal class that can be renamed as often as we like.

**Comment by cjlarose** [comment]
Renaming makes sense. We can't really change the module in which `config/puma.rb` is evaluated easily since it has to be executed within the `Puma::DSL` context. Doing something more fancy like delegating methods and constant lookups would probably not be easy and might introduce some weird bugs.

`JSONSerialization` is probably a better name anyway, since the module handles only JSON encoding and not JSON decoding. 👍

**Comment by walro** [comment]
Submitted #2640, let me know if I need to change something :)
