### ISSUE TITLE
[Documentation] Comparing puma, webrick and alternatives

### ISSUE THREAD

**Issue by rubyFeedback** [puma/puma#2644]
Hey folks,

Would it be possible to add a short subsection OR a short document, either to the main README,
or a linked in component of the documentation being referred to by the README, or an entry to
the wiki here at github (and linked in to from the main README), explaining a few key points
DIFFERENCES between puma, webrick and any alternatives?

Background: I am currently using sinatra + webrick. This works very well and one advantage is
that it is super-simple. I am contemplating using puma, but the requirement is that it must
work both on windows and linux. Are there advantages for puma, as opposed to, say, webrick,
or any other servers? This is what I am most interested in.

This is an internal site really, but may be used by some family members, and it may also 
have to serve some content at a later time (e. g. in-house streaming of audio/video data).

I am mostly interested in something I can read through; one or two paragraphs should
suffice, so it really does not have to be overly long. Just a primer but ideally written by
someone who actually knows at the least a few differences. I am an experienced 
ruby user, with a little bit of experience with webrick and sinatra, but other than that,
I am actually not a true "www expert". I am reading a +1000 pages javascript book
right now, for example, and can finish perhaps ~5 pages a day or so, so new info
is slow - any more useful info in general is highly appreciated. Thanks for reading!

**Comment by johnnyshields** [comment]
It's very simple: Webrick is a single-server, single-process bare bones server. You can think of it as a sort of "demo" of the basic features that a Ruby server can do, so it comes with a basic HTTP implementation, HTTPS support, CGI script support, etc.

Puma can do everything Webrick can HTTP-wise, but its main claim to fame is multi-process (copy-on-write forking) and multi-threading. These features allow you to serve as many requests as possible and efficiently use your CPU, memory, etc. resources in a production environment.

If you are using the two servers in your local environment (Puma in single process / single threaded mode), you won't see a whole lot of difference.

**Comment by nateberkopec** [comment]
I would be OK with adding this.

If you were going to compare/contrast all the differences between [the popular ruby application servers](https://www.ruby-toolbox.com/categories/web_servers) I would probably say important features to compare would be:

1. Process-based, thread-based, fiber-based concurrency
2. Native language extensions required?
3. SSL
4. Probably a comparison of restart-related features
5. What else?

**Comment by sreeram-venkitesh** [comment]
@nateberkopec Is this issue still up for grabs? If so I'm interested in working on it. Would love to research and compare puma alternatives and contribute to the docs in the process.

**Comment by nateberkopec** [comment]
All issues are always open 👍

**Comment by sreeram-venkitesh** [comment]
Awesome, can I assign this to myself?

**Comment by nateberkopec** [comment]
I decided to not directly compare with other servers, but instead to enumerate in the very first paragraph of the readme what I think makes Puma unique. 

I don't want to be maintaining a list of what _other_ webservers can do, and I think it engenders competition in a way that I absolutely hate in OSS. We're not in competition with other webservers, we're all just sharing code that we use every day.
