### ISSUE TITLE
Thread pool deadlock

### ISSUE THREAD

**Issue by ob-stripe** [puma/puma#2655]
**Describe the bug**
The Puma worker thread pool can enter a deadlock state and become unable to process new requests.

**Puma config:**

In our case, the issue only happens on the control server worker and not the main server worker, so I assume most of the config is irrelevant since the configuration for the control server is mostly hardcoded. We have tried using both Unix sockets and TCP sockets for the control server and have observed the issue in both cases.

**To Reproduce**
Unfortunately I have not yet been able to produce a minimal example to reproduce the issue. The best I can do for now is describe our setup. (I will update this post if I can come up with a reliable way to reproduce the issue.)

(EDIT: I have been able to reproduce the issue with a minimal Puma setup, cf. https://github.com/puma/puma/issues/2655#issuecomment-872524754)

The deadlock issue only happens in the worker for the Puma control server, not the main server. We have a monitoring script that sends a `/stats` request to the Puma control server every 2 seconds. We use the response to aggregate statistics to monitor the overall availability of our services across multiple hosts.

The client side timeout is fairly short (0.5 seconds). Occasionally a request will time out (presumably because the Puma Ruby process is busy doing GC or something else and does not yield to the control server thread in time). That's not an issue, since the next request will likely succeed. However, sometimes the control server will become completely stuck and unable to process any further requests, which causes us to report the worker as unavailable (despite the fact that the main server thread is still running fine).

Using gdb to attach to a Puma process in this deadlock state, we were able to determine that the control server thread is stuck on this line: https://github.com/puma/puma/blob/v5.3.1/lib/puma/thread_pool.rb#L236.

As far as we can tell, the thread pool for the Puma control server is empty at that time. So it looks like what happens is that, once the bug is triggered, the next incoming request will call [`pool.wait_until_not_full`](https://github.com/puma/puma/blob/v5.3.1/lib/puma/server.rb#L334) and wait forever for a thread to become available, but the only way for a thread to become available would be to call `spawn_thread` which happens _after_ the call to `pool.wait_until_not_full`.

**Expected behavior**
The thread pool should never deadlock.

**Desktop (please complete the following information):**
 - OS: Linux (uname: `Linux <hostname> 5.8.0-1038-aws #40~20.04.1-Ubuntu SMP Thu Jun 17 13:25:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`)
 - Puma Version: 5.3.1

**Additional notes:**
I realize that without clear steps to reproduce, there might not be much you can do here. However I would appreciate any insights you can offer. I can also instrument the Puma code as needed.

**Comment by cjlarose** [comment]
I think the control/status server is given its own thread pool that's configured to have a maximum of 1 thread.

https://github.com/puma/puma/blob/8264d20caeb73d65564c5def9267fecfc9473c16/lib/puma/runner.rb#L57-L58

So basically the status server is capable of servicing at most one request concurrently. If the single worker thread gets stuck doing something, it would make sense that the server would not be able to handle any new requests.

But you did mentioned that

> As far as we can tell, the thread pool for the Puma control server is empty at that time.

If that's true, that's really interesting because it would mean that the single worker thread was terminated, but left the `Puma::Server` in such a state that it's stuck indefinitely. If I'm reading `ThreadPool#wait_until_not_full` correctly, that'd mean that `busy_threads >= @max` (meaning the server thinks it's running at capacity), but no thread is able to signal the `@not_full` condition variable.

Like you mentioned, it's hard to dig any further without a good reproducible example. But you mentioned that you're able to instrument the server. If that's the case, it'd be nice to know what `busy_threads` is returning when this happens and why (what are the values of `@spawned`, `@waiting` and `@todo.size` when `busy_threads` is computed).

Thanks for the detailed bug report!

**Comment by ob-stripe** [comment]
> If that's true, that's really interesting because it would mean that the single worker thread was terminated, but left the Puma::Server in such a state that it's stuck indefinitely. 

Yes, I think that's exactly what's happening. I'm not sure what causes the single worker thread to die. I thought it might be an unhandled exception, but couldn't find anything in the logs confirming that. (I've also checked that we do have `Thread.abort_on_exception` set to `true`). It could be that the thread was terminated by either the trimming or the reaping threads. I will instrument the code further to try and confirm if that's the case.

>  If that's the case, it'd be nice to know what `busy_threads` is returning when this happens and why (what are the values of `@spawned`, `@waiting` and `@todo.size` when busy_threads is computed).

Here are the last logs I got from a process as the bug was triggered:

```
[2021-07-01 16:45:45.678890] !!! busy_threads pid=4080073 @spawned=1 @waiting=1 @todo.size=0 busy_threads=0
[2021-07-01 16:45:46.249938] !!! busy_threads pid=4080073 @spawned=1 @waiting=1 @todo.size=0 busy_threads=0
[2021-07-01 16:45:46.250509] !!! busy_threads pid=4080073 @spawned=1 @waiting=0 @todo.size=0 busy_threads=1
[2021-07-01 16:45:48.543309] !!! requested trim pid=4080073 @trim_requested=1
[2021-07-01 16:45:48.544559] !!! busy_threads pid=4080073 @spawned=1 @waiting=1 @todo.size=0 busy_threads=0
[2021-07-01 16:45:48.545161] !!! busy_threads pid=4080073 @spawned=1 @waiting=0 @todo.size=0 busy_threads=1
```

I suspect some sort of race condition caused by the thread trimmer. I will instrument further.

**Comment by ob-stripe** [comment]
Okay, I am now fairly sure this is an issue with the thread trimmer. Here's another log trace:
```
[2021-07-01 17:55:09.468032] !!! requested trim pid=114154 @trim_requested=1
[2021-07-01 17:55:09.469370] !!! busy_threads pid=114154 @spawned=1 @waiting=1 @todo.size=0 busy_threads=0
[2021-07-01 17:55:09.469829] !!! busy_threads pid=114154 @spawned=1 @waiting=0 @todo.size=0 busy_threads=1
[2021-07-01 17:55:09.469934] !!! thread was trimmed pid=114154 @spawned=0 @trim_requested=0
```

I've changed the default period for the tread trimmer from 30 seconds to 5 seconds and can reproduce the issue faster on our servers. I will try and see if I can use that to get a minimal project that reproduces the issue.

**Comment by ob-stripe** [comment]
I have created a sample project at https://github.com/ob-stripe/puma_2655 that can reproduce the issue. On my laptop (MacBook Pro 2017), the issue happens within 2/3 minutes of starting the `control_client.rb` script that hammers the server with requests.

**Comment by ob-stripe** [comment]
Alright, after instrumenting the code all over the place, here's how I think the deadlock happens:

1. Thread `puma control threadpool 001` is processing a request.
2. Thread `puma control threadpool trimmer` requests a trimming.
3. Thread `puma control` accepts a new connection and enters `pool.wait_until_not_full`. Since thread `puma control threadpool 001` is busy, thread `puma control` waits for `not_full` to be signaled.
4. Thread `puma control threadpool 001` finishes processing the request, then terminates itself since a trimming is requested.

At this point thread `puma control` is deadlocked: `not_full` will never be signaled.

The fix should be as simple as calling `not_full.signal` immediately before `Thread.exit` ([here](https://github.com/puma/puma/blob/1c91a4f1af23328118dbfe5b615f812af5e817ef/lib/puma/thread_pool.rb#L122)). This will wake up thread `puma control` which will then add the client to the thread pool queue and spawn a new thread in the thread pool.

I will submit a PR tomorrow. I'll see if it's possible to write a test for this, but I'm not holding out hope -- race conditions are rarely testable without heavy instrumentation.

**Comment by cjlarose** [comment]
This is awesome! Thanks for all the detailed information. Looking forward to that PR!

**Comment by nateberkopec** [comment]
> I will submit a PR tomorrow.

Leaves a bunch of detailed notes, reproduces their own issue and puts the repro online, and now fixes it themselves too? Dream bug report! 😍
