### ISSUE TITLE
getting error message 

### ISSUE THREAD

**Issue by AlienSky** [puma/puma#2658]
We are not able to build our application we are getting error message ! Unable to load application: URI::InvalidURIError: bad URI(is not URI?): :
**Puma config:**
in deploy.rb

set :puma_roles, :app
set :puma_socket, "unix://#{fetch(:sockets_path).join('puma_' + fetch(:application) + '.sock')}"
set :pumactl_socket, "unix://#{fetch(:sockets_path).join('pumactl_' + fetch(:application) + '.sock')}"
set :puma_state, fetch(:sockets_path).join('puma.state')
set :puma_log, -> { shared_path.join("log/puma-#{fetch(:stage )}.log") }
set :puma_flags, nil

set :bundle_flags, '--deployment'

set :puma_state, fetch(:sockets_path).join('puma.state')
set :puma_log, -> { shared_path.join("log/puma-#{fetch(:stage )}.log") }
set :puma_flags, nil

/tmp/sockets/puma.state restart
 DEBUG [c6ad4f8e] 	Puma starting in single mode...
 DEBUG [c6ad4f8e] 	
 DEBUG [c6ad4f8e] 	* Version 3.7.1 (ruby 2.3.7-p456), codename: Snowy Sagebrush
 DEBUG [c6ad4f8e] 	
 DEBUG [c6ad4f8e] 	* Min threads: 0, max threads: 16
 DEBUG [c6ad4f8e] 	
 DEBUG [c6ad4f8e] 	* Environment: development
 DEBUG [c6ad4f8e] 	
 DEBUG [c6ad4f8e] 	! Unable to load application: URI::InvalidURIError: bad URI(is not URI?): :
 DEBUG [c6ad4f8e] 	
 DEBUG [c6ad4f8e] 	bad URI(is not URI?): :

**Comment by nateberkopec** [comment]
Not enough information, but I think this is probably an issue with your configuration rather than an issue with puma.

Can you post the entire error message? Knowing what line number raises `URI::InvalidURIError` would help.

**Comment by AlienSky** [comment]
deploy@qa:/var/www/plantsmap/current/tmp/sockets$ puma -e qa_internal -bind /var           /www/plantsmap/current/tmp/sockets/puma_plantsmap.sock
Puma starting in single mode...
* Puma version: 5.3.2 (ruby 2.3.7-p456) ("Sweetnighter")
*  Min threads: 0
*  Max threads: 5
*  Environment: qa_internal
*          PID: 96589
! Unable to load application: LoadError: cannot load such file -- /var/www/plant           smap/current/tmp/sockets/puma_plantsmap.sock
/home/deploy/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/k           ernel_require.rb:54:in `require': cannot load such file -- /var/www/plantsmap/cu           rrent/tmp/sockets/puma_plantsmap.sock (LoadError)
        from /home/deploy/.rvm/rubies/ruby-2.3.7/lib/ruby/site_ruby/2.3.0/rubyge           ms/core_ext/kernel_require.rb:54:in `require'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/lib/puma/rack/bui           lder.rb:165:in `parse_file'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/lib/puma/configur           ation.rb:345:in `load_rackup'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/lib/puma/configur           ation.rb:267:in `app'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/lib/puma/runner.r           b:143:in `load_and_bind'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/lib/puma/single.r           b:44:in `run'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/lib/puma/launcher           .rb:181:in `run'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/lib/puma/cli.rb:8           0:in `run'
        from /home/deploy/.rvm/gems/ruby-2.3.7/gems/puma-5.3.2/bin/puma:10:in `<           top (required)>'
        from /home/deploy/.rvm/gems/ruby-2.3.7/bin/puma:23:in `load'
        from /home/deploy/.rvm/gems/ruby-2.3.7/bin/puma:23:in `<main>'
        from /home/deploy/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `           eval'
        from /home/deploy/.rvm/gems/ruby-2.3.7/bin/ruby_executable_hooks:24:in `           <main>'

**Comment by MSP-Greg** [comment]
@AlienSky

Just a quick look:
```
deploy@qa:/var/www/plantsmap/current/tmp/sockets$ puma -e qa_internal -bind /var/www/plantsmap/current/tmp/sockets/puma_plantsmap.sock
```

Try (either `-b` or `--bind`):
```
deploy@qa:/var/www/plantsmap/current/tmp/sockets$ puma -e qa_internal --bind unix:///var/www/plantsmap/current/tmp/sockets/puma_plantsmap.sock
```

**Comment by AlienSky** [comment]
@MSP-Greg thank you for advise command --bind unix:///var/www/plantsmap/current/tmp/sockets/puma_plantsmap.sock worked though our deploy script still give us error on this command. set :pumactl_socket, "unix://#{fetch(:sockets_path).join('pumactl_' + fetch(:application) + '.sock')}"

**Comment by AlienSky** [comment]
@MSP-Greg Thank you, we enable trace for puma process which seem to hung and here output.
[pid 22409] select(11, [9 10], NULL, NULL, NULL <unfinished ...>
[pid 22408] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid 22407] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid 22406] select(13, [12], NULL, NULL, {26, 878478} <unfinished ...>
[pid 22394] restart_syscall(<... resuming interrupted call ...> <unfinished ...>
[pid 22393] futex(0x237569c, FUTEX_WAIT_PRIVATE, 11, NULL <unfinished ...>
[pid 22407] <... restart_syscall resumed> ) = -1 ETIMEDOUT (Connection timed out)
[pid 22407] futex(0xb9a0d40, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989259, 49757308}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989259, 49874917}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989259, 49951823}) = 0
[pid 22407] futex(0xb9a0ccc, FUTEX_WAIT_BITSET_PRIVATE, 520525, {989260, 49951823}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid 22407] futex(0xb9a0d40, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989260, 50320635}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989260, 50434644}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989260, 50509550}) = 0
[pid 22407] futex(0xb9a0ccc, FUTEX_WAIT_BITSET_PRIVATE, 520527, {989261, 50509550}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid 22407] futex(0xb9a0d40, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989261, 50826859}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989261, 50923266}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989261, 50981971}) = 0
[pid 22407] futex(0xb9a0ccc, FUTEX_WAIT_BITSET_PRIVATE, 520529, {989262, 50981971}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid 22407] futex(0xb9a0d40, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989262, 51266877}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989262, 51390587}) = 0
[pid 22407] clock_gettime(CLOCK_MONOTONIC, {989262, 51453391}) = 0
[pid 22407] futex(0xb9a0ccc, FUTEX_WAIT_BITSET_PRIVATE, 520531, {989263, 51453391}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
[pid 22407] futex(0xb9a0d40, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 22407] cloc

**Comment by AlienSky** [comment]
@MSP-Greg thank you for advise I'll try to add lines.

**Comment by nateberkopec** [comment]
Closing as stale, please comment if you need additional assistance.
