### ISSUE TITLE
Memory leaks reported and fixed by setting min threads equal to max threads

### ISSUE THREAD

**Issue by ehelms** [puma/puma#2665]
**Describe the bug**
Users report memory leaks when the minimum threads are set to 0. The [Foreman project](https://github.com/theforeman/foreman) deploys a larger Rails application using Puma over Unix socket behind an Apache reverse proxy. Users of a downstream version of Foreman, Red Hat Satellite, have been reporting memory leaks that they claim are resolved if the number of minimum threads is set to the number of maximum threads. For reference, the bug report is https://bugzilla.redhat.com/show_bug.cgi?id=1976051

This issue is seen on Puma 4.3. We are not clear at this time if the same issue persists on newer versions using Puma 5.3+

We'd like to have some insight into:

 * why we might be seeing this behavior
 * why setting min and max threads equal appears to be solving the problem
 * Are there any side effects to setting min threads to max threads we should be mindful of
 * Is there anything in 5+ that alleviates this concern?
 * Is this a Puma specific issue or an indicator of something within our own application?

Thank you for any details that can be provided. 

**Puma config:**

We deploy Puma via systemd over a Unix socket.

```
run_dir = Rails.root.join('tmp')

# Store server info state.
state_path File.join(run_dir, 'puma.state')
state_permission 0o0640

# Configure "min" to be the minimum number of threads to use to answer
# requests and "max" the maximum.
#
# The default is "0, 16".
#
threads ENV.fetch('FOREMAN_PUMA_THREADS_MIN', 0).to_i, ENV.fetch('FOREMAN_PUMA_THREADS_MAX', 16).to_i

# === Cluster mode ===

# How many worker processes to run.
#
# The default is "0" for puma. Recommending "2" for foreman
#
workers ENV.fetch('FOREMAN_PUMA_WORKERS', 2).to_i

# In clustered mode, Puma can "preload" your application. This loads all the
# application code prior to forking. Preloading reduces total memory usage of
# your application via an operating system feature called copy-on-write
#
preload_app!

# When systemd socket activation is detected, only use those sockets. This
# makes FOREMAN_BIND redundant. The code is still there for non-systemd
# deployments.
bind_to_activated_sockets 'only'

# Check if FOREMAN_BIND was set to an IP address based on the previous
# definition of FOREMAN_BIND. If it is an IP address, define the host
# and port through Puma's DSL. Otherwise rescue and assume the new
# style of a fully specified bind in the formats of:
#
#  * unix:///run/foreman.sock
#  * tcp://127.0.0.1:3000
#
begin
  IPAddr.new(ENV['FOREMAN_BIND'])

  port ENV.fetch('FOREMAN_PORT', '3000'), ENV['FOREMAN_BIND']
rescue IPAddr::Error
  bind ENV.fetch('FOREMAN_BIND', 'tcp://127.0.0.1:3000')
end

on_worker_boot do
  dynflow = ::Rails.application.dynflow
  dynflow.initialize! unless dynflow.config.lazy_initialization
end

# === Puma control rack application ===
activate_control_app "unix://#{run_dir}/sockets/pumactl.sock"

# Loading and initializing of all gettext languages takes about 100ms per language
# in development environment and little less on production. Let's eager load languages
# for production before forking to save memory on CoW operating systems.
before_fork do
  FastGettext.human_available_locales
end
```

**Comment by dentarg** [comment]
>why setting min and max threads equal appears to be solving the problem

Because you are allocating the memory needed for your application upfront 

Read more about how Puma works in the README:

* https://github.com/puma/puma/blob/a99331d32e762c1b9823ab44bed92d622a65b6d3/README.md#thread-pool
* https://github.com/puma/puma/blob/a99331d32e762c1b9823ab44bed92d622a65b6d3/README.md#clustered-mode

See also these comments about Puma and memory leaks in general: https://github.com/puma/puma/issues/2179#issuecomment-598254022, https://github.com/puma/puma/issues/1600#issuecomment-468291010

**Comment by ehelms** [comment]
> > why setting min and max threads equal appears to be solving the problem
> 
> Because you are allocating the memory needed for your application upfront
> 

Thanks for the reply @dentarg. I'm feeling a bit dumb here if you have any more insight. I'm struggling to understand why setting threads to 0:16 leads to a memory leak while setting it to 16:16 appears to not to. Is this a mechanic of how min-max handling works with Puma and something in our application that 16:16 happens to prevent from happening?

**Comment by dentarg** [comment]
Is there a memory leak? Not sure a single snapshot from `top` is evidence of that. I just suggested that the growing memory you are seeing might be that you started with few threads and as time moved on more threads have been spawned, make Puma use more memory.

**Comment by nateberkopec** [comment]
Is there any publicly accessible discussion about how setting it to 16 threads upfront alleviates the issue? The bug report doesn't mention that.

How many Puma workers was the person running in the `top` output posted? The screenshot makes it look like 1? 118gb of memory is definitely a sign of something being wrong and not normal...

**Comment by nateberkopec** [comment]
Closing as this seems like a leak in the app rather than Puma.
