### ISSUE TITLE
Queue_requests is short circuited by client.eagerly_finish

### ISSUE THREAD

**Issue by brphelps** [puma/puma#2667]
**Describe the bug**
I'm seeing behavior that _seems_ bug-like -- The backlog isn't filling up when requests are "waiting" to be processed with queue_requests being enabled. With a simple rails app with a controller method that is sleep 100'ing, you can exhaust the workers and not see any indication that the request is queued. 

From looking at the code, it appears that client.eagerly_finish will skip Reactor processing, which inherently skips backlog reporting. So, if I have a bunch of queued small requests (tested with cUrl GETs) I don't fill up the backlog at all even though queuing is happening, but if I have a bunch of queued large requests (tested with 25MB JSON files) I start seeing the backlog fill up.

This seems really confusing: is backlog really just "backlog_for_uneagerly_loaded_requests"? How can I see the backlog of all requests?

**Puma config:**

```
require 'active_support'

pod_type = ENV["DG_POD_TYPE"]&.downcase
threads_count = ENV.fetch("RAILS_MAX_THREADS") {
  pod_type && pod_type == "api" ? 10 : 5
}.to_i
threads threads_count, threads_count

# threads above ends up being 5 in my local runs

puma_bind = (ENV.fetch("PUMA_BIND") { "tcp://0.0.0.0:9596" }) + "?backlog=5"
bind puma_bind

environment ENV.fetch("RAILS_ENV") { "development" }

app_dir = File.expand_path("../..", __FILE__)

unless get(:environment) == "development"
  pidfile "#{app_dir}/tmp/pids/puma.pid"
end

Thread.new do
  while(true) do
    sleep(10)
    printf Puma.stats
  end
end
```

**To Reproduce**
https://github.com/brphelps/puma-queue-repro

**Expected behavior**
Backlog fills up because queuing is enabled, or at least SOME statistic shows that we are queuing requests.

**Desktop (please complete the following information):**
 - OS: Mac
 - Puma Version ~5.3

**Comment by gugaiz** [comment]
I think I am having a similar issue on puma 4.3.8, I was doing benchmark to compare it with passenger and I got the following results

Puma 4.3.8 output
```bash
$ ./wrk -t12 -c400 -d30s "https://puma_server_url"
Running 30s test @ https://puma_server_url
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    12.08ms   17.99ms   1.85s    98.61%
    Req/Sec     1.02k   401.21     3.46k    73.89%
  356680 requests in 30.09s, 136.43MB read
  Socket errors: connect 0, read 0, write 0, timeout 1198
  Non-2xx or 3xx responses: 355475
Requests/sec:  11853.39
Transfer/sec:      4.53MB
```
Passenger output (free version)
```bash
$ ./wrk -t12 -c400 -d30s "https://passenger_server_url"
Running 30s test @ https://passenger_server_url
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.15s   532.16ms   1.99s    61.29%
    Req/Sec    20.26     20.83   100.00     85.09%
  2098 requests in 30.08s, 52.37MB read
  Socket errors: connect 0, read 0, write 0, timeout 1974
Requests/sec:     69.75
Transfer/sec:      1.74MB
```
As you can see, puma is generating 11853.39 req/sec, while passenger is only 69, but puma has `Non-2xx or 3xx responses: 355475` while passenger, didn't have any non-2xx or 3xx responses. When looking the logs I saw many 502 errors on the puma server.
I tried with `?backlog=1024` but didn't make any difference, also tried turning on/off `queue_requests` without changes in the results. I guess it is a good idea to refuse connection when the queue is filled, but in this case, didn't fill it at all and it is refusing all requests as soon as the threads are filled (`threads 8, 11`)
I also monitored the requests using [puma-status](https://github.com/ylecuyer/puma-status) and I only saw the queue go at the max of 2, but that is not going anywhere close to 1024 as set on the config.

```
13573 (/var/run/puma/puma.state) Uptime:  0m38s | Phase: 0 | Load: 39[███████████████████████████████████████░░░░░]44
 └ 13579 CPU:  65.9% Mem:  215 MB Uptime:  0m38s | Load: 10[██████████░]11 Queue: 1
 └ 13581 CPU:  63.9% Mem:  219 MB Uptime:  0m38s | Load: 9[█████████░░]11 Queue: 2
 └ 13583 CPU:  71.9% Mem:  215 MB Uptime:  0m38s | Load: 10[██████████░]11
 └ 13584 CPU:     0% Mem:    0 MB Uptime:  0m38s killed
 ```

**Comment by dentarg** [comment]
@gugaiz did you do the wrk tests directly against puma and passenger or did you have nginx in front of them? Do you mind doing the same test against Puma 3.12.6?

**Comment by nateberkopec** [comment]
@gugaiz A lot of things have been fixed in 5.3.2 that would solve that issue for you, I would recommend upgrading.

**Comment by nateberkopec** [comment]
> Backlog fills up because queuing is enabled, or at least SOME statistic shows that we are queuing requests.

The `backlog` in Puma.stats is the backlog of the threadpool, not the reactor. The Reactor is what queues and buffers requests, not the threadpool. The number of connections waiting to be buffered by the Reactor is not accessible via Puma.stats (yet). See [architecture.md](https://github.com/puma/puma/blob/master/docs/architecture.md).

When you turn `queue_requests` off you turn off the reactor, which means that requests are passed directly to the threadpool, increasing `backlog`.

**Comment by gugaiz** [comment]
I will try testing with both, version `5.3.2` and if does not work I will try going back to version `3.12.6`. It is a bit tricky because I am using AWS Elastic Beanstalk and there is not much freedom with regards to moving between different puma versions.

I will post the results here.

@dentarg I am hitting the Nginx server that is in front of puma/passenger.

**Comment by gugaiz** [comment]
Hey @nateberkopec, I tried with puma 5.3.2 and the result was pretty similar

```bash
ubuntu@ip-10-2-12-168:~/wrk$ ./wrk -t12 -c400 -d30s "https://puma_5.3.2_server_url"
Running 30s test @ https://puma_5.3.2_server_url
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    34.47ms    7.30ms 271.96ms   92.35%
    Req/Sec     0.96k   161.09     2.53k    89.37%
  338601 requests in 30.10s, 126.91MB read
  Non-2xx or 3xx responses: 338601
Requests/sec:  11249.81
Transfer/sec:      4.22MB
```

Is there a way to increase the "queue size" at the Reactor level? Do you think this will make a difference? Is there anything else I can try?

Didn't have the chance to test with an older version, anyway I would like to upgrade rather than downgrade.

**Comment by MSP-Greg** [comment]
@gugaiz

What are the Puma worker and thread settings?

**Comment by gugaiz** [comment]
I tried different settings, but all these tests I posted previously were done with

```
threads 8, 32
workers %x(grep -c processor /proc/cpuinfo) # --> 4
```
The only way I can get puma to reject fewer packages is to increase workers to 20 (or more) and keep 32 threads, doing so I can get results similar to the one below, but I don't think I can leave those settings for production because it will consume all server's memory very easily.

```
Running 30s test @ https://puma_server_url
  8 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.76s   332.98ms   2.00s   100.00%
    Req/Sec     9.10      7.81    80.00     78.32%
  1074 requests in 30.09s, 49.91MB read
  Socket errors: connect 0, read 0, write 0, timeout 1072
  Non-2xx or 3xx responses: 729
Requests/sec:     35.70
Transfer/sec:      1.66MB
```

**Comment by gugaiz** [comment]
Hi, any ideas what else I can try?

**Comment by gugaiz** [comment]
I solved the issue by changing the upstream configuration on nginx from socket to TCP

```nginx
upstream my_app {
   server 127.0.0.1:3000;
   # server unix:///var/run/puma/my_app.sock;
}
```
