### ISSUE TITLE
Replace "Goodbye" with "See you soon"

### ISSUE THREAD

**Issue by dorianmariefr** [puma/puma#2674]
I stop and start my rails servers a lot, so it's not really a goodbye 😄 

**Describe the solution you'd like**

Replace "Goodbye" by "See you soon"

**Describe alternatives you've considered**

"Good luck", "Puma is stopping, but never stop dreaming", etc. 😄 

**Additional context**

I see there are a few tests that depend on "Goodbye" being present so wanted to ask before sending a pull request.

**Comment by seuros** [comment]
What the end goal of this refactoring ?

**Comment by dorianmariefr** [comment]
I just found it funny and maybe users will find it funny too

**Comment by nateberkopec** [comment]
Given that we have tests depending on it, other people probably do too, which makes this idea a major API version bump.

**Comment by dentarg** [comment]
"Goodbye" is a pretty clear exit message where as "See you soon" could be confusing? Should we change even in 6.0?

**Comment by johnnyshields** [comment]
There's no reason to do this change. Let's close the ticket.
