### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by basicfeatures** [puma/puma#2679]
https://docs.github.com/en/discussions

**Comment by nateberkopec** [comment]
@MSP-Greg advocated for this previously. Anyone else have thoughts?

I looked around and some projects do have a "no support" policy, which we could implement and then just close the Matrix channel perhaps?

**Comment by jacobherrington** [comment]
Personally, I like the idea of long-lived forums for better documentation of discussions.

Also, I almost never have the patience to log into a second or third chat app and I'm sure others feel the same way. This seems like it would lower the barrier to joining discussions about Puma, which would be good?

**Comment by dentarg** [comment]
> then just close the Matrix channel perhaps?

I like the Matrix channel actually: there's not a lot going on there, which is good, as I agree that we should have most discussions here on GitHub. The Matrix channel makes it is possible to bring up things that aren't a great fit for GitHub, or bring attention to something on GitHub (I'm sure we all get many emails/notifications from GitHub, and sometimes things may fall behind).
