### ISSUE TITLE
Support APP_ENV?

### ISSUE THREAD

**Issue by mperham** [puma/puma#2692]
Several years ago, I added support in Sidekiq for `APP_ENV` as a generic replacement to `RAILS_ENV` and `RACK_ENV`. The idea being that RAILS_ENV doesn't make sense if you are using Sinatra, RACK_ENV doesn't make sense if you are using Sidekiq, etc. What we are really trying to express here is the environment specific to the running application code. This term makes sense no matter what specific framework or infrastructure the user is running.

WDYT?

**Comment by dentarg** [comment]
I'm 👍 on `APP_ENV`. Supported [in Sinatra since v2.0.0](https://github.com/sinatra/sinatra/commit/8c2504c816fb5beb89f472ffeccd5f20f911e875). More related previous discussion: https://github.com/sinatra/sinatra/pull/984

**Comment by nateberkopec** [comment]
What precedence/order would we go with?

**Comment by mperham** [comment]
Here’s Sidekiq’s impl: https://github.com/mperham/sidekiq/blob/0bdec6f144de449c8cc4c945acd41d1248a2619d/lib/sidekiq/cli.rb#L198
