### ISSUE TITLE
Fix automatic detection of localhost SSL configuration

### ISSUE THREAD

**Issue by bkuhlmann** [puma/puma#2706]
**Describe the bug**

With the release of Puma 5.5.0, I'm seeing an issue where using the Localhost gem doesn't automatically configure SSL for me without some manual intervention.

ℹ️ @ioquatix This is what I was talking about on Slack. Let me know if this helps or if I can provide any additional info.

**Puma config:**

For the purposes of this example, I'm not using anything special as I detail below. ...but if it helps, I was able to work around the issue by adding this to my Rails `config/puma.rb` to make SSL work:

``` ruby
secure_url = "ssl://localhost:9292" +
             %(?key=#{ENV["HOME"]}/.localhost/localhost.key) +
             %(&cert=#{ENV["HOME"]}/.localhost/localhost.crt) +
             "&ssl_cipher_filter=!aNULL:AES+SHA"

bind secure_url if ENV["RAILS_ENV"] == "development"
```

**To Reproduce**

Start by creating a `Gemfile` with the following configuration and then run `bundle install`:

``` ruby
source "https://rubygems.org"

gem "localhost", "~> 1.1", require: "localhost/authority"
gem "puma", "~> 5.5"
```

Next, create a `config.ru` file with the following code:

```
run proc { [200, {"Content-Type" => "text/plain"}, ["Hello, World!"]] }
```

Now, run with:

```
bundle exec puma
```

You should see the following:

![iTerm2-HHvczzDC](https://user-images.githubusercontent.com/50245/134202793-12e23f9b-8f53-462a-b2f1-348536b90b47.png)

You won't be able to visit https://localhost:9292, though. You'll only be able to use HTTP instead of HTTPS.

If you run the following instead:

``` bash
puma -b "ssl://localhost:9292"
```

You'll get:

![iTerm2-eK5Gi1PX](https://user-images.githubusercontent.com/50245/134203078-0f3d0a35-cde3-46cc-8502-0c5a4753bf0c.png)

**Expected behavior**

I would expect, when using the Localhost gem AND requiring `localhost/authority` to work automatically, maybe?

**Desktop (please complete the following information):**

 - **OS**: macOS 11.6 (20G165)
 - **Ruby**: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin20.5.0]
 - **Puma**: 5.5.0

**Comment by nateberkopec** [comment]
So `bundle exec puma` with localhost/authority defined will not create an SSL listener. That is expected behavior. You need to specifically bind to one with `-b`, as you did. 

I'm looking at the `-b` part and why that's asking for a key, I can repro that.

**Comment by nateberkopec** [comment]
Ok, now I remember.

The problem is that `bundler` does not automatically require anything - we're just used to the fact that Rails, for example, calls `Bundler.setup` when it starts a Rails app and then requires everything in your gemfile. So, you can either:

```ruby
require "localhost/authority"

# or
Bundler.setup(:default)
```

... in your config.ru.

I'm gonna leave this open because I think the docs could be improved to address this.

**Comment by bkuhlmann** [comment]
:bow: Nate. Yeah, that makes sense. To confirm, though, that's essentially what I'm doing with this line `gem "localhost", "~> 1.1", require: "localhost/authority"`. We are both saying the same thing I guess, just two ways of tackling the same problem.

**Comment by nateberkopec** [comment]
So Bundler's dependency management/installing of gems is separate from actually requiring them. Yes, you have a line that says `require: <whatev>` in your Gemfile, but that is best understood as an option for "what will bundler try to require when Bundler requires all the things?"

Your reproduction program never calls `Bundler.setup`, so the gemfile is effectively ignored and nothing is `require`d.

**Comment by bkuhlmann** [comment]
:bow: Nate. Ah, yes, I forgot about that too. In case it helps, either of the following will work:

**With Bundler**

``` ruby
require "bundler/setup"
Bundler.require

run proc { [200, {"Content-Type" => "text/plain"}, ["Hello, World!"]] }
```
---

**Without Bundler**

``` ruby
require "localhost/authority"

run proc { [200, {"Content-Type" => "text/plain"}, ["Hello, World!"]] }
```

**Comment by dentarg** [comment]
> You need to specifically bind to one with `-b`

I updated the [Puma v5.5.0 release notes](https://github.com/puma/puma/releases/tag/v5.5.0) to mention that.
