### ISSUE TITLE
`PumaWorkerKiller: Consuming` messages don't continue after a phased restart w/ fork_worker

### ISSUE THREAD

**Issue by dfuentes77** [puma/puma#2713]
**Describe the bug**
The `PumaWorkerKiller: Consuming` messages don't continue after a phased restart w/ fork_worker

**Puma config:**
This is what I have in puma config file

```
workers Etc.nprocessors
preload_app! false
prune_bundler
wait_for_less_busy_worker 
fork_worker
plugin :tmp_restart

on_worker_fork do
  require 'puma_worker_killer'

  PumaWorkerKiller.config do |config|
    config.ram           = 2048 # mb
    config.frequency     = 10 # seconds
  end

  PumaWorkerKiller.start
end

before_fork do
    require 'puma_worker_killer'
  
    PumaWorkerKiller.config do |config|
      config.ram           = 2048 # mb
      config.frequency     = 10 # seconds
    end
  
    PumaWorkerKiller.start
end
```
I added both (on_worker_fork and before_fork) since I was trying to see if either worked.  Neither worked together or individually.

Basically after I do a phased-restart (SIGUSR1), the PumaWorkerKiller stops logging the consumed memory. 

**To Reproduce**
I stand up rails locally `RAILS_ENV=development bundle exec rails server`
I see the PumaWorkerKiller messages about consumed memory
I send a SIGURG to the master process which triggers a phased-restart
After the phased-restart, I no longer see the PumaWorkerKiller message

I was able to reproduce it with your `hello.ru`

**Expected behavior**
I would assume the PumaWorkerKiller messages would resume right after the phased-restart

**Desktop (please complete the following information):**
 - OS: Mac Big Sur  11.6
 - Puma 5.5.0

**Comment by nateberkopec** [comment]
Sounds like a PWK issue, not our side. It sounds like an issue with IOs closing during the restart, I suspect PWK can deal with that w/o any help from Puma.
