### ISSUE TITLE
Puma 5.5.1: Puma returns 400 error with special characters in headers

### ISSUE THREAD

**Issue by jmreid** [puma/puma#2722]
**Describe the bug**
We noticed that some of our services were returning 400 errors after updating to Puma 5.5.1. We chased it down to requests that had any special characters in headers:

**To Reproduce**
```
curl -IXGET "https://test.echo.server/that_runs_puma_511" --header "X-Forwarded-Name: Raphaël Beamonte"

HTTP/2 400 
date: Tue, 12 Oct 2021 21:15:40 GMT
```

**Expected behavior**
Puma should not return 400 errors for requests with special characters in the request. Downgrading to 5.5.0 resolved the issue for us.

**Comment by nateberkopec** [comment]
> I'll write bluntly: this seems to be a huge change, as I do believe we might not be the only ones having UTF-8 in our headers. The level of breakage this brings is not one of a "patch"-level update, but of a major version, or at least a minor!

Well, if you're doing something that's not covered by RFCs, and not something we explicitly supported as feature before, Puma might break that in a patchlevel release. So for me the conversation is only about whether or not we're .enforcing the RFC correctly or in a useful way.

So now that I'm reading the RFC again, I think we're probably failing Too Loudly here. 

> Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].
   Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

An octet is any 8-bit sequence of data. I think I like rejecting control characters in headers with 400s (there's really no reason to accept them), but I think we were overzealous in rejecting all octets which are not printable ASCII + HTAB, when the spec sort of makes it clear you should treat it as opaque data. It seems like the intention is that we should pass that value, uninterpreted, into the Rack env.

I'll release a 5.5.2/4.3.10 with this change. It's simple but my power is going in and out today so it may take a few tries, please be patient.

**Comment by XaF** [comment]
Thanks Nate! Super efficient!
