### ISSUE TITLE
Release notes for 5.5.1 should mention the change for APP_ENV

### ISSUE THREAD

**Issue by pbstriker38** [puma/puma#2726]
We use `APP_ENV` to define our deployment environment(development, stage, prod). This change caused our app to fail to boot in stage because we do not define a stage configuration.

**Expected behavior**
Breaking changes to load behavior should be mentioned in the release notes.

**Desktop (please complete the following information):**
 - OS: Linux
 - Puma Version 5.5.1

**Comment by nateberkopec** [comment]
This was a mistake on my part. 5.5.1 should've been branched off of v5.5.0 but I just released `master` instead. Luckily this was the only thing that was on there.

Will add.
