### ISSUE TITLE
requests failing sometimes

### ISSUE THREAD

**Issue by mrbrdo** [puma/puma#274]
Hey,

I'm experiencing very slow requests, it seems especially if I don't access the server for a while, it feels similar to how Heroku works on the free version (like it has to start up the whole rails app first). After the first request goes through it works pretty fast (occasionally some hickups though).
Any idea? I'm using MRI with 3 workers and thread config 1:8

EDIT: I updated the description of the problem below... I am getting errors, like sometimes puma can't boot to serve the request.

**Comment by dt1973** [comment]
Same here -- very slow requests after a certain period of inactivity (or after reboot). Works fine again after the first request has gone through.

Using Rails 4.2 with Puma 2.11.0.
