### ISSUE TITLE
preload_app! seems to affect Rails' logging level

### ISSUE THREAD

**Issue by vitobotta** [puma/puma#2749]
**Describe the bug**
I was looking into why Rails' log level stays at INFO even if I explicitly set it to DEBUG in the config (I am making this customizable with and environment variable since it can be handy at times), and found that this happens only if I leave `preload_app!`. If I comment it out, the log level I set is respected. Is there a workaround? Thanks!

**Puma config:**

config/puma.rb:
```ruby
max_threads_count = ENV.fetch("MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

port        ENV.fetch("PORT") { 3000 }

environment ENV.fetch("RAILS_ENV") { "development" }

workers ENV.fetch("WEB_CONCURRENCY") { 2 }

preload_app!

plugin :tmp_restart

rackup      DefaultRackup

on_worker_boot do
  ActiveRecord::Base.establish_connection
end
```

command:

```bash
bundle exec puma -C config/puma.rb -p 3000
```

**To Reproduce**

1. Use the config above for Puma
2. Set the log level in Rails, e.g. `config.log_level = :debug` in the environment's config.

**Expected behavior**
I would expect puma not to affect the logging level I specify in Rails.

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux]: any
 - Puma Version [e.g. 4.1.1]: 5.5.2

**Comment by vitobotta** [comment]
Update. I was able to track it down to a combination of preloading enabled when the stackdriver gem for GCP is in the Gemfile. I don't know why yet but if I either disable the preloading in Puma or remove the stackdriver gem (which I need) then the log level I set is respected. For the time being I have just disabled the preloading but I would be happier if there were another workaround that didn't require that.

**Comment by dentarg** [comment]
If you can post a complete repro (e.g. a minimal app that exhibit the problem, in its own GitHub repo, with clear instructions how to reproduce) that would be helpful for anyone wanting to take a look at this

**Comment by vitobotta** [comment]
> If you can post a complete repro (e.g. a minimal app that exhibit the problem, in its own GitHub repo, with clear instructions how to reproduce) that would be helpful for anyone wanting to take a look at this

Hi! It's a bit tricky because it requires the stackdriver gem to be active (not just in the gemfile) at the same time, so the app needs to be in a real Google Cloud project. I'll see if I can prepare a repo anyway so hopefully someone who uses GCP might give it a try.

**Comment by nateberkopec** [comment]
Closing, if you have a repro we can take a look again 🙏
