### ISSUE TITLE
Adding requests metadata to worker handle for better observability

### ISSUE THREAD

**Issue by synth** [puma/puma#2754]
**Is your feature request related to a problem? Please describe.**
There are two example problems I'd like to address: 
1. A request consumes a ton of memory and causes a worker process to be OOM-killed
2. A request causes memory fragment or leak

**Describe the solution you'd like**
I'd like Puma master process to be able to keep track of request level metadata (eg, request path at a minimum) so it actually knows information about the types of requests the workers are handling at any given time. In other words, **Puma master process could know what workers are processing which requests at any given moment**.  It should go without saying that, for this purpose, we don't care about historical requests (ones that have completed) - only inflight request state

**Describe alternatives you've considered**
I could see this implemented a few ways. For example, the workers could report in about the requests via the IPC ping mechanism just as it does with the request count and store a requests array in the worker handle. 

Alternatively, If an "around request" block were to be implemented in the worker, it could potentially be exposed to Puma config and allow calculation of `GC.stat` deltas that could be reported out on. Then in the case of abnormal termination of the worker (in which case the "around request" block wouldn't complete), the parent process would have access to the stale worker handle requests state and report/log on it, before it clears it out and spawns a new worker. 

Also, could this potentially be implemented as a plugin? If so, I would gladly build one!

**Additional context**
Standard observability tools don't work for these problems because while they may be able to detect when a process dies, they don't typically track request to process detail. In fact, they typically don't report requests at all unless they finish. Puma parent process knows when a worker has abnormally died. If it knew metadata about that process, then we can get observability into perhaps why that process died. Puma can log the situation that it knows a worker has terminated and it was in the process of x,y,z requests. Practitioners can then investigate to see, for example, if the same request was causing the process to die. Further, for cases when the process doesn't die, but causes fragmentation or a leak, we can use similar mechanism to track which are the problematic requests.

**Comment by synth** [comment]
I would gladly submit a PR for this if there is support for this idea and if I am given implementation guidance.

**Comment by nateberkopec** [comment]
You could implement a Rack middleware which uses GC.stat to report this information. 

However, and this is a limitation of Ruby, you can't guarantee that this information is useful in a multithreaded environment. Multiple requests could be in-flight when the worker exits and you won't know which of the requests caused the change in memory use. Still, sometimes some info is better than none.

> Puma parent process knows when a worker has abnormally died

So does the child. The OOM killer sends SIGKILL to the child, not the parent (because the child process will be the one with the higher "badness" score"). So you could probably use `at_exit` here to fire off something before the process dies.

Closing because this is not necessary to implement in Puma (or would even be Puma-specific).

**Comment by synth** [comment]
Hi @nateberkopec Thx for your response. Respectfully, I'd like to advocate for this a bit more though. As you mentioned, GC.stat in a middleware is not usable in multi-threaded envs (which is a common, if not predominant, case).

> The OOM killer sends SIGKILL to the child, not the parent 
> So you could probably use at_exit here to fire off something before the process dies.

I don't believe this is possible because you cannot trap SIGKILL. [Ref1](https://askubuntu.com/questions/832767/run-another-command-when-my-script-receives-sigkill-signal) | [Ref2](https://stackoverflow.com/questions/22807714/why-i-am-not-getting-signal-sigkill-on-kill-9-command-in-bash)

> Closing because this is not necessary to implement in Puma (or would even be Puma-specific).

You mention in the "Complete Guide to Rails Performance" how load balancers are dumb because they don't know the state of requests from individual parent worker processes (in multi-threaded cluster mode) which is why timeouts can happen. In other words, Puma parent process is smarter about routing requests because it knows which child processes are still processing requests and which children are better suited for an incoming request. 

The reasoning here is similar. We can add a little more "smarts" to the parent process to help observability and handling regarding a prime Ruby problem: memory awareness and management. 

I'm not necessarily advocating for all of this functionality to be added to Puma core, as it is indeed a bit application/use-case specific. However, I do think that Puma's plugin architecture could be amended to support these cases. 

I appreciate a second thought on this :)

**Comment by synth** [comment]
> Puma's parent process doesn't know anything about its child processes. Puma child processes all listen on the same OS socket, and the operating system determines which child process' accept syscall succeeds and processes the request.

Ah, got it. Good design ;)

> Puma's parent process doesn't know anything about its child processes.
> it's adding lots of new coupling between the parent and child processes that didn't exist before,

This is not entirely true. Parent knows the status of children, knows the request count of each child and knows whether to respawn a new child if a process has died. Since an "extraneous" (but useful) data point like request count is passed up to parent through IPC, why draw a judgement against other data? If Puma implemented the appropriate hooks, plugins could have children pass up arbitrary data to the parent as well. 

Sorry to be persistent here, but in summary, I think there could be a lot of value added by: 
1. leveraging Puma's existing IPC functionality (that is already used for data points like request count that is communicated from child to parent via IPC) to expose plugin hooks so plugin authors can add additional data points or functions for observability
2. adding a hook into parent process that runs an arbitrary function registered by a plugin when the parent detects that a child has died (which it already does in order to spawn a new child) that can read the data points stored by the parent on that worker for the purposes of sending to observability/logging tools. 

This actually seems like not very much work and a huge value add and I'm super down to submit a PR with your blessing. Hope to hear back on your final thoughts :)
