### ISSUE TITLE
Puma close after initiallization without intent and without giving info

### ISSUE THREAD

**Issue by juansecaro** [puma/puma#2755]
**Describe the bug**
Existing and working app, previously tested configuration. New deploy with different version of Puma.
After invoking Puma, it seems it gets the configuration right, but don't keep listening and ends unexpectedly without any message

**Puma config:** (Tested previously in another deployment)
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count
app_dir = "/home/deploy/redvi/current" #
shared_dir = "/home/deploy/redvi/shared" #
bind  "unix://#{shared_dir}/tmp/sockets/puma.sock"
pidfile "#{shared_dir}/tmp/pids/puma.pid"
state_path "#{shared_dir}/tmp/puma.state"
directory "#{app_dir}/"
stdout_redirect "#{app_dir}/log/puma.stdout.log", "#{app_dir}/log/puma.stderr.log", true
workers 9
preload_app!
environment "production"
plugin :tmp_restart

Please copy-paste your Puma config AND your command line options here.
/home/deploy/.rbenv/shims/puma -C /home/deploy/redvi/current/config/puma/production.rb

![puma](https://user-images.githubusercontent.com/5209472/142733339-6180ca42-f740-419e-8eac-ad98fdbe8ef9.png)

**Comment by nateberkopec** [comment]
Please reopen if you have a reproducing app 🙏
