### ISSUE TITLE
Expected behaviour with thousands of simultaneous connections?

### ISSUE THREAD

**Issue by jdelStrother** [puma/puma#2756]
**Describe the bug**
I'm running puma with nginx sitting between it & the internet. On sudden traffic spikes (eg 1800 requests hitting a single puma master over 10 seconds), I see nginx producing errors like:

```
*63469832 recv() failed (104: Connection reset by peer) while reading response header from upstream
```

**Puma config:**

None, I can reproduce this with just `bundle exec puma`

**To Reproduce**

I believe I can reproduce the same error with apachebench, even with a zero-config puma and a config.ru like: 

```ruby
run proc { sleep 0.01; [200, {"Content-Type" => "text/html"}, ["Hello Rack!"]] }
```

Here's apachebench talking directly to puma, with 2000 concurrent connections:
```
$ ab -c2000 -n20000 http://0.0.0.0:9292/
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 0.0.0.0 (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
apr_socket_recv: Connection reset by peer (104)
Total of 6640 requests completed
```

or if I tell apachebench to ignore socket errors - 
```
$ ab -r  -c2000 -n20000 http://0.0.0.0:9292/
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 0.0.0.0 (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
Completed 18000 requests
Completed 20000 requests
Finished 20000 requests


Server Software:
Server Hostname:        0.0.0.0
Server Port:            9292

Document Path:          /
Document Length:        11 bytes

Concurrency Level:      2000
Time taken for tests:   68.211 seconds
Complete requests:      20000
Failed requests:        1651
   (Connect: 0, Receive: 546, Length: 559, Exceptions: 546)
Total transferred:      1458075 bytes
HTML transferred:       213851 bytes
Requests per second:    293.21 [#/sec] (mean)
Time per request:       6821.090 [ms] (mean)
Time per request:       3.411 [ms] (mean, across all concurrent requests)
Transfer rate:          20.87 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  415 1464.6      0   31615
Processing:    14 4234 11997.5   1080   62383
Waiting:        0 3806 11788.7   1079   62383
Total:         88 4648 12517.2   1081   65415

Percentage of the requests served within a certain time (ms)
  50%   1081
  66%   1086
  75%   1090
  80%   1805
  90%   5143
  95%  30514
  98%  55864
  99%  64990
 100%  65415 (longest request)
```

I've tried with different numbers of puma workers, numbers of threads, raising tcp_max_syn_backlog & netdev_max_backlog, without any apparent success. Is this just expected behaviour and I need to spread my traffic peaks out over more puma-master processes, or is there something else I might try?

**Expected behavior**

On the same machine, nginx seems capable of accepting many thousands of connections without issue. Can I do anything to get puma to match that?

**Desktop (please complete the following information):**
 - OS: Ubuntu 18, also tested on AWS Linux 2
 - Puma Version: 5.5.2, but the problem seems present in all the versions I tested back to puma 4 (I didn't try further back).

**Comment by MSP-Greg** [comment]
I believe the default backlog depth is 1,024, so that might be an issue.  See [Puma::DSL#bind](https://msp-greg.github.io/puma/Puma/DSL.html#bind-instance_method) for info on setting it higher.  I.think.  I don't think I've seen mention of 'while reading response header from upstream' before.

Not normally awake at this time, somewhat foggy.

**Comment by jdelStrother** [comment]
Ah, yes it is. I'd tried tweaked that setting before, but apparently not in combination with net.core.somaxconn. After raising them both to 2096 it passes my little ab test - I'll try enabling it in production tomorrow & see if it resolves our nginx errors.

**Comment by MSP-Greg** [comment]
Glad that was it.  Thanks for checking.

Lately I've done quite a bit of local perf testing.  When one sees times like the following, where the top 10% have an order of magnitude increase in time, it means that a lot of requests are queued in the backlog.

The only way to fix it is to add more threads (and maybe workers), assuming one's app can also handle the extra traffic...

```
Percentage of the requests served within a certain time (ms)
  50%   1081
  66%   1086
  75%   1090
  80%   1805
  90%   5143
  95%  30514
  98%  55864
  99%  64990
 100%  65415 (longest request)
```

**Comment by jdelStrother** [comment]
> Lately I've done quite a bit of local perf testing. When one sees times like the following, where the top 10% have an order of magnitude increase in time, it means that a lot of requests are queued in the backlog.
Thanks - yep, we're only seeing those crazy long-tail requests in my artificial one-worker one-thread test case.

Looks like increasing the backlog has fixed all our problems, happy to close this if you like. I wondered if the default behaviour could be improved - seems like you could request a much higher backlog and then leave it up to sysctl to enforce the lower system if net.core.somaxconn hasn't been increased, but I don't know enough about the tradeoffs.
