### ISSUE TITLE
Add ability to increase max REQUEST_PATH and REQUEST_URI

### ISSUE THREAD

**Issue by dlynam** [puma/puma#2758]
I have a scenario where I want to allow a bookmarklet to save URLs through a GET request but am running into `REQUEST_URI is longer than the 1024 * 12 allowed length` errors. 

Thoughts on allowing a max REQUEST_PATH and REQUEST_URI to be set through an environment variable (similar to how this was handled with the QUERY_STRING https://github.com/puma/puma/issues/2273)?

**Comment by nateberkopec** [comment]
Works for me, fine with following #2273 as a template.

**Comment by ukolovda** [comment]
In Dockerfile I used:
```Dockerfile
RUN bundle config build.puma "--with-cflags='-D PUMA_QUERY_STRING_MAX_LENGTH=64000 -D PUMA_REQUEST_URI_MAX_LENGTH=64000'"
RUN bundle install
```

Long URLs I use for reports with rich filters. Users can share URL for send report conditions.

**Comment by dentarg** [comment]
Closing as this was released with Puma 6
