### ISSUE TITLE
k8s pod rolling deployment successful but application doesn't give any response

### ISSUE THREAD

**Issue by continuuminnovations** [puma/puma#2772]
**Describe the bug**
we are running AWS EKS with 1.21 version of k8s. deploying the rails application for our backend API, when we deploy the rails application with rolling updates deployment becomes successful and we are able to connect to the containers but one pod doesn't not give any response.

**Puma config:**

max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

port ENV.fetch("PORT") { 3000 }

environment ENV.fetch("RAILS_ENV") { "development" }

pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

plugin :tmp_restart

Please copy-paste your Puma config AND your command line options here.

**To Reproduce**
Run the ruby rails API with sample app in k8s with the below deployment file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: mamba-connect-webserver
          image: CONTAINER_IMAGE
          imagePullPolicy: "Always"
          env:
            - name: RAILS_MASTER_KEY
              value: R_MASTER_KEY
          command: ["rails", "server", "-b", "0.0.0.0", "-p", "4000"]
          ports:
            - containerPort: 4000

Your issue will be solved very quickly if you can reproduce it with a "hello world" rack application. To do this, copy this into a file called `hello.ru`:

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma -C <where_your_config_is> hello.ru
```

If you cannot reproduce with a hello world application or other simple application, we will have a lot more difficulty helping you fix your issue, because it may be application-specific and not a bug in Puma at all.  

There is also a Dockerfile available for reproducing Linux-specific issues. To use:

```
$ docker build -f tools/docker/Dockerfile -t puma .
$ docker run -p 9292:9292 -it puma
```

This will help you to create a container that reproduces your issue.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Amazon Linux 2]
 - Puma Version 5.4.2

**Comment by nateberkopec** [comment]
Is this a problem with Puma or a problem with your k8s deployment?

**Comment by dentarg** [comment]
I'm not sure we can help you debug your deployment setup, but feel free to comment if you have anything more concrete that should be changed in Puma, and we can re-open.
