### ISSUE TITLE
Encoding::UndefinedConversion error (Mac OS M1, Rubymine Debug mode)

### ISSUE THREAD

**Issue by Gooner91** [puma/puma#2775]
**Describe the bug**
While setting up my new dev machine (Macbook air M1) with RubyMine, I ran into an issue where starting the app in debug mode, I faced the following issue from puma
<img width="1173" alt="Screenshot 2021-12-21 at 10 56 35" src="https://user-images.githubusercontent.com/8371074/146910072-031a2cf9-cd5e-4059-8eea-344c7c8e555a.png">

As it seems puma was trying to log a checkmark from one of the files (below screenshot) but there seems to be an encoding issue while trying to display it on the console
<img width="605" alt="Screenshot 2021-12-20 at 18 06 33" src="https://user-images.githubusercontent.com/8371074/146908925-1ebdacf3-b469-48f1-b1ab-070fc423593c.png">

I have been able to run the same command from the IDE seamlessly on Ubuntu and Mac Intel machines for quite some time. Is it related to some OS settings?

I have also taken this issue up with the Jetbrains community [here](https://youtrack.jetbrains.com/issue/RUBY-29145) and it seems this is relevant to Puma and not Jetbrains. 

**Expected behavior**
Encoding conflicts should not appear.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur (11.3.1)
 - Puma Version 5.5.2

**Comment by dentarg** [comment]
To me, it looks like RubyMine on your machine isn't running with the encoding set to UTF-8 for the Ruby environment. I think you should contact JetBrains support about it again.

How one can re-produce the same error with only IRB:

```ruby
$ LANG= LC_ALL= LC_CTYPE= irb
irb(main):001:0> Encoding.default_external
=> #<Encoding:US-ASCII>
irb(main):002:0> puts "Restarts: (\u2714)"
(irb):2:in `write': U+2714 from UTF-8 to US-ASCII (Encoding::UndefinedConversionError)
	from (irb):2:in `puts'
	from (irb):2:in `puts'
	from (irb):2:in `<main>'
	from /Users/dentarg/.gem/ruby/3.0.2/gems/irb-1.3.7/exe/irb:11:in `<top (required)>'
	from /Users/dentarg/.gem/ruby/3.0.2/bin/irb:23:in `load'
	from /Users/dentarg/.gem/ruby/3.0.2/bin/irb:23:in `<main>'
irb(main):003:0>
```

**Comment by Gooner91** [comment]
Thanks for the response @dentarg . Will check again with Jetbrains and see how can I configure the IDE appropriately.

**Comment by Gooner91** [comment]
@nateberkopec on another look I can see the IDE configured to use UTF-8. 
![Screenshot 2022-01-04 at 08 58 59](https://user-images.githubusercontent.com/8371074/148027452-68fdc389-7c9b-4f70-9aaf-283fbba4c1f3.png)

**Comment by Gooner91** [comment]
@nateberkopec on another look I can see the IDE configured to use UTF-8.
![Screenshot 2022-01-04 at 09 01 31](https://user-images.githubusercontent.com/8371074/148027640-f615453f-89c1-4ff2-a98f-95515ba85f70.png)
