### ISSUE TITLE
Question about how to handle a pipe when forking

### ISSUE THREAD

**Issue by estolfo** [puma/puma#2776]
Hi Puma team, this isn't a bug report but rather a request for advice. I'm dealing with a "bug" in the [Elastic Ruby APM agent](https://github.com/elastic/apm-agent-ruby) and I wanted to ask you if you've heard of someone having this issue in the past and how they resolved it. It's not exactly a bug in the agent, more like a limitation of Ruby and forking.

The Ruby agent is a singleton and uses a `IO.pipe` to send data to the APM server. When the parent process is forked, the child inherits the `reader`s and (gzip)`writer`s. I create new `reader`s and `writer`s in the child process so that I don't interfere with the parent's work.
When the fork exits, I close the child's `reader`s and `writers` but I see the follow error
```
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
```
because the parent's `writer` is still considered living in the child process.
One option to address this error is to create a finalizer on the writer that closes it. But then I get intermittent errors from the APM server saying the gzipped data's header is invalid. I'm assuming this is because the (parent's) writer is closed by the child before the compression is complete in the parent.

Have you heard of an issue like this before? Do you have any ideas on how to handle it?
Thanks!

**Comment by nateberkopec** [comment]
Hey Emily!

Puma's pipes are either a) deliberately inherited and re-used in child processes or b) only opened in the child. So we don't have the issue you've mentioned here. Good luck!

**Comment by estolfo** [comment]
Thanks @nateberkopec !
