### ISSUE TITLE
'production' or 'deployment' for environment to be consistent with Rack gem

### ISSUE THREAD

**Issue by justin808** [puma/puma#2788]
**Describe the bug**

Should the environment for production deployment be 'deployment' according to [Rack docs](https://github.com/rack/rack/blob/master/lib/rack/server.rb#L184-L190) or 'production' according to

https://github.com/puma/puma/blob/4ac14482f1eda4bcf2d2baa3a379afe3f5b55a9c/lib/puma/dsl.rb#L292-L301

Heroku's docs state:
https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#environment

```
# Set the environment of Puma. On Heroku ENV['RACK_ENV'] will be set to 'production' by default.
environment ENV['RACK_ENV'] || 'development'
```

Seems that in Rack's code, only 'deployment' and 'development' are used:

https://github.com/rack/rack/blob/d08cdbe7f940af0d2040fe65965caf1c8c531307/lib/rack/server.rb#L264-L280

**Comment by MSP-Greg** [comment]
I think Puma uses a test for equal to 'development', so 'production' or 'deployment' will behave the same way.

**Comment by dentarg** [comment]
Yes, Puma is not using `Rack::Server` where `RACK_ENV=deployment` matters. 

`Rack::Server` is used by [`rackup`](https://github.com/rack/rack/blob/2.2.3/bin/rackup), and there's been discussion about this for `rackup`: https://github.com/rack/rack/pull/831

I don't see any upside with making `environment production` in Puma mean `RACK_ENV=deployment`, that would just be very unexpected for anyone using Puma, I think.
