### ISSUE TITLE
OpenSSL 3 - symbol not found in flat namespace '_SSL_get1_peer_certificate'

### ISSUE THREAD

**Issue by jakemumu** [puma/puma#2790]
**Describe the bug**

I've been attempting to spin up a new rails 6 or 7 project, but haven't been able to do so due to a consistent issue with puma and open SSL

`puma_http11.bundle, 0x0009): symbol not found in flat namespace '_SSL_get1_peer_certificate'`

**Puma config:**

NA

**To Reproduce**

Mac 12.0.1 Intel, OpenSSL 3 installed via brew + Puma. 

rails new project

--

Anyone able to give some tips here?

**Comment by MSP-Greg** [comment]
@jakemumu I tested against OpenSSL 3.0.0 when it was released.  The test suite passed, can't recall what else I checked.

I've got 3.0.1 installed/built; I haven't built Ruby or Puma with it yet.  I'll try to do so over the weekend...

**Comment by nickmc** [comment]
Just had the same problem with an existing Rails 6.1 app. Upgraded Ruby from 2.7.1 to 2.7.5 and now receiving this error. 

Using Puma 5.5.2 and OpenSSL 3.0.1 (brew). On a Mac Mini M1.

Very grateful for any suggestions!

**Comment by MSP-Greg** [comment]
I just tested using Ruby master and Puma master built with OpenSSL 3.0.1.  It passes all of Puma's SSL tests.  

@nickmc I don't believe Ruby 2.7.5 is compatible with OpenSSL 3.0.1.  It may build, but I doubt Ruby OpenSSL tests would pass...

**Comment by nickmc** [comment]
Aah OK, understood, many thanks.

**Comment by MSP-Greg** [comment]
Re OpenSSL 3, I haven't tested what works and doesn't work if there are OpenSSL version mismatches between build/run versions with Puma and/or Ruby.  Regardless, to check, use the following code:
```ruby
require 'puma'
require 'puma/minissl'
require 'openssl'

p_ssl = Puma::MiniSSL
wid = 32

pre = "\n#{RUBY_DESCRIPTION}\nRUBYOPT: #{ENV['RUBYOPT']}\n\n"

if Puma::IS_JRUBY || !Puma::HAS_SSL
  STDOUT.syswrite pre +
    "                         OpenSSL\n" \
    "OPENSSL_LIBRARY_VERSION: #{OpenSSL::OPENSSL_LIBRARY_VERSION}\n" \
    "        OPENSSL_VERSION: #{OpenSSL::OPENSSL_VERSION}\n\n"
else
  STDOUT.syswrite pre +
    "                         #{'Puma::MiniSSL'.ljust wid}Ruby OpenSSL\n" \
    "OPENSSL_LIBRARY_VERSION: #{p_ssl::OPENSSL_LIBRARY_VERSION.ljust wid}#{OpenSSL::OPENSSL_LIBRARY_VERSION}\n" \
    "        OPENSSL_VERSION: #{p_ssl::OPENSSL_VERSION.ljust wid}#{OpenSSL::OPENSSL_VERSION}\n\n"
end
```

Locally, I run Windows and Windows WSL2/Ubuntu.  I haven't switched to OpenSSL 3.0.1 on Ubuntu, but I can run it on Windows.  Running the code above, all four OpenSSL versions should be the same, as below.
```
ruby 3.2.0dev (2022-01-10T15:30:53Z master c9325cb8cf) [x64-mingw-ucrt]
RUBYOPT: <system/user defined>

                         Puma::MiniSSL                   Ruby OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 3.0.1 14 Dec 2021       OpenSSL 3.0.1 14 Dec 2021
        OPENSSL_VERSION: OpenSSL 3.0.1 14 Dec 2021       OpenSSL 3.0.1 14 Dec 2021
```

Also, the first version of the Ruby OpenSSL stdlib that is compatible with OpenSSL 3 was included in Ruby 3.1.  If you're not using Ruby 3.1, you should upgrade the Ruby OpenSSL std-lib, which is compatible with Ruby 2.6 and later...

**Comment by MSP-Greg** [comment]
@jakemumu @nickmc

Wondering if this should be left open?  OpenSSL 3 adoption by major OS's is probably at least a few months away.

Changes need to be made to Puma for it, but those changes are due to deprecations of many functions that are still available.  I'm not sure if OpenSSL has announced when they'll be removed.

**Comment by jakemumu** [comment]
Thanks for the information on this -- Is the consensus then to stay on ruby 2.7.4 -- I don't think I was having issues with OpenSSL 3 with that version -- I just used brew install openssl which I believe does 3 by default (at least on my machine)

**Comment by upgundecha** [comment]
Experiencing the same issue `symbol not found in flat namespace '_SSL_get1_peer_certificate'` while switching existing Rails application set up to Apple M1Pro macOS 12.1 and OpenSSL 3 is installed via Homebrew. I'm using Ruby 3.0.1

**Comment by dentarg** [comment]
How are you all installing Ruby?

Both [ruby-build](https://github.com/rbenv/ruby-build) and [ruby-install](https://github.com/postmodern/ruby-install) (since version 0.8.3) should use OpenSSL 1.1.1. ruby-build only uses OpenSSL 3.0 for Ruby 3.2.0-dev today: https://github.com/rbenv/ruby-build/commit/b5ade33c34cca8b9c57d11fd66477fa222ae4980

Maybe related somehow? https://github.com/postmodern/ruby-install/issues/412

**Comment by upgundecha** [comment]
Resolved my issue after removing the OpenSSL 3 and `gem install puma -v '5.5.2' -- --with-cppflags=-I$(brew --prefix openssl)/include` using the default openssl installed on macOS i.e. `LibreSSL 2.8.3`

**Comment by MSP-Greg** [comment]
@upgundecha

What is the output of:
```
ruby -ropenssl -e "puts %Q[\ \ \ Build: #{OpenSSL::OPENSSL_VERSION}\n Runtime: #{OpenSSL::OPENSSL_LIBRARY_VERSION}]"
```

**Comment by upgundecha** [comment]
Hi @MSP-Greg 

It is 

```
 Build: OpenSSL 1.1.1l  24 Aug 2021
 Runtime: OpenSSL 1.1.1m  14 Dec 2021
```

**Comment by MSP-Greg** [comment]
@upgundecha

Thanks. At present, I can't run macOS locally.  I doubt Puma will run if it's compiled with OpenSSL 3.0.x when the Ruby calling it is using OpenSSL 1.1.1.

One needs to build Ruby with OpenSSL 3.0.x, then build Puma.  From the above, your Ruby was built with OpenSSL 1.1.1l, and OpenSSL has been upgraded to 1.1.1m.  Normally, that difference (l vs m) isn't an issue.

**Comment by MSP-Greg** [comment]
In OpenSSL 3, there are many functions that have a 0 or 1 suffix added to them, and the unsuffixed versions that existed in previous OpenSSL versions are deprecated. So, in OpenSSL 3, `SSL_get1_peer_certificate` exists, but it doesn't exist in OpenSSL 1.1.1, which has `SSL_get_peer_certificate`.

So, the error is probably due to compiling Puma with OpenSSL 3.0.x, but using a Ruby that runs with OpenSSL 1.1.1.  The code three comments above this will output what version Ruby is using.

**Comment by jakemumu** [comment]
not sure if this helps anyone else -- but after creating a new rails 7 project, downgrading puma to 4.3 resolves this for me.

**Comment by MSP-Greg** [comment]
I'm going to close this.  Unless the following reports OpenSSL 3.0.x, you need to build Ruby with OpenSSL 3.0.x, then install/build Puma.

The first version of Ruby that has been tested with OpenSSL 3 is 3.1.0.  You may be able to install the Ruby OpenSSL gem (`gem install openssl`) or later with Ruby 2.6 or later.

```
ruby -ropenssl -e "puts %Q[\ \ \ Build: #{OpenSSL::OPENSSL_VERSION}\n Runtime: #{OpenSSL::OPENSSL_LIBRARY_VERSION}]"
```

**Comment by koppen** [comment]
I've been seeing this issue as well, and I am trying to wrap my head around this.

- One needs to build Ruby with OpenSSL 3.0.x, then build Puma
- in OpenSSL 3, `SSL_get1_peer_certificate` exists, but it doesn't exist in OpenSSL 1.1.1, which has `SSL_get_peer_certificate`
- The first version of Ruby that has been tested with OpenSSL 3 is 3.1.0. 

Does the above mean that if one gets the `symbol not found in flat namespace '_SSL_get1_peer_certificate'` error, one needs to compile Ruby with OpenSSL 3, which effectively means upgrading to at least 3.1.0?

Sorry for being dense, but this is somewhat confusing to me.

**Comment by dentarg** [comment]
Sounds correct to me @koppen

**Comment by MSP-Greg** [comment]
> Does the above mean that if one gets the symbol not found in flat namespace '_SSL_get1_peer_certificate' error, one needs to compile Ruby with OpenSSL 3, which effectively means upgrading to at least 3.1.0?

The above statement is more or less 'if A then B'.  More generally, if one wants to use OpenSSL 3, all the code in a process/app needs to use OpenSSL 3.  Hence, in this case, both Ruby and Puma.  Note that there are other gems using OpenSSL.  I think EventMachine does...

**Comment by wlipa** [comment]
I encountered something close to this error with a clean MacPorts installed ruby30 and the latest puma gem.  Could not figure it out so eventually I dropped back to puma 5.5.3 which is good enough for now and avoids the problem.

**Comment by kaysiz** [comment]
I had the same problem and below was my solution
`Rails 7.0.2.2`
`ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21]`
`ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52`

1. brew reinstall openssl@3
2. rvm reinstall 3.1.0 --with-openssl-dir=`brew --prefix openssl`

Hope this helps someone.

**Comment by muhammadyana** [comment]
Hello all, Is there any update? 
i got same error in my existing project

`Ruby 2.6.3`
`Rails 6.0.1`
`Mac Intel` 

`ruby -ropenssl -e "puts %Q[\ \ \ Build: #{OpenSSL::OPENSSL_VERSION}\n Runtime: #{OpenSSL::OPENSSL_LIBRARY_VERSION}]"`
openSSL
`Build: OpenSSL 1.1.1m  14 Dec 2021`
` Runtime: OpenSSL 1.1.1m  14 Dec 2021`

Thank u

**Comment by dentarg** [comment]
@muhammadyana See https://github.com/puma/puma/issues/2790#issuecomment-1013898050

**Comment by Jarrodsz** [comment]
Why closed this problem is still not resolved.

**Comment by MSP-Greg** [comment]
I suspect it should be
```
--with-openssl-dir=$(brew --prefix openssl)
```

**Comment by Jarrodsz** [comment]
Trying to recompile on Apple Silicon with above instructions gives:


```Building native extensions. This could take a while...
/Users/jonathan/.rvm/src/ruby-3.1.0/lib/rubygems/ext/builder.rb:95:in `run': ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    current directory: /Users/jonathan/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension
/Users/jonathan/.rvm/rubies/ruby-3.1.0/bin/ruby --disable\\=gems -I/Users/jonathan/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/arm64-darwin22 -I /Users/jonathan/.rvm/src/ruby-3.1.0/lib -r ./siteconf20220627-96660-lmy32v.rb extconf.rb
creating Makefile

current directory: /Users/jonathan/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension
make DESTDIR\\= clean
dyld[96663]: terminating because inserted dylib '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' could not be loaded: tried: '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (no such file), '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))
dyld[96663]: tried: '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (no such file), '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))

current directory: /Users/jonathan/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0/gems/rbs-2.0.0/ext/rbs_extension
make DESTDIR\\=
dyld[96664]: terminating because inserted dylib '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' could not be loaded: tried: '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (no such file), '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))
dyld[96664]: tried: '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (no such file), '/Users/jonathan/.rvm/src/ruby-3.1.0/libruby.3.1.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'arm64e'))

make failed, uncaught signal 6
```
How should I bypass this? there seems to be no dylib for brew install dylib :S

**Comment by WilliamMena** [comment]
M1 macbook, ruby 2.6.8, OpenSSL 3 installed along with OpenSSL 1.1

Ran into `symbol not found in flat namespace '_SSL_get1_peer_certificate'` when trying to build a client application.
The way I was able to overcome it was by uninstalling my current ruby version and installing it again using these commands.

```
CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)" RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)" rbenv install 2.6.8
gem install bundler -v 2.2.33 # install the bundler version in your Gemfile.lock
bundle config build.puma --with-cppflags=-I$(brew --prefix openssl@1.1)/include
bundle install
```

**Comment by pengyin-shan** [comment]
For anyone like me who use rvm, since '_SSL_get1_peer_certificate' belongs to openssl@3 on Mac, remove your current ruby (for a clean install), then run `rvm install RUBY_VERSION --with-openssl-dir=/usr/local/opt/openssl@3` to reinstall ruby with the correct OpenSSL version. 
(Also good to confirm the existence of `/usr/local/opt/openssl@3` before you do this)

**Comment by SurenNihalani** [comment]
I ran into this with a python import error. This happened because I had reinstalled openssl after poetry installing my dependency. After doing the following in my dotenv rc file, I did a poetry install and that fixed this error:
```
export LIBRARY_PATH="/usr/local/opt/openssl/lib${LIBRARY_PATH:+:$LIBRARY_PATH}"
export LDFLAGS="-L$(brew --prefix openssl)/lib -L$(brew --prefix librdkafka)/lib  $LDFLAGS"
export CPPFLAGS="-I$(brew --prefix openssl)/include -I$(brew --prefix librdkafka)/include $CPPFLAGS"
if [ -z ${PKG_CONFIG_PATH+x} ]; then
   export PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig:$(brew --prefix librdkafka)/lib/pkgconfig:$PKG_CONFIG_PATH"
else
   export PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig:$(brew --prefix librdkafka)/lib/pkgconfig"
fi
```

**Comment by soudai-s** [comment]
I encountered this problem and the way I was able to resolve it is follows,

```
$ bundle config build.puma --with-pkg-config=$(brew --prefix openssl@1.1)/lib/pkgconfig
$ bundle install --redownload
```

M1 Max x Ruby 3.0.5 (installed via rbenv 1.2.0-64-gaf9201e) x puma 5.6.4.

I did not have to reinstall ruby to specify build options, or remove openssl@3 :)

**Comment by taf2** [comment]
For anyone else having this issue if you have both openssl 3 and 1 - more common these days (2023) - most deployments of puma don't need ssl support (would normally run behind a proxy) you can get around this issue with 

```
PUMA_DISABLE_SSL=1 bundle
```

**Comment by dux** [comment]
what [kaysiz](https://github.com/kaysiz) said helped me, but unfortunately he made a type so here are correct commands

```
brew reinstall openssl@3
rvm reinstall 3.1.4 --with-openssl-dir=$(brew --prefix openssl)
```

**Comment by domenkozar** [comment]
What's the best way to test puma works with openssl?

**Comment by dentarg** [comment]
@domenkozar https://github.com/puma/puma#self-signed-ssl-certificates-via-the-localhost-gem-for-development-use

**Comment by domenkozar** [comment]
I'd like to have a Ruby snippet I can run.

I'm trying to write a test for https://github.com/bobvanderlinden/nixpkgs-ruby/issues/80#issuecomment-1654429692

Where I'd have to add [a test](https://github.com/cachix/devenv/blob/main/examples/rubyonrails/.test.sh) to the [ror example](https://github.com/cachix/devenv/blob/main/examples/rubyonrails/devenv.nix).

**Comment by dentarg** [comment]
You can look at the tests for https://github.com/Starkast/wikimum if you want

**Comment by RedaBenh** [comment]
> I encountered this problem and the way I was able to resolve it is follows,
> 
> ```
> $ bundle config build.puma --with-pkg-config=$(brew --prefix openssl@1.1)/lib/pkgconfig
> $ bundle install --redownload
> ```
> 
> M1 Max x Ruby 3.0.5 (installed via rbenv 1.2.0-64-gaf9201e) x puma 5.6.4.
> 
> I did not have to reinstall ruby to specify build options, or remove openssl@3 :)

thanks @dux your solution works fine with my mac pro m1 pro because no need to reinstall ruby

**Comment by soudai-s** [comment]
@RedaBenh 
Remember to remove the bundle option from its config before upgrading ruby, as openssl@3 is required for ruby 3.1 or higher 👍

**Comment by ishikajain0411** [comment]
dlopen(//gems/2.7.0/gems/puma-5.6.4/lib/puma/puma_http11.bundle, 0x0009): symbol not found in flat namespace (_SSL_get1_peer_certificate) -versions/2.7.6/lib/ruby/gems/2.7.0/gems/puma-5.6.4/lib/puma/puma_http11.bundle (LoadError)

macOS version: 12.7
ruby: 2.7.6
rails: 6.1.7
puma: 

any solution will be helpful

**Comment by MSP-Greg** [comment]
`_SSL_get1_peer_certificate` is only available in OpenSSL 3, but Ruby 2.7 should be built with OpenSSL 1.1. What's the output of:
```
ruby -ropenssl -e "puts %Q[\ \ \ Build: #{OpenSSL::OPENSSL_VERSION}\n Runtime: #{OpenSSL::OPENSSL_LIBRARY_VERSION}]"
```

**Comment by ishikajain0411** [comment]
I'm getting this output 

Build: OpenSSL 1.1.1w  11 Sep 2023
 Runtime: OpenSSL 1.1.1w  11 Sep 2023

**Comment by MSP-Greg** [comment]
@ishikajain0411

Thanks.  Your ruby is built and running with OpenSSL 1.1.1, but when Puma is compiled, it's finding the headers for OpenSSL 3.1 first.

We have places in the code that define how that search is done, but it can get messy.

What is the output of `ruby -e "puts RbConfig::CONFIG['configure_args']"`?

**Comment by MSP-Greg** [comment]
@ishikajain0411

Never mind the above.  I didn't notice the Puma version you're using.

You're using Puma 5.6.4.  Please try using Puma 5.6.7.

Using current Puma, this isn't a problem.

**Comment by ishikajain0411** [comment]
after installing the puma version 5.6.7. with the command 
`gem install puma -v '5.6.7' -- --with-opt-include=/usr/local/opt/openssl/include` and then bundle install I'm getting the same above error then I checked in my gem file it is still at 5.6.4
`gem search ^puma$ --remote` and by this i'm getting this  puma (6.4.0 ruby java)

**Comment by jeygeethan** [comment]
This worked for me on macOS using brew for openssl:

`gem install puma -v '5.6.5' -- --with-pkg-config=$(brew --prefix openssl@1.1)/lib/pkgconfig`
