### ISSUE TITLE
fork_worker makes puma hang with debug gem

### ISSUE THREAD

**Issue by Mathieuu** [puma/puma#2796]
**Describe the bug**

Puma application takes 20 seconds to quit when it has two workers configured with fork_worker and the [debug](https://github.com/ruby/debug) gem is loaded. debug becoming the official debug gem in ruby 3.1, it might be a good one to fix.

**Puma config:**

Please copy-paste your Puma config AND your command line options here.

**To Reproduce**

See that repo: https://github.com/Mathieuu/DebugPuma

I scaffold a rails app with `rails new app --api` and [did the following changes](https://github.com/Mathieuu/DebugPuma/commit/ce918532536f062d1ebfa0efc82a94e44f257cd4).

Launch the server with `rails s` then press ctrl+c to exit the process. It hangs for 20 seconds.
Remove `debug` from the gemfile or `fork_worker` from `config/puma.rb` and it exits instantly.

**Comment by dentarg** [comment]
Probably worth asking about this in the debug repo (ruby/debug here on GitHub)

**Comment by nateberkopec** [comment]
Looks like Stan has this under control over the at the `debug` repo.
