### ISSUE TITLE
Test failure `TestIntegrationCluster#test_load_path_includes_extra_deps` 

### ISSUE THREAD

**Issue by pvalena** [puma/puma#2804]
**Describe the bug**
Test `TestIntegrationCluster#test_load_path_includes_extra_deps` fails when building Puma 5.5.2 in Fedora.

**To Reproduce**

When running tests:

Executed like so -- `CI=1 LC_ALL=C.UTF-8 ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'`
```
TestIntegrationCluster#test_load_path_includes_extra_deps [/builddir/build/BUILD/puma-5.5.2/usr/share/gems/gems/puma-5.5.2/test/test_integration_cluster.rb:264]:
Expected /gems\/rdoc-[\d.]+\/lib$/ to match "/usr/lib/ruby\n".
```
TBH I'm not sure what happens here. Let me know if I can debug in some way.

**Desktop (please complete the following information):**
 - OS: Fedora rawhide (buildroot)
 - Puma Version: 5.5.2

**Comment by MSP-Greg** [comment]
Do you see the same thing when you run the tests with `bundle exec rake test`?

**Comment by MSP-Greg** [comment]
Maybe a little explanation.   Puma restarts should function when one's app is updated, or the dependencies in its Gemfile.  You'll notice that the Gemfile has `rdoc`, which isn't required for Puma.  The test failure above is looking for rdoc.

Also, I think that some tests assume that `bundle --config path` is used.  Obviously, some of the tests do not check whether the tests were started with Bundler.  We should skip any that assume that...

**Comment by voxik** [comment]
Just for explanation, on Fedora, we typically execute the test suite without Bundler mainly to reduce the dependencies (e.g. RuboCop, which has huge dependency chain and is not important for downstream). But also, unfortunately, we not always have all dependencies available (localhost).

Nevertheless, this could be the case to reconsider Bundler usage.

**Comment by pvalena** [comment]
> **EDIT:** For testing, could you do something similar to:
> 
> ```shell
> bundle config --local path vendor/bundle
> bundle install --gemfile=Gemfile_no_rubocop
> bundle exec rake test
> ```

Hello,  I kind-of like the idea, so I've tried it.... but I'm not sure I'm what I'm doing wrong.

I've done some modifications to current Rakefile and Gemfile and ended up with:
```
cat > Gemfile <<EOF
gem "json", "~> 2.3"
gem "nio4r", "~> 2.0"
gem "rack"
gem "sd_notify"
EOF
cat Gemfile

cat > Rakefile <<EOF
require "bundler/setup"
require "rake/testtask"
require "rake/extensiontask"
require "rake/javaextensiontask"
require_relative 'lib/puma/detect'
require 'rubygems/package_task'
require 'bundler/gem_tasks'

gemspec = Gem::Specification.load("puma.gemspec")
Gem::PackageTask.new(gemspec).define

file "lib/puma/puma_http11.rb" do |t|
  File.open(t.name, "w") do |f|
    f.puts "RUBY_VERSION =~ /(\d+.\d+)/"
    f.puts 'require "puma/#{$1}/puma_http11"'
  end
end

Rake::TestTask.new(:test)

namespace :test do
  desc "Run all tests"

  task :all => :test
end
EOF
cat Rakefile
```
But I've not been able to load the dependencies, although they're installed:
```
$ bundle install
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run. Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
Could not find gem 'json (~> 2.3)' in locally installed gems.

$ gem list | grep json
json (2.5.1)
```

TBH I don't have much experience with running via bundler.

**Comment by MSP-Greg** [comment]
> Hello, I kind-of like the idea, so I've tried it.... but I'm not sure I'm what I'm doing wrong.

Sorry.  You're not doing anything wrong.  I was just wondering if you're okay with working with bundler.  The file `Gemfile_no_rubocop` doesn't exist yet, and the rake file needs changes.

But, if testing that way would be okay, I can push a PR, maybe you can test from the branch?

**Comment by pvalena** [comment]
> > Hello, I kind-of like the idea, so I've tried it.... but I'm not sure I'm what I'm doing wrong.
> 
> Sorry. You're not doing anything wrong. I was just wondering if you're okay with working with bundler. The file `Gemfile_no_rubocop` doesn't exist yet, and the rake file needs changes.
> 
> But, if testing that way would be okay, I can push a PR, maybe you can test from the branch?

Thanks, that sounds great!

**Comment by dentarg** [comment]
https://github.com/puma/puma/commit/97c7457c8967653861b3dd1b4e844918f97087d0 added support for not installing RuboCop when bundling using the Gemfile in this repo, with `PUMA_NO_RUBOCOP`:

    PUMA_NO_RUBOCOP=1 bundle install

I'm going to close this issue as the tests pass when running them as documented.
