### ISSUE TITLE
Feature request: `on_worker_shutdown` should be able to know how time it has left to clean up / shut down

### ISSUE THREAD

**Issue by machty** [puma/puma#2819]
Heroku has a 30s delay between SIGTERM and SIGKILL, and Puma only runs the `on_worker_shutdown` hook after all requests (including potentially slow ones) have completed. It would be useful if Puma exposed some kind of shutdown_time arg or something to the `on_worker_shutdown` hook so it knew how much time it had to perform any additional slow shutdown operations. 

My use case for this is that I want to more slowly shutdown ActionCable connections spaced out over the remaining time I have to gracefully shutdown the dyno so that the clients don't immediately reconnect all at once and cause a potential autoscsale-up event due to a spike in queueing time. I could also do some client-side work to prevent this, but this would have the most immediately helpful impact.

**Comment by nateberkopec** [comment]
> My use case for this is that I want to more slowly shutdown ActionCable connections spaced out over the remaining time I have

I'm not super familiar with ActionCable, what would the code for this look like?

**Comment by machty** [comment]
@nateberkopec 

This works:

```rb
on_worker_shutdown do
  connections = ActionCable.server.connections
  max_shutdown_time = 20

  # Limit max sleep to 2s to prevent unnecessarily slow shutdown
  sleep_seconds_per_connection = [max_shutdown_time / connections.size.to_f, 2].min
  connections.each do |c|
    # Emulating disconnect behavior here:
    # https://github.com/rails/rails/blob/f95c0b7e96eb36bc3efc0c5beffbb9e84ea664e4/actioncable/lib/action_cable/server/base.rb#L43
    c.close(reason: ActionCable::INTERNAL[:disconnect_reasons][:server_restart])
    sleep sleep_seconds_per_connection
  rescue StandardError => e
    puts "Error while shutting down ActionCable: #{e}"
  end
end
```

**Comment by nateberkopec** [comment]
I think it's better to implement this clientside with random backoff + jitter. Reconnect after a random short time, if that doesn't work try with a time twice longer, then twice again, etc etc.

**Comment by machty** [comment]
I agree it's good to have client-side jitter/backoff for the non-graceful or transient disconnects/outages, but in the case of a graceful downscale (which might actually be somewhat common), relying on clientside reconnect jitter is basically committing to / guaranteeing a small period of downtime that might be happening at a crucial / transactional moment within the app's UI.

But, I can also agree that there probably isn't much demand for this feature at this time, so I'm fine leaving it closed.

If we every reopened, there are the following considerations:

- on_worker_shutdown only fires after all open http requests are handled, which might eat into that shutdown time
- hence, would there be value in a hook that fires earlier? Then again, it would be bad to perform a blocking operation in this hook, so you might want to spin up a thread... but then there are concurrency issues, including: what happens if some of those unfinished HTTP requests spin up new ActionCable connections while you're tearing down ActionCable connections, and how do we await the spun-up thread to complete?

**Comment by brandondrew** [comment]
@machty moving away from Heroku seems like it might be the easiest solution 😄

**Comment by machty** [comment]
@brandondrew just so that I could control how much shutdown time I have?
