### ISSUE TITLE
Implementing strict transport security headers HSTS

### ISSUE THREAD

**Issue by vbnvaidy** [puma/puma#2831]
**Describe the bug**
I would like to know how we can implement or configure the puma webserver to use the HTTP Strict-Transport-Security response header.

**Puma config:**

Please copy-paste your Puma config AND your command line options here.

**To Reproduce**
Please add reproduction steps here.

Your issue will be solved very quickly if you can reproduce it with a "hello world" rack application. To do this, copy this into a file called `hello.ru`:

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma -C <where_your_config_is> hello.ru
```

If you cannot reproduce with a hello world application or other simple application, we will have a lot more difficulty helping you fix your issue, because it may be application-specific and not a bug in Puma at all.  

There is also a Dockerfile available for reproducing Linux-specific issues. To use:

```
$ docker build -f tools/docker/Dockerfile -t puma .
$ docker run -p 9292:9292 -it puma
```

This will help you to create a container that reproduces your issue.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux]
 - Puma Version [e.g. 4.1.1]

**Comment by dentarg** [comment]
This is something you need to to in your app. You can use a rack middleware like https://github.com/spinels/rack-ssl-enforcer

**Comment by vbnvaidy** [comment]
@dentarg thank you
