### ISSUE TITLE
SSL ServerHello should send "session id"

### ISSUE THREAD

**Issue by donv** [puma/puma#2845]
**Describe the bug**

We have set up a Rails server with SSL and peer certificates, and it is working well serving REST requests.  However one client requires us to set a SSL session id, and the log shows that the SSL session id sent in the "ServerHello" message from our application is empty.  I have done a done a ton of searching, but cannot find how to get Ruby/Rails/Puma/OpenSSL to send a "session id" in the "ServerHello" handshake.

Any help greatly appreciated.

**Puma config:**

```ruby
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count
ssl_bind '0.0.0.0', 3000, {
  key: 'key.pem',
  cert: 'cert.pem',
  verify_mode: 'force_peer',
  ca: "cacerts.pem",
}
environment ENV.fetch("RAILS_ENV") { "development" }
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
```

**To Reproduce**

Start the server and make a request.  The "ServerHello" should contain a non-empty "session id".

**Expected behavior**

A "ServerHello" handshake response with a session id.

**Desktop (please complete the following information):**

 - OS: macOS, Linux, and Windows
 - Puma Version 5.6.2 (ruby 3.1.1-p18)

**Comment by MSP-Greg** [comment]
@donv

Thanks for opening the issue.  I think the following has been set since at least v3.0.0.

https://github.com/puma/puma/blob/f0762d1216c825009a5d3d0a13d1d3ec1ff95682/ext/puma_http11/mini_ssl.c#L157

I have noticed this before, but this may be the first issue about it.  I've got a few things that I'd like to finish before this issue.

You could try setting it to `SSL_SESS_CACHE_SERVER`, which is the default.  Not.sure.

**Comment by MSP-Greg** [comment]
@donv

Do you know what protocol is being used?  TLSv1.3 doesn't use session ids.  Although session reuse is currently disabled in Puma, I believe it still sends a session id with TLSv1.2?

**Comment by donv** [comment]
Hi @MSP-Greg !

Thanks for your answer, and thank you for looking into this!  TLSv1.2 is being used, and a session id header is sent, but it is an empty string.

**Comment by donv** [comment]
Hi @MSP-Greg !

We have worked around this issue in our project, so I think we have no immediate need for a fix.

For the secure communication in production, we will put a webserver in front (apache or heroku), and for development we can disable security.

It would be nice if session resumption would work out of the box for TLSv1.3 for future applications.

**Comment by MSP-Greg** [comment]
@donv

Specific to TLSv1.2 reuse, please see PR #2846.  If you can test that branch to see if it fixes your TLSv1.2 issue, it would be appreciated.  One needs to set `ENV['PUMA_REUSE_ID']` to anything before compiling.

Maybe `PUMA_REUSE_ID=true bundle install`...

**Comment by MSP-Greg** [comment]
@dentarg

Re a test, it's tricky to do with OpenSSL, but it can be done with curl or net/http.
```
curl -k -v --tls-max 1.2 -H "Connection: close" https://<uri> https://<uri>
```

When working, the 2nd connection should show a line something like `* SSL re-using session ID`...

**Comment by donv** [comment]
Testing the branch now...

**Comment by donv** [comment]
The test went well!    Hopefully this can be merged and enabled.
