### ISSUE TITLE
Prefix all environment variables with `PUMA_`

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2853]
Currently we're reading `DISABLE_SSL`. We should rename all env variables to read `PUMA_` (except the env variables that are defined by the community: RAILS_MAX_THREADS, probably others I can't think of right now).

**Comment by timrogers** [comment]
👋 I'm up for picking this up, if that's okay? ❤️

**Comment by nateberkopec** [comment]
@timrogers Just checking in, are you still working on this? Do you need assistance?

**Comment by timrogers** [comment]
👋🏻 Yep! I think this issue is mostly discussion and decision rather than actually implementation, so I'll share some thoughts here soon.
