### ISSUE TITLE
Puma 5.5.2 crash in tmp_restart.rb, when connecting a remote debugger

### ISSUE THREAD

**Issue by ths-somebody** [puma/puma#2854]
**Describe the bug**
Puma crashes, when attaching a remote debugger

Workaround: Don't use the tmp_restart plug-in (or place a return in your local file tmp_restart.rb to not disturb others)

➜  ~/Projects/<prj>/web git:(<user>/...) ✗ rails server
=> Booting Puma
=> Rails 5.2.6.2 application starting in development 
=> Run `rails server -h` for more startup options
[99581] Puma starting in cluster mode...
[99581] * Puma version: 5.5.2 (ruby 2.6.9-p207) ("Zawgyi")
[99581] *  Min threads: 1
[99581] *  Max threads: 1
[99581] *  Environment: development
[99581] *   Master PID: 99581
[99581] *      Workers: 1
[99581] *     Restarts: (✔) hot (✔) phased
[99581] * Listening on http://127.0.0.1:3456
[99581] * Listening on http://[::1]:3456
[99581] Use Ctrl-C to stop
[99581] ! WARNING: Detected running cluster mode with 1 worker.
[99581] ! Running Puma in cluster mode with a single worker is often a misconfiguration.
[99581] ! Consider running Puma in single-mode (workers = 0) in order to reduce memory overhead.
[99581] ! Set the `silence_single_worker_warning` option to silence this warning message.
[99581] - Worker 0 (PID: 99588) booted in 0.0s, phase: 0
**/Users/<user>/.rvm/gems/ruby-2.6.9/gems/puma-5.5.2/lib/puma/plugin/tmp_restart.rb:24: [BUG] object allocation during garbage collection phase**
ruby 2.6.9p207 (2021-11-24 revision 67954) [arm64-darwin21]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0015 e:000014 CFUNC  :stat
c:0003 p:0024 s:0010 e:000009 BLOCK  /Users/<user>/.rvm/gems/ruby-2.6.9/gems/puma-5.5.2/lib/puma/plugin/tmp_restart.rb:24
c:0002 p:0035 s:0006 e:000005 BLOCK  /Users/<user>/.rvm/gems/ruby-2.6.9/gems/puma-5.5.2/lib/puma/plugin.rb:68 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/<user>/.rvm/gems/ruby-2.6.9/gems/puma-5.5.2/lib/puma/plugin.rb:68:in `block (2 levels) in fire_background'
/Users/<user>/.rvm/gems/ruby-2.6.9/gems/puma-5.5.2/lib/puma/plugin/tmp_restart.rb:24:in `block in start'
/Users/<user>/.rvm/gems/ruby-2.6.9/gems/puma-5.5.2/lib/puma/plugin/tmp_restart.rb:24:in `stat'

-- Other runtime information -----------------------------------------------

* Loaded script: bin/rails

* Loaded features:

    0 enumerator.so
    1 thread.rb
    .....

Complete feature list (3814 entries) attached a file

[ruby-2022-04-05-090354.ips.zip](https://github.com/puma/puma/files/8416686/ruby-2022-04-05-090354.ips.zip)
[desktop_puma_crash.txt](https://github.com/puma/puma/files/8416689/desktop_puma_crash.txt)

**Puma config:**

threads_count = ENV.fetch('PUMA_MAX_THREADS') { 5 }
threads threads_count, threads_count
port        ENV.fetch('PORT') { 3000 }
environment ENV.fetch('RAILS_ENV') { 'development' }
pidfile ENV.fetch('PIDFILE') { 'tmp/pids/server.pid' }
workers Integer(ENV['PUMA_WORKER_COUNT'] || 2)
worker_timeout ENV.fetch('PUMA_WORKER_TIMEOUT') if ENV['RAILS_ENV'] == 'development'
plugin :tmp_restart

**To Reproduce**
I can only reproduce it on a large project. Sorry.

**Expected behavior**
Puma should not crash

**Desktop (please complete the following information):**
 - OS: MacOS 12.3
 - Puma Version 5.5.2

**Comment by nateberkopec** [comment]
You're crashing inside `File.stat`, so this is actually a Ruby bug (or a problem with your debugger, perhaps).
