### ISSUE TITLE
New build step for verifying ragel

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2858]
Action should:

```
rm ext/puma_http11/http11_parser.c
rm ext/puma_http11/org/jruby/puma/Http11Parser.java

bundle exec rake ragel
```

and then [assert there is no diff against master](https://stackoverflow.com/questions/5139290/how-to-check-if-theres-nothing-to-be-committed-in-the-current-branch)

**Comment by MSP-Greg** [comment]
Too much coding today.  All the Ubuntu jobs are okay, all the macOS jobs fail, and some of the Windows jobs fail.  Even better, same Windows Ruby version (ucrt master) fails in CI, passes locally...

Or, need to show the diff in CI to see how to make cross platform work.
