### ISSUE TITLE
Using default temp DH parameters error setting certificate

### ISSUE THREAD

**Issue by jeetash1** [puma/puma#2865]
$ openssl s_server -cert server.pem -WWW
Enter pass phrase for server.pem:
Using default temp DH parameters
error setting certificate
139644954981696:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: DH PARAMETERS
139644954981696:error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak:../ssl/ssl_rsa.c:310:

**Comment by jeetash1** [comment]
[OpenSSL error when trying to runopenssl s_server -cert server.pem -WWW   ?

**Comment by MSP-Greg** [comment]
Are you using Puma?  Your code is opening a server with openssl...
