### ISSUE TITLE
Puma starts listening to the port before it can handle requests

### ISSUE THREAD

**Issue by alanhala** [puma/puma#2876]
I'm trying to deploy an API to Google Cloud Run and I found something that is causing me some downtime in the deployment process.

When deploying a new version to Cloud Run they basically wait until the container is listening to some port. After that, they consider that the deploy was a success, so they start sending traffic. This is what they mention in their docs:

https://cloud.google.com/run/docs/about-instance-autoscaling#exceed-max
```
...incoming requests can be queued for up to 10 seconds. During this time window, if an instance finishes processing requests, it becomes available to process queued requests. If no instances become available during the window, the request fails with a 429 error code.
```

So the issue that I'm having is that it seems that puma starts listening to the port before it's able to handle requests. Because of that, Cloud Run starts sending requests to the instance and, as there's no response, the service starts failing. Here are some screenshots of the logs:
![image](https://user-images.githubusercontent.com/7353713/168171579-34d7b8fd-96f6-4114-a7d3-1e096d0db447.png)
![image](https://user-images.githubusercontent.com/7353713/168171622-de9d431c-32de-4bc9-acc9-f5277cba741e.png)

Is this expected? I'm not sure how Puma works internally so I don't know if what I'm saying makes sense :/. Is there something I can do to see what's going on between `[3] * Preloading application` and `[3] * Listening on http://0.0.0.0:8080` that is taking so long and it's making the port available for handling requests?

Thanks!

**Comment by dentarg** [comment]
Sounds like a problem that hopefully can be addressed 

Maybe a workaround could be to disable preloading (probably what takes time)

**Comment by ernsheong** [comment]
I'm seeing this as well. Huge pause between `* PID: 2` and `* Listening on http://0.0.0.0:8080`.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/1343284/168715477-7712907c-4c83-4c0d-80bb-ddd5d97390c4.png">

**Comment by alanhala** [comment]
> Sounds like a problem that hopefully can be addressed
> 
> Maybe a workaround could be to disable preloading (probably what takes time)

But wouldn't that impact a lot the memory usage? If each worker is loading the application instead of just preloading it once. I guess what I wanted to verify is if puma starts listening to the port before even being able to respond to requests as it's still preloading the app. Couldn't the `load_and_bind` only load the app, then spawn workers and then finally bind? Does that make sense?

**Comment by ernsheong** [comment]
@alanhala you may want to verify from your Cloud Console logs whether the logs in between `[3] * Preloading application` and `[3] * Listening on http://0.0.0.0:8080` are coming from the same container instance or another container instance which may already be concurrently running and serving requests.

**Comment by alanhala** [comment]
Yep, it's the same instance.

**Comment by alanhala** [comment]
It seems like Cloud Run for some reason is just slow... I compared it with running the same image locally. Here's the diff:

![image](https://user-images.githubusercontent.com/7353713/169118676-4d4bc1ec-39fa-4552-9aa7-87947b0da9fb.png)

```
2022-05-18T18:31:35.966501396Z Starting Kisi API
2022-05-18T18:31:38.955910060Z Rails environment: staging
2022-05-18T18:31:39.463062021Z [14] Puma starting in cluster mode...
2022-05-18T18:31:39.463086853Z [14] * Puma version: 5.6.4 (ruby 3.0.3-p157) ("Birdie's Version")
2022-05-18T18:31:39.463089794Z [14] *  Min threads: 10
2022-05-18T18:31:39.463091962Z [14] *  Max threads: 10
2022-05-18T18:31:39.463094000Z [14] *  Environment: staging
2022-05-18T18:31:39.463096064Z [14] *   Master PID: 14
2022-05-18T18:31:39.463098097Z [14] *      Workers: 2
2022-05-18T18:31:39.463100153Z [14] *     Restarts: (✔) hot (✖) phased
2022-05-18T18:31:39.463102864Z [14] * Preloading application
2022-05-18T18:31:49.018234984Z [14] * Listening on http://0.0.0.0:3000
2022-05-18T18:31:49.018274837Z [14] Use Ctrl-C to stop
2022-05-18T18:31:49.025961957Z [14] - Worker 0 (PID: 46) booted in 0.0s, phase: 0
2022-05-18T18:31:49.027216463Z [14] - Worker 1 (PID: 48) booted in 0.0s, phase: 0
```

I guess we can't do much with that. But looking at this scenario, does it make sense to bind after booting workers?

**Comment by alanhala** [comment]
It seems like Cloud Run for some reason is just slow... I compared it with running the same image locally. Here's the diff:

![image](https://user-images.githubusercontent.com/7353713/169121336-b1f501d3-ee76-451d-a950-926197366d65.png)

```
2022-05-18T18:31:38.955910060Z Rails environment: staging
2022-05-18T18:31:39.463062021Z [14] Puma starting in cluster mode...
2022-05-18T18:31:39.463086853Z [14] * Puma version: 5.6.4 (ruby 3.0.3-p157) ("Birdie's Version")
2022-05-18T18:31:39.463089794Z [14] *  Min threads: 10
2022-05-18T18:31:39.463091962Z [14] *  Max threads: 10
2022-05-18T18:31:39.463094000Z [14] *  Environment: staging
2022-05-18T18:31:39.463096064Z [14] *   Master PID: 14
2022-05-18T18:31:39.463098097Z [14] *      Workers: 2
2022-05-18T18:31:39.463100153Z [14] *     Restarts: (✔) hot (✖) phased
2022-05-18T18:31:39.463102864Z [14] * Preloading application
2022-05-18T18:31:49.018234984Z [14] * Listening on http://0.0.0.0:3000
2022-05-18T18:31:49.018274837Z [14] Use Ctrl-C to stop
2022-05-18T18:31:49.025961957Z [14] - Worker 0 (PID: 46) booted in 0.0s, phase: 0
2022-05-18T18:31:49.027216463Z [14] - Worker 1 (PID: 48) booted in 0.0s, phase: 0
```

I guess we can't do much with that. But looking at this scenario, does it make sense to bind after booting workers?

**Comment by MSP-Greg** [comment]
> It seems like Cloud Run for some reason is just slow...

Actions CI intermittently run very slow, somewhat OS dependent.  It's a PITA.

> does it make sense to bind after booting workers?

This is also affected by the socket backlog, in that client connections are essentially 'queued' while the workers are booting.   But, if the workers take too long, that's not good either.

**Comment by nateberkopec** [comment]
We need to open the socket prior to forking, which means the socket is open for a period of time before the application is booted. I don't think preload will change the behavior you're observing.

I haven't looked at Puma's application boot process in a long time, but maybe we could boot the application before opening the socket if preload is on? In the non-preload case, there's nothing we can do I think.

**Comment by alanhala** [comment]
I've found new stuff. The dockerfile command that I was using was `bundle exec puma -C ./config/puma.rb`. I changed that to `bin/rails server -b 0.0.0.0` and now the preload looks just like in my local computer.
![image](https://user-images.githubusercontent.com/7353713/170101670-e9a45b9b-df54-4caf-9e1c-3ea384daae14.png)

After that change, it seems that now I'm getting more logs... It looks like the problem here is that puma is shutting down right after starting. I'm going through the code to see if I can find the reason, but maybe that's a cloud run problem?

Any ideas on how I can troubleshoot this? Sorry if it's no longer a puma issue!

**Comment by nateberkopec** [comment]
> I'm going through the code to see if I can find the reason, but maybe that's a cloud run problem?

We've had people post about this before. Yes, something in your environment is sending a kill/termination signal.

**Comment by ernsheong** [comment]
FWIW, may want to log an issue to https://issuetracker.google.com/savedsearches/5447537

**Comment by ernsheong** [comment]
Logged https://issuetracker.google.com/issues/233779083

**Comment by dentarg** [comment]
Sounds like this is/was an upstream problem with Cloud Run, so I'll close this.
