### ISSUE TITLE
Time to change to require_relative?

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2902]
Have a branch prepared for a PR, so I thought I'd ask first.

Any reason to not change all `require` statements to `require_relative`?

See https://github.com/ruby/ruby/search?q=require_relative, and https://github.com/puma/puma/pull/2381

Ruby master has now copied all the methods Puma used from `io/wait` to `IO`. I originally started the PR for that, as `io/wait` won't need to be required for Ruby 3.2 and later.  I.think.  I haven't tested it yet, but I think the only methods used in Puma are `wait_readable` and `wait_writable`...

**Comment by nateberkopec** [comment]
Can we avoid breaking CentOS?

**Comment by MSP-Greg** [comment]
> Can we avoid breaking CentOS?

I interpreted #2381 to mean that all ruby files could be loaded with `require_relative`, but any *.so files needed to be loaded with `require`.  We only have one `puma_http11`.

We could use `require_relative`, and if an error is raised, load via `require`...

**Comment by nateberkopec** [comment]
Cool! Full speed ahead then 🚆
