### ISSUE TITLE
Question about thread-safety and disabling multi-threading

### ISSUE THREAD

**Issue by DanielStevenLewis** [puma/puma#2910]
The Puma readme states the following: "Be aware that additionally Puma creates threads on its own for internal purposes (e.g. handling slow clients). So, even if you specify -t 1:1, expect around 7 threads created in your application."

Suppose that my Rails app is not thread-safe, and as such I need to prevent the app from being multi-threaded. Let's say I use Puma and specify `-t 1:1` to try configure this. Is there any thread-safety-related reason for me to be concerned that Puma will still create threads on its own for internal purposes? I think the answer is probably no, but I'm asking here to be sure.

**Comment by DanielStevenLewis** [comment]
I asked this question on GitHub too [here](https://stackoverflow.com/q/73241112/805141).

**Comment by nateberkopec** [comment]
> Is there any thread-safety-related reason for me to be concerned that Puma will still create threads on its own for internal purposes? 

No, these threads don't interact with your app in any way, and only one thread will ever run your application code, ever, with no concurrency.

**Comment by brendon** [comment]
Sorry to jump in on this, but if we go with the default of 3 threads per worker, is it possible to run into thread safety issues? I'm coming from Passenger where it's one worker per application instance. In this case would you advice settings `RAILS_MAX_THREADS` to `1` instead as a safe way to start, or am I misunderstanding the purpose of threading with Puma?

**Comment by dentarg** [comment]
It is possible (for example if your middleware's aren't thread safe, like this https://github.com/tobmatth/rack-ssl-enforcer/pull/105)

1 thread per worker is a safe way to start.

**Comment by brendon** [comment]
Thanks @dentarg, that's good to know. Just checked my custom middleware and luckily they don't declare instance variables.

Still better to err on the side of safety since the current server setup is non-threaded :)
