### ISSUE TITLE
Puma 6 - ThreadPool.new, general issue with 'init' code

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2921]
Looking for opinions.

Currently, the code in Server for ThreadPool 'init' is:

```ruby
@thread_pool = ThreadPool.new(
  thread_name,
  @min_threads,
  @max_threads,
  ::Puma::IOBuffer,
  &method(:process_client)
)

@thread_pool.out_of_band_hook = @options[:out_of_band]
@thread_pool.clean_thread_locals = @options[:clean_thread_locals]
@thread_pool.before_thread_exit_hook = @options[:before_thread_exit]
```

And the 'signature' for `ThreadPool.initialize` is
```
def initialize(name, min, max, *extra, &block)
```

Maybe it's time to change it to the below, allowing all the `@thread_pool.some_attribute = @options[:some_key]` code in Server to be moved to ThreadPool, where it should be:
```ruby
def initialize(name, min, max, opts, *extra, &block)
```

The above is a common pattern in Puma, maybe it's time to review what changes will clean things up in Puma 6.

**Comment by nateberkopec** [comment]
Might as well just make min and max part of opts. Maybe also find a way to get rid of *extra.

So `(name, opts, &block)`
