### ISSUE TITLE
Puma 6 - Configuration constants

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#2922]
Some constants are defined in [`Puma::ConfigDefault`](https://msp-greg.github.io/puma/Puma/ConfigDefault.html), and some are in defined in [`Puma::Const`](https://msp-greg.github.io/puma/Puma/Const.html) (`FIRST_DATA_TIMEOUT`, `PERSISTENT_TIMEOUT`, `MAX_FAST_INLINE`, etc).

One issue involving 'config' is when the default values are added/merged.  This doesn't involve 'normal' CLI use of Puma, but repo's using Puma to run up a server (often for testing) do so by creating a server via `server = Server.new; ...; server.run`.

Wondering about getting all the config constants in one place, and not having any in `Puma::Const`, which has a lot of constants related to HTTP (strings, status codes, etc).

Any thoughts?

Sorry about the maybe self-serving links, they're easy for me to grab...

**Comment by nateberkopec** [comment]
Personally I'd rather just move everything into const.rb. Feels like premature optimization to be worried about the memory overhead of including const.rb, if thats what youre worried about?

**Comment by MSP-Greg** [comment]
No, this isn't an optimization issue.  Three main thoughts.

1. Organizing config constants kind of goes along with adding config options to all classes' initialize methods that need them.  
2. Only have one place in the code that touches a particular config option.  
3. `const.rb` has a lot of items that are only used in `request.rb`, along with config constants and other items.  Maybe split into two or three files, and only load the constants needed by `request.rb` into its namespace?

I wonder whether [Puma::Configuration#puma_default_options](https://github.com/puma/puma/blob/cf973d50fa972534857574fbe71c1d6b5a6a2e78/lib/puma/configuration.rb#L189-L216) should be removed and all the logic moved into the objects that use each key.  It sets two options that are also 'adjusted' in the below:

https://github.com/puma/puma/blob/cf973d50fa972534857574fbe71c1d6b5a6a2e78/lib/puma/server.rb#L94-L95

But, that also means that the code is run every time a new server or thread pool is created, which happens in every worker.  If that's considered a problem, we could also add a class method (like `Server.set_default_options`) to anything that init's with options, and call that in the main process.  That would keep the code with the object (file) that needs the options. and perform the calculation once.  I.think.that.made.sense...

I'll see if I can work on it more this weekend.

**Comment by nateberkopec** [comment]
OK, now I understand. Makes sense.
