### ISSUE TITLE
Skip duplicate action runs

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2929]
New PRs run actions twice, once for PR and once for push trigger. Let's fix that, either via https://github.com/marketplace/actions/skip-duplicate-actions#skip-duplicate-workflow-runs or something else.

**Comment by dentarg** [comment]
>New PRs run actions twice, once for PR and once for push trigger.

I haven't double checked this but I think this is only the case when the PR doesn't come from a fork (although it my run the tests in their fork too)

**Comment by MSP-Greg** [comment]
Actions allows filtering by branch for 'events'.  Two standard events are 'push' and 'pull_request'.

If we filter branches in Actions, it affects both CI in this repo and forks.

Maybe an option is to filter branches on pushes here when the branch matches 'pr/**' or 'pr-*'?

Or, to create a branch here (puma/puma) for a PR, it must start with the above?

I've often run into this where a repo only allows 'push' events to run on active release branches.  One creates a branch in their fork for a PR, and when it's pushed to the fork, CI doesn't run.

Then one has to screw around with rebasing master/main on the PR branch, running CI, then removing the commit(s) from master/main, etc.

**Comment by dentarg** [comment]
I agree, it should continue to be easy to work in a fork

**Comment by nateberkopec** [comment]
Summarizing for the benefit of those who want to contribute, the feature is: 

Using https://github.com/marketplace/actions/skip-duplicate-actions#skip-duplicate-workflow-runs:
1. [ ] Skip duplicate actions
1. [ ] Skip concurrent actions
1. [ ] Skip documentation-only changes using ignored paths
1. [ ] Skip ragel tests if extension directory is not changed
1. [ ] Cancel outdated workflow runs

Contributors can implement one or all of these features.

**Comment by MemunaHaruna** [comment]
> Summarizing for the benefit of those who want to contribute, the feature is:
> 
> Using https://github.com/marketplace/actions/skip-duplicate-actions#skip-duplicate-workflow-runs:
> 
> 1. [ ]  Skip duplicate actions
> 2. [ ]  Skip concurrent actions
> 3. [ ]  Skip documentation-only changes using ignored paths
> 4. [ ]  Skip ragel tests if extension directory is not changed
> 5. [ ]  Cancel outdated workflow runs
> 
> Contributors can implement one or all of these features.

hi @nateberkopec if this is still needed, I'd like to work on it.

**Comment by nateberkopec** [comment]
Hi @MemunaHaruna, as we mention in [CONTRIBUTING.md](https://github.com/puma/puma/blob/master/CONTRIBUTING.md#how-to-contribute), if there's no PR open, it's ready for anyone to contribute! 😄
