### ISSUE TITLE
Does Puma support Array headers?

### ISSUE THREAD

**Issue by dentarg** [puma/puma#2931]
I've added this puma-head-rack-v3 to my conformance tests:

https://github.com/socketry/rack-conform/runs/8246190238?check_suite_focus=true

It failed because you may not be supporting Array headers. Can you check?

_Originally posted by @ioquatix in https://github.com/puma/puma/issues/2927#issuecomment-1240473585_

**Comment by ioquatix** [comment]
Thanks, I've confirmed with this change you are passing the conformance test suite. However, I will be writing additional tests over the next few days which I believe Puma will fail, so I'll touch base once I have done them so we can figure out the right fix.
