### ISSUE TITLE
Make a Codespace for contributing

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2934]
https://github.com/features/codespaces

The key thing will probably be installing Ragel.

**Comment by dentarg** [comment]
I think these are the relevant docs: https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/introduction-to-dev-containers

I was wondering who pays, found this in [the docs](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces) 

> GitHub Codespaces usage is billed for all organization and enterprise accounts on GitHub Team and GitHub Enterprise, which do not include any free minutes or storage. Personal accounts are not currently billed for Codespaces usage.
