### ISSUE TITLE
Uninitialized constant Puma::DSL::DefaultRackup

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [puma/puma#2989]
**Describe the bug**

I tried upgrading one of my production applications, but got the following error:

<details>
  <summary>bundle exec rails server</summary>
  
```bash
config/puma.rb:7:in `_load_from': uninitialized constant Puma::DSL::DefaultRackup (NameError)
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/dsl.rb:131:in `instance_eval'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/dsl.rb:131:in `_load_from'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:235:in `block in load'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:235:in `each'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:235:in `load'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/launcher.rb:54:in `initialize'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/rack/handler/puma.rb:68:in `new'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/rack/handler/puma.rb:68:in `run'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:327:in `start'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in `start'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/zil/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```
</details>

I think this was the default puma config generated with a Rails 5 app initially (4 years ago). I am not familiar what this setting did before, but after going through the upgrade guide I haven't seen any mention of `rackup`. Worked fine with Puma 5.6.5.

**Puma config:**

```ruby
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3020
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end
```

**To Reproduce**

Make `hello.ru`:

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma -C <where_your_config_is> hello.ru
```

**Expected behavior**

Upgrade guide instructions should mention this breaking change.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6, M1 Max
 - Puma Version 6

**Comment by ZilvinasKucinskas** [comment]
So this configuration comes from Heroku blog post - [Deploying Rails Applications with the Puma Web Server](https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#config).

**Comment by shimbaco** [comment]
The `DefaultRackup` has been replaced with [Puma::Configuration::DEFAULTS[:rackup]](https://github.com/puma/puma/blob/32d999708d7019b85b0518c8e0693773b0bd4ff4/lib/puma/configuration.rb#L155) in https://github.com/puma/puma/pull/2928.
If you use the default value (`"config.ru"`) you can simply delete `rackup DefaultRackup` from config I think.

**Comment by nateberkopec** [comment]
@schneems Could you kindly help us w/updating that Heroku blog post?

**Comment by schneems** [comment]
The docs need to work with all puma versions so it will likely have to change to something like:

    rackup  DefaultRackup if defined?(DefaultRackup)

**Comment by schneems** [comment]
I updated the docs

**Comment by nateberkopec** [comment]
🙇 Thanks Schneems!

**Comment by MSP-Greg** [comment]
JFYI, I think `rackup DefaultRackup` was no longer needed as of Puma 3.0.0.  See [configuration.rb from 3.0.0](https://github.com/puma/puma/blob/v3.0.0/lib/puma/configuration.rb#L180).  It was release 25-Feb-2016.

So, 'This line may not be necessary on newer versions of Puma.' is true, but...

**Comment by mobilutz** [comment]
@schneems The second occurrence of `DefaultRackup` does not have the `if` condition in the heroku documentation:

https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#rackup

Not major, just still something that should be aligned I guess.

**Comment by schneems** [comment]
I appreciate the eyes. I updated it and linked to the PR that removed the constant https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#rackup
