### ISSUE TITLE
Gemfile not refreshed between deploys

### ISSUE THREAD

**Issue by Flink** [puma/puma#300]
I think puma have the exact same issue unicorn did as described here: https://github.com/bundler/bundler/wiki/Gem.refresh-to-reload-the-gemfile

Problem appears when deploying using tools such as capistrano and mina, and using phased restarts. When sending an USR1 signal, puma will reload its workers but if Gemfile has changed, new gems won’t be picked up.

**Comment by AleksandrLeontev** [comment]
I have the same problem...

**Comment by itsNikolay** [comment]
I'd been using `prune_bundler` but still has the same issue ^_^

**Comment by xiaoronglv** [comment]
@itsNikolay 

which restart method are you using， normal restart or phased restart？

prune bundler only works in `phased restart` and `do not preload app`

**Comment by mrbrdo** [comment]
I am using prune_bundler with phased-restart, but I get errors when my Gemfile changes, e.g.:
```
/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:34:in `block in setup': You have already activated tzinfo 0.3.42, but your Gemfile requires tzinfo 0.3.43. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
  from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:19:in `setup'
  from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler.rb:122:in `setup'
  from /opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/setup.rb:17:in `<top (required)>'
  from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
...
```
After I stop and start puma it begins working correctly. I start puma itself with `bundle exec` (using the puma jungle init script). I am using rbenv without gemsets. Bundler is setup to install into vendor/bundle (as per usual).

**Comment by araslanov-e** [comment]
@bnorton `ENV["BUNDLE_GEMFILE"]` helped me

**Comment by araslanov-e** [comment]
`bundle update capistrano3-puma` helped me B)

**Comment by mrbrdo** [comment]
this has been working fine for me, but today I set up a new server, using the same Chef script I used with the previous server, however now I cannot boot puma if I use `prune_bundler`. It works fine without that, but with it I get the attached error.
I am using rbenv 0.4.0-146-g7ad01b2 and puma 2.9.0. I also tried `export BUNDLE_GEMFILE=/path/to/Gemfile` before running the command but that did not change anything.

```bash
$ bundle exec puma -C config/puma.rb
* Pruning Bundler environment
/opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'rack' (= 1.5.2) among 9 total gem(s) (Gem::LoadError)
  from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
  from /opt/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
  from /u/apps/myapp_production/current/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/bin/puma-wild:10:in `block in <main>'
  from /u/apps/myapp_production/current/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/bin/puma-wild:8:in `each'
  from /u/apps/myapp_production/current/vendor/bundle/ruby/2.1.0/gems/puma-2.9.0/bin/puma-wild:8:in `<main>'
```

**Comment by mrbrdo** [comment]
It seems like the problem could be related to bundler version (old: `1.7.9` new: `1.9.1`). I checked the changes in rbenv between the two versions and it is basically just a single commit and it's very unlikely it's causing the problem.

**Comment by todd** [comment]
We're also seeing the same issue as @mrbrdo when performing a phased restart. Running Puma 2.11.2, deploying with Capistrano. `prune_bundler` is present in our Puma config. Hot restart works as advertised.

**Comment by marktran** [comment]
If you guys are using Capistrano, make sure the Ruby version defined in your `config/deploy.rb` (e.g. `set :rbenv_ruby, '2.2.2'`) is the same as the version in your `.ruby-version` file.

I ran into an issue the other week where Capistrano was running `bundle install` on a different version of Ruby and my app was booting up in another version.
