### ISSUE TITLE
Old Actions workflows - remove?

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#3019]
When viewing the Puma [Actions tab](https://github.com/puma/puma/actions), there are several old workflows listed.  All have had all logs removed from their runs.  I believe if one deletes the workflow runs, the workflow is removed from the listing.

Does any have a problem with removing the three below workflows?

[CRuby](https://github.com/puma/puma/actions/workflows/cruby.yml) one run 26-Mar-2021
[non-CRuby](https://github.com/puma/puma/actions/workflows/non_cruby.yml) one run 26-Mar-2021
[Puma](https://github.com/puma/puma/actions/workflows/ruby.yml) 28-Nov-2020 latest of two runs

**Comment by dentarg** [comment]
Fine with me, but how do you delete them?

**Comment by MSP-Greg** [comment]
I normally use the Web UI.  If you go to https://github.com/puma/puma/actions/workflows/cruby.yml, there's three 'dots' on the right side of the single workflow line.  Click that, then click `Delete workflow run`.  I believe once a workflow has no runs, it's removed from the list.  I guess we'll see.  I'll wait for more input.  Thanks for yours.

**Comment by MSP-Greg** [comment]
Done

**Comment by MSP-Greg** [comment]
Next workflow in line for deletion would be [Check Changelog](https://github.com/puma/puma/actions/workflows/check_changelog.yml), which has 307 runs.  That's a lot of mouse clicks to delete in the web UI.  I'll see if one can delete the runs using the Github API...
