### ISSUE TITLE
I am running a rails application on heroku and am having starting rails.  The error is in starting puma.

### ISSUE THREAD

**Issue by pkristoff** [puma/puma#3021]
I am running a rails application on heroku and am having starting rails.  The error is in starting puma.  I am not sure whose report this to.

**Describe the bug**
I am running my rails application on heroku.  it is having trouble deploying/running the application.
There is a warning in deploy log:        "Detecting rails configuration failed."

I try to run the application and I get an error starting rails:  /tmp/build_d797a345/vendor/bundle/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require': No such file to load -- RMagick.rb (LoadError)

Traceback:
[startup_traceback.txt](https://github.com/puma/puma/files/10006909/startup_traceback.txt)

Here is the Gemfile:
[Gemfile.txt](https://github.com/puma/puma/files/10006914/Gemfile.txt)

Gemfile.lock
[Gemfile.lock.txt](https://github.com/puma/puma/files/10006913/Gemfile.lock.txt)

As you can see from the Gemfile RMagick should be loaded both directly and
loaded in the dependencies in the Gemfile.lock.
If you cannot help me can you point me to who can?
I tried heroku

**Puma config:**
I am not sure this will be helpful since this is set up for development and the problem is on heroku.
[puma.rb.txt](https://github.com/puma/puma/files/10007119/puma.rb.txt)

**To Reproduce**

deploy on heroku
Please add reproduction steps here.

Your issue will be solved very quickly if you can reproduce it with a "hello world" rack application. To do this, copy this into a file called `hello.ru`:

```
run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

Run it with:

```
bundle exec puma -C <where_your_config_is> hello.ru
```

If you cannot reproduce with a hello world application or other simple application, we will have a lot more difficulty helping you fix your issue, because it may be application-specific and not a bug in Puma at all.  

There is also a Dockerfile available for reproducing Linux-specific issues. To use:

```
$ docker build -f tools/docker/Dockerfile -t puma .
$ docker run -p 9292:9292 -it puma
```

This will help you to create a container that reproduces your issue.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Mac, Linux]
 - Puma Version [e.g. 4.1.1]

**Comment by MSP-Greg** [comment]
`No such file to load -- RMagick.rb`

Sholdn't that be `rmagick.rb`?

**Comment by pkristoff** [comment]
It looks like you are right.  How do I fix it?  This is what I have in my Gemfile:
gem 'rmagick'

From the traceback it is failing in loading the gem dependencies.

**Comment by pkristoff** [comment]
Santosh,

I have fixed the problem.  I had a "require 'RMagick'" for a file.  It had not changed in  years.


Paul

**Comment by MSP-Greg** [comment]
From the repo

2.13.4
RMagick.rb

2.14.0
rmagic.rb

**Comment by pkristoff** [comment]
Something else has changed.  I have been using rmagick for a while, on the order of years.  The file has had 

require 'RMagick'

in it for at least 2 years.  I think it is related to this message I get periodically:

**DEPRECATION WARNING: Initialization autoloaded the constants ApplicationHelper, CandidateImportsHelper, FileHelper, OrphanedsHelper, RegistrationsHelper, DeviseHelper, ApplicationController, and DeviseController.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationHelper, for example,
the expected changes won't be reflected in that stale Module object.

`config.autoloader` is set to `classic`. These autoloaded constants would have been unloaded if `config.autoloader` had been set to `:zeitwerk`.

In order to autoload safely at boot time, please wrap your code in a reloader
callback this way:

    Rails.application.reloader.to_prepare do
      # Autoload classes and modules needed at boot time here.
    end

That block runs when the application boots, and every time there is a reload.
For historical reasons, it may run twice, so it has to be idempotent.

Check the "Autoloading and Reloading Constants" guide to learn more about how
Rails autoloads and reloads.
 (called from <top (required)> at ...**

but I have not investigated it.  It seem to me that case sensitivity stopped being ignored.
