### ISSUE TITLE
New release: `6.0.1`?

### ISSUE THREAD

**Issue by jeffwidman** [puma/puma#3028]
I'd like to upgrade to `6.x` series, but blocked until a release is cut that incorporates:
* https://github.com/puma/puma/issues/2999
* https://github.com/puma/puma/issues/3000

It looks like those have been on `master` for a while, so can you cut a new `6.0.1` release?

Also, I noticed the `6.0` milestone could probably be closed now that it's shipped? 
* https://github.com/puma/puma/milestone/13

**Comment by jeffwidman** [comment]
> Just to clarify, current master works for your app(s)?

You got me--I haven't actually tried it. Here's what I'd commented on our internal Dependabot PR that wanted to bump Puma:
_...I also checked recent issues, and these all have a small chance they may affect us. I didn't want to invest time into digging whether they actually affect us because I figured simplest to wait til 6.0.1 drops..._

I also help maintain a few popular OSS projects, and after experimenting with several release strategies, I've found the most efficient is generally to keep the release process very lightweight and whenever a blocker bug is fixed to quickly cut a new patch release... that way I don't stackup fixes, only to realize after it's out that one fix had an unexpected side effect somewhere else. Better to get feedback quickly, plus hopefully with each release I'm able to reduce the number of users affected by known bugs. Only works if the release process is very lightweight though, otherwise the overhead of cutting a release dominates the process.

But I defer to your judgement, you know this library and it's userbase much better than I do. 😃

**Comment by mockdeep** [comment]
FWIW, we've started seeing a lot more test flake after the upgrade to `6.0.0` and it appears related to the issue with response bodies. I noticed in our test logs that the ActiveRecord query cache wasn't getting cleared after requests in our feature tests, causing stale data to appear in the page. My understanding is that clearing the query cache is attached to Puma closing the response. I'm going to set up a repeat build on our CI to see if `master` fixes the issue.

**Comment by jeffwidman** [comment]
Yes, thanks!
