### ISSUE TITLE
Add `before_worker_boot` config block with clustered mode

### ISSUE THREAD

**Issue by catsby** [puma/puma#303]
From my understanding, preloading your application will boot the application before forking workers. In the case of Rails and ActiveRecord, this will establish a database connection pool. What happens to that pool after fork? Is it shared with the workers? 

One option is to re-establish the connection in an `on_worker_boot` hook, but does it need to call `ActiveRecord::Base.disconnect!` first? 

Unicorn provides a `before_fork` and `after_fork`. On Heroku, it's important to call `disconnect!` in the `before_fork`, or you can easily leak connections and get weird EOF messages. 

So, should users call `disconnect!` and then re-establish in the `on_worker_boot`, or just establish the connection? Or should an equivalent `before_fork` config block be added?

**Comment by nathansamson** [comment]
I think this is actually quit important. I noticed I was "leaking" a database connection per master process today. If you only have very limited connections every one of them should count...

Quoting Heroku's docs
> Multi-process servers
>
> For a forking server such as Unicorn, the master process will boot your rails applications (and execute any initializers) and then fork workers. For this reason it’s necessary to disconnect in your master process in the before_fork and then re-establish the connection in an after_fork block:
