### ISSUE TITLE
Actions - remove Ubuntu 18.04 ?

### ISSUE THREAD

**Issue by MSP-Greg** [puma/puma#3045]
Ubuntu 18.04 is deprecated in Actions.  Ok to remove?

JFYI, Actions/setup-ruby is having issues with Ruby 2.5 and earlier re RubyGems & Bundler.  Fix being discussed.

Happy Holidays!

**Comment by nateberkopec** [comment]
Let's do it 👍 

Happy holidays to you Greg and to all of our Puma contributors!
