### ISSUE TITLE
Using rack 3. Receive deprecation warning.

### ISSUE THREAD

**Issue by mmarvb8h** [puma/puma#3057]
**Describe the bug**
deprecation warning: "Rack::Handler is deprecated and replaced by Rackup::Handler"

Spent a little time to determine the issue. The issue seems to be when rackup.rb requires puma.rb. puma.rb does a require on rack/handler.rb on about line 3. rack/handler.rb throws deprecation warning.

**Expected behavior**
App should start without deprecation warning.

**Desktop (please complete the following information):**
 - OS: Mac M1 arm
 - Puma Version 6.0.2
 - rack version 3.0.3

~Marvin Foster 
email: mmarvb7@gmail.com or marvinfoster@finsync.com

**Comment by dentarg** [comment]
Can you post complete code and steps to reproduce?

**Comment by nateberkopec** [comment]
I'm guessing you just need rack 3+ in the Gemfile or otherwise loaded for this to occur.

**Comment by MSP-Greg** [comment]
I think the issue is when using rack 3 and rackup (rackup was included with rack 2)

See https://github.com/jeremyevans/roda/issues/301#issuecomment-1383273820

When an app is started with the rackup bin file, we're using Rack::Handler, but with rack 3, the namespace is Rackup::Handler.  I.think...

**Comment by MSP-Greg** [comment]
I've got a patch which works when using the rackup bin, but I need to fix the tests...

**Comment by MSP-Greg** [comment]
@mmarvb8h Don't know if you can easily test a PR, but I believe PR #3061 fixes this issue.

**Comment by mmarvb8h** [comment]
Sorry been focused on elsewhere. since all does seem to work. i'm comfortable with warning for now. since i generally use puma anyway i can start puma directly. in order for me to push to a "prod-like" state i needed to verify cause. when pushed fix is verified and released i'll just update puma. thx...
