### ISSUE TITLE
Sinatra stream test fails with Puma master branch

### ISSUE THREAD

**Issue by dentarg** [puma/puma#3085]
Haven't had time to look into this but reporting it so it is not forgotten.

Following #3000, I have over at https://github.com/sinatra/sinatra added different versions of Puma to the CI matrix 

Running the Sinatra tests (using Rack 2) and Puma master branch (a61b0782d7aec250f7d355a7471603abc5837685), one stream test fails: https://github.com/sinatra/sinatra/actions/runs/4235438155/jobs/7359050938#step:5:22

```
  1) Failure:
IntegrationTest#test_with_puma_streams_0 [/home/runner/work/sinatra/sinatra/test/integration_test.rb:39]:
Expected false to be truthy.
```

That test passes with the latest releases of Puma (5.6.5, 6.1.0) so I wonder what has changed.

**Comment by MSP-Greg** [comment]
See https://github.com/sinatra/sinatra/pull/1887

Seems like a small CI & threading related timing issue.  Main change is sleeping for 1.25 instead of 1.2 seconds...

Thanks for adding Puma master to the CI.
