### ISSUE TITLE
Incorrect Rack::RELEASE comparison in test_rack_server.rb

### ISSUE THREAD

**Issue by ron-shinall** [puma/puma#3097]
**Describe the bug**
The `Rack::RELEASE` version comparison for requiring `Rack::Chunked` is incorrect in `test/test_rack_server.rb`. 

If the `Rack::RELEASE` is "3.1" the following evaluates to true and therefore requires rack/chunked when it should not be (as of 3.1):
`require "rack/chunked" if Rack::RELEASE.between?('3', '3.1')`

This was changed in https://github.com/puma/puma/pull/3064

**Expected behavior**
A comparison more like this is what is required:
`require "rack/chunked" if Rack::RELEASE >= '3' && Rack::RELEASE < '3.1'`

**Comment by MSP-Greg** [comment]
@ron-shinall

Thanks.  My mistake.

I'll fix soon with `Rack::RELEASE.start_with? '3.0'`.  For others, no versions of Rack 3.1 have been released, and current master is '3.0.0'.

**Comment by ron-shinall** [comment]
@MSP-Greg Thanks for the quick response! I appreciate your efforts.
