### ISSUE TITLE
Puma server does not serve static files for my app

### ISSUE THREAD

**Issue by ghost** [puma/puma#313]
Hi, I'm trying to deploy a Rails app in 2.3 version using nginx + Puma.

It works fine except I all the requests under my public directory have a 404 as result.
In development occurs the same. Every request for a media asset (js, css, etc) are not working.

Maybe I am forgetting something basic, I'm not expert in this issues. Please, can anybody help me to fix this? I'm looking forward change my Passenger default server to Puma!!

**Comment by hansottowirtz** [comment]
In Rails 5, you can use `RAILS_SERVE_STATIC_FILES=true rails s -e production`.
The key in production.rb is now `config.public_file_server.enabled`.

**Comment by reejosamuel** [comment]
Like to point out, its better to use nginx or sorts to serve static assets rather than make rails do it. Since everything to points to say it is a overhead on rails to serve assets. Also worth mentioning nginx etc manages cache and is meant for this job.
