### ISSUE TITLE
`fork_worker` mode possibly causing Errno::EPIPE: Broken pipe 

### ISSUE THREAD

**Issue by johnnyshields** [puma/puma#3134]
**Describe the bug**

I've recently rolled out Puma 6.2.2. In general, it's behaving well, however, I think `fork_worker` mode may be causing a few `Errno::EPIPE: Broken pipe` on my MongoDB connections (it's coming as `Mongo::Error::SocketError`). I see this about 3-10 times per deploy on an app (tablecheck.com) that's getting 1000+ requests per second.

I suspect this is due to `fork_worker` not draining connections, or not waiting long enough for all web requests to complete.

We will try to reproduce locally.

Here is my `puma.rb`:

```ruby
environment ENV.fetch('RAILS_ENV', 'development')

workers ENV.fetch('WEB_CONCURRENCY', 0).to_i

threads_count = ENV.fetch('RAILS_MAX_THREADS', 5).to_i
threads threads_count, threads_count

bind "tcp://#{ENV.fetch('HTTP_LISTEN_ADDRESS', '0.0.0.0')}:#{ENV.fetch('HTTP_LISTEN_PORT', '9292')}"

raise_exception_on_sigterm false

fork_worker

on_worker_boot do
  ::Mongoid::Clients.clients.each do |_name, client|
    client.close
    client.reconnect
  end
end

before_fork do
  ::Mongoid.disconnect_clients
end
```

**Comment by johnnyshields** [comment]
I am also seeing a few `Redis::CannotConnectError` which might be related.

**Comment by johnnyshields** [comment]
@MSP-Greg do you think your recently added thread pool grace period will help with this?

**Comment by dentarg** [comment]
> @MSP-Greg do you think your recently added thread pool grace period will help with this?

@johnnyshields which PR are you thinking about? maybe you can test? maybe you already have?

**Comment by johnnyshields** [comment]
Issue solved--I wasn't setting the `on_refork` callback 🤦‍♂️. I will raise a PR to update Puma's `fork_worker` documentation to be more clear.

My `puma.rb` now looks like:

```
before_fork do
  ::Mongoid.disconnect_clients
end

on_refork do
  ::Mongoid.disconnect_clients
end

on_worker_boot do
  ::Mongoid.clients.values.each(&:reconnect)
end
```

I've also raised PRs for Mongoid and the Mongo Ruby driver documentation:
- https://github.com/mongodb/mongoid/pull/5808
- https://github.com/mongodb/mongo-ruby-driver/pull/2856
