### ISSUE TITLE
Error: implicit declaration of function 'TLS_method' is invalid (puma 6.3.0, macOS Ventura, M1)

### ISSUE THREAD

**Issue by vrtsev** [puma/puma#3194]
**Describe the bug**
Hi, I am trying to install the v.6.3.0 through the gemfile. The installation fails on the building native extensions step
Here is the console output:
```
Using base_api 0.1.0 from source at `vendor/dependencies/base_api`
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/vriaz/Projects/telapp/tas/vendor/bundle/ruby/2.7.0/gems/puma-6.3.0/ext/puma_http11
/Users/vriaz/.rvm/rubies/ruby-2.7.6/bin/ruby -I /Users/vriaz/.rvm/rubies/ruby-2.7.6/lib/ruby/site_ruby/2.7.0 extconf.rb
--with-cflags\=-fms-extensions
using OpenSSL pkgconfig (openssl.pc)
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_session_cache_mode(NULL, 0) in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version(NULL, 0) in openssl/ssl.h... no
checking for X509_STORE_up_ref()... yes
checking for SSL_CTX_set_ecdh_auto(NULL, 0) in openssl/ssl.h... yes
checking for SSL_CTX_set_dh_auto(NULL, 0) in openssl/ssl.h... no
checking for SSL_get1_peer_certificate() in openssl/ssl.h... no
checking for Random.bytes... yes
creating Makefile

current directory: /Users/vriaz/Projects/telapp/tas/vendor/bundle/ruby/2.7.0/gems/puma-6.3.0/ext/puma_http11
make DESTDIR\= sitearchdir\=./.gem.20230713-30919-14d4awl sitelibdir\=./.gem.20230713-30919-14d4awl clean

current directory: /Users/vriaz/Projects/telapp/tas/vendor/bundle/ruby/2.7.0/gems/puma-6.3.0/ext/puma_http11
make DESTDIR\= sitearchdir\=./.gem.20230713-30919-14d4awl sitelibdir\=./.gem.20230713-30919-14d4awl
compiling http11_parser.c
compiling mini_ssl.c
mini_ssl.c:209:21: error: implicit declaration of function 'TLS_method' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  ctx = SSL_CTX_new(TLS_method());
                    ^
mini_ssl.c:209:21: note: did you mean 'DTLS_method'?
/opt/homebrew/Cellar/openssl@1.0/1.0.2u/include/openssl/ssl.h:2387:19: note: 'DTLS_method' declared here
const SSL_METHOD *DTLS_method(void); /* DTLS 1.0 and 1.2 */
                  ^
mini_ssl.c:209:21: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const SSL_METHOD *' (aka
'const struct ssl_method_st *') [-Wint-conversion]
  ctx = SSL_CTX_new(TLS_method());
                    ^~~~~~~~~~~~
/opt/homebrew/Cellar/openssl@1.0/1.0.2u/include/openssl/ssl.h:2131:40: note: passing argument to parameter 'meth' here
SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);
                                       ^
1 warning and 1 error generated.
make: *** [mini_ssl.o] Error 1

make failed, exit code 2
An error occurred while installing puma (6.3.0), and Bundler cannot continue
```

**Puma config:**
-

**To Reproduce**
-

**Expected behavior**
Gem installs and builds native extensions correctly

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.3.1
 - Puma Version 6.3.0
 - RVM ruby 2.7.6

**Comment by nateberkopec** [comment]
This looks like an issue with the SSL library version you're using.

Previously noted here: https://github.com/puma/puma/discussions/3146

**Comment by nateberkopec** [comment]
Maybe we should be more explicit somewhere that we no longer support OpenSSL 1.0.x (which has been EOL for 3 years now). I think OpenSSL 1.1 should do the trick for you.

**Comment by MSP-Greg** [comment]
In Puma CI, Windows 2.4 is tested with OpenSSL 1.0.2.  I just quickly looked at the Ruby OpenSSL [History.md](https://github.com/ruby/openssl/blob/master/History.md), and it looks like current versions (3.x) are still compatible with OpenSSL 1.0.2.

I'm macOS challenged, so I can't be of much help.

JFYI, I did just get a iMac, but I'm mainly using it to find/fix a bug in a GUI app, so I'm not yet using it for Ruby related work.  Or, I may have some really dumbass macOS questions in the future...

> I think OpenSSL 1.1 should do the trick for you.

Agree.

**Comment by dentarg** [comment]
Hey @MSP-Greg does the following matter?

In 37a3bc66ff351ac4cbc2ca476a247455c5245ad2 (Puma v5.2.0 and forward) `TLS_server_method()` changed to `TLS_method()`

https://github.com/puma/puma/blob/607c3193cab45caa74c966acc676efc96f2b2ae4/ext/puma_http11/mini_ssl.c#L176-L177

https://github.com/puma/puma/blob/99ae85bbbe425d1949f9e8693993499aae02fce4/ext/puma_http11/mini_ssl.c#L214-L216

but the `#ifdef HAVE_TLS_SERVER_METHOD` stayed the same

https://github.com/puma/puma/blob/99ae85bbbe425d1949f9e8693993499aae02fce4/ext/puma_http11/extconf.rb#L36-L37

Should it have changed?

**Comment by dentarg** [comment]
> Should it have changed?

Okay, looking in https://github.com/openssl/openssl it doesn't seem to matter, for tag `OpenSSL_1_0_2u` neither method is found and for tag `OpenSSL_1_1_1` both are found in `ssl/methods.c`.

---

So what's happening here for OP is that when Puma creates the Makefile, OpenSSL 1.1.1 or newer is found? 
...but when it time comes to compile `mini_ssl.c`, openssl 1.0.2u is used (as seen in the logs above)? and that fails

**Comment by dentarg** [comment]
> So what's happening here for OP is that when Puma creates the Makefile, OpenSSL 1.1.1 or newer is found?
> ...but when it time comes to compile `mini_ssl.c`, openssl 1.0.2u is used (as seen in the logs above)? and that fails

Tried to make sense of this but I'm giving up. Feels problems like this (`pkg-config` and the like) have haunted Ruby since forever. 

* Here's a recent one: https://bugs.ruby-lang.org/issues/19778 ("mkmf.rb pkg_config() interaction with RbConfig::CONFIG["cflags"]") Originated from https://github.com/ruby/openssl/issues/650
* https://bugs.ruby-lang.org/issues/14422 "Ruby configuration options should not be reused for gem builds"
* https://bugs.ruby-lang.org/issues/16836 "configure-time LDFLAGS leak into ruby pkg-config file"
* https://bugs.ruby-lang.org/issues/18391 "Error building gems with binary extensions on Ruby 3.1"
* https://bugs.ruby-lang.org/issues/18763 "The configure option “--with-openssl-dir” has lower precedence than pkg-config" (https://github.com/ruby/openssl/pull/486, https://github.com/ruby/openssl/issues/534)
  * this one was the culprit for https://github.com/puma/puma/issues/2839

I would suggest installing Ruby again using https://github.com/rbenv/ruby-build which installs a version of OpenSSL alongside it. That has helped we a lot since I switched to doing that.

Both OpenSSL 1.0.2 and Ruby 2.7 are EoL so I'm closing this issue.
