### ISSUE TITLE
Rendering an Enumerator with Puma > 6

### ISSUE THREAD

**Issue by tomrossi7** [puma/puma#3219]
When upgrading from Puma 5 -> 6, we began receiving an undefined method `to_ary` error:

```
Read: #<NoMethodError: undefined method `to_ary' for #<Enumerator: #<Enumerator::Generator:0x000000011e938568>:each>>
```

We are using this to stream large CSV files while they are being generated. The body being being passed is an Enumerator built from an ActiveRecord collection.

**Comment by dentarg** [comment]
This is not a problem in Puma: https://github.com/puma/puma/issues/3112#issuecomment-1490629940

Are you using Rails? Maybe you are running into https://github.com/rails/rails/commit/017428390115b1f7f7c1366fc60cac1032fd0ed5

**Comment by tomrossi7** [comment]
We were able to fix the issue by using the [ActionController#send_stream method.](https://api.rubyonrails.org/classes/ActionController/Live.html#method-i-send_stream). Previously, we just set the body equal to the enumerator object.

**Comment by cimm** [comment]
We had the same error in Rails 7.1.1, upgrading Rails to 7.1.2 fixed it.
