### ISSUE TITLE
Ability to specify plugins via CLI flags

### ISSUE THREAD

**Issue by segiddins** [puma/puma#3253]
**Is your feature request related to a problem? Please describe.**

I am unable to specify a plugin when launching puma via the CLI, without a config file

**Describe the solution you'd like**

`puma --plugin $plugin_name`

**Describe alternatives you've considered**

Dynamically writing new config files

**Additional context**

N/a

**Comment by MSP-Greg** [comment]
Seems reasonable...

**Comment by nateberkopec** [comment]
I feel like a good way to get your feature request in is to list an alternative you've considered that makes the maintainer go: "ick!"

I'm also in favor, marked as contrib wanted because I feel like the scope here is fairly limited.

**Comment by the-spectator** [comment]
I took a shot at this in https://github.com/puma/puma/pull/3262.
