### ISSUE TITLE
activate_control_app only reutrns "Invalid auth token"

### ISSUE THREAD

**Issue by inspire22** [puma/puma#3257]
**Describe the bug**
activate_control_app only reutrns "Invalid auth token"
puma version 5.6.4

**Puma config:**
```
port 3001
pidfile "/tmp/puma.pid"
state_path "/tmp/puma.state" ##{basedir}
environment `hostname` =~ /everybean/ ? 'development' : 'production'
threads 4, 4
workers 2
preload_app!
activate_control_app 'tcp://127.0.0.1:9293', { auth_token: 'kev124' }
```

Please copy-paste your Puma config AND your command line options here.

**To Reproduce**

`curl -X GET "http://127.0.0.1:9293/stats?secret=kev124"`

returns Invalid auth token
pumactl -S /tmp/puma.state stats DOES work

Thanks for any help!

**Comment by MSP-Greg** [comment]
@inspire22

Try `curl -X GET "http://127.0.0.1:9293/stats?token=kev124"`

**Comment by inspire22** [comment]
Thanks, that works!  Looks like it changed at some point, so various docs online are wrong.  Now that I know where to look, 'view source' on  https://puma.io/puma/Puma/App/Status.html would have helped :)
