### ISSUE TITLE
Auto-terminate the application when it idle and RAM usage exceed some value

### ISSUE THREAD

**Issue by ukolovda** [puma/puma#3260]
**Is your feature request related to a problem? Please describe.**
In Kubernetes environment (and other) RAM usage increases and not reduce. After some time the application (pod) become killed by OOM. If the application process user request, the user got application error.

**Describe the solution you'd like**
I want then the application can close himself when it idle and use much RAM (but before `OOMKilled`). The application will be restarted by Kubernetes, and RAM usage will be smaller. It may check environment variable (i.e. `PUMA_CLOSE_AFTER_IDLE_AND_RAM_EXCEED=500mb` or similar) or setting variable.
This allow do not break user request and terminate working process.

**Describe alternatives you've considered**
Manual check RAM usage and shut down the application when it idle.

**Additional context**
It will be useful in Kubernetes or Docker environment, which can auto-restart terminated worker.

**Comment by dentarg** [comment]
Sounds a bit like https://github.com/puma/puma/pull/3209 (and https://github.com/puma/puma/issues/3228)?

Shutting down based on RAM usage feels like questionable behavior. It will likely not be part of Puma. There's https://github.com/zombocom/puma_worker_killer but please read the README of that project.

**Comment by ukolovda** [comment]
> Sounds a bit like #3209 (and #3228)?
> 
> Shutting down based on RAM usage feels like questionable behavior. It will likely not be part of Puma. There's https://github.com/zombocom/puma_worker_killer but please read the README of that project.

Standard behaviour is: when web-server process some complex user request, it exceeded RAM, and OOM killer terminate it. It can be occured after 100 or 1000 requests, but it happens.
I want terminate (restart) application not in the middle of request processing.

May be, it should be graceful termination. Usual Kubernetes (or simple Nginx) run in balancer mode and send requests only to "live" workers. I want to have some method for safe restarting single worker (simplest case is check that worker is idle, more complex - mark worker as "not live" for complete requests).

If this is too complex, I would be check that current process is idle or disable incoming requests (other processes still works). And then terminate process.

**Comment by nateberkopec** [comment]
You should user `puma-worker-killer` or modify that project to suit your needs. Monitoring memory usage is outside of the scope of Puma.
