### ISSUE TITLE
Puma bundle error with v6.4

### ISSUE THREAD

**Issue by Dragonicity** [puma/puma#3266]
Installing puma 6.4.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /Users/xxx.gem/ruby/3.2.2/gems/puma-6.4.0/ext/puma_http11
/Users/marknelson/.rubies/ruby-3.2.2/bin/ruby extconf.rb
using OpenSSL pkgconfig (openssl.pc)
checking for openssl/bio.h... yes
checking for DTLS_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_session_cache_mode(NULL, 0) in openssl/ssl.h... yes
checking for TLS_server_method() in openssl/ssl.h... yes
checking for SSL_CTX_set_min_proto_version(NULL, 0) in openssl/ssl.h... yes
checking for X509_STORE_up_ref()... yes
checking for SSL_CTX_set_ecdh_auto(NULL, 0) in openssl/ssl.h... yes
checking for SSL_CTX_set_dh_auto(NULL, 0) in openssl/ssl.h... yes
checking for SSL_get1_peer_certificate() in openssl/ssl.h... no
checking for Random.bytes... yes
creating Makefile

current directory: /Users/xxx/.gem/ruby/3.2.2/gems/puma-6.4.0/ext/puma_http11
make DESTDIR= sitearchdir=./.gem.20231025-9688-7uig3e sitelibdir=./.gem.20231025-9688-7uig3e clean

current directory: /Users/xxx/.gem/ruby/3.2.2/gems/puma-6.4.0/ext/puma_http11
make DESTDIR= sitearchdir=./.gem.20231025-9688-7uig3e sitelibdir=./.gem.20231025-9688-7uig3e
compiling http11_parser.c
compiling mini_ssl.c
compiling puma_http11.c
linking shared-object puma/puma_http11.bundle
ld: warning: -multiply_defined is obsolete
ld: Undefined symbols:
_SSL_get1_peer_certificate, referenced from:
_engine_peercert in mini_ssl.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [puma_http11.bundle] Error 1

make failed, exit code 2

My puma.rb file:

```
# This configuration file will be evaluated by Puma. The top-level methods that
# are invoked here are part of Puma's configuration DSL. For more information
# about methods provided by the DSL, see https://puma.io/puma/Puma/DSL.html.

# Puma can serve each request in a thread from an internal thread pool.
# The `threads` method setting takes two numbers: a minimum and maximum.
# Any libraries that use thread pools should be configured to match
# the maximum value specified for Puma. Default is set to 5 threads for minimum
# and maximum; this matches the default thread size of Active Record.
max_threads_count = ENV.fetch("RAILS_MAX_THREADS", 5)
min_threads_count = ENV.fetch("RAILS_MIN_THREADS", max_threads_count)
threads min_threads_count, max_threads_count

# Specifies that the worker count should equal the number of processors in production.
if ENV["RAILS_ENV"] == "production"
  require "concurrent-ruby"
  worker_count = Integer(ENV.fetch("WEB_CONCURRENCY") { Concurrent.physical_processor_count })
  workers worker_count if worker_count > 1
end

# Specifies the `worker_timeout` threshold that Puma will use to wait before
# terminating a worker in development environments.
worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

# Specifies the `port` that Puma will listen on to receive requests; default is 3000.
port ENV.fetch("PORT", 3000)

# Specifies the `environment` that Puma will run in.
environment ENV.fetch("RAILS_ENV", "development")

# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```

**Comment by MSP-Greg** [comment]
@Dragonicity

What's the output of `ruby -e "puts RbConfig::CONFIG['configure_args']"`

I think some macOS installs find `openssl.pc`, but it's not the same OpenSSL version as what's linked to in `RbConfig::CONFIG['configure_args']`.  I can't repo the issue on my mac, not sure why...

**Comment by Dragonicity** [comment]
Sorry for delay in response, different time zone. Output of the above command:

```'--prefix=/Users/xxx/.rubies/ruby-3.2.2' '--with-opt-dir=/opt/homebrew/opt/openssl@1.1:/opt/homebrew/opt/readline:/opt/homebrew/opt/libyaml:/opt/homebrew/opt/gdbm'```

**Comment by MSP-Greg** [comment]
Thanks.  I think I know how to solve this.  Now, the question is how can you test it?

I could build the gem and upload it to a Git repo so you could download it.  Or, I could add a PR with the patch and you could install from the repo?  That would require a bundle install, etc.

Thoughts?

**Comment by MSP-Greg** [comment]
Ok, a gem file is at https://github.com/MSP-Greg/ruby-loco/releases/download/old-ruby/puma-6.4.0.rc3266.gem

Download it, switch to the folder, and run `gem install puma-6.4.0.rc3266.gem`.  Hopefully, it installs...

**Comment by Dragonicity** [comment]
Yes, that works:

Building native extensions. This could take a while...
Successfully installed puma-6.4.0
Parsing documentation for puma-6.4.0
Installing ri documentation for puma-6.4.0
Done installing documentation for puma after 0 seconds
1 gem installed

Thanks for your quick response, and glad this will be resolved for the set of MacOS users this would affect.

**Comment by MSP-Greg** [comment]
Thanks for checking.  I'll do a PR tomorrow, it should be in the next release.

**Comment by lcreid** [comment]
[Possibly unrelated, but posting here for others like me that find this issue.]

I had the following error on a Debian Docker container when doing `bundle install`: `LoadError: libssl.so.1.1: cannot open shared object file: No such file or directory - /app/vendor/bundle/gems/puma-6.4.0/lib/puma/puma_http11.so`. In my case, a `gem pristine puma` solved the problem.
