### ISSUE TITLE
`--idle-timeout` should not shut down entire cluster if any single worker is idle

### ISSUE THREAD

**Issue by bensheldon** [puma/puma#3282]
**Describe the bug**

#3235 was introduced to fix #3228, but now it will shut down the entire cluster if any single worker is idle. This is currently unreleased but staged in [v6.4.1](https://github.com/puma/puma/pull/3261).

For example, `bundle exec puma -C config/puma.rb -w 10 --idle-timeout 10` seems like if the server gets 1 request every 5 seconds (less than the 10 second idle timeout), it will still shutdown. That doesn't seem right.

**Expected behavior**

I would expect that the idle-timeout is applied to the entire cluster. So any request to the cluster as a whole would reset the idle timer.

**Comment by joshuay03** [comment]
Got this up: https://github.com/puma/puma/pull/3283
