### ISSUE TITLE
require puma/dsl not on the top

### ISSUE THREAD

**Issue by SeifESlimene** [puma/puma#3287]
in source file puma/configuration.rb:

      @user_dsl    = DSL.new(@options.user_options, self)
      @file_dsl    = DSL.new(@options.file_options, self)
      @default_dsl = DSL.new(@options.default_options, self)
      
I don't understand how instanciate a DSL class where there is no require 'puma/dsl' on the top where it should be in order to use "DSL" inside the code!

Can someone explain to me how that this works the way it works?

**Comment by dentarg** [comment]
There's a comment

https://github.com/puma/puma/blob/32e011ab9e029c757823efb068358ed255fb7ef4/lib/puma/configuration.rb#L6

**Comment by MSP-Greg** [comment]
I'll remove/fix that.  See issue #2922, which led to PR #2928, which made the EOF require unnecessary.
