### ISSUE TITLE
Error responses written twice

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#3307]
For example, for a parser error:

```
assert_equal "HTTP/1.1 400 Bad Request\r\nConnection: close\r\nContent-Length: 0\r\n\r\n", data
```

doesn't pass, because the actual response is:

```
"HTTP/1.1 400 Bad Request\r\nConnection: close\r\nContent-Length: 0\r\n\r\nHTTP/1.1 400 Bad Request\r\n\r\n"
```

The problem comes from `prepare_response` and `client.write_error` essentially trying to do the same thing. We should fix this overlap of responsbilities.

**Comment by dentarg** [comment]
I'll note that we did discuss this in https://github.com/puma/puma/pull/3094#discussion_r1136573131
