### ISSUE TITLE
NoMethodError: undefined method `release' for Rack:Module error at "rails s" initialization time

### ISSUE THREAD

**Issue by ramrod** [puma/puma#3331]
**Describe the bug**
I'm running the folllowing versions combination, which I believe are the latest on each project, as the time of this post:

Jruby 9.4.5.0 
Rails 7.0.7
Puma 6.4.2

My Gemfile looks like this:

```
source 'https://rubygems.org'
gem 'rails', '7.0.7'
gem 'rake'
group :development, :test do
  gem 'jdbc-sqlite3'
  gem 'activerecord-jdbc-adapter'
end
gem 'puma'
gem 'jruby-openssl'
group :production do
  gem 'activerecord-jdbcmysql-adapter', :platforms => :jruby
end
gem 'rack-cors'
gem 'swagger-docs'
gem 'jruby-memcached'
gem 'statsd-ruby'
gem 'aws-sdk'
gem 'aws-sdk-resources'
gem 'rexml'
gem 'mygemlocal', :path => "../mygemlocal/"
```

When I try to start the server with this command:

`jruby -J-Xmx768m -J-Xms256m script/rails s -p 9292 -e docker RAILS_LOG_LEVEL=debug --trace `

I get the following error:

```
NoMethodError: undefined method `release' for Rack:Module
       <main> at /opt/argo/.bundle/jruby/9.4/gems/puma-6.4.2-java/lib/rack/handler/puma.rb:130
      require at org/jruby/RubyKernel.java:1071
  try_require at /opt/argo/.bundle/jruby/9.4/gems/rack-2.2.8/lib/rack/handler.rb:79
          get at /opt/argo/.bundle/jruby/9.4/gems/rack-2.2.8/lib/rack/handler.rb:18
       <main> at script/rails:7
```
Looks looks like this specific line in the puma code is failing to pull an integer out of Rack.release:

https://github.com/puma/puma/blob/master/lib/rack/handler/puma.rb#L130C1-L131C1

It feels iike it is a bug in the puma codebase, but I am not completely sure what is going on.

What could be the cause? did I miss any configuration? or what would be the best way to troubleshoot it further?

**Puma config:**

I don't think I have any puma configuration. I just install the gem as specified above and did not configure anything for it.

**Desktop (please complete the following information):**
 - OS: 12.7.1
 - Puma Version 6.4.2
- Running on docker desktop 4.6.1

**Comment by MSP-Greg** [comment]
> Looks like this specific line in the puma code is failing to pull an integer out of Rack.release:
```ruby
do_register = Object.const_defined?(:Rack) && Rack.release < '3'
```
I believe the code is testing against a string (`'3'`), which is what `Rack.release` returns.  Not sure what `script/rails` contains.  Possible cause is that `rack.rb` is not loaded?  Whether Puma should be doing so, not sure.

**Comment by dentarg** [comment]
Yes, please share the contents of `script/rails` @ramrod

**Comment by ramrod** [comment]
ok, thanks. This is the content of my script/rails file:

```
#!/usr/bin/env jruby

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rack/handler'
Rack::Handler::WEBrick = Rack::Handler.get(:puma)
require 'rails/commands'
```

the content of the config/boot file that seem to be pulling:

```
require 'rubygems'
# Set up gems listed in the Gemfile.
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)
require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])
```

the content of the config/application that seem to be pulled too:

```
require File.expand_path('../boot', __FILE__)
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "sprockets/railtie"
require "rails/test_unit/railtie"
if defined?(Bundler)
  Bundler.require(*Rails.groups(:assets => %w(development test)))
end
module WebappScheduler
  class Application < Rails::Application
    configFile = File.exists?('./etc/config.yml') ? './etc/config.yml' : 'config.yml'
    MyModule::Config.load(base: configFile, local: "local.yml")
    config.encoding = "utf-8"
    config.filter_parameters += [:password]
    config.active_support.escape_html_entities_in_json = true
    config.action_mailer.default_url_options = {
      :host => "localhost:3000"
    }
  end
end
```
 MyModule::Config.load(base: configFile, local: "local.yml") is just adding a bunch of env variables to a module the app reads once it is running

**Comment by ramrod** [comment]
nevemind, the problem has nothing to do with puma!

I inherited this really old rails app, and after upgrading, we find out this line of code:

Rack::Handler::WEBrick = Rack::Handler.get(:puma)

needs to be changed to:

Rackup::Handler::WEBrick = Rackup::Handler.get(:puma)

Sorry for the confusion

**Comment by ramrod** [comment]
issue related to outdated code, not puma
