### ISSUE TITLE
HttpParserError raised when body (chunk) exceeds 4096 bytes does not end with "\r\n"

### ISSUE THREAD

**Issue by skliew** [puma/puma#3337]
**Describe the bug**
Looking at the change log, 6.4.2 introduced changes to fix https://github.com/advisories/GHSA-c2f4-cvqm-65w2. I am facing an issue however I am not sure if it is a bug or it's exactly what the changes are meant to fix. 
When sending a payload (more than 4096 bytes) to Puma, using `chunked` transfer-encoding, Puma intermittently raises `#<Puma::HttpParserError: maximum size of chunk header exceeded>`. I then tried to see what Puma receives on its end when the exception happens. This happens in a production system but I could also reproduce the problem with a payload as follows:
```
400\r\n # 1024 bytes
data\r\n # 1024 bytes of data followed by "\r\n"
400\r\n # 1024 bytes
data\r\n # 1024 bytes of data followed by "\r\n"
.... # The above repeats until the total number of bytes exceeds 4096 (I used 10000 bytes)
40 
```
The above payload contains valid chunk headers, however it does not end with one.

The above payload isn't complete. The next `read` by Puma would read the remaining data:
```
0\r\n
data\r\n # 1024 bytes of data followed by "\r\n"
...
0\r\n\r\n
```

**To Reproduce**
Using the following `config.ru`:
```
run lambda { |env| [200, {}, ["Hello World"]] }
```
And `config/puma.rb`:
```
port 8080
```

Run application
```
bundle exec puma
```

Run the following script:
```
require 'socket'

def build_data
  data = ''
  while data.size < 10000
    data += "400\r\n"
    data += ('x' * 1024)
    data += "\r\n"
  end
  data += "0\r\n\r\n"
  data
end

def run_test
  header = "GET /gg/2 HTTP/1.1\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n"
  socket = TCPSocket.new('127.0.0.1', 8080)
  data = build_data
  data1 = data[0..7218] # Number here is arbitrary, so that the first chunk of data ends with `40`
  data2 = data[7219..-1] # remaining data
  socket << "#{header}#{data1}"
  socket.flush
  sleep 0.1 # This makes it easier to reproduce the issue, might need to be adjusted
  socket << data2
  socket.flush

  result = socket.read

  puts result
end

run_test

```

**Expected behavior**
Request accepted and no parser error raised.

**Desktop (please complete the following information):**
 - OS: Linux
 - Puma Version: 6.4.2

**Comment by dentarg** [comment]
Have you tried running the reproduction script against another web server? What's the result then?

**Comment by skliew** [comment]
I just tried it with WEBrick and Unicorn, and also a Node.js application using Koa.

Interestingly all of them, they mostly return 200. But intermittently, I'd get a `Connection reset by peer` error at the line doing `socket.read`.
For Unicorn and the Node.js application, when the error `Connection reset by peer` error happens, I see that it still logs the request as being successful, for example `"GET /gg/2 HTTP/1.1" 200 - 0.0006`.

**Comment by MSP-Greg** [comment]
@skliew

See PR #3338, I believe it fixes this issue.  Thanks for reporting it.

**Comment by skliew** [comment]
@MSP-Greg I applied the change in the PR locally (changing `chunk.size` to `line.size`), and the issue no longer happens. Thank you!
