### ISSUE TITLE
undefined method `log_writer' for #<Puma::Launcher on usin plugin :solid_queue in puma

### ISSUE THREAD

**Issue by Moavia-00** [puma/puma#3339]
### (gemfile)
ruby "3.0.3"
gem "rails", "~> 7.0.2", ">= 7.0.2.4
gem "solid_queue", require: true || gem "solid_queue" (tried both)

### puma.rb

max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
min_threads_count = ENV.fetch("RAILS_MIN_THREADS") { max_threads_count }
threads min_threads_count, max_threads_count

worker_timeout 3600 if ENV.fetch("RAILS_ENV", "development") == "development"

port ENV.fetch("PORT") { 3000 }

environment ENV.fetch("RAILS_ENV") { "development" }

pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }

plugin :solid_queue

### Error
/home/moavia/.rvm/gems/ruby-3.0.3/gems/solid_queue-0.1.2/lib/puma/plugin/solid_queue.rb:7:in `start': undefined method `log_writer' for #<Puma::Launcher:0x000055dac33b1ae8 @runner=#<Puma::Single:0x000055dac3512360 @launcher=#<Puma::Launcher:0x000055dac33b1ae8 ...>, @events=#<Puma::Events:0x000055dac2edd710 @formatter=#<Puma::Events::DefaultFormatter:0x000055dac2edc8d8>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x000055dac2ed7e28 @ioerr=#<IO:<STDERR>>, @debug=false>, @hooks={}>, @options=#<Puma::UserFileDefaultOptions:0x000055dac2ebf030 @user_options={:early_hints=>true, :environment=>"development"}, @file_options={:config_files=>["config/puma.rb"], :min_threads=>5, :max_threads=>5, :worker_timeout=>3600, :binds=>["tcp://0.0.0.0:3000"], :environment=>"development", :pidfile=>"tmp/pids/server.pid"}, @default_options={:min_threads=>0, :max_threads=>5, :log_requests=>false, :debug=>false, :binds=>["tcp://0.0.0.0:9292"], :workers=>0, :silence_single_worker_warning=>false, :mode=>:http, :worker_check_interval=>5, :worker_timeout=>60, :worker_boot_timeout=>60, :worker_shutdown_timeout=>30, :worker_culling_strategy=>:youngest, :remote_address=>:socket, :tag=>"rails_acb", :environment=>"development", :rackup=>"config.ru", :logger=>#<IO:<STDOUT>>, :persistent_timeout=>20, :first_data_timeout=>30, :raise_exception_on_sigterm=>true, :max_fast_inline=>10, :io_selector_backend=>:auto, :mutate_stdout_and_stderr_to_sync_on_write=>true, :preload_app=>false}>, @app=nil, @control=nil, @started_at=2024-03-07 01:56:40.02002962 +0500, @wakeup=nil>, @events=#<Puma::Events:0x000055dac2edd710 @formatter=#<Puma::Events::DefaultFormatter:0x000055dac2edc8d8>, @stdout=#<IO:<STDOUT>>, @stderr=#<IO:<STDERR>>, @debug=false, @error_logger=#<Puma::ErrorLogger:0x000055dac2ed7e28 @ioerr=#<IO:<STDERR>>, @debug=false>, @hooks={}>, @argv=["-C", "config/puma.rb", "--early-hints", "-e", "development"], @original_argv=["-C", "config/puma.rb", "--early-hints", "-e", "development"], @config=#<Puma::Configuration:0x000055dac2ed4d90 @options=#<Puma::UserFileDefaultOptions:0x000055dac2ebf030 @user_options={:early_hints=>true, :environment=>"development"}, @file_options={:config_files=>["config/puma.rb"], :min_threads=>5, :max_threads=>5, :worker_timeout=>3600, :binds=>["tcp://0.0.0.0:3000"], :environment=>"development", :pidfile=>"tmp/pids/server.pid"}, @default_options={:min_threads=>0, :max_threads=>5, :log_requests=>false, :debug=>false, :binds=>["tcp://0.0.0.0:9292"], :workers=>0, :silence_single_worker_warning=>false, :mode=>:http, :worker_check_interval=>5, :worker_timeout=>60, :worker_boot_timeout=>60, :worker_shutdown_timeout=>30, :worker_culling_strategy=>:youngest, :remote_address=>:socket, :tag=>"rails_acb", :environment=>"development", :rackup=>"config.ru", :logger=>#<IO:<STDOUT>>, :persistent_timeout=>20, :first_data_timeout=>30, :raise_exception_on_sigterm=>true, :max_fast_inline=>10, :io_selector_backend=>:auto, :mutate_stdout_and_stderr_to_sync_on_write=>true, :preload_app=>false}>, @plugins=#<Puma::PluginLoader:0x000055dac2ebe720 @instances=[#<#<Class:0x000055dac3513a30>:0x000055dac35134b8>]>, @user_dsl=#<Puma::DSL:0x000055dac2ebe1a8 @config=#<Puma::Configuration:0x000055dac2ed4d90 ...>, @options={:early_hints=>true

**Comment by dentarg** [comment]
The issue is not with Puma. I see you have already opened https://github.com/basecamp/solid_queue/issues/165
