### ISSUE TITLE
Windows - Puma compiled without ssl support

### ISSUE THREAD

**Issue by fedorzajac** [puma/puma#3369]
**Describe the bug**
Cant compile puma with ssl on windows. Did try almost everithing on the internet, but there is mainly only one path line such as:

- uninstall puma
- install ssl
- install puma

**To Reproduce**

```
PS C:\Users\fedor\Documents\sf-devops-portal> ruby -rpuma -e "puts Puma.ssl?"
false
PS C:\Users\fedor\Documents\sf-devops-portal> openssl version
OpenSSL 3.2.1 30 Jan 2024 (Library: OpenSSL 3.2.1 30 Jan 2024)
PS C:\Users\fedor\Documents\sf-devops-portal> openssl version -d
OPENSSLDIR: "C:\Program Files\Common Files\SSL"
PS C:\Users\fedor\Documents\sf-devops-portal> gem install puma -- --with-openssl-dir="C:\Program Files\Common Files\SSL"
Using rubygems directory: C:/Users/fedor/.local/share/gem/ruby/3.1.0
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions with: '--with-openssl-dir=C:\Program Files\Common Files\SSL'
This could take a while...
Successfully installed puma-6.4.2
Parsing documentation for puma-6.4.2
Done installing documentation for puma after 1 seconds
1 gem installed
PS C:\Users\fedor\Documents\sf-devops-portal> ruby -rpuma -e "puts Puma.ssl?"
false
PS C:\Users\fedor\Documents\sf-devops-portal> gem uninstall puma
Successfully uninstalled puma-6.4.2
PS C:\Users\fedor\Documents\sf-devops-portal> ruby -rpuma -e "puts Puma.ssl?"
false
PS C:\Users\fedor\Documents\sf-devops-portal> gem install puma -- --with-openssl-dir="C:\Program Files\Common Files\SSL"
Fetching puma-6.4.2.gem
Using rubygems directory: C:/Users/fedor/.local/share/gem/ruby/3.1.0
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions with: '--with-openssl-dir=C:\Program Files\Common Files\SSL'
This could take a while...
Successfully installed puma-6.4.2
Parsing documentation for puma-6.4.2
Installing ri documentation for puma-6.4.2
Done installing documentation for puma after 2 seconds
1 gem installed
PS C:\Users\fedor\Documents\sf-devops-portal> ruby -rpuma -e "puts Puma.ssl?"
false
```

**Expected behavior**

`ruby -rpuma -e "puts Puma.ssl?" => true`

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Puma Version [latest?]

what I am doing wrong? please help. Thank you.

**Comment by MSP-Greg** [comment]
This is a bit messy.

You appear to be using a RubyInstaller2 Ruby 3.1.x, and that Ruby is the last to use OpenSSL 1.1.1.  You can check it with the following:
```
ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION"
```
The output should be two lines, both should be the same 'basic' OpenSSL version.  In your case, both lines should be
```
OpenSSL 1.1.1t  7 Feb 2023
```
So, two points:

* Use an OpenSSL package that matches the 'base' version of OpenSSL that Ruby was built with.  In your case, that's OpenSSL 1.1.1.
* Use an OpenSSL package that was built with same build tools as your Ruby.  Your Ruby was built with MSYS2 UCRT64 tools.  JFYI, Ruby can be built with MSYS2 UCRT64, MSYS2 MINGW64, or MSWIN UCRT.

The current MSYS2 OpenSSL is version 3.2.1, so you need to manually download the package:
https://github.com/oneclick/rubyinstaller2-packages/releases/download/ci.ri2/mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst
https://github.com/oneclick/rubyinstaller2-packages/releases/download/ci.ri2/mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst.sig

Place both of the above in a folder without spaces, then run the following:
```
ridk exec pacman -U <folder>/mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst
```

After installing the correct OpenSSL package, you should be able to install Puma.  Remove the `--with-openssl-dir` argument from your gem install command.

**Comment by fedorzajac** [comment]
Thank you for the answer, I will definitely check it out and let you know.

**Comment by MSP-Greg** [comment]
You're welcome.  I'm 'involved' with 'Windows Ruby', which has nothing to do with my involvement with Puma.

I'm pretty sure it should work for you.

I have built a 1.1.1.w package locally.  If you'd like that, I could upload it somewhere.  You'd need to add my signing key to your MSYS2 install (or you could temporarily disable the signing key check).

I just used it to build & test Ruby 3.1.4, and all ssl tests passed (with Puma master)...

I think the last official MSYS2 build was 1.1.1.s, see https://repo.msys2.org/mingw/ucrt64/

**Comment by fedorzajac** [comment]
Yes, that would be great, many thanks!

**Comment by MSP-Greg** [comment]
See https://github.com/MSP-Greg/ruby-loco/releases/tag/old-ruby

**Comment by MSP-Greg** [comment]
@fedorzajac

Wondering if you've had a chance to see if 1.1.1w works?

**Comment by fedorzajac** [comment]
@MSP-Greg hi, yes, thank you very much, it worked well.

**Comment by adeherdt-r7** [comment]
Hey,

I am running into the exact same problem, but I am unable to install the packages mentioned here: https://github.com/puma/puma/issues/3369#issuecomment-2051785290

I've downloaded them as instructured, but `pacman` refuses to add the key, or rather fails:
```
PS C:\windows\system32> ridk exec pacman -U C:\Users\adeherdt\Downloads\mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst
loading packages...
:: Import PGP key F98B8484BE8BF1C5? [Y/n] Y
error: key "F98B8484BE8BF1C5" could not be looked up remotely
error: required key missing from keyring
error: 'C:\Users\adeherdt\Downloads\mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst': unexpected error
```

which blocks me from installing them.
pgp itself however can find the key:
```
PS C:\windows\system32> ridk exec gpg -v --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F98B8484BE8BF1C5
gpg: enabled compatibility flags:
gpg: data source: http://185.125.188.26:80
gpg: armor header: Comment: Hostname:
gpg: armor header: Version: Hockeypuck 2.2
gpg: key F98B8484BE8BF1C5: number of dropped non-self-signatures: 1
gpg: pub  rsa2048/F98B8484BE8BF1C5 2017-06-17  appveyor ri2 package signing key
gpg: no running keyboxd - starting '/usr/lib/gnupg/keyboxd'
gpg: waiting for the keyboxd to come up ... (5s)
gpg: connection to the keyboxd established
gpg: /home/adeherdt/.gnupg/trustdb.gpg: trustdb created
gpg: using pgp trust model
gpg: key F98B8484BE8BF1C5: public key "appveyor ri2 package signing key" imported
gpg: no running gpg-agent - starting '/usr/bin/gpg-agent'
gpg: waiting for the agent to come up ... (5s)
gpg: connection to the agent established
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by MSP-Greg** [comment]
@adeherdt-r7

Does EventMachine also install?

**Comment by adeherdt-r7** [comment]
> @adeherdt-r7
> 
> Does EventMachine also install?

Does now:

```
ruby -rpuma -e "puts Puma.ssl?"
=> true

ruby -reventmachine -ve "puts EM.library_type, EM.ssl?"
=> ruby 3.1.6p260 (2024-05-29 revision a777087be6) [x64-mingw-ucrt]
   Extension
   True 
```

Initial packages were corrupted, so downloading them again and running the installer worked.
Just lost soo much time on this.....
Documented it for the future developer.
At least I can drop all this when we're on Ruby 3.2+

**Comment by MSP-Greg** [comment]
Yes, I wrote most of the code that does this switching for GHA/setup-ruby, and it's a PITA. Some package managers will allow installing multiple versions.  Pacman and vcpkg will not...

**Comment by adeherdt-r7** [comment]
You have my utmost respect for dealing with that.

**Comment by oneminuteman** [comment]
> This is a bit messy.
> 
> You appear to be using a RubyInstaller2 Ruby 3.1.x, and that Ruby is the last to use OpenSSL 1.1.1. You can check it with the following:
> 
> ```
> ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION"
> ```
> 
> The output should be two lines, both should be the same 'basic' OpenSSL version. In your case, both lines should be
> 
> ```
> OpenSSL 1.1.1t  7 Feb 2023
> ```
> 
> So, two points:
> 
> * Use an OpenSSL package that matches the 'base' version of OpenSSL that Ruby was built with.  In your case, that's OpenSSL 1.1.1.
> * Use an OpenSSL package that was built with same build tools as your Ruby.  Your Ruby was built with MSYS2 UCRT64 tools.  JFYI, Ruby can be built with MSYS2 UCRT64, MSYS2 MINGW64, or MSWIN UCRT.
> 
> The current MSYS2 OpenSSL is version 3.2.1, so you need to manually download the package: https://github.com/oneclick/rubyinstaller2-packages/releases/download/ci.ri2/mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst https://github.com/oneclick/rubyinstaller2-packages/releases/download/ci.ri2/mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst.sig
> 
> Place both of the above in a folder without spaces, then run the following:
> 
> ```
> ridk exec pacman -U <folder>/mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zst
> ```
> 
> After installing the correct OpenSSL package, you should be able to install Puma. Remove the `--with-openssl-dir` argument from your gem install command.
> 
> **EDIT**: If you want to use OpenSSL 3, install Ruby 3.2 or 3.3. For those Rubies, the command to install the package is:
> 
> ```
> ridk exec pacman -S mingw-w64-ucrt-x86_64-openssl
> ```

C:\>ridk exec pacman -U Users\Hp\Downloads\mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zs
loading packages...
error: 'Users\Hp\Downloads\mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zs': could not find or read package I HAVE NOT BEEN ABLE TO INSTALL KINDLY HELP

**Comment by MSP-Greg** [comment]
@oneminuteman

Can you please post the output of:
```text
ruby -ropenssl -ve "puts OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION"
```
Should be three lines.

**Comment by MSP-Greg** [comment]
@oneminuteman

Forgot to mention:
> C:>ridk exec pacman -U Users\Hp\Downloads\mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zs
loading packages...
error: 'Users\Hp\Downloads\mingw-w64-ucrt-x86_64-openssl-1.1.1.t-1-any.pkg.tar.zs': could not find or read package I HAVE NOT BEEN ABLE TO INSTALL KINDLY HELP

Wrong file extension.  You show `.zs`, it should be `.zst`
