### ISSUE TITLE
windows 8 64bit 

### ISSUE THREAD

**Issue by donamk** [puma/puma#341]
Test on Windows 8 64bit + ruby 2.0.0p195 (2013-05-14) [x64-mingw32]

D:>gem install puma
Fetching: puma-2.4.0.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
ERROR: Failed to build gem native extension.

D:/Programs/Ruby200-x64/bin/ruby.exe extconf.rb

creating Makefile

make
generating puma_http11-x64-mingw32.def
compiling http11_parser.c
ext/http11/http11_parser.rl: In function 'puma_parser_execute':
ext/http11/http11_parser.rl:111:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

compiling io_buffer.c
io_buffer.c: In function 'buf_to_str':
io_buffer.c:118:3: warning: pointer targets in passing argument 1 of 'rb_str_new' differ in signedness [-Wpointer-sign]
In file included from d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby/ruby.h:1567:0,
                 from d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby.h:33,
                 from io_buffer.c:1:
d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby/intern.h:668:7: note: expected 'const char *' but argument is of type 'uint8_t *'

compiling mini_ssl.c
In file included from mini_ssl.c:2:0:
d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby/backward/rubyio.h:2:2: warning:
# warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]

mini_ssl.c:3:25: fatal error: openssl/bio.h: No such file or directory
compilation terminated.
make: **\* [mini_ssl.o] Error 1

Gem files will remain installed in D:/Programs/Ruby200-x64/lib/ruby/gems/2.0.0/gems/puma-2.4.0 for inspection.
Results logged to D:/Programs/Ruby200-x64/lib/ruby/gems/2.0.0/gems/puma-2.4.0/ext/puma_http11/gem_make.out
# gem_make.out 

D:/Programs/Ruby200-x64/bin/ruby.exe extconf.rb
creating Makefile

make
generating puma_http11-x64-mingw32.def
compiling http11_parser.c
ext/http11/http11_parser.rl: In function 'puma_parser_execute':
ext/http11/http11_parser.rl:111:3: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
compiling io_buffer.c
io_buffer.c: In function 'buf_to_str':
io_buffer.c:118:3: warning: pointer targets in passing argument 1 of 'rb_str_new' differ in signedness [-Wpointer-sign]
In file included from d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby/ruby.h:1567:0,
                 from d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby.h:33,
                 from io_buffer.c:1:
d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby/intern.h:668:7: note: expected 'const char _' but argument is of type 'uint8_t *'
compiling mini_ssl.c
In file included from mini_ssl.c:2:0:
d:/Programs/Ruby200-x64/include/ruby-2.0.0/ruby/backward/rubyio.h:2:2: warning: #warning use "ruby/io.h" instead of "rubyio.h" [-Wcpp]
mini_ssl.c:3:25: fatal error: openssl/bio.h: No such file or directory
compilation terminated.
make: *_\* [mini_ssl.o] Error 1

**Comment by gihdz** [comment]
Following your instructions it got me into this:

gem install puma --platform=ruby -- --with-opt-dir=C:/Knapsack/x86-windows
Building native extensions with: '--with-opt-dir=C:/Knapsack/x86-windows'
This could take a while...
ERROR:  Error installing puma:
        ERROR: Failed to build gem native extension.

    C:/row/Ruby21/bin/ruby.exe -r ./siteconf20150202-6560-i9u6l7.rb extconf.rb --with-opt-dir=C:/Knapsack/x86-windows
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
creating Makefile

make "DESTDIR=" clean
process_begin: CreateProcess(NULL, rm -f, ...) failed.
make (e=2): The system cannot find the file specified.

make: [clean-static] Error 2 (ignored)
process_begin: CreateProcess(NULL, rm -f puma_http11.so *.o *.bak mkmf.log puma_
http11-i386-mingw32.def .*.time, ...) failed.
make (e=2): The system cannot find the file specified.

make: [clean] Error 2 (ignored)

make "DESTDIR="
generating puma_http11-i386-mingw32.def
The system cannot find the path specified.
make: *** [puma_http11-i386-mingw32.def] Error 1

make failed, exit code 2

Gem files will remain installed in C:/row/Ruby21/lib/ruby/gems/2.1.0/gems/puma-2
.11.0 for inspection.
Results logged to C:/row/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0
/puma-2.11.0/gem_make.out


Any way i can solve this??

Regards

**Comment by luislavena** [comment]
```
C:/row/Ruby21/bin/ruby.exe -r ./siteconf20150202-6560-i9u6l7.rb extconf.rb --with-opt-dir=C:/Knapsack/x86-windows
```

Looks like you have RubyGems 2.4.x, which is broken for Windows.

Downgrade to 2.3.0 or 2.2.x to correct this.

**Comment by gihdz** [comment]
I had RubyGems 2.4.5. Tried to install puma with 2.3.0 and 2.2.2 versions; got the same error for both versions!.

I have windows 8 as OS, but using 2.1.5 x86 version of ruby, as well as development kit. Might the ruby version be broken as well?

**Comment by gihdz** [comment]
@luislavena it worked! Just re-installed ruby 2.1.5 x86, rubygems 2.3.0 and everything worked fine! Thanks!

Regards.

**Comment by Bogeyduffer** [comment]
This is great! I spent the last two day trying to get this to install. With your help it worked in just a few minutes. Thanks!  I wish I'd found this two days ago.
