### ISSUE TITLE
Marking C-extension as Ractor-safe

### ISSUE THREAD

**Issue by mohamedhafez** [puma/puma#3422]
According [this part of this Ruby Kaigi talk back in 2020](https://youtu.be/281YdMYRAsk?t=700), the Puma C-extention is already safe to run in parallel. If this is still accurate, could the C-extension be marked at Ractor-safe with `rb_ext_ractor_safe(true)`? I'm personally interested in that because that will allow future versions of TruffleRuby to run Puma with true thread parallelization, but also it'll be beneficial to all users once Ractors are promoted from being just an experimental feature.

**Comment by eregon** [comment]
Yes, this should be fine, [the extension](https://github.com/puma/puma/blob/master/ext/puma_http11/puma_http11.c) doesn't seem to have any mutable global state, and it's been run without the C extension lock on TruffleRuby many times successfully.
Could you make a PR?
