### ISSUE TITLE
Option to turn off Systemd integration

### ISSUE THREAD

**Issue by mohamedhafez** [puma/puma#3424]
So in https://github.com/puma/puma/blob/a7e3d944fa66bbba355abb9efed8ce53048c7e7c/lib/puma/launcher.rb#L65-L67 we load the Systemd integration if the `NOTIFY_SOCKET` is set.

It would be great to have the option to opt out of this, say if `ENV["PUMA_SKIP_SYSTEMD"]` is set. 

In my case I'd like this because in one of my background daemons, I run Puma in a thread with `Rack::Handler::Puma.run` just as an interface to the daemon. However, since the daemon does way more that Puma doesn't know about, I deal with systemd integration elsewhere in that daemon. Currently I'm just monkeypatching the lines above to turn off the automatic Puma integration.

**Comment by dentarg** [comment]
Makes sense to me 👍🏻
