### ISSUE TITLE
Use `available_processor_count` as worker numbers if `WEB_CONCURRENCY` is set to `"auto"`

### ISSUE THREAD

**Issue by rafaelfranca** [puma/puma#3437]
**Is your feature request related to a problem? Please describe.**
We are trying to make easier for applications to configure better defaults to puma in Rails. One of the features we introduced in our configuration was to automatically detect the number of processors and set that as the worker count.

We later had to revert that change because some platforms lie about how many processors they provide to users. So instead we defined a new value to `WEB_CONCURRENCY` that is `"auto"`.

We had to rever that change because puma is also reading the value of that variable and that would just explode trying to parsing it that.

See https://github.com/rails/rails/commit/142e6ab2c1e3cb7df4b82e20e2a1cd676b755714

**Describe the solution you'd like**
Now that puma is taking care of reading `WEB_CONCURRENCY`, I think it would make sense to puma to implement the `"auto"` feature. This would allow Rails and non-Rails users to get better default without having to change the puma.rb file with conditionals.

**Describe alternatives you've considered**
Rails could introduce a new variable to control the concurrency of puma, but I think that would provide worse experience since people are already used with `WEB_CONCURRENCY`.

**Comment by MSP-Greg** [comment]
Seems reasonable.

Currently, code is:
```ruby

workers = ENV['WEB_CONCURRENCY']
```

Is the following what you'd like it updated to?
```ruby
workers =
  if (t = ENV['WEB_CONCURRENCY']) == 'auto' && defined?(::Concurrent)
    Concurrent.available_processor_count
  else
    t
  end
```

**Comment by rafaelfranca** [comment]
Yes!

**Comment by ioquatix** [comment]
Why don't you use `Etc.nprocessors`? No external dependency required.

**Comment by dentarg** [comment]
Why doesn't Rails?

(maybe this? https://github.com/rails/rails/commit/f719787c582839fd2fcd886d70b43da3ddad2ceb)

**Comment by ioquatix** [comment]
Actually I don't know the answer to that, but I suppose IMHO, if `Etc.nprocessors` is not doing the right thing, maybe we should fix that in CRuby... it seems a bit weird if it doesn't work correctly.

**Comment by rafaelfranca** [comment]
It doesn't take in consideration cpu quotas, also JRuby, but yeah, that might be enough. The way the PR was implemented doesn't force the dependency, but if you have use it
