### ISSUE TITLE
Test failiures (certificate has expired)

### ISSUE THREAD

**Issue by fkobi** [puma/puma#3489]
**Describe the bug**
During running the test phase of puma some tests fail:
```
Errors & Failures:

  1) Failure:
TestPumaServerSSLWithCertPemAndKeyPem#test_server_ssl_with_cert_pem_and_key_pem [test/test_puma_server_ssl.rb:503]:
Expected #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=127.0.0.1:43983 state=error: certificate verify failed (certificate has expired)> to be nil.

  2) Failure:
TestExampleCertExpiration#test_certs_not_expired [test/test_example_cert_expiration.rb:40]:
Cert puma/cert_puma.pem has expired. Check the puma for a `.rb` with instructions on how to regenerate.

  3) Failure:
TestPumaServerSSLClient#test_verify_client_cert [test/test_puma_server_ssl.rb:348]:
SSL_connect returned=1 errno=0 peeraddr=127.0.0.1:44507 state=error: certificate verify failed 
(certificate has expired).
Expected: false
  Actual: true

  4) Failure:
TestPumaServerSSLClient#test_verify_fail_if_client_expired_cert [test/test_puma_server_ssl.rb:3
38]:
--- expected
+++ actual
@@ -1 +1,3 @@
-"/DC=net/DC=puma/CN=localhost"
+# encoding: ASCII-8BIT
+#    valid: true
+"/DC=net/DC=puma/CN=CA"
```

**To Reproduce**
Run the test siute

**Expected behavior**
Tests pass, like with 6.3.1

**System info:**
 - OS: Gentoo Linux 2.15, `amd64/23.0/no-multilib/hardened`
 - Puma Version: 6.4.2

**Also see**
https://bugs.gentoo.org/939786

**Comment by dentarg** [comment]
This has been fixed in the master branch

**Comment by Segaja** [comment]
@dentarg is there any chance to get a release which includes this fix?

Right now this is causing issues when trying to build the [ruby-puma](https://archlinux.org/packages/extra/x86_64/ruby-puma/) package for Arch Linux

**Comment by dentarg** [comment]
I'm not the one doing releases. If you want to help out, you can continue on https://github.com/puma/puma/pull/3409 as it's been more changes added since it was lasted updated, I think.
