### ISSUE TITLE
Puma merges request headers together by overwriting

### ISSUE THREAD

**Issue by jamiestrachan-shopify** [puma/puma#3502]
**Describe the bug**
Puma appears to be merging request headers with dash and underscore together, by overwriting.
This seems to pick one at random.

For example, the request headers `X_MYHEADER:1` and `X-MYHEADER:2` will result in only `HTTP_X_MYHEADER = 2` in the handler environment.

This bug has some interesting, possibly serious implications, such as being able to override headers set by a load balancer merely by including a similar header in the http request.

**Puma config:**
This config creates an app that simply echoes back the request headers that start with `HTTP_X`:
```
# frozen_string_literal: true

# Extract "X_" headers and print one per line
def headers(env)
  env.filter { |k, _| k.upcase.start_with?("HTTP_X") }.map{ |k,v| "#{k}: #{v}" }.join("\n")
end

App = ->(e) { [200, { "content-type" => "text/plain" }, [headers(e)]] }

run App
```

Command line:
```
rackup
```

**To Reproduce**
* Run rackup
* Post a request with curl that contains similar headers, such as `X-MyHeader` and `X_MyHeader`
* Observe the response only contains one header value.

Examples:
* underscore first:
```
curl localhost:9292 -H "X_MyHeader: false" -H "x-myheader: true"

HTTP_X_MYHEADER: true
```

* dash first:
```
curl localhost:9292 -H "X-MyHeader: false" -H "x_myheader: true"

HTTP_X_MYHEADER: false
```

* what is even happening here:
```
curl localhost:9292 -H "X_My-Header: false" -H "x_my_header: true"

HTTP_X_MY_HEADER: true


curl localhost:9292 -H "X_My-Header: false" -H "x_my_header: true" -H "X-my-header: filenotfound"

HTTP_X_MY_HEADER: filenotfound
```

* anti-example showing two headers with different casing
```
curl localhost:9292 -H "X_MyHeader: false" -H "x_myheader: true"

HTTP_X_MYHEADER: false, true
```

**Expected behavior**
I should probably expect the headers to be combined as if they both contained underscore, as in the anti-example.

**Desktop (please complete the following information):**
 - Puma Version 6.4.3

**Workaround**
Don't use any dashes or underscores in your header names!

**Comment by MSP-Greg** [comment]
I don't think Puma 4 is supported anymore.

**Comment by jamiestrachan-shopify** [comment]
Whoops.  Just checked my gemfile, it's 6.4.3. Updating...

**Comment by MSP-Greg** [comment]
I think the idea is that if both hyphen and underscore headers exist, the underscore is ignored.  I'd have to test, but if one or the other exist, they are treated as correct.

**Comment by dentarg** [comment]
See https://github.com/puma/puma/security/advisories/GHSA-9hf4-67fc-4vf4

> v6.4.3/v5.6.9 now discards any headers using underscores if the non-underscore version also exists. Effectively, allowing the proxy defined headers to always win.

I created this script from your with your `curl` commands (and added the last one)

```shell
#!/bin/sh

PORT=${1:-9292}

set -x

# underscore first
curl localhost:$PORT -H "X_MyHeader: false" -H "x-myheader: true"

# dash first
curl localhost:$PORT -H "X-MyHeader: false" -H "x_myheader: true"

# what is even happening here
curl localhost:$PORT -H "X_My-Header: false" -H "x_my_header: true"
curl localhost:$PORT -H "X_My-Header: false" -H "x_my_header: true" -H "X-my-header: filenotfound"

# anti-example showing two headers with different casing
curl localhost:$PORT -H "X_MyHeader: false" -H "x_myheader: true"

# anti-example showing two headers with different casing -- with dash
curl localhost:$PORT -H "X-MyHeader: false" -H "x-myheader: true"
```

I ran your repro (with a newline added to the response) against both Puma v6.4.2 (port 8081) and Puma v6.4.3 (port 8082).

Puma v6.4.2

```shell
$ ./0_all.sh 8081
+ curl localhost:8081 -H 'X_MyHeader: false' -H 'x-myheader: true'
HTTP_X_MYHEADER: false
+ curl localhost:8081 -H 'X-MyHeader: false' -H 'x_myheader: true'
HTTP_X_MYHEADER: true
+ curl localhost:8081 -H 'X_My-Header: false' -H 'x_my_header: true'
HTTP_X_MY_HEADER: true
+ curl localhost:8081 -H 'X_My-Header: false' -H 'x_my_header: true' -H 'X-my-header: filenotfound'
HTTP_X_MY_HEADER: true
+ curl localhost:8081 -H 'X_MyHeader: false' -H 'x_myheader: true'
HTTP_X_MYHEADER: false, true
+ curl localhost:8081 -H 'X-MyHeader: false' -H 'x-myheader: true'
HTTP_X_MYHEADER: false, true
```

Puma v6.4.3

```shell
$ ./0_all.sh 8082
+ curl localhost:8082 -H 'X_MyHeader: false' -H 'x-myheader: true'
HTTP_X_MYHEADER: true
+ curl localhost:8082 -H 'X-MyHeader: false' -H 'x_myheader: true'
HTTP_X_MYHEADER: false
+ curl localhost:8082 -H 'X_My-Header: false' -H 'x_my_header: true'
HTTP_X_MY_HEADER: true
+ curl localhost:8082 -H 'X_My-Header: false' -H 'x_my_header: true' -H 'X-my-header: filenotfound'
HTTP_X_MY_HEADER: filenotfound
+ curl localhost:8082 -H 'X_MyHeader: false' -H 'x_myheader: true'
HTTP_X_MYHEADER: false, true
+ curl localhost:8082 -H 'X-MyHeader: false' -H 'x-myheader: true'
HTTP_X_MYHEADER: false, true
```

**Comment by dentarg** [comment]
To me, it seems clear that header without underscore wins with Puma v6.4.3. @jamiestrachan-shopify do you still think there's a problem in the latest version of Puma?

**Comment by jamiestrachan-shopify** [comment]
I am not sure why Puma is altering the headers at all (other than upper-casing them).
HTTP header names are case insensitive, but underscore and dash are both legal characters (at least, I am [pretty sure](https://developers.cloudflare.com/rules/transform/request-header-modification/reference/header-format/)!)

I would much rather handle the collection of similar headers in my program, instead of having to know that a header with a dash in it may supersede a header with an underscore.

However, I am happier with the 6.4.3 changes, as I can configure my FLB to provide consistent headers.

**Comment by dentarg** [comment]
I think it comes from the CGI specification that the Rack SPEC links to: https://github.com/rack/rack/blob/main/SPEC.rdoc

**Comment by dentarg** [comment]
Connecting this discussion with https://github.com/puma/puma/issues/3397 and https://github.com/rack/rack/issues/1374

**Comment by dentarg** [comment]
And https://github.com/rack/rack/pull/1881
