### ISSUE TITLE
System specs break after upgrading to rackup 1.0.1

### ISSUE THREAD

**Issue by tagliala** [puma/puma#3531]
**Describe the bug**

Hello, I've reported this to rackup repository but it appears to be a problem with Puma.

```
     1.1) Failure/Error: register :puma, Puma
          
          NoMethodError:
            undefined method `register' for Rackup::Handler:Module
```

Some references from rack/rackup#19

> It looks like a problem with Puma:
> 
> https://github.com/puma/puma/blob/v6.4.3/lib/rack/handler/puma.rb#L117-L141
> 
> ```
> if Object.const_defined? :Rackup
> ```
> 
> is probably incorrect.
> 
> There should be two separate files, `lib/rack/handler/puma.rb` and `lib/rackup/handler/puma.rb`. The former is loaded by Rack v2 and the latter by Rackup v2. Having only one file with the detection logic is, basically, looking incorrect to me.
> 
> cc `@MSP-Greg`

> Yes, I think we should report this to Puma.
> 
> Here is how I do it in Falcon:
> 
> https://github.com/socketry/falcon/blob/main/lib/rackup/handler/falcon.rb
> 
> It should be easy to adapt.

**Puma config:**

Default puma 7.2 rails config, but should not be relevant here: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/blob/tmp/rack-rackup-19/config/puma.rb

**To Reproduce**
1. Upgrade rackup to 1.0.1
2. Run system specs driven by a capybara chrome driver

Failure: https://github.com/diowa/ruby3-rails7-bootstrap-heroku/actions/runs/11477074046

**Expected behavior**
Specs keep running

**Desktop (please complete the following information):**
 - OS: n/a
 - Puma Version: 6.4.3
 - Rack version: 2.2

/cc @ioquatix

**Comment by MSP-Greg** [comment]
If anyone can change their Gemfiles, please see PR #3532 or try:
```ruby
gem 'puma', github: 'MSP-Greg/puma', branch: '00-rackup-1.0.1'
```

**Comment by dentarg** [comment]
@tagliala can you help me out? see https://github.com/puma/puma/pull/3532#issuecomment-2433395572

**Comment by tagliala** [comment]
Hi @dentarg, still need my help with a reproducible test case?

I guess that https://github.com/diowa/ruby3-rails7-bootstrap-heroku/pull/995 didn't help or it is too "complex"

**Comment by dentarg** [comment]
@tagliala I figured it out (see the comments on the PR)

**Comment by eikes** [comment]
While puma doesn't have a new release you can use the current unreleased version:

`gem 'puma', github: 'puma/puma', branch: 'master'`

Thank you @MSP-Greg!
