### ISSUE TITLE
Kernel Panic on M4 chips

### ISSUE THREAD

**Issue by aaronjensen** [puma/puma#3551]
**Describe the bug**
When starting puma with multiple workers and eager loading enough code, the new MacBook M4 Max will kernel panic with a SPTM (Secure Page Table Monitor) fault. 

```
[SPTM] VIOLATION_ILLEGAL_SPRR_INDEX: sptm_map_page(sptm.c:406)
```

It's highly likely that this is a macOS bug, but I'm reporting it here for posterity and diligence. 

This has happened on two different M4 Max MacBook Pros

I have reported this to Apple and am waiting to hear back if they will give the report to their developers.  

**Puma config:**

This config is from Mastodon, which is a public app that this reproduces with. Our config is much simpler (just setting threads and workers)

```
RAILS_ENV=development WEB_CONCURRENCY=8 script/rails s
```

```
# frozen_string_literal: true

persistent_timeout ENV.fetch('PERSISTENT_TIMEOUT') { 20 }.to_i

max_threads_count = ENV.fetch('MAX_THREADS') { 5 }.to_i
min_threads_count = ENV.fetch('MIN_THREADS') { max_threads_count }.to_i
threads min_threads_count, max_threads_count

if ENV['SOCKET']
  bind "unix://#{ENV['SOCKET']}"
else
  bind "tcp://#{ENV.fetch('BIND', '127.0.0.1')}:#{ENV.fetch('PORT', 3000)}"
end

environment ENV.fetch('RAILS_ENV') { 'development' }
workers     ENV.fetch('WEB_CONCURRENCY') { 2 }.to_i

preload_app!

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end

plugin :tmp_restart

set_remote_address(proxy_protocol: :v1) if ENV['PROXY_PROTO_V1'] == 'true'
```
**To Reproduce**

1. Clone mastodon: https://github.com/mastodon/mastodon
2. Run `bin/setup`
3. Modify `config/enviroments/development.rb` to have `config.eager_load = true`, rather than `config.eager_load = false`
4. Run `RAILS_ENV=development bin/rails db:create` (it may fail if you don't have Redis running, which is fine -- you just need the database schemas.
5. Run `RAILS_ENV=development WEB_CONCURRENCY=8 script/rails s`
6. If it forks successfully, Ctrl-C and run it again. It may take a couple times.

**Expected behavior**
It runs successfully without kernel panic. 

**Desktop (please complete the following information):**
 - OS: MacOS 15.1 M4 Max
 - Puma Version 6.4.3

**Comment by dentarg** [comment]
Same as https://bugs.ruby-lang.org/issues/20890 but the problem seems to be with Apple and macOS – looks like Secure Page Table Monitor (SPTM) is something new for M4: https://support.apple.com/en-gb/guide/security/sec8b776536b/web

> SPTM also relies on new silicon primitives that are an evolution of the Fast Permission Restrictions that PPL utilises.

From the Ruby ticket it sounds like not using YJIT is a workaround

**Comment by aaronjensen** [comment]
@dentarg Thank you, I added to that issue. 

Also, disabling preload is a workaround. 

It's worth noting that the lack of a `--no-preload` flag and the fact that preload is defaulted when workers are set is a rather unfortunate setback when it comes to me doing this personally (as opposed to committing a change to our shared puma config). I even tried with `--prune-bundler` which claims to prevent preload, but does not appear to do that in practice (possibly a bug?).

**Comment by dentarg** [comment]
> It's worth noting that the lack of a `--no-preload` flag and the fact that preload is defaulted when workers are set is a rather unfortunate setback when it comes to me doing this personally (as opposed to committing a change to our shared puma config).

Maybe you can consider a change to your Puma config that controls `preload_app!` based on an `ENV` value? So you can disable it when needed.

**Comment by mjankowski** [comment]
I'm seeing same issue, also on new M4 Max MBP. Also filed an apple feedback ... seems like this must be an OS/hardware issue, maybe related to SPTM?

**Comment by dentarg** [comment]
Yes (https://github.com/puma/puma/issues/3551#issuecomment-2473727451)

**Comment by dotexe1337** [comment]
> Same as https://bugs.ruby-lang.org/issues/20890 but the problem seems to be with Apple and macOS – looks like Secure Page Table Monitor (SPTM) is something new for M4: https://support.apple.com/en-gb/guide/security/sec8b776536b/web

Same problem with the OpenZFS driver in some cases as well, it seems. My new Mac Mini M4 has the same kernel panic when trying to launch Parallels VM's that are stored on a ZFS volume.

**Comment by mjankowski** [comment]
FYI, release notes for 15.2 Beta 4 release includes:

> Fixed: Resolved an issue where running Ruby with YJIT enabled causes Mac with M4 chip to kernel panic. (139714575) (FB15774033)

I haven't installed this yet to confirm, but looks like people on the ruby-core thread have had success.

**Comment by aaronjensen** [comment]
@dentarg given this, I'd be fine closing this. Up to you if you'd like to leave it open until macOS 15.2 is released officially. I think we can safely consider this an upstream issue.

**Comment by aaronjensen** [comment]
@mjankowski Great, thank you for updating us.

@dentarg given this, I'd be fine closing this. Up to you if you'd like to leave it open until macOS 15.2 is released officially. I think we can safely consider this an upstream issue.

**Comment by nateberkopec** [comment]
Thanks for the research all, closing as solved/solving upstream.

**Comment by aaronjensen** [comment]
Just to confirm, the official release of 15.2 solves this for me.
