### ISSUE TITLE
New release for rackup 1.0.1 compatibility

### ISSUE THREAD

**Issue by mikevoets** [puma/puma#3558]
**Is your feature request related to a problem? Please describe.**

After upgrading rackup to 1.0.1, the latest release of this gem breaks. This has now been fixed in https://github.com/puma/puma/pull/3532, but this hasn't been packaged in a release yet.

**Describe the solution you'd like**

I'd love to get this PR released in a new latest release.

**Describe alternatives you've considered**

We could pin this gem dependency in our project to the latest from master, however our internal policies advise against that practice.

**Additional context**

N/A

**Comment by frederikspang** [comment]
6.5.0 solves this, right?

**Comment by MSP-Greg** [comment]
Yes.
