### ISSUE TITLE
Puma hangs during asset loading

### ISSUE THREAD

**Issue by bpardee** [puma/puma#358]
I have a fairly large backbone app and when I clear my tmp/cache, puma under MRI 2.0 hangs during asset loading until I get "Require.js Load Timeout for Modules" error (Increasing the waitSeconds for Require.js doesn't help).  I have to kill -9 to stop the server at this point.  Under JRuby 1.7.4, the console log lists all kinds of supposed syntax errors in my coffeescript files although there is nothing actually wrong.  Then when I cntl-c I get "Error in reactor loop escaped: closed stream (IOError)".  What I end up doing is starting up webrick to get all the asset compilations cached and after that puma seems to work fine.

**Comment by emiliowl** [comment]
same issue here...

**Comment by emiliowl** [comment]
The problem is happening with these assets... they keep trying to download indefinitely. Since I abort the process through firebug and the pages get loaded successfully. 
(sorry about the bad english)

http://localhost:5000/assets/dataTables/jquery.dataTables.bootstrap3.css?body=1
http://localhost:5000/assets/dataTables/jquery.dataTables.responsive.css?body=1
http://localhost:5000/assets/jquery-ui/flick.css?body=1
http://localhost:5000/assets/send_offs.css?body=1
http://localhost:5000/assets/system_users.css?body=1

Tks for your help.

**Comment by emiliowl** [comment]
https://gist.github.com/emiliowl/320284e00e135d962519

**Comment by emiliowl** [comment]
and at least I found some relevant info at the log file, really hope it helps:

Puma caught this error: Attempt to unlock a mutex which is locked by another thread (ThreadError)
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/rack-1.4.5/lib/rack/lock.rb:20:in `unlock'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/rack-1.4.5/lib/rack/lock.rb:20:in `ensure in call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/rack-1.4.5/lib/rack/lock.rb:21:in `call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/rack-timeout-0.2.0/lib/rack/timeout.rb:108:in `call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/railties-3.2.16/lib/rails/engine.rb:484:in `call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/railties-3.2.16/lib/rails/application.rb:231:in `call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/railties-3.2.16/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/puma-2.11.1/lib/puma/rack_patch.rb:13:in `call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/puma-2.11.1/lib/puma/configuration.rb:82:in `call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/puma-2.11.1/lib/puma/server.rb:507:in `handle_request'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/puma-2.11.1/lib/puma/server.rb:375:in `process_client'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/puma-2.11.1/lib/puma/server.rb:262:in `block in run'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in `call'
/home/murta/.rvm/gems/ruby-2.1.3@trans_terralheiro_dev/gems/puma-2.11.1/lib/puma/thread_pool.rb:104:in
