### ISSUE TITLE
A really lowlevel plumbing error occured. Maytag(tm) error

### ISSUE THREAD

**Issue by mingle2** [puma/puma#360]
A really lowlevel plumbing error occured. Please contact your local Maytag(tm) repair man.

I get this error when sending some traffic to the box...roughly 300-400 request per minute. When there's no traffic I cant reproduce the issue.

Our setup:

puma - 2.5.1,
centos - CentOS release 6.4 (Final) 64 bit 
nginx - 1.5.3
ruby -  1.9.3 p448
rails - 3.2.14

---

[3702] Puma starting in cluster mode...
[3702] \* Version 2.5.1, codename: Astronaut Shoelaces
[3702] \* Min threads: 10, max threads: 10
[3702] \* Environment: production
[3702] \* Process workers: 1
[3702] \* Phased restart available
[3702] \* Listening on unix:/u/apps/myapp/current/tmp/puma/myapp-puma.sock
[3702] \* Daemonizing...
##

**Comment by LeandroSNunes** [comment]
I solved the problem "A really lowlevel plumbing error occured. Please contact your local Maytag(tm) repair man" with the tips of @Alamoz , assigning the key `config/secrets.yml` for the environment.

Rails 4.2.0
ruby 2.2.0p0
puma 2.10.2
nginx 1.1.19

thank you!

**Comment by velobuff** [comment]
We've had this issue when someone attempts to POST malformed JSON i.e. it contains unescaped quotes. 

In our case, someone was using the Postman Chrome plugin to post JSON. Apparently the plugin doesn't escape quotes in JSON strings before it transfers it over the ether.
