### ISSUE TITLE
Puma doesn't display OmniAuth errors until the server terminates

### ISSUE THREAD

**Issue by nchelluri** [puma/puma#365]
This may apply to all Rack Middleware, I am not sure. But here is a repro case...

Here is a simple Sinatra app, in `app.rb`, using Thin and working as expected:

```ruby
#!/usr/bin/env ruby

require 'rubygems'
require 'puma'
require 'sinatra'
require 'omniauth'

use OmniAuth::Builder do
  provider :bad_provider  
end

# set :server, :puma

get '/hi' do
  'Hello World!'
end
```

```shell
$ ruby app.rb 
== Sinatra/1.4.3 has taken the stage on 4567 for development with backup from Thin
>> Thin web server (v1.5.1 codename Straight Razor)
>> Maximum connections set to 1024
>> Listening on localhost:4567, CTRL+C to stop
!! Unexpected error while processing request: Could not find matching strategy for :bad_provider. You may need to install an additional gem (such as omniauth-bad_provider).
```

The last line of the above output happens after running the following in a different terminal tab:

```shell
$ curl localhost:4567/hi
Internal server error
```

Now, let's uncomment the `set :server, :puma` line and try running the code again:

```shell
$ ruby app.rb 
Puma 2.5.1 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
== Sinatra/1.4.3 has taken the stage on 4567 for development with backup from Puma
^C
== Sinatra has ended his set (crowd applauds)
Exception handling servers: Could not find matching strategy for :bad_provider. You may need to install an additional gem (such as omniauth-bad_provider). (LoadError)
/Users/nchelluri/.rvm/gems/ruby-1.9.3-p429/gems/omniauth-1.1.4/lib/omniauth/builder.rb:40:in `rescue in provider'
/Users/nchelluri/.rvm/gems/ruby-1.9.3-p429/gems/omniauth-1.1.4/lib/omniauth/builder.rb:37:in `provider'
app.rb:9:in `block in <main>'
/Users/nchelluri/.rvm/gems/ruby-1.9.3-p429/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
[...]
```

Notice that the exception message doesn't show up until after the user hits Ctrl-C -- so the server just fails silently. Here is the curl output:

```shell
$ curl localhost:4567/hi
curl: (52) Empty reply from server
```

I am not entirely sure that this is a bug, but I would have expected the error to have shown up in the output before the server terminated -- which left me wondering where the error was at all.

For reference, this is a(n attempt at a) minimal repro based on an actual issue encountered when using OmniAuth and upgrading to the latest version of omniauth-linkedin-oauth2 which uses a different OmniAuth provider name.

**Comment by evanphx** [comment]
Puma has a fallback error handler now and sinatra should also provide a rescue handler for uncaught exceptions running the app.

**Comment by nchelluri** [comment]
:+1:
