### ISSUE TITLE
How to cleanup event-stream actions?

### ISSUE THREAD

**Issue by bpardee** [puma/puma#389]
I have a controller that includes ActionController::Live to serve up real time events.  If there are any clients subscribed to these events then my jungle init.d script fails to restart my server and it just hangs.  I suspect that its trying to do a clean shutdown and waiting for all requests to finish.  Is there a hook I can use to close these actions?  I attempted to do it in my config/puma.rb using on_restart but it never makes it this far.

**Comment by j-manu** [comment]
@evanphx Is there a cleaner way to fix this than using halt? Will the timed terminate option be added?

**Comment by j-manu** [comment]
On further testing, found a way. Use phased-restart with a _worker_shutdown_timeout_. First TERM gets sent to workers and after _worker_shutdown_timeout_ KILL gets sent if the worker hasn't shutdown.

**Comment by evanphx** [comment]
A new option `force_shutdown_after` can be used to have SSE workers killed after a time.
