### ISSUE TITLE
Feature request: JRuby hot restart

### ISSUE THREAD

**Issue by mrbrdo** [puma/puma#418]
I would love to see some sort of support for hot restart of JRuby apps.
Perhaps by making it possible to use workers/cluster mode on JRuby, which sounds like an easy modification. If this would be done, then step 2 would be to simply have a cluster of 1, and on hot restart add another worker, wait for it to boot, and then remove the old worker.

**Comment by jeremyhaile** [comment]
Puma is recommended to run on jruby, but doesn't have hot restarts? This is pretty much a deal killer for using puma on jruby production apps. Has there been any update to this?
