### ISSUE TITLE
Puma stoppped working

### ISSUE THREAD

**Issue by mrPsycho** [puma/puma#443]
Hello,

everything was fine, and redmine was working correctly, but after installing https://github.com/alexbevi/redmine_dropbox_attachments puma won't start anymore:

<pre>
[root@liot ~]# /etc/init.d/redmine start
rm: cannot remove `/var/www/liot_work/redmine/tmp/sockets/redmine.socket': No such file or directory
[25797] Puma starting in cluster mode...
[25797] * Version 2.3.2, codename: Delicious Thin Mints
[25797] * Min threads: 0, max threads: 16
[25797] * Environment: development
[25797] * Process workers: 4
[25797] * Phased restart available
ERROR: [25797] No application configured, nothing to run
Redmine service started
[root@liot ~]# /etc/init.d/redmine status
Redmine service is not running.
</pre>

so init script is:

<pre>
[root@liot init.d]# cat redmine
#! /bin/bash

# Redmine
# Maintainer: @psychozoic
# App Version: 5.2

### BEGIN INIT INFO
# Provides:          Redmine
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Redmine project management
# Description:       Redmine project management
### END INIT INFO

APP_ROOT="/var/www/liot_work/redmine"
APP_USER="liot_work"
DAEMON_OPTS="-C $APP_ROOT/config/puma.rb"
PID_PATH="$APP_ROOT/tmp/pids"
SOCKET_PATH="$APP_ROOT/tmp/sockets"
WEB_SERVER_PID="$PID_PATH/puma.pid"
NAME="Redmine"
DESC="Redmine service"

check_pid(){
  if [ -f $WEB_SERVER_PID ]; then
    PID=`cat $WEB_SERVER_PID`
    STATUS=`ps aux | grep $PID | grep -v grep | wc -l`
  else
    STATUS=0
    PID=0
  fi
}

execute() {
  sudo -u $APP_USER -H bash -l -c "$1"
}

start() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    # Program is running, exit with error code 1.
    echo "Error! $DESC $NAME is currently running!"
    exit 1
  else
    if [ `whoami` = root ]; then
      execute "rm $SOCKET_PATH/redmine.socket"
      execute "RAILS_ENV=production bundle exec puma $DAEMON_OPTS"
      echo "$DESC started"
    fi
  fi
}

stop() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    ## Program is running, stop it.
    kill -QUIT `cat $WEB_SERVER_PID`
    rm "$WEB_SERVER_PID" >> /dev/null
    echo "$DESC stopped"
  else
    ## Program is not running, exit with error.
    echo "Error! $DESC not started!"
    exit 1
  fi
}

restart() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    echo "Restarting $DESC..."
    kill -USR2 `cat $WEB_SERVER_PID`
    echo "$DESC restarted."
  else
    echo "Error, $NAME not running!"
    exit 1
  fi
}

status() {
  cd $APP_ROOT
  check_pid
  if [ "$PID" -ne 0 -a "$STATUS" -ne 0 ]; then
    echo "$DESC / Puma with PID $PID is running."
  else
    echo "$DESC is not running."
    exit 1
  fi
}

## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload|force-reload)
        echo -n "Reloading $NAME configuration: "
        kill -HUP `cat $PID`
        echo "done."
        ;;
  status)
        status
        ;;
  *)
        echo "Usage: sudo service redmine {start|stop|restart|reload}" >&2
        exit 1
        ;;
esac

exit 0
</pre>

puma config is:

<pre>
cat /var/www/liot_work/redmine/config/puma.rb | grep -v "#"
application_path = '/var/www/liot_work/redmine'
directory application_path
environment = :production
daemonize true
workers 4
</pre>

what is wrong? what should i check?

**Comment by aivils** [comment]
yep it stops working.
This works for me:
```bash
RAILS_ENV=production bundle exec puma -C config/puma.rb config.ru
```
Adding at end of line config.ru is very important. Seems puma pick up an empty argument and then said "No application configured, nothing to run".

**Comment by gavinheavyside** [comment]
I think this looks OK, but I'd like to take a bit more time before I say ship it.

**Comment by jeffrafter** [comment]
This is an old issue, but in case someone else gets here, you might run into this if your `config/puma.rb` references `RAILS_ENV` instead of `RACK_ENV` or if the `PORT` is missing. Double check your ENV. Also, if your `config.ru` is older it might not have the correct path. A good `config.ru` looks like:

```ruby
# This file is used by Rack-based servers to start the application.
require_relative 'config/environment'

run Rails.application
```

**Comment by sg552** [comment]
I met this problem . 

make sure you have these attributes in your puma.rb file: 

```
app_dir = '/opt/app/www.yoursite.com/current'
directory app_dir
rackup "#{app_dir}/config.ru"
```

my complete `config/puma.rb` looks like: 

```
threads_count = 32
threads 4, 32

port 8888
environment "production"

app_dir = '/opt/app/www.yoursite.com/current'
directory app_dir
rackup "#{app_dir}/config.ru"

shared_dir = '/opt/app/www.yoursite.com/shared'
workers 8
bind "unix://#{shared_dir}/sockets/puma.sock"
stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true
pidfile "#{shared_dir}/pids/puma.pid"
state_path "#{shared_dir}/pids/puma.state"
daemonize true

preload_app!

before_fork do
  ActiveRecord::Base.connection_pool.disconnect! if defined?(ActiveRecord)
end


on_worker_boot do
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
end


# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart

```

**Comment by PixApplications** [comment]
If you are deploying to AWS EB, make sure that the puma.rb has the following:

directory /var/app/current

Then, as mentioned above:

bundle exec puma start -C config/puma.rb
