### ISSUE TITLE
Stats not available via pid only

### ISSUE THREAD

**Issue by concept47** [puma/puma#461]
when I run

```
 bundle exec pumactl -S tmp/status.txt stats
```

I get this message (Stats not available via pid only), what does it mean?
PS: there is a pid number in status.txt, i get the same error with

```
bundle exec pumactl -p xxxx stats
```

**Comment by manuelmeurer** [comment]
Just ran into this... @evanphx how can one see stats with `pumactl` if not with a pid or status file?

**Comment by yld** [comment]
You need to specify a control URL in your puma config file and on your command line.

**Comment by troyswanson** [comment]
So if you don't have a control URL defined in your config, this command is useless?

**Comment by yld** [comment]
> So if you don't have a control URL defined in your config, this command is useless?

Exactly.
