### ISSUE TITLE
Unix sockets, Puma, Nginx Concurrency issues

### ISSUE THREAD

**Issue by momer** [puma/puma#462]
As discussed with Evan on IRC - I'm running into an issue where after hitting nginx/puma with 50 concurrent users, I start to get errors about the puma unix socket not being available.

`2014/02/11 11:20:46 [error] 21167#0: *31067 connect() to unix:///home/deployer/apps/my_app/shared/sockets/puma.sock failed (11: Resource temporarily unavailable) while connecting to upstream, client: XX.XXX.XXX.XXX, server: xxx.my-application.com, request: "GET /tracking_pixel.png HTTP/1.1", upstream: "http://unix:///home/deployer/apps/my_app/shared/sockets/puma.sock:/500.html", host: "xxx.my-application.com"`

I've adjusted a number of settings in /etc/sysctl.conf and /etc/security/limits.conf [1] but am unable to resolve this issue.

So, I've created an app which produces the same results [2]. It's a Sinatra app that runs on Rubinius 2.2.5.

You can reproduce the stress test by using Apache Jmeter [3] with the settings shown at the imgur library I've set up [4] and the getting started guide on the Jmeter site [5].

[1] https://gist.github.com/momer/8940093
[2] https://github.com/momer/puma_nginx_issues
[3] http://jmeter.apache.org/
[4] http://imgur.com/a/1gEHA
[5] http://jmeter.apache.org/usermanual/build-web-test-plan.html

**Comment by collimarco** [comment]
@momer  I have your exact same issue. Do you remember how you solved that error? Any tip would be greatly useful ;)

**Comment by poc7667** [comment]
@momer how could you solve this?

**Comment by swordfish444** [comment]
@momer @collimarco @poc7667 Did any of you resolve this issue? I'm also facing this and any tips would be very much appreciated!

**Comment by collimarco** [comment]
@swordfish444 You need to increase the backlog for Puma: https://github.com/puma/puma/issues/370

See also: https://www.nginx.com/blog/tuning-nginx/
