### ISSUE TITLE
upstream timed out (110: Connection timed out) while reading response header from upstream

### ISSUE THREAD

**Issue by concept47** [puma/puma#464]
I've been trying to debug this problem for almost 7 months now where I'll get random 4-5 minute outages on my site thats running a rails app using puma (2.7.1) proxied to nginx. This happens almost daily. what really bothers me is how the outages are always almost certainly 3-5 minutes in length, every single time.

At first I thought it was the VPS, but after moving to different instances the problem persisted, after a bit of digging I realized that during the outages I'd get these entries in nginx error logs during the outage periods

**2014/02/12 04:28:31 [error] 963#0: *2783320 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xx.xx.xx.xx, server: www.xxxx.com, request: "GET / HTTP/1.0", upstream: "http://unix:///var/www/xxx/tmp/puma.sock:/", host: "www.xxx.com"**

Which means that puma is just not responding on that socket (or port) for whatever reason around that time.

This happens whether I use unix sockets (stored on filesystem) or just a good old port. Just looking for things to try since, I'm out of ideas :\

**Comment by prashantham** [comment]
I have similar issue on a server which does not have any background workers. Using monit is the only solution?
