### ISSUE TITLE
Puma + SSL + Rails in development and output logs in console

### ISSUE THREAD

**Issue by randoum** [puma/puma#488]
Hi,

I'm trying to set-up puma server with my rails application with SSL.

Starting with the `puma` command work well:

```
puma -b 'ssl://127.0.0.1:3001?key=bin/ssl/server.key&cert=bin/ssl/server.crt' 
```

But I'm trying to get more info in the console output (currently it shows only the access log)
## 

So I tred the following command (given 'puma' is declared in my Gemfile)

```
bundle exec rails server -b 'ssl://127.0.0.1:3001?key=bin/ssl/server.key&cert=bin/ssl/server.crt'
```

which give me the following output:

```
=> Booting Puma
=> Rails 4.0.3 application starting in development on http://ssl://127.0.0.1:3001?key=bin/ssl/server.key&cert=bin/ssl/server.crt:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.8.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://ssl://127.0.0.1:3001?key=bin/ssl/server.key&cert=bin/ssl/server.crt:3000
Exiting
/home/benj/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.0/lib/puma/binder.rb:195:in `initialize': getaddrinfo: Name or service not known (SocketError)
    from /home/benj/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.0/lib/puma/binder.rb:195:in `new'
    from /home/benj/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/puma-2.8.0/lib/puma/binder.rb:195:in `add_tcp_listener'
    from (eval):2:in `add_tcp_listener'
    ...
```

Is there a solution to get a full app log output when using puma in ssl with rails?
Thanks in advance
- ruby 2.1.1
- rails 4.0.3
- puma 2.8.0

**Comment by Fuffi** [comment]
+1

**Comment by standingwave** [comment]
Any chance of this getting addressed? Just bit me today....

**Comment by randoum** [comment]
@standingwave I guess not, if @evanphx is silently ignoring this since 3 years than you can consider it dead.

**Comment by evanphx** [comment]
What are you looking to have addressed? I dealt with the issue long ago. Are you having a problem with rails -b still?

**Comment by lvela** [comment]
I found a good workaround. Add to `config/environments/development`

**Comment by schnittchen** [comment]
Bonus points to avoid running over other people's setup:

```
if $0["puma"]
  config.logger = ActiveSupport::TaggedLogging.new(ActiveSupport::Logger.new(STDOUT))
end
```

**Comment by digaoddc** [comment]
It is better to use Syslog instead of files, it follows 12factorApp.  Add this code to `production.rb`

`config.logger = ActiveSupport::TaggedLogging.new(Syslogger.new('MyApp'))`
