### ISSUE TITLE
How to get info from activate_control_app? (no docs?)

### ISSUE THREAD

**Issue by inspire22** [puma/puma#501]
I can't find anything about this online, so am asking here.

the config file examples all say something like this:
   activate_control_app 'tcp://127.0.0.1:9000', { auth_token: 'asdf' }

I've attempted to go to that web page but get 'invalid auth_token'.  How do I access this and what does it do?

**Comment by nkokkos** [comment]
Hi. 
You can also do a 

``GET /stats?secret=asdf``

which will return a JSON object with data

References:
See here: https://dev.to/amplifr/monitoring-puma-web-server-with-prometheus-and-grafana-5b5o

**Comment by inspire22** [comment]
Just in case anyone else comes here, looks like ?secret has changed to ?token at some point
