### ISSUE TITLE
puma causes a premature close on a ActionController::Live socket

### ISSUE THREAD

**Issue by pedrocr** [puma/puma#525]
I discussed this initially in issue #523. As it turns out this does indeed seem to be some kind of bug in puma. I am using rails 4.1 and puma 2.8.2. I am using ActionController::Live to do proxying of a HTTP chunked request. The code is simple enough:

```ruby
class CamerasController < ApplicationController
  include ActionController::Live

  before_action :set_camera, only: [:show, :edit, :update, :destroy, :stream]

  # GET /cameras/1/stream
  def stream
    if !@camera.port
      # FIXME: return a "waiting for camera image jpg"
    else
      begin
        response.headers['Content-Type'] = 'multipart/x-mixed-replace;boundary=SurelyJPEGDoesntIncludeThis'

        logger.info "Connecting to camera on port #{@camera.port}"

        Net::HTTP.start("127.0.0.1", @camera.port) do |http|
          req = Net::HTTP::Get.new "/mjpeg"

          http.request req do |res|
            res.read_body do |chunk|
              response.stream.write chunk
            end
          end
        end
      ensure
        response.stream.close
      end
    end
  end
end
```

The streaming starts fine but after a second or two I get an IOError on response.stream.write as the stream has been closed. If I add a "sleep 1" after "response.stream.write chunk" this will stutter but work.

I've traced this to this chunk of puma code in Puma::Server#handle_request:616:

```ruby
        begin
          res_body.each do |part|
            if chunked
              client.syswrite part.bytesize.to_s(16)
              client.syswrite line_ending
              fast_write client, part
              client.syswrite line_ending
            else
              fast_write client, part
            end

            client.flush
          end

          if chunked
            client.syswrite CLOSE_CHUNKED
            client.flush
          end
        rescue SystemCallError, IOError
          raise ConnectionError, "Connection error detected during write"
        end
```
Adding some debug printfs to that it seems we are getting EPIPE on the "client.syswrite part.bytesize.to_s(16)" call. This then gets rescued to a ConnectionError and the later ensure closes the socket. Any ideas of what could be going on?

**Comment by matthewd** [comment]
Could this be a manifestation of #743? It seems unlikely that `read_body` would yield an empty chunk, but the described symptoms (including sleep fixing it) otherwise sound plausible.

**Comment by evanphx** [comment]
that's certainly possible. I'll release that fix this weekend.

**Comment by evanphx** [comment]
i'm pretty sure the issue was #743. If you still have this issue, please open a new issue.
