### ISSUE TITLE
puma cluster mode: master forked workers more than configuration

### ISSUE THREAD

**Issue by chenghung** [puma/puma#526]
My puma config 

<pre>
workers 3
preload_app!
threads 4, 8

path = '/opt/www/my_project/shared'
bind "unix://#{path}/sockets/puma.socket"
state_path "#{path}/puma.state"
pidfile "#{path}/pids/puma.pid"

rackup      DefaultRackup
environment 'production'

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
</pre>

puma.state

<pre>
pid: 5434
config: !ruby/object:Puma::Configuration
  options:
    :min_threads: 4
    :max_threads: 8
    :quiet: true
    :debug: false
    :binds:
    - unix:///opt/www/my_project/shared/sockets/puma.socket
    :workers: 3
    :daemon: true
    :worker_directory: /opt/www/my_project/current
    :environment: production
    :config_file: ./config/puma/production.rb
    :mode: :http
    :worker_timeout: 60
    :preload_app: true
    :state: /opt/www/my_project/shared/puma.state
    :pidfile: /opt/www/my_project/shared/pids/puma.pid
    :rackup: config.ru
    :control_auth_token: a459346df55714499a9e58baadbb4a1e
</pre>

ps aux|grep puma|grep master

<pre>
1002      5434  0.0  0.5 274564 90044 ?        Sl   09:54   0:00 puma 2.8.2 (unix:///opt/www/my_project/shared/sockets/puma.socket)  
</pre>

ps aux|grep puma|grep worker

<pre>
1002      3427  0.0  0.5 822696 94648 ?        Sl   09:51   0:00 puma: cluster worker 0: 5026                                                                                     
1002      3439  0.0  0.5 822888 94704 ?        Sl   09:51   0:00 puma: cluster worker 0: 6968                                                                                     
1002      3442  0.0  0.5 822888 94728 ?        Sl   09:51   0:00 puma: cluster worker 1: 6968                                                                                     
1002      3445  0.0  0.5 822888 94704 ?        Sl   09:51   0:00 puma: cluster worker 2: 6968                                                                                     
1002      3451  0.0  0.5 822868 94680 ?        Sl   09:51   0:00 puma: cluster worker 0: 9115                                                                                     
1002      3454  0.0  0.5 822868 94676 ?        Sl   09:51   0:00 puma: cluster worker 1: 9115                                                                                     
1002      3457  0.0  0.5 822868 94688 ?        Sl   09:51   0:00 puma: cluster worker 2: 9115                                                                                     
1002      3516  0.0  0.5 822696 94624 ?        Sl   09:51   0:00 puma: cluster worker 1: 5026                                                                                     
1002      3519  0.0  0.5 822696 94628 ?        Sl   09:51   0:00 puma: cluster worker 2: 5026                                                                                     
1002      5437  0.0  0.5 817356 89524 ?        Sl   09:54   0:00 puma: cluster worker 0: 5434                                                                                                                               
1002      5441  0.0  0.5 817356 89492 ?        Sl   09:54   0:00 puma: cluster worker 1: 5434                                                                                                                               
1002      5450  0.0  0.5 817356 89492 ?        Sl   09:54   0:00 puma: cluster worker 2: 5434 
</pre>

**Comment by cinic** [comment]
@chenghung what's problem?
