### ISSUE TITLE
How to disable multi-threading completely?

### ISSUE THREAD

**Issue by openface** [puma/puma#531]
Unsure if my application is 100% threadsafe, I'd like to first deploy in a single-threaded clustered environment.  (2 workers)

I've read that the way to run Puma in single-threaded context is by specifying the min and max number of threads both to 1.

```
  threads 1, 1
```

However, with this in place, when I use htop to view the processes, I can see individual threads (8 for each worker) and an additional thread for the master. 

![Image of htop with threads](http://i.imgur.com/mUTGhZh.png)

When I disable userspace thread viewing in htop, the extra threads disappears and I then only see the (expected) master and 2 worker processes.

![Image of htop without threads](http://i.imgur.com/FIe1aor.png)

So there still appears to be some form of threading happening with Puma.   I don't see this behavior using Unicorn, for example.

So is there a more concrete way to effectively disable multi-threading in Puma?

**Comment by albertnetymk** [comment]
> Puma uses some threads for other things (such as handling slow clients) and that is what you're seeing.

Anywhere I can see more documentation on those extra threads?

**Comment by evanphx** [comment]
@albertnetymk they're not documented right now. What info are you looking for?

**Comment by albertnetymk** [comment]
Using `puma` on `herkou`, and `newrelic` reports that I have 11 threads totally; not sure if that's reasonable and wonder if it's possible to bring it down a bit due to the frequent `Memory Quota Exceeded` warning.

**Comment by vizcay** [comment]
Being caught by this also, wasted almost an hour tweaking the thread count wondering what exactly was puma doing because it didn't matched the numbers. Well, does some admin mind if I send a PR to state this in the README for the next curious soul?

**Comment by nateberkopec** [comment]
No, we don't mind. Something in the docs for the `threads` dsl command would be appropriate.
