### ISSUE TITLE
Warning On Puma Restart 

### ISSUE THREAD

**Issue by rodrigdav** [puma/puma#532]
We upgraded to Puma 2.8.2 running jruby 1.7.11 and now when I restart puma I get the below warnings.  

The signal USR1 is in use by the JVM and will not work correctly on this platform
The signal USR1 is in use by the JVM and will not work correctly on this platform

Using the below config file. 
directory '/home/sites/applicationServer/current/'

environment 'staging'

daemonize true
pidfile 'tmp/pids/puma.pid'

state_path 'tmp/pids/puma.state'

stdout_redirect '/home/sites/applicationServer/current/log/puma.log', '/home/sites/applicationServer/current/log/puma.log', true

threads 0, 16

bind 'unix://tmp/pids/puma.sock?umask=0111'

workers 0

I am also seeing an issue where after a couple of restarts puma seems to time out on restart.

**Comment by evanphx** [comment]
It's fine, that functionality just isn't available. Use USR2.
