### ISSUE TITLE
Feature - pumatcl restart on worker

### ISSUE THREAD

**Issue by allaire** [puma/puma#547]
As discussed on Twitter, it would be cool to be able to restart puma workers with `pumactl restart`.

We can drop the pid of each worker with:

```ruby
on_worker_boot do |index|
  worker_pidfile = File.join(@options[:pidfile].gsub('.pid', "_worker_#{index}.pid"))
  File.open(worker_pidfile, 'w') { |f| f.puts Process.pid }
end
```

But there's no easy way with `pumactl` to kill/restart one of these worker with their associated `--pidfile`.

Thanks!

**Comment by evanphx** [comment]
I think this would be interesting. I'd be happy to merge a PR.
