### ISSUE TITLE
Embed API for the CLI

### ISSUE THREAD

**Issue by YorickPeterse** [puma/puma#548]
As it currently stands Puma is hard to embed inside Gems that provide their own `config.ru` files and CLI options. This is mainly due to most of the startup logic being handled by `Puma::CLI` without exposing everything needed for this. For example, the option parser is hidden away in a non public instance variable. This prevents users from adding their own options to the CLI.

As a use-case there's https://github.com/opener-project. Basically this is a set of NLP tools written in a bunch of languages and wrapped as Gems. These Gems then provide things such as a Puma web interface, a CLI, a daemon, etc. In these cases we want to provide our own default `config.ru` files so that the user literally can just run `foobar-server` and start using things. 

Due to the lack of a proper embed API we had to resort to hacking ARGV as can be seen here: https://github.com/opener-project/language-identifier/blob/cd98c228d7e4dec307b0bc7113bd823db9a276d7/bin/language-identifier-server

In some other cases we wanted custom options and had to essentially re-invent the Puma CLI: https://github.com/opener-project/polarity-tagger/blob/bf90991db7f0de8fa6267468344a0b88fe1cc11d/bin/polarity-tagger-server

To achieve this the `Puma::CLI` class probably has to be broken apart into smaller pieces, allowing for them to be re-used more easily Second the option parser would have to be exposed to the public so that we can hook our own options into it.

Code wise, I envision something like the following:

```ruby
# my-gem/bin/some-puma-server
cli = Puma::CLI.new

cli.rackup_config = File.expand_path('../../config.ru', __FILE__)

cli.option('--resource [URL]', 'Downloads the file to the current directory') do |file|
  # Download the file ...
end

cli.run(ARGV)
```

**Comment by evanphx** [comment]
This gone done for 3.0!
