### ISSUE TITLE
link_to generating SSL errors

### ISSUE THREAD

**Issue by iklier** [puma/puma#559]
I have a Rail 4 application that I'm attempting to run with SSL. I've managed to get everything working except for my ajax link_to links throw the following error 'Read error: Puma::MiniSSL::SSLError: OpenSSL error: error:00000005:lib(0):func(0):DH lib - 5' and appear to execute multiple times (3+).

The same links work without issue under Puma without SSL

Backtrace:
xx.xx.xx.xx - - [22/Jul/2014 15:15:53] "GET /test/refresh?id=1066 HTTP/1.1" 200 - 0.0161
2014-07-22 15:15:53 -0700: Read error: Puma::MiniSSL::SSLError: OpenSSL error: error:00000005:lib(0):func(0):DH lib - 5
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/minissl.rb:60:in `write'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/minissl.rb:60:in `write'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/server.rb:784:in `fast_write'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/server.rb:619:in `block in handle_request'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/server.rb:615:in `handle_request'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/server.rb:361:in `process_client'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/server.rb:254:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `call'
/Library/Ruby/Gems/2.0.0/gems/puma-2.8.2/lib/puma/thread_pool.rb:92:in `block in spawn_thread'

The error appears to be thrown when the controller function ends and it attempts to respond back to the client.

**Comment by Leooo** [comment]
Did you manage to get rid of this problem? have the same issue since months, and I cannot get a clean SSL in development because of it.

**Comment by chytreg** [comment]
Have the same issue any cure for that?

**Comment by evanphx** [comment]
Is the link_to generating an http:// link targeted at the port running SSL? Perhaps that's the issue.

**Comment by chytreg** [comment]
Thx for the tip, will check it.
