### ISSUE TITLE
How I can launch a rails app in production mode?

### ISSUE THREAD

**Issue by pioz** [puma/puma#56]
There is a way to run a rails app in production mode like this?

```
puma --pidfile /var/run/puma.pid -p 3030 -e production
```

**Comment by MassMadankumar** [comment]
A server is already running

root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
A server is already running. Check /mnt/zapstore.com/shopifyapp/zap/tmp/pids/server.pid.
Exiting
