### ISSUE TITLE
Deferred shutdown until background threads are done executing?

### ISSUE THREAD

**Issue by johnkchow** [puma/puma#562]
I have a question: is there a mechanism within Puma to defer shutdown/restarts until background worker threads are done executing? Let's say I want to run certain tasks async during a request (i.e. making analytics API calls or updating a cache). While I could use Sidekiq/Resque, I was wondering if there was a proper way of having all these async tasks run and finish before shutting down?

P.S. Great work w/ puma, first time using jruby with this bad boy and I'm pretty excited w/ this!

**Comment by evanphx** [comment]
`on_worker_shutdown` gives you the ability to add your own logic to control the lifecycle.
