### ISSUE TITLE
Pumactl restart not working

### ISSUE THREAD

**Issue by deathbob** [puma/puma#563]
https://github.com/puma/puma/issues/409

I don't think this problem every really went away for me, and I've spent today trying to fix it, with no luck.
It is present for me in 2.7.1, 2.9.0, and master branch.  

Again, the fact that restart says "Command restart sent success" but the actual Puma process is down is pretty much horrible.  It might be true that the command was sent successfully, but I don't care about that, I care if the #@?! Puma process has in fact restarted.  The definition of success when you ask something to restart is if it comes back up. This is something Apache and Nginx understand, and they do report a failure if attempts to restart them fail.  

Puma really has to block on this, and report failure when it happens.  

For now I overrode the built in capistrano restart task to simply call stop and start.  Not really a great solution.

**Comment by urkle** [comment]
this is not working at all under RHEL 6 64-bit.. 
puma 2.12.1 on ruby 2.2.1.
any time I do a pumactl restart, phased-restart, or use the kill -USR2 / kill -USR1, puma simply exits.  This is rather disappointing that a core piece functionality is severely broken in puma.

When I start puma (non-daemonized) in one terminal (pumactl start) and restart it from another terminal (pumactl phased-restart) here is the output I get.
```
[2856] Puma starting in cluster mode...
[2856] * Version 2.12.1 (ruby 2.2.1-p85), codename: Plutonian Photo Shoot
[2856] * Min threads: 5, max threads: 5
[2856] * Environment: production
[2856] * Process workers: 2
[2856] * Preloading application
[2856] * Listening on tcp://0.0.0.0:3000
[2856] Use Ctrl-C to stop
[2856] - Worker 0 (pid: 2863) booted, phase: 0
[2856] - Worker 1 (pid: 2868) booted, phase: 0
[2856] * phased-restart called but not available, restarting normally.
[2856] - Gracefully shutting down workers...
[2856] * Restarting...
Available commands: halt, restart, phased-restart, start, stats, status, stop, reload-worker-directory
```
why would it spit out "available commands" like that ???
.. time passes..
 Well, it seems I found the issue..   if I start the server with puma instead of pumactl it restarts correctly!!  So it seems somewhere in the code the restart_command is being incorrectly calculated when using pumactl to start the app

**Comment by evanphx** [comment]
I'm sorry about that, I should just remove the start functionality from `pumctl`. It provides an additional unnecessary vector for confusion.

**Comment by evanphx** [comment]
And another vector for bugs. In fact, I should just reimplement it in terms of exec'ing normal puma.

**Comment by evanphx** [comment]
@urkle what commands were you running? You didn't paste them in.

**Comment by urkle** [comment]
I was running 
```pumactl start```  and ```pumactl phased-restart```
to start the server and now am changing it to 
```puma```
it would be better to reimplement it in terms of exec'ing puma, as right now (from others on this bug) running pumactl restart will start puma if it's not running (though presumably via the wrong command)
as for my configuration
```workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!
daemonize

rackup      DefaultRackup
port        ENV['PORT'] || 3000
environment ENV['RAILS_ENV'] || 'development'
state_path  './tmp/puma.state'
pidfile     './tmp/pids/puma.pid'
activate_control_app
```

**Comment by urkle** [comment]
Any progress in getting this properly fixed?

**Comment by isaiah** [comment]
@urkle In the readme it says:
 > Note that preload_app can’t be used with phased restart, since phased restart kills and restarts workers one-by-one, and preload_app is all about copying the code of master into the workers.

@evanphx Maybe you should put that in a big banner :)

**Comment by urkle** [comment]
Regardless of that, the issue still remains pumactl start sets the wrong process name so restarting does not function.

**Comment by tonytonyjan** [comment]
I encountered the same problem with the config below (no `preload_app!`):

```ruby
threads 8, 32
workers 4
bind 'tcp://0.0.0.0:3000'
daemonize
```

ruby 2.2.3p173
puma version 2.14.0

**Comment by cwardata** [comment]
For future Googlers like me, now it's:

```
#!/bin/bash
kill -s SIGUSR2 $(cat tmp/pids/server.pid)
```

(credit to @SaimonL)

**Comment by omenking** [comment]
It's 2021 and I still can't get `pumactl stop` to work as expected.

I guess I'll just kill as @localhostdotdev suggests.

**Comment by cjlarose** [comment]
A bunch of stuff has changed in puma since this issue was first opened. @omenking if you're experiencing a similar problem in Puma 5, please feel free to open a new issue.
