### ISSUE TITLE
Rolling Restarts with Rails ActionController::Live

### ISSUE THREAD

**Issue by Geokoumpa** [puma/puma#569]
Hello, 
we have a live controller in our rails app, with an action streaming new alerts to users. We have implemented the heartbeat solution as described here https://github.com/rails/rails/issues/10989

We can't however do a rolling restart when at least one open session exists. As soon as the user closes the client and the heartbeat kicks in, the thread is killed and the restart goes on, but until then Puma remains down. This is n't a situation we can handle on production of course, so I thought I'd ask how anyone else has handled it. Otherwise live controllers are pretty much useless.

**Comment by xanview** [comment]
Any solution for this?

**Comment by evanphx** [comment]
You'll be able to use `force_shutdown_after` to tell puma to kill any Live running threads in 3.4.0.
