### ISSUE TITLE
Puma stops responding with Rails live streaming if the connection is closed while the controller is writing to the buffer

### ISSUE THREAD

**Issue by rosenfeld** [puma/puma#576]
I'm not sure whether this is an issue with Rails or Puma so I'm posting to both in the hope you could help me to investigate this issue:

https://groups.google.com/forum/#!topic/rubyonrails-core/rHDADm3wyP4

Basically, if I create the server with 16 threads this won't complete in an IRB session:

```ruby
require 'socket'
20.times{s = TCPSocket.new 'localhost', 3000; s.puts "GET / HTTP/1.1\r\n\r\n";s.gets; s.close}
```

The result is the same both for JRuby and MRI.

The controller sends lots of traffic so that it doesn't fit in the socket buffer and you'll notice that I don't read from the buffer in the IRB session on purpose to simulate what happens sometimes in our real servers.

The Rails logs seem to indicate that all 16 requests were completed but still I can't initiate any other request and if I take a look at the threads dump using VisualVM and JRuby I can see several live threads there waiting on some object monitor.

Since I can't set up any timeout in Puma I can only try to kill the threads from the Rails side but my attempts didn't work so far.

Here is the code for the Main controller (the root path is mapped to main#index):

```ruby
# main_controller.rb
require 'timeout'
class MainController < ApplicationController
  include ActionController::Live

  CHUNK = ('a' * 1_000_000).freeze
  def index
    logger.info 'outside timeout block'
    Timeout::timeout(5) do
      logger.info 'inside timeout block'
    10.times do |i|
      20.times{response.stream.write "#{CHUNK}\n"}
      sleep 1
    end
    end
    logger.info 'timeout returned without errors'
  rescue
    logger.error "timeout rescue inside controller\n\n"
  ensure
    logger.error 'closing stream'
    Thread.current.exit
    # response.stream.close
    # logger.info 'stream closed'
  end
end
```

I'm also forcing a timeout to all controller's actions:

```ruby
# application_controller.rb
require 'timeout'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def process(*args)
    Timeout::timeout(5) do
      super
    end
  rescue
    logger.error "timeout happened!\n\n\n"
    raise 'error'
  end
end
```

And I'm using the production environment for my tests.

Am I missing something?

**Comment by evanphx** [comment]
Because it causes many other issues if we don't close it. Looks like it was a rails bug anyway.
