### ISSUE TITLE
JRuby SSL binding creates broken thread if non SSL connection targets SSL Port

### ISSUE THREAD

**Issue by wendelllam** [puma/puma#603]
Once I run an SSL server with puma:

    bundle exec puma remote-webapp/config.ru -b 'ssl://0.0.0.0:8888?keystore=remote-webapp/keystore.jks&keystore-pass=123456'

And then try to use http instead on the https, the following error occur:

    vendor/jruby/1.9/gems/puma-2.9.2-java/lib/puma/thread_pool.rb:56" java.lang.RuntimeException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

The problem is then the particular thread would become a zombie and never got recycled. Is there anyway I could prevent this from happening?

**Comment by evanphx** [comment]
@wendelllam Where is the fixe for this?
