### ISSUE TITLE
! WARNING: Detected 2 Thread(s) started in app boot:

### ISSUE THREAD

**Issue by wherewelive** [puma/puma#614]
Making the switch from Unicorn to Puma on Heroku. Everything is working per Heroku guide, but getting the following warning when deploying or restarting the app. Happens locally as well with foreman start. We are also using Octopus for replication. Is this something to be concerned about or can we ignore the warnings? Assuming it has to do with stale threads that are not killed on restart. Below is output on foreman startup...

❯❯❯ foreman start web
10:41:21 web.1       | started with pid 17290
10:41:22 web.1       | [17290] Puma starting in cluster mode...
10:41:22 web.1       | [17290] \* Version 2.10.2 (ruby 2.1.4-p265), codename: Robots on Comets
10:41:22 web.1       | [17290] \* Min threads: 1, max threads: 1
10:41:22 web.1       | [17290] \* Environment: development
10:41:22 web.1       | [17290] \* Process workers: 3
10:41:22 web.1       | [17290] \* Preloading application
10:41:25 web.1       | => 2 databases enabled as read-only slaves
10:41:25 web.1       |   \* FOLLOWER 1
10:41:25 web.1       |   \* FOLLOWER 2
10:41:26 web.1       | [17290] \* Listening on tcp://0.0.0.0:3000
10:41:26 web.1       | [17290] ! WARNING: Detected 2 Thread(s) started in app boot:
10:41:26 web.1       | [17290] ! #<Thread:0x007fceea782b28 sleep> - /Users/aaronats/.rvm/gems/ruby-2.1.4/gems/minitest-5.4.2/lib/minitest/parallel.rb:12:in `pop'
10:41:26 web.1       | [17290] ! #<Thread:0x007fceea7829c0 sleep> - /Users/aaronats/.rvm/gems/ruby-2.1.4/gems/minitest-5.4.2/lib/minitest/parallel.rb:12:in`pop'
10:41:26 web.1       | [17290] Use Ctrl-C to stop
10:41:26 web.1       | [17290] - Worker 0 (pid: 17293) booted, phase: 0
10:41:26 web.1       | [17290] - Worker 2 (pid: 17295) booted, phase: 0
10:41:26 web.1       | [17290] - Worker 1 (pid: 17294) booted, phase: 0

**Comment by monfresh** [comment]
I'm getting the same thing with New Relic and AppSignal:
```
2015-02-02T02:47:49.519893+00:00 app[web.2]: [3] ! WARNING: Detected 2 Thread(s) started in app boot:
2015-02-02T02:47:49.519941+00:00 app[web.2]: [3] ! #<Thread:0x007f5b515a44d0 sleep> - /app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent/event_loop.rb:118:in `select'
2015-02-02T02:47:49.522561+00:00 app[web.2]: [3] Use Ctrl-C to stop
2015-02-02T02:47:49.519964+00:00 app[web.2]: [3] ! #<Thread:0x007f5b55bebf10 sleep> - /app/vendor/bundle/ruby/2.1.0/gems/appsignal-0.10.6/lib/appsignal/agent.rb:33:in `sleep'
```
Could this be the cause of R12 errors when Heroku restarts the dyno?

**Comment by evanphx** [comment]
You're using preload and clustering, which means that those threads don't survive into the workers unless the code that uses those threads automatically restarts them. I suggest you turn off preload.

**Comment by lacco** [comment]
@monfresh NewRelic should just work in thread mode since version 3.8.0 of their gem, it should automatically restart thread in children. See also https://github.com/newrelic/rpm/blob/master/CHANGELOG (search for "restart_thread_in_children").

**Comment by afeld** [comment]
Hmm, running into the same issue with `newrelic_rpm` v3.12.1.298 and `puma` v2.11.3...

```
$ bundle exec puma
[27978] Puma starting in cluster mode...
[27978] * Version 2.11.3 (ruby 2.2.2-p95), codename: Intrepid Squirrel
[27978] * Min threads: 5, max threads: 5
[27978] * Environment: development
[27978] * Process workers: 2
[27978] * Preloading application
[27978] * Listening on tcp://0.0.0.0:3000
[27978] ! WARNING: Detected 2 Thread(s) started in app boot:
[27978] ! #<Thread:0x007fc9dd1039f8@/Users/aidanfeldman/.rvm/gems/ruby-2.2.2/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/threading/agent_thread.rb:12 sleep> - /Users/aidanfeldman/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/protocol.rb:155:in `select'
[27978] ! #<Thread:0x007fc9dd324840@/Users/aidanfeldman/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:80 sleep> - /Users/aidanfeldman/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:82:in `sleep'
[27978] Use Ctrl-C to stop
[27978] - Worker 0 (pid: 27999) booted, phase: 0
[27978] - Worker 1 (pid: 28000) booted, phase: 0
```

@Tomohiro's [workaround](https://github.com/Tomohiro/plate/commit/0a5a072c8d882f32a48d8bdbfa325e83719f58f8) worked for me, but not sure why the issue is still coming up.

**Comment by ghprince** [comment]
Hmmm I have the same issue too... now warning on local dev setup but always shows up on Heroku
```
app web.1 - - [3] Puma starting in cluster mode...
app web.1 - - [3] * Version 2.12.2 (ruby 2.2.2-p95), codename: Plutonian Photo Shoot
app web.1 - - [3] * Min threads: 5, max threads: 5
app web.1 - - [3] * Environment: production
app web.1 - - [3] * Process workers: 2
app web.1 - - [3] * Preloading application
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : To prevent agent startup add a NEWRELIC_AGENT_ENABLED=false environment variable or modify the "production" section of your newrelic.yml.
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Starting the New Relic agent in "production" environment.
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Reading configuration from config/newrelic.yml (/app)
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Environment: production
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Installing Rails 3+ middleware instrumentation
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Installing Rack::Builder middleware instrumentation
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Installing Rails 4 Controller instrumentation
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Dispatcher: Puma
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Application: 
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Installing Net instrumentation
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Installing deferred Rack instrumentation
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Installing Rails 4 view instrumentation
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Installing Rails 4 Error instrumentation
app web.1 - - ** [NewRelic][08/05/15 04:17:36 +0000 web.1 (3)] INFO : Finished instrumentation
app web.1 - - [3] ! WARNING: Detected 2 Thread(s) started in app boot:
app web.1 - - [3] - Worker 1 (pid: 22) booted, phase: 0
app web.1 - - [3] * Listening on tcp://0.0.0.0:24407
app web.1 - - [3] ! #<Thread:0x007f4c477ee240@/app/vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.12.1.298/lib/new_relic/agent/threading/agent_thread.rb:12 sleep> - /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
app web.1 - - [3] ! #<Thread:0x007f4c47566298@/app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:80 sleep> - /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:82:in `sleep'
app web.1 - - [3] Use Ctrl-C to stop
app web.1 - - [3] - Worker 0 (pid: 8) booted, phase: 0
```

**Comment by evanphx** [comment]
@ghprince this is a warning to you that, because you used preload and workers, a thread was created in the parent process that won't be inherited into the workers. Either turn off preload or be sure to add something in `on_worker_boot` to recreate the threads.

**Comment by ghprince** [comment]
@evanphx thx a lot for the explanation! just curious what would be impact of this? to me the app seems to be running ok and new relic reporting are also normal, is there anything might go wrong?
