### ISSUE TITLE
Using `tmp/puma/pid` versus `shared/tmp/pids/puma.pid`

### ISSUE THREAD

**Issue by paulepanter** [puma/puma#618]
Hi. The Jungle scripts assume the following locations.

    tools/jungle/init.d/puma:  PIDFILE=$1/tmp/puma/pid
    tools/jungle/init.d/puma:  PIDFILE=$1/tmp/puma/pid
    tools/jungle/init.d/puma:  STATEFILE=$1/tmp/puma/state
    tools/jungle/init.d/puma:  PIDFILE=$1/tmp/puma/pid
    tools/jungle/init.d/puma:    pumactl --state $dir/tmp/puma/state restart
    tools/jungle/init.d/puma:  PIDFILE=$1/tmp/puma/pid
    tools/jungle/init.d/puma:    pumactl --state $dir/tmp/puma/state stats

The Gem [Capistrano::Puma](https://github.com/seuros/capistrano-puma) has the defaults below.

    set :puma_env, -> { fetch(:rack_env, fetch(:rails_env, fetch(:stage))) }
    # Configure "min" to be the minimum number of threads to use to answer
    # requests and "max" the maximum.
    set :puma_threads, [0, 16]
    set :puma_workers, 0
    set :puma_rackup, -> { File.join(current_path, 'config.ru') }
    set :puma_state, -> { File.join(shared_path, 'tmp', 'pids', 'puma.state') }
    set :puma_pid, -> { File.join(shared_path, 'tmp', 'pids', 'puma.pid') }
    set :puma_bind, -> { File.join("unix://#{shared_path}", 'tmp', 'sockets', 'puma.sock') }
    set :puma_conf, -> { File.join(shared_path, 'puma.rb') }
    set :puma_access_log, -> { File.join(shared_path, 'log', 'puma_access.log') }
    set :puma_error_log, -> { File.join(shared_path, 'log', 'puma_error.log') }
    set :puma_init_active_record, false
    set :puma_preload_app, true
    set :puma_prune_bundler, false

These can be changed of course to use the upstream Puma default in `tmp/puma/` so that the init scripts work correctly.

On the other hand, it’d be great if the Jungle and Capistrano scripts would be compatible by default.

Currently I can only think of either changing the paths in Capistrano::Puma to achieve that. On the other hand, using different paths in Capistrano::Puma (or Puma’s configuration file `puma.conf`) is incompatible with the Jungle script, as the location is hardcoded there as seen above.

@seuros, could you tell us why you diverted from the upstream Puma defaults? Because “your” paths are Capistrano best practices?

Please tell me, what you think the best solution is? Should the Jungle scripts be adapted, to read the Puma config file or make the paths configurable at the top?

On the other hand, Puma::Capistrano could provide it’s own init scripts just executing `cap puma:start`, `cap puma:stop`, `cap puma:restart` and so on.

**Comment by Epigene** [comment]
I would like to see configuration moving in the `shared/tmp/pids/puma.pid` direction because storing the pid in a specific release's directory makes the pidfile vulnerable to being lost if last release identifier changes, such as on deploy, rollback, black magic etc.

Whereas being stored in the shared folder it will always be easy to find.

**Comment by evanphx** [comment]
I encourage you to copy the jungle scripts into your own repo and begin to work on them there. I'm likely going to split them out soon anyway.
