### ISSUE TITLE
Chunked request bodies are not supported

### ISSUE THREAD

**Issue by javanthropus** [puma/puma#620]
If I understand the HTTP RFC correctly, an HTTP 1.1 web server must support chunked request bodies.  As of version 2.10.2, Puma does not and instead treats any such request as having no body at all.  This inability of Puma was originally raised as issue #80 which has been closed without resolution.  Please see that issue for the reasons.  My hope is that this issue addresses those reasons better so that we can add support for this.

A simple Rack app demonstrates the problem:

```ruby
run proc { |env| [200, {}, [env['rack.input'].read.bytesize.to_s]] }
```

Run that with Puma and use curl to upload some data in a request using the chunked transfer encoding:

```bash
dd if=/dev/zero bs=1 count=10240 |
  curl -v -X POST -H 'Transfer-Encoding: chunked' --data-binary @- localhost:9292
```

Under Puma, the response reports that the request body contained 0 bytes.  This works correctly under Unicorn and reports 10240 bytes.

Interestingly, sending 1024 bytes or less in the request causes Puma to complain on the server side that the request could not be parsed even though the Rack app returns a response code of 200.  Larger requests do not trigger the server side exception.

```
127.0.0.1 - - [11/Dec/2014 08:55:04] "POST / HTTP/1.1" 200 - 0.0001
2014-12-11 08:55:04 -0600: HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>
2014-12-11 08:55:04 -0600: ENV: {"rack.version"=>[1, 2], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "CONTENT_TYPE"=>"text/plain", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"2.10.2", "GATEWAY_INTERFACE"=>"CGI/1.2"}
```

I discovered this issue while attempting to host grack with Puma.  After a certain threshold (somewhere less than 7MB), git will chunk commits during a push operation in order to enable streaming, so the fix for this needs to avoid attempting to dump the entire request body into a temporary file prior to handing the content to the app since those requests are unbounded in size.  It needs to wrap the socket content in a streaming decoder for chunked data and pass that up to the app.

**Comment by bbozo** [comment]
I'd like to give this a go if it's not overly complicated, or plan B switch to Trinidad and cross fingers and I hate Tomcat with equal passion with which I love puma <3

@evanphx can you maybe point me in a good direction how to tackle this?

**Comment by thom-nic** [comment]
@bbozo wow interesting that you just commented on this.  I recently ran into issues with chunked Transfter-Encoding across a number of different Ruby HTTP servers (Puma being one of them.)  

I want to reference [this rails issue](https://github.com/rails/rails/issues/15079) for context then make a suggestion...

If you follow the (somewhat confusing) precedent that Webrick/ Unicorn/ Rainbows set (see linked issue above) you'll be passing along a request that `ActionDispatch::Request` fails to handle correctly if the `Content-Length` header is still missing.

So I'd suggest taking one of the two approaches:

1.  Parse & reassemble the chunked data, reassign `env['rack.input']` to the decoded body, **and** add a `Content-Length` header.  I'd also remove the `Transfer-Encoding` header, at which point rack/rails can be oblivious to the fact that the request was ever chunked.

2.  Simply read the full request body, don't decode it, and pass it along to rack.  This is more of a "hands-off" approach which IMO is still valid **but** requires the user to add [rack middleware](https://gist.github.com/thom-nic/8b586749d3b88bef8c59) to actually decode the request.  Another example which I think validates this approach is [this middleware for handling Content-Encoding](https://gist.github.com/relistan/2109707)

That said, I want to say thanks for tackling this!  I was rather surprised when I figured out [thin doesn't support this](https://github.com/macournoyer/thin/pull/71) then I tried Puma which didn't work either :)

**Comment by thom-nic** [comment]
@bbozo if you want to try your hand at this, it looks like [this is where you need to start](https://github.com/puma/puma/tree/master/ext/puma_http11).  Unfortunately I'm not familiar with Ragel so it's all a bit of a mystery to me.

**Comment by javanthropus** [comment]
Since Unicorn already does this, it may also be useful to check out how this is done in its fork of the parser: http://bogomips.org/unicorn.git/tree/ext/unicorn_http.

**Comment by thom-nic** [comment]
Well that's certainly helpful.  I didn't realize the projects share a common code ancestor.  Unfortunately ragel still seems *way* too far over my head for me to contribute a patch in the near future.

**Comment by bbozo** [comment]
Indeed :) https://github.com/defunkt/unicorn/commit/81026ea66279695206ea53287427c05281662572#diff-35c8f85f334e5bc83c3623ac6e9f4f94

I'll take a look, maybe we can beg for help some of the guys from unicorn too ^_^

**Comment by fedesoria** [comment]
Is there any workaround for this?

**Comment by bbozo** [comment]
Hi :) for the moment, it seems this is the only solution: http://atnan.com/blog/2008/08/08/transfer-encoding-chunked-or-chunky-http/

We fixed our use case with a free tier Amazon EC2 VM to fix the requests, our plan is to make uploads go directly to S3 in the future - which is really the better option for us anyway

I'm interested in playing with this, I just need to get some slack of my work to be able to tackle it and learn some ragel :)

**Comment by chewi** [comment]
This is something I'd like to have but I'm not desperately needing it right now. If it were to be done, I'd like to have the option for Puma not to dechunk the request in the middle because otherwise you'd lose some of the benefit. I'd be putting this in front of Grape, which might handle this better than Rails. I used to fetch large CSV files over SFTP and load them on the fly, sometimes even decompressing them and decrypting them in the process. It would be nice to be able to do the same over HTTP.

**Comment by marianandre42** [comment]
+1
