### ISSUE TITLE
Add option to Puma’s config file to set environment variables like `JAVA_OPTS`

### ISSUE THREAD

**Issue by paulepanter** [puma/puma#621]
Both the Jungle and Capistrano scripts execute `puma` or `pumactl` and pass Puma’s configuration file.

    $ nl config/puma/run-puma 
         1	#!/bin/bash
         2	app=$1; config=$2; log=$3;
         3	cd $app && exec bundle exec puma -C $config 2>&1 >> $log

From [Capistrano::Puma’s](https://github.com/seuros/capistrano-puma) task `puma:start`:

          execute :bundle, 'exec', :puma, "-C #{fetch(:puma_conf)} --daemon"

It’d be great if the environment variable could be passed using the config file. Would that possible or not, because the executable is already started when reading the config file and changing these Java (and Puma) run-time things is not possible anymore? Is there a better solution for passing the environment variables like `JAVA_OPTS` to Puma?

**Comment by evanphx** [comment]
Probably.
