### ISSUE TITLE
Whem puma run as daemon xmpp4r in initializer disconnects

### ISSUE THREAD

**Issue by FlySnake** [puma/puma#624]
I've got an initializer which starts xmpp4r client. It works fine when I run puma server as a regular process. But when I start puma as a daemon (-d option) it works for a few seconds and disconnects from the xmpp server. I've got separate thread which handles reconnects, but it doesn't work when puma is a daemon.
```
def init_reconnection_timer
    timers = Timers::Group.new
    periodic_timer = timers.every(5) do
      if @client.is_disconnected?
        begin
          Rails.logger.info "XmppConnector ##### reconnecting to #{APP_CONFIG['broker_address']} ..."
          connect
          Rails.logger.info "XmppConnector ##### connected!"
          presence
        rescue
        end
      end
    end
    Thread.new do
      loop do
        timers.wait
      end
    end
  end
```
I've got nothing from this code in log when puma is a daemon. Right after rails app start it works for a few seconds before puma is demonized. Then silently disconnects. Probably because of my thread starts before puma demonizing.
MIN:MAX threads option has no effect. 
How can I debug this?

**Comment by evanphx** [comment]
You're probably using `preload`, don't use it. That will fix the problem.
