### ISSUE TITLE
forking from Puma: how to do access parent socket?

### ISSUE THREAD

**Issue by riffraff** [puma/puma#638]
I have an app that forks child processes from a puma server, and I'd like to release the listening socket in the child processes to avoid the situation where the puma server dies and gets restarted but the socket is already in use until the child process is alive.  

I _think_ the right way to do it could be through `ENV['rack.hijack']` and `ENV['rack.hijack_io']` but it would be nice if this was documented somewhere.

**Comment by evanphx** [comment]
Well, it's not exposed. If you'd like it exposed, I'd take a look at a PR.

**Comment by riffraff** [comment]
Thanks for your reply, in the meantime I have solved horribly by using reflection to get ahold of the socket, but I could try to write a PR.

I realize now that the variables in ENV refer to the accepted socket rather than the listening one (i.e.  `TCPSocket`rather than the `TCPServer` that I'd actually needed). 

I am not sure if I should expose something like `ENV['puma_binder']` to match `@binder` in `Puma::Server` the way it seems to be done for `ENV['puma_socket']`, or if there is a way to get a handle of the current server which I'm currently missing, could you clarify what you'd think would be the ouma way of doing it?

Also, should this be made available only if a specific config option is enabled or made available in general?

Thanks.

**Comment by evanphx** [comment]
I think it needs to be abstracted. So something like `Puma.clean_for_fork` or something that closes the sockets, would be best.

**Comment by riffraff** [comment]
ok, but that brings me back to the issue that I couldn't find a globally
accessible reference to the current running Puma::Server, or the
Puma::Runner that contains it, nor a way to find "who is running me" in a
generic rack app.

The only way in which I can get access to the current server (that I could
find) is in Rack::Handler::Puma which appears to be a singleton object with
class-level methods, but I'm not sure Rack::Handler::Puma.clean_for_fork
makes total sense.

I can get a reference to the Server via ObjectSpace or register the runner
with a class-level list on initialize but I'm not sure it's a good idea.


Sorry If I'm making stupid comments, but I'm just getting familiar with the
code base, and thanks for your patience.



On Wed, Jan 21, 2015 at 6:57 PM, Evan Phoenix <notifications@github.com>
wrote:

> I think it needs to be abstracted. So something like Puma.clean_for_fork
> or something that closes the sockets, would be best.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puma/puma/issues/638#issuecomment-70887256>.
>



-- 
twitter: @riffraff
blog (en, it): www.riffraff.info
work: circleme.com

**Comment by evanphx** [comment]
We can add a mechanism to allow that to be read. Perhaps a new env key that contains the "Puma runtime information".
