### ISSUE TITLE
documentation for exception handler

### ISSUE THREAD

**Issue by jjb** [puma/puma#641]
This ticket mentions a user defined low-level exception handler: https://github.com/puma/puma/pull/477

Is there any documentation for this? If there isn't any, where is it in the code? I can submit a PR with docs.

**Comment by evanphx** [comment]
There is configuration for it but no docs because it's generally not used. Feel free to submit a PR with docs.

**Comment by jjb** [comment]
@evanphx done https://github.com/puma/puma/pull/686/
