### ISSUE TITLE
Jungle documentation for RVM

### ISSUE THREAD

**Issue by ain** [puma/puma#643]
I've been having an headache setting up Puma with RVM and I'm still failing at it. Would be good if https://github.com/puma/puma/tree/master/tools/jungle/init.d also included the necessary process for RVM users.

**Comment by evanphx** [comment]
The jungle scripts are maintained by users, not by myself and are provided mostly as an example.

What kind of issue are you having with RVM?

**Comment by ain** [comment]
I haven't reached a stable setting with jungle + RVM so that it'd run multiple sites on different ports in parallel. `rvmsudo` gets it running, but one process goes down shortly after launching. Hard to debug as well, I have no info on the errors. 

Is there a debug flag or something that could be used to scope?

**Comment by mensfeld** [comment]
@evanphx  @ain  here you go: http://dev.mensfeld.pl/2014/02/puma-jungle-script-fully-working-with-rvm-and-pumactl/

**Comment by kayakyakr** [comment]
Can we add rvm & bundle-ready versions of the init.d and run-puma scripts to the repository and modify the capistrano scripts to be able to install these? I think that would be helpful.

**Comment by ain** [comment]
:+1: on @kayakyakr suggestion for automating this part.

**Comment by evanphx** [comment]
PR accepted!
