### ISSUE TITLE
How to set the backlog size for a unix socket ?

### ISSUE THREAD

**Issue by bpaquet** [puma/puma#645]
As I can see in code, listen is not call for unix socket. It's call for tcp.

Do you have a specific reason to do that ?

**Comment by evanphx** [comment]
There currently is one because I didn't think it made a whole lot of sense, given it's always on the local machine and thusly behind another load balancer. Can you tell me why you'd want to set it?

**Comment by bpaquet** [comment]
I was searching a way to limit the number of request queued in puma.
Backlog can be a solution, but I realized after the question that puma
queued requests internally. So changing backlog do nothing for limiting the
number of concurrent request.

The 2.11 add a new option queue_request. If I disable request queuing,
backlog can be set to limit concurrency. But a load balancer like Haproxy
can do this before Puma. So, no real usage of backlog on unix socket :(

But I think disabling queue_request will increase latency. Correct ?

Anyway, thx you for you answer

**Comment by evanphx** [comment]
Using queue_request will increase latency, yes. Could you tell me about your use case? Why are you looking to disable request queueing?

**Comment by bpaquet** [comment]
Because request queueing in the process, not in socket can have lot of side effects :(
