### ISSUE TITLE
Puma hangs when starting

### ISSUE THREAD

**Issue by nachogiljaldo** [puma/puma#649]
Hi there!

I am facing a tricky problem in which my puma server freezes when starting. This is my data:
* JRuby 1.7.14
* Puma 2.11.0 (it happened also with 2.7.x and 2.9.0)
* Using pumactl start/stop (the issue happens with puma as well anyway, it seems doing puma -C config/puma.rb start triggers it more easily)

These are the relevant parts of my puma.rb:
```ruby
#!/usr/bin/env puma
application_path = "."
directory application_path
environment ENV["RAILS_ENV"]
daemonize true
pidfile "#{application_path}/tmp/pids/puma-#{railsenv}-#{instance}.pid"
state_path "#{application_path}/tmp/pids/puma-#{railsenv}-#{instance}.state"
  stdout_redirect "#{application_path}/log/puma-#{railsenv}.stdout.log", "#{application_path}/log/puma-#{railsenv}.stderr.log"
threads 0, 16
socket_file = "#{application_path}/tmp/sockets/#{railsenv}-#{instance}.socket"
bind "unix://#{socket_file}"
```

I tried to trace the problem and everything seems to happen in jruby_restart.rb. Sometimes (still don't know why) the call to execlp seems to freeze leaving the child process in sleep status (as well as the parent, since the children will never kill SIGUSR2). Actually if I kill -SIGUSR2 the master, the master just finishs normally, which basically reduces the problem to the children.

An improvement would be already that the sleep of the parent wouldn't be eternal. However, I still don't get why the child process (which seems to be working fine) it just suddenly sleeps.

```bash
0 S jose      6422 11011  2  80   0 - 1027689 futex_ 23:33 pts/4  00:00:04 /opt/software/development/jdk1.8.0_25/bin/java -Djdk.home= -Djruby.home=/home/jose/.rvm/rubies/jruby-1.7.14 -Djruby.script=jruby -Djruby.shell=/bin/sh -Djffi.boot.library.path=/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni/i386-Linux:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni/arm-Linux:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni/x86_64-Linux -Xss2048k -Dsun.java.command=org.jruby.Main -cp  -Xbootclasspath/a:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jruby.jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djruby.compile.mode=OFF -Djruby.compile.invokedynamic=false -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Xmx1024m -Djruby.cext.enabled=true -XX:+TieredCompilation -XX:TieredStopAtLevel=1 org/jruby/Main --dev /home/jose/.rvm/gems/jruby-1.7.14/bin/jruby_executable_hooks /home/jose/.rvm/gems/jruby-1.7.14/bin/puma -C config/puma.rb start
1 S jose      6448  6422  0  80   0 - 1027689 futex_ 23:33 pts/4  00:00:00 /opt/software/development/jdk1.8.0_25/bin/java -Djdk.home= -Djruby.home=/home/jose/.rvm/rubies/jruby-1.7.14 -Djruby.script=jruby -Djruby.shell=/bin/sh -Djffi.boot.library.path=/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni/i386-Linux:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni/arm-Linux:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jni/x86_64-Linux -Xss2048k -Dsun.java.command=org.jruby.Main -cp  -Xbootclasspath/a:/home/jose/.rvm/rubies/jruby-1.7.14/lib/jruby.jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djruby.compile.mode=OFF -Djruby.compile.invokedynamic=false -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -Xmx1024m -Djruby.cext.enabled=true -XX:+TieredCompilation -XX:TieredStopAtLevel=1 org/jruby/Main --dev /home/jose/.rvm/gems/jruby-1.7.14/bin/jruby_executable_hooks /home/jose/.rvm/gems/jruby-1.7.14/bin/puma -C config/puma.rb start
```
By now my theory is that there is some kind of race condition between the parent going to sleep and the execlp() call.

No exception can be seen. There is also an strange phaenomena, I am trying to log the values of argv and cmd in JRubyRestart.daemon_start method, however, when it hangs, it fails if I try to do (as an example) puts "#{argv} #{argv}", I guess it has something to do and it is hanging when trying to call execlp with those 2 parameters (could it be that is the thing that causes the process to sleep). But to be sincere, I don't really know whether this problem happens because it freezes or exactly why.

Any ideas?

**Comment by nachogiljaldo** [comment]
Got some more info:
```bash
Process 7521 attached
restart_syscall(<... resuming interrupted call ...>) = -1 ETIMEDOUT (Connection timed out)
futex(0x7fd61800b728, FUTEX_WAKE_PRIVATE, 1) = 0
write(1, "Continues here 7521.", 20)    = 20
write(1, "\n", 1)                       = 1
write(1, "None is null", 12)            = 12
write(1, "\n", 1)                       = 1
write(1, "Ey still here", 13)           = 13
write(1, "\n", 1)                       = 1
lseek(4, 1257095, SEEK_SET)             = 1257095
read(4, "PK\3\4\24\0\10\10\10\0\vq\33E\0\0\0\0\0\0\0\0\0\0\0\0.\0\0\0", 30) = 30
lseek(4, 1257171, SEEK_SET)             = 1257171
read(4, "\215SmO\323`\24=\3176\3261\213TD\231\210\10R\331@\245\202\202/#&\10[X\334\213"..., 616) = 616
futex(0x7fd61800bb54, FUTEX_WAIT_PRIVATE, 525, NULL
```

It seems is reading something don't know exactly what it is.

**Comment by nachogiljaldo** [comment]
I found that I can (or so it seems) prevent the deadlock by making sure the process is not a daemon in my config/puma.rb and initializing just the strictly necessary things in case it is not.

**Comment by evanphx** [comment]
Honestly, don't use daemonize on JRuby at all. It's very difficult to implement a daemon on the JVM and all kinds of weird bugs show up. Use a process monitor instead.

**Comment by nachogiljaldo** [comment]
If it doesn't work, wouldn't it make sense disabling it and/or adding it to the documentation? I spent a lot of time investigating this issue (which was fun and since this is a personal project I could do it without much time pressure), but it would have been nice to know!

Anyway, if it helps anyone, the issue seems to be gone (or at least I could not reproduce it) if you run certain commands in the puma.rb only if the current process is the daemon one:
```ruby
already_daemon = ENV.key?("PUMA_DAEMON_PERM") || ENV.key?("PUMA_DAEMON_RESTART")
```
I have the feeling it is somehow related to the socket file, because usually deleting the file was fixing the problem and the next time it would restart...

**Comment by evanphx** [comment]
It does work, it's just subject to very specific JVM conditions and that's why you get these kinds of weird bugs. In all honesty, I feel like, over all, daemon mode was probably a mistake. It causes more problems and generally let's people get away with deploying without monitoring, which is bad.

@nachogiljaldo What commands are you running in puma.rb?
