### ISSUE TITLE
To add limit memory usage function

### ISSUE THREAD

**Issue by poc7667** [puma/puma#652]
As title, Is it possible to limit puma servers max memory usage and CPU usage ?

Because there are many rails apps are running on my EC2 server

I need to limit each app's resource. To avoid some app's spend too much resources.

Is the function available in the future? Thanks

**Comment by evanphx** [comment]
No, puma doesn't have that ability. You can use linux cgroups to limit memory to a set of processes though, if that's what you want.

**Comment by nateberkopec** [comment]
People reading this may also be interested in https://github.com/schneems/puma_worker_killer
