### ISSUE TITLE
Puma 2.11 does not start with bundler 1.8 & prune_bundler

### ISSUE THREAD

**Issue by dvrensk** [puma/puma#653]
I created a new server today, and RVM installed bundler 1.8 for me.  This is what happens when I try to start puma:

```
~/app/current$ bundle exec puma 
* Pruning Bundler environment
/usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'rack' (= 1.5.2) among 15 total gem(s) (Gem::LoadError)
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/dependency.rb:309:in `to_spec'
	from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
	from /home/simba/app/shared/bundle/ruby/2.1.0/gems/puma-2.11.0/bin/puma-wild:20:in `block in <main>'
	from /home/simba/app/shared/bundle/ruby/2.1.0/gems/puma-2.11.0/bin/puma-wild:18:in `each'
	from /home/simba/app/shared/bundle/ruby/2.1.0/gems/puma-2.11.0/bin/puma-wild:18:in `<main>'
```

This is my `config/puma.rb`:

```ruby
workers 3
threads 2, 6
directory "/home/simba/app/current"
pidfile "/home/simba/app/shared/pids/puma.pid"

rackup      DefaultRackup
bind 'unix:///tmp/.rails3app'
environment 'production'
prune_bundler

# Use this with phased restarts (not preload_app)
on_worker_boot do
  $start_order_queue_processor = true
  $start_queue_processor = true
end
```

I've manually downgraded bundler to 1.7.12 and everything works.

**Comment by NickLaMuro** [comment]
We ran into the same issue on our end.  For what it is worth, removing the `prune_bundler` option seemed to allow us to deploy again.

**Comment by evanphx** [comment]
Sounds like perhaps prune_bundler broke. I'll take a look.

**Comment by SavithaK** [comment]
FWIW, we are seeing the same issue as well.

**Comment by evanphx** [comment]
@indirect would you be willing to chime in here? Did bundler change anything that might break this code: https://github.com/puma/puma/blob/master/lib/puma/cli.rb#L462-L489 ?

**Comment by evanphx** [comment]
Hm, I'm not able to reproduce this yet. @SavithaK could you provide some details on what your app is and what the output is?

**Comment by SavithaK** [comment]
Our app uses puma with rails (MRI). With bundler v1.8, puma would continuously start and crash. Exception was the same as @dvrensk specified above. 
We've redeployed without prune_bundler as a workaround. 

Our puma config looks like this:
threads 8,32
workers 16
bind "unix:///tmp/service.puma.sock"
environment "production"
pidfile "/opt/service/current/tmp/pids/puma.pid"
activate_control_app 'tcp://0.0.0.0:8081', { no_token: true }
directory '/opt/service/current'
prune_bundler

# Log puma output to files
stdout_redirect '/opt/service/current/log/puma.stdout.log',
  '/opt/service/current/log/puma.stderr.log', true

# Read VERSION file for git SHA
@git_sha = File.exists?('/opt/service/current/VERSION') &&
  File.read('/opt/service/current/VERSION')[0,8]

# Tag master process with git SHA
tag @git_sha

# Log worker boot with git SHA
on_worker_boot do
  puts "[#{Process.pid}] Booting puma worker: git rev #{@git_sha}" if @git_sha
end

**Comment by SavithaK** [comment]
Also some version details:
Rails: 4.1.5
Ruby: 2.1.4
Puma: 2.9.2

**Comment by indirect** [comment]
Nothing changed that would effect that code that I know of, but I guess something did. FWIW the backtrace doesn't include anything but Rubygems, so it seems likely that the pruned load path somehow doesn't include rack.

**Comment by evanphx** [comment]
@dvrensk @NickLaMuro @SavithaK Would you be willing to gist your Gemfiles? I want to see if maybe you've got puma configured in such a way that is causing issues.

I was just reviewing the code that I'm noticing that I didn't pull over any load path, which makes me would cause this bug. But then I wonder why reverting back to a previous bundler release fixes it... 

At any rate, this gives me something to go on. Will report shortly.

**Comment by evanphx** [comment]
@dvrensk @NickLaMuro @SavithaK Can you run `gem env` and `gem list` in the same environment you run `bundle exec puma` and gist the output?

**Comment by dvrensk** [comment]
I've gisted `Gemfile` and the output of `gem env` and `gem list` here: https://gist.github.com/dvrensk/f28d4c5bcf91582b2b46

The only difference between the broken environment and what I have now is that I have run `gem uni bundler`, `gem i bundler -v 1.7.12`.

Thanks for your help!  Let me know if there is anything more I can do.  (If you want me to really recreate the problem by launching a new server running bundler 1.8.0 I can do that too, although not immediately.)

**Comment by NickLaMuro** [comment]
@evanphx I am looking into it a bit myself since I have a bit of free time today.  I will get back to about the Gemfile, but since it isn't "my code to share", I don't want to just copy-pasta the Gemfile in since it is using Gemfury for some of the sources.  I will work on a stripped down dummy app to recreate this via vagrant to hopefully help things out.

In regards to what I can share, we are actually using multiple versions of puma.  2.9.0, 2.9.1, and 2.10.0 are the ones that I just quickly checked on the about 10 different apps running puma as the app server.  The only changed that happened yesterday that would affect this is bundler, and that is because we have some deploy automation code in place that auto upgrades bundler for us.  The release that happened yesterday seems to have then caused this to fail in multiple places.

I tracked down the failure in `puma-wild` to [here](https://github.com/puma/puma/blob/4332f86fbaa/bin/puma-wild#L10) for `2.9.1`, and that seems to match the stacktrace that @dvrensk ran into for `2.11.0` (https://github.com/puma/puma/blob/e8feadd2b/bin/puma-wild#L20).  I have had trouble recreating it locally myself, and the closest I have gotten is by running the command passed to `Kernel.exec` with `sudo -u <my_user_name>`, which is similar to how we handle it in our init scripts.

This backs up the theory you seem to be having that it is an ENV issue change with bundler, so I will see what I can do to get you more information to prove/disprove that thought.

**Comment by NickLaMuro** [comment]
I just realized that because I am using `.rvm`, my tests locally are going to be fruitless when using `sudo -u` because it won't pull in the `.bashrc` env to get RVM into the load path :disappointed:.  I will probably get you some Vagrant config once I get that going.

**Comment by evanphx** [comment]
@dvrensk that `gem list` output is odd. If you run `bundle`, does gems like puma and rack show up? @indirect shouldn't running `bundle` actually install the gems into the gem path? That's what I've always seen... what am I missing?

**Comment by evanphx** [comment]
I have isolated the issue and it's a change in a behavior of the value of GEM_HOME between 1.7 and 1.8 when `bundle install --path` is used. I'm talking with @indirect to figure out which behavior is the correct one.

**Comment by evanphx** [comment]
@dvrensk @NickLaMuro can you confirm that you're using `bundle install --path`?

**Comment by evanphx** [comment]
I'm going to go ahead and release this fix since it's active and in the wild. @dvrensk / @NickLaMuro please let me know if 2.11.1 does or does not fix your issue?

**Comment by SavithaK** [comment]
Thanks for looking at this @evanphx and sorry I wasn't able to help out much today. Yes, we do use bundle install --path. I have some time now, if you need any other info.

**Comment by SavithaK** [comment]
Upgraded one of our apps to 2.11.1 and seeing something odd. When using pumactl to start the app, I get:
bundle exec pumactl -F config/puma/staging.rb start
* Pruning Bundler environment
/opt/exceptions/shared/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/cli.rb:295:in `parse_options': invalid option: -F (OptionParser::InvalidOption)
from /opt/exceptions/shared/bundle/ruby/2.1.0/gems/puma-2.11.1/lib/puma/cli.rb:453:in `run'
from /opt/exceptions/shared/bundle/ruby/2.1.0/gems/puma-2.11.1/bin/puma-wild:31:in `<main>'

I don't see this in the other apps that are running puma version 2.9.2. I'll dig around some more in case this is unrelated.

**Comment by SavithaK** [comment]
Actually the other apps have prune-bundler removed too. So that's another difference.

**Comment by SavithaK** [comment]
curl --silent --show-error http://localhost:8081/restart works, however

**Comment by NickLaMuro** [comment]
@evanphx Yup, all our apps are installing gems using `bundle install --path`, so that seems like the likely culprit.

**Comment by NickLaMuro** [comment]
Also confirmed that applying that fix solves our issue!  Great work on this and sorry I wasn't more help.

**Comment by dvrensk** [comment]
Yes, we are using `--path` (`bundle install --gemfile /home/simba/app/releases/20150209113217/Gemfile --path /home/simba/app/shared/bundle --deployment --quiet --without development test` to be specific).
I'm launching a new server now to see if 2.11.1 solves the problem.  Thanks a lot!  And I'm sorry about the time zone delays.

**Comment by ball-hayden** [comment]
Apologies for bumping an old issue, but I'm seeing the following:

```
[sparkseat@localtest current]$ puma -v
puma version 2.11.2
[sparkseat@localtest current]$ bundle exec pumactl -F config/puma.rb start
* Pruning Bundler environment
/var/www/sparkseat_api/shared/bundle/ruby/2.1.0/gems/puma-2.11.2/lib/puma/cli.rb:534:in `parse_options': invalid option: -F (OptionParser::InvalidOption)
	from /var/www/sparkseat_api/shared/bundle/ruby/2.1.0/gems/puma-2.11.2/lib/puma/cli.rb:190:in `run'
	from /var/www/sparkseat_api/shared/bundle/ruby/2.1.0/gems/puma-2.11.2/bin/puma-wild:31:in `<main>'
```

We are also installing gems using bundle install --path
