### ISSUE TITLE
pumactl and SIGUSR2 have no effect

### ISSUE THREAD

**Issue by ianwalter** [puma/puma#655]
I've tried:
* `pumactl restart -P tmp/pids/server.pid`
* `pumactl restart -F config/puma.rb`
* `kill -s SIGUSR2 $(cat tmp/pids/server.pid)`
* `pumactl restart -p $(cat tmp/pids/server.pid)`  
(each using absolute paths as well)  
And none of them have any effect.

I'm running my server within a Docker container (root) so I'm wondering if that has something to do with it.
Here's some other info:
* ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
* Rails 4.2.0
* puma version 2.11.0
* puma.rb:
```ruby
#!/usr/bin/env puma
directory     '/app'
pidfile       '/app/tmp/pids/puma.pid'
state_path    '/app/tmp/pids/puma.state'
prune_bundler
bind          'tcp://0.0.0.0:3000'
```

**Comment by evanphx** [comment]
Well, first of all, is that pid file correct? You should check that.

How are you running these commands? Outside the container or inside?

**Comment by ianwalter** [comment]
That is the correct pid file. Just realized puma is ignoring puma.rb even though it's in the config directory. I was running `rails s -b 0.0.0.0` originally, but changing it to `puma -C config/puma.rb` doesn't seem to fix the problem, although the config is no longer ignored. I'm running the restart commands inside of the container using docker exec. I'm sorry I forgot to mention that the pumactl commands return:
```
Neither pid nor control url available
```

**Comment by ianwalter** [comment]
So the pid is 1 according to `ps` I guess since there's only one process running within the container. The pid file does contain 1. But I still get that message even when I pass 1 directly with `-p`

**Comment by evanphx** [comment]
This should be fixed now.
