### ISSUE TITLE
on_worker_boot can't find ActiveSupport constant on Rails 4.2

### ISSUE THREAD

**Issue by tbuehlmann** [puma/puma#656]
Using Puma 2.11.1, having a vanilla Rails 4.2.0 app, the following puma.rb can't find the `ActiveSupport` constant:

```rb
# config/puma.rb

workers 4

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

Output:

```
config/puma.rb:4:in `block in _load_from': uninitialized constant ActiveSupport (NameError)
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:210:in `call'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:210:in `block in worker'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:210:in `each'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:210:in `worker'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:108:in `block (2 levels) in spawn_workers'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:108:in `fork'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:108:in `block in spawn_workers'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:105:in `times'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:105:in `spawn_workers'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cluster.rb:379:in `run'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/lib/puma/cli.rb:512:in `run'
	from /home/tobias/.gem/ruby/2.2.0/gems/puma-2.11.1/bin/puma:10:in `<top (required)>'
	from /home/tobias/.gem/ruby/2.2.0/bin/puma:23:in `load'
	from /home/tobias/.gem/ruby/2.2.0/bin/puma:23:in `<main>'
```

Shouldn't we be able to call stuff like that in an `on_worker_boot` call as described on several websites?

**Comment by evanphx** [comment]
That's only possible (and necessary) when `preload` is used. You're not using preload and thus don't need any `on_worker_boot` code.

**Comment by tbuehlmann** [comment]
Ah, okay. So if I wanted to run one-time code (depending on a gem from the Gemfile)

**Comment by tbuehlmann** [comment]
Ah, didn't know that, thanks.

**Comment by david-pm** [comment]
For posterity, if you run into this error and preloading the app isn't your issue, make sure you are including ActiveRecord in your application.rb: `require 'active_record/railtie'`

**Comment by jjb** [comment]
in case it helps someone finding this: 

I was befuddled by this problem being present in one environment but not another seemingly identical environment. The problem ended up being that I was using puma's newish default behavior to use preboot if using 2 or more workers. I was using 1 worker in cluster mode in a staging environment in order to closer approximate prod but with less memory, but I need to use 2 workers to get puma to use preboot as well as cluster.

---
2025 update: see also: https://github.com/puma/puma/pull/3297
