### ISSUE TITLE
Puma hot restart hangs workers

### ISSUE THREAD

**Issue by SavithaK** [puma/puma#659]
We upgraded to Puma 2.11.1 and bundler 1.8.3. It looks like we can no longer hot restart the application. We are running puma in cluster mode. Not all workers go down on restart and this hangs the application (3-6 of them seem to stick around)
Only killing the master process brings the puma process back up.

Puma config:
```
threads 8,32
workers 16
bind "unix:///tmp/service.puma.sock"
environment "production"
pidfile "/opt/service/current/tmp/pids/puma.pid"
activate_control_app 'tcp://0.0.0.0:8081', { no_token: true }
directory '/opt/service/current'
prune_bundler

stdout_redirect '/opt/service/current/log/puma.stdout.log',
  '/opt/service/current/log/puma.stderr.log', true

@git_sha = File.exists?('/opt/service/current/VERSION') &&
  File.read('/opt/service/current/VERSION')[0,8]

tag @git_sha

on_worker_boot do
  puts "[#{Process.pid}] Booting puma worker: git rev #{@git_sha}" if @git_sha
end
```
We see this in the puma log but not much else (This happened when we tried to use phased restart):
[628] Booting puma worker: git rev blah
[18036] - Worker 5 (pid: 628) booted, phase: 1
[18036] - Stopping 18080 for phased upgrade...
[18036] - TERM sent to 18080...
[18036] - TERM sent to 18080...
[18036] - TERM sent to 18080...
[18036] - TERM sent to 18080...
[18036] - TERM sent to 18080...
[18036] - TERM sent to 18080...
[18036] - KILL sent to 18080...
[765] + Gemfile in context: /opt/service/releases/20150225015400/Gemfile

**Comment by evanphx** [comment]
You're using phased upgrade and the output indicates that the worker isn't stopping. The likely reason for that is that there are requests that haven't finished running and so it's waiting. Are you using web sockets or another kind of persistent request?

**Comment by SavithaK** [comment]
We aren't using any kind of persistent requests. This is a new problem that we haven't seen before. The last issue we had was with the bundler update to 1.8 that broke hot restart with prune_bundler. That got fixed with the update to puma 2.11.1. 

The phased restart was just a one off attempt to see if the issue still happened. We are only using hot restart for our deployment.

**Comment by SavithaK** [comment]
@evanphx is there a way we can check what the worker processes are doing? Any worker level logs?

**Comment by SavithaK** [comment]
We stopped all traffic to the box and  the restart worked. It does look like we may have hanging requests that caused the workers to not stop. We'll investigate a bit more.

**Comment by SavithaK** [comment]
It does appear this was because of hung requests.
