### ISSUE TITLE
Multiple request

### ISSUE THREAD

**Issue by thiaguerd** [puma/puma#675]
using -e production: I execute many request and them execute 5 request at a time
using -e production -w 2: execute 6 request at a time
using -e production -t 8:32 -w 3 --preload: execute 6 request at a time
using -e production -t 80:320 -w 30 --preload: execute 6 request at a time
how i can process more of 6 request at a time?

**Comment by evanphx** [comment]
This sounds like an issue with your app. Did you test this against a simple rack app? What did you use to execute the requests?

**Comment by thiaguerd** [comment]
single rack
buttons, click in the button to execute command
I am doing like this
: rails new test_app
: add "gem 'puma'" on Gemfile
: rails g controller multiple index slow
: change method slow to
	def slow
		sleep 5
	end
: export SECRET_KEY_BASE='MY_SECRET_KEY'
: on prodiuction.rb
	config.assets.compile = true
: add on routes
	post ':controller/:action'
	get ':controller/:action'
: index.html.erb 
	<% 20.times do %>
		<%= button_to "Go!", {controller: "multiple", action: "slow"}, remote: true %> 
	<% end %>
	<input type="button" value="Go all!" onclick="$('input').each(function(){$(this).click()})" />
: mv slow.html.erb slow.js.coffee
: in slow.js.coffee
	console.log "done"
using WEBrick: 1 at a time
using puma: 6 at a time
what I need to execute all 20 or more request at a time?

**Comment by nathansamson** [comment]
This looks like your browser limiting number of requests per host.
Op 22 mrt. 2015 6:54 AM schreef "thiaguerd" <notifications@github.com>:

**Comment by evanphx** [comment]
Yes, this is just a symptom of the number of connections your browser chooses to make.
