### ISSUE TITLE
502 Bad Gateway nginx + puma + ruby 2.1.3

### ISSUE THREAD

**Issue by pvijayror** [puma/puma#676]
Help me.
I am not happy after switching unicorn to puma. Before I never faced 502 any issue with unicorn server.
After installing puma server I faced many times "502 Bad Gateway" issue.

**Comment by kcollignon** [comment]
Do you have Nginx configured correctly to the correct upstream server?

**Comment by Epigene** [comment]
Setting up correct puma and nginx configuration can be a headache, here is a gist to what we are running in production at manabalss.lv https://gist.github.com/Epigene/616d397cda078fb2d176

The `location @puma {` line in nginx.conf is key.

**Comment by dt1973** [comment]
@pvijayror it's impossible for us to know without showing us your config files.

**Comment by Telmo** [comment]
I am having similar issue but it stems from the fact that I need both regular and HTTPS traffic. Can puma handle this? So far based on the documentation it can do one or the other but not both?

This is the error in questions, related to https traffic being redirected to puma http:

```
2015/04/30 17:39:38 [error] 509#0: *56 SSL_do_handshake() failed (SSL: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol) while SSL handshaking to upstream, client: 10.10.10.172, server: server.examplet.net, request: "GET / HTTP/1.1", upstream: "https://10.10.0.53:80/", host: "server.examplet.net"
```

Is there a way of actually accomplishing this?

**Comment by evanphx** [comment]
@Telmo nginx should be doing your SSL termination, not puma.
