### ISSUE TITLE
Simple pumactl start on Ubuntu boot

### ISSUE THREAD

**Issue by Epigene** [puma/puma#677]
Hi!

Not a bug, just wondering how to do a simple, crucial part of dev-ops with puma.

I need puma to boot whenever I start (or restart) my Ubuntu server.

So far if the server is up, I simply run a mina deployment task a-la:
```
cd #{current}
bundle exec pumactl start
```

Is this possible within the boot environment without going into the 'jungle'?

Thanks!

**Comment by david-harkness** [comment]
Perhaps something like this?
sh -c "cd $dir && /home/[myapp]/.rvm/bin/rvm default do bundle exec pumactl -F $config_file start"

**Comment by Epigene** [comment]
Found a solution following [this blog entry](http://dev.mensfeld.pl/2014/02/puma-jungle-script-fully-working-with-rvm-and-pumactl/)
