### ISSUE TITLE
Puma slow/failing on initial requests

### ISSUE THREAD

**Issue by dt1973** [puma/puma#678]
Experiencing something similar to https://github.com/puma/puma/issues/274 -- first requests after prolonged periods of inactivity often time out. Subsequent requests are fine.

I'm using Puma 2.11.0 on MRI 2.2.0p0, PostgreSQL 9.4.0, Rails 4.2 and FreeBSD 10.1-RELEASE. I'm on DigitalOcean with 2GB memory and a 2 core processor.

**config/puma.rb**
```
#!/usr/bin/env puma

dir = "/home/myapp"

environment "production"
daemonize

# threads 0, 16
workers 4

pidfile "#{dir}/tmp/puma.pid"
state_path "#{dir}/tmp/puma.state"
bind "unix://#{dir}/tmp/puma.sock"

stdout_redirect "#{dir}/log/puma/access.log", "#{dir}/log/puma/errors.log"
```

**config/database.yml**
```
production:
  pool: 16
```

Not sure what other info I should provide considering it's not actually erroring out. I see nothing worth mentioning in the Puma log files.

**Comment by evanphx** [comment]
That sounds more like something within your app, perhaps database connections are slow to connect because of some kind of reverse DNS? Does this happen with other webservers?

**Comment by dt1973** [comment]
Sounds plausible. Please give me some time to investigate.

Thank you!

**Comment by dt1973** [comment]
You are most right. Seems to be something with the db - getting the same with Unicorn.

Thanks again!

**Comment by dt1973** [comment]
Sorry -- only tested for delays after reboot, which are to be expected:

http://stackoverflow.com/questions/12903575/why-postgresql-queries-are-slower-in-the-first-request-after-server-start-than-d

I've yet to investigate the cause of delay after periods of inactivity.

**Comment by evanphx** [comment]
This doesn't sound like a puma issue still.

**Comment by dt1973** [comment]
You're right. I was querying some external APIs and forgot to send them into the background.

Happy Easter!

**Comment by dt1973** [comment]
Not sure that's it either -- still getting extreme lags after prolonged periods of inactivity.

Came across http://stackoverflow.com/questions/680302/how-can-i-find-out-why-my-app-is-slow -- is Puma doing anything similar?

> If it is just slow on the first time you load it is probably because of passenger killing the process due to inactivity. I don't remember all the details but I do recall reading people who used cron jobs to keep at least one process alive to avoid this lag that can occur with passenger needed to reload the environment.

**Comment by evanphx** [comment]
Puma will wind down the number of threads on inactivity, but not processes. Starting up new threads is fast and would not be the source of a delay.

There is nothing within the puma codebase that would explain what you are seeing. I suggest you try to minimize the reproduction to give yourself more data.

**Comment by dt1973** [comment]
Maybe I need something like PgBouncer (https://wiki.postgresql.org/wiki/PgBouncer)?

Came across http://hans.io/blog/2014/02/19/postgresql_connection/index.html -- shouldn't this be a must for everyone who uses Rails with PostgreSQL?

**Comment by evanphx** [comment]
@dt1973 perhaps, but this issue is now outside the scope of puma.
