### ISSUE TITLE
Crash: double free or corruption

### ISSUE THREAD

**Issue by FlySnake** [puma/puma#679]
CentOS release 6.6 (Final)
nginx version: nginx/1.6.2 -- from nginx repo http://wiki.nginx.org/Install
puma version 2.11.1
ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux]  -- built from sources, installed globally into /usr/local
Rails 4.2.0
PostgreSQL 9.4.1 -- from postgre repo https://wiki.postgresql.org/wiki/YUM_Installation

Puma start cli: `bundle exec puma --bind unix://tmp/sockets/puma.sock --pidfile tmp/pids/puma.pid -e production -t 8:1024`
Once in a few days puma crashes with backtrace in stderr http://pastebin.com/1510DwvU
Same problem with daemonized process.
I'm not sure if it's actually problem with puma or postgre, but after the crash I need only restart puma, without touching postgre or nginx.
My application uses Live Streaming feature and delayed_job_active_record. Here is it's source https://bitbucket.org/antlabs_dev/fbbs2/ (subfolder 'control').

**Comment by evanphx** [comment]
This is a crash inside libpq and thusly there isn't anything Puma can do about it.

**Comment by Leooo** [comment]
Hi @FlySnake, did you manage to isolate your bug? Have the same behavior with puma / postgres / streaming.

**Comment by FlySnake** [comment]
@Leooo nope. I use god http://godrb.com/ as a dirty workaround which restarts puma when it crashes and for this project it's kind of OK.
It feels to me that the problem is somewhere with thread-safety, like using same db connection in different threads, but I couldn't find it. One suggestion is to avoid using database queries inside threads, but rather pass them data through queues. But I haven't tried this.
Hopefully, with upcoming ActionCable there will be no such problems.

**Comment by Leooo** [comment]
ok same here, using ActionController:Live extensively, haven't tried to use it without DB access but this would seem laborious in our case, waiting for ActionCable too. Thanks.
