### ISSUE TITLE
2.11.1 HTTP 'STATUS' header is missing

### ISSUE THREAD

**Issue by L-Oto** [puma/puma#680]
I'm running a PUMA server on Heroku Cedar-14 stack with Ruby 2.2.1p85 and it seems that the "Status" HTTP header is missing from the request response.

Do you have any idea of what's going on? Because Passenger returns it and correct me if I'm wrong by Unicorns does too.

**Comment by bjubinville** [comment]
@L-Oto Unicorns do return this header as well.  I'm experiencing the same thing.

**Comment by evanphx** [comment]
I actually don't see where Unicorn sets a STATUS header. What are you using the STATUS header for? Why not just use the HTTP status code?
