### ISSUE TITLE
Request timeouts (H12's) when switching from Unicorn to Puma on Heroku

### ISSUE THREAD

**Issue by plindelauf** [puma/puma#681]
On Heroku I switched one of our Rails 3.2 (/Ruby 2.0.0) apps from Unicorn to Puma, because we're experiencing problems with slow clients using Unicorn. Almost immediately we started seeing many 30 second timeouts (H12 errors) on at least 5% of our requests. Something we never had when running on Unicorn. 

Here's our setup:

    workers Integer(ENV['WEB_CONCURRENCY'] || 2)
    threads_count = Integer(ENV['MAX_THREADS'] || 5)
    threads threads_count, threads_count

    preload_app!

    rackup      DefaultRackup
    port        ENV['PORT']	|| 3443
    environment ENV['RACK_ENV']		|| 'development'

    on_worker_boot do
      # Valid on Rails up to 4.1 the initializer method of setting `pool` size
      ActiveSupport.on_load(:active_record) do
        config = ActiveRecord::Base.configurations[Rails.env] || Rails.application.config.database_configuration[Rails.env]
        config['pool'] = ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5
        ActiveRecord::Base.establish_connection(config)
      end
    end

Since our app is likely not thread safe, we've set `WEB_CONCURRENCY` to `1` and scaled the processes by setting `WEB_CONCURRENCY` to values ranging from `4` to `8`. We generally run a number of 2x dynos, but we also tried 1x dynos. No matter how we up- or downscale these, the H12's keep coming. Memory usage stays within the normal bounds. Additionally, since we're running just 1 thread per processes, we have set the `DB_POOL` to `1`. We have also configured Rack::Timeout to timeout at 28 seconds.

I contacted Heroku support and they don't know where this is coming from either. They mentioned that they had at least one other similar issue report from someone using 1 thread and multiple processes.

Any ideas what could be causing this?

**Comment by chanks** [comment]
I just diagnosed a problem with an app wherein Rack::Timeout's errors (which descend from the Exception class instead of StandardError) weren't being caught by anything and were killing Puma's workers. Then new requests that came in wouldn't be serviced and would timeout themselves.

I'm going to open an issue with rack-timeout, but in the meantime I wrote a quick middleware to catch those errors and reraise them in a way that Puma can recover from. Haven't deployed to production yet, but it seems to work alright in testing.

```
class TimeoutRecovery
  def initialize(app, options = {})
    @app, @options = app, options
  end

  # Rack::Timeout, as of 0.2.4, raises errors that descend from the Exception
  # class when a request takes too long - however, this is a very strong
  # exception level and will kill Puma's worker if we let it continue down the
  # stack. So instead, catch it and wrap it in a recoverable StandardError.

  class Error < StandardError; end

  def call(env)
    @app.call(env)
  rescue Rack::Timeout::Error => e
    raise Error, "Original Error: #{e.class.inspect}, #{e.message.inspect}, #{e.backtrace.inspect}"
  end
end
```

**Comment by schneems** [comment]
Can you give me a simple app that I can reproduce the problem with?

**Comment by syednasir** [comment]
We are having the same issue with Puma on Heroku.

**Comment by ostinelli** [comment]
> Since our app is likely not thread safe, we've set WEB_CONCURRENCY to 1 and scaled the processes by setting WEB_CONCURRENCY to values ranging from 4 to 8. 

@plindelauf If your actually meant `MAX_THREADS` as your second entry here, I think you're seeing this upside down. "Worker processes are isolated from one another at the OS level, therefore not needing to be thread safe", while on the contrary "Puma can serve each request in a thread from an internal thread pool", and these needs to be thread safe.

Anyhow, I'm experiencing the same one on Heroku. H12 when dynos are restarted. I'd be willing to offer details.

**Comment by rhymes** [comment]
@ostinelli don't know if you use rack-timeout too but in the meantime I solved using this gem https://github.com/keyme/rack-timeout-puma/

**Comment by ostinelli** [comment]
Thank you @rhymes, I'm already doing a custom implementation as described in [this github issue](https://github.com/heroku/rack-timeout/issues/76).

**Comment by evanphx** [comment]
This is most likely #691 as well, which is now fixed.
