### ISSUE TITLE
unable to load rails app with ssl on puma

### ISSUE THREAD

**Issue by fatroller** [puma/puma#688]
I'm trying to run my rails app on puma in development environment on windows box. Without ssl the application works fine..

However when I try to configure ssl for puma, nothing happens. No error is generated in the log and the web page (https://localhost:3000/) says Secure Connection Failed. Below is the output from command line that shows the server started but nothing happened after that..

    E:\ap01\dev\rmmi>foreman start -p 3000
    17:19:31 web.1  | started with pid 3016
    17:19:34 web.1  | *** SIGUSR2 not implemented, signal based restart unavailable!
    17:19:34 web.1  | *** SIGUSR1 not implemented, signal based restart  unavailable!
    17:19:34 web.1  | *** SIGHUP not implemented, signal based logs reopening unavailable!
    17:19:34 web.1  | Puma starting in single mode...
    17:19:34 web.1  | * Version 2.11.2 (ruby 2.0.0-p353), codename: Intrepid Squirrel
    17:19:34 web.1  | * Min threads: 5, max threads: 5
    17:19:34 web.1  | * Environment: development
    17:19:36 web.1  | * Listening on tcp://0.0.0.0:3000
    17:19:36 web.1  | * Listening on ssl://127.0.0.1:3000?cert=E:/ap01/OpenSSL-Win32/bin/server.crt&key=E:/ap01/OpenSSL-Win32/bin/server.key
    17:19:36 web.1  | Use Ctrl-C to stop

My config/puma.rb file is given below -

    path_to_key="E:/ap01/OpenSSL-Win32/bin/server.key"
    path_to_cert="E:/ap01/OpenSSL-Win32/bin/server.crt"
    threads_count = Integer(ENV['MAX_THREADS'] || 5)
    threads threads_count, threads_count

    preload_app!

    rackup      DefaultRackup
    port        ENV['PORT'] || 3000
    environment ENV['RACK_ENV'] || 'development'
    ssl_bind '127.0.0.1', '3000', { key: path_to_key, cert: path_to_cert }
      
     on_worker_boot do

    ActiveSupport.on_load(:active_record) do
      config = ActiveRecord::Base.configurations[Rails.env] ||
                 Rails.application.config.database_configuration[Rails.env]
       config['pool'] = ENV['MAX_THREADS'] || 5
        ActiveRecord::Base.establish_connection(config)
      end
    end

The procfile for foreman is given below -

     web: bundle exec puma -p $PORT -C config/puma.rb

I've also set *config.force_ssl = true* in my apps config/application.rb file.
My ruby version is - *ruby 2.0.0p353 (2013-11-22) [i386-mingw32]*

Has anyone come across similar issue ?

**Comment by evanphx** [comment]
Hm, strange. I can't say I've gotten any reports of users using SSL on
windows, so it's possible there are some bugs there. Any chance you could
try this exact setup but under linux and see if it works? I'm interested to
know if it's mostly just SSL windows support.

**Comment by fatroller** [comment]
Hi evan,

I planning on deploying my app on Heroku - so will let you know how I go. But at the moment my dev environment is Windows... Without SSL, Puma works fine on windows...

Is there a way to debug what really is happening? At the moment there are no errors in the logs and it seems that the browser is unable to connect to the application when SSL is configured...

**Comment by evanphx** [comment]
Is there a reason you need SSL on Windows then? We can figure out what's wrong but I'm wondering why you need it.

**Comment by krzcho** [comment]
I need SSL on Windows and pulling my hair to make it work
I would first need some guidelines how to compile puma with openssl
I was trying with instructions from here https://github.com/hicknhack-software/rails-disco/wiki/Installing-puma-on-windows but I can't make compiler to see openssl libs :(

**Comment by krzcho** [comment]
ok some hair left untouched after moving from ruby193 to 21 with fresh devkit
puma with openssl is compiled and installed but i do have the same result:
puma launches, starts to listen on specified port but fails to serve any request
additionally exactly after 2 mins of time after first request it stops listening on the port

**Comment by evanphx** [comment]
This issue is pretty old and I'm sorry I didn't get back to you. Are you still having this issue?

**Comment by evanphx** [comment]
Given the age, I'm going to close this issue. Please reopen if it's still a problem.
