### ISSUE TITLE
Possible regression with Rackup file using first line magic comment

### ISSUE THREAD

**Issue by nonnenmacher** [puma/puma#689]
I have a service using puma, that was running fine for months, but on the last upgrade (2.11.2), it fails to start, with a error message 
     ```
     ! Unable to load application: NoMethodError: undefined method `start_with?' for :server:Symbol
     undefined method `start_with?' for :server:Symbol
    ```
I start my server using the following command 

     bundle exec pumactl -S tmp/puma/puma.state start

That read a puma config file from the `config/puma.rb` file 
 that contains a `rackup  config-puma.ru` line.

This backup file contains the magic comment line 
       #\ -s puma     (or alternate    #\ --server puma)

This allow to start either the service using command line, or using my favorite IDE, using a rack launcher.

Tracing the problem down, seems to deal with a change in puma/configuration.rb
along the lines 

      rack_app, rack_options = Rack::Builder.parse_file(rackup)
      @options.merge!(rack_options)

      config_ru_binds = rack_options.each_with_object([]) do |(k, v), b|
        b << v if k.start_with?('bind')
      end

When returning from Rack builder, the rack_options is a hash
with two **Symbol** keys   :server and :config

      { :server => "puma", :config => nil}

however the loop that try to figure out, if there is a rack options that could overrides network binding, assume the options are keyed by String and not using Symbols.

I guess a simple  caution like :

         b << v if k.start_with?('bind') if k.respond_to?(:start_with?)

will solve the issue, without too much changes.

**Comment by evanphx** [comment]
This is fixed on master. I'll release it tomorrow. Sorry about that!
