### ISSUE TITLE
Dead threads

### ISSUE THREAD

**Issue by bpaquet** [puma/puma#691]
We have got a big outage on our production platform.

After lot of investigation, we found in some edge cases, puma app threads can die and are not relaunched.

I have add the following loop at https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb#L42
```rb
Thread.new do
  while true
    puts "Threads #{@workers.size} #{@workers.select{|x| x.alive?}.size}"
    sleep 5
  end
end
````

During our tests,  the second number decreases.

I do not have a precise method to reproduce the problem. What I do is
- use our rails / postgresql application
- lock a postgres table (``begin; alter table xxxx add column toto integer;``)
- launch lot of curl command to the rails app, which try to update the table (and are blocked against the lock)
- wait

We are using [rack-timeout](https://github.com/heroku/rack-timeout) and [airbrake](https://github.com/airbrake/airbrake).

We think the thread death is related to edge cases in rack-timeout, but we got no evidence. All standard uses cases are ok (eg : rack-timeout can kill a thread blocked in a postgresql transaction, and the thread is reused).

So, I have some questions
- why there is no rescue around https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb#L104 ?
- what about detecting dead threads and decreasing ``@spawned``, to allow relaunch ?
- why there is no params request_timeout in puma, like in unicorn ? multi threading issue ?
- any idea about how to kill active record connections of dead threads ?

**Comment by bpaquet** [comment]
Probably related to https://github.com/heroku/rack-timeout/issues/76

**Comment by evanphx** [comment]
There is no rescue around the block because that has typically been handled by puma's lowlevel handler. This should probably also do it's own management though too.

**Comment by evanphx** [comment]
@bpaquet Which version of puma are you using?

**Comment by bpaquet** [comment]
2.11.1
