### ISSUE TITLE
Server event logging cannot be configured

### ISSUE THREAD

**Issue by jamiehodge** [puma/puma#696]
I am forwarding logs to log stash in JSON format and would like to either silence or format puma's output.

The puma CLI uses a custom logging interface (events.rb) and does not allow the full silencing of server event logging. Would you consider either a) making the logger a config option and adopting the stdlib interface and/or b) allowing the full silencing of process logging? 

Best,

Jamie

**Comment by evanphx** [comment]
I'd definitely be fine turning the logs off entirely (though, if you just want them off, you can always just redirect the output to dev/null, yes?)

As for the standard logging interface, that would probably be fine. Or at least the ability to, in the configuration, specify a logging object that is used.

**Comment by hkroger** [comment]
AFAIK there is still no way to suppress start up messages at all, right?
