### ISSUE TITLE
start and stop puma like daemon

### ISSUE THREAD

**Issue by svetogor** [puma/puma#70]
how can I start and stop puma in background mode, like daemon?

**Comment by explainer** [comment]
I have been working on a rails app with puma, and found some documentation which defined this command to start puma:
bundle exec puma -e production -p 9292 --pidfile tmp/pids/puma.pid -d

Is this correct? If not, can you point me to a shell script which can start puma as a daemon (in production)?

**Comment by eflukx** [comment]
Anyone still looking for the `-d` daemonize option, you may stop looking for it; it has been removed from newer versions. See #1983
