### ISSUE TITLE
Puma hangs on jRuby responses with no body

### ISSUE THREAD

**Issue by SebastianEdwards** [puma/puma#707]
Puma appears to be setting a header for chunked encoding on responses with no bodies. This occurs on jRuby only as far as I can tell. These requests hang indefinitely and eventually starve Puma of threads.

Here is a comparison of responses to the same application between MRI and jRuby.

First MRI:

```
< HTTP/1.1 404 Not Found
< Strict-Transport-Security: max-age=31536000
< Content-Type: text/html; charset=utf-8
< X-Request-Id: 3625cca8-09d9-4660-b179-34fc2c9994ab
< X-Runtime: 0.055454
< Content-Length: 0

DISCONNECTS HERE
```

And jRuby:

```
< HTTP/1.1 404 Not Found
< Strict-Transport-Security: max-age=31536000
< Content-Type: text/plain; charset=utf-8
< X-Request-Id: 4ca9b819-4070-45f0-a383-f297d83bfa8b
< X-Runtime: 0.076803
< Transfer-Encoding: chunked

HANGS HERE
```

Tested on jRuby 9.0.0.0-pre2, Puma 2.11.3 and Rails 4.2.1.

**Comment by deepj** [comment]
Hi,
this is already fixed in JRuby 9k head -> https://github.com/jruby/jruby/issues/2957
