### ISSUE TITLE
Running multiple instances of puma server on a linux box

### ISSUE THREAD

**Issue by trekr5** [puma/puma#708]
Hi,

I have a scenario where I run two web apps powered by puma server running on a linux box. However when one server starts, the other shuts down.

Can someone please tell me how to enable puma to run multiple instances. I also tried running the puma servers on different ports but have been unsuccessful.

Many thanks

**Comment by nathansamson** [comment]
Hi,

Except for different ports you probably also need different PID & state
files (if you are using pumactl).

Can you post the logs of both apps at the time of boot/shutdown. Also the
config for both would be helpful, startup commands .

I've been running multiple pumas on the same VM without problems, and
technically there is no reason why one instance would affect the other one,
unless they share state / config.

Nathan

**Comment by trekr5** [comment]
Hi Nathan,

I've created two dashbaords both powered by puma servers on the same linux box.

These dashboards are stored in different locations on the same box and the start puma command for each dashboard run from these directories.

This is my config.ru file for both:-

#config.ru

require 'dashing'

configure do

  set :auth_token, 'YOUR_AUTH_TOKEN'
  set :bind, '0.0.0.0'
    helpers do
    def protected!
     # Put any authentication code you want in here.
     # This method is run before accessing any resource.
    end
  end
end

map Sinatra::Application.assets_prefix do
  run Sinatra::Application.sprockets
end

and my command to start puma server 1 is:-

"bundle exec puma -d config.ru tcp://0.0.0.0:9292 --pidfile /var/run/puma.pid" 

with pid stored as /var/run/puma.id

My command to start puma server 2 is:

bundle exec puma -d config.ru tcp://0.0.0.0:3030 --pidfile /var/run/puma-3030.pid

with the pid stored as /var/run/puma-3030.pid

**Comment by nathansamson** [comment]
looks good, any logs we can have a look at?

Nathan

**Comment by trekr5** [comment]
The two dashboards are Sinatra framework running with a Puma server. Don't have any puma logs though..

**Comment by evanphx** [comment]
Remove that `bind` line from your config, that is causing them to bind to the default port. Since you specify a port on the CLI, you don't want to set one like this in the config.
