### ISSUE TITLE
puma start causes "There is already a server bound to: <socket>" error

### ISSUE THREAD

**Issue by nwshane** [puma/puma#713]
EDIT: Since I'm not sure if this is a puma problem (it's likely just a configuration problem on my end), I transferred this question to stackoverflow: http://stackoverflow.com/questions/31018456/puma-start-causes-there-is-already-a-server-bound-to-socket-error

I haven't been able to reliably reproduce this issue, so I'll describe what's happening and hope one of you wise puma kids out there can help me out. 

When I start puma with the command `puma -q -d -e staging -C <config_path>`, it sometimes (not always) causes the following error:

```
[12802] Puma starting in cluster mode... 
[12802] * Version 2.11.3 (ruby 2.1.2-p95), codename: Intrepid Squirrel
[12802] * Min threads: 2, max threads: 4
[12802] * Environment: staging
[12802] * Process workers: 2
[12802] * Phased restart available 
[12802] * Listening on unix:///<app_dir>/tmp/puma/sockets/puma.sock 
<ruby_path>/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:284:in `add_unix_listener': There is already a server bound to: <app_dir>/tmp/puma/sockets/puma.sock (RuntimeError)
<ruby_path>/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:124:in `block in parse'
<ruby_path>/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `each'
<ruby_path>/2.1.0/gems/puma-2.11.3/lib/puma/binder.rb:82:in `parse'
<ruby_path>/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:325:in `run'
<ruby_path>/2.1.0/gems/puma-2.11.3/lib/puma/cli.rb:216:in `run'
<ruby_path>/2.1.0/gems/puma-2.11.3/bin/puma:10:in `<top (required)>'
<ruby_path>/2.1.0/bin/puma:23:in `load'
<ruby_path>/2.1.0/bin/puma:23:in `<main>'
```

If I try to run the command again afterwards, it works.

Here's my puma config:
```
#!/usr/bin/env puma
    
directory "<app_dir>/current"
rackup "<app_dir>/current/config.ru"
environment "staging"
    
pidfile "<app_dir>/tmp/puma/pid"
state_path "<app_dir>/tmp/puma/state"
activate_control_app "<app_dir>/tmp/puma/sockets/pumactl.sock"
    
stdout_redirect "<app_dir>/shared/log/puma.error.log", "<app_dir>/shared/log/puma.access.log", true
    
threads 2,4
    
bind "unix:///<app_dir>/tmp/puma/sockets/puma.sock"
workers 2
```

Any thoughts on 1) how I might reproduce this error and/or 2) how to fix it? Is this a problem with puma itself or with my configuration?

**Comment by evanphx** [comment]
Well, that means that something is already using that socket. That process needs to exit before you can start a new one.

**Comment by nwshane** [comment]
This error occurs when I first stop and then start puma (as part of my deploy task). Does that imply to you that the puma stop command isn't ending the process in time for puma start to work? 

If the command `pumactl -F <config_path> stop` is immediately followed by `puma -q -d -e staging -C <config_path>`, do they run asynchronously? Or will the `stop` command complete before `puma` begins?

**Comment by Rttearth** [comment]
I also have the same problem with @nwshane. It seems like puma.sock & puma.state is not cleaned when invoke "restart". Previously it was a bug, but @evanphx said it has been fixed after version 2.3.0. The condition is that I still have the problem when deploying. I doubt whether this cause from deploy.rb file. Still waiting for solutions.

**Comment by kannancet** [comment]
This issue occurs while deploying with capistrano. What could be the reason ? Any idea

**Comment by alfie-max** [comment]
no fixes?? Still facing same issue in 2018

**Comment by nwshane** [comment]
@alfie-max As far as I remember, I think the issue might have been that instead of calling stop and then start separately, you need to run a restart command: https://github.com/puma/puma/blob/master/docs/restart.md

**Comment by andy-harper** [comment]
i tried that, but then the server didn't even start. got a 502 at ngnix

**Comment by light-flight** [comment]
I'm using config from the [DigitalOcean's tutorial](https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma#step-6-—-adding-deployment-configurations-in-the-rails-app). Faced this issue with puma restart when **`set :pty, false`** in my `deploy.rb`

**Comment by alfie-max** [comment]
@nwshane  i tried that, but then the server didn't even start. got a 502 at ngnix

Seems like puma stop doesn't stop it in time. 
i'm using mina for deployment and calling puma:stop and puma:start

this is the log : 

```
-----> Using RVM environment "ruby-2.4.1"
       Using /home/ubuntu/.rvm/gems/ruby-2.4.1
-----> Stopping Puma...
       Command stop sent success
-----> Starting Puma...
       [30986] Puma starting in cluster mode...
       [30986] * Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
       [30986] * Min threads: 2, max threads: 2
       [30986] * Environment: production
       [30986] * Process workers: 1
       [30986] * Phased restart available
       [30986] * Listening on unix:///home/ubuntu/site_home/shared/tmp/sockets/puma.sock
       bundler: failed to load command: puma (/home/ubuntu/site_home/releases/4/vendor/bundle/ruby/2.4.0/bin/puma)
       RuntimeError: There is already a server bound to: /home/ubuntu/site_home/shared/tmp/sockets/puma.sock
```

So the stop command is sent successfully.. but it doesn't stop immediately.
Right now i've to run the deploy script twice. or stop the puma manually and run deploy.

**Comment by vikk2411** [comment]
Hi 
This error is coming on my production server every 5-6 minutes.
Any solution to problem? We have a couple of servers on production.. Puma server seems to be running fine but dont know why it is trying to reconnect again and again
