### ISSUE TITLE
Trouble Debugging Random Puma Failures

### ISSUE THREAD

**Issue by milesmatthias** [puma/puma#714]
I'm seeing some inconsistent errors and I'm having trouble figuring out how to go about debugging it. I'm using Rails 4.1.8, Puma 2.11.3, Nginx 1.4.6, Ubuntu 14.04, and Capistrano 3.

In `config/deploy.rb`, I have this:

```
after 'deploy:finished', 'puma:smart_restart'
```

and when I deploy, I usually see this:

```
DEBUG [9fc09c1c]        Command restart sent success
INFO [9fc09c1c] Finished in 0.797 seconds with exit status 0 (successful).
CF origin DID NOT return 200 so NOT invalidating CloudFront.
```

however, curling the server returns a `502 bad gateway`. It's unfortunate because `puma:restart` doesn't return any errors.

When I deploy again after seeing an error like the above, capistrano outputs the following:

```
DEBUG [2b7e95f9]        Puma starting in single mode...
DEBUG [2b7e95f9] 
DEBUG [2b7e95f9]        * Version 2.11.3 (ruby 2.1.4-p265), codename: Intrepid Squirrel
DEBUG [2b7e95f9] 
DEBUG [2b7e95f9]        * Min threads: 4, max threads: 16
DEBUG [2b7e95f9] 
DEBUG [2b7e95f9]        * Environment: staging
DEBUG [2b7e95f9] 
DEBUG [2b7e95f9]        * Daemonizing...
DEBUG [2b7e95f9] 
INFO [2b7e95f9] Finished in 0.631 seconds with exit status 0 (successful).
CF origin returns 200 so invalidating CloudFront now.
```

So I'm not sure where to start debugging / what to look at, but any advice would be appreciated.

**Comment by evanphx** [comment]
Try to hit puma directly and see if it is returning a 500. It's possible that CF or nginx are getting confused about the app as it restarts?

**Comment by milesmatthias** [comment]
Going to close this issue since I've since migrated from Nginx + Puma to Apache + Passenger and can't debug this situation. If someone else comes along with similar issues, feel free to re-open.
