### ISSUE TITLE
Need to specify `--with-opt-dir` on OSX 10.11 El Capitan.

### ISSUE THREAD

**Issue by idyll** [puma/puma#718]
Haven't had a change to dig into exactly what's going on but gem install fails on OSX 10.11 because it can't find some openssl headers.

When compiling `mini_ssl.c` I get a `fatal error: 'openssl/bio.h' file not found`.

> As an aside the openssl situation is getting pretty crazy. Brew installs 1.0.2. Apple still installs 0.9.8. Of course Ruby is using 1.0.1.

If this is still an issue when 10.11 gets to beta 3 I will see if I can suggest a fix.

**Comment by jeremy** [comment]
10.11 removes `/usr/include/openssl` for good.

**Comment by ryanbrink** [comment]
Is there a simple workaround I can use for now?

**Comment by evanphx** [comment]
Hrm, fun. I can make SSL support optional though I wonder if that will confuse folks.

**Comment by robertjpayne** [comment]
If you are installing home-brew openssl it's a lot easier:

`gem install puma -- --with-opt-include=/usr/local/opt/openssl/include``

**Comment by ginolon** [comment]
On El Capitan, @robertjpayne's answer works.

**Comment by MxBird** [comment]
On El Capitan, @robertjpayne's answer works.  many gem could install success in this way

**Comment by betoharres** [comment]
@robertjpayne worked to me as well ^^ thanks!

**Comment by jeremy** [comment]
To make this sticky for all your Gemfiles:
```sh
bundle config build.puma --with-opt-dir=/usr/local/opt/openssl
```

Confirm:
```sh
$ grep PUMA ~/.bundle/config 
BUNDLE_BUILD__PUMA: "--with-opt-dir=/usr/local/opt/openssl"
```

**Comment by jonnyarnold** [comment]
:+1: for @jeremy's comment

**Comment by jeroenvisser101** [comment]
@jeremy, that's great!

**Comment by jomarquez** [comment]
:+1: thank you @jeremy and @robertjpayne

**Comment by vkhang55** [comment]
:+1: Jeremy

**Comment by kocodude** [comment]
awesome, thanks @jeremy and @robertjpayne

**Comment by chischaschos** [comment]
thank you @jeremy and @robertjpayne

**Comment by enderahmetyurt** [comment]
cheers @jeremy

**Comment by whitehorse0324** [comment]
I tried this on my mac - 10.15.5 catalina. But, it still shows same error.
Can anyone help me?

**Comment by dentarg** [comment]
@whitehorse0324 it looks like you are running into issue #2304 (it is not solved)
