### ISSUE TITLE
Puma threads not working, all requests still blocked by the first query

### ISSUE THREAD

**Issue by poc7667** [puma/puma#719]
I have a DB query which will take more than 100seconds.

Therefore I adopt PUMA to make my server won't be blocked by some requests,

However it doesn't work.

My server is still blocked by the first query and the follwoing requests are blocked.

I run the PUMA with `puma -C config/puma.rb`

Whats wrong with my config file ?

# Config

    workers Integer(ENV['WEB_CONCURRENCY'] || 6)
    threads_count = Integer(6)
    threads threads_count, threads_count
    preload_app!
    rackup      DefaultRackup
    port        ENV['PORT']     ||  8591
    environment ENV['RACK_ENV'] || 'development'

**Comment by nathansamson** [comment]
Are you testing this in development?

In development rails will refuse (at least in default config) to allow multiple requests at the same time.

**Comment by poc7667** [comment]
Yes I test it in development mode, I got it. thanks for your answer
