### ISSUE TITLE
Why I get all zero in Puma::Cluster#stats

### ISSUE THREAD

**Issue by larryzhao** [puma/puma#721]
I am running Puma 2.11.3, I had `workers 8` in my puma config, and after started I could see the following on my server:

```
$ ps -ef | grep puma
deployer  8546  8374  0 18:11 pts/1    00:00:00 grep --color=auto puma
deployer 19470     1  0 12:14 ?        00:00:05 puma 2.11.3 (tcp://0.0.0.0:2801) [myapp]
deployer 29147 19470 13 16:48 ?        00:11:34 puma: cluster worker 0: 19470 [myapp]
deployer 29193 19470 12 16:48 ?        00:10:38 puma: cluster worker 1: 19470 [myapp]
deployer 29238 19470 13 16:48 ?        00:11:16 puma: cluster worker 2: 19470 [myapp]
deployer 29268 19470 17 16:49 ?        00:14:08 puma: cluster worker 3: 19470 [myapp]
deployer 29305 19470 14 16:49 ?        00:12:12 puma: cluster worker 4: 19470 [myapp]
deployer 29372 19470 14 16:49 ?        00:12:04 puma: cluster worker 5: 19470 [myapp]
deployer 29406 19470 12 16:50 ?        00:10:27 puma: cluster worker 6: 19470 [myapp]
deployer 29456 19470 12 16:50 ?        00:10:23 puma: cluster worker 7: 19470 [myapp]
```

But why I got `Stats: { "workers": 0, "phase": 0, "booted_workers": 0 }` from Puma::Cluster#stats, where are my workers? Is anywhere I've done wrong?

Best Regards.
Larry

**Comment by evanphx** [comment]
That's odd! Does it ever work?

**Comment by larryzhao** [comment]
@evanphx Yes, I think it works. But I really don't know why it doesn't work with my case. I've tried it with a fresh Rails project, but it runs into the same problem in daemon mode, in non-daemon mode, everything looks fine. 

I am also discussing it with the author of `puma-worker-killer` in another thread: https://github.com/schneems/puma_worker_killer/issues/15

**Comment by evanphx** [comment]
Sorry for leaving this going so long! Are you still having this issue with current puma?

**Comment by evanphx** [comment]
Given the age, I'm going to close this. Please reopen if it's still an issue.

**Comment by larryzhao** [comment]
@evanphx It's OK. Current puma works fine in my production deployment. I haven't had a close look into this with current puma yet. I will reopen if I find it's still there.
