### ISSUE TITLE
Puma configuration takes precedence over explicit CLI arguments

### ISSUE THREAD

**Issue by rwz** [puma/puma#723]
![screen shot 2015-07-01 at 3 40 28 pm](https://cloud.githubusercontent.com/assets/129043/8466467/fda90838-2007-11e5-9199-f27a83631d34.png)

Update: puma configuration takes precedence over explicit CLI arguments

**Comment by evanphx** [comment]
I suspect that's because you have other values configured in a config file?

**Comment by rwz** [comment]
True. Although, I was expecting explicit arguments to take precedence here.

**Comment by evanphx** [comment]
This is fixed in d2d1e5b430f.

**Comment by rwz** [comment]
yay. thanks!
