### ISSUE TITLE
uninitialized constant Puma::DSL::ActiveSupport

### ISSUE THREAD

**Issue by milesmatthias** [puma/puma#728]
Deploying a rails 4.2 app on ubuntu 14.04 with nginx and puma 2.11.3 and have been following tutorials [like this one](https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma).

I'm seeing this in my `log/puma.access.log`:

```
/var/www/foo.com/shared/puma.rb:24:in `block in _load_from': uninitialized constant Puma::DSL::ActiveSupport (NameError)
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `call'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `block in worker'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `each'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `worker'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:109:in `block (2 levels) in spawn_workers'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:109:in `fork'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:109:in `block in spawn_workers'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:105:in `times'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:105:in `spawn_workers'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:157:in `check_workers'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cluster.rb:421:in `run'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/lib/puma/cli.rb:216:in `run'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/gems/puma-2.11.3/bin/puma:10:in `<top (required)>'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/bin/puma:23:in `load'
        from /var/www/foo.com/shared/bundle/ruby/2.1.0/bin/puma:23:in `<main>'
```

Any ideas on what's causing this? I'm not seeing this in my other nginx/puma/rails apps so I'm having a hard time debugging this.

**Comment by hbin** [comment]
Same issue. 
It seems like something wrong with `prune_bundler`. The latest `capistrano-puma` switch `puma_preload_app` from `true` to `flase` https://github.com/seuros/capistrano-puma/commit/013bb17ce0c79bfd3e40bf9648ddb819d9f6e58b 

Try to set `puma_preload_app` to true, and it will works again.

**Comment by evanphx** [comment]
What does your puma config file look like?

**Comment by hbin** [comment]
@evanphx I pasted both configuration files that work and doesn't work below:

### Work
```
#!/usr/bin/env puma

directory '/home/deploy/apps/sample_app_production/current'
rackup "/home/deploy/apps/sample_app_production/current/config.ru"
environment 'production'

pidfile "/home/deploy/apps/sample_app_production/shared/tmp/pids/puma.pid"
state_path "/home/deploy/apps/sample_app_production/shared/tmp/pids/puma.state"
stdout_redirect '/home/deploy/apps/sample_app_production/shared/log/puma_access.log', '/home/deploy/apps/sample_app_production/shared/log/puma_error.log', true

threads 0,16

bind 'unix:///home/deploy/apps/sample_app_production/shared/tmp/sockets/puma.sock'

workers 2

preload_app!

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/home/deploy/apps/sample_app_production/current/Gemfile"
end

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

===============

### Doesn't Work
```
#!/usr/bin/env puma

directory '/home/deploy/apps/sample_app_production/current'
rackup "/home/deploy/apps/sample_app_production/current/config.ru"
environment 'production'

pidfile "/home/deploy/apps/sample_app_production/shared/tmp/pids/puma.pid"
state_path "/home/deploy/apps/sample_app_production/shared/tmp/pids/puma.state"
stdout_redirect '/home/deploy/apps/sample_app_production/shared/log/puma_access.log', '/home/deploy/apps/sample_app_production/shared/log/puma_error.log', true

threads 0,16

bind 'unix:///home/deploy/apps/sample_app_production/shared/tmp/sockets/puma.sock'

workers 2

prune_bundler

on_restart do
  puts 'Refreshing Gemfile'
  ENV["BUNDLE_GEMFILE"] = "/home/deploy/apps/sample_app_production/current/Gemfile"
end

on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    ActiveRecord::Base.establish_connection
  end
end
```

### The error message from `puma_error.log` file
```
==> log/puma_error.log <==
/home/deploy/apps/sample_app_production/shared/puma.rb:30:in `block in _load_from': uninitialized constant Puma::DSL::ActiveSupport (NameError)
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `call'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `block in worker'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `each'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:211:in `worker'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:109:in `block (2 levels) in spawn_workers'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:109:in `fork'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:109:in `block in spawn_workers'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:105:in `times'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:105:in `spawn_workers'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:157:in `check_workers'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cluster.rb:421:in `run'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/cli.rb:216:in `run'
	from /home/deploy/apps/sample_app_production/shared/bundle/ruby/2.2.0/gems/puma-2.11.3/bin/puma-wild:31:in `<main>'
```

I deploy this app on Ubuntu 14.04 LTS running in the VirtualBox 4.3.28 supervised by Vagrant.

Hope these message could help you.

**Comment by evanphx** [comment]
Oh right right. Of course! That doesn't when you don't preload, as you're doing in the second one, the app isn't loaded into the process yet! So you can just delete the `on_worker_boot` block entirely, you don't even need it when using `prune_bundler`.

**Comment by kamok** [comment]
I got this issue after deploying my app using Puma for the very first time.

Here's my config file: 
```

if Rails.env.production?
  #Can't use this on Windows...
  workers Integer(ENV['WEB_CONCURRENCY'] || 2)
end

threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end
```

Here are the logs:

> 2016-09-05T04:14:17.575779+00:00 heroku[web.1]: State changed from crashed to starting
> 2016-09-05T04:14:20.107795+00:00 heroku[web.1]: Starting process with command `bundle exec puma -C config/puma.rb`
> 2016-09-05T04:14:22.691015+00:00 heroku[web.1]: Process exited with status 1
> 2016-09-05T04:14:22.702562+00:00 heroku[web.1]: State changed from starting to crashed
> 2016-09-05T04:14:22.621186+00:00 app[web.1]: config/puma.rb:1:in `_load_from': uninitialized constant Puma::DSL::Rails (NameError)
> 2016-09-05T04:14:22.621201+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/dsl.rb:26:in `instance_eval'
> 2016-09-05T04:14:22.621202+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/dsl.rb:26:in `_load_from'
> 2016-09-05T04:14:22.621203+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/dsl.rb:9:in `load'
> 2016-09-05T04:14:22.621204+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/configuration.rb:205:in `block in load'
> 2016-09-05T04:14:22.621204+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/configuration.rb:202:in `each'
> 2016-09-05T04:14:22.621205+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/configuration.rb:202:in `load'
> 2016-09-05T04:14:22.621208+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/launcher.rb:62:in `initialize'
> 2016-09-05T04:14:22.621209+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/cli.rb:65:in `initialize'
> 2016-09-05T04:14:22.621209+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/lib/puma/cli.rb:65:in `new'
> 2016-09-05T04:14:22.621210+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/bin/puma:8:in `new'
> 2016-09-05T04:14:22.621211+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/puma-3.6.0/bin/puma:8:in `<top (required)>'
> 2016-09-05T04:14:22.621211+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/bin/puma:23:in `load'
> 2016-09-05T04:14:22.621212+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/bin/puma:23:in `<main>'
>

**Comment by evanphx** [comment]
Rails isn't loaded yet when parsing the config file, so you can't do that first line. You'll need to remove it.
