### ISSUE TITLE
stdout_redirect function in puma config file not working in production

### ISSUE THREAD

**Issue by kylebebak** [puma/puma#731]
Actually, it's not working in any environment except for development. In development, stdout is written to **access.log**, and stderr is written to **error.log**. However, if any other environment is specified when puma is started, stdout is being redirected to stderr, and winds up in **error.log**. Here's my `config/puma/production.rb`:

```
#!/usr/bin/env puma

stdout_redirect(stdout = 'log/access/access.log', stderr = 'log/error/error.log', append = false)
p @options
```

Launching puma as follows
`puma -p 54321 -e production`
... yields the following options hash:

```
{:min_threads=>0, :max_threads=>16, :quiet=>false, :debug=>false, :binds=>["tcp://0.0.0.0:54321"], :workers=>0, :daemon=>false, :before_worker_boot=>[], :after_worker_boot=>[], :wor
ker_directory=>"/home/kylebebak/repos/opi_api", :environment=>"production", :config_file=>"config/puma/production.rb", :mode=>:http, :on_restart=>[], :worker_timeout=>60, :redirect_
stdout=>"/home/kylebebak/repos/opi_api/log/access/access.log", :redirect_stderr=>"/home/kylebebak/repos/opi_api/log/error/error.log", :redirect_append=>false}
```

The redirect_stdout and redirect_stderr keys seem to point to the correct files, yet all stdout logging is happening in **error.log**. This doesn't happen in development.

I've looked at the contents of **error.log** and they are filled with 

```
127.0.0.1 - - [14/Jul/2015 22:03:18] "GET /lugar/categorias?cvegeo=09 HTTP/1.0" 200 3551 0.0236
127.0.0.1 - - [14/Jul/2015 22:03:18] "GET /lugar/categorias?cvegeo=09 HTTP/1.0" 200 3551 0.0228
```

... successful petitions. I don't think they should wind up in **error.log**, and I'm not sure if this is being caused by puma or by a logging function used by puma. I'm having trouble debugging this, thanks for any help.

**Comment by evanphx** [comment]
Is this in a rails app? One thing is that puma does not use it's own request logging in production mode, leaving it up to the app to provide that via either `Rack::CommonLogger` or as Rails does, it's own internal logging.

What mechanism are you using for logging in production?

**Comment by kylebebak** [comment]
Hey Evan, thanks for the help! I'm using Puma to run a Sinatra app. Sinatra doesn't have its own logging capabilities as far as I know.

I was hoping to use Puma's logging functionality because it covers all our needs, and I was having trouble getting `CommonLogger` to play nice when it was deployed in a docker container.

Is there any way to use Puma's `stdout_redirect` in production mode?

**Comment by evanphx** [comment]
The way `stdout_redirect` works is just changing where STDOUT/$stdout go to. If you use a logger that sends data to stdout, it will be redirected to the requested file.

The logging in Puma is just using a rack middleware called `Puma::CommonLogger`, so you can add that into your config.ru script to use it.

**Comment by kylebebak** [comment]
Hey Evan, thanks for the info I'll try this and see if I can get it working in environments other than development.

**Comment by vadviktor** [comment]
@kylebebak, have you got any luck getting it to work yet? Please share any working solution to this, I'm facing the very same problem :( Thank you very much!

**Comment by kylebebak** [comment]
@vadviktor , I haven't looked at this yet, I've been working on other stuff. As Evan noted above, Puma's logger use its own request logging in production.

I think I'll end up defining an instance of `Rack::CommonLogger` in `config.ru` and use that

**Comment by mwpastore** [comment]
Hi, sorry to butt in on an old issue, but Sinatra [does indeed have its own logging](http://www.sinatrarb.com/intro.html#Logging), and [it writes to stderr by default](http://www.sinatrarb.com/configuration.html): 

> `:logging` - log requests to STDERR
> 
> Writes a single line to STDERR in Apache common log format when enabled. This setting is enabled by default in classic style apps and disabled by default in Sinatra::Base subclasses.
> 
> Internally, the Rack::CommonLogger component is used to generate log messages.

So if you have a classic style app in production (or a modular app with `enable :logging` or `set :logging, true`) this explains the behavior you're seeing.

**Comment by Silex** [comment]
> Is this in a rails app? One thing is that puma does not use it's own request logging in production mode, leaving it up to the app to provide that via either Rack::CommonLogger or as Rails does, it's own internal logging.

Is there a way to tell puma to use its own request logging in production mode? If not, how do we get the same behavior using rails? code example would be great :wink: 

I'm using rails and this is a bit annoying because in production, access.log looks like:

```
172.18.0.1 - - [26/Feb/2016:11:20:41 +0100] "GET /jquery-fbd3c47db8f7f0030f377a105ed8fc51.js?body=1 HTTP/1.0" 200 294162 0.0082
172.18.0.1 - - [26/Feb/2016:11:20:41 +0100] "GET /bootstrap/modal-0f3e39885adbbe856a4c41ebc3ce9402.js?body=1 HTTP/1.0" 200 9939 0.0052
172.18.0.1 - - [26/Feb/2016:11:20:41 +0100] "GET /bootstrap/popover-8c9186ed62118dbc62c6f97afd0ca840.js?body=1 HTTP/1.0" 200 3164 0.0079
```

But in production that log is just empty.

The rails log production.log looks as expected but that log doens't contain the same information.

**Comment by mwpastore** [comment]
@Silex Take a look at [this](http://guides.rubyonrails.org/debugging_rails_applications.html#log-levels). What's your `config.log_level` (or `Rails.logger.level`) set to in production?

**Comment by Silex** [comment]
@mwpastore: it's set to `:info`. I remember testing with `:debug` too but it didn't change anything, tho it was a quick test so maybe I messed up.

**Comment by Silex** [comment]
> puma.stdout.log looks like:
> But in production that log is just empty.

I should be more clear here, to be exact that log looks like this:

```
=== puma startup: 2016-02-25 09:47:08 +0100 ===
* Listening on unix:///var/run/puma/puma.sock
```

**Comment by mwpastore** [comment]
Right, as @evanphx explained above, in production Puma simply captures the stderr and stdout of the app and redirects it to the logs you specify with `stdout_redirect`. I don't know even about Rails—I thought maybe setting the `log_level` to `:info` or `:debug` would do the trick.

**Comment by Silex** [comment]
@mwpastore: can you show me where puma checks for the production environment and decides not to log?

**Comment by mwpastore** [comment]
@Silex I believe it's [this statement](https://github.com/puma/puma/blob/v2.16.0/lib/puma/configuration.rb#L108).

**Comment by Silex** [comment]
@mwpastore: thanks! now I know what to fiddle with :)

**Comment by mwpastore** [comment]
It looks like @evanphx added a `--log-requests` (or `log_requests`) option in Puma 3.0 that can be used to enable request logging in production. If you're planning to upgrade soon, maybe you can give that a try!

**Comment by DzmitryNikitsin** [comment]
is there any reason why you skip logs for jruby & damon mode ? https://github.com/puma/puma/blob/master/lib/puma/jruby_restart.rb#L55

**Comment by evanphx** [comment]
Looks like this has been solved a while back! Sorry about the delay.
