### ISSUE TITLE
Puma 2.1.2 + JRuby 1.7.21 + SSL will cause errors

### ISSUE THREAD

**Issue by hab278** [puma/puma#739]
Just opening an issue for JRuby. Looks like it's [failing on travis](https://travis-ci.org/puma/puma/jobs/71287932#L227) so it's being tested for, but currently when running on SSL, Puma will throw the error 
```
#<NoMethodError: undefined method `peercert' for #<Puma::MiniSSL::Engine:0x7a87818c>>
```

Commit [e8d25b30f3d4a8ae4fca0fd9f2acadaff9e8d41d](https://github.com/puma/puma/commit/e8d25b30f3d4a8ae4fca0fd9f2acadaff9e8d41d) notes that the changes were MRI only, I didn't see that in [History.txt](https://github.com/puma/puma/blob/master/History.txt) when I updated. Using 2.11.3 instead.

**Comment by evanphx** [comment]
Sorry about that! 2.12.2 should at least stub it out enough to still work.

**Comment by hab278** [comment]
:+1: Thanks! Definitely will try it out.
