### ISSUE TITLE
Request for feature to allow an action to be dispatched to all workers in cluster

### ISSUE THREAD

**Issue by rosenfeld** [puma/puma#740]
It would be interesting if we could configure some routes to be dispatched to all workers in a cluster.

For example, there are some simple values that could be stored in memory upon the application boot rather than stored somewhere else, like Redis.

So, I was wondering that maybe it would be great if we could add an option to tell Puma that any requests to "/cache/clear" should be performed in all workers for the cluster. I understand this is not enough if you have a load balancer going through multiple Puma clusters, but for a single cluster this would be very interesting.

We have some kind of configuration stored in the database which are used very often but rarely change. Currently we store them in-memory and when we need to change them we restart the Puma cluster, but it would be even better if I could simply place a request to all workers when logged as an admin to clear those cached configurations.

I'm sorry if this is not the proper place for feature requests but I couldn't find any pointers to where we should ask for feature requests.

**Comment by lfalcao** [comment]
@rosenfeld, 
why not reload puma from the controller? :)

```
system('bundle exec pumactl -P /path/to/pid/file.pid restart')
```

**Comment by rosenfeld** [comment]
Hi @lfalcao, while this is certainly possible, the main reason why I'm requesting this feature is not that I want a better way to restart Puma. I'd really prefer to avoid restarting the application just to clear up some cache if possible. This way I can have better granularity. There are parts of the application that depend on specific tables from the database. When I change one of those tables that rarely change, I'd like to be able to only clear the related cache rather than all of them, for example...

**Comment by evanphx** [comment]
@rosenfeld This would be better implemented as a standalone gem that something internal to puma. For instance, you could have code in the workers monitor a file and clear the cache when the file is touched.

**Comment by rosenfeld** [comment]
That's really a good idea. I haven't thought about it before. Thanks :)
