### ISSUE TITLE
Constants in config.ru not accessible in required files

### ISSUE THREAD

**Issue by tozz** [puma/puma#750]
Using Ruby 2.2.2
Rack 2.12.2 (This was working in 2.11.3)

I've created a simple gist (https://gist.github.com/tozz/bce3768970de30b70d6a)
Just run puma in the folder and you'll see
```! Unable to load application: NameError: uninitialized constant Application::TestPuma::FOO```

**Comment by evanphx** [comment]
Hm. Is this a common thing to do, put constants in the config.ru assuming it's the top-level?

**Comment by evanphx** [comment]
This should be fixed now in 2.12.3.

**Comment by tozz** [comment]
Thanks for the quick fix, as for how common it is I have no idea, I've been doing it like this for many years with thin and puma and didn't stumble upon any issue until 2.12.2.
