### ISSUE TITLE
puma upstart /proc/self/fd/9: 4: /proc/self/fd/9: logger: not found

### ISSUE THREAD

**Issue by slavajacobson** [puma/puma#752]
Ubuntu server 14.04

Running sudo start puma-manager gives me an error "/proc/self/fd/9: 4: /proc/self/fd/9: logger: not found"

Commenting out logger -t "Starting $app" from puma-manager.conf fixes it though, any ideas how to fix the logger?

**Comment by evanphx** [comment]
What is the `puma-manager` you're using? The bug is in that entirely.

**Comment by slavajacobson** [comment]
https://github.com/puma/puma/tree/master/tools/jungle/upstart

**Comment by evanphx** [comment]
Your system is missing the `logger` command. In Ubuntu, it's in the `bsdutils` package it looks like.
