### ISSUE TITLE
Puma cannot compile against openssl 0.9.8

### ISSUE THREAD

**Issue by jamesmeador** [puma/puma#753]
Caveats:
- 0.9.8 is insanely old. 
- We're stuck on CentOS 5.5.
- I don't know C.

Other users have issues with this, but they don't have the openssl-devel packages. We do! Alas, no go, because 0.9.8 doesn't have openssl/ec.h headers. I wrapped the EC_KEY section of mini_ssl.c with #ifdef #endif and it now compiles. We don't need SSL, so I can't exactly confirm that this is a good thing or bad thing.

Puma 2.12 has some bugfixes that we need, so I'm filing this.

Thanks!

**Comment by evanphx** [comment]
This will be fixed in 2.13.
