### ISSUE TITLE
Large params set causing: "HTTP parse error, malformed request"

### ISSUE THREAD

**Issue by JoshMcKin** [puma/puma#757]
I was searching thru the code but cannot find where we can increase the maximum query string. Is it possible to increase the maximum query size?

```2015-08-11 20:47:48 -0500: HTTP parse error, malformed request (): #<Puma::HttpParserError: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length (was 14530)>
2015-08-11 20:47:48 -0500: ENV: {"rack.version"=>[1, 3], "rack.errors"=>#<IO:<STDERR>>, "rack.multithread"=>true, "rack.multiprocess"=>false, "rack.run_once"=>false, "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "SERVER_PROTOCOL"=>"HTTP/1.1", "SERVER_SOFTWARE"=>"2.12.3", "GATEWAY_INTERFACE"=>"CGI/1.2", "REQUEST_METHOD"=>"GET", "REQUEST_PATH"=>"/msp_recurring_payments"}```

**Comment by abritinthebay** [comment]
Puma's limit is 10240, which isn't THAT long but it's waaaay longer than say: IE. If you're using that long of a query string you're going to run into issues cross-browser.

However it should be configurable... ideally. Most are, and the spec actually says there is *no limit at all* which is.. you know, fun.

For reference:

* MSIE - max total url length (inc path, etc) -  2,083 characters.
* Chrome -  stops displaying after 64k characters, but can serve more than 100k characters. 
* Firefox - same as Chrome.
* Safari - will not truncate and can handle up to 100k.
* Apache - ~4,000 characters, after which Apache produces a "413 Entity Too Large" error.
* IIS -  16,384 characters, but is configurable.
* Perl HTTP::Daemon - 8,000 bytes. After which a 413 is issued.

**Comment by JoshMcKin** [comment]
I was able to work around the issue by using a POST route but it would be nice to keep controllers a bit drier by having the option to increase maximum query string.

**Comment by abritinthebay** [comment]
Well yeah, GET adds to the url so that makes sense. If you're sending data (rather than getting it) you should be using POST anyhow...

**Comment by JoshMcKin** [comment]
Its a feature that I believe Thin supported, if its not something Puma wants to do,  thats fine. Just thought it would be nice.

**Comment by thantoldo** [comment]
I second to Josh, I'm facing a situation where I can't use POST, so it would be nice if query length can be configured over 10K.

**Comment by JoshMcKin** [comment]
I should clarify this GET was to an INDEX action in a Rails controller. The index action accepts parameters a search. I have yet to work on a Rails project where at least 1 controllers index action doesn't accept extra parameters. In this case, one of input parameters could be an array of user ids. A client wanted to preform a search that included all of their users with the exception of 1, they have 1500 users and as you can image the resulting form post query string was quite long. Our work around to use a POST request to a "search" action that is really an alias of index, while effective in providing immediate relief for the client, does not follow our implementation of a standard REST API.

Initially we were not sure what was happening. When the client would submit the form the app was just rendering a blank screen. I tried tailing the Heroku logs (where the app is deployed) and nothing would show in logs when the form was submitted, New Relic missed the error as well. I wasn't until I started the app locally in production with dev logging that I was able see the error.

**Comment by evanphx** [comment]
Given you wouldn't be able to actually use something that large, I'd rather protect users out of the box and I don't see a big reason to make it configurable.

**Comment by liamwhite** [comment]
"I'd rather protect users out of the box"
This is more akin to security theater than actual security.

I recently switched over an app from Passenger Enterprise (which has left a bad taste in my mouth) to Puma, to try it out. We are now going to move to Unicorn because of this particular bug. My app doesn't exactly get enormous requests like these all the time, but it has no trouble handling extremely large requests.

I could fork puma and change the code in the C extension, but I'd really rather not do all that work if such a change would never be accepted by the team.

**Comment by nateberkopec** [comment]
@liamwhite I understand your pain but is it really that difficult to maintain a fork with a single number changed?

80% of actions that take 10,000 characters should probably be POSTs, and the remaining 20% are too edge-casey or could probably be worked around in other ways.

**Comment by liamwhite** [comment]
@nateberkopec It's that much more effort I have to put in for

- updates to puma
- bugfixes
- security vulns

if I have to maintain a fork.

This is a particular edge case where the normal GET query size would be one or two simple values in the query string, but has no theoretical limit, because not having a limit makes it a boon to users who desire to use search in interesting ways; in the context of my app, Elasticsearch doesn't really care if you're doing a filter on two terms (50ms) or two hundred thousand terms (350ms)

**Comment by Victoria-Vachevskih** [comment]
It's impossible to View Users Results or Download CSV file when URL is too long
Steps:
1. Prepare a long request in User search or use an existing one (e.g. )
2. Open it
3. Click on View Results button
Actual result:  Error 414 in Console. Users results aren't showed

4. Go to Download Result Tab
5. Click on "Download CSV" button

Actual result: Blank page appears. Error 414
This page isn’t working If the problem continues, contact the site owner.
HTTP ERROR 414
