### ISSUE TITLE
Threading error when using `ActiveRecord with_connection do` & Puma

### ISSUE THREAD

**Issue by duttski** [puma/puma#758]
Source: http://stackoverflow.com/questions/31535545/threading-error-when-using-activerecord-with-connection-do-puma , https://github.com/rails/rails/issues/21209

**Summary:**  When using Puma and running long-running connections I am consistently receiving errors related to ActiveRecord connections crossing threads. This manifests itself in message like `message type 0x## arrived from server while idle` and a locked (crashed) server.

What isn't clear is what conditions could cause the connection to be crossed between threads, i.e. am I, or is Puma, doing something wrong and needs correcting, or is the connection_pool getting confused. If you think this is better placed somewhere else then please let me know. I'm trying to do leg work on this but pretty much out of ideas!

---------------------
The set up:

 - Ubuntu 15
 - PostgreSQL (9.4) / MySQL (`mysqld 5.6.25-0ubuntu0.15.04.1`)
 - Ruby - MRI `2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]` / Rubinius `rbx-2.5.8`
 - Rails (`4.2.3`, `4.2.1`)
 - Puma (`2.12.2`, `2.11`)
 - pg (`pg-0.18.2`) / mysql2
 
Note, not all combinations of the above versions have been tried. First listed version is what I'm currently testing against.

 - `rails new issue-test`
 - Add a route `get 'events' => 'streaming#events'`
 - Add a controller `streaming_controller.rb`
 - Set up database stuff (`pool: 2`, but seen with different pool sizes)

Code:

	class StreamingController < ApplicationController

	  include ActionController::Live

	  def events
		begin
		  response.headers["Content-Type"] = "text/event-stream"
		  sse = SSE.new(response.stream)
		  sse.write( {:data => 'starting'} , {:event => :version_heartbeat})
		  ActiveRecord::Base.connection_pool.release_connection
		  while true do
			ActiveRecord::Base.connection_pool.with_connection do |conn|
			  ActiveRecord::Base.connection.query_cache.clear
			  logger.info 'START'
			  conn.execute 'SELECT pg_sleep(3)'
			  logger.info 'FINISH'
			  sse.write( {:data => 'continuing'}, {:event => :version_heartbeat})
			  sleep 0.5
			 end
		  end
		rescue IOError
		rescue ClientDisconnected
		ensure
		  logger.info 'Ensuring event stream is closed'
		  sse.close
		end
		render nothing: true
	  end
	end

Puma configuration:

	workers 1
	threads 2, 2
    #...
	bind "tcp://0.0.0.0:9292"

	#...
	activate_control_app

	on_worker_boot do
	  require "active_record"
	  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
	  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
	end

 - Run the server `puma -e production -C path/to/puma/config/production.rb`

Test script:

	#!/bin/bash

	timeout 30 curl -vS http://0.0.0.0/events &
	timeout 5 curl -vS http://0.0.0.0/events &
	timeout 30 curl -vS http://0.0.0.0/events

This reasonably consistently results in a complete lock of the application server (in PostgreSQL, see notes). The scary message comes from `libpq`:

    message type 0x44 arrived from server while idle
    message type 0x43 arrived from server while idle
    message type 0x5a arrived from server while idle
    message type 0x54 arrived from server while idle

In the 'real-world' I have quite a few extra elements and the issue presents itself at random. My research indicates that this message comes from `libpq` and is subtext for *'communication problem, possibly using connection in different threads'*. Finally, while writing this up, I had the server lock up without a single message in any log.

--------------
I don't see the issue happen if I change the controller block to look like:

	begin
	  #...
	  while true do
		t = Thread.new do #<<<<<<<<<<<<<<<<<
			ActiveRecord::Base.connection_pool.with_connection do |conn|
	  		    #...
			end
		 end
		 t.join #<<<<<<<<<<<<<<<<<
	  end
	  #...
	rescue IOError
	#...

But I don't know whether this has actually solved the problem or just made it extremely unlikely. Nor can I really fathom why this would make a difference.

--------------
**MySQL**

If running MySQL, the message is a bit different, and the application recovers (though I'm not sure if it is then in some undefined state):

	F, [2015-07-30T14:12:07.078215 #15606] FATAL -- : 
	ActiveRecord::StatementInvalid (Mysql2::Error: This connection is in use by: #<Thread:0x007f563b2faa88@/home/dev/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/live.rb:269 sleep>: SELECT  `tasks`.* FROM `tasks`  ORDER BY `tasks`.`id` ASC LIMIT 1):

**Comment by evanphx** [comment]
This definitely seems more like an issue with `activerecord` and database connections across threads. /cc @tenderlove

**Comment by duttski** [comment]
Yep apologies Puma-people, just this morning managed to get a similar issue with Rainbows too.
