### ISSUE TITLE
Trying to restart or get status with pumactl on windows keep getting bad URI(is not URI?):

### ISSUE THREAD

**Issue by acosonic** [puma/puma#762]
ruby 2.0.0p645 (2015-04-13) [x64-mingw32]
puma version 2.12.2

puma config:
threads 1, 16
environment 'production'
bind 'tcp://0.0.0.0:3000'
pidfile 'C:/ruby/puma.pid'
state_path 'C:/ruby/puma.state'
preload_app!
tag 'Redmine'
daemonize false

Puma start command:
pumactl -F config/puma.rb start

Puma restart tried:
C:\>pumactl -S C:/ruby/puma.state status
bad URI(is not URI?):

C:\>pumactl -F C:/redmine/config/puma.rb status
bad URI(is not URI?):

**Comment by evanphx** [comment]
That's not a URI, thats why. You need to specify an actual file:// uri.
