### ISSUE TITLE
HTTP Streaming with Puma

### ISSUE THREAD

**Issue by chadwtaylor** [puma/puma#763]
Trying to get HTTP Streaming (http://api.rubyonrails.org/classes/ActionController/Streaming.html) working with Puma. My understanding, through the documentations I've read, is that Puma should support it?

I was able to get streaming to work with Unicorn but our shop uses Puma and want to see if anybody have insight to configuring the Puma to support HTTP Streaming?

Any tips are greatly appreciated.

**Comment by evanphx** [comment]
@chadwtaylor are you have a problem with the way those docs indicate? Streaming does work fine in Puma.
