### ISSUE TITLE
Using a config file with pumactl and 2.13.0

### ISSUE THREAD

**Issue by keithpitt** [puma/puma#764]
I just wanted to give you guys a heads up I updated to 2.13.0, and it looks like it may have broke restarting puma on my production boxes.

I have a `puma.rb` file that defines where the `pidfile` lives. On production when I need to restart, I run: `bin/pumactl -F config/puma.rb phased-restart`, but now it seems that I may need to provide the PID manually since it doesn't read from the config file anymore?

Is this expected behaviour now? Or was I exploring something that was never really supported?

**Comment by evanphx** [comment]
Sorry about that! Should be fixed now.

**Comment by keithpitt** [comment]
Thanks @evanphx! :heart_decoration:
