### ISSUE TITLE
Phased restart ignores directory configuration when Puma is invoked from that configured directory

### ISSUE THREAD

**Issue by jamesmeador** [puma/puma#770]
Our config file looks like:
```
directory "#{ENV["HOME"]}/current"
pidfile "#{ENV["HOME"]}/puma.pid"

prune_bundler
```

Where ```current``` is  a symlinked directory to the new code.

And is passed to puma as:
```
bundle exec puma -t 16:16 -w 3 -C ${HOME}/puma.rb
```

Sending SIGUSR1 to the process results in the same directory being restarted, even though the symlink was updated.

Sending SIGUSR2 works correctly.

**Comment by jamesmeador** [comment]
After some digging, it appears that this is more of a problem with respecting the directory configuration.

It looks like puma "prefers" to use env['PWD'] but this is causing us issues.

We spawn Puma from a custom daemon that we use that listens to watches on a zookeeper node. We fire updates to the node, and whatever machines we have listening to that node will pick up the new configuration (a git sha and repo). 

When the daemon starts up, it clones the repo into a directory, say `root/master-gitsha1`. It changes into that directory, runs "bundle" to activate gems, as well as compile assets, etc.

When the setup is done, it's time to symlink `root/master-gitsha1` to `root/current` and launch puma for the first time. The daemon Dir.chdir's to `root/current`, and does 
```
Bundler.with_clean_env { Process.spawn('bundle exec puma -w 3 -C ${HOME}/puma.rb') }
```

Note that Dir.chdir in Ruby just changes to the target, thus anything spawned from Ruby means that ENV['PWD'] will be the target directory, not the symlink. In this case, the target directory is `root/master-gitsha1`.

Puma takes off. CLI.new sets `@cli_options[:worker_directory]` to `ENV['PWD']` because `Dir.pwd` and `ENV['PWD']` match.

CLI.run calls parse_options which then (via configuration.rb and dsl.rb) parses my config file, setting `@options[:directory]` and `@options[:worker_directory]` to `root/current`. Then, it merges cli_options in. **This is what I think is a bug:**

 **Now, `@options[:directory]` is `root/current` and `@options[:worker_directory]` is `root/master-gitsha1`**.

when `start_phased_restart` for a cluster is called, the directory will **always be changed to `root/master-gitsha1`**.

Seems unreasonable to me. Am I crazy? It seems silly to store a cli_option that the user didn't explicitly set. (and then override an attribute they **did** intentionally set).

**Comment by allaire** [comment]
@evanphx Having some problem with the `directory` config as well with phased-restart. Seems like the `Gemfile in context` was still pointing to the old one, where in the past (if I recall), it was using the `directory` option I had set (in my case `/current`)

**Comment by allaire** [comment]
@evanphx Any update on this? In the meantime, I'll try to rollback to a puma version prior that config refactor if it fixes it.

**Comment by allaire** [comment]
@evanphx confirmed that rolling back to `2.12.3` fixed the phased restart issue in my case. Here the upstart log:

```
[8899] - Starting phased worker restart, phase: 2
[8899] + Changing to /home/agendrix/apps/web/current
[8899] - Stopping 10925 for phased upgrade...
[8899] - TERM sent to 10925...
[12934] + Gemfile in context: /home/agendrix/apps/web/releases/20150903174757/Gemfile
[8899] - Worker 0 (pid: 12934) booted, phase: 2
[8899] - Stopping 10996 for phased upgrade...
[8899] - TERM sent to 10996...
[13003] + Gemfile in context: /home/agendrix/apps/web/releases/20150903174757/Gemfile
[8899] - Worker 1 (pid: 13003) booted, phase: 2

**Comment by allaire** [comment]
@jamesmeador Was this fixed by #793 ?

**Comment by grimm26** [comment]
#793 did not fix this for me and neither does using 2.12.3

**Comment by allaire** [comment]
@grimm26 then your issue is not related to this one.

**Comment by ifyouseewendy** [comment]
same issue, version 2.15.3

**Comment by allaire** [comment]
Rolling restarts work for us with `puma (2.15.3)` with Capistrano deploys

**Comment by ifyouseewendy** [comment]
@allaire Thanks. I was using puma 2.15.3, with mina deploy (phased restart). Got the issue, losing the right directory when restarting. Here is my conf, anything wrong?

```ruby
workers Integer(ENV['WEB_CONCURRENCY'] || 4)
threads_count = Integer(ENV['MAX_THREADS'] || 1) # Not sure for thread safe
threads threads_count, threads_count

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

prune_bundler

stdout_redirect 'log/puma.stdout.log', 'log/puma.stderr.log', true
```

**Comment by allaire** [comment]
Here's mine:

```
threads 6, 12
workers 6
pidfile "tmp/pids/puma.pid"
state_path "tmp/pids/puma.state"
bind "unix://tmp/sockets/puma.sock"
directory "/home/myproject/apps/web/current" # https://github.com/puma/puma/issues/539
prune_bundler true
```

Try defining `directory`

**Comment by ifyouseewendy** [comment]
@allaire :+1: it works, thanks very much

**Comment by allaire** [comment]
@ifyouseewendy glad to hear it :)

**Comment by grimm26** [comment]
I specify directory on the command line, but puma dereferences the 'current' symlink and sticks with that dereferenced directory after a USR1 and the 'current' symlink has changed.

**Comment by allaire** [comment]
@grimm26 did you try in the config file?

**Comment by evanphx** [comment]
This bug was fixed.
