### ISSUE TITLE
Can't install with the latest ruby

### ISSUE THREAD

**Issue by scrummie02** [puma/puma#771]
>gem install puma --version ">=2.0.b7"
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
        ERROR: Failed to build gem native extension.

    D:/RailsInstaller/Ruby2.1.0/bin/ruby.exe extconf.rb
checking for BIO_read() in -lcrypto... no
checking for BIO_read() in -llibeay32... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/RailsInstaller/Ruby2.1.0/bin/ruby
        --with-puma_http11-dir
        --without-puma_http11-dir
        --with-puma_http11-include
        --without-puma_http11-include=${puma_http11-dir}/include
        --with-puma_http11-lib
        --without-puma_http11-lib=${puma_http11-dir}/lib
        --with-cryptolib
        --without-cryptolib
        --with-libeay32lib
        --without-libeay32lib

extconf failed, exit code 1

Gem files will remain installed in D:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1
.0/gems/puma-2.13.4 for inspection.
Results logged to D:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/extensions/x86
-mingw32/2.1.0/puma-2.13.4/gem_make.out

**Comment by scrummie02** [comment]
If this is done it works:
https://groups.google.com/forum/#!topic/rubyinstaller/RkBqA6DsGl0

**Comment by dedles** [comment]
And in macs?

**Comment by evanphx** [comment]
Newest puma doesn't require openssl.

**Comment by vipulnsward** [comment]
Looks like still an issue on ruby-head https://travis-ci.org/puma/puma/jobs/121497343
This is also causing failure on rails builds with `ruby-head`.
