### ISSUE TITLE
Phased restart & symlinks - workers preserve old symlink destination

### ISSUE THREAD

**Issue by OUGHT** [puma/puma#776]
Hello!
I have an issue with phased restarts on Puma. When I deploy my app (using mina), it seems that after phased restart workers do not catch new release (marked as symlink 'current' => 'releases/25'). They continue to work in old directory:
```
[2705] + Changing to /var/www/oughtsite/releases/24
```
Versions: Puma - 2.13.4, Ruby - 2.2.3.

Steps to reproduce:
1. Configure Puma to work in directory `.../current`.
2. Make symlink from folder `.../releases/1` to `.../current`.
3. Start Puma.
4. Copy `.../releases/1` to `.../releases/2`.
5. Make symlink from folder `.../releases/2` to `.../current`.
6. Make some changes in folder `.../releases/2`.
7. Make phased restart.
Expectation: see changes made in `.../releases/2`.
Reality: see app from `.../releases/1`.

My config/puma.rb:
```
# Change to match your CPU core count
workers 8

# Min and Max threads per worker
threads 1, 6

app_dir = File.expand_path("../..", __FILE__)
shared_dir = "#{app_dir}/../../shared"

# Default to production
rails_env = ENV['RAILS_ENV'] || "production"
environment rails_env

# Set up socket location
bind "unix://#{shared_dir}/sockets/puma.sock"

# Logging
stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true

# Set master PID and state locations
pidfile "#{shared_dir}/pids/puma.pid"
state_path "#{shared_dir}/pids/puma.state"
activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
end
```

Advices from https://github.com/puma/puma/issues/468 did not help me.
Tried `pumactl reload-worker-directory` before and after phased restart, neither worked.
Please, help me!

**Comment by mcb** [comment]
:+1:  Seeing this here as well. However if we remove the puma.sock File as well, it works as it is expected. The puma.sock file does persist after stop as well.

**Comment by OUGHT** [comment]
You mean remove socket file _before_ or _after_ the phased restart? =-)

**Comment by allaire** [comment]
@OUGHT Have a similar issue here: https://github.com/puma/puma/issues/770

Our current solution is to pin to an older Puma version:

`gem "puma", "~> 2.12.3"`

Basically I think `2.13` broke this. Can you confirm this on your side? It might help @evanphx to pin this down.

Thanks!

**Comment by chenghung** [comment]
the same problem on puma-2.15.3

**Comment by evanphx** [comment]
This should be fixed now.
