### ISSUE TITLE
stdout_redirect not working for jruby daemon server

### ISSUE THREAD

**Issue by niedhui** [puma/puma#778]
when runnging in single mode using jruby ,  stdout_redirect is not working.
I saw `redirect_io` call for CRuby, 
https://github.com/puma/puma/blob/master/lib/puma/single.rb#L76
but when  jruby_daemon is true
https://github.com/puma/puma/blob/master/lib/puma/single.rb#L49
the redirect_io is not called

**Comment by evanphx** [comment]
Sorry about that and the delay!

**Comment by jxc876** [comment]
Still not working for us ... :(
