### ISSUE TITLE
Puma crashed at loading 

### ISSUE THREAD

**Issue by wonderer007** [puma/puma#779]
I am running puma with Capistrano using this tutorial

https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma 

everything is working fine except puma crashed at start.
If i start puma with it output 

uma starting in single mode...
* Version 2.13.4 (ruby 2.2.1-p85), codename: A Midsummer Code's Dream
* Min threads: 0, max threads: 16
* Environment: development
! Unable to load application: TypeError: no implicit conversion of Symbol into String
/home/office/Development/golf_backend/app/api/v1/api.rb:5:in `format': no implicit conversion of Symbol into String (TypeError)
	from /home/office/Development/golf_backend/app/api/v1/api.rb:5:in `<class:API>'
	from /home/office/Development/golf_backend/app/api/v1/api.rb:4:in `<module:V1>'
	from /home/office/Development/golf_backend/app/api/v1/api.rb:3:in `<top (required)>'
	from /home/office/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `load'
	from /home/office/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /home/office/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /home/office/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /home/office/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /home/office/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /home/office/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/office/Development/golf_backend/config/routes.rb:10:in `block in <top (required)>'

if i run rails s it works very fine

**Comment by tawan** [comment]
Hi @wonderer007 Thank for the bug report. Do you still encounter the issue?
