### ISSUE TITLE
Unable to connect through 127.0.0.1 when bound to localhost

### ISSUE THREAD

**Issue by Tonkpils** [puma/puma#782]
I'm not sure if this issue has been raised and I can't find any reference to it here but stemming from: https://github.com/rails/rails/issues/19815#issuecomment-111159194

Using `rails s` on WebRick allows using `localhost` and `127.0.0.1` to connect but when switching to `puma` this behavior changes and does not allow `127.0.0.1`

Is this intended behavior for Puma or would you be open for a fix?

**Comment by ArturT** [comment]
I had this problem and I was looking for solution. I'm not sure what is exactly the reason of this behaviour but here are things I found out and solution to fix this in my app. 

When I start `rails server` then puma listens on localhost:3000

```
$ rails server
=> Booting Puma
=> Rails 4.2.3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.13.4 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
```
and http://127.0.01:3000 doesn't work.


When I start puma explicitly without config file then it listens on  tcp://0.0.0.0:3000 and http://127.0.01:3000 does work.

Read more https://github.com/puma/puma#configuration-file
```
$ puma -C '-'
Puma starting in single mode...
* Version 2.13.4 (ruby 2.2.3-p173), codename: A Midsummer Code's Dream
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:3000
```

When I created my custom config file then it works as well
`bundle exec puma -C config/puma.rb`
```ruby
# config/puma.rb
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT']     || 3000
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end
```

**Comment by Tonkpils** [comment]
From my understanding both `rails` and `rack` moved away from defaulting the listening host to `0.0.0.0` as it caused security implications. They then moved to listening on `localhost`. Starting the app with `puma` command actually does listening on `0.0.0.0` which pretty much listens on all network interfaces. 

On other webservers, namely Unicorn and Webrick listening on `localhost` allows accessing the server from `127.0.0.1` as well as `localhost`. Puma doesn't seem to follow that same behavior though.

**Comment by evanphx** [comment]
If anyone can replicate the issue, I'd be happy to fix it. I tried a bunch of combos of rails/puma/ruby this morning and couldn't get it to pop up.

**Comment by Tonkpils** [comment]
@evanphx I simply started puma with `rails s` and tried curling `127.0.0.1` which gives me connection refused. Once I curl localhost it works just fine.

![image](https://cloud.githubusercontent.com/assets/1507561/9965383/e9e45142-5e03-11e5-8c1b-f7df8b931a78.png)

**Comment by evanphx** [comment]
@Tonkpils What version of ruby? What OS? Because ruby and the OS translate `localhost` into an address, I think those are the variables here.

**Comment by Tonkpils** [comment]
Ruby 2.2.1 and OS X Yosemite.

**Comment by Tonkpils** [comment]
So, it seems that accessing '[::1]:3000' works instead of 127.0.0.1 .

**Comment by evanphx** [comment]
Well, puma passes whatever the host you want to bind to directly to `TCPServer.new`, it doesn't do anything with it other than passing it along. So the handling of `localhost` as the value is entirely up to Ruby and and the OS.

**Comment by Tonkpils** [comment]
I'm assuming `unicorn` and `webrick` are connecting some different way than `TCPServer`. 

In any case, I'll close this as a non-issue since this is not puma's issue.

**Comment by graudeejs** [comment]
Having this issue on FreeBSD as well

**Comment by graudeejs** [comment]
I suspect it is related to this line:
https://github.com/puma/puma/blob/master/lib/puma/server.rb#L142

**Comment by chadzink** [comment]
@evanphx: Having this same issue on OSX El Capitan, this definitely seems like a puma issue. The trick ^^^ worked, not sure what `::1 localhost` means in the hosts file though.

**Comment by Tonkpils** [comment]
@chadzink `::1 localhost` simply means that accessing `localhost` will point to IPv6 address `::1`. It's simply a name resolution.

**Comment by gryphon** [comment]
The same for me. Got this issue after El Capitan upgrade.
Seems that Puma checks hostname of HTTP request to be equal to what it is binded to.

**Comment by whistlerbrk** [comment]
@evanphx I too can verify that commenting out the IPv6 line means I can access localhost aliases as well

**Comment by whistlerbrk** [comment]
If you're visiting this thread you may be forgetting that you're using, by default, IPv6 networking. As a result your resolution of `localhost` turns to `::1` rather than `127.0.0.1`. So any aliases you had on that line in your `/etc/hosts` need to be duplicated or moved to the `::1` line.

**Comment by himdel** [comment]
To clarify, it's still a puma bug if localhost can resolve to both `127.0.0.1` and `::1` - which it does on some systems.

**Comment by shawzt** [comment]
Hi @himdel , any plan to fix this?

**Comment by himdel** [comment]
@shawzt not sure.. I'd love to, but essentially what happens is `TCPServer.new('localhost', port)` - which makes me think the bug is not quite a puma bug but a `TCPServer` bug.

If you need a workaround and use puma only from rails, this works...

```rb
diff --git a/lib/puma/binder.rb b/lib/puma/binder.rb
index 6cb8909..2751484 100644
--- a/lib/puma/binder.rb
+++ b/lib/puma/binder.rb
@@ -236,6 +236,12 @@ module Puma
     # allow to accumulate before returning connection refused.
     #
     def add_tcp_listener(host, port, optimize_for_latency=true, backlog=1024)
+      if host == 'localhost'
+        add_tcp_listener('127.0.0.1', port, optimize_for_latency, backlog)
+        add_tcp_listener('::1', port, optimize_for_latency, backlog)
+        return
+      end
+
       host = host[1..-2] if host and host[0..0] == '['
       s = TCPServer.new(host, port)
       if optimize_for_latency
```

(but it's clearly not the right place to fix this).

**Comment by alecguintu** [comment]
+1 here. Just want to know how/where will I add those snippet code to @himdel?

**Comment by himdel** [comment]
@alecguintu if you look at it carefully, you'll see that it mentions both the file name and the line numbers..

**Comment by alecguintu** [comment]
Haha. I mean, where do I find the file binder.rb? I've checked on rails app, there is no puma folder under lib folder.

**Comment by insanux** [comment]
I've the same issue and I didn't find the binder.rb.

**Comment by himdel** [comment]
@alecguintu probably the safest way to find the right file would be `gem contents puma`

**Comment by alecguintu** [comment]
Thanks so much for this @himdel!

**Comment by Eduzenet** [comment]
Thank you @himdel! now it works with 127.0.0.1 and ::1

**Comment by agrberg** [comment]
For those coming here who access their Rails server via an alias you can simply duplicate your alias as @whistlerbrk said. For example, if your alias is `www.fakewebsite.com` you'll want the following two lines in your `/etc/hosts` file:

```text
127.0.0.1    www.fakewebsite.com
::1    www.fakewebsite.com
```

Looking at what @graudeejs and @himdel said in [this comment](https://github.com/puma/puma/issues/782#issuecomment-190817476) it seems like puma is matching the first valid address in your `/etc/hosts` file. If yours is like mine it'll start with:

```text
```

**Comment by tomascharad** [comment]
Hi guys,

This is a very important issue.

I was trying to proxy some requests from webpack-dev-server and had a very hard time to figure that I should change localhost:3000 to [::1]:3000.

**Comment by RobinDaugherty** [comment]
I just want to mention why this is such an issue. Issues like this cause developers to turn off IPv6 on their machine rather than a more complicated workaround. This is bad for the community and the Internet at large. We need to encourage IPv6 adoption, and every "minor" issue like this is a blocker.

**Comment by evanphx** [comment]
Hi y'all,

I'm going to go ahead and release @himdel's fix, I think it's a perfectly acceptable way to manage this issue. Sorry for the delay, the release will be out later today.

**Comment by yohayg** [comment]
I'm using: bundle exec rails server  Puma -b 0.0.0.0 -p 3000 which works just fine

**Comment by babinslava** [comment]
I'm using `rackup -p 7000 -o 127.0.0.1`

**Comment by RobinDaugherty** [comment]
This bug has been fixed, so `localhost` should work correctly with or without IPv6. Using `0.0.0.0` makes the server available to everyone on every wireless network you connect to, and `127.0.0.1` does not work with IPv6. Please leave it the default or use `localhost`.

@yohayg: your advice leaves people open to unintended public access. It would be best if you remove your comment.

**Comment by sfcgeorge** [comment]
I had this same issue that I couldn't connect locally to Puma aka `curl [::1]:3000` failed. Fixed it without disabling IPv6 by forcing Puma to listen on localhost rather than 127.0.0.1 which it was for some reason using by default.

```sh
bundle exec rails s -b localhost -p 3000 
```

So the above command works with IPv4 and IPv6.

**Comment by RobinDaugherty** [comment]
@sfcgeorge glad to hear that it's working as intended. Do you know where that default value of `127.0.0.1` was coming from? Was it in your `puma.rb` or somewhere like that?

**Comment by sfcgeorge** [comment]
@RobinDaugherty I don't wish to be the harbinger of reopened issues but I believe our app is just using the defaults. My machine is macOS High Sierra (experiencing the issue), whereas my colleague's machine running an older version of macOS is unaffected and seems to work fine.

**Comment by RobinDaugherty** [comment]
And in my case, the default is `0.0.0.0`, running Rails 4.2 on High Sierra. I suspect it's a Rails default, but I haven't had time to dig deeper.
