### ISSUE TITLE
Compilation of Puma 2.13.4 on El Capitain GM with Command Line Tools 7.0 fails

### ISSUE THREAD

**Issue by deepj** [puma/puma#783]
Ruby 2.2.3 compiled with Clang `Apple LLVM version 7.0.0 (clang-700.0.72)` through `ruby-build`

Console output:
```
$ gem install puma -v '2.13.4'
Building native extensions.  This could take a while...
ERROR:  Error installing puma:
	ERROR: Failed to build gem native extension.

    /Users/deepj/.rubies/ruby-2.2.3/bin/ruby -r ./siteconf20150913-90782-12h8n45.rb extconf.rb
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling http11_parser.c
compiling io_buffer.c
io_buffer.c:119:10: warning: passing 'uint8_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
  return rb_str_new(b->top, b->cur - b->top);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/deepj/.rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:796:20: note: expanded from macro 'rb_str_new'
        rb_str_new_static((str), (len)) : \
                          ^~~~~
/Users/deepj/.rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:727:37: note: passing argument to parameter here
VALUE rb_str_new_static(const char *, long);
                                    ^
io_buffer.c:119:10: warning: passing 'uint8_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
  return rb_str_new(b->top, b->cur - b->top);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/deepj/.rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:797:13: note: expanded from macro 'rb_str_new'
        rb_str_new((str), (len));         \
                   ^~~~~
/Users/deepj/.rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:706:29: note: passing argument to parameter here
VALUE rb_str_new(const char*, long);
                            ^
2 warnings generated.
compiling mini_ssl.c
In file included from mini_ssl.c:3:
/Users/deepj/.rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/backward/rubyio.h:2:2: warning: use "ruby/io.h" instead of "rubyio.h" [-W#warnings]
#warning use "ruby/io.h" instead of "rubyio.h"
 ^
mini_ssl.c:4:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
         ^
1 warning and 1 error generated.
make: *** [mini_ssl.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/deepj/.gem/ruby/2.2.3/gems/puma-2.13.4 for inspection.
Results logged to /Users/deepj/.gem/ruby/2.2.3/extensions/x86_64-darwin-15/2.2.0-static/puma-2.13.4/gem_make.out
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
```

**Comment by hellojere** [comment]
+1

**Comment by deepj** [comment]
One of solutions is the following

```bash
brew install openssl
brew link --force openssl
```

If I remember it correctly OpenSSL (headers only???) has been removed in favour of Apple's own crypto library. Some solution how to fix this (as above) would be mentioned in `README`. I guess for some people this will be unpleasant surprise on El Captain.

**Comment by hellojere** [comment]
Thanks, worked!

**Comment by isaachall** [comment]
Instead of force linking openssl, this command worked for me using El Capitan (10.11) and openssl installed (but not linked) via Homebrew:

```sh
$ gem install puma -v 2.13.4 -- --with-opt-dir=/usr/local/opt/openssl
```

**Comment by gvt** [comment]
+1 this worked for me on El Capitan 
`gem install puma -v 2.13.4 -- --with-opt-dir=/usr/local/opt/openssl`

**Comment by deepj** [comment]
@isaachall Yes, that is another solution. But I have couple of scripts (which are run on other machines with different OSs and settings) installing gem dependencies via Bundler. So this approach is not viable for me. So the solution is linking OpenSSL on my machine.

**Comment by evanphx** [comment]
Good news everyone! I've just released `2.14.0` which makes SSL optional. So on platforms without OpenSSL (like El Capitan) puma will build without issue but you won't have SSL. Normally that's not an issue on OS X, so there ya go!

**Comment by deepj** [comment]
@evanphx :+1:

**Comment by carlosveucv** [comment]
+1.
For older versions `gem install puma -v '2.1X.X' -- --with-opt-dir=/usr/local/opt/openssl` works like a charm.

**Comment by vladiim** [comment]
+1

**Comment by oshchygol** [comment]
```bundle config build.puma --with-opt-dir=/usr/local/opt/openssl```

**Comment by olivierlacan** [comment]
I would highly recommend against doing:

```
gem install X --with-opt-dir
```

This will only fix the problem for the current Ruby version your using, and the current Puma version. Any subsequent install will still fail. It's much better to use @oshchygol's advice of configuring Bundler to learn how to build Puma's native extensions:

```
bundle config build.puma --with-opt-dir=/usr/local/opt/openssl
```

Again, assuming you're using the openssl from Homebrew.

For the record your can find these build instructions in `~/.bundle/config` or display them with `bundle config`.

**Comment by vishaldeepak** [comment]
yes worked for me thanks

**Comment by llwang8** [comment]
This one works for me.  Thanks deepj,
------------------------------
deepj
One of solutions is the following

brew install openssl
brew link --force openssl

**Comment by cema-sp** [comment]
For me worked only this (brew install openssl - without linking):
~~~
gem install puma -v '2.13.4' -- --with-opt-include=/usr/local/opt/openssl/include
~~~
And bundler config:
~~~
bundle config build.puma --with-opt-include=/usr/local/opt/openssl/include
~~~

**Comment by ninabreznik** [comment]
gem install puma -v 2.13.4 -- --with-opt-dir=/usr/local/opt/openssl worked on El Capitan. Thanks.

**Comment by voelzmo** [comment]
Shouldn puma use pkgconfig, such that `export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig` works as well?

**Comment by Marcos2015** [comment]
I use: gem install puma -v 2.13.4 -- --with-opt-dir=/usr/local/opt/openssl
          brew link --force openssl
still can't resolve the problem, I use EI Capitan, please help me !


/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
/bin/sh ./libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I./compat -I./include -I./include    -g -O2 -Wall -fno-strict-aliasing -Wno-deprecated-declarations -D_THREAD_SAFE  -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c -o bufferevent_openssl.lo bufferevent_openssl.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./compat -I./include -I./include -g -O2 -Wall -fno-strict-aliasing -Wno-deprecated-declarations -D_THREAD_SAFE -MT bufferevent_openssl.lo -MD -MP -MF .deps/bufferevent_openssl.Tpo -c bufferevent_openssl.c  -fno-common -DPIC -o .libs/bufferevent_openssl.o
bufferevent_openssl.c:60:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
         ^
1 error generated.
make[2]: *** [bufferevent_openssl.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by rahuldavd** [comment]
I have downloaded openssl-0.9.8k_X64.zip and followed link https://github.com/hicknhack-software/rails-disco/wiki/Installing-puma-on-windows#install-the-puma-gem but on trying to install gem install puma -- --with-opt-dir=c:\openssl but it is giving error:-193: %1 is not a valid Win32 application. - C:/Ruby22/lib/ruby/2.2.0/i386-mingw32/openssl.so
i have followed each step but couldn't get to install Puma.

**Comment by patr1ck** [comment]
FYI – For users of macports, this can be solved similarly using the macports opt path:
```
gem install puma -- --with-opt-include=/opt/local
```
or with bundler config
```
bundle config build.puma --with-opt-include=/opt/local
```

**Comment by traynorkevin** [comment]
+1 !  gem install puma -v 2.13.4 -- --with-opt-dir=/usr/local/opt/openssl
Worked for me!!! I used version 3.4.0 though!

**Comment by albertoalmagro** [comment]
You also need to care about in which directory is puma being installed. i.e. If you wat Puma to be installed in your application's vendor/bundle directory you may have to run:

`gem install puma -v 2.13.4 -i ./vendor/bundle -- --with-opt-dir=/usr/local/opt/openssl`

**Note**: Puma version, vendor/bundle and openssl directories may be different in your case.

**Comment by gerard-morera** [comment]
@albertoalmagro solution works for me. I am using rbenv

**Comment by sonjarae** [comment]
gem install puma -v '3.0.0' -- --with-opt-dir=/usr/local/opt/openssl
bundle install 
💪

**Comment by annzenkina** [comment]
```
bundle config build.puma --with-opt-include=/usr/local/opt/openssl/include/
```

Worked for me on MacOS 10.12.6.

**Comment by voelzmo** [comment]
@evanphx I'd like to re-iterate my question in https://github.com/puma/puma/issues/783#issuecomment-190245578 given that there are still numerous users commenting on this: 
> Shouldn't puma use pkgconfig, such that export PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig works as well?
