### ISSUE TITLE
Creating pidfile before app initialization

### ISSUE THREAD

**Issue by kml** [puma/puma#785]
I have rails app with initializer building cache. It takes some time (~ 1-2 minutes).
There is also monit monitoring if process exists. It checks pidfile.
Because initialization takes very long monit thinks that app is not running and starts another instance of it.
It would be helpfull if puma could create pidfile much earlier - before load_and_bind/load_rackup.

What you you think about this idea?

I'm using puma in single mode without daemonization, so I created patch:
https://gist.github.com/kml/5559c5a515e042960efc

It's my first patch in life added to Gemfile :)

**Comment by evanphx** [comment]
Send a PR!
