### ISSUE TITLE
Im having difficulties running puma with capistrano and puma jungle. Get the error `puma.sock failed (111: Connection refused)`

### ISSUE THREAD

**Issue by THPubs** [puma/puma#786]
I have setup `capistrano3-puma` gem. I can successfully deploy the app to my server and puma also works. But when restarted puma won't start. So, I added the puma jungle init scripts. Now in the nginx-error log I see this error :

    2015/09/20 13:21:46 [error] 747#0: *3 connect() to unix:/home/kahir03/kahawanu/shared/tmp/sockets/kahawanu-puma.sock failed (111: Connection refused) while connecting to upstream, client$
    2015/09/20 13:21:58 [info] 747#0: *2 client closed connection while waiting for request, client: 123.231.126.48, server: 0.0.0.0:443

If I deploy the site using capistrano again it will work. Either puma is not running or the puma jungle have trouble connecting to my site. What might be the real problem here?

**Comment by Preen** [comment]
What was the error here?

**Comment by shilpi230** [comment]
I am also getting the same error. Any fixes please?
