### ISSUE TITLE
URI Backport crashes if loaded by multiple gems.

### ISSUE THREAD

**Issue by herregroen** [puma/puma#788]
Puma includes a backport of URI located here:

https://github.com/puma/puma/blob/master/lib/puma/rack/backports/uri/common_193.rb

This seems to be included not only in Puma but in other gems as well. When two or more gems include this backport it leads to a direct crash as they attempt to modify a hash that's just been frozen by the first gem.

**Comment by dunyakirkali** [comment]
:+1:
