### ISSUE TITLE
Inconsistent behavior in Ubuntu with clustered mode

### ISSUE THREAD

**Issue by cadizjavier** [puma/puma#789]
I have the following sample scenario with the following use case ready to replicate.

```shell
rails new sample
cd sample
rails g controller foobar home endpoint
```

I added `puma` and `httparty` to my Gemfile. Then in `foobar_controller.rb` i type the following inside the `home` method getting like this.

```ruby
def home
  HTTParty.get('http://localhost:3000/foobar/endpoint')
end
```

So if i run the rails server and type in the console `curl http://localhost:3000/foobar/home` i should get an immediate response. Notice that this will only happen if i run a web server with multiple workers. Running default webrick in development or unicorn/puma with one worker will result in a HTTParty timeout because each single request to `foobar#home` will take up two requests to the server and only one worker is available.

If my understanding is correct, when i set puma in clustered mode with more than one worker the above example should work. So if i run the app with `puma -p 3000 -w 3` (clustered mode) it should work.
Well, it does in OSX as expected but in my Ubuntu machine it works oddly. Some times (almost always the first time) works but when hit refresh or call the curl command again after a reasonable time it returns a timeout.
Again this is happening only in my Ubuntu machine. I have similar hardware specs in both machines, running Ruby 2.2.3, rbenv and Rails 4.2.4.

I don't know if my understanding of the situation is right but it seems to me like an issue.

**Comment by eliank** [comment]
I'm encountering similar issues, the requests aren't sent to an idle worker but instead to a worker that is already handling a request. This wouldn't be an issue if the worker threads handled requests concurrently, but in conjunction with MRI it doesn't

**Comment by evanphx** [comment]
Puma doesn't have control over which worker gets the request, the OS controls that. If you want to that kind of load balancing, you'll need to use something in front of haproxy or (and this is better) do that work in the background with something that does proper balancing, like sidekiq.
