### ISSUE TITLE
Still seeing occasional total outages on Heroku

### ISSUE THREAD

**Issue by vincentwoo** [puma/puma#797]
I've been running puma on Heroku since they made it the officially sanctioned option, but have continuously run into situations were all requests, randomly, start `H12`ing. This results in my app being entirely offline.

How can I begin debugging this issue? I'm running the very latest in `puma` and `rack-timeout-puma`. Should I... not run the latter? Is there some debugging option I can turn on to get better logs? All I see now are all my requests mysteriously dying.

**Comment by vincentwoo** [comment]
Taking a page from the other issue with dead workers, I've added the following to my `config.ru` in the hopes of catching something next time:

```ruby
if ENV['RACK_ENV'] == 'production'
  module PumaThreadLogger
    def initialize *args
      ret = super *args
      Thread.new do
        while true
          puts "puma threads: #{@workers.select{|x| x.alive?}.size}/#{@workers.size} alive"
          sleep 10
        end
      end
      ret
    end
  end

  module Puma
    class ThreadPool
      prepend PumaThreadLogger
    end
  end
end
```

**Comment by evanphx** [comment]
What configuration are you using? How many workers, how many threads?

**Comment by evanphx** [comment]
Do you have any logs around when the H12s begin?

**Comment by vincentwoo** [comment]
I see no untoward log messages at the start of H12 periods, besides perhaps an exclusive lock message from postgres. I am running one worker, seven threads per 2x dyno.

**Comment by vincentwoo** [comment]
Yeah, it *might* be correlated with these kinds of postgres issues:


590720474347274240	2015-10-13T22:39:18	2015-10-13T22:39:18Z	102409703	CoderPad	54.161.169.179	Local0	Info	app/postgres.12931	[DATABASE] process 12931 still waiting for ExclusiveLock on tuple (18856,8) of relation 16435 of database 16385 after 1000.129 ms Detail: Process holding the lock: 12210. Wait queue: 12274, 12190, 12243, 12307, 12335, 12191, 12312, 12378, 12333, 31279, 21050, 2855, 11741, 4825, 31612, 21051, 21061, 12882, 21073, 12872, 12881, 12931. Query: UPDATE "pads" SET "events" = '....', "updated_at" = '2015-10-13 22:39:17.370246' WHERE "pads"."id" = 242792 

I could see deadlocking on a pg lock causing puma to stop being able to accept new requests. Restarting the dynos fixed the issue. Is there some way for puma to catch situations like this? Is this exacerbated by running `rack-timeout-puma`?

**Comment by JoshMcKin** [comment]
Could be rack time out is killing the request before it releases the lock on the table. I'd try removing it.

https://github.com/heroku/rack-timeout#timing-out-inherently-unsafe

**Comment by vincentwoo** [comment]
@schneems do you think having this passage on the default heroku docs might need reconsidering? https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#timeout

**Comment by schneems** [comment]
You should be releasing your lock in an ensure block. Rack timeout might be causing the exception but it is your applications responsibility to clean up when an exception is raised

**Comment by vincentwoo** [comment]
@schneems I'm not doing any locking manually, it's probably just happening in Rails underneath me.

**Comment by schneems** [comment]
Got it. Active Record should be handling exceptions properly. If not, well we'll need to reproduce the bug and file an issue. Do you have a suggested edit for the devcenter? Rack Timeout has many many problems and caveats, however it's still the best (only?) way to keep your app from being locked up when you get too many requests (as far as I know).

@evanphx awhile ago you were toying with some worker based timeouts. What ever happened to all that?

**Comment by vincentwoo** [comment]
@schneems I'll try but that might be hard for me to pull off. Do you have any recommended approaches for debugging whether we're locking up workers or not? I can try just curl hammering some endpoints locally and hoping.

**Comment by schneems** [comment]
If you have logs from an endpoint so you know where in your app the problem is coming from, you could try a tool like siege. However you'll also need to detect the failure condition of when a response is not returned by your server. I'm not sure if siege gives us good insights into this, maybe a custom curl script might be better, idk. You can also try to force the problem by decreasing the rack timeout. 

Once you can reproduce, from there you'll need to pull out the problem query into a new app we can share with contributors and some reproduction instructions.

It will be a lot of work and won't be easy. It might end up that we can't reproduce locally, if that's the case then maybe there's something else happening. This is one of those cases where you either decide to timebox it and shoot the moon or look for workarounds.

**Comment by jchatel** [comment]
I have some too. I have multiple Heroku dynos (5 for web). And my config is as recommended on Heroku (2 Workers, 5 Threads). I don't have any time out because my requests don't take long, there is the occasional db taking a bit of time to serve the request but that's all.

Yet since I moved to puma I had a few occurrences of blocked dynos.

heroku router - - at=error code=H12 desc="Request timeout" method=GET path="[simple request here]" host=[my domain] request_id=ae10b6f6-0028-4393-b99a-a104353c0f87 fwd="84.19.57.4" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0

and hours later, web.1 still failing. May have been an underlying problem before when I was using webbrick (default) and I did not configured timeout in rack but that's not good. I don't see why any request would take so long to execute.

I do have one lock on the database (with_lock do) to prevent multiple threads to update the same object list, but it only sets some flags (unlikely to time out, and the other web.X are all working on Heroku, so no deadlock).

Thinking of going back to webbrick :(

**Comment by guillaumebesse** [comment]
Do you use New Relic ? We had issues with it and puma.

**Comment by jchatel** [comment]
Yes I do.

**Comment by guillaumebesse** [comment]
we stop using New Relic after Puma migration...

**Comment by jchatel** [comment]
Did that stop the H12 errors for you? I hardly use New Relic (except when I need it of course :/)

**Comment by guillaumebesse** [comment]
We had a lot of H12, H13 and R12 errors. The outages were chaotic and restarting the web app (eventually several times) fixed temporary the problem. 

We also had a hight level of postgres memory cache usage :  it is a bug in prepared statements in activerecord https://github.com/rails/rails/issues/14645. We didn't try to re-introduce New Relic after all this difficulties.

**Comment by schneems** [comment]
I had super crazy high memory on one app and all the errors you mentioned. It turned out to be an includes that was loading thousands of models that weren't being used. https://github.com/codetriage/codetriage/commit/facfbd775513609024465d70ebd77a14042059e7

**Comment by vincentwoo** [comment]
This happened again today on one of my dynos. Logging indicates that all worker threads are alive, but a ton of `H12` errors were going on. No undue stress on the dynos, low volume (far past peak for the day). No postgres errors (indeed, I turned off prepared statements), no rack-timeout. I have no idea how to reproduce or what to do to mitigate. My app's memory footprint is very stable and doesn't go over 50% of the dyno allotment.

I'd really love some advice! This is a very scary thing to have happen in production.

**Comment by JoshMcKin** [comment]
@vincentwoo, ask Heroku if you have a "noisy neighbor". We saw something similar on standard dynos a few months ago. Heroku's support explained another users application, sharing server public resources with our app, was eating all the public resources. The issue i have described only accured on a single dyno and after restart the issue we disappear. 

If you dont have something now get NewRelic or a similar service and enable their  "availability monitoring" which alert you of a down time. Then the next time you have an event, open a ticket with Heroku with their highest priority.

I've never experienced issues using NewRelic described by @guillaumebesse but if you are concerned there are other app monitoring services available.

**Comment by schneems** [comment]
With H12 you are seeing a request that is taking longer than 30 seconds. You need info on what your app is doing when that happens, the best way we have to do that for now is Rack::Timeout. When the timeout fires you'll get a backtrace, use that backtrace to see where in your code you are stuck. Is it the same place every time?  If you don't kill the request it will stay stuck and other requests will back up behind it and cause more H12s. 

If you think you're hitting noisy neighbors, you can try performance dynos which are on a dedicated VPS instead of a shared runtime.

**Comment by schneems** [comment]
Any update? Did you try performance dynos? Did you try out Rack::Timeout to get backtraces?

I've been thinking about writing another gem that doesn't actually kill the thread (which can cause it's own new problems) but instead only outputs debug information when a request goes over a certain time.

Relatedly, i'm wondering if some kind of a long request worker restart for puma would be effective. Basically when a request goes over some limit the master process sends a "quit processing new requests" to all threads. Once each thread stops minus the one that is stuck then the whole worker is restarted. There's two problems i'm trying to address. One is hung/stuck requests. When these happen they pile up other hung requests after them where the client disconnects before a response is written, however puma doesn't know and keeps processing old requests. Currently the only solution to this is to use Rack::Timeout. Unfortunately this throws exceptions in arbitrary threads. It's not safe. See http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/ for more context about why raising on another thread is bad. In some cases adding Rack::Timeout causes more problems than it solves.

**Comment by vincentwoo** [comment]
@schneems When I was running rack-timeout, I was seeing even more problems, and certainly got no backtraces of value.

I can't really afford to just turn on performance dynos and wait - this problem happens infrequently enough that I'd never really be sure (and also eat a hefty bill in the meantime). If you're willing to comp me the dyno time, I'm happy to give it a shot, though.

Your points about Timeout's unsafeness are what I had in mind too. I WAS logging the number of alive threads in Puma, and it reported everything as healthy when I saw the issue, but I have no idea if that's information you can trust.

**Comment by schneems** [comment]
You could try running your app directly AWS if you can't afford to run a Performance-M dyno for a few days. They're pro-rated so you only pay for what you use. Generally the pattern is to run more puma workers on fewer instances. So if you're running 5 regular dynos, with 1 worker each, you could maybe get the same throughput by running 1 Performance M dyno (2.5 GB of Ram) with 5 workers. I don't have a budget for debugging performance problems, would be nice if I did. If the problem happens this intermittently you could probably get away with something like Puma Worker Killer's rolling restarts.

**Comment by vincentwoo** [comment]
The time between incidents is something like a few weeks. I run 7 workers on two 2x dynos right now. Is that... too many? I basically only use half of the available RAM with that configuration.

**Comment by vincentwoo** [comment]
@schneems Happened again to me just now. Filed a high priority request with heroku support but they are closed right now. Trying to see if it is "noisy neighbor" related. If you could lend your support, that'd be great too: https://help.heroku.com/tickets/315102

**Comment by vincentwoo** [comment]
I think this might be related to issues like https://github.com/heroku/rack-timeout/issues/39 - I've got some code that uses httpclient + Timeout under the covers. Investigating more.

**Comment by larchiu** [comment]
@vincentwoo / @schneems , were you able to solve this issue? We're getting this H12 problem happening at least once a week on a static page in Heroku with one of our two dynos. :(  The issue does not stop until we do a dyno restart.

**Comment by evanphx** [comment]
@larchiu what version of puma? Can you try with the latest version?

**Comment by vincentwoo** [comment]
I think my issues were exacerbated by certain long running requests. I removed or optimized every endpoint that ran for more than a short number of milliseconds and haven't seen issues since. My intuition is that puma can get into a bad state with long requests piling up. We never figured out a root cause.

**Comment by jchatel** [comment]
For me, I stopped using New Relic and used rack-timeout in production. No problem since.

**Comment by benoittgt** [comment]
@jchatel We have some issues too. We use a lot newrelic. Did you contact them before removing the service?

**Comment by jchatel** [comment]
Honestly, I wasn't using new relic, the things that interested me were badly priced (too high for my usage). I just removed it.

**Comment by larchiu** [comment]
@evanphx/all, thanks for your response. 

@evanphx, we currently have puma (2.15.3) installed now on Heroku.  Was there a particular fix in v2.16.0 that would potentially solve request timeout issues in Heroku?

**Comment by Baril27** [comment]
I am getting this same issue after upgrading to puma on heroku. I am using rack-timeout and newrelic as well. Looking at the logs the H12's occur at random points and well below the 29 second cutoff in rack-timeout.

**Comment by benoittgt** [comment]
@Baril27 Which version of puma and ruby are you using ?

**Comment by larchiu** [comment]
We had the same H12 issue for v2.15.3. 

The problem went away after the upgrade to  v2.16.

**Comment by wcurtis** [comment]
Unfortunately we've been seeing the same problem with `v2.16` in prod. Ruby 2.3.0.

**Comment by schneems** [comment]
We've seen an issue on a few apps where the "mysterious" behavior always happens after a restart. The best we can tell is that it happens because lots of requests are being held by our router while the new app boots. After it boots there are too many requests to catch up and even with rack timeout the backlog never entirely catches up. 

I'm not 100% sure exactly what the failure mode is, but I can tell you that everyone we've asked to use rack-timeout and preboot https://devcenter.heroku.com/articles/preboot have seen the problem go away.

**Comment by Baril27** [comment]
@benoittgt 
Currently on:
```
ruby '2.3.0'
puma '2.14.0'
````

I am going to bump puma to `2.16.0` see how that goes first stay tuned!

**Comment by Baril27** [comment]
So little update. After upgrading to puma v2.16.0 I have not seen the random timeouts for the last two days. Going to say for me its fixed.

**Comment by benoittgt** [comment]
Thanks @baril27 !

**Comment by evanphx** [comment]
Great! If you're here because you're having this issue still, open a new issue.
