### ISSUE TITLE
Connection pooling problem on aws rds postgresql multi az

### ISSUE THREAD

**Issue by klemenkobetic** [puma/puma#805]
Using amazon aws rds postgresql multi az deployment, connection pooling doesnt work.

Repeat with:
1. set up aws rds postgresql multi az deployment database 
2. Set up app with datababase endpoint defined as amazon's www (example :   host: name.hash.eu-west-1.rds.amazonaws.com)
3. run ap

netstat shows a pool of open connection towards ip that database hostname resolves. Now restart aws rds and force failover (possible via console). Ip of the database changes, but connection pool still holds established connections towards "old" instance (in different az, that is not available to us to read) open. If you restart aws rds again and force failover "back" the app again starts to work.

Problem with connection pooling (?)

**Comment by klemenkobetic** [comment]
similar problems:
https://github.com/felixge/node-mysql/issues/821

**Comment by tawan** [comment]
Hi, CodeTriage assigned this issue to me.

@klemenkobetic Can you elaborate on how you connect to the database? Which client library did you use?

**Comment by klemenkobetic** [comment]
Hi!

We used this gem and we are connecting to the database as written in gem documentation  :
https://rubygems.org/gems/pg/versions/0.18.2

**Comment by evanphx** [comment]
You need to manage the connections and the connection pool more tightly if you're having a stale connection problem. This is outside the scope of puma.

**Comment by ccastaneda13** [comment]
hi @klemenkobetic , ran into the same issue. Did you find a workaround for this or some health check script to auto restart the puma servers on the failover?
