### ISSUE TITLE
Logs  are blank on production

### ISSUE THREAD

**Issue by grepruby** [puma/puma#806]
@evanphx 

I am using puma on production env. My production logs partially blank . It looks very weird. Some of logs are getting appear in production.rb and not all. 

Any hint would be really helpfull.

**Comment by mwpastore** [comment]
This may be related to #880?

**Comment by evanphx** [comment]
Do you have any more info about this? How much data is in the logs? What framework are you using? Who is writing the log?

**Comment by grepruby** [comment]
Having same issue with my production app. When I start puma, everything works fine. Log appears in production.log however over the time, it doesnt log anything in log file.

**Comment by evanphx** [comment]
@grepruby What log? On defined by the puma config file? Or a Rails log? I need more info.

**Comment by grepruby** [comment]
@evanphx Rails log are blank.

**Comment by evanphx** [comment]
Are you using a log rotator? Did you send it `SIGHUP` after the logs were rotated?

**Comment by evanphx** [comment]
At present I don't have enough data to know what the issue is. If it's still a problem, please reopen this issue.
