### ISSUE TITLE
Any way to monitor # of threads on Heroku?

### ISSUE THREAD

**Issue by jjb** [puma/puma#807]
(btw I couldn't find an email list on which to ask this, are github issues the correct venue?)

Is there a way to monitor the # of threads in use (and anything else?) on Heroku?

**Comment by albertnetymk** [comment]
http://newrelic.com/ can do it.

**Comment by jjb** [comment]
:disappointed:

**Comment by evanphx** [comment]
I figured the comment about new relic was best. There are services to help
you do this. There isn't another way on Heroku.

**Comment by jjb** [comment]
:cool:
