### ISSUE TITLE
Outdated comment?

### ISSUE THREAD

**Issue by vemv** [puma/puma#808]
https://github.com/puma/puma/blob/master/tools/jungle/upstart/puma-manager.conf :

```
# Set this to the number of Puma processes you want
# to run on this machine
env PUMA_CONF="/etc/puma.conf"
```

**Comment by micfan** [comment]
I have install puma-manager plugin by [digital ocean guide](https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma) one month ago, and it works well.

However, if only the system wide cmd was packaged to apt-get or the same ones should be easy to install & config.

**Comment by vemv** [comment]
How is your reply related to the outdated comment I point out?
