### ISSUE TITLE
Report on # of threads, number of currently active threads, and backlog depth to determine how saturated our servers are

### ISSUE THREAD

**Issue by Taytay** [puma/puma#811]
First, Puma is awesome.

We currently use the Puma Stats Logger : https://github.com/hired/puma-stats-logger
It dumps our stats in a way that Librato can understand.
It dumps whatever Puma gives it. However, when running in cluster mode, all Puma reports from the control server URL is the workers count, the booted workers count, and the "phase".  
There are other things that would make our monitoring much more insightful. 
In particular, we are trying to determine how saturated our Puma servers are at any given second. Basically: How many open connections we are currently holding open (which I believe is the currently active threads), the total # of threads (across all clusters), and the backlog depth. 

If we had this, we'd know when our Heroku dynos were approaching being saturated.

If these are easily available to us, I can try to add it to the `stats` method myself - would you have any pointers on where to find these values?

**Comment by Taytay** [comment]
I've ended up writing this code and putting it in my config.ru. I got the base of the code from @vincentwoo here : https://github.com/puma/puma/issues/797#issuecomment-147892653

```ruby
module PumaThreadLogger

  def initialize *args
    ret = super *args
    Thread.new do
      while true

        # Every X seconds, write out what the state of this dyno is. We can sum these values every minute to determine how things look
        sleep 5

        thread_count = 0
        backlog = 0
        waiting = 0

        # I don't do the logging or string stuff inside of the mutex. I want to get out of there as fast as possible
        @mutex.synchronize {
          thread_count = @workers.size
          backlog = @todo.size
          waiting = @waiting
        }

        # For some reason, even a single Puma server (not clustered) has two booted ThreadPools.
        # One of them is empty, and the other is actually doing work
        # The check above ignores the empty one
        if (thread_count > 0)

          # It might be cool if we knew the Puma worker index for this worker, but that didn't look easy to me.
          # The good news: By using the PID we can differentiate two different workers on two different dynos with the same name
          # (which might happen if one is shutting down and the other is starting)
          source_name = "#{Process.pid}"

          # If we have a dyno name, prepend it to the source to make it easier to group in the log output
          dyno_name = ENV['DYNO']
          if (dyno_name)
            source_name="#{dyno_name}."+source_name
          end
          msg = "source=#{source_name} "

          msg += "sample#puma.backlog=#{backlog} sample#puma.active_connections=#{thread_count - waiting} sample#puma.total_threads=#{thread_count}"
          Rails.logger.info msg
        end
      end
    end
    ret
  end
end

module Puma
  class ThreadPool
    prepend PumaThreadLogger
  end
end
```

**Comment by vincentwoo** [comment]
@taytay any chance you could add backlog depth to the `stats` endpoint as a PR into puma? I think this really should be in there fore debugging purposes. Would help a TON on Heroku.

cc @schneems

**Comment by jeffblake** [comment]
Any chance of getting the control server to report the # of "actively serving threads"? It currently reports the count of spawned threads per worker, but not how many are serving a request.

**Comment by evanphx** [comment]
#891 provides the required functionality.

@jeffblake That seems possible, yeah. Please open a new issue about it.

**Comment by jjb** [comment]
@Taytay I'd love to hear what your overall solution to this was / currently is.

**Comment by jjb** [comment]
I created a method for logging these stats to stdout on heroku, would love anyone's feedback! https://github.com/puma/puma/issues/1512
