### ISSUE TITLE
phased restart does not update process names

### ISSUE THREAD

**Issue by gucki** [puma/puma#812]
When I do a phased restart of puma by sending USR1 it works as expected. However the process names are not updated and so make one assume they run a different (older) version than they actually are.

Before restart:

    butler   14434  0.0  0.1 135384 12912 ?        Sl   14:36   0:00 puma 2.14.0 (unix://tmp/puma.sock) [20151029132938]
    butler   14437 20.5  1.6 3254124 135460 ?      Sl   14:40   0:26 puma: cluster worker 0: 14532 [20151029132938]
    butler   14438 21.8  1.8 1658660 150620 ?      Sl   14:40   0:27 puma: cluster worker 0: 14434 [20151029132938]

After restart:

    => puma.log <==
    [14434] - Starting phased worker restart, phase: 1
    [14434] + Changing to /home/test/app/current
    [14434] - Stopping 14437 for phased upgrade...
    [14434] - TERM sent to 14437...
    [16122] + Gemfile in context: /home/test/app/releases/20151029133952/Gemfile
    ....

    butler   15634  0.0  0.1 1354647 12952 ?       Sl   14:50   0:00 puma 2.14.0 (unix://tmp/puma.sock) [20151029132938]
    butler   18465 21.5  1.3 2254124 155460 ?      Sl   14:53   0:28 puma: cluster worker 0: 14532 [20151029132938]
    butler   18468 21.0  1.6 1658660 120620 ?      Sl   14:53   0:26 puma: cluster worker 0: 14434 [20151029132938]

**Comment by allaire** [comment]
Related? https://github.com/puma/puma/issues/770 & https://github.com/puma/puma/issues/776

**Comment by gucki** [comment]
@allaire I read those but I'm not sure as in my case puma seems to load the correct code (follow the new symlink), it just doesn't update the name of the process.

**Comment by unleashed** [comment]
This used to happen to me, but it went away for me using `--dir` option in CLI. You should try the latest version and see if this is now fixed.

**Comment by allaire** [comment]
@evanphx went frenzy and merge a lot of stuff, cool.

I see this got merged in, maybe it fixes this? https://github.com/puma/puma/commit/718c401c7b1334dc6b6563127062472eb9e58840

**Comment by evanphx** [comment]
Is this still an issue?

**Comment by allaire** [comment]
@evanphx Phased restart bug worked with your latest fix, I think this should cover this as well!
