### ISSUE TITLE
Can't install puma -- error: expected specifier-qualifier-list before ‘uint8_t’

### ISSUE THREAD

**Issue by nate-dipiazza** [puma/puma#815]
The C code cannot compile. The error is in io_buffer.c.
```c
gcc -I. -I/usr/local/lib/ruby/1.8/x86_64-linux -I/usr/local/lib/ruby/1.8/x86_64-linux -I. -Wno-deprecated-declarations    -fPIC -g -O2   -c io_buffer.c
io_buffer.c:6: error: expected specifier-qualifier-list before ‘uint8_t’
```
I can install version 1.5.0.

I'm running ruby 1.8.7 on Redhat 5.11. Are you aware of any dependencies that are preventing me from installing a 2+ puma gem?

**Comment by evanphx** [comment]
That must be a very, very old linux if 'uint8_t' isn't available.

**Comment by jmacmullin** [comment]
I get the same error when attempting to install the latest Puma on Mac OS X El Capitan

**Comment by jmacmullin** [comment]
Well, similar:
io_buffer.c:118:10: warning: passing 'uint8_t *' (aka 'unsigned char *') to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]

**Comment by micfan** [comment]
@jmacmullin Why this occurs in Mac machine? My Ruby version is RVM.ruby-2.2.1
