### ISSUE TITLE
Optimal configuration for quad core CPU

### ISSUE THREAD

**Issue by bdorry** [puma/puma#825]
I understand this might not be the best place to look for this info, I just haven't found a good resource for this. I'm looking to optimize the puma configuration on our servers, scaling up to a quad core CPU (AWS c3.xlarge). 

What would be the optimal worker/thread configuration? It already looks like puma utilizes all four CPUs on the machine with one worker. Is there any utility in adding additional workers to the puma config?

**Comment by Edwardzyc** [comment]
What ruby implementation are you running?

worker count should optimally be equal to the number of cores on your system(4)
thread count should be 4-8

If anyone thinks otherwise - post a comment!

**Comment by evanphx** [comment]
If you want to max out the instance, use 4 workers and tune the thread count up until the workers are using 100% each.
