### ISSUE TITLE
ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8)

### ISSUE THREAD

**Issue by senott** [puma/puma#827]
I'm using Puma 2.12.3 with NGINX 1.4.6, Rails 4.2.5 and Ruby 2.1.3 on an Ubuntu 14.04. My application is in brazilian portuguese and some STATIC pages have characters like é, ã, ç.
When I run Puma trough a socket and try to access one of those static pages I get the following error:
ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8)
The line indicated by the error is where rails is rendering the view ( <%= yield %>).
If I remove all the "strange" characters from the view, it works fine. 
The worst part comes now: if I bind the NGINX server to Puma running through rails s puma everything works fine. Can you please help me to solve this?

puma.conf
# Change to match your CPU core count
workers 1

# Min and Max threads per worker
threads 1, 6

app_dir = File.expand_path("../..", __FILE__)
shared_dir = "#{app_dir}/shared"

# Default to production
rails_env = ENV['RAILS_ENV'] || "production"
environment rails_env

# Set up socket location
bind "unix://#{shared_dir}/sockets/puma.sock"

# Logging
stdout_redirect "#{shared_dir}/log/puma.stdout.log", "#{shared_dir}/log/puma.stderr.log", true

# Set master PID and state locations
pidfile "#{shared_dir}/pids/puma.pid"
state_path "#{shared_dir}/pids/puma.state"
activate_control_app

on_worker_boot do
  require "active_record"
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[rails_env])
end

etc/nginx/sites-available/default
upstream app {
    # Path to Puma SOCK file, as defined previously
    server unix:/home/user_name/app_name/shared/sockets/puma.sock fail_timeout=0; # this gives the error
    # server localhost:3000; # this works fine
}

server {
    listen 80;
    server_name localhost;

    charset utf-8;

    root /home/user_name/app_name/public;

    try_files $uri/index.html $uri @app;

    location @app {
        proxy_pass http://app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    error_page 500 502 503 504 /500.html;
    client_max_body_size 4G;
    keepalive_timeout 10;
}

Thanks in advance! Let me know if you need more information.

**Comment by evanphx** [comment]
This is normal encoding issues with rails, not puma specific.

**Comment by senott** [comment]
I'm sorry to disagree, but is working fine in production with Unicorn.

**Comment by evanphx** [comment]
Ok, can you provide a backtrace of the error? It looks like it happens at the `yield` site according to your code above so that's why I figured it was  rails encoding issue.

**Comment by senott** [comment]
Ok, give me some time to prepare a virtual machine to make a new deploy changing the server because this is running in production now. Thanks for you time!
