### ISSUE TITLE
support TLS client verification options (verify_mode) in jruby

### ISSUE THREAD

**Issue by joemiller** [puma/puma#832]
It appears that the `verify_mode` settings on the MiniSSL context object only work in C / OpenSSL and not in Jruby. The options have no effect under JRuby.

```
      ctx = Puma::MiniSSL::Context.new
      ctx.keystore = @keystore
      ctx.keystore_pass = @keystore_password.value
      ctx.verify_mode = case @verify_mode
                        when 'peer'
                          Puma::MiniSSL::VERIFY_PEER
                        when 'force_peer'
                          Puma::MiniSSL::VERIFY_PEER | Puma::MiniSSL::VERIFY_FAIL_IF_NO_PEER_CERT
                        when 'none'
                          Puma::MiniSSL::VERIFY_NONE
                        else
                          raise(LogStash::ConfigurationError, "Unrecognized TLS verification mode: #{@verify_mode}. Should be: peer, force_peer, or none.")
                        end
      @server.add_ssl_listener(@host, @port, ctx)
```

It looks like we would need to set this in `ext/puma_http11/org/jruby/puma/MiniSSL.java` `initialize()` method. Using either nothing (current behavior) to emulate `none` mode, `setWantClientAuth()` for `peer` mode and `setNeedClientAuth()` for `force_peer` mode.

https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setNeedClientAuth()

**Comment by joemiller** [comment]
I took a shot at implementing this here:  https://github.com/puma/puma/pull/833

**Comment by evanphx** [comment]
Fixed!

**Comment by frankwong15** [comment]
This is breaking puma when using binder dsl because there is no way to set verify_mode.
