### ISSUE TITLE
Config hook execution order doesn't seem to match examples/config.rb

### ISSUE THREAD

**Issue by maxkwallace** [puma/puma#840]
I'm trying to gain a better understanding of how Puma works. I'm running Puma in cluster mode, with `preload_app!`, and my `config/puma.rb` looks like:

```
...

on_worker_boot do
  puts "on_worker_boot for pid #{Process.pid}"
end

before_fork do
  puts "before_fork for pid #{Process.pid}"
end

after_worker_boot do
  puts "after_worker_boot for pid #{Process.pid}"
end
```

When I start Puma, I see:
```
before_fork for pid 17069
after_worker_boot for pid 17069
after_worker_boot for pid 17069
on_worker_boot for pid 17082
on_worker_boot for pid 17085
[17069] - Worker 0 (pid: 17082) booted, phase: 0
[17069] - Worker 1 (pid: 17085) booted, phase: 0
```

This doesn't match my expectations based on reading `examples/config.rb`. To paraphrase from the file, `on_worker_boot` is for 

> ... when a worker boots to setup the process before booting the app.

and `after_worker_boot` is for 

> ...when a worker boots to setup the process after booting the app.

Based on that documentation, I would expect the `after_worker_boot` hook to run in each worker process, after the `on_worker_boot` hook. But this doesn't match what I see in my console-- the `after_worker_boot` hook is being run first, and only in the parent process.

What's the source of this misunderstanding?

**Comment by tpodom** [comment]
Looking at the source I think this is an error in documentation and naming. The underlying code registers an ```after_worker_fork``` callback which parallels ```before_worker_fork``` and it appears both of those callback happen in the master process.  It does not look like there is any support for the documented ```after_worker_boot```.  I'm currently looking to see if there's any workaround because I'm trying to register Bunny consumers after Rails has loaded.

**Comment by maxkwallace** [comment]
@tpodom Thanks for the reply!

**Comment by tpodom** [comment]
@evanphx I saw this was closed but I'm not sure why.  It seems like either <code>after_worker_boot</code> should be renamed to <code>after_worker_fork</code>, or it's documentation should be updated to make it clear that it's after a worker is forked in the master process, or it should be updated to work as described.

**Comment by evanphx** [comment]
Well, I can't rename those now because that would break peoples config files. The docs just need to be be clear that it happens in the master, i'll do that.

**Comment by evanphx** [comment]
I fixed the name, because it was confusing, leaving an alias for the old name.

**Comment by tpodom** [comment]
@evanphx thanks, that will be much more clear going forward

**Comment by maxkwallace** [comment]
@evanphx Thanks! The updated documentation is super helpful. I noticed two tiny inconsistencies so I sent over a PR: https://github.com/puma/puma/pull/956
