### ISSUE TITLE
Unresponsive socket after x time

### ISSUE THREAD

**Issue by niels-s** [puma/puma#841]
Hello guys and girls,

I've experiencing unresponsive in my Puma socket after x time. Up to this point I don't have a clue what's causing the issue. Hopefully somebody over here can help we with some answers. I'm having the following scenario;

I'm use the official docker `ruby-2.2.3-slim` image together with the latest puma release 2.15.3. I'm also using Nginx as a reverse proxy but I skipped Nginx and tried to verify if the socket was working using this [script] (https://gist.github.com/niels-s/f2c1fff209193fcaf769) But it wasn't I also got a time out over there.

This is a staging environment so the server isn't experiencing any extreme load, I've also check memory consumption it has still several GB of free space so that couldn't be the issue either.

Also I couldn't find anything in the logs of puma, over here are my puma setup:
```ruby
threads 0, 16

app_dir = ENV.fetch('APP_HOME')
environment ENV['RAILS_ENV']

daemonize

bind "unix://#{app_dir}/sockets/puma.sock"
stdout_redirect "#{app_dir}/log/puma.stdout.log", "#{app_dir}/log/puma.stderr.log", true

pidfile "#{app_dir}/pids/puma.pid"
state_path "#{app_dir}/pids/puma.state"
activate_control_app

on_worker_boot do
  require 'active_record'
  ActiveRecord::Base.connection.disconnect! rescue ActiveRecord::ConnectionNotEstablished
  ActiveRecord::Base.establish_connection(YAML.load_file("#{app_dir}/config/database.yml")[ENV['RAILS_ENV']])
end
```

And this it the output in my puma state file:
```yaml
---
pid: 43
config: !ruby/object:Puma::Configuration
  cli_options:
  conf:
  options:
    :min_threads: 0
    :max_threads: 16
    :quiet: false
    :debug: false
    :binds:
    - unix:///APP/sockets/puma.sock
    :workers: 1
    :daemon: true
    :mode: :http
    :before_fork: []
    :worker_timeout: 60
    :worker_boot_timeout: 60
    :worker_shutdown_timeout: 30
    :environment: staging
    :redirect_stdout: "/APP/log/puma.stdout.log"
    :redirect_stderr: "/APP/log/puma.stderr.log"
    :redirect_append: true
    :pidfile: "/APP/pids/puma.pid"
    :state: "/APP/pids/puma.state"
    :control_url: unix:///tmp/puma-status-1449260516541-37
    :config_file: config/puma.rb
    :control_url_temp: "/tmp/puma-status-1449260516541-37"
    :control_auth_token: cda8879717be7a645ea323d931b88d4b
    :tag: APP
```

The app itself is running rails 4.2.5, besides that is deployed on GCE (Google Container Engine). 

If somebody good give me some pointer how to debug this any further would be very much appreciated. Because now I don't see any output any where which could help me further.

**Comment by niels-s** [comment]
I finally found out why my application was behaving the way it was. After trying to use a tcp connection and switching to Unicorn I start looking into other possible sources.

That's when I thought maybe my connection to Google Cloud SQL could be the problem. Once I read the faq of [Cloud SQL](https://cloud.google.com/sql/docs/diagnose-issues), they mentioned that you have to tweak you Compute instances to ensure they keep open your DB connection. So I performed the next steps they recommend and that solved the problem for me, I added them just in case:

    # Display the current tcp_keepalive_time value.
    $ cat /proc/sys/net/ipv4/tcp_keepalive_time
    
    # Set tcp_keepalive_time to 60 seconds and make it permanent across reboots.
    $ echo 'net.ipv4.tcp_keepalive_time = 60' | sudo tee -a /etc/sysctl.conf
    
    # Apply the change.
    $ sudo /sbin/sysctl --load=/etc/sysctl.conf
    
    # Display the tcp_keepalive_time value to verify the change was applied.
    $ cat /proc/sys/net/ipv4/tcp_keepalive_time

sorry for the misunderstanding

**Comment by rilian** [comment]
thank you!
