### ISSUE TITLE
Chunked Endcoding over SSL results in NullIO body

### ISSUE THREAD

**Issue by NZGlitch** [puma/puma#844]
When using cordova-plugin-file-transfer on android with chunked encoding over SSL to rails app using Puma 2.14.0 running on heroku, the body seems to be dropped.

Issue, logs and extra information reported here: http://stackoverflow.com/questions/33533618/cordova-app-on-android-using-ssl-sending-multipart-form-data-causes-rack-app-err

Please Note: Issue does not occur if chunked encoding is not used OR if not using SSL, OR if I use Unicorn instead of Puma.

**Comment by tawan** [comment]
This seems to be the same issue as reported in #620 . @NZGlitch can you confirm?

**Comment by evanphx** [comment]
Yes, thats probably it. Currently puma doesn't support chunked request bodies. I'm going to prioritize adding support for them and you can follow in #620
