### ISSUE TITLE
X_FORWARDED_PROTO

### ISSUE THREAD

**Issue by rvfx** [puma/puma#851]
I have an Apache -> Puma -> Rails setup and tell Puma about HTTPS connections by setting the `X_FORWARDED_PROTO` header field in my `.htaccess`:
```
RequestHeader set X_FORWARDED_PROTO 'https' env=https
RequestHeader set X_FORWARDED_PROTO 'http' env=!https
```

Since Puma's version 2.15 this doesn't seem to work anymore. Is there a way to restore this functionality or should it still work with the newer versions?

**Comment by evanphx** [comment]
What about it doesn't work?

**Comment by mwpastore** [comment]
Something simple to try:

```apacheconf
RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
RequestHeader set X-Forwarded-Proto 'http' env=!HTTPS
```

I also found [this](http://serverfault.com/questions/257616/requestheader-with-apache-environment-variable) StackOverflow question that suggests you may need to add `early` to the end of those lines. Try it with and without.
