### ISSUE TITLE
Rack::Handler::Puma versus Puma::CLI default behavior

### ISSUE THREAD

**Issue by schneems** [puma/puma#855]
Right now if you have a `config/puma.rb` file in your application and you run `$ puma` it will detect the file, use it for configuration. The same is not true if puma is booted using only `Rack::Handler::Puma`. 

Recently Rails switched over to specifying puma as the default webserver, this is generally good but we need to configure it to run with fewer threads by default. ActiveRecord connection pool uses 5 threads and we want puma to match, otherwise if you run with more threads than connections you get connection timeouts since connections are checked out for the duration of each request. One idea was to have a default `config/puma.rb` file in the project that could specify using a max of 5 threads. This would work if the project is being run with `$ puma` but will not work with `$ rails server` which relies on Rack::Server to call Rack::Handler::Puma.

I'm interested in getting the handler behavior to match the CLI behavior and respect a config file when found. Do you have any concerns or thoughts on getting the handler behavior to match the CLI default behavior?

**Comment by evanphx** [comment]
I'm definitely open to making `Rack::Handler::Puma` pick up the config file. The reason it didn't was that originally I thought that the point of the rack handlers was quick (dev style) work and thus you wouldn't need a config file.

The number of threads could also be controlled by an environment variable that rails can set before invoking the Rack handler, so you don't need the config file. Basically, I'm happy to add whatever is needed to pass the values from rails into puma in the context of it's Rack handler.

**Comment by schneems** [comment]
:rocket: :boom: i poked around a bit and i'm going to either need to expose some functionality in Puma::CLI (currently private methods) or move some things around to make them accessible by multiple things. I'll play around some more and see what I come up with. Thanks for the feedback. cc/ @pixeltrix

**Comment by evanphx** [comment]
I don't mean to add more work to this request, but this might be a good place to begin a new Puma::Embedded class that can be used to configure puma within a process. Right now it's a mess and I've been meaning to clean that up for ages.

**Comment by schneems** [comment]
What did you have in mind with Puma::Embedded class? A good amount of the config does stuff on boot, instead of dynamically. I think there's a few places that we could change on the fly such as worker count as there is a reactor that constantly looks to see if we have more or less workers than needed. Other changes would either require code changes or a restart. Would you want to restrict to the values that make sense to set today or default to restarting the server on any config change or what? I could see using something like this in Puma worker killer or similar. 

I want to pull all the server starting business out of CLI into it's own class. `Runner` was already taken, so i'm thinking `Launcher`. That way CLI is still responsible for parsing input and orchestrating a launched process, but now we can re-use the server starting portion inside of Rack::Puma.

**Comment by evanphx** [comment]
This has been done for 3.0!
