### ISSUE TITLE
Should puma be able to start with max_threads = 0

### ISSUE THREAD

**Issue by errm** [puma/puma#866]
I have just finished debugging a production issue where we *stupidly* set max threads to 0.
Puma starts up somewhat normally, but nothing works . . .

Should this configuration cause puma to exit early or at least emit a warning?

**Comment by evanphx** [comment]
That would mean it has no ability to run requests. Why would you want that?

**Comment by errm** [comment]
I wouldn't want that . . . thats the point I would like this useless configuration to at least say:

"Warning: This configuration of max_threads leaves puma without the ability to serve requests"

or to exit with a similar message.

I just stayed up all night trying to work out why the puma process that looked like it was running fine, without any errors in the logs was not accepting any connections.  So its a silly thing really, but 3am me would love some sort of explicit warning why that was happening.

I can open a PR if you think its a good idea @evanphx

**Comment by evanphx** [comment]
AAAH! I misunderstood. Yes, it should error out if max_threads equal to or
less than 0.

**Comment by errm** [comment]
What do you prefer a warning or an exit

**Comment by evanphx** [comment]
Probably an exit
