### ISSUE TITLE
what happened when i Using http get within Rails to hit Rails

### ISSUE THREAD

**Issue by lanjingyu** [puma/puma#869]
Yes, this is a puma question.
```ruby
class WelcomeController < ApplicationController

  def demo
  end

  def hello
    url_str = 'http://127.0.0.1:9292/welcome/demo'
    url = URI.parse(url_str)
    req = Net::HTTP::Get.new(url.to_s, { 'User-Agent' => 'Mozilla/5.0 (etc...)' })
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
    @response = res.body
  end
end
```
The hello action  get the demo action.(the demo action is just some text page.). It will crush.
It is not the code problem, but the server problem.

And i got the answer like this:
=====
It doesn't work because you are not using a multi-threaded server. Your request is coming in and blocking the server until it's complete. During that time, you're making a request to your localhost that isn't being handled.

Easy solution? Try puma. Other easy solution, spin up two rails instances, connect to the 2nd instance.
Come from here:http://stackoverflow.com/questions/16970242/using-nethttp-within-rails-to-hit-rails
------
So I change to puma, but the same thing. 

It died too, crush.

What should i do.

**Comment by micfan** [comment]
* The best way is [redirect_to](http://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_to)
*  Read docs: http://guides.rubyonrails.org/action_controller_overview.html#flash-now
