### ISSUE TITLE
Puma not displaying actionmailer previews

### ISSUE THREAD

**Issue by obromios** [puma/puma#870]
I asked this [question](http://stackoverflow.com/questions/35053483/puma-not-working-with-actionmailer-preview-in-development-mode)  on stackoverflow and received no response, so perhaps it is an issue with puma.

  When using the puma server, then  /rails/mailers on Chrome displays  'This webpage is not available'.  If I run webrick instead i.e.
`
    rails server webrick`
then my mailer previews page is displayed.

I am running ```rails 4.2.5.1``` and ```puma 2.16.0```.  The relevant configurations in my ```development.rb``` file are

  [    config.action_mailer.default_url_options = {
        host: 'localhost',
        port: 3000, protocol: 'http' }
      config.action_mailer.smtp_settings = { address: 'localhost', port: 1025 }
      config.action_mailer.preview_path = "#{Rails.root}/mailers_previews/"
](url)
I have been using puma in development and production on heroku for several months and everything else works.  How do I get puma to display the previews?

**Comment by TheKidCoder** [comment]
What is the URL of the preview when you open it in chrome? This might be a interface binding issue.

**Comment by obromios** [comment]
Very good question.  It turns out that I was using an old url
`http://0.0.0:3000/rails/mailers`
when I should have been using
`http://localhost:3000/rails/mailers`

The later works fine. Thank you for your help.
