### ISSUE TITLE
Puma Not Picking Up New Deploys on Phased Restarts

### ISSUE THREAD

**Issue by todd** [puma/puma#878]
We recently updated Puma to 2.16.0 and our phased restarts are now failing to pick up our new deploys. We're running Ruby 2.3.0, the latest Rails 4.1/4.2 releases, and deploying with Capistrano.

```
[28889] - Starting phased worker restart, phase: 4
[28889] - Stopping 32630 for phased upgrade...
[28889] - TERM sent to 32630...
[32752] + Gemfile in context: /path/to/our/app/releases/20160202205923/Gemfile
[28889] - Worker 0 (pid: 32752) booted, phase: 4
```

```
$ ls -al /path/to/our/app/
total 24
[redacted] 4096 Feb  4 18:02 .
[redacted] 4096 Jan 12 18:25 ..
[redacted]   46 Feb  4 18:02 current -> /path/to/our/app/releases/20160204180200
[redacted] 4096 Feb  4 18:02 releases
[redacted] 4096 Jan 12 18:29 repo
[redacted] 3857 Feb  4 18:02 revisions.log
[redacted] 4096 Jan 12 18:29 shared
```

Addendum: We're using `prune_bundler true` in our Puma config.

**Comment by TheKidCoder** [comment]
This looks like an issue with capistrano / your env config. 

When puma gets the signal to restart, it is still using the old release path. `releases/20160202205923/Gemfile`

Your new path is: `/releases/20160204180200`

Puma is restarting with the old app code in its working directory.

**Comment by todd** [comment]
Right - that's the issue. After we upgraded to 2.16.0, Puma stopped picking up the new release directory Capistrano symlinks to `/path/to/app/current`. This was all working as expected previously.

**Comment by todd** [comment]
It's worth pointing out that we were using Puma 2.12 previously. Rolling back to 2.15 exhibits the same unexpected behavior. We've rolled back to 2.14 for now as that version doesn't seem to be affected.

**Comment by todd** [comment]
I managed to track down the relevant commit, PR, and #770 where this behavior was discussed and changed. I can verify that using the `directory` DSL method fixed this problem for us. Moving forward, is the plan only to support setting the release directory with this method or should the CLI option be preserved?

**Comment by evanphx** [comment]
@todd Oh geez. So sorry for the confusion. I completely forgot about #770 about the need for `directory` because of how the current path is otherwise derived.

You have to use `directory "path/to/release"` because puma can't resolve it properly due to how links and `getwd` work.

Which CLI option do you mean?

I need to add this to the docs so I don't forget to tell people about it in the future.

**Comment by todd** [comment]
@evanphx Oops, misremembered about setting it via the CLI. Ignore me on that front. I can take a stab at updating the docs if you'd like.

**Comment by evanphx** [comment]
@todd That would be wonderful!

**Comment by todd** [comment]
Will do. I'm going to close this issue.

**Comment by robdimarco** [comment]
After upgrading from 2.16.0 to 3.0.2, I am seeing this behavior again. We do have the `directory` set in the puma config file as per the instructions to #770

**Comment by robdimarco** [comment]
I figure out how to work around our problem. We are using upstart and I had in there a

    chdir /mnt/deploy/app/current

To get the reload to work correctly, I had to explicitly set and export the present working directory env variable with

    env PWD=/mnt/deploy/app/current
    export PWD

Apparently upstart does not set the PWD when you use, which I learned reading #539

**Comment by allaire** [comment]
started seeing this al well by upgrading to 3.0.2, was also to 2.16. 0 @robdimarco @evanphx, here's my config:

```
threads 1, 2
workers 2
pidfile "tmp/pids/puma.pid"
state_path "tmp/pids/puma.state"
bind "unix://tmp/sockets/puma.sock"
directory "/home/user/apps/project/current"
prune_bundler true```

**Comment by robdimarco** [comment]
@allaire one other thing. I had to `stop` and `start` via upstart. When I just did a `restart` of the process, it did not pick up my change. Maybe that is it.

**Comment by allaire** [comment]
The weird thing is with `3.x`, I see in the log `Changing to /home/user/apps/app/releases/20160319210637` where with `2.x` I see `Changing to /home/user/apps/app/current`.

Something really changed internally, and by looking at the code, I can't see where the `worker_directory` is different in `3.x`

**Comment by evanphx** [comment]
@allaire strangely I can't replicate that behavior with `3.1.1`:

```shell
veritas :: proj/current> bundle exec puma -C puma.rb
[23132] Puma starting in cluster mode...
[23132] * Version 3.1.1 (ruby 2.3.0-p0), codename: El Niño Winter Wonderland
[23132] * Min threads: 0, max threads: 16
[23132] * Environment: development
[23132] * Process workers: 2
[23132] * Phased restart available
[23132] * Listening on tcp://0.0.0.0:9292
[23132] Use Ctrl-C to stop
[23132] - Worker 0 (pid: 23145) booted, phase: 0
[23132] - Worker 1 (pid: 23146) booted, phase: 0
[23132] - Starting phased worker restart, phase: 1
[23132] + Changing to /Users/evan/git/puma/tmp/proj/current
[23132] - Stopping 23145 for phased upgrade...
[23132] - TERM sent to 23145...
[23132] - Worker 0 (pid: 23149) booted, phase: 1
[23132] - Stopping 23146 for phased upgrade...
[23132] - TERM sent to 23146...
[23132] - Worker 1 (pid: 23150) booted, phase: 1
```

**Comment by evanphx** [comment]
@allaire Is puma starting via a normal shell or via upstart/systemd?

**Comment by allaire** [comment]
Via upstart

**Comment by evanphx** [comment]
@allaire Could you paste in your upstart config file? Or at least show how you're invoking puma?

**Comment by allaire** [comment]
@evanphx sure, here is the cap file: https://github.com/agendrix/capistrano-foundation/blob/master/lib/capistrano/tasks/puma.rake

Here's the upstart script:

```
start on starting app-web
stop on stopping app-web
respawn

# Custom to App
# http://sorentwo.com/2014/12/08/self-healing-deployment.html
respawn limit 3 30
reload signal USR1
normal exit 0 TERM

env PORT=5000
env PATH='/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/plugins/ruby_build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games'
env LANG='en_CA.UTF-8'
env RAILS_ENV='staging'
env RACK_ENV='staging'
...

setuid app

chdir /home/user/apps/app/current

exec bundle exec puma
```

**Comment by evanphx** [comment]
Ok, I've figured out the issue. I'll have a new version out this evening to fix it.

**Comment by allaire** [comment]
Nice! Make sure to let me know what is it, curious :)

**Comment by evanphx** [comment]
Ok, 3.2.0 is out now and it fixes this issue. Sorry for breaking this in 3.0 :cry:

**Comment by allaire** [comment]
Thanks evan! What's the related commit?

Is the phased restart testable?

**Comment by evanphx** [comment]
Here is the commit: https://github.com/puma/puma/commit/8b05d0a76374019a815c7889f147e7c0aa561532

It's testable, but not well tested automated right now. If you want to spend a little time on writing those tests, I'd be happy to merge them.
