### ISSUE TITLE
Logging stops after a while 

### ISSUE THREAD

**Issue by grepruby** [puma/puma#880]
Hi 

I am using puma on production. After a while, logging does stop. It doesn't write anything in log file. Issue is random but I know it has something to do with puma.  

I hope I dont have to remind how important logs are for any live application. Aren't puma is production candidate ?

Please advice.

**Comment by YuriSolovyov** [comment]
does app itself continue running? I guess rack env is set to production?

**Comment by codehotter** [comment]
Are you using Rails.logger.silence? This became thread-safe in rails only very recently (4.2.6), and if you're using an older version, a race condition can permanently set the log level to ERROR in your application, even if you've configured it higher. Are errors still logged?

**Comment by mwpastore** [comment]
I just ran into this. Puma stops writing to the logs after they're rotated. The solution is to sighup the top-level Puma process after logrotate does its thing. This tells Puma to close and reopen the log files.

I'm running Puma through Upstart, so I modified my puma config.rb to write out a pid file, and added these lines to /etc/logrotate.d/upstart:

```
        sharedscripts # only run the postrotate script once
        postrotate
                /bin/kill -HUP `cat /srv/rack/example.com/puma.pid 2>/dev/null` 2>/dev/null
        endscript
```

Your solution may not be exactly identical but hopefully this gives you a place to work from.

**Comment by evanphx** [comment]
That's correct, if you move the log files, you need to tell puma so.

**Comment by grepruby** [comment]
I am having same problem with production log with puma. However I am not using upstart instead I am using god script to start/stop puma. Also we are not rotating log of god/puma , so not sure in our case what is causing issue. 

My sidekiq workers keep writing in log file, regardless what puma does. So clear it has something with puma. 

Please advice.

**Comment by mwpastore** [comment]
@grepruby:

1. What operating system?
2. How did you install God? `gem install` or yum or apt or something, e.g. `apt-get install ruby-god`?
3. Are you redirecting stderr and stdout through puma (e.g. `puma --redirect-stdout ..`) or through god (e.g. `w.log_cmd = ..`)?

**Comment by grepruby** [comment]
@evanphx 
1 Ubuntu 14
2 Installed God through  gem. I am using rvm to manage ruby.
3 No. Not redirecting stderr or stdout

My God script looks like below
```

RAILS_ROOT='/var/www/apps/wl-event/current'
SHARED_ROOT='/var/www/apps/wl-event/shared'
STATE = "#{SHARED_ROOT}/log/puma.state"
SOCK = "unix://#{SHARED_ROOT}/tmp/puma.sock"
PID = "#{SHARED_ROOT}/tmp/puma.pid"

God.watch do |w|
  w.name = 'wl-event'
  w.dir = "#{RAILS_ROOT}"
  w.log = "#{SHARED_ROOT}/log/god.log"
  w.pid_file = File.join(SHARED_ROOT, "/tmp/puma.pid")
  w.start = "cd #{RAILS_ROOT}; bundle exec puma -b #{SOCK} -C #{RAILS_ROOT}/config/puma.rb --pidfile #{PID}"
  w.stop = "cd #{RAILS_ROOT}; bundle exec pumactl -p `cat #{w.pid_file}` stop"

  w.behavior(:clean_pid_file)
  w.start_if do |start|
    start.condition(:process_running) do |c|
      c.interval = 5.seconds
      c.running = false
    end
  end
  w.keepalive
end

```

**Comment by rishijain** [comment]
Hopefully its still not an an issue since its been 2 years now. But posting a possible solution for anyone else who stumbles to this problem.

If after restarting the puma server, it starts to print the logs. You most likely are missing the `copytruncate` option in the config. It would basically make a copy of the log file, truncate the existing log file.

You can read more about it here: http://excid3.com/blog/logrotate-rails-production-logs  and https://www.systutorials.com/docs/linux/man/5-logrotate.conf/
