### ISSUE TITLE
Puma Cluster Workers at 100% cpu

### ISSUE THREAD

**Issue by deha23** [puma/puma#881]
My 4 Cluster Workers go to 100%. The main process is ok. At the moment i do not have an idea how to handle that. Any ideas?

**Comment by evanphx** [comment]
Is there any log output? Do they respond to requests?

**Comment by deha23** [comment]
I checked the puma_access and the puma_error log, but there is nothing special in it.
What I see is that the app is very slow. Sometimes o requests lasts about 100 sec. When I kill the worker processes everything works fine until they come up again.

**Comment by evanphx** [comment]
Sounds like your app is just working at max capacity?

**Comment by codebymikey** [comment]
This can also happen when one of your files have a syntax error. 

Always check your `puma.stderr.log` file.
