### ISSUE TITLE
CLOSE_WAIT Process Blocked

### ISSUE THREAD

**Issue by simonmorley** [puma/puma#882]
We've been having a long-running issue with puma (2.16.0) hanging. Running netstat reveals a few hundred connections 'stuck' in CLOSE_WAIT

```
tcp      954      0 localhost:5100          localhost:42053         CLOSE_WAIT
tcp      121      0 localhost:5100          localhost:38524         CLOSE_WAIT
tcp      119      0 localhost:5100          localhost:38203         CLOSE_WAIT
tcp      121      0 localhost:5100          localhost:34869         CLOSE_WAIT
tcp     1124      0 localhost:5100          localhost:42139         CLOSE_WAIT
```

We're running puma behind an nginx proxy which is behind haproxy.

While this is happening, the servers are 100% unresponsive. Over the last 6 weeks, we've been through our entire application - removing unwanted gems and bloat. We've upgraded / rebooted our databases.

Initially I thought it was an issue with the AMQP gem but have since replaced that with Bunny. 

We've checked our kernel limits, increased the ram significantly. Tweaked the number of workers and threads puma is using. Right now, we're looking like this:

```
bind "tcp://0.0.0.0:5100"
environment "production"
threads 4,16
preload_app!
```

We're running this in Docker but have also run on a vm directly - same issue. 

As per other requests, it's impossible to kill the process without using -9.

If I use GDB to debug the stuck process (running call rb_backtrace() a few times), there's little to be seen (I'm sure I'm not using it right).

```
{"log":"10:29:52 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `block in start!'\n","stream":"stdout","time":"2016-02-08T10:29:52.362721857Z"}
{"log":"10:29:52 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `sleep'\n","stream":"stdout","time":"2016-02-08T10:29:52.362990388Z"}
{"log":"10:31:16 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `block in start!'\n","stream":"stdout","time":"2016-02-08T10:31:16.670685736Z"}
{"log":"10:31:16 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `sleep'\n","stream":"stdout","time":"2016-02-08T10:31:16.674043322Z"}
{"log":"10:33:05 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `block in start!'\n","stream":"stdout","time":"2016-02-08T10:33:05.271826453Z"}
{"log":"10:33:05 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `sleep'\n","stream":"stdout","time":"2016-02-08T10:33:05.272072828Z"}
{"log":"10:33:39 web.1   | \u0009from /usr/local/bundle/gems/mongo-2.2.2/lib/mongo/server/monitor.rb:116:in `block in run!'\n","stream":"stdout","time":"2016-02-08T10:33:39.388642039Z"}
{"log":"10:33:39 web.1   | \u0009from /usr/local/bundle/gems/mongo-2.2.2/lib/mongo/server/monitor.rb:116:in `loop'\n","stream":"stdout","time":"2016-02-08T10:33:39.388768644Z"}
{"log":"10:33:39 web.1   | \u0009from /usr/local/bundle/gems/mongo-2.2.2/lib/mongo/server/monitor.rb:117:in `block (2 levels) in run!'\n","stream":"stdout","time":"2016-02-08T10:33:39.388987701Z"}
{"log":"10:33:39 web.1   | \u0009from /usr/local/bundle/gems/mongo-2.2.2/lib/mongo/server/monitor.rb:117:in `sleep'\n","stream":"stdout","time":"2016-02-08T10:33:39.389101396Z"}
{"log":"10:33:47 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/server.rb:296:in `block in run'\n","stream":"stdout","time":"2016-02-08T10:33:47.242523705Z"}
{"log":"10:33:47 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/server.rb:322:in `handle_servers'\n","stream":"stdout","time":"2016-02-08T10:33:47.242778064Z"}
{"log":"10:33:47 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/server.rb:322:in `select'\n","stream":"stdout","time":"2016-02-08T10:33:47.243587653Z"}
{"log":"10:33:50 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `block in start!'\n","stream":"stdout","time":"2016-02-08T10:33:50.522572519Z"}
{"log":"10:33:50 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `sleep'\n","stream":"stdout","time":"2016-02-08T10:33:50.523380208Z"}
{"log":"10:33:56 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `block in start!'\n","stream":"stdout","time":"2016-02-08T10:33:56.702466347Z"}
{"log":"10:33:56 web.1   | \u0009from /usr/local/bundle/gems/puma-2.16.0/lib/puma/thread_pool.rb:219:in `sleep'\n","stream":"stdout","time":"2016-02-08T10:33:56.702582335Z"}
```

We've figured the issue is within our code and not Puma but still can't see anything wrong our side. We've been using Haproxy's rules to redirect individual routes to a specific set of servers for debugging purposes. So far, we've found one particular end-point that looks like the culprit but haven't found anything in the code that's problematic - Newrelic hasn't really given any nice hints either.

Can someone recommend a way to debug this stuck process further?

**Comment by ianks** [comment]
Can you print out a backtrace of all the threads on this process?

`Thread.list.map(&:backtrace)`

**Comment by simonmorley** [comment]
Of course, sods law dictates the issue stops happening as soon I raise an issue after months of troubleshooting.

Thanks for the command, I wasn't aware that could be run. Will do so again when it blocks.

Yesterday by chance I installed the rack timeout gem which started throwing connection timeout errors all over the shop - in particular with bunny + connection pool.

I've now re-replaced bunny with AMQP and things are better but not perfect. We're working through the other timeouts now.

It feels a bit misplaced to have put this here since it's clearly not a direct issue with puma. However, it's the puma process that's blocking. It's just been hard to diagnose the issue.

Will try with Thread.list and report back.

**Comment by simonmorley** [comment]
The following is from a running server with approx 800 CLOSE_WAIT connections 'stuck' as above. 

```
 [["(irb):1:in `backtrace'", "(irb):1:in `map'", "(irb):1:in `irb_binding'", "/usr/local/lib/ruby/2.2.0/irb/workspace.rb:86:in `eval'", "/usr/local/lib/ruby/2.2.0/irb/workspace.rb:86:in `evaluate'", "/usr/local/lib/ruby/2.2.0/irb/context.rb:379:in `evaluate'", "/usr/local/lib/ruby/2.2.0/irb.rb:489:in `block (2 levels) in eval_input'", "/usr/local/lib/ruby/2.2.0/irb.rb:623:in `signal_status'", "/usr/local/lib/ruby/2.2.0/irb.rb:486:in `block in eval_input'", "/usr/local/lib/ruby/2.2.0/irb/ruby-lex.rb:245:in `block (2 levels) in each_top_level_statement'", "/usr/local/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `loop'", "/usr/local/lib/ruby/2.2.0/irb/ruby-lex.rb:231:in `block in each_top_level_statement'", "/usr/local/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `catch'", "/usr/local/lib/ruby/2.2.0/irb/ruby-lex.rb:230:in `each_top_level_statement'", "/usr/local/lib/ruby/2.2.0/irb.rb:485:in `eval_input'", "/usr/local/lib/ruby/2.2.0/irb.rb:395:in `block in start'", "/usr/local/lib/ruby/2.2.0/irb.rb:394:in `catch'", "/usr/local/lib/ruby/2.2.0/irb.rb:394:in `start'", "/usr/local/bundle/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'", "/usr/local/bundle/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'", "/usr/local/bundle/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'", "/usr/local/bundle/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'", "/usr/local/bundle/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'", "bin/rails:8:in `require'", "bin/rails:8:in `<main>'"], ["/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'", "/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'", "/usr/local/bundle/gems/amqp-1.5.0/lib/amqp.rb:56:in `start'", "/myapp/config/initializers/amqp.rb:29:in `block in <top (required)>'"]]
```

Again it looks like amqp is blocking *everything*. Line 29 refers to this:

```
Thread.new {
  AMQP.start(connection_options.merge ssl_options) do |connection, open_ok|
```

I'd previously swapped from AMQP and eventmachine to bunny but swapped back when we experienced timeouts there.

I'm happy to move this elsewhere since puma blocking seems to be the symptom not the cause of this. Any advice appreciated however.

**Comment by simonmorley** [comment]
The root cause of this appears to be rabbitmq. 

I've been slowly working through end end-point, moving them to a separate set of pods. I've finally found the one (our second busiest) that's seemingly causing the issue.

It would appear that the connection to rabbit times out, even though I'm not seeing any errors on the rabbit servers. I thought rack timeout would kill the connections but maybe it's just leaving them in a state.

After a few minutes, puma blocks with all the connections in CLOSE_WAIT state.

Like I said, puma has taken the blame for something else.

**Comment by evanphx** [comment]
@simonmorley Thanks for tracking it down! Good for future users to look out for as well.

**Comment by madsheep** [comment]
@simonmorley sorry for pinging you over an old issue - did you happen to identify the issue you had with rabbitmq? We have the exact same stack (puma / rabbitmq) and the exact same problem (CLOSE_WAIT connections).

**Comment by aotenko** [comment]
Did you know there is a Ruby issue handling CLOSE_WAIT sockets?

1. start a connection (plain TCPSocket.new(...))
2. now restart the other end
3. wait for 60 seconds
4. now write to the connection from step 1.

You will see Ruby never throws, and netstat -nap shows send queue growing for a CLOSE_WAIT socket.

I can reproduce this always, ruby 2.2.0 for Ubuntu, at least for localhost connections.

**Comment by hamzaaltaf** [comment]
Anyone found solution for this problem? I am facing the same issue with PUMA.  I am using PUMA 4.3 with ruby 2.4.2 and rails 4.2.8.
server doesn't respond after 15-20 or 1 hour idle time. When I see the ruby processes, a lot of ruby process have CLOSE_WAIT in front of them. I have been trying to solve this issue for 4 days now . Please help me out.

**Comment by donalod** [comment]
I've been having similar issues (freezing) but different... it seems to be with HTTP2 and puma... puma seems to hold open connections in a CLOSE_WAIT state and then hits the default max in NGINX of 128 and stops responding... (this is with upstream via IP not unix socket and puma bound to 127.0.0.1). By ensuring proxy_http_version 1.1; in NGINX location for the proxy it seems to allow PUMA to clean up after itself better... is this just me? Am running nginx/1.19.9 on v4 and v6 as a reverse proxy and as per the Gemfile Puma version: 5.2.2 (ruby 3.0.0-p0).

**Comment by dentarg** [comment]
@donalod Feel free to create a new issue describing how to reproduce the problem, if you think there's an issue with Puma

**Comment by dentarg** [comment]
Is it happening because the default of [`proxy_http_version`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version) is 1.0?

I'm also using Nginx (I haven't set `proxy_http_version`), HTTP/2 and Puma 5.2.2 (Ruby 2.6.6 though) but I have Heroku between Nginx and Puma and they have special handling for HTTP/1.0: https://devcenter.heroku.com/articles/http-routing#http-versions-supported

---

Some more links I looked at while trying to understand the problem @donalod reported. Dumping for future-self and possibly others that are interested:

* https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Protocol_operation
* https://www.w3.org/Protocols/HTTP/1.0/HTTPPerformance.html
* https://blog.cloudflare.com/this-is-strictly-a-violation-of-the-tcp-specification/
* https://benohead.com/blog/2013/07/21/tcp-about-fin_wait_2-time_wait-and-close_wait/
* https://stackoverflow.com/questions/17437950/when-does-an-http-1-0-server-close-the-connection
* https://serverfault.com/questions/421727/nginx-jetty-thousands-of-connections-stuck-in-last-ack

**Comment by donalod** [comment]
> @donalod Feel free to create a new issue describing how to reproduce the problem, if you think there's an issue with Puma

@dentarg Will do thanks, trying to repro and currently failing after a reboot of all things...!! Will post a new issue with better data if it surfaces again, thank you. The Cloudflare link would seem to suggest it was NGINX and not Puma from my reading?

**Comment by donalod** [comment]
> Is it happening because the default of [`proxy_http_version`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version) is 1.0?

And just to answer your question, I think it might have been happening due to the default `proxy_http_version` of 1.0 hence it seemed to subside with `proxy_http_version 1.1`. Am guessing this would also mean an NGINX config rather than Puma issue as such...

**Comment by donalod** [comment]
🤦  Trying to repro... no joy.. will morph back in to the hedge... 
![image](https://user-images.githubusercontent.com/4045949/113891889-668c0e80-97bd-11eb-80ef-6d17e7364bec.png)
