### ISSUE TITLE
Add mongoid connection in on_worker_boot

### ISSUE THREAD

**Issue by SubhashShah-BTC** [puma/puma#889]
My rails application (Ruby 2.3.0, Rails 4.2.5) uses `Mongoid` gem instead of ActiveRecord. I am now in the process of deploying the application on digitalocean. I am wandering how to configure mongoid connection in `on_worker_boot` block in `config/puma.rb` file. I searched for it but couldn't find any references.

**Comment by TheKidCoder** [comment]
If you have an initializer that was created by `rails g mongoid:config` I would imagine you can move whatever is within that initializer into the `on_worker_boot` block. 

If you don't have an initializer, it looks like `Mongoid.load!("path/to/your/mongoid.yml", :production)` inside the `on_worker_boot` block will work.

**Comment by SubhashShah-BTC** [comment]
@TheKidCoder : Thanks for your help.
