### ISSUE TITLE
Upstart script fails to run

### ISSUE THREAD

**Issue by thezed** [puma/puma#898]
I set up Upstart scripts from here: https://github.com/puma/puma/tree/master/tools/jungle/upstart

When I do:
`sudo service puma start /home/deployer/apps/my_app/current`
it fails with message:
`start: Env must be KEY=VALUE pairs`

I am using RVM, Ubuntu 14.04. Googliing is not helping. Please help

**Comment by mwpastore** [comment]
Try:

```sh
sudo service puma start app=/home/deployer/apps/my_app/current
```

or just:

```sh
sudo start puma app=/home/deployer/apps/my_app/current
```

**Comment by thezed** [comment]
@mwpastore, tried them both, gives me this error:
`start: Job failed to start`

**Comment by mwpastore** [comment]
@thezed OK, anything in /var/log/upstart/puma-_home_deployer_apps_my_app_current.log (or similarly-named file)?

**Comment by thezed** [comment]
@mwpastore, I have `/var/log/upstart/puma-manager.log`. Inside of it:

`start: Job failed to start`
`start: Job failed to start`

**Comment by mwpastore** [comment]
You should have a log for your application as well. Did you create an empty
`/etc/puma.conf` file, and did you customize `/etc/init/puma.conf` per the
instructions?

**Comment by thezed** [comment]
@mwpastore, I have /etc/puma.conf and it's filled with paths to my apps. I was using [https://github.com/seuros/capistrano-puma](url) gem and it was generated by it.

In /etc/init/puma.conf I changed `setuid` and `setgid` to deployer. Nothing more I changed in the file.

**Comment by mwpastore** [comment]
In order for me or anyone else to help you, we're going to need more information. 

- What puma-specific settings did you put in your deploy.rb file (for capistrano-puma)?
- Do you have a config/puma.rb file in your app repo?
- Do you have a tmp/puma directory in your app repo, writeable by the deployer/user running puma?
- Did you add pidfile, state_path, and activate_control_app statements to config/puma.rb?
- Can you manually cd to an app and `bundle exec puma`? How are you running it if the upstart script isn't working?
- Are you using rbenv, chruby (with or without auto), rvm, or a system-wide Ruby? Did you modify /etc/puma.conf to reflect any differences cf. your system configuration?

**Comment by magedmakled** [comment]
@thezed, I'm getting the same error, how did you fix it? 
I'm using https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-puma-and-nginx-on-ubuntu-14-04

**Comment by magedmakled** [comment]
@mwpastore when I ran `bundle exec puma` from the app I get
```
[6318] Puma starting in cluster mode...
[6318] * Version 3.2.0 (ruby 2.3.0-p0), codename: Spring Is A Heliocentric Viewpoint
[6318] * Min threads: 1, max threads: 6
[6318] * Environment: production
[6318] * Process workers: 2
[6318] * Phased restart available
[6318] * Listening on unix:///home/deploy/myapp/shared/sockets/puma.sock
[6318] Use Ctrl-C to stop
```

**Comment by thezed** [comment]
@magedmakled I still did not fixed this. 
When I start Puma manually or with capistrano task `cap production puma:start` it runs ok. 
But after server restart upstart script still fails, so I have to run all my apps manually.

**Comment by evanphx** [comment]
@thezed Since this has been ongoing for a while and things have changed, would you resummarize what problem you're seeing?

**Comment by evanphx** [comment]
Due to this issues age, I'm going to go ahead and close it. If this is still an issue, please reopen it.
