### ISSUE TITLE
Memory optimisation since 2.16.0? 

### ISSUE THREAD

**Issue by benoittgt** [puma/puma#903]
Hello

Two weeks ago we jump from puma `2.11.2` to `2.16.0`. Since then we have a lot less memory leak. I was wondering if it could be possible? I'm just curious. 
We updated also other gems but none how seems related to our problem.

I was wondering if https://github.com/puma/puma/pull/702 could have change this ? 

Thanks in advance, also thanks for the last updates we will jump 3.0.0 soon.

**Comment by evanphx** [comment]
Hiya! There have been various fixes that we've hoped would plug some potential leaks folks have seen, so I'll hope you're one of them. Did you change ruby versions also?

**Comment by benoittgt** [comment]
Yep. We switch from ruby-2.2.2  to ruby-2.3.0. I will keep you updated about this in the next two weeks to see if the optimisation is confirmed. 

Thanks !

**Comment by benoittgt** [comment]
@evanphx Seems still good. Thanks !
