### ISSUE TITLE
Undefined method options for nil 

### ISSUE THREAD

**Issue by jeffblake** [puma/puma#906]
Upgraded to Puma 3.0.1 and found this error:

![screen shot 2016-02-26 at 11 22 29 am](https://cloud.githubusercontent.com/assets/620564/13362854/4b83a60a-dc7b-11e5-909b-fc38530d9d79.png)

**Comment by evanphx** [comment]
The state file was never intended to be a portable format used by external tools. I didn't even know about this gem. I'll have to see what they're doing with the state file data...
