### ISSUE TITLE
ENOENT No such file tmp/pids/server.pid during SIGTERM

### ISSUE THREAD

**Issue by jaredbeck** [puma/puma#915]
If I `cat tmp/pids/server/pid` while `rails s` is running, it is present and has the correct number, but when I send SIGTERM I get a ENOENT.

```
bin/rails s
=> Booting Puma
=> Rails 4.2.5.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[88789] Puma starting in cluster mode...
[88789] * Version 3.0.2 (ruby 2.3.0-p0), codename: Plethora of Penguin Pinatas
[88789] * Min threads: 1, max threads: 1
[88789] * Environment: development
[88789] * Process workers: 2
[88789] * Preloading application
[88789] * Listening on tcp://localhost:3000
[88789] Use Ctrl-C to stop
[88789] - Worker 0 (pid: 88818) booted, phase: 0
[88789] - Worker 1 (pid: 88819) booted, phase: 0
^C[88789] - Gracefully shutting down workers...
/Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:355:in `delete': 
No such file or directory @ unlink_internal - /Users/jared/git/redacted/redacted/tmp/pids/server.pid (Errno::ENOENT)
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:355:in `block in write_pid'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.0.2/lib/puma/cluster.rb:120:in `fork'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.0.2/lib/puma/cluster.rb:120:in `block in spawn_workers'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.0.2/lib/puma/cluster.rb:116:in `times'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.0.2/lib/puma/cluster.rb:116:in `spawn_workers'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.0.2/lib/puma/cluster.rb:415:in `run'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.0.2/lib/puma/launcher.rb:173:in `run'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-3.0.2/lib/rack/handler/puma.rb:51:in `run'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/server.rb:80:in `start'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/jared/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:10:in `require'
	from bin/rails:10:in `<main>'
[88789] === puma shutdown: 2016-03-01 15:18:03 -0500 ===
[88789] - Goodbye!
Exiting
```

Not a big deal, but no one likes to see an unexpected stack trace.

**Comment by klippx** [comment]
I think it is due to having 2 workers and both concurrently trying to do the same thing. One worker deletes it, the other throws. This hypothesis is backed by doing the following 2 quick tests:

- If you start rails with two workers and ctrl+c the error is present.
- If you start rails with only one worker and ctrl+c the error goes away.

I agree with @jaredbeck that this would be nice to have a fix for.

**Comment by evanphx** [comment]
That error is actually inside Rack::Server itself, it's something I have no control over in this case because Puma is started via `rails s`.

**Comment by jaredbeck** [comment]
> That error is actually inside Rack::Server itself, it's something I have no control over in this case because Puma is started via rails s.

OK, so are you going to open an issue with that project, or do you want someone else to do it, or how do you want to proceed?

**Comment by klippx** [comment]
@evanphx For a rails app the documentation says we should start it with the command `rails s Puma`. Rack::Server is not necessarily meant to be run concurrently in threads, isn't this is a responsibility that Puma pushes upon it? 

When Puma is "Gracefully shutting down workers..." it is actually doing so in parallell, right, so this becomes a concurrency issue/race condition because all threads see that the PID file exist and try to delete it:

```ruby
      def write_pid
        ::File.open(options[:pid], ::File::CREAT | ::File::EXCL | ::File::WRONLY ){ |f| f.write("#{Process.pid}") }
        at_exit { ::File.delete(options[:pid]) if ::File.exist?(options[:pid]) }
      rescue Errno::EEXIST
        check_pid!
        retry
      end
```
*- rack-1.6.4/lib/rack/server.rb*

How could Rack::Server protect itself from this particular failure, it already tries to do so? Wouldn't a better solution be that Puma shuts down workers one-by-one (ie even more Gracefully)?

Would this issue not happen when starting puma with pumactl?

**Comment by jaredbeck** [comment]
>> That error is actually inside Rack::Server itself, it's something I have no control over in this case because Puma is started via rails s.
>
> OK, so are you going to open an issue with that project, or do you want someone else to do it, or how do you want to proceed?

@evanphx please advise

**Comment by oboxodo** [comment]
I'm having this same issue after upgrading from 2.15.x to 3.4.0. @evanphx is there a chance this is a regression since then?

**Comment by sophiedeziel** [comment]
Just so you know, I opened a pull-request on Rack to solve that: https://github.com/rack/rack/pull/1080
