### ISSUE TITLE
Restarting Puma on CentOS Broke

### ISSUE THREAD

**Issue by rodrigdav** [puma/puma#918]
We updated puma to 3.0.1 and all of a sudden I can't restart or start puma.  When I try to restart/start the application I get the following 

```NameError: undefined local variable or method `restart_args' for #<Puma::Single:0xbb095>
  jruby_daemon_start at /opt/ruby/lib/ruby/gems/shared/gems/puma-3.0.1-java/lib/puma/single.rb:35
                 run at /opt/ruby/lib/ruby/gems/shared/gems/puma-3.0.1-java/lib/puma/single.rb:74
                 run at /opt/ruby/lib/ruby/gems/shared/gems/puma-3.0.1-java/lib/puma/launcher.rb:173
                 run at /opt/ruby/lib/ruby/gems/shared/gems/puma-3.0.1-java/lib/puma/cli.rb:74
               <top> at /opt/ruby/lib/ruby/gems/shared/gems/puma-3.0.1-java/bin/puma:10
                load at org/jruby/RubyKernel.java:957
               <top> at bin/puma:16```

Any thoughts?  

This is running on a Centos 6.6 server and running on jruby 9.0.4.0

**Comment by donv** [comment]
I can confirm the issue on our system, CentOS release 5.11.

**Comment by rodrigdav** [comment]
If I go back to puma version  2.12.2 which is what we were using before it starts working again.

**Comment by donv** [comment]
Puma 2.16.0 is working for us.

**Comment by evanphx** [comment]
Sorry about that! Fix showing up VERY shortly!

**Comment by donv** [comment]
@evanphx Thanks!  Looking forward to it.  Puma is great!

**Comment by donv** [comment]
@evanphx Awesome!

**Comment by evanphx** [comment]
3.1.0 out now should fix this issue! Please let me know if other things are JRuby are busted!

**Comment by donv** [comment]
I can confirm the fix OK :+1: in our production test environment.  Thanks!

Will let you know about any JRuby issues :smile: 

Well, actually, I'll submit a trivial consmetic issue right away: https://github.com/puma/puma/issues/923

**Comment by donv** [comment]
@evanphx BTW: the tests are failing for JRuby in travis:  https://travis-ci.org/puma/puma

**Comment by evanphx** [comment]
@donv: Yeah, I'm working on the JRuby tests this evening.
