### ISSUE TITLE
tmp_restart not working with daemon mode

### ISSUE THREAD

**Issue by lokenmakwana** [puma/puma#925]
I recently upgraded to puma 3.1.0

Noticed that when running puma in foreground and touching tmp/restart.txt triggers a restart.

But in case of running puma in daemon mode (-d) don't trigger restarts as expected.

Steps to reproduce

1. start puma server  without -d
2. touch tmp/restart.txt restarts server

3. start puma server with -d and redirect output to another file
4. touch tmp/restart.txt does nothing here

**Comment by evanphx** [comment]
Sorry for the delay on this!
