### ISSUE TITLE
Recieving MSS error with PUMA

### ISSUE THREAD

**Issue by lschroth** [puma/puma#928]
We have our PUMA ver 3.0.2 version behind our SonicWALL firewall and keep receiving a MSS header checksum error from the Firewall from our PUMA installation.  Any idea on what might be causing this?

**Comment by evanphx** [comment]
Can you show me the error somehow?

**Comment by evanphx** [comment]
I have zero idea how that would happen, it's not as though puma has control over those values...

**Comment by evanphx** [comment]
Please reopen if you have more info.
