### ISSUE TITLE
Large Responses Truncated Only Via UNIX Socket

### ISSUE THREAD

**Issue by cdonadeo** [puma/puma#929]
- CentOS 6.7
- OpenJDK 1.8.0_71
- JRuby 9.0.5.0
- Puma 3.1.0
- Rails 4.2.5.1

I'm having an issue where a specific GET request which returns a rather large JSON response (168849 bytes with my current test data) is being truncated **only** when using Puma's UNIX socket.  The truncation can vary, but most commonly only 128000 bytes are returned.  I'm able to replicate the issue when making the request direct to Puma's UNIX socket myself, or when using Nginx as a reverse proxy with Puma's UNIX socket as an upstream.  I am attaching raw request and response headers:
- [request.txt](https://github.com/puma/puma/files/164342/request.txt)
- [response.txt](https://github.com/puma/puma/files/164341/response.txt)

I am able to reliably reproduce this issue using this command to generate a request to Puma's UNIX socket:
```
nc -U /opt/REDACTED/shared/tmp/sockets/puma.sock < request.txt
```
The same request sent instead to Puma's TCP socket, which responds correctly:
```
nc 127.0.0.1 9292 < request.txt
```
Note that this is the same instance of Puma configured to bind to both the UNIX socket and the TCP address - I would expect the results to be exactly the same.

I can also observe this issue affecting Nginx.  I am attaching my configuration, adapted from the one generated by capistrano-puma:
- [nginx_config.txt](https://github.com/puma/puma/files/164359/nginx_config.txt)

Nothing of interest is logged, though the access log does show the response being served is shorter than what would be correct:
```
[09/Mar/2016:00:35:13 +0000] "GET /api/v1/services/problems HTTP/1.1" 200 128259 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
```

Puma is usually started via Capistrano, but for testing purposes I borrowed and modified capistrano-puma's command to hopefully get more information:
```
export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="jruby-9.0.5.0" RACK_ENV="staging" ; $HOME/.rbenv/bin/rbenv exec bundle exec puma -C /opt/REDACTED/shared/puma.rb --log-requests --debug
```
But this yields nothing of any interest.  The only log line for each request is this:
```
127.0.0.1 - - [09/Mar/2016:02:28:39 +0000] "GET /api/v1/services/problems HTTP/1.1" 200 - 0.2470
```
Here is the Puma configuration file being loaded:
- [config.txt](https://github.com/puma/puma/files/164354/config.txt)

The Rails log indicates no issues either, aside from the request being slow to process (expected):
```
I, [2016-03-09T02:55:20.651000 #22322]  INFO -- : [9ca3fedc-650e-417e-8970-2f0ba08dd282] Completed 200 OK in 384ms (Views: 329.5ms | ActiveRecord: 25.0ms)
```
Now for real kicker: the issue seems to be somehow related to how fast the response is read off the socket.  Piping the results of `nc` to a file like so:
```
nc -U /opt/REDACTED/shared/tmp/sockets/puma.sock < request.txt > response.txt
```
Seems to always return the full response.  In other words, observing the issue makes it disappear.  As long as I allow `nc` to dump output to the console, it is truncated.  In a terminal emulator with enough backscroll, I can copy and paste the response into a file and that file's size will be truncated.  This is not just an artifact of the console or `nc` either - Nginx serves the same truncated response.  My theory is that opening the file file for writing somehow slows things down enough that some sort of race condition is avoided, but I have no evidence to support that.

Any advice on how to go about troubleshooting this would be greatly appreciated.

**Comment by evanphx** [comment]
How are you generating the json? It's not being generated as one big string and returned, I can tell that by the use of chunked encoding. Perhaps there is something there that will shine a light on this.

**Comment by evanphx** [comment]
Closed due to lack of input.

**Comment by cdonadeo** [comment]
Hi Evan,

Sorry for the long delay - I am still here.  The controller just passes an AR relation to a Jbuilder view.  I hadn't really thought about it, but it could possibly make sense that the JSON is being built in some sort of incremental manner - I'm not very familiar with how Jbuilder goes about things under the hood.  Here's the controller in `app/controllers/api/v1/services_controller.rb`:
```
class Api::V1::ServicesController < ApplicationController
  def problems
    @services = Service.problems.includes(:host)
  end
end
```
and here's the view in `app/views/api/v1/services/problems.json.jbuilder`:
```
json.array!(@services) do |service|
  json.extract! service, :id, :remote_id, :name, :backend_acknowledged, :acknowledged, :backend_downtimed, :downtimed, :check_interval, :retry_interval, :current_attempt, :max_check_attempts, :state, :last_state_change, :last_healthy, :last_check, :state_message, :notes_url, :notes, :host_id
  json.host do
    json.extract! service.host, :id, :remote_id, :name, :notes_url, :notes, :backend_id, :backend_acknowledged, :acknowledged, :backend_downtimed, :downtimed
  end
end
```
As far as I know this is pretty par for the course in a Rails app.  The output is something like this (only not formatted):
```
[{
	"id": 41413,
	"remote_id": "some_short_name",
	"name": "A Longer Name",
	"backend_acknowledged": false,
	"acknowledged": false,
	"backend_downtimed": false,
	"downtimed": false,
	"check_interval": 60,
	"retry_interval": 60,
	"current_attempt": 1,
	"max_check_attempts": 1,
	"state": "critical",
	"last_state_change": 1460250052,
	"last_healthy": null,
	"last_check": 1460413397,
	"state_message": "Usually a sentence or two",
	"action_url": "http://example.net/some/path",
	"notes_url": "http://example.net/some/other/path",
	"notes": "Usually a sentence or two",
	"host_id": 4046,
	"host": {
		"id": 4046,
		"remote_id": "host.example.net",
		"name": null,
		"notes_url": null,
		"notes": null,
		"backend_id": 1054,
		"backend_acknowledged": false,
		"acknowledged": false,
		"backend_downtimed": false,
		"downtimed": false
	}
}]
```
The above example shows roughly what we'd see when the relation yields 1 element.  When the query results are this short, I see no issues.  However, at the moment the live system ends up encoding an array with about 300 elements, which makes a much larger response and does exhibit the issue.

As a troubleshooting step, I rewrote my controller to use JSON.generate instead:
```
class Api::V1::ServicesController < ApplicationController
  def problems
    result = []
    @services = Service.problems.includes(:host).each do |service|
      result << service.to_hash
    end
    render json: JSON.generate(result)
  end
end
```
Service#to_hash does what it says - returns a simple hash representation of the AR object in question.  So, we're encoding nothing but a simple array of simple hashes - no magic involved.  I think this should make Rails just pass the already-encoded JSON - no templates or anything required.  It has the exact same issues with truncated output as my original implementation though.  My next step is to separate this logic from my application and move it to a new, clean Rails application and see if I can reproduce the issue there.  I'll let you know what I find.

**Comment by cdonadeo** [comment]
@evanphx I was actually able to reproduce this pretty easily with a fresh Rails app and very few changes.  I put the entire application in a repo so you can see:

https://github.com/cdonadeo/puma_big_response_test

**Comment by evanphx** [comment]
So, sadly this appears to be a JRuby bug. I've submitted it: https://github.com/jruby/jruby/issues/3799.

Until that bug is fixed, you likely should not use unix sockets on jruby.
