### ISSUE TITLE
is Puma + Grape not threadsafe ?

### ISSUE THREAD

**Issue by wxianfeng** [puma/puma#933]
my online Grape Project change unicorn to puma deploy.

so much users get other users data from api.

develop by Rails 4.2 + puma 3.0.1 + Grape 0.9.0.

some code like as:

base.rb
```
module V3
  class Base < Grape::API 
    helpers V3Helpers

    include V3::Photos
  end
end
```

v3_helpers.rb
```
def current_user
return @current_user if defined? @current_user

@current_user = User.find(params[:uid])
end
```

photos.rb
```
module V3
  module Photos
    extend ActiveSupport::Concern

    included do

      resources :photos do
    
        get do 
          photos = Photo.where(user_id: current_user.id)
          photos.to_json 
        end   
   
      end

    end
end
end
```

is my code not threadsafe ?

**Comment by evanphx** [comment]
I assume that the helper is scope to an instance of the controller created per request. In that case, you should be fine. I don't know if the internals of Grape are thread safe, but most frameworks are pretty good on that at this stage.

**Comment by wxianfeng** [comment]
this issue is not Puma problem

at last i found `active_model_serializers` problem, am use not release code,  it's use class variables, not threadsafe !

`gem 'active_model_serializers', git: 'https://github.com/rails-api/active_model_serializers.git', ref: '2df8804'`

`active_model_serializers/lib/active_model/serializer.rb`

```ruby
def read_attribute_for_serialization(attr)
  if self.class._serializer_instance_method_defined?(attr)
    send(attr)
  elsif self.class._fragmented
    self.class._fragmented.read_attribute_for_serialization(attr)
  else
    object.read_attribute_for_serialization(attr)
  end
end
```

chinese user , u can see here: https://ruby-china.org/topics/30188
