### ISSUE TITLE
Release notes between version 2.6 and 3.2?

### ISSUE THREAD

**Issue by robmathews** [puma/puma#934]
This isn't an issue, just wondering where to look. We're currently running 2.6 and I'm noticing we're woefully behind, with v3.2 being released. Short of reading the commit logs, where can I find the release notes or some other information that help me figure out what to watch out for?

Great work on the gem BTW. Thanks!

**Comment by hsoerensen** [comment]
@robmathews There's a history file at https://github.com/puma/puma/blob/master/History.txt
