### ISSUE TITLE
Puma::Server::running returns "true" after stopping server

### ISSUE THREAD

**Issue by jenlersadnie** [puma/puma#935]
Hey, all,

I came across this recently by starting and stopping a puma server instance, then checking if the server is running. It looks like in Puma::Server::running, you check for the existence of a ThreadPool and whether the spawned thread count resolves to true. I assume that you intend for this to return false when the thread pool exists and the spawned threads count is 0. That is, at least, the state of the thread pool after a server is shut down.

```
    def running
      @thread_pool and @thread_pool.spawned
    end
```
https://github.com/puma/puma/blob/master/lib/puma/server.rb#L131
https://github.com/puma/puma/blob/master/lib/puma/thread_pool.rb

When `@thread_pool` is initialized, its `@spawned` instance variable is set to 0, and the value is never unset. Furthermore, 0 in ruby resolves to true:
```
irb(main):001:0> 0 ? true : false
=> true
```

Is Puma::Server::running expected to return false after invoking Puma::Server::stop? If so, this is a bug.
If not, my apologies!

**Comment by evanphx** [comment]
Running returns the number of threads that are running, not if puma is running or not. Sorry for the confusion!
