### ISSUE TITLE
puma missing query string

### ISSUE THREAD

**Issue by huangxiangdan** [puma/puma#937]
Hi, all

I'm using puma 3.2 as my Rails webserver. When I make a http get request with query string like this,

```
GET http://192.168.1.96:3000/api/v1/matches/test?1=1 HTTP/1.1  
Accept: text/event-stream
Authorization: Token  token=QsG8IZ77ng0e9PJXgKyEzniRe4lCbK7yeeB1B+9MKnaG6Aa08c7zDZGAH19XbdJICJgHcZr9YMeGLi+3dCkWaA==, imei=867575025069603   
Host: 192.168.1.96   
Origin: http://192.168.1.96   
Cache-Control: no-cache  
```
Puma is missing the query string "1=1", like 
```
Started GET "/api/v1/matches/test" for 192.168.1.45 at 2016-03-29 11:30:12 +0800
```

When I change my webserver back to WEBrick, It workes fine.
```
Started GET "/api/v1/matches/test?1=1" for 192.168.1.45 at 2016-03-29 11:32:12 +0800
```

I think it's a bug of puma. Please check it.

**Comment by evanphx** [comment]
Are you using puma as a proxy server? Why are you including a URL in the path?

**Comment by huangxiangdan** [comment]
No, I'm not using puma as a proxy server. I run it direct on command "rails server", and then I request from my android app.

Some android lib behave like this, using absolute url in the path. I'm using [eventsource](https://github.com/tylerjroach/eventsource-android). And I checked [HTTP 1.1 protocol](https://tools.ietf.org/html/rfc2616#section-5.1.2) , using absolute url is fine.

**Comment by evanphx** [comment]
@huangxiangdan Ah ok. Just curious. Can you verify for me if the query params are missing in the actual code or is it just the log output?

**Comment by huangxiangdan** [comment]
The query params are missing in theactual code.


Original Message
Sender:Evan Phoenixnotifications@github.com
Recipient:puma/pumapuma@noreply.github.com
Cc:Danny Huangxd_huang1986@163.com
Date:Wednesday, Mar 30, 2016 09:59
Subject:Re: [puma/puma] puma missing query string (#937)


@huangxiangdan Ah ok. Just curious. Can you verify for me if the query params are missing in the actual code or is it just the log output?
