### ISSUE TITLE
Conditional port is ignored in puma.rb

### ISSUE THREAD

**Issue by micahlisonbee** [puma/puma#939]
When I put a conditional for the port value it seems to get ignored and 5000 is used. When I define the port explicitly it works. Here is my puma.rb, the ` ENV['PORT']` is not defined in this case, running locally.

When I do `port 3001` it works.

Using `Puma 3.0.2`

```
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
port        ENV['PORT'] || 3001
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection

  if defined?(Resque)
     Resque.redis = ENV["<redis-uri>"] || "redis://127.0.0.1:6379"
  end
  
end
```

**Comment by evanphx** [comment]
Are you sure that `ENV['PORT']` is not defined? Add `p :env => ENV['port']` and see what is output.

**Comment by micahlisonbee** [comment]
`{:env=>nil}`

```ruby
workers Integer(ENV['WEB_CONCURRENCY'] || 2)
threads_count = Integer(ENV['MAX_THREADS'] || 5)
threads threads_count, threads_count

preload_app!

rackup      DefaultRackup
p :env => ENV['port']
port        ENV['PORT'] || 3001
environment ENV['RACK_ENV'] || 'development'

on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  
  
end
```

It seemed to be working for a while, is the port cached somewhere and it's not getting reset upon start/stop of server?

**Comment by evanphx** [comment]
Nothing in puma resets environment variables. How are you running puma? What environment? (heroku, upstart, systemd, command line, etc)

**Comment by micahlisonbee** [comment]
Heroku for production, but local development with `rails s` is where i'm having the port problems.

**Comment by evanphx** [comment]
Ok, can you run me through when it stops working? I need to understand the steps to try and figure out what the issue is.

**Comment by micahlisonbee** [comment]
It looks like it defaults to 3000 with `rails s` regardless of what's in puma.rb. Looks like it reads the port correctly running `heroku local`.

```ruby
#puma.rb
port        ENV['PORT'] || 3000
```

`rails s`

`[49861] * Listening on tcp://0.0.0.0:3000`

Kill server.
Change port to 3001:

```ruby
#puma.rb
port        ENV['PORT'] || 3001
```

`rails s`

` Listening on tcp://0.0.0.0:3000`

It doesn't reflect the change to port 3001.

Remove conditional and restart:

```ruby
#puma.rb
port        3001
```

Still on 3000:
` Listening on tcp://0.0.0.0:3000`

run `heroku local`
`Listening on tcp://0.0.0.0:3001`

It works with `heroku local`.

Kill server and `rails s` again.

Back on 3000:
`Listening on tcp://0.0.0.0:3000`

**Comment by vipulnsward** [comment]
Related https://github.com/rails/rails/issues/24435#issuecomment-205875323
rails server, does not support it. running `puma` directly will.

**Comment by evanphx** [comment]
OH, I did not realize you were starting puma via `rails s`. Yes, via `rails s` it has control of the port entirely.

**Comment by micahlisonbee** [comment]
Ok thanks.

**Comment by schneems** [comment]
It should be read in via the rack handler, I think we should re-open this issue

**Comment by schneems** [comment]
This works for me

```
$ env PORT=4000 rails server
=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:4000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:2: warning: already initialized constant GitHubBub::Request::USER_AGENT
/Users/richardschneeman/.gem/ruby/2.3.0/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:7: warning: previous definition of USER_AGENT was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:3: warning: already initialized constant GitHubBub::Request::RETRIES
/Users/richardschneeman/.gem/ruby/2.3.0/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:12: warning: previous definition of RETRIES was here
/Users/richardschneeman/Documents/projects/codetriage/config/initializers/git_hub_bub.rb:4: warning: already initialized constant GitHubBub::Request::GITHUB_VERSION
/Users/richardschneeman/.gem/ruby/2.3.0/gems/git_hub_bub-0.0.6/lib/git_hub_bub/request.rb:8: warning: previous definition of GITHUB_VERSION was here
[59980] Puma starting in cluster mode...
[59980] * Version 3.0.0.rc1 (ruby 2.3.0-p0), codename: Schneems Sleak Shoes
[59980] * Min threads: 5, max threads: 5
[59980] * Environment: development
[59980] * Process workers: 2
[59980] * Preloading application
[59980] * Listening on tcp://localhost:4000
[59980] Use Ctrl-C to stop
[59980] - Worker 0 (pid: 60018) booted, phase: 0
[59980] - Worker 1 (pid: 60019) booted, phase: 0
```

Are you using Puma 3.0 or above?

**Comment by schneems** [comment]
Okay, so the reason that worked is that `rails server` sets port for you via ENV["PORT"] https://github.com/rails/rails/blob/9d87ce34f865fa9d7a24ef9f1f1b0d4dedfd3fbf/railties/lib/rails/commands/server.rb#L92-L92

What we're seeing here is that puma is picking up the Port option that is passed in, and prefering it to the port that is set in the `config/puma.rb`. I think we want the `config/puma.rb` to be authoritative i.e. if there is a conflict (at least with the rack handler) then the config file should win.

Here is where it is set to 3000 based on the `rails server` input hash https://github.com/puma/puma/blob/d2da2caf49932827f07994c8b65b1f99001c5fb9/lib/rack/handler/puma.rb#L39

I changed my config file to this

```
port 4000 
```

Then when I boot the app still run s with 


```
[63654] * Listening on tcp://localhost:3000
```

The DSL value is being picked up, curiously it is set to 4000 __after__ it is set to 3000, but for some reason it does not get persisted. Here is the caller of where `port` is being called from when it is set to 4000 (from the file). 

```
config/puma.rb:7:in `_load_from'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/puma/dsl.rb:26:in `instance_eval'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/puma/dsl.rb:26:in `_load_from'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/puma/dsl.rb:9:in `load'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:204:in `block in load'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:201:in `each'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/puma/configuration.rb:201:in `load'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/puma/launcher.rb:62:in `initialize'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/rack/handler/puma.rb:47:in `new'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/puma-3.4.0/lib/rack/handler/puma.rb:47:in `run'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:296:in `start'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:78:in `start'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:90:in `block in server'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `tap'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `server'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
/Users/richardschneeman/.gem/ruby/2.3.0/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in `<top (required)>'
```

I think this is an issue in Puma, we should re-open the issue. Any idea why `port` being called after might not set the binds correctly?

**Comment by schneems** [comment]
When I output the value of `@options` here https://github.com/puma/puma/blob/d2da2caf49932827f07994c8b65b1f99001c5fb9/lib/puma/launcher.rb#L64

I see that binds is set to 4000 in that object


```ruby
#<Puma::LeveledOptions:0x007f8dfca5d318 @cur={:workers=>2, :min_threads=>6, :max_threads=>6, :rackup=>"config.ru", :binds=>["tcp://0.0.0.0:4000"], :environment=>"development", :preload_app=>true, :before_worker_boot=>[#<Proc:0x007f8dfbb06018@config/puma.rb:11>]}, @set=[{:environment=>"development", :pid=>"/Users/richardschneeman/Documents/projects/codetriage/tmp/pids/server.pid", :Port=>3000, :Host=>"localhost", :AccessLog=>[], :config=>"/Users/richardschneeman/Documents/projects/codetriage/config.ru", :DoNotReverseLookup=>true, :daemonize=>false, :caching=>false, :log_stdout=>true, :server=>nil}, {:log_requests=>false, :environment=>"development", :binds=>["tcp://localhost:3000"], :app=>#<CodeTriage::Application:0x007f8e00dce9a8 @_all_autoload_paths=["/Users/richardschneeman/Documents/projects/codetriage/app/assets", "/Users/richardschneeman/Documents/projects/codetriage/app/controllers", "/Users/richardschneeman/Documents/projects/codetriage/app/helpers", "/Users/richardschneeman/Documents/projects/codetriage/app/jobs", "/Users/richardschneeman/Documents/projects/codetriage/app/mailers", "/Users/richardschneeman/Documents/projects/codetriage/app/models", "/Users/richardschneeman/Documents/projects/codetriage/app/services"], @_all_load_paths=["/Users/richardschneeman/Documents/projects/codetriage/lib", "/Users/richardschneeman/Documents/projects/codetriage/vendor", "/Users/richardschneeman/Documents/projects/codetriage/app/assets", "/Users/richardschneeman/Documents/projects/codetriage/app/controllers", "/Users/richardschneeman/Documents/projects/codetriage/app/helpers", "/Users/richardschneeman/Documents/projects/codetriage/app/jobs", "/Users/richardschneeman/Documents/projects/codetriage/app/mailers", "/Users/richardschneeman/Documents/projects/codetriage/app/models", "/Users/richardschneeman/Documents/projects/codetriage/app/services"], @app=#<Rack::Sendfile:0x007f8e019af150 @app=#<ActionDispatch::Static:0x007f8e019af3f8 @app=#<ActionDispatch::LoadInterlock:0x007f8e019af420 @app=#<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007f8e019a6910 @name="ActiveSupport::Cache::Strategy::LocalCache", @local_cache_key=:active_support_cache_null_store_local_cache_70123944453740, @app=#<Rack::Runtime:0x007f8e019af448 @app=#<Rack::MethodOverride:0x007f8e019af4c0 @app=#<ActionDispatch::RequestId:0x007f8e019af4e8 @app=#<Rails::Rack::Logger:0x007f8e019af588 @app=#<ActionDispatch::ShowExceptions:0x007f8e019af5b0 @app=#<WebConsole::Middleware:0x007f8e019af5d8 @app=#<ActionDispatch::DebugExceptions:0x007f8e019af650 @app=#<ActionDispatch::RemoteIp:0x007f8e019af678 @app=#<ActionDispatch::Reloader:0x007f8e019af6a0 @app=#<ActionDispatch::Callbacks:0x007f8e019af718 @app=#<ActiveRecord::Migration::CheckPending:0x007f8e019af740 @app=#<ActiveRecord::ConnectionAdapters::ConnectionManagement:0x007f8e019af768 @app=#<ActiveRecord::QueryCache:0x007f8e019af7e0 @app=#<ActionDispatch::Cookies:0x007f8e019af808 @app=#<ActionDispatch::Session::CookieStore:0x007f8e019af998 @app=#<Rack::Head:0x007f8e019af9c0 @app=#<Rack::ConditionalGet:0x007f8e019af9e8 @app=#<Rack::ETag:0x007f8e019afa60 @app=#<Warden::Manager:0x007f8e019afb78 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x007f8dfd29f0d0>}, @app=#<struct ActionView::Digestor::PerRequestDigestCacheExpiry app=#<Bullet::Rack:0x007f8e019afc18 @app=#<OmniAuth::Strategies::GitHub>>>>, @cache_control="max-age=0, pri

# ...
```


However

```ruby
puts @options[:binds]
# => tcp://localhost:3000
```

So it looks like something funny is going on with `LeveledOptions`

**Comment by vipulnsward** [comment]
In the above case, when trying to read binds, its hitting https://github.com/puma/puma/blob/c4006b93fad6052a915bca2703cccedf6d4812b8/lib/puma/configuration.rb#L33

This is taking precision for user_options passed on from Rails(default 3000), since its the first entry created in https://github.com/puma/puma/blob/c4006b93fad6052a915bca2703cccedf6d4812b8/lib/puma/configuration.rb#L17-L18.

Changing it to `reverse_each`, fixes this issue.

**Comment by evanphx** [comment]
So the problem is that rails specifies it's own port and passes it into the puma rack handler. Then we load the config file. The rack handler has higher precedence (which is how it should be) and thus we get this behavior. I think the current behavior is actually the correct one, because you're using `rails s` which has it's own way to specify the port. If you don't want to do that, then use `puma` directly.

**Comment by schneems** [comment]
I'm wondering if maybe there's an orthogonal solution. Could we bind to both ports? It looks like puma can do that. Maybe we can warn when you specify different ports and we only bind to one. Something like

> Rack passed in a different port than specified in config/puma.rb to use this port instead run the `puma` command directly

Something like that?

**Comment by evanphx** [comment]
It could bind to multiple ports, sure, but I'm doubting people would expect that?

**Comment by schneems** [comment]
Agreed binding to multiple ports would be non-obvious. 

I'm thinking either we could make it more clear where the values are coming from, maybe listing out the flags that are passed in via the options hash. Alternatively we could add some logic in Rails to not specify port if puma is bundled and a `config/puma.rb` file exists.

**Comment by omitter** [comment]
This is pretty confusing. I thought the implicit order when using `rails server` would be `command-line options > environment variables > conf/puma.rb > puma default values`. Maybe you can find a more straight forward solution? Is it possible to load conf/puma.rb earlier? Is there any way to make `rails server` bind to another ip/socket without using command-line options?

**Comment by nateberkopec** [comment]
hey @omitter we're fixing this via #28137
