### ISSUE TITLE
Local haproxy does not see puma backend

### ISSUE THREAD

**Issue by richmolj** [puma/puma#943]
Not sure if this is the correct place to file an issue, but not having luck finding a solution anywhere else.

I have a new rails app with a local haproxy. Using `bin/rails s webrick`, haproxy finds the rails backend with no problems. With `bin/rails s puma`, as far as haproxy is concerned the Rails app is not even running. This is with the simplest possible haproxy config:

```
global
  maxconn 4096

defaults
  mode http

frontend http-farm
  bind *:9000
  default_backend rails

backend rails
  server localhost_3000 localhost:3000
```

Could someone point me in the right direction?

**Comment by evanphx** [comment]
@richmolj Can you hit localhost:3000 fine by hand? What exactly does haproxy say about that backend in the logs?

**Comment by richmolj** [comment]
Thanks for the response!

Yes, I can hit localhost:300 fine by hand. If I run haproxy in debug mode, you'll see the request come in, then see the response:

```
00000000:rails.clicls[0008:000b]
00000000:rails.closed[0008:000b]
```

If I start rails with webrick, you'll see the correct response as something like

```
00000006:rails.srvrep[0008:000b]: HTTP/1.1 200 OK
00000006:rails.srvhdr[0008:000b]: X-Frame-Options: SAMEORIGIN
00000006:rails.srvhdr[0008:000b]: X-Xss-Protection: 1; mode=block
00000006:rails.srvhdr[0008:000b]: X-Content-Type-Options: nosniff
00000006:rails.srvhdr[0008:000b]: Content-Type: application/json; charset=utf-8
00000006:rails.srvhdr[0008:000b]: Etag: W/"9efea607cceada2d867cff074281c553"
00000006:rails.srvhdr[0008:000b]: Cache-Control: max-age=0, private, must-revalidate
00000006:rails.srvhdr[0008:000b]: X-Request-Id: f5d94957-ce70-4f3b-9865-a92185038ec2
00000006:rails.srvhdr[0008:000b]: X-Runtime: 0.058698
00000006:rails.srvhdr[0008:000b]: Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
```

I was thinking since puma starts on `tcp://localhost:3000` and not `http://localhost:3000`. That might be the issue, but using haproxy's `mode tcp` seems to have a similar problem:

```
00000000:http-farm.accept(0004)=0008 from [127.0.0.1:53529]
00000000:rails.clicls[0008:0009]
00000000:rails.closed[0008:0009]
00000001:http-farm.accept(0004)=0008 from [127.0.0.1:53535]
00000001:rails.clicls[0008:0009]
00000001:rails.closed[0008:0009]
```

**Comment by richmolj** [comment]
It actually looks specific to `rails s`. This will start puma and will fail with haproxy. HOWEVER, if I start puma using `bin/puma -C config/puma.rb` everything works ok.

**Comment by evanphx** [comment]
This might be related to how localhost is resolved. Try using `127.0.0.1` instead of localhost in case there is some weird ipv6 localhost screwing with things.

**Comment by richmolj** [comment]
Gave it a shot but no luck unfortunately

**Comment by evanphx** [comment]
@richmolj I'll see if I can replicate the issue locally.

**Comment by evanphx** [comment]
So, the issue is that an OS X (which I'm assuming where you're having this problem, but it could happen on other platforms too), when a socket says to listen on "localhost", it's dependent upon `/etc/hosts` to define what "localhost" means. Well, ruby ends up listen on `::1` (IPv6 for localhost) only in this case.

There are 2 fixes for you:

1. In your haproxy config, using `::1:3000` instead of `localhost:3000`, then haproxy will connect properly.
2. Use `rails s -b 127.0.0.1` to force puma to use the IPv4 localhost only.

**Comment by richmolj** [comment]
:+1: verified `::1:3000` fixes the issue
