### ISSUE TITLE
Rails Server close issue - Couldn't cleanly terminate all actors in 10 seconds!

### ISSUE THREAD

**Issue by sai43** [puma/puma#948]
[28159] - Gracefully shutting down workers...
/Users/Apple/.rvm/gems/ruby-2.2.3@global/gems/rack-1.6.4/lib/rack/server.rb:355:in `delete': No such file or directory @ unlink_internal - /Users/Apple/Developer/rails/humos-rails-server-develop/tmp/pids/server.pid (Errno::ENOENT)

from /Users/Apple/.rvm/gems/ruby-2.2.3@global/gems/rack-1.6.4/lib/rack/server.rb:355:in `block in write_pid'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/puma/cluster.rb:120:in `fork'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/puma/cluster.rb:120:in `block in spawn_workers'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/puma/cluster.rb:116:in `times'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/puma/cluster.rb:116:in `spawn_workers'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/puma/cluster.rb:172:in `check_workers'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/puma/cluster.rb:460:in `run'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/puma/launcher.rb:173:in `run'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/puma-3.0.1/lib/rack/handler/puma.rb:51:in `run'
        from /Users/Apple/.rvm/gems/ruby-2.2.3@global/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/server.rb:80:in `start'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /Users/Apple/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'
E, [2016-04-08T08:29:41.524282 #28645] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2016-04-08T08:29:41.524356 #28647] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
E, [2016-04-08T08:29:41.524580 #28646] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!
[28159] === puma shutdown: 2016-04-08 08:29:41 +0530 ===
[28159] - Goodbye!
Exiting

**Comment by evanphx** [comment]
I'm sorry, this is not a proper issue. I have no clue what you're reporting.

**Comment by evanphx** [comment]
If I were to guess based on your paste, it's about that error message which is not emitted from puma.

**Comment by freen** [comment]
This issue is happening to my team's application as well. When we send a `phased-restart` signal to the master puma process, there's a 50/50 chance that all requests interacting with the hard-drive will result in this error, e.g. `getcwd`, `pwd`, `unlink_internal`. The application more or less fails.

For instance, any transaction using `RestClient` is a valid test of whether this problem is occurring. since it invokes `getcwd`somewhere under the hood. (We're making an API call in our health check to determine whether the bug is present or not.)

We're running:
* Puma 3.1.0
* Rails 5.0.0.beta3
* Ruby 2.2.4
* Ubuntu 14.04.3

**Comment by freen** [comment]
Our current remediation step is to redeploy the application. The subsequent `phased-restart` typically resolves the issue (until the next botched deployment.)

**Comment by evanphx** [comment]
@freen please open an issue about your problem separately. I have no clue if it's related to this one.

**Comment by freen** [comment]
@evanphx thanks!

https://github.com/puma/puma/issues/952

**Comment by evanphx** [comment]
Closed due to lack of input.
