### ISSUE TITLE
upstart puma-manager won't start

### ISSUE THREAD

**Issue by jogaco** [puma/puma#949]
My system: Ubuntu 14.04.1 LTS

puma-manager will not run unless I rename it to puma_manager.conf

**Comment by evanphx** [comment]
What does it do when you try to start it?

**Comment by jogaco** [comment]
Seems odd but this is the behaviour.

`sudo service puma-manager start` => works fine
`sudo bootup` => does not work
whereas if I change the name to `puma_manager.conf`, both scenarios work.

And on several machines.
I was moving my app to a new machine from a different provider and thus had the chance to try and fix this with the unused one.

**Comment by evanphx** [comment]
What is `bootup`?

**Comment by jogaco** [comment]
I meant sudo reboot

**Comment by evanphx** [comment]
@jogaco I'm still very unsure what the issue is. Can you explain further?

**Comment by jogaco** [comment]
The service will not start automatically upon rebooting the system, with the current filename of `puma-manager.conf`.
However, it will start fine if the file is renamed to `puma_manager.conf`

**Comment by evanphx** [comment]
Ok, so I guess keep it that name? Whats wrong with it being `puma_manager.conf`?

**Comment by evanphx** [comment]
Because of the age, I'm going to go ahead and close this. If it's still an issue, please reopen.
