### ISSUE TITLE
Puma seems ingnoring -t options

### ISSUE THREAD

**Issue by ciaoben** [puma/puma#950]
I am playing around for the first time with `puma`, but launching this command:

```
puma -e production -t 2:2 -w 6
```
I expect to have 6 workers, with 2 thread each, instead I get 6 workers with 12:

![schermata 2016-04-08 alle 14 57 59](https://cloud.githubusercontent.com/assets/4526061/14384289/7f56a24e-fd9a-11e5-9719-6dc422bdea81.png)

Why? Am I missing something or it is a bug?

**Comment by evanphx** [comment]
I'm betting those are just other Threads running in the process, not the number of request threads in the thread pool. Puma uses a number of other Threads to manage things, such as the IO Reactor, timeouts, etc.

When you started Puma, what did it say about the number of threads?

**Comment by ciaoben** [comment]
when it starts the server, it shows the right number of threads.


I ll try to start it without thread to understand the minimun number that it uses and see if the behaviour is right with more thread!
