### ISSUE TITLE
phased-restart causes getcwd, pwd, unlink_internal to throw Error::ENOENT

### ISSUE THREAD

**Issue by freen** [puma/puma#952]
When my team sends a `phased-restart` signal to the master puma process, there's a 50/50 chance that all requests interacting with the hard-drive will result in this error. The application fails.

For instance, any transaction using `RestClient` is a valid test of whether this problem is occurring, since it invokes `getcwd`somewhere under the hood. We've added a `RestClient` API call to our application health check / ping URL in order to be notified right away if a deployment causes this bug.

We're running:
* Puma 3.1.0
* Rails 5.0.0.beta3
* Ruby 2.2.4
* Ubuntu 14.04.3
* rbenv

This is an example stacktrace: https://gist.github.com/freen/0859baf8cb21859765c072fe0007069d

This is our `puma.rb`: https://gist.github.com/freen/cc970069488a2a5b672b95d10aea3f6d

Restart cmd (via Capistrano): `pumactl -S tmp/pids/puma.state phased-restart`

Our current remediation step is to redeploy the application. The subsequent `phased-restart` typically resolves the issue (until the next botched deployment.)

**Comment by freen** [comment]
I should also mention that we're managing the deployment using Capistrano, hence the shared / current folders in the stacktrace. We keep the five latest releases on disk, so it isn't a question of the process running in a release folder which has been deleted --- application releases which don't result in Error::ENOENT outages will consistently reflect the latest version deployed.

**Comment by evanphx** [comment]
Do you have the puma output doing a restart? Does this happen every time you use phased-restart only only sometimes? It almost sounds like your system isn't picking up the new directories fast enough?

**Comment by freen** [comment]
So far I'm seeing nothing apropos in the upstart logs, just standard restart details. I'm going to double check our error redirection and output settings and follow-up.
