### ISSUE TITLE
Puma becomes unresponsive a while after deployment.

### ISSUE THREAD

**Issue by dasomx77** [puma/puma#961]
We are currently facing an issue where we would deploy our application on a 2-server cluster, then a while after (about a week or so), both servers will end up unresponsive. We have new-relic monitoring setup on the servers and they happen to show a hike of puma threads right when the servers crash (images below), I interpret it as being because all the available threads became unresponsive and more were spawn as a result but then they end up in the same state as the previously spawned threads and make the entire application unresponsive as well. Here is my puma.rb file:

```
threads 0,4
workers 4
bind "unix:///tmp/houston.puma.sock"
environment "production"
pidfile "/opt/houston/current/tmp/pids/puma.pid"
activate_control_app 'tcp://0.0.0.0:8081', { no_token: true } #This is to be able to send hot restart command by allowing app control through 8081 on localhost
directory "/opt/houston/current"
prune_bundler

# Log puma output to files
stdout_redirect '/opt/houston/current/log/puma.stdout.log', 
	'/opt/houston/current/log/puma.stderr.log', true

# Read VERSION file for git SHA
@git_sha = File.exists?('/opt/houston/current/VERSION') && 
  File.read('/opt/houston/current/VERSION')[0,8]

# Tag master process with git SHA
tag @git_sha

# Log worker boot with git SHA
on_worker_boot do
  puts "[#{Process.pid}] Booting puma worker: git rev #{@git_sha}" if @git_sha
end

```

When the application goes down, nginx shows:
```
2016/04/12 10:48:40 [error] 24457#0: *13034501 connect() to unix:/tmp/houston.puma.sock failed (111: Connection refused) while connecting to upstream, client: XX.XXX.XXX.XX, server: houston.com, request: "GET /healthcheck HTTP/1.0", upstream: "http://unix:/tmp/houston.puma.sock:/healthcheck"
```
On the puma logs it shows a bunch of healthchecks requests (which are litterally rendering the text "CHECK") without showing any response:

<img width="625" alt="screen shot 2016-04-13 at 12 05 48 pm" src="https://cloud.githubusercontent.com/assets/2053347/14505938/2355137a-0170-11e6-84b5-d282cbce84cc.png">

As you can see above, all the requests are hanging...
This keeps on happening until we kill the puma pid on both servers.

A couple of things to note:
Our application relies on a couple of external services, with a timeout set on each of them (actually set within the application's application_controller as an around filter to stop processing once a request takes too long to complete). 
We also have some healthchecks pings (3-4 per second) running on each server to make sure that the application is alive and so far we weren't able to find a clear pattern pointing to a specific request that may have been triggering puma to become unresponsive.
puma version: 2.14.0

<img width="447" alt="screen shot 2016-04-13 at 11 42 50 am" src="https://cloud.githubusercontent.com/assets/2053347/14505187/ebb00f7c-016c-11e6-9ed1-8d5471321225.png">
This is the thread count and as you can see around 4am a bunch of threads were created and this is when the application crashed.

<img width="1101" alt="screen shot 2016-04-13 at 11 42 37 am" src="https://cloud.githubusercontent.com/assets/2053347/14505188/ebb2ea76-016c-11e6-8886-a1be7cdbd087.png">
This is the memory trend along with gc from within 8 hours

<img width="1059" alt="screen shot 2016-04-13 at 11 44 18 am" src="https://cloud.githubusercontent.com/assets/2053347/14505226/1c7cadfe-016d-11e6-8216-289bb99c55c7.png">
This is the same trend expanded to 3 days for general trend.

The general drop in the graphs above is essentially us killing the pid and restarting the main puma process. 
Is there a known issue with puma that may trigger this? I couldn't find anything in our source code that pointed to a memory leak though the memory seems to be climbing steadily. When attempting to reach the servers from an outside resource, all we get is a 503.

**Comment by dasomx77** [comment]
bump

**Comment by Eversilence** [comment]
Have the same issue with Puma. It is running on 3 servers, and after some time Puma starts to consume 100% of a CPU and become unresponsive as well. Only thing that helps is killing the pid and restarting.
Memory consumption doesn't grow, New Relic doesn't show anything suspicious, and Puma logs are clean as well.

**Comment by equivalent** [comment]
had similar issue after doing some code and gem changes, suddenly puma took ages to load (like 10 minutes till worker respond)

bumping puma version helped

```
-    puma (2.15.3)
+    puma (3.4.0)
```

**Comment by Eversilence** [comment]
@equivalent, thanks for advice, but this didn't solve the issue. I have tried to update Puma ( i had exactly the same version you had ) and Puma still hangs.

**Comment by equivalent** [comment]
@Eversilence   ...hmmm, this upgrade I was doing was a part of a Docker image change. One other thing I've done as a part of this change is that I've increased memory size for Docker container running Puma server, as it appeared to me that maybe Worker have not enough memory to worm up. But from the metrics you posted you should be fine. Maybe I had different issue than you had. 

one last thing I would suggest is to decrees number of Puma workers to and Threads and see if that helps. If you already done that then sorry, I'm out of option 

One last question:  Are you running you app directly on a server or in a Docker container ? if on Docker are you using docker-compose or maybe AWS Elastic Beanstalk `Dockerrun.aws.json` ?

**Comment by Eversilence** [comment]
@equivalent, I am pretty sure, that the problem is not with memory size, as I am running Puma on dedicated server with 16gb of RAM and Ubuntu 14.04. It is not in docker container. The only thing that I have noticed, is that it hang's up much faster when there is a big number of request ( usually, when RPM becomes 500+ ). I am still trying to debug this issue, but so far I have no results.
I have tried changing config of Puma ( add more/less threads and workers ) -- still no result.

If I will come up with something, I will let you guys know.

**Comment by evanphx** [comment]
The answer to these kinds of issues almost always lays in the kind of app it is. Are you using Actioncable or another solution that keeps connections open? When puma refuses connections, is it otherwise idle? What configuration are you using puma in? If you're using non-clustering, then it's possible for a gem that uses a C extension to become a bad actor and prevent all threads from running.

Basically, I need more information about the app and the circumstances to have a chance of figuring out what is going on.

**Comment by common-nighthawk** [comment]
@evanphx:
I believe I am having the same problem.  Puma creates more threads than I ask for and the memory consumption continues to grow until all the processes need to be killed.

I wrote up a full description on StackOverflow: http://stackoverflow.com/questions/36961700/puma-stops-running-for-rails-app-on-ec2-instance-with-nginx-using-capistrano-ca

My rails application is pretty simple--nothing that should keep a connection open.  Gemfile here: https://github.com/common-nighthawk/picturebookmylife-2.0/blob/master/Gemfile.  Puma config here: https://github.com/common-nighthawk/picturebookmylife-2.0/blob/master/config/deploy.rb.

I don't know if this an 'Issue' or due to a lack of understanding on my part.  But I truly appreciate any help.

**Comment by evanphx** [comment]
@common-nighthawk Your app is the primary unknown here. Can you tell me about it? Is it using long running connections (SSE, Actioncable, etc)? What happens when you set the threads to `1, 1`? Perhaps you have some code that is not thread safe and it's become confused and is locking up.

**Comment by common-nighthawk** [comment]
@evanphx Thank you so much for looking in this.  I _really_ appreciate it.

My app is a standard CRUD app.  It has nothing fancy, including no long running connections.  I think it's pretty unlikely something in my rails app is causing a problem.  The entire project is available here: https://github.com/common-nighthawk/picturebookmylife-2.0

I tried setting the threads to `1,1` and nothing changed.  Here is a screenshot of Puma running on 6 different processes:
![puma htop](http://i.imgur.com/EWTLq6Q.png?1)

Any ideas?  I'm confused because it feels like my app and configuration are pretty straightforward, so would love to get to the root problem.

**Comment by evanphx** [comment]
Oh. You know what, I just realized. Those aren't worker processes, those are the threads in the worker! Your top program is just confusing. Can you gist the output of `ps ax`? I'm betting it doesn't show those because they're threads, not processes.

**Comment by evanphx** [comment]
@common-nighthawk I also just realized that probably doesn't matter since you're still having troubles, regardless of if those are threads or not.

How can I replicate the issue using your repo? Do you just let it sit there, no requests? Or is there a pattern I can use to recreate the problem.

**Comment by evanphx** [comment]
@common-nighthawk As for the memory, there are no known memory leaks in puma, despite many people thinking there are over the years. They've always been either the app or ruby itself. What version of ruby are you on?

**Comment by common-nighthawk** [comment]
@evanphx 
You are exactly right.  Here is the output of `ps ax`: https://gist.github.com/common-nighthawk/48ba336df4ae06d7ace10e788cb85731

When I run htop in "tree" mode, it's clear the six threads belong to the one worker.  But shouldn't `threads 1,1` cap the maximum number of threads?

I don't think there are any memory leaks in puma.  My memory problem is just that I'm getting more threads than I want.

As for replicating the issue--yes, this problem happens right from the start without any requests.  Here is my puma.rb file: https://gist.github.com/common-nighthawk/e910cb67d6cc4aeff8274657a734301a

**Comment by evanphx** [comment]
The threads command sets the number of threads in the thread pool to
service requests. There are other threads used to handle other tasks you're
seeing.

**Comment by fedeest** [comment]
I  have this same problem. I think this is an issue with Puma workers.

I have set one worker for the app. After about 5 minutes of inactivity, the app hangs as explained here before and can only work again after restarting Puma.
If I set the workers to 2, after 5 minutes of inactivity the app works, BUT if I then wait another 5 minutes, the app hangs.

Based on this I assume it must be something related to workers not being able to restart or something.

**Comment by common-nighthawk** [comment]
@evanphx 
thank you so much!  i think its so cool the person that wrote puma helped me look into my issue.

everything you said makes sense now.  ill summarize what i learned, should anyone else make it to this page with "puma stops working" problems.

- if Puma stops working, make sure you have enough memory to handle to number of workers and threads that you specified.  each Puma process is pretty expensive.
- if you set 0 workers, Puma will not run in cluster mode.  if it recommended to run MRI using cluster mode.
- threads are set per cluster.  if you have 2 works and 0,8 threads that means you will have two works and each will have between 1 and 8 threads.
- Puma uses processes in addition to the threads.  Puma has a PID for the parent process.  if you are using cluster mode, it has a PID to manager the clusters.  if you are using cluster mode, it also has PID for each cluster.  then, there are a fixed number of PIDs to run other tasks (per cluster).  without cluster mode, there are 5 fixed PIDs.  with cluster mode, there are 7 fixed PIDs.
- this is all to say--if you see more processes than you expect, this is why.  also--when you add a new worker you add a significant amount of expensive processes.  make sure you have the space.

i have a small app, and things seem to be working nicely with 1 worker and min=1, max=4 threads.  having a max of 8 threads looks to be what kept killing puma for me.

**Comment by machty** [comment]
This thread is very helpful.

What are the implications on Puma / concurrency for apps that use ActionCable/SSE or otherwise keep connections open?

**Comment by evanphx** [comment]
Minor clarification:

* Threads are set per worker, not per cluster. If you set it to workers: 2, threads: 8 you'll have 16 total threads in the system.

@machty You need more threads basically. I'm currently researching ways to make that not be such a sticking point though.

**Comment by bbozo** [comment]
The thing with Puma is that it's the only mainstream project that encourages the use of threading in MRI Ruby (well, anyway, Heroku encourages).

This is why we sometimes see statements from people working on Puma about how people think that Puma has various kinds of issues, while the problem is elsewhere, and it is, and it affects only Puma :P

"We" have discovered and fixed in the past some very freaky and nasty Ruby GC issues on heavy duty use of threads in Ruby MRI with some freaky corner cases (remember http://blog.skylight.io/hunting-for-leaks-in-ruby/) and who is to say this is not the last of such freaky issues that people attribute to Puma?

Try disabling threading for a while, see how it goes, and let us know, maybe the rabbit lies there, again

**Comment by common-nighthawk** [comment]
Thanks to @bbozo for writing up an even more extensive answer on SO: http://stackoverflow.com/questions/36961700/puma-stops-running-for-rails-app-on-ec2-instance-with-nginx-using-capistrano-ca/39835783

Hope this helps others going forward 😄.

**Comment by dthomaz** [comment]
Hello, 
I have a service running puma 2.8.1 with setting **threads 4, 16**
A process:
```
[deploy@production ~]$ ps ax | grep 9199
 9199 ?        Sl     6:16 puma 2.8.1 (unix:///data/apps/aquanetix/shared/sockets/puma.sock,unix:///data/apps/aquanetix/current/tmp/sockets/aquanetix-puma.sock)
11262 pts/1    S+     0:00 grep --color=auto 9199
```

keeps growing in use of memory and also sometimes (once per day or once every 2 days) ends up blocking cpu (>100%) and users cannot access the web application (Gateway Time-Out 504).
I need to restart puma to get users using the service again.
Memory use goes from approx 2% to 30-40% in 24h and continues growing until the server is blocked.  At some point sometimes with 30% sometimes with >70% mem usage cpu usage peaks and stays high for long enough so users cannot use the service.
From the above discussion, should I set threads to smaller values?

Thank you for your help.

**Comment by common-nighthawk** [comment]
@dthomaz--
It's difficult to know much.  Evan seems prone to saying "Your app is the primary unknown here", which I like.

On the most basic level, threads are per worker.  How many workers do you have?  You set threads to be min 4, max 16.  But if you have 5 workers, those numbers are actually 5x.  Also--you'll probably want at least 1 worker so puma is running in cluster mode.

Nothing in your comment seems off.  It is possible you are running out of memory for valid reasons--resources consume memory.

There are two things to try: 1. reduce the number of workers and threads.  Try one worker and 1,4 threads maybe.  Your app will be slower if you have lots of concurrent users, but it should stop breaking.  2. buy a more powerful server.  You can always pay for more memory and processing power.  I would try 1, and if that works and you need to speed up the app, then go with 2.

This is the most basic answer.  If that doesn't help, you'll need to look into things like "Are you using Actioncable or another solution that keeps connections open?"  And it's always possible you're using a Gem with a memory leak.  But altering the puma setting is the more likely fix.

**Comment by dthomaz** [comment]
@common-nighthawk 
Thank you for the reply.  
I am not 100% sure of how many workers are 'setup'... If the workers are those setup with the line:
```
# Resque workers
set :workers, { "reporting" => 3, "periodic" => 1 }
```
then the total is 4.  Is this correct?.. or resque workers have nothing to do with puma workers? (apologies for the ignorance...)

If however this is correct then I could start by reducing total workers to 3, and if not enough to 2, etc... Correct?

Thanks again.

**Comment by common-nighthawk** [comment]
Pretty sure resque workers have nothing to do with puma workers.  I usually have a puma.rb file where I set up the dedicated webserver configuration.

`threads 1,4`
`workers 1`

The readme has a section dedicated to setting up the configuration: https://github.com/puma/puma#configuration

As far as reducing the number by one until it's stable: that backoff plan sounds good to me.

Lastly, I found running htop in tree mode (just hit t to toggle) to be helpful.  It allows you to see the parent puma process, its children (workers), and their children (threads).  Which was helpful for confirming numbers of workers, etc.

**Comment by dthomaz** [comment]
Hello again @common-nighthawk . My puma.rb file is the following:
```
rack_env = padrino_env = ENV['PADRINO_ENV'] || ENV['RACK_ENV'] || 'production'

threads 4,16

bind  "unix:///data/apps/aquanetix/current/tmp/sockets/aquanetix-puma.sock"
pidfile "/data/apps/aquanetix/current/tmp/puma-pid"
state_path "/data/apps/aquanetix/current/tmp/sockets/puma.state"

activate_control_app
```
The fact that no workers line appears means that by default there is only one? Or this will be defined somewhere else?

**Comment by common-nighthawk** [comment]
It looks like 0 workers are set by default.  There is a link to this file in the readme.
https://github.com/puma/puma/blob/master/lib/puma/configuration.rb

Maybe that's your problem?  It is recommended to run MRI using cluster mode.  (If you have 0 workers, you are not running cluster mode.)  I would try setting the workers to 1 in your puma.rb.

**Comment by dthomaz** [comment]
Will try that and feedback over this weekend on the progress of memory and cpu usage.  Thanks again @common-nighthawk

**Comment by dthomaz** [comment]
Hello again,
I set workers to 2, kept threads 4,16 and my memory leak issue remains.
From last night when I deployed the two worker processes have steadily increased in %mem use to values of 19% and 16%. No signs of these coming down, only up.
Is it possible that the reason the memory increases continually is because we don't close sessions and with time, more users will just keep opening more sessions? Or puma would sort this itself?

**Comment by manojpogadadanda** [comment]
I have been working on a rails application for the past four months. Suddenly one-day puma server stops responding to the requests. Here is what I see in the terminal:
```
$ rails s  
=> Booting Puma  
=> Rails 5.1.7 application starting in development   
=> Run `rails server -h` for more startup options  
 Puma starting in single mode...  
 Puma version: 5.5.2 (ruby 2.6.3-p62) ("Zawgyi")  
  Min threads: 5  
  Max threads: 5  
  Environment: development  
          PID: 12446  
 Listening on http://127.0.0.1:3000  
 Listening on http://[::1]:3000  
Use Ctrl-C to stop   
Started GET "/" for ::1 at 2021-11-10 12:28:58 +0530  
Started GET "/recommendations" for ::1 at 2021-11-10 12:29:20 +0530  
Started GET "/" for ::1 at 2021-11-10 12:29:39 +0530  
Started GET "/" for ::1 at 2021-11-10 12:29:40 +0530 
```
I tried many things like changing the port, making sure that the rails version in my local and gemfile are the same, trying with other ruby versions, uninstalling and reinstalling ruby and rails in local. Tried keeping binding.pry in the application controller's index action but that not getting hit. I am not able to exit from that point, the server gets stuck there. There are no recent changes in my application.

Can anyone suggest to me what might be the problem?
