### ISSUE TITLE
Incorrect parsing of Basic Authorization credentials when multiple credentials encoded don't end with `=`

### ISSUE THREAD

**Issue by shekibobo** [puma/puma#964]
Discovered a strange bug.

If multiple headers (in my case duplicate headers) are sent in a request, and the encoded credentials don't end in an `=`, the credentials don't seem to be properly decoded. I discovered this when an HTTP client was mistakenly adding a second `Authorization` header and certain users couldn't log in. In cases where the credentials end in `=`, the parsing strategy successfully decodes the credentials (though I'm not sure which one).

For example:

If I have a user with email: `user@example.com` and password `FourFourFourFour`, the credentials generated are `Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy`. If I add two `Authorization` headers with that, Devise is unable to find the user via the `current_user` method. 

However, if I have a user `user@example.com` and password `FourFourFourFours`, the credentials generated are `Basic dXNlcjJAZXhhbXBsZS5jb206Rm91ckZvdXJGb3VyRm91cnM=`. If I add two `Authorization` headers with that, Devise finds the expected user.

Thin handles this the same way regardless of the last character of the encoded credentials.

**Comment by evanphx** [comment]
What do you think the puma bug is? I'm not following.

**Comment by shekibobo** [comment]
Here's the example using puma as a rails server.

If I have a controller like this:

```ruby
class ItemController < ActionController::Base
  def show
      def show
        pp request.headers["HTTP_AUTHORIZATION"]
        pp ActionController::HttpAuthentication::Basic.decode_credentials(request)
      end
    end
  end
end
```

Here's what I get if I send duplicate headers with encoded credentials:

```
# user@example.com:FourFourFourFour
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy"
"user@example.com:FourFourFourFour\x05\xAB\"q\xD5\xCD\x95\xC9\x01\x95\xE1\x85\xB5\xC1\xB1\x94\xB9\x8D\xBD\xB4\xE9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD5"

# user@example.com:FourFourFourFou
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U=, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U="
"user@example.com:FourFourFourFou"

# duplicate headers, user@example.com:FourFourFourFour and user@example.com:FourFourFourFou
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U="
"user@example.com:FourFourFourFour\x05\xAB\"q\xD5\xCD\x95\xC9\x01\x95\xE1\x85\xB5\xC1\xB1\x94\xB9\x8D\xBD\xB4\xE9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD4"

# duplicate headers, user@example.com:FourFourFourFou and user@example.com:FourFourFourFour
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U=, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy"
"user@example.com:FourFourFourFou"
```

The same examples using thin as a server:

```
# user@example.com:FourFourFourFour
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy"
"user@example.com:FourFourFourFour\x05\xAB\"q\xD5\xCD\x95\xC9\x01\x95\xE1\x85\xB5\xC1\xB1\x94\xB9\x8D\xBD\xB4\xE9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD5"

# user@example.com:FourFourFourFou
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U=, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U="
"user@example.com:FourFourFourFou"

# duplicate headers, user@example.com:FourFourFourFour and user@example.com:FourFourFourFou
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U="
"user@example.com:FourFourFourFour\x05\xAB\"q\xD5\xCD\x95\xC9\x01\x95\xE1\x85\xB5\xC1\xB1\x94\xB9\x8D\xBD\xB4\xE9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD5\xC9\x19\xBD\xD4"

# duplicate headers, user@example.com:FourFourFourFou and user@example.com:FourFourFourFour
"Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3U=, Basic dXNlckBleGFtcGxlLmNvbTpGb3VyRm91ckZvdXJGb3Vy"
"user@example.com:FourFourFourFou"
```

And now that I've tested these examples, it looks like the issue is more likely with Rails than with Puma. I was pretty certain the examples worked when using thin before, but it was still unclear what the actual problem was. I'll move this issue to Rails unless you happen to see something that I'm missing.

Code for handling duplicate headers is here for reference, but it looks like Puma is handling this as designed: https://github.com/puma/puma/blob/4ca81231c42828980dad26cfe21e47ba527d8be9/ext/puma_http11/puma_http11.c#L202-L212
