### ISSUE TITLE
when use unix socket, how puma deal with it when puma restart

### ISSUE THREAD

**Issue by Baozi2** [puma/puma#965]
when  puma  listen unix socket, how it deal  with  unix socket when puma. 
Directly delete it?
if delete it, the  data in  unix socket will  lose?
Thank  you

**Comment by evanphx** [comment]
Data isn't saved inside a unix socket, so deleting it doesn't lose any data. Puma removes the unix socket file when it exits.

**Comment by Baozi2** [comment]
thank  you
