### ISSUE TITLE
SSL not available in this build

### ISSUE THREAD

**Issue by promentus** [puma/puma#971]
Hi,
I have a problem with Puma (3.4.0) with SSL on OS X El Capitan. I get this error message: 

"SSL not available in this build (StandardError)" when I start the server with SSL on localhost:

$ puma -b 'ssl://127.0.0.1:3000?key=/Users/myusername/sites/mysite/server.key&cert=/Users/myusername/sites/mysite/server.crt'

I can't find out how to solve this. Any ideas?

**Comment by stmarier** [comment]
Hi,  I ran into this issue earlier this morning,  I took a look at https://github.com/puma/puma/blob/master/ext/puma_http11/mini_ssl.c#L12-L18 because the error message is in this file.

In my case, I didn't have any of these header files.  I had to install the openssl development tools, gem uninstall puma, and then gem install puma.  I don't really know a lot about ruby, or gems, so there might be a better way to trigger a 'recompilation' after this #ifdef evaluates to true.

With yum, I think the package name is "openssl-devel".  I'm not sure about apt or any other distros.  Hope this helps or puts you on the right track.

**Comment by evanphx** [comment]
@promentus @stmarier is correct, you're missing the proper OpenSSL headers. New versions of OS X do not ship with them, so if you'd like SSL support to work, you'll need to install from elsewhere, perhaps homebrew.

**Comment by promentus** [comment]
I have openSSL installed but after your suggestion to uninstall Puma, install openssl and reinstall Puma it works!
Thanks big time!

**Comment by fagiani** [comment]
To save some eventual struggle with openssl linking, I found [here](https://github.com/phusion/passenger/issues/1630#issuecomment-173118784) some useful command sequence:
```
brew install openssl
ln -s /usr/local/Cellar/openssl/1.0.2c/include/openssl /usr/local/include/openssl
gem uninstall puma
gem install puma
```

Hope it helps!

**Comment by djones** [comment]
```
gem install puma -v 'YOUR VERSION' -- --with-cppflags=-I/usr/local/opt/openssl/include --with-ldflags=-L/usr/local/opt/openssl/lib
```

Fixed it for me.

**Comment by flah00** [comment]
If you want to fix it across the board, I think this will persist across all of your projects

    bundle config --global build.puma \
      --with-cppflags=-I/usr/local/opt/openssl/include \
      --with-ldflags=-L/usr/local/opt/openssl/lib

**Comment by NafaaBout** [comment]
On `Ubuntu 16.04` I installed `libssl-dev` and it works fine. 
```
sudo apt install libssl-dev
gem install puma
```

**Comment by gregoryrpitts** [comment]
In response to fagiani's comment about symlinking, make sure you aren't just copying and pasting the command and have the proper symlink. Example, mine was 
`ln -s /usr/local/Cellar/openssl/1.0.2p/include/openssl /usr/local/include/openssl`

**Comment by vabburi86** [comment]
I am facing this in Windows. Installed Openssl and reinstalled puma gem, even then getting below error.

>rails s
=> Booting Puma
=> Rails 6.0.3.2 application starting in development
=> Run `rails server --help` for more startup options
**************************************************
⛔️ WARNING: Sidekiq testing API enabled, but this is not the test environment.  Your jobs will not go to Redis.
**************************************************
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 4.3.5 (ruby 2.6.6-p146), codename: Mysterious Traveller
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://[::1]:3000
* Listening on tcp://127.0.0.1:3000
Exiting
Traceback (most recent call last):
        22: from bin/rails:9:in `<main>'
        21: from bin/rails:9:in `require'
        20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<top (required)>'
        19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
        18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
        17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        15: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:39:in `start'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/rack/handler/puma.rb:73:in `run'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/launcher.rb:172:in `run'
         7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/single.rb:98:in `run'
         6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/runner.rb:161:in `load_and_bind'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:90:in `parse'
         4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:90:in `each'
         3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:158:in `block in parse'
         2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/binder.rb:158:in `new'
         1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/minissl/context_builder.rb:6:in `initialize'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/puma-4.3.5/lib/puma/minissl/context_builder.rb:6:in `check': SSL not available in this build (StandardError)

**Comment by MSP-Greg** [comment]
@vabburi86

What's the output of:
```
ridk exec pacman -Q openssl
```

Should be similar to:
```
openssl 1.1.1.g-3
```

**Comment by nicolasgoris** [comment]
Hi I am working on a windows device and I am having troubles with the SSL part as well.
I get the following error:
``` 
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/puma-5.1.1/lib/puma/binder.rb:220:in 'block in parse': 
Puma compiled without SSL support (RuntimeError)
 ```
This after I changed my puma.rb file to include the following:
```
if ENV.fetch("RAILS_ENV") == 'development'
  localhost_key = "#{File.join('config', 'localhost.key')}"
  localhost_crt = "#{File.join('config', 'localhost.crt')}"
  # To be able to use rake etc
  ssl_bind '0.0.0.0', 3000, {
    key: localhost_key,
    cert: localhost_crt,
    verify_mode: 'none'
  }
end
```
I already uninstalled and reinstalled puma and the output of your command @MSP-Greg is the same as you mentioned.

**Comment by MSP-Greg** [comment]
@nicolasgoris

Sorry, wrong command above, try:
```
PS C:\> ridk exec pacman -Q mingw-w64-x86_64-openssl
mingw-w64-x86_64-openssl 1.1.1.i-1
```
If no output, then:
```
ridk exec pacman -S mingw-w64-x86_64-openssl
```
and repeat above...

**Comment by nicolasgoris** [comment]
```
>ridk exec pacman -Q mingw-w64-x86_64-openssl
mingw-w64-x86_64-openssl 1.1.1.h-1
```
But still gives me the same error when running the rails server.

**Comment by MSP-Greg** [comment]
Does the following output true?
```
ruby -rpuma -e "puts Puma.ssl?"
```

**Comment by nicolasgoris** [comment]
Nope it returns false 👎

**Comment by MSP-Greg** [comment]
Did you install Puma with bundler or rubygems?

**Comment by nicolasgoris** [comment]
I used the gem install command.
I did the uninstall again and installed again and now it seems to be working...

**Comment by MSP-Greg** [comment]
Sorry, I wasn't really clear.  If you needed to do `ridk exec pacman -S mingw-w64-x86_64-openssl`, that installed the needed OpenSSL libraries, headers, etc, but you would still need to re-install the gem.  Maybe?

Regardless, working now...

**Comment by nicolasgoris** [comment]
> Sorry, I wasn't really clear. If you needed to do `ridk exec pacman -S mingw-w64-x86_64-openssl`, that installed the needed OpenSSL libraries, headers, etc, but you would still need to re-install the gem. Maybe?
> 
> Regardless, working now...

Yeah, so running that command inclusive with running the reinstallment of the gem!

**Comment by MSP-Greg** [comment]
Puma is what is often called an extension gem, in that it contains c/c++ code that needs to be compiled.  Running `ridk exec pacman -S mingw-w64-x86_64-openssl` installs the files needed for compiling.

Windows Rubies contain the OpenSSL dll's needed for Puma to run (see `bin\ruby_builtin_dlls`), but not the files needed to compile.  That's the reason Puma has the two constants, `Puma::MiniSSL::OPENSSL_LIBRARY_VERSION`, and `Puma::MiniSSL::OPENSSL_VERSION`, which identify the OpenSSL versions that Puma is running with and compiled with, respectively.

Normally, as long as the numeric OpenSSL version is the same, everything should be okay.  Or, running with `1.1.1e` and compile with `1.1.1i` should be fine.  Note that OpenSSL 3.0 will change to semantic versioning...
