### ISSUE TITLE
Puma occasionally leaks a Puma::Client and associated Rails controller

### ISSUE THREAD

**Issue by Botje** [puma/puma#978]
Occasionally, Puma forgets to clean up a `Puma::Client` object, causing it and the associated Rails controller to remain in memory.
I've managed to reproduce the problem on a fresh Rails project, which can be found at https://github.com/Botje/test-puma-leak .

This project prints the number of active `Puma::Client` and Rails controllers every five seconds.
After a large number of requests, one `Puma::Client` remains behind, even after garbage collection.
This is on OSX 10.10.5, with Ruby 2.2.5 and Rails 4.2.6.
I went as far as dumping the Ruby heap, but that just shows that a Puma thread directly references an array with one `Puma::Client` object in it.

I'm reporting this because I think it is a bug in Puma, but I'm willing to chase any other pointers you can give me, and help with debugging in any way I can.

**Comment by anshul** [comment]
@Botje I am also exploring some memory leaks that appear to come from puma.  Based on #342, it may be worth testing if you can replicate this with ruby 2.3.1...

**Comment by Botje** [comment]
Yes, I can also reproduce it with ruby 2.3.1.

**Comment by evanphx** [comment]
Did you have something in the real world that was made you think there might be a leak?

The reason I ask is because the GC in Ruby 2.3 is lazy now, so GC.start doesn't really perform a full GC anymore. As a result, there might not be a leak, it's just an object that is garbage but not yet collected.

**Comment by evanphx** [comment]
Ok, so I used http://ruby-doc.org/stdlib-2.1.0/libdoc/objspace/rdoc/ObjectSpace.html#method-c-dump_all to look at all the live objects in the system. While `ObjectSpace.each_object` is finding a `Puma::Client` and `ActiveController::Base`, they're not live objects. You're seeing garbage objects that just haven't been overridden yet.
