### ISSUE TITLE
Puma freeze on startup when first request is a websocket

### ISSUE THREAD

**Issue by anykeyh** [puma/puma#979]
Hello, 

Not sure it's related to puma or to action-cable / websocket, but I've a strange issue happening for now in development (not sure about production yet).

The step to reproduce are simple:

- Launch the server (in my case using `rails s`)
- Open the website using actioncable
- Stop the server and launch it again
- Wait for auto-reconnect of action cable
- Refresh your app

And TADA, broken :(

Here what is inside my console:

```
[44646] Puma starting in cluster mode...
[44646] * Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
[44646] * Min threads: 1, max threads: 8
[44646] * Environment: development
[44646] * Process workers: 1
[44646] * Phased restart available
[44646] * Listening on tcp://localhost:3000
[44646] Use Ctrl-C to stop
[44646] * Starting control server on unix:///var/folders/sh/64tpb9ys67l6smwkqlmhz5pr0000gn/T/puma-status-1462691832716-44646
[44646] - Worker 0 (pid: 44649) booted, phase: 0
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Started GET "/live/" [WebSocket] for ::1 at 2016-05-08 15:17:14 +0800
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Registered connection (08657a35-aca7-404c-b44c-84ca3793d07c)
^C[44646] - Gracefully shutting down workers...
```

Note the ^C (Try to cancel, can spam nothing will happens)

The only way for me to kill is to use `kill -9 PID`, and I can't get any stacktrace.

**Comment by cleverlemming** [comment]
Same issue here. Assets stop loading and application hangs with no error messages. Happens roughly 4 out of 5 times after Ctrl-C & rails s. Tried varying load order of javascript assets. Doesn't happen with Thin.
```
=> Booting Puma
=> Rails 5.0.0.rc1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.4.0 (ruby 2.3.0-p0), codename: Owl Bowl Brawl
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started GET "/cable" for ::1 at 2016-06-13 17:43:23 -0600
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Started GET "/cable/" [WebSocket] for ::1 at 2016-06-13 17:43:23 -0600
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
```

**Comment by gamut** [comment]
I think this issue has returned in 3.10.  I just experienced exactly the same behaviour.  Downgrading to 3.9.1 resolved it.

**Comment by nateberkopec** [comment]
@gamut It can't be exactly the same because this was a Rails bug, so the Puma version shouldn't have any effect. Please open a new issue.
