### ISSUE TITLE
Drop TLS 1.0?

### ISSUE THREAD

**Issue by chewi** [puma/puma#980]
We're trying to pass a PCI DSS audit and we noticed that Puma is hardcoded to allow TLS 1.0. It's not completely outlawed yet (2 years left) but you do have to state why you are using it and have mitigations in place. We'd rather just rule it out entirely. Given that you generally shouldn't have Puma directly exposed to the Internet, I don't see why old clients need to be supported. The headline casualties are Android 4.3 (Jelly Bean) and IE7. Of course, it could be made configurable but that's non-trivial. :wink:

**Comment by evanphx** [comment]
I'll likely add code to remove it being an option in another year. There was someone asking about the ability to override the cipher settings as well. I might do that.

**Comment by chewi** [comment]
Happy new year! Our next audit is coming up. What's the current feeling about this?
