### ISSUE TITLE
Puma started with control server not responding to restart

### ISSUE THREAD

**Issue by awlamb** [puma/puma#982]
When starting puma with the control server, everything seems fine:

`bundle exec puma -C config/puma.rb --control tcp://127.0.0.1:9293 --control-token foo`

It responds to stop and stats. However, nothing happens when you you call the restart command. The server responds with 'ok', but if you look at the puma server console, there's no change. Is it restarting but there's no notification? It might make sense for console messages to be displayed if the environment was in development mode

**Comment by evanphx** [comment]
What's in your config?

**Comment by evanphx** [comment]
I'm testing this and I'm unable to replace the issue. Please reply if you're still having this problem.
