### ISSUE TITLE
Puma is running on development env when is included just in production group

### ISSUE THREAD

**Issue by alagos** [puma/puma#983]
I've been using `thin` as development server and now that the app will be released to production, I've added `puma` as [Heroku recommends](https://devcenter.heroku.com/changelog-items/594). Some (maybe?) relevant lines of my `Gemfile`:

    source 'https://rubygems.org'
    ruby '2.2.2'
    
    gem 'rails', '>= 5.0.0.rc1', '< 5.1'
    gem 'thin'
    group :production do
      gem 'puma' # 3.4.0
      gem 'rails_12factor'
    end

The problem now is, when I run the app locally, is using `puma` instead of `thin` as web server, regardless `puma` is just included in `production` group.

    rails s
    => Booting Puma
    => Rails 5.0.0.rc1 application starting in development on http://localhost:3000
    => Run `rails server -h` for more startup options
    [7336] Puma starting in cluster mode...
    [7336] * Version 3.4.0 (ruby 2.2.2-p95), codename: Owl Bowl Brawl
    [7336] * Min threads: 5, max threads: 5
    [7336] * Environment: development
    [7336] * Process workers: 2
    [7336] * Preloading application
    [7336] * Listening on tcp://localhost:3000
    [7336] Use Ctrl-C to stop
    [7336] - Worker 0 (pid: 7350) booted, phase: 0
    [7336] - Worker 1 (pid: 7360) booted, phase: 0

Any thoughts what it could be? Thanks in advance

**Comment by t27duck** [comment]
I'm thinking this is more of an issue with Rails than it is with puma. Rails 5 introduced puma as the default web server for development mode. Perhaps since the gem is available Rails is loading it up regardless.

**Comment by alagos** [comment]
@t27duck nope, the same story
```
➜ bundle exec rails s
=> Booting Puma
=> Rails 5.0.0.rc1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
[24367] Puma starting in cluster mode...
[24367] * Version 3.4.0 (ruby 2.3.1-p112), codename: Owl Bowl Brawl
[24367] * Min threads: 5, max threads: 5
[24367] * Environment: development
[24367] * Process workers: 2
[24367] * Preloading application
[24367] * Listening on tcp://localhost:3000
[24367] Use Ctrl-C to stop
[24367] - Worker 0 (pid: 24381) booted, phase: 0
[24367] - Worker 1 (pid: 24392) booted, phase: 0
```
At the end I gave up and I started to use `puma` locally

**Comment by evanphx** [comment]
This is really a bundler issue, not something that puma has any control over. But basically I believe rails hardcodes using puma in dev mode now.

**Comment by 1Rhino** [comment]
Same issue.
`Rails (5.0.2).  puma (3.8.2)`.  (Puma so slow debugging with `better_errors`, `binding_of_caller`)
A trick that worked for me.
```ruby
if ENV['RAILS_ENV'] == 'production'
  gem 'puma', '~> 3.8'
else
  gem 'thin'
end
```

**Comment by kenan-memis** [comment]
the config/puma.rb file has a line:

```
# Specifies the `environment` that Puma will run in.
environment ENV.fetch("RAILS_ENV") { "development" }
```

So, although you put it to production gem list, it fetches the dev environment

**Comment by olivierlacan** [comment]
@kenan-memis No, the `"development"` in the block after `ENV.fetch` is a fallback for the `Enumberable#fetch` method. Think of it as ENV["RAILS_ENV"] || "development". The only way this gets set to `"development"` is if `ENV["RAILS_ENV"]` is returning `nil`, which is possible but unlikely.
