### ISSUE TITLE
[Tutorial/Document] More tutorial or document about how to use puma?

### ISSUE THREAD

**Issue by 1c7** [puma/puma#985]
I can't find any great tutorial about puma on google.
is because I got wrong keyword? or just not many tutorial about puma?

Thanks

**Comment by netwire88** [comment]
I don't understand the instructions here. I am using earlier version of Puma + Heroku and already have a` puma.rb` file. Are we supposed to change it? What's the new puma-heroku lib? How do we even install it?

**Comment by evanphx** [comment]
@1c7 What kind of information are you looking for? Your question almost makes it sound like it's not clear what the puma software even does.

**Comment by evanphx** [comment]
@netwire88 Not sure what your referring to, please open a separate issue.

**Comment by 1c7** [comment]
@evanphx 
Maybe put a longer version tutorial, FAQ, common error section on http://puma.io/?
how to deploy puma with nginx, how to config them, stuff like that?
actually these info in README.MD can be break into a lot little piece and put into  http://puma.io/
Good example I think is Jekyll  https://jekyllrb.com/
their document just feel better.


Thanks for you guys write puma. awesome software.
open source rock!
:D

**Comment by evanphx** [comment]
I'm going to be a doing a bunch of work on puma.io very soon so I'll definitely do this!
