### ISSUE TITLE
Puma is about 20 times slower on jruby compared to mri ruby-2.2.2

### ISSUE THREAD

**Issue by Zloy** [puma/puma#988]
I try to estimate the simplest Sinatra (1.4.7) app performance with Puma (3.4.0). I use [wrk](https://github.com/wg/wrk) (4.0.2) to stress that app. Everything is run on my Dell  notebook with Intel(R) Core(TM) **i5-3317U CPU @ 1.70GHz** and **8Gb** RAM under Ubuntu 14.04 (64 bit)

with ruby-2.2.2-p95 it shows **7317** rps with 100% of all 4 cores load
with jruby-1.7.19 it shows **385** rps with 40% of all 4 cores load
 
```
# app.rb
require 'sinatra'

set :logging, nil

get '/hello' do
    "Hello World!"
end
```

```
# config/puma.rb
environment production
quiet
```

```
# config.ru
require './app'

run Sinatra::Application
```

When I run that app with ruby-2.2.2
```
> puma -C config/puma.rb -w 4
> wrk -d 60s -t 16 -c 500 http://localhost:9292/hello
Running 1m test @ http://localhost:9292/hello
  16 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.76ms   19.06ms 204.07ms   87.91%
    Req/Sec     0.92k     1.16k    5.08k    84.75%
  439717 requests in 1.00m, 77.58MB read
Requests/sec:   7317.10
Transfer/sec:      1.29MB
```

When I run that app with jruby-1.7.19
```
> puma -C config/puma.rb
> wrk -d 60s -t 16 -c 500 http://localhost:9292/hello
Running 1m test @ http://localhost:9292/hello
  16 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    41.44ms    6.19ms 232.17ms   93.90%
    Req/Sec   129.17    117.81   363.00     68.78%
  23155 requests in 1.00m, 4.09MB read
  Socket errors: connect 0, read 124, write 0, timeout 0
Requests/sec:    385.28
Transfer/sec:     69.64KB

> java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```

Why is that? **Shouldn't Puma perform better on jruby than on mri ruby?**

**Comment by evanphx** [comment]
I'm not really able to give you much comment here. The code used is effectively identical, perhaps @headius can provide some insight.

**Comment by jjb** [comment]
JRuby will take much longer to boot up and so the first request will seem to take much longer and affect the rest of the test. Maybe add a `curl http://localhost:9292/hello` before each invocation of `wrk`, to normalize the results a bit.

**Comment by Zloy** [comment]
@jjb I tried several times not stopping puma. The results are pretty same. Can you try this test?

**Comment by evanphx** [comment]
I'd suggest you discuss this with the jruby folks, this isn't a puma issue given the common code.
