### ISSUE TITLE
Puma restart failing

### ISSUE THREAD

**Issue by hakkiplaten** [puma/puma#990]
In Puma 3.4.0 (ruby 2.2.4-p230), why won't `sudo puma restart` work, while `sudo puma stop && sudo puma start` does?

`sudo puma restart` says `Command restart sent success` but then nothing happens. I'm using FreeBSD's startup system: https://freebsd.org/doc/en/articles/rc-scripting/rcng-dummy.html:

```sh
. /etc/rc.subr

name="myapp"
name_home="/home/www/${name}"

rcvar="${name}_enable"

pumactl="/usr/local/bin/pumactl"

start_cmd="cd ${name_home} && sudo ${pumactl} start"
restart_cmd="cd ${name_home} && sudo ${pumactl} start && sudo ${pumactl} stop"
# restart_cmd="cd ${name_home} && sudo ${pumactl} restart"
stop_cmd="cd ${name_home} && sudo '${pumactl} stop'"

load_rc_config $name
run_rc_command "$1"
```

**Comment by evanphx** [comment]
What happens when you run the commands in a normal shell, not inside a rc script?

**Comment by evanphx** [comment]
If this is still an issue, please reopen.
