### ISSUE TITLE
Specifing SSL Ciphers to use

### ISSUE THREAD

**Issue by bararchy** [puma/puma#996]
Is there a way to pass on a String like in Ruby's SSL Cipher Context class that will make the server use only specific settings ? 

for example in Ruby:

``` ruby
ssl_context = OpenSSL::SSL::SSLContext.new
ciphers = '!ADH:!RC4:!aNULL:!MD5:!EXPORT:!SSLv2:HIGH'
ssl_context.ciphers = ciphers
```

**Comment by evanphx** [comment]
At present, there is not, no.

**Comment by mirceal** [comment]
Would you consider taking a PR for this?

**Comment by nateberkopec** [comment]
> Would you consider taking a PR for this?

I think so, yes.

**Comment by mirceal** [comment]
Can we please reopen the issue?

**Comment by mirceal** [comment]
PR is being prepared and should land shortly

**Comment by mirceal** [comment]
May we get some feedback on https://github.com/puma/puma/pull/1476 and on the test failures?
From the looks of it it does not seem to be related to the code that is introduced. How can we run the whole test suite locally before submitting the PR to ensure
