### ISSUE TITLE
PUMA becomes unresponsive after a few minutes of being idle on Azure

### ISSUE THREAD

**Issue by t-anjan** [puma/puma#998]
The default keepalive time in Ubuntu is 7200 seconds (2 hours). 
Azure has a TCP session timeout of 4 minutes in its virtual networks.

Details of my setup:

* 1 VM running NGINX and PUMA. Puma is listening on a socket.
* 1 VM running MySQL database.
* The 2 VMs are not on the same (virtual) network. Puma connects to the DB via a public IP.
* Both VMs running Ubuntu 14.04.4, default install.

When the RoR app is left idle for more than 4 minutes, Puma stops responding. No error messages are thrown. Nothing but a blank page, waiting for the page to load. After exactly 10 minutes, the browser's timeout message appears. Restarting the Puma server made the app work again.

This is because the TCP session between Puma and the MySQL DB had been torn down by Azure after 4 minutes of idle time. 

This was solved by setting the `net.ipv4.tcp_keepalive_time = 60` in Ubuntu. I got this solution from Azure's tech support. This is also mentioned in this issue: https://github.com/puma/puma/issues/841 .

I had sent a bunch of TCPDump packet captures and log files (from both VMs) to Azure support over the last week or so to figure this out. They were very helpful throughout. I would be happy to share the same diagnostic files here if needed.

When they looked through the PCAPs, they mentioned the following:

---
START QUOTE

Looking at your packet capture, it appears that your App server(PUMA) sent some sort of keepalive after about 579 seconds of idle time, but got no response, and then kept trying to send them.

![unnamed1](https://cloud.githubusercontent.com/assets/743179/15927386/13122aae-2e5f-11e6-8280-69c51535d4de.png)

You can see from the capture on the DB side, that the last packet that made it through was the ACK with sequence number 37892, and the following Request Pings never made it through to the other machine.

![unnamed2](https://cloud.githubusercontent.com/assets/743179/15927412/2fdd3e08-2e5f-11e6-9e30-33d4c66d8c19.png)

Thus PUMA thinks the DB is down, but for some reason, isn’t smart enough to open a new TCP stream.  When you came along and restarted the daemon, that stream gets torn down on the app server, and a new TCP stream starts up. (which allows the web-app to work again).

END QUOTE

---

Now, for the questions.

* There should be a way to adjust Puma's own keepalive interval. What is it now, anyway? In [this issue](https://github.com/puma/puma/issues/957), a constant named `PERSISTENT_TIMEOUT` is mentioned, which is set to `20` in the [source code](https://github.com/puma/puma/blob/d2da2caf49932827f07994c8b65b1f99001c5fb9/lib/puma/const.rb#L111). So, is the keepalive interval 20 seconds? If yes, then the above problem should never have occurred.
* When Puma wasn't able to contact the DB anymore, why wasn't it throwing any error messages?
* When Puma wasn't able to connect to the DB anymore, why wasn't it automatically trying to open a fresh, new connection?

Although setting `net.ipv4.tcp_keepalive_time = 60` on Ubuntu solves the problem now, depending on the OS to send the keepalives seems like a hack to me. Any suggestions?

**Comment by evanphx** [comment]
This is an issue with your MySQL gem. There are no settings within puma that will help at all because none will influence how/when your MySQL gem makes connections. Are you using mysql2? /cc @brianmario

**Comment by t-anjan** [comment]
Yes, I am using the mysql2 gem.

I understand what you're getting at. You're saying that puma doesn't
connect directly to the DB at all. Neither does it maintain the connection
with the DB. It delegates that work to the mysql2 gem.

So, should I post this issue on the mysql2 github repo?

I should probably try the same setup with a postgres DB and the pg gem.

**Comment by brianmario** [comment]
@t-anjan I would be curious to see how the pg gem acts here.

Do you have any of the `read_timeout`, `write_timeout` or `connect_timeout` mysql2 options specified when creating the connection? It may be worth playing with those.

**Comment by evanphx** [comment]
This is an issue with how your database connections are managed and timed out.
