### ISSUE TITLE
Confusion w/ init.d on centos

### ISSUE THREAD

**Issue by kyledecot** [puma/puma#999]
When attempting to use the example init.d script found at https://github.com/puma/puma/blob/master/tools/jungle/init.d/puma#L29 I am getting an error when trying to load `/lib/init/vars.sh`. Where does this file come from? Is this created automatically via some package or do I need to create this?

**Comment by evanphx** [comment]
Thats a platform shell library basically. What version of centos?

**Comment by evanphx** [comment]
Ok, looks like the init script excepts lsb stuff and you're probably on a systemd release. So I need to add systemd scripts to have you use instead.

**Comment by evanphx** [comment]
We'll track adding systemd support in #1029. For now, I suggest you author your own systemd unit file.
